### ISSUE TITLE
Bokeh not rendering, stuck on Loading BokehJS [BUG]

### ISSUE THREAD

**Issue by cuspime** [bokeh/bokeh#10002]
Hi, 

Yesterday I had Bokeh version 0.12 or something like that running on windows 10 (so within Anaconda). I decided to upgrade to version 2.0.2 within the notebook using `!pip install bokeh --upgrade` and it seems to have been a terrible mistake. Now I cannot even plot the simplest things.
I do the imports as follows and try to plot just a simple line

```from bokeh.io import curdoc
from bokeh.models import Slider, ColumnDataSource, Button, Panel, Tabs, CategoricalColorMapper, HoverTool, Select
from bokeh.io import push_notebook,  output_notebook, reset_output
from bokeh.plotting import figure, show #, output_file
from bokeh.layouts import gridplot, row, column
from bokeh.palettes import Category10
# from bokeh.resources import INLINE
# import bokeh.io

# bokeh.io.output_notebook(INLINE)

from numpy.random import random
import sys


# output_notebook()
output_notebook()#hide_banner=True)  #Este comando se necesita para hacer el embedding the los plots!!!!!
```

This just gives `Loading BokehJS ...` and the jupyter cell moves on to the next one but it doesn't successfully loads Bokeh. 
Then, trying to run

```
p = figure()
p.line(x=[2,4,5,6,7], y=[3,4,5,7,9])
show(p) 

```
does nothing...

As you can tell I have already tried the solution `bokeh.io.output_notebook(INLINE)` but it just doesn't do the trick.

When running `!bokeh info` in the jupyter notebook I get:

```
Python version      :  3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
IPython version     :  7.6.1
Tornado version     :  6.0.3
Bokeh version       :  2.0.2
BokehJS static path :  c:\users\cuspi\anaconda3\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)```

I have tried this on Chrome, Firefox and Explorer. I do get a couple of errors in the JS console:
```VM40:258 Uncaught TypeError: Bokeh.set_log_level is not a function
    at inline_js (eval at append_javascript (outputarea.js:763), <anonymous>:258:13)
    at run_inline_js (eval at append_javascript (outputarea.js:763), <anonymous>:271:20)
    at eval (eval at append_javascript (outputarea.js:763), <anonymous>:293:7)
    at eval (eval at append_javascript (outputarea.js:763), <anonymous>:179:11)
    at Array.forEach (<anonymous>)
    at run_callbacks (eval at append_javascript (outputarea.js:763), <anonymous>:177:36)
    at HTMLScriptElement.on_load (eval at append_javascript (outputarea.js:763), <anonymous>:207:9)
```

```events.js:33 Exception in event handler for clear_output.CodeCell TypeError: Cannot use 'in' operator to search for '1002' in undefined
    at window._Events.handleClearOutput (eval at append_javascript (outputarea.js:763), <anonymous>:36:26)
    at window._Events.dispatch (jquery.min.js:2)
    at window._Events.y.handle (jquery.min.js:2)
    at Object.trigger (jquery.min.js:2)
    at window._Events.<anonymous> (jquery.min.js:2)
    at Function.each (jquery.min.js:2)
    at w.fn.init.each (jquery.min.js:2)
    at w.fn.init.trigger (jquery.min.js:2)
    at w.fn.init.events.trigger (events.js:31)
    at CodeCell.clear_output (codecell.js:544) Arguments(2) ["clear_output.CodeCell", {…}, callee: (...), Symbol(Symbol.iterator): ƒ]
```
 And finally:

```VM45:6 Uncaught TypeError: Cannot read property 'embed_items_notebook' of undefined
    at embed_document (<anonymous>:6:20)
    at <anonymous>:10:5
    at <anonymous>:26:3
    at window._Events.handleAddOutput (eval at append_javascript (outputarea.js:763), <anonymous>:76:60)
    at window._Events.dispatch (jquery.min.js:2)
    at window._Events.y.handle (jquery.min.js:2)
    at Object.trigger (jquery.min.js:2)
    at window._Events.<anonymous> (jquery.min.js:2)
    at Function.each (jquery.min.js:2)
    at w.fn.init.each (jquery.min.js:2)
```

To be honest, I don't know what they mean, if there is some problem with my installation, or with bokeh or what is going on.

**Comment by bryevdv** [comment]
Hi @cuspime Have you tried this with other browsers/OS yet, as suggested in the SO comments? Have you force-reloading the page, clearing cache, or loading in a private browser? The only way to make any progress on this problem that is specific to your situation is to narrow down what about your specific situation is causing the issue. What version of notebook do you have installed? Can you also try with Jupyterlab instead of classic notebook?

**Comment by cuspime** [comment]
yes, I have tried on Chrome, FireFox and Explorer. Haven't tried with another OS since I don't really have other OS. I have reloaded the page, closed it, restarted the terminal, cleared browser cache, private browser

I have version 6.0.0 of jupyter and the program didn't render on jupyterlab either.

**Comment by bryevdv** [comment]
Really not sure what could be different on your system. Here is Win 10, Chrome, notebook 6.0.3 and Bokeh 2.0.2 just now:

<img width="1125" alt="Screen Shot 2020-05-09 at 4 04 32 PM" src="https://user-images.githubusercontent.com/1078448/81487092-fe305800-920e-11ea-86d3-6adc3a36939b.png">

Do the live mybinder tutorials work for you? 

https://mybinder.org/v2/gh/bokeh/bokeh-notebooks/master?filepath=tutorial%2F00%20-%20Introduction%20and%20Setup.ipynb

**Comment by bryevdv** [comment]
Well, I guess let's also take a step back and verify assumptions. What is the value of `bokeh.__version__` inside the notebook? Also, do examples outside the notebook work? e.g. running any of the plain python scripts here:

https://github.com/bokeh/bokeh/tree/master/examples/plotting/file

**Comment by cuspime** [comment]
The tutorials are working!! doing boke._version__ gives me 2.0.2

The link you sent 
[https://docs.bokeh.org/en/latest/docs/gallery/hex_tile.html](https://docs.bokeh.org/en/latest/docs/gallery/hex_tile.html)

does render and I can move the plot around

**Comment by p-himik** [comment]
@cuspime You have used `pip` in a `conda` environment. Sometimes it can mess things up. I would attempt to recreate the environment with Bokeh 2.0.2 and void using `pip`.

**Comment by cuspime** [comment]
I was able to solve the problem! Thanks @p-himik. In the end I [created a new environment](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/environments.html) all from within the anaconda prompt and was able to load bokeh. Now everything is back to normal. 
I guess pip did messed things up.

**Comment by bryevdv** [comment]
@p-himik  can you elaborate? I always test Bokeh pip packages by pip installing them into conda simple conda envs. That always works for me and, more importantly, should work. Do you suppose this is specifically when pip installing over an already existing conda install? I guess I wouldn't be too surprised if that specifically could be problematic, but would also wonder what could be done to improve things if that is that case.

**Comment by p-himik** [comment]
> Do you suppose this is specifically when pip installing over an already existing conda install?

I think that's it, yeah. I don't remember having issues when using `pip install` with packages that aren't in any conda channel, so it's either installing or upgrading with pip over an existing conda package, or maybe vice versa.

**Comment by teebr** [comment]
I've also run into this problem recently, on a Macbook (Catalina) and a machine running Ubuntu 18. Below is more of an info dump rather than anything concrete; if I get any further I'm happy to re-open this or create a new issue.

In both cases I use a virtual environment, and there's no Conda install. 

Notebooks tend to work fine for a while, then suddenly can't load, with the same `set_log_level` error as above. I had it just now on OSX with Firefox and Chrome, but when I tried Safari, it worked fine. However, when I use `nbconvert --to html` the output went back to not loading, and now Safari doesn't work either. 

On my Linux machine I did try rolling back to a slightly older version of Python Bokeh (still version 2. something) but that didn't change anything. Just now, I tried changing the CDN version for `output_notebook` to `2.0.0`, and then it loaded. Now, if I try and load `INLINE` or a newer CDN version, the cell output is still `BokehJS 2.0.0 successfully loaded.` 

As things stand, from using `jupyter nbconvert --execute my_notebook --to html` seems to reliably work with `2.0.0` but often doesn't work with `2.1.1`.

For OS X:
```
Python version      :  3.7.3 (default, Dec 13 2019, 19:58:14)
IPython version     :  7.16.1
Tornado version     :  6.0.4
Bokeh version       :  2.1.1
node.js version     :  v14.4.0
npm version         :  6.14.4
```

**Comment by bryevdv** [comment]
@teebr the most helpful things in these situations will probably be from the browser dev tools:

* messages in the js console?
* issues/failed loads in the network pane?

>  Now, if I try and load INLINE or a newer CDN version, the cell output is still BokehJS 2.0.0 successfully loaded.

I would expect at least it would be necessary to clear all output cells in the notebook. But I also don't understand: are you specifying BokehJS 2.0 with a *different* python version imported? If so that is not supported and not expected to work.

**Comment by SarahOst** [comment]
This issue might be related to this one: [No output in jupyter notebook -suddenly #463](https://github.com/holoviz/hvplot/issues/463).

In the linked issue you can find a compressed notebook. Bokeh wasn't successfully loaded in a jupyter notebook (via holoviews). I could reproduce the error (including java script console output) with that notebook and "got it working again" with changing the markdown cell "# Bokeh" to ''# anything else"

At my own notebook I faced the same problem when importing bokeh (not holoviews) and having this kind of markdown cells.

**Comment by mattpap** [comment]
The problem boils down to this:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>color_scatter.py example</title>
  </head>
  <body>
    <div id="FooBarBaz">Foo Bar Baz</div>
    <script type="text/javascript">
      if (typeof window.FooBarBaz !== "undefined") {
        const text = document.createTextNode(`window.FooBarBaz == ${window.FooBarBaz} with "${window.FooBarBaz.textContent}"`)
        document.body.appendChild(text)
      }
    </script>
  </body>
</html>
```
i.e. setting `id` on an element, creates a global variable with the same name as the ID. Whenever I think that web browsers can't sink any lower, then there's another day to prove me wrong.

Jupyter exposes this behavior, as it converts e.g. `# Bokeh` Markdown markup into `<h1 id=Bokeh>Bokeh</h1>`, which in turn defines `window.Bokeh = (... ref to h1 node ...)`, which conflicts later with initialization of bokehjs.

> error doesn't happen with Bokeh 1.4.1, but with 2.0 and 2.1 (I didn't test with other versions in between)

This is because starting with bokeh 2.x, it's now possible to load multiple versions of bokehjs into a page without any additional setup, but this seems not to work well, when `window.Bokeh` is clobbered with an unrelated object. Previously `window.Bokeh` was just overwritten, so the issue wasn't visible. This is something that we can improve. 

I also think that Jupyter's behavior could be improved, by not generating simple IDs from content (at least use `jp-` prefix).

**Comment by teebr** [comment]
Thanks everyone -  I can confirm that I had a `# Bokeh` markdown cell in my notebook, changing that seems to have fixed my problems 😿

**Comment by Sidney-Bishop** [comment]
Hi folks,

I've encountered a similar problem on MAC OS Big Sur 11.2 ( see screen grab below )

However, I don't have any markdown code mentioning Bokeh but still get the following error:

"Javascript error adding output!
TypeError: o is not a function
See your browser Javascript console for more details."

Python version      :  3.8.5 (default, Sep  4 2020, 02:22:02) 
IPython version     :  7.19.0
Tornado version     :  6.0.4
Bokeh version       :  2.2.3

I get the same error in Jupyter Lab.

Any suggestions would be appreciated. 

Best Jason

<img width="1401" alt="Screenshot 2021-03-29 at 19 19 17" src="https://user-images.githubusercontent.com/7266636/112884552-89d10280-90c7-11eb-8446-ef0f98c88eb3.png">
