### ISSUE TITLE
[BUG] Model.serializable_attributes method removed in Bokeh master

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#10126]
In bokeh master and therefore the coming release the `Model.serializable_attributes` method has been removed without warning as far as I can tell. We use this method in Panel in crucial codepaths and this currently breaks Panel entirely. I'd be happy to migrate to a different codepath, however I would prefer if there was at least a deprecation cycle here.

Cc: @mattpap @bryevdv

**Comment by mattpap** [comment]
I see only one code path. I actually checked at the time of removal that panel and related libraries libraries didn't use the removed APIs. However, it took a while to finish the PR, which is when the code path in panel was added. I'm fine with restoring this method for the time being. We also really need to set up a combined test suite to catch such issues earlier.

**Comment by philippjfr** [comment]
Thanks, what is the recommended equivalent API that's replaces it so I can patch that asap and we can actually deprecate it?

**Comment by mattpap** [comment]
I restored and deprecated this method in PR #10127. The replacement depends on the use case. The code in panel:
```ts
!(event.attr in event.model.serializable_attributes())
```
which btw. is pretty inefficient, because you're iterating an entire model for a single attribute, would be repaced with:
```ts
!event.model.property(event.attr).syncable
```
In general I'm moving away from using string attributes, in favour of fully embracing properties.

Also note the new terminology. A property is syncable, because something serializable isn't necessarily syncable, but syncable must be serializable.
