### ISSUE TITLE
GitGuardian CI job often fails on `master`

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#10169]
For example https://github.com/bokeh/bokeh/runs/771002039. I hope they don't expect us to `push --force` to `master`.

**Comment by bryevdv** [comment]
@mattpap Can you explain more thoroughly what circumstances led to seeing this?  This seems to be due to the previous leak which already have had all keys rotated (thankfully.. but this shot me out of bed this morning) but I have never once seen this where their checks "re-fail". If there are details I can report to them they seem fairly responsive.

**Comment by bryevdv** [comment]
@mattpap I guess this would happen anytime a check is run against master. How did you even get alerted to this? I don't see it on the actual GG site (maybe I am just missing it) and all I've seen are the PR checks (which is why I never saw it before because it never shows up there). I would say for now it's just something to explicitly ignore and I can raise the issue with them.

**Comment by mattpap** [comment]
I'm monitoring https://github.com/bokeh/bokeh/commits/master looking for spurious failures, to improve reliability of our tests eventually. I would expect that every commit to `master` would fail, but GitGuardian's job fails just once in awhile. However, it seems that the job actually always fails, but that failure isn't reported reliably. For example this https://github.com/bokeh/bokeh/runs/747492502 failed and was neutral at the same time. GitGuardian checks last 250 commits, so this problem will eventually go away on its own.

**Comment by bryevdv** [comment]
>  GitGuardian checks last 250 commits, so this problem will eventually go away on its own.

In that case I would say it's just something to ignore until then. With the checks on PR we should be able to avoid anything getting committed to master in the future, which is the most important thing anyway.
