### ISSUE TITLE
set timeout for automatic closing of the tooltip in hovertool bokeh[FEATURE]

### ISSUE THREAD

**Issue by NandhiniS08** [bokeh/bokeh#10389]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh Project Discourse](https://discourse.bokeh.org).

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bryevdv** [comment]
I'm going to go ahead and close this for now since none of the template was filled out. @NandhiniS08 If you'd like a feature to be considered, we need more information, e.g.

* a more thorough description of the ask
* example of code/API that you would like to be available 
* comparisons to other projects, does this exist anywhere else?
* Why this is needed, what use cases does this enable?

The hover tool is already very complicates, so we would  definitely want to justify adding even more complexity to it.
