### ISSUE TITLE
[BUG] Select is not updated upon setting value after changing the options

### ISSUE THREAD

**Issue by harmbuisman** [bokeh/bokeh#10407]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.1.1

python           : 3.7.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362

#### Description of expected behavior and the observed behavior
When I dynamically change the options of a Select component and then update the value, the UI is not reflecting the selected value.

Run the code below where I update the options and at the same time change the value. The value is changed in the background, since it is printed out, but it is not reflected in the UI. The select always shows the first option in the options list, even though select.value is set to "A".

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.models import Button, Select
from bokeh.plotting import curdoc
from bokeh.events import ButtonClick

select = Select(title="Selection:", value='A',
                options=['A', 'B', 'C', 'D'])
# div = Div(text='Nothing selected')
button1 = Button(label='Show selection')
button2 = Button(label='Change options')

def click_button1():
    print("Selected: ", select.value)

def click_button2():
    select.options = select.options[1:] + [select.options[0]]
    print("Changed options to:", select.options)
    select.value = 'A'
    print(f'Setting value to {select.value}')

button1.on_event(ButtonClick, click_button1)
button2.on_event(ButtonClick, click_button2)

curdoc().add_root(select)
curdoc().add_root(button1)
curdoc().add_root(button2)
```

#### Stack traceback and/or browser JavaScript console output
Selected:  A
Changed options to: ['B', 'C', 'D', 'A']
Setting value to A
Selected:  A
Changed options to: ['C', 'D', 'A', 'B']
Setting value to A
Selected:  A

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/7702207/90492339-5eedfb80-e141-11ea-92a7-adb252411f30.png)

**Comment by mattpap** [comment]
I can't reproduce this anymore on 2.2 branch. Or perhaps I misunderstood this issue earlier and didn't actually reproduce it.

**Comment by harmbuisman** [comment]
@mattpap , that would be great if it is fixed. 

I just noticed also a related issue, which may have the same root cause. Is thar also not reproducible anymore?

If I do not set the value, but just the options, the value does not change, while the selected value in the UI gets a new value.
In the example below I would expect that after setting options to 1, 2, 3, that select.value is autoset to 1 as that is the value visible in the UI, but it remains at A:

```
from bokeh.plotting import curdoc
from bokeh.events import ButtonClick
from bokeh.models import Button, Select

select = Select(title="Selection:", value='A',
                options=['A', 'B', 'C', 'D'])

button1 = Button(label='Show selection')
button2 = Button(label='Change options')

def click_button1():
    print("Selected: ", select.value)

def click_button2():
    select.options = ['1', '2', '3'] if not ['A'] in select.options else ['A', 'B', 'C', 'D']
    print("Changed options to:", select.options)
    print(f'Value is {select.value}')

button1.on_event(ButtonClick, click_button1)
button2.on_event(ButtonClick, click_button2)

curdoc().add_root(select)
curdoc().add_root(button1)
curdoc().add_root(button2)

```

![image](https://user-images.githubusercontent.com/7702207/90650292-ff284b00-e23b-11ea-80ea-49a99a780e30.png)

**Comment by brycepg** [comment]
Here's an example of the UI select value becoming unset after options change:

```python3
from bokeh.io import curdoc
from bokeh.models import Select, Toggle
from bokeh.layouts import row

options = ["1", "2", "3"]
select = Select(
    title="mycallback",
    value="2",
    options=options,
)
toggle = Toggle()


def myclick(*args):
    select.options = ["1", "2"]


toggle.on_click(myclick)
curdoc().add_root(row(select, toggle))
```

Note that the value should be 2 always, but when the options select is reset by clicking "toggle", the value (in the UI) shows the first option. I tested this on bokeh `2.2.0`

---

I found a workaround @harmbuisman :
Instead of setting the select options attribute to a new list, keep the old list clear it and extend the new values:

```python
select.options.clear()
select.options.extend(value_seq)
```

**Comment by harmbuisman** [comment]
> 
> 
> I can't reproduce this anymore on 2.2 branch. Or perhaps I misunderstood this issue earlier and didn't actually reproduce it.

The bug is still there in 2.2.1. 

Steps:
* start server
* click show selection
* click change options
* click show selection

output:
![afbeelding](https://user-images.githubusercontent.com/7702207/92387603-2032dc00-f116-11ea-953d-9eafe72be013.png)

expected output:
The last two lines should print out 1 instead of A


@brycepg 
Thanks for the suggestion. I tried to replace the first line in click_button2 to:
    new = ['1', '2', '3'] if 'A' in select.options else ['A', 'B', 'C', 'D']
    select.options.clear()
    select.options.extend(new)
But this does not work either, it always prints A.

**Comment by brycepg** [comment]
You're right @harmbuisman I was wrong about that workaround. It preserves current select UI but does not update the options UI list.

I think the root cause of my issue and your issue are the same @harmbuisman . When `options` attribute is changed on a `Select` widget, the UI select value resets to the first item in the `options` list, and does not reflect the bokeh server internal model value. 

### The UI selected option for a `Selection` should not reset when the `options` attribute is set to a new list.

A secondary issue you have @harmbuisman is that setting the `value` attribute does not do anything if your are setting it to the same value.

### The Workaround

A workaround I realized was to clear the value attribute and then set it to the same value again make sure the bug does not creep in:

    select.value = ""
    select.value = 'A'

Adding the above line to your initial example appears to be a clear workaround. (I tested it)

If one has a callback on the `Select` widget for on_change `"value"`, one may want to temporarily disable the callback when doing this to prevent potential issues.

**Comment by harmbuisman** [comment]
@brycepg, thanks, that is very helpful!
