### ISSUE TITLE
[BUG] server_session is completely broken 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10412]
Neither `embed/arguments` or `embed/server_session` function at all (tested on linux and OSX)

Edit: Also all the `howto/server_embed` examples

![image](https://user-images.githubusercontent.com/1078448/90593937-14e73300-e19e-11ea-9556-4baf518a340e.png)

**Comment by mattpap** [comment]
The underlying problem is that `AutoloadJsHandler` uses `None` as empty `docs_json`, instead of `{}`. This didn't surface until recently, after PR #10338, which replaced for-in loops with `entries()`. Originally for-in loop allowed `null` argument, e.g.:
```
$ node
Welcome to Node.js v13.13.0.
Type ".help" for more information.
> let i = 0; for (const x in null) i++; i
0
```
I would expect an exception, but perhaps I'm just projecting Java's behavior on JavaScript.
