### ISSUE TITLE
[BUG]Reverse Y axis range with circle 

### ISSUE THREAD

**Issue by ruoyu0088** [bokeh/bokeh#10457]
Bokeh 2.2.1

Here is the source code

```python
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource
from bokeh.layouts import row
from bokeh.colors import RGB

source = ColumnDataSource(data=dict(
    x = [0, 50, 100],
    y = [0, 50, 100],
    r = [20, 20, 20],
    c=['red', 'green', 'blue']
))

fig1 = figure(match_aspect=True, aspect_ratio=1, width=400, x_range=(0, 100), y_range=(0, 100))
fig1.circle('x', 'y', radius='r', source=source, line_color='black', fill_color='c', alpha=0.5)

fig2 = figure(match_aspect=True, aspect_ratio=1, width=400, x_range=(0, 100), y_range=(100, 0))
fig2.circle('x', 'y', radius='r', source=source, line_color='black', fill_color='c', alpha=0.5)

layout = row(fig1, fig2)
show(layout)
```

and the output figures:

![tmp](https://user-images.githubusercontent.com/826871/92068363-b054e680-ede1-11ea-97a5-4aadd0813a31.png)

the right figure has some circles disappeared, and if you pan the right figure view range, you can see some circles and the edge always shown and hidden.

**Comment by bryevdv** [comment]
@ruoyu0088 Thanks for the report. Can you possibly try to construct an MRE that does not use random data?  We will need to make sure a test is in place for the fix for this and will need a completely reproducible test case. 

@bokeh/core offhand the only thing that comes to mind is the making based on spatial indexing is malfunctioning somehow when ranges are reversed. I would not be opposed to simply turning that off if `radius` is used instead of `size` (AFIAK I *think* circles and markers  are the only glyph to implement masking at all)
