### ISSUE TITLE
issue a warning when LogColorMapper is used with negative values

### ISSUE THREAD

**Issue by 816-8055** [bokeh/bokeh#10477]
Currently the warning can be found in the documentation. But no warning is thrown, when negative values are plotted as image with an LogColorMapper.

bokeh: 2.2.0

Solution: throw warning in code

**Comment by bryevdv** [comment]
@816-8055 Are you asking about a warning on the Python side? If so, that is not possible, because the colormapping does not happen in Python. It is done by JavaScript code, *in the browser*. We could potentially add a JavaScript `console.log` error message, and I would not turn down a PR that did this, but to be completely hones, most users do not know about the JS console or how to access it, so warnings in the JS console are extremely limited.

**Comment by bryevdv** [comment]
For reference, this is the relevant file for anyone who wants to look at guarding all the calls to `log` and printing JS console warnings if there is an error:

https://github.com/bokeh/bokeh/blob/branch-2.3/bokehjs/src/lib/models/mappers/log_color_mapper.ts

Tho thinking even more I think I am 👎 on adding this. If log is called with a negative number then an error message will end up in the console anyway. I am not sure there is any benefit to us adding code and complexity for simply printing a *different* message. 

@816-8055 if you want/need assurances on the Python side, the best bet for you is to colormap the data yourself so that you have full control/visibility, and then explicitly send the colors to bokeh.
