### ISSUE TITLE
[FEATURE] Hiding hex number from color swatch in hover tool

### ISSUE THREAD

**Issue by tmikolajczyk** [bokeh/bokeh#10506]
It'd be nice to have an option to hide hex number from the hover. Swatch is a great option, but sometimes there is no need to share a information about the HEX. Inspired by the discussion [here](https://discourse.bokeh.org/t/hiding-hex-number-from-hover-tool-swatch/6324).

![image](https://user-images.githubusercontent.com/10706421/93608900-76800480-f9cb-11ea-9f8b-4a6bb914c93d.png)

**Comment by bryevdv** [comment]
This is supposed to be possible (used to be possible) by specifying  e.g.
```
$color[swatch]:fill_color"
```
but AFAICT it is currently not respecting that configuration. @tmikolajczyk can you confirm that it also does not work for you?

**Comment by tmikolajczyk** [comment]
@bryevdv, yes I confirm that hiding hex does not work for me

**Comment by mattpap** [comment]
> This is supposed to be possible (used to be possible) by specifying (...)

As far as I can tell (at least going back to 2017), this hasn't been possible and adding `hex` only means to convert a CSS color spec to hex representation, but color string regardless of representation is non-optional (swatch is). Changing the existing behavior would be a breaking change, so I would add another special variable `$swatch:field_name` to resolve this.

**Comment by gaurlakshya** [comment]
Hey @tmikolajczyk  i want to work on this issue. I am a totally new to open source contribution world and i want to make a start by solving this issue.

**Comment by MarkSachinPerera** [comment]
Hey, I am new to the project and I would like to take a crack at this.

**Comment by bryevdv** [comment]
@MarkSachinPerera Contributors come in with lots varying experience, please let us know where we can help with any guidance as you start taking a look.

**Comment by MarkSachinPerera** [comment]
Thanks! ill let you know if i need help 😄

**Comment by MarkSachinPerera** [comment]
Link to new code: https://github.com/MarkSachinPerera/bokeh/commit/3df6917a8fa1d5d954eefa70c32990c2b391c1ac

So running this piece of code: 

```
source = ColumnDataSource(data=dict(
    x=[1, 2, 3, 4, 5],
    y=[2, 5, 8, 2, 7],
    color=['red', 'red', '#1f9ca7', '#0ea2e9', '#01e3ed']
))

p = figure(plot_width=400, plot_height=400, tooltips=[("fill color", "$color[swatch,hideColorValue]:color"),],
           title="Mouse over the dots")

p.circle('x', 'y', size=20, source=source, color='color')
```

Here the new `hideColorValues` option will hide any text (string  representation or hex representation) from the fill color tag. 

Some screen shots:
![image](https://user-images.githubusercontent.com/34218455/100530102-136cd400-31ab-11eb-958b-52bbdfec0eea.png)

![image](https://user-images.githubusercontent.com/34218455/100530110-27183a80-31ab-11eb-8499-8dc0fd86e146.png)


Is this solution valid?

Because I was unsure what this comment meant?

> so I would add another special variable $swatch:field_name to resolve this.

**Comment by bryevdv** [comment]
@MarkSachinPerera My interpretation of the above is to allow:
```
$color:fieldname      # display the color value as-is (no swatch) 
$color[hex]:fieldname # display the color value hex-formatted (no swatch)
$swatch:fieldname     # display a swatch for fieldname (no color value)
```
This decouples swatch inclusion from color string formatting. So for compatibility, this should still work:
```
$color[swatch,hex]:fieldname  # display color value hex-formatter, and a swatch (current behavior)
```
but we can deprecate that usage, and encourage this instead:
```
$color[hex]:fieldname $swatch:fieldname
```

**Comment by MarkSachinPerera** [comment]
ahh okay. I will update this accordingly.

**Comment by MarkSachinPerera** [comment]
Link: https://github.com/MarkSachinPerera/bokeh/commit/e9a12947684acfa445f3e1ed7a149dd295c4da34


I updated the code as requested. I defined a new special variable called "swatch" which decouples the swatch functionality from the color field. Now, you can add the swatch element to any field you want.  In addition, the code is backwards compatible so that the swatch option continues to work for the color field. For bad input handling, I was not sure what the preferred behavior is. Right now, I hide the swatch element and just display text.

I can update the documentation if the behavior looks good. In terms of testing, I looked around and couldn't finding existing tests for testing specific special variables used in the hover_tool. Do we need tests for this case?

Test program: 

```
import numpy as np

from bokeh.io import curdoc
from bokeh.layouts import column, row
from bokeh.models import ColumnDataSource, Slider, TextInput
from bokeh.plotting import figure


source = ColumnDataSource(data=dict(
    x=[1, 2, 3, 4, 5],
    y=[2, 5, 8, 2, 7],
    color=['red', 'red', '#1f9ca7', '#0ea2e9', '#01e3ed']
))

p = figure(plot_width=400, plot_height=400, tooltips = [
    ("(x,y)", "($x, $y)"),
    ("fill color", "$color[hex,swatch]:color, $swatch:color"),
    ("swatch", "$swatch:color")
],
           title="Mouse over the dots")

p.circle('x', 'y', size=20, source=source, color='color')


curdoc().add_root(p)
curdoc().title = "Sliders"
```

Example 1:
![image](https://user-images.githubusercontent.com/34218455/100676169-987bf880-3325-11eb-8417-41329d2fe175.png)

Example 2:
![image](https://user-images.githubusercontent.com/34218455/100676187-a2056080-3325-11eb-974a-5550e8b8549f.png)
