### ISSUE TITLE
Missing an example on how to code interactions between map and scatter plots

### ISSUE THREAD

**Issue by PBrockmann** [bokeh/bokeh#10540]
I would find very useful to find in the documentation a clean example with all callbacks properly set to produce a minimal dashboard where a map and a scatter plots are linked.

With links, I mean:
- when the map moves the corresponding geo-referenced points of the scatter plot are drawn accordingly,
- when points either from the map or from the scatter plot are selected from a lasso or box select then the other plot presents only selected points.

I have started a demo available from https://gist.github.com/PBrockmann/44f69779de55d1fe69a2232bdd1d4c09

Mostly works as expected except that with a selection I would like to use a visible property for points rather than rebuild the variables. That would make possible the return to the initial state.
This problem is visible in the demo when you select from the scatter plot then click on reset. You do not retrieve all the points whereas the selection on the map let you see selected points and also unselected points (lower opacity). A click on the reset, retrieve in this case the initial state.

![a](https://user-images.githubusercontent.com/5402758/94842749-0be3b580-041c-11eb-8b38-10f4432190d2.png)

**Comment by bryevdv** [comment]
> when the map moves the corresponding geo-referenced points of the scatter plot are drawn accordingly,

This sounds like you want linked ranges, which is documented here:

https://docs.bokeh.org/en/latest/docs/user_guide/interaction/linking.html#linked-panning

> when points either from the map or from the scatter plot are selected from a lasso or box select then the other plot presents only selected points.

There are a number of ways to have a first plot drive a second plot this way, and some of them are demonstrated in the docs as well:

* have a selection callback update a CDS view filter on the second plot
* have a selection callback literally copy data from a "ground truth" CDS to the CDS that drives the glyph
* have a selection callback update the opacity column of the CDS for the second plot
* have a selection callback update the selection on the second plot programmatically. 

There is not one right example to provide, it depends on what you actually want to do and the constraints of your actual use-case. 

Having both plots react mutually is, I am afraid, a more difficult proposition. Bokeh is a reactive/event system, so you have to contend with the ping pong problem: "plot A updates plot B updates plot A updates plot B...". There might be some way to accomplish it, but since that is a specialized and unusual ask that will have an involved solution (if there is a solution)  it's not something we would want to distract users with in the docs. That discussion is [better left to a support forum](https://discourse.bokeh.org).

>  a clean example with all callbacks properly set

Interpreted literally, this is simply not practical. Every single Bokeh property (of which there are hundreds if not thousands) can have a python or js (or both) callback set on it. The best we can ever hope for is to describe the general principles that apply everywhere, i.e what properties  do what, and how to hook up callbacks to any of them, and illustrate those principles with a few selected concrete examples.
