### ISSUE TITLE
[FEATURE] 'transparent' as an alias for `rgba(0, 0, 0, 0)`

### ISSUE THREAD

**Issue by yportier** [bokeh/bokeh#10576]
**Is your feature request related to a problem? Please describe.**

`color=None` usually does the job at specifying 'no color' or 'fully transparent' color
However, inside mappers such as `ColorLinearMapper` for instance, setting `high_color=None` or `low_color=None` will not result in using 'no color' but will default to extending the map to higher/lower values.

**Describe the solution you'd like**
A simple solution would be to follow Matplotlib's pattern of allowing 'none' as a color and where `color=None` clearly means 'apply default behavior' and `color='none'` means 'no color'.

**Describe alternatives you've considered**
Granted, it's easy enough to specify `low_color='rgba(0, 0, 0, 0)'` but a simple alias would be cleaner IMHO.
`'none'` and `None` can also introduce confusion but in most cases they would be fully substitutable. 'nocolor' could also be considered for the alias name.

**Comment by mattpap** [comment]
`low_color`/`high_color` are defined inconsistently with the rest of bokeh, because in all other cases `None` means no color (or skip rendering). The current meaning of `None` should have been implemented under `"auto"` or something like that. Note that `none` is not a valid CSS color keyword, so perhaps `transparent` would make more sense (given that color are modeled after CSS spec), but that's not supported either.

**Comment by bryevdv** [comment]
I'm not opposed to changing this in the way described but it would have to be at Bokeh 3.0 since it is a breaking change.

**Comment by mattpap** [comment]
PR #10677 adds support for `transparent` keyword.
