### ISSUE TITLE
[FEATURE] Add a `PythonCallback` similar to `CustomJS`

### ISSUE THREAD

**Issue by erezinman** [bokeh/bokeh#10571]
Add a new model to allow a python-side callback that's called from the browser. If this is possible, I didn't find any way to do that in the docs.
Note that this can also simplify the event-mechanism as there will not be longer be a need for both `on_event` and `js_on_event`.

Looking briefly on the code, I have an implementation suggestion (tell me what you think about it):
In the python side, it just wraps a callback.
On the browser side, this could be implemented by triggering a new type of event on calling `CallbackLike<..>.execute`, which, in turn, triggers a wrapper in the python-side that calls the given callback.

**Comment by philippjfr** [comment]
Could you explain how this would be functionally any different from just using `on_event` directly?

**Comment by erezinman** [comment]
There are places where just the JS functionality is implemented. For example, the `CustomActionTool`, where only a JS action is implemented. There might be other places.
You could add a server-side implementation for the event  (for instance, call the `ButtonClick` event every time the tool is clicked), but I think that both implementations have similar complexity.

**Comment by philippjfr** [comment]
>You could add a server-side implementation for the event (for instance, call the ButtonClick event every time the tool is clicked), but I think that both implementations have similar complexity.

Similar complexity at the implementation level maybe, but it would be adding another mechanism for defining events which adds user-level complexity. If the proposal is to replace/unify event system that's worth discussing but I'm definitely -1 on adding another mechanism without that and on balance I'd also vote to keep the current event system.

So I'd argue that we should just add the equivalent Python events using the existing mechanism in the places they are missing.

**Comment by erezinman** [comment]
My suggestion is just to allow a simple client2server callback that can be used throughout the system. My suggestion is not to replace the events mechanism - I simply note that it would be possible if such a callback is implemented.

Also, passing a callable as a callback is much simpler user-wise than to register to an event.

**Comment by erezinman** [comment]
Also, all the tools that have a `callback` property (there are quite a few), could be used with such a callback. I think implementing such a callback (especially if it's not complicated to do so) is the more elegant solution.

**Comment by bryevdv** [comment]
* It's more complicated, not less. You can just currently define a function and pass to `on_event` with no imports. To use some `PythonCallback` you have to: import it, define a function and configure it, or subclass is and define a method, then configure that result on the model. That is strictly always more work, not less (and more and more ways to have to document)

* This could only work with a Bokeh server because the Bokeh server *is the Python process*  that will execute python code. (I hope that is understood here but I am not sure). It cannot work at all with standalone output (i.e. `output_file` + `show`) but it seems like it would be very easy for users to be confused on this point, which directly translates into an inctreased support burden. 

> Also, all the tools that have a callback property (there are quite a few),

There are only three  *left*. `CustomAction`, `TapTool`, and `HoverTool` It used to be the case there there were lots but the plan (which has been ongoing) is to get rid of all of them and have only the one consistent `on_event`  / `js_on_event`. These will all be deprecated some day. 

This is duplicative of existing functionality but will require more work to develop, maintain, document, and explain. We should continue the work to unify everything event-related under common `on_event` / `js_on_event` which is easier to explain via parallel comparison. If we need *new* events, we can add them. But I am a strong -1 on a  different`PythonCallback` that needs to be maintained (and explained) differently. .

**Comment by bryevdv** [comment]
FYI I will go ahead and close this with `noaction` if others feel strongly please make a case to re-open
