### ISSUE TITLE
[BUG] 2.3.0dev2 introduced an erroneous dependency on "python_abi 3.9.* *_cp39"

### ISSUE THREAD

**Issue by rstrutt** [bokeh/bokeh#10603]
Noted on discourse [here](https://discourse.bokeh.org/t/is-2-3-0dev2s-dependency-on-python-abi-3-9-intentional/6594).

2.3.0dev2 introduced an erroneous dependency on "python_abi 3.9.* *_cp39"/
2.3.0dev1 does not have this dependency.

Examining the anaconda artifact [here](https://anaconda.org/bokeh/bokeh/files), shows the dependency;

![image](https://user-images.githubusercontent.com/7271339/97190684-68689500-177c-11eb-98ac-2edad1324e9c.png)

**Comment by bryevdv** [comment]
Will require some investigation to determine whether this was some change on our end (I don't _think_ so) or something on the conda side of things. FWIW 2.2.3 does not exhibit this extra dependency.

**Comment by bryevdv** [comment]
This seems potentially relevant: https://github.com/conda/conda-build/issues/3956 I wonder if the build env picked up `conda-build` from conda-forge instead of defaults

**Comment by bryevdv** [comment]
Unfortunately the [full build logs](https://pipelines.actions.githubusercontent.com/ulO0VbHVmvhg5sIouatb8EE0BHOKrnPm4eEAD0pcj0jqeytZcZ/_apis/pipelines/1/runs/3394/signedlogcontent/3?urlExpires=2020-10-26T23%3A10%3A03.3596561Z&urlSigningMethod=HMACV1&urlSignature=gJzeOZ20Db%2BRVEL0GwJMiXfmgj7Dwy1gmkMxVQ3%2BRHY%3D) do not shed light on where `conda-build` was installed from since the GH action handled things. However, [environment-release-build.yml](https://github.com/bokeh/bokeh/blob/branch-2.3/ci/environment-release-build.yml) does currenty att `conda-forge` as a channel even though I don't think there is anything we specifically require from there.  

As a first step I will try just removing `conda-forge` from the release-build env

**Comment by bryevdv** [comment]
OK, upping to the lastest `conda-build` seems to have resolved:

<img width="955" alt="Screen Shot 2020-10-27 at 2 34 30 PM" src="https://user-images.githubusercontent.com/1078448/97364650-9673d500-1861-11eb-814b-b9d866c9f71c.png">

**Comment by rstrutt** [comment]
Excellent!  Thanks for tracking it down Bryan.
