### ISSUE TITLE
[FEATURE] Collapsible figures in layouts

### ISSUE THREAD

**Issue by Felix-neko** [bokeh/bokeh#10642]
Hi folks! I often use layouts with dozens of plots on them.

Can you make an option to make some plots collapsible (maybe with an option to make a figure collapsed by default)?

---
P.S. Thank you for great product, it really rocks = )

**Comment by bryevdv** [comment]
HI @Felix-neko sorry this issue got overlooked until now. We would need more information in order to consider acting on a new feature. For instance, plots already have a `visible` property that can be used to show or hide them. Are you asking for something different? If so, then please describe the interaction you are looking for in more detail, provide some mock up drawings, etc. to help us understand what you are proposing.

**Comment by bryevdv** [comment]
Closing for lack of update. We can consider re-opening if/when additional information is provided.
