### ISSUE TITLE
Clarify and alias(?) Plot's various width attrs

### ISSUE THREAD

**Issue by hyles-lineata** [bokeh/bokeh#10664]
A review of [Plot](http://docs.bokeh.org/en/latest/docs/reference/models/plots.html?highlight=plot#bokeh.models.plots.Plot) shows that it has the following width-related attributes and descriptions:
- `frame_width`: The width of a plot frame or the inner width of a plot, excluding any axes, titles, border padding, etc.
- `inner_width`: This is the exact width of the plotting canvas, i.e. the width of the actual plot, without toolbars etc. Note this is computed in a web browser, so this property will work only in backends capable of bidirectional communication (server, notebook).
- `max_width`: Maximal width of the component (in pixels) if width is adjustable.
- `min_width`: Minimal width of the component (in pixels) if width is adjustable.
- `outer_width`: This is the exact width of the layout, i.e. the height of the actual plot, with toolbars etc. Note this is computed in a web browser, so this property will work only in backends capable of bidirectional communication (server, notebook).
- `plot_width`: The outer width of a plot, including any axes, titles, border padding, etc.
- 'width': The width of the component (in pixels). This can be either fixed or preferred width, depending on width sizing policy.

The last of these, regular `width`, does not appear to do anything. Even when passing `width` in as an argument to `figure()`, that value actually becomes `plot_width`; testing shows that the `width` attribute stays as `None`. It's probably worth mentioning this somewhere in the docs, to avoid potential confusion between `p.plot_width` and `p.width` if setting this attr after initial plot creation.

The purpose of this issue is to start a discussion about the best way to clearly convey the effects of all these attributes, and review whether `plot_width` and `width` are aliased in the right direction.

**Comment by mattpap** [comment]
Those properties can be divided into input (configuration) and output (actual layout state). So, `width` (`plot_width`; see next paragraph), `min_width`, `max_width`, `frame_width` are inputs and `outer_width` and `inner_width` are outputs. All values are integer pixels.  `width` is reflected in layout by `outer_width` and `frame_width` as `inner_width`. `outer_width` encompases all components of a plot (frame, axes, annotations, borders, etc.), whereas `inner_width` is exactly the size of the cartesian frame. Depending on the configuration, the outer size of a plot will be determined either by `width` (outside-in layout) or by `frame_width` (inside-out layout). `min_width` and `max_width` are constraints on `width`, if `width` is a suggestion (or a starting point for layout optimization), depending on sizing policy (sizing mode). All of this generalizes to any layouts, but only plots implement this dual inner/outer layout interface in full (to allow axis alignment between plots).

`plot_width` is an alias for layout's `width` with a non-null default value. `width` can be `null`, because depending on the layout and its configuration, it may not be necessary to provide any specific width, e.g. widgets can use CSS layout to determine their intrinsic size. `plot_width` was added to reduce confusion between `fig = figure(width=nnn)` and `fig.rect(width=mmm)`, but that was done before layout's `width` was exposed.

I wouldn't make references to "canvas" if it refers to HTML canvas, because that's an implementation detail. Currently there is 1-1 mapping between plots and canvases, but that will be changed either in 2.3 or 2.4, where it will be possible to lay multiple plots  on a single canvas.

**Comment by bryevdv** [comment]
`plot_width` and `plot_height` are removed on `branch-3.0` so I think this can simply be closed now
