### ISSUE TITLE
Cross reference user guide widgets examples to reference guide

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10667]
All the examples here:

https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html

Should link to the corresponding reference guide entry.

**Comment by swamilikes2code** [comment]
Hello everyone, I am planning to work on this issue. Quick question, since some descriptions do not have the names in the text below the heading, I am planning to add a short sentence. For the example attached here, looking to add "Detailed reference can be accessed for Colorpicker[https://link]".
![image](https://user-images.githubusercontent.com/66532440/99198627-e6aacc80-2767-11eb-8f8a-73aa6d06e780.png)

**Comment by bryevdv** [comment]
@swamilikes2code do you still plan to submit a PR? We need to have this done for the 2.3 release so unless you expect to have a PR in the next day or two before the code freeze, then we will need to work on it instead.

**Comment by swamilikes2code** [comment]
Bryan, I can't wrap it up in the next day or two. Please proceed as I can't
submit a PR.

I am having trouble setting up Sphinx documents environment on my machine.
Will try to figure it out in the upcoming week. Will start contributing to
documentation after that.

**Comment by bryevdv** [comment]
@swamilikes2code no problem let us know how we can help on other issues in the future!
