### ISSUE TITLE
Tag 2.3.0dev6 exists but the package is missing under bokeh/label/dev

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#10714]
I suppose this is a bug in release automation.

```
(branch-2.3) ~/repo/bokeh
$ git tag -l 2.3.0dev6
2.3.0dev6
```
```
$ conda search -c bokeh/label/dev bokeh=2.3.0dev6
Loading channels: done
No match found for: bokeh=2.3.0dev6. Search: *bokeh*=2.3.0dev6

PackagesNotFoundError: The following packages are not available from current channels:

  - bokeh=2.3.0dev6
```

**Comment by bryevdv** [comment]
The deploy part is still manual and I just never got around to it. At this point I will probably just make a `dev7` this weekend and try to see if the CI deploy job can be moved forward a bit more.

**Comment by jbednar** [comment]
Thanks! Several of us are working on a new HoloViews release, testing changes that went into dev6, and so having either 6 or 7 installable in the next day or so would be really helpful!

**Comment by bryevdv** [comment]
@mattpap @jbednar Bokeh `2.3.0dev7` is published, this time using the GH deploy action entirely to publish pip, conda, and docs. 

@mattpap there is no automation added to publish npm packages yet, this is an area where you will need to take the lead because you are the one with strong opinions about the policy. I'm happy to help with any questions about the code under `bokeh/release`

**Comment by jbednar** [comment]
Thanks; I was able to install 2.3.0dev7 from the dev channel!

**Comment by mattpap** [comment]
I started https://github.com/bokeh/bokeh/pull/10730 to get this sorted out.
