### ISSUE TITLE
[BUG] Link to Installation Documentation on Github README is broken

### ISSUE THREAD

**Issue by markgacoka** [bokeh/bokeh#10767]
Hello,

I was browsing through the repository readme and realized that the Installation link is broken. The page that links to https://docs.bokeh.org/en/latest/docs/first_steps/installation.html when instead it should link to https://docs.bokeh.org/en/latest/docs/installation.html.

I am using Chromium Version 87.0.4280.88 (Official Build) snap (64-bit) on Linux but the link is also broken in the regular Chrome version 87.0.4280.86 on my phone.

**COMMENT**: I intend to work on this as this will be my first contribution request. I also hope to make significant contributions in the future.

#### Stack traceback and/or browser JavaScript console output
favicon.ico: Failed to load resource: the server responded with a status of 404 ()
installation.html:1 Failed to load resource: the server responded with a status of 404 ()

#### Screenshots or screencasts of the bug in action
![Link to the Installation documentation on Github](https://user-images.githubusercontent.com/23658445/101286766-72f75f00-37fd-11eb-80cf-8d440c16976f.png)

![Broken webpage](https://user-images.githubusercontent.com/23658445/101286728-404d6680-37fd-11eb-9898-d44f6a5db455.png)

**Comment by bryevdv** [comment]
Hi @markgacoka appreciate the issue and the PR and we would love to have more contributions in the future! 

In this specific case though, the link is currently broken because it was already updated to what will become the new location when the next release comes out. Since that should be in the nexts few weeks,I think it is better to just leave things as they are so that it's not necessary to do even more work (which might be forgotten about) just to change it back  when the release comes out. So, accordingly I will close both the issue and the PR, since the problem will resolve itself when then next release happens. 

cc @tcmetzger can you confirm also that the old "installation" URL will redirect once the new docs are published?

**Comment by tcmetzger** [comment]
@markgacoka Thank you for noticing! Like @bryevdv said, I have just recently updated this link in the 2.3 branch to point to a new URL that will be available as soon as the documentation for 2.3 is published (the same is true for the link to the "first steps guides" right below it). I'm sorry about the confusion - we'd love to have more contributions from you in the future! If you are interested in contributing to the docs specifically, I'd suggest taking a look at the newly overhauled [documentation resources](https://github.com/bokeh/bokeh/blob/branch-2.3/sphinx/source/docs/dev_guide/documentation.rst) in the 2.3 branch. This issue might be a good place to start: #10539

I can also confirm that the old installation URL is part of the list of deprecated URLs that get automatically forwarded to their new locations (in the 2.3 branch [conf.py](https://github.com/bokeh/bokeh/blob/e0dcecca1f1bfb0bf9af7fb508c473b3d0d62cbc/sphinx/source/conf.py#L95)). You can test this by visiting https://docs.bokeh.org/en/test/docs/installation.html (the old URL in the testing environment running 2.3's redirect configuration). This link should automatically forward you to its new location.
