### ISSUE TITLE
[BUG] Dates in DataTables appear as zero-epoch

### ISSUE THREAD

**Issue by lyijin** [bokeh/bokeh#10769]
As requested by @bryevdv on issue #10749.

Dates in DataTables all appear as zero epoch (1970-01-01), despite them actually having valid dates in those table cells. Best illustrated by the DataTable section in the official widget documentation
https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html
(I hope this skips the need for a minimal repro code :D)

Copy-pasting the values out of the table DOES produce valid dates, so it's just the appearance that is faulty.

Screenie to illustrate fault:
![image](https://user-images.githubusercontent.com/9586164/101228325-4ce39900-36ef-11eb-88c1-dbcf647b373a.png)

Cheers!

**Comment by Suicoleiro** [comment]
Hi all,

The official bokeh documentation example works correctly if you put the "dates" source into a numpy array instead of a list. The two ways I tested and give correct results are:

1. Converting list into numpy array
```python
data = dict(
        dates=np.array([date(2014, 3, i+1) for i in range(10)]),
        downloads=[randint(0, 100) for i in range(10)],
    )
```

2. Converting the data dict into a pandas dataframe (same effect, list is being converted to numpy array)
```python
data = dict(
        dates=[date(2014, 3, i+1) for i in range(10)],
        downloads=[randint(0, 100) for i in range(10)],
    )
df = pd.DataFrame(data)
```

@mattpap @bryevdv checking with you if this is related to a more general issue between list vs. array or if it is an isolated event for the DateFormatter class before going into more details?
