### ISSUE TITLE
[BUG] Marker docs require updating 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10875]
Circle/Scatter links broken on this page:

https://docs.bokeh.org/en/dev/docs/reference/models/glyphs.html

Maybe they should be removed as they are technically markers. 

Circle is here (but strangely w/o parens) but  Scatter is not, and new Star links are broken:

https://docs.bokeh.org/en/dev/docs/reference/models/markers.html

cc @tcmetzger in case you have some bandwidth to look at this before me.

**Comment by bryevdv** [comment]
Oh, it's worse. The marker links that do work go to pages with no real info:

https://docs.bokeh.org/en/dev/docs/reference/models/markers/circle_cross.html#bokeh.models.markers.CircleCross

glyph pages seem to be ok. 

cc @mattpap any ideas what change might have affected this recently?

**Comment by tcmetzger** [comment]
From a very cursory glance: is it possible this is related to #10698? Also, this seems to be limited to the _bokeh.models_ interface - the docs for the respective elements in the _bokeh.plotting_ interface (and thus all links from the narrative docs, as far as I can see) seem to be working fine (e.g. https://docs.bokeh.org/en/dev/docs/reference/plotting.html#bokeh.plotting.Figure.circle_cross)

**Comment by mattpap** [comment]
There are no marker models anymore, only `Scatter` glyph and marker glyph functions. This documentation has to be fundamentally revised. I would also not consider `Circle` a marker, given it has different interface from other markers, though the implementation still insists on this.

**Comment by bryevdv** [comment]
Ah, I had forgotten about that. We really need to examine our processes somewhat, since at minimum a separate issue to update the docs should have been logged at the time, if the docs update was not part of the PR. 

I will try to look at this over the weekend. @tcmetzger if you have thoughts on organization, your input would be valuable. The upshot is that things like `p.square` are now really just aliases for `p.scatter("square", ...)`. Offhand I think the `scatter` docs should include a single plot that shows the name and appearance of all markers (a plot per marker is too many plots on a page). But we need to figure out what to do about the (now deprecated) marker methods `p.square` and marker classes `Square`.

> I would also not consider Circle a marker, given it has different interface from other markers, though the implementation still insists on this.

In hindsight, perhaps it would not have been so bad to explicitly distinguish "data radius" circle glyphs vs "pixel size" circle markers, but that is water under the bridge at this point.

**Comment by tcmetzger** [comment]
Yes, this should definitely be reflected in the docs, and having an example plot with all the markers (similar to https://github.com/bokeh/bokeh/blob/branch-2.3/examples/reference/models/Scatter.py?) would be great! I'll need some more time to understand what these changes mean in terms of docs. Some quick thoughts on what to look at for making changes: 

- For the reference guide, we probably should add more information to the docstrings in https://docs.bokeh.org/en/dev/docs/reference/models/markers.html. This is probably the place to put the most detailed information on what has changed. We should also check and update https://docs.bokeh.org/en/dev/docs/reference/plotting.html for consistency, as well as https://docs.bokeh.org/en/dev/docs/reference/models/glyphs.html and https://docs.bokeh.org/en/dev/docs/reference/plotting.html?highlight=scatter#bokeh.plotting.Figure.scatter, I think.

- In the narrative docs, we need to look at https://docs.bokeh.org/en/dev/docs/user_guide/plotting.html#scatter-markers where we should probably include a brief explanation of the aliases and `p.scatter()`. There is also https://docs.bokeh.org/en/dev/docs/first_steps/first_steps_2.html#rendering-circles where it might be sufficient to make sure we use consistent wording and otherwise link to the user guide and the reference. 

- In addition, we need to look at https://hub.gke2.mybinder.org/user/bokeh-bokeh-notebooks-qofexp32/notebooks/tutorial/01%20-%20Basic%20Plotting.ipynb#Scatter-Plots. It might also be necessary to look at some of the examples and gallery items.

As a suggestion: @bryevdv If you wanted to focus on updating the docstrings and building the "all markers" plot (and maybe drafting some updates to the narrative docs), I could edit the changes for clarity and consistency, and also write the necessary updates for the narrative docs (based on the updated docstrings).

**Comment by bryevdv** [comment]
@tcmetzger here is a script you can play with / improve:
```
from bokeh.core.enums import MarkerType
from bokeh.io import show
from bokeh.plotting import figure

bases = [
    "asterisk",
    "circle",
    "cross",
    "dash",
    "diamond",
    "dot",
    "hex",
    "inverted_triangle",
    "plus",
    "square",
    "star",
    "triangle",
    "x",
    "y",
]

kinds = [
    "",
    "cross",
    "dot",
    "pin",
    "x",
    "y",
]

data = []

for base in bases:
    for kind in kinds:
        name = f"{base}_{kind}" if kind else base
        if name in MarkerType:
            data.append((name, base, kind))

marker, base, kind = zip(*data)

p = figure(x_range=kinds, y_range=list(reversed(bases)), width=300,
           toolbar_location=None, x_axis_location="above")
p.grid.grid_line_color = None
p.axis.major_tick_line_color = None

p.scatter(marker=marker, x=kind, y=base, size=25, fill_alpha=0.4, fill_color="orange")

show(p)
```

It generates this:

<img width="308" alt="Screen Shot 2021-01-30 at 6 05 56 PM" src="https://user-images.githubusercontent.com/1078448/106372583-deedd380-6325-11eb-88f0-787d009e9bcb.png">

**Comment by tcmetzger** [comment]
@bryevdv Thanks, I will take a look at this in the next few days. Do you happen to know why the links to `Scatter` (and `Circle)` in  https://docs.bokeh.org/en/dev/docs/reference/models/glyphs.html are not working? In the `glyphs.py` module, the class `Scatter` and the class `Circle` both seem to have docstrings, but somehow those docstrings are not rendered and linked?

**Comment by bryevdv** [comment]
Still investigating. I tried building with `SPHINXOPTS=-v` but didn't see anything obvious.

**Comment by bryevdv** [comment]
@tcmetzger circle and scatter need missing `circle.rst` and `scatter.rst` files created under the directory
> bokeh/sphinx/source/docs/reference/models/glyphs/

#### circle.rst
```
.. _bokeh.models.glyphs.Circle:

bokeh.models.glyphs.Circle
--------------------------

.. autoclass:: bokeh.models.glyphs.Circle
    :members:
    :inherited-members:
```

##### scatter.rst
```
.. _bokeh.models.glyphs.Scatter:

bokeh.models.glyphs.Scatter
---------------------------

.. autoclass:: bokeh.models.glyphs.Scatter
    :members:
    :inherited-members:
```

**Comment by tcmetzger** [comment]
I have opened pull request #10885 and added some first commits. I'd suggest we continue the discussion there.
