### ISSUE TITLE
[BUG]Custom Widget Example fails to load (2.3.0rc2)

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10924]
cc @mattpap 

ref: https://docs.bokeh.org/en/dev/docs/user_guide/extensions_gallery/widget.html#userguide-extensions-examples-widget

Example does not render and JS console reports:

> Refused to apply style from 'https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.1.4/img/sprite-skin-flat.png' because its MIME type ('image/png') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by mattpap** [comment]
I also get (in Chrome):
```
failed to load https://cdn.bokeh.org/bokeh/dev/bokeh-api-2.3.0rc2.min.js
```

**Comment by mattpap** [comment]
The problem with `sprite-skin-flat.png` is that it's requested with wrong MIME type. In DOM inspector:
```
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.1.4/img/sprite-skin-flat.png">
```

**Comment by mattpap** [comment]
Which is an obvious failure given that this image is referenced from `__css__ `.

**Comment by mattpap** [comment]
> failed to load https://cdn.bokeh.org/bokeh/dev/bokeh-api-2.3.0rc2.min.js

Actually, this is just bad javascript (leaky scopes) in `autoload_js.js`. When fixed it tells that it couldn't load the png file.

**Comment by bryevdv** [comment]
Why did this work before?

**Comment by mattpap** [comment]
I'm not sure. I don't see any recent changes to this example or autoload, that would affect this. Did we always use autoload in documentation? If not, then this may be the culprit, i.e. this example has always been broken under autoload. Otherwise, maybe strict MIME checking now produces errors instead of warnings. However, a quick web search reveals that people have been having issues with this at least for a few years.
