### ISSUE TITLE
[BUG] BokehJS component default value not passing through

### ISSUE THREAD

**Issue by 02GEEK** [bokeh/bokeh#10926]
I’m currently running bokeh(2.3.0.dev12), node( 14.15.5) and npm (6.14.11). - it looks like default values are not passing from python into javascript.

```
from bokeh.plotting import curdoc

from bokeh.core.properties import String
from bokeh.models import HTMLBox
from bokeh.util.compiler import TypeScript


CODE = """
import {HTMLBox, HTMLBoxView} from "models/layouts/html_box"

import * as p from "core/properties"


export class AlertBoxView extends HTMLBoxView {
  model: AlertBox

  render(): void {
    const { message } = this.model;
    super.render();
    console.log("@ render", message);
    this.el.innerHTML = `Message is: ${message}`;
  }

}
export namespace AlertBox {
  export type Attrs = p.AttrsOf<Props>
  export type Props = HTMLBox.Props & {
    message: p.Property<string>
  }
}
export interface AlertBox extends AlertBox.Attrs {}
export class AlertBox extends HTMLBox {
  properties: AlertBox.Props
  __view_type__: AlertBoxView
  constructor(attrs?: Partial<AlertBox.Attrs>) {
    console.log("@@@@ attrs are", attrs);
    super(attrs)
  }
  static init_AlertBox(): void {
    this.prototype.default_view = AlertBoxView
    this.define<AlertBox.Props>(({String}) => ({
      message: [String],
    }));
  }
}
"""

class AlertBox(HTMLBox):
    __implementation__ = TypeScript(CODE)

    message = String(default="passing a default value!")


# Get a reference to the document we will be creating
doc = curdoc()

# Put the column into the document
doc.add_root(AlertBox(
    # message="This is a component processed"
))


```
The output in html is:
Message is: null

**Comment by mattpap** [comment]
Non-volatile default values (primitive values in particular) are not serialized, to save on JSON bundle size. The assumption is that default values are mirrored between Python and JavaScript, mostly so that models in JavaScript can be used independently of Python models. However, if you don't intend to do that, then duplicating those values seems pointless. I suppose we could allow serialization of all values for custom models and/or if requested by model creator.

**Comment by 02GEEK** [comment]
I see! thanks for the clarification. What ever works better for the Bokeh roadmap/vision - I'll put the defaults on the JS side as well - worth putting a note on it in the documentation.

**Comment by bryevdv** [comment]
Ah, yes, not sure why this did not jump out at me earlier. Offhand, I would be fine with simply adding more documentation support making it clear that default values should be mirrored for custom models. 

@mattpap my only question would be about `DataModel` then. Do these mirror default values? It seems like perhaps they should (since there is no JS implementation for users to do so explicitly).

**Comment by mattpap** [comment]
> my only question would be about DataModel then. Do these mirror default values?

Data models are fully mirrored with their types, default values, etc.

**Comment by bryevdv** [comment]
Perfect. I'll label this as a docs issue for `next` cc @tcmetzger
