### ISSUE TITLE
[BUG] BokehJS failing with Webpack

### ISSUE THREAD

**Issue by alexanderhupfer** [bokeh/bokeh#10925]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Python 3.9.1 (default, Feb  2 2021, 22:54:59)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
bokeh.__version__ = '2.2.3'

  System:
    OS: macOS 11.2.1
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 15.8.0 - ~/.nvm/versions/node/v15.8.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.1 - ~/.nvm/versions/node/v15.8.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.182
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.0.3
  npmPackages:
    react: ^17.0.1 => 17.0.1 
    react-dom: ^17.0.1 => 17.0.1 
    react-scripts: 4.0.2 => 4.0.2 
  npmGlobalPackages:
    create-react-app: Not Found

  "dependencies": {
    "@bokeh/bokehjs": "^2.2.3",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.2",
    "web-vitals": "^1.0.1"
  },

#### Complete, minimal, self-contained example code that reproduces the issue

https://gist.github.com/sonium0/2c9ec81c4fd25ce2515872cf64df7000

No issues with yarn start
however:
yarn build & serve -s build produces the JavaScript error below

#### Stack traceback and/or browser JavaScript console output

Blank Page

Uncaught TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
    at new Set (<anonymous>)
    at new n (kinds.js:129)
    at St (kinds.js:206)
    at Object.<anonymous> (kinds.js:210)
    at a ((index):1)
    at Module.23 (main.7681e39c.chunk.js:1)
    at a ((index):1)
    at t ((index):1)
    at Array.r [as push] ((index):1)
    at main.7681e39c.chunk.js:1

**Comment by sonium0** [comment]
After some searching this seems to be the same bug as https://github.com/bokeh/bokeh/issues/10497

**Comment by sonium0** [comment]
This seems to cause the error:

yarn start:
<img width="547" alt="Screenshot 2021-02-21 at 18 08 50" src="https://user-images.githubusercontent.com/5372632/108632580-0856d680-7470-11eb-845e-1efa79150fc7.png">

yarn build:
<img width="489" alt="Screenshot 2021-02-21 at 18 09 16" src="https://user-images.githubusercontent.com/5372632/108632613-2b818600-7470-11eb-9aab-dd3a6228f381.png">

**Comment by mattpap** [comment]
I need to see `kinds.js` as generated by your build, preferably as an extract from the final bundle, to make sure that all relevant code transformations were applied. Or alternatively show the second screenshot without source mapping.

**Comment by sonium0** [comment]
Here is the complete project https://www.icloud.com/iclouddrive/0wvAEXVw6GjP79l9VJDUumzbw#grafana-ui including the build

**Comment by sonium0** [comment]
@mattpap do you have the information you need?

**Comment by bryevdv** [comment]
@sonium0  we are in the middle of a release this week, responses may take some time.

**Comment by mattpap** [comment]
The problem is with this:
```js
Tt=function(e){return new _t.Array(e)}
```
and then
```js
function(){for(var e=arguments.length,t=new Tt(e),n=0;n<e;n++)t[n]=arguments[n];return new _t.Enum(t)}
```
One of source transforms in your build (transpiler to ES5, maybe minifier) tracks build-in names and incorrectly replaces build-in `Array` with (local) `Array` kind from `core/kinds` module in `arguments` to an array conversion. This is utter nonsense in an ES module. This is, for example, what TypeScript emits when generating ES5 code:
```js
var Enum = function () {
  var values = [];
  for (var _i = 0; _i < arguments.length; _i++) {
    values[_i] = arguments[_i];
  }
  return new exports.Kinds.Enum(values);
};
```

**Comment by mattpap** [comment]
There's nothing I can do on our side. In particular I can't rename `Array` kind, as this would be a major breaking change. I would try transpiling and minifying modules individually and then bundling them. This is what bokehjs' build system does.

**Comment by mattpap** [comment]
This is the same problem as in https://github.com/bokeh/bokeh/issues/10925.

**Comment by bryevdv** [comment]
[Prefacing this by stating that I lack technical depth in this area, and also lack any personal bandwidth to obtain it.]

@mattpap so what's the takeaway here? JS devs will not use BokehJS directly unless it is quick and easy and works with existing common tools and workflows. We saw that clearly in the other issue ("We have abandoned using Bokeh"). 

So then: is it categorically impossible to write guidance like "5 minutes to Bokeh+React" or "5 minutes to Bokeh+Vue" with complete worked examples? [1] If so, that's a bit disappointing, but it also is what it is. If so, we should accept that reality and add a huge disclaimer to the top of the BokehJS docs to that effect so that at least we have something to point to when the question comes up. cc @bokeh/core 

[1] If it *is possible* to write such guidance, then I still maintain that literally nothing else—no new features, no bugfixes, nothing—would go further to promote BokehJS as a viable JS tool that real JS devs could actually use on their day job.
