### ISSUE TITLE
[FEATURE] bokeh.io.webdriver should have function close_webdrivers()

### ISSUE THREAD

**Issue by jnettels** [bokeh/bokeh#10940]
- Windows 10
- Python 3.7
- Bokeh 2.1.1 (and 2.2.3)

**Is your feature request related to a problem? Please describe.**
When I am using bokeh.io.export_png() or bokeh.io.export_svgs() on Windows, there are several firefox.exe programs launched that I can observe in task manager. Even after the python script is finished, these task are not killed automatically and they keep consuming CPU and ram until I kill them manually in task manager. When creating a lot of exports, this gets quite annoying.

I realized that I can somewhat solve this by calling bokeh.io.webdriver.quit() manually when I am done, like so:
```Python
from bokeh.io import export_png, export_svgs, webdriver
web_driver = webdriver.create_firefox_webdriver()
export_png(plot, filename=filename, webdriver=web_driver)
export_svgs(plot, filename=filename, webdriver=web_driver)
web_driver.quit()
```

The only problem is that here I have to choose between ``webdriver.create_firefox_webdriver()`` and ``webdriver.create_chromium_webdriver()``. Ideally I would like to let bokeh choose between those and call ``export_*`` without specifying a webdriver. Also I am accessing a ``Dev API`` function, which I should not.
I also guess that you do not automatically kill the webdriver instance, because then it can be used again for different exports.

**Describe the solution you'd like**
``bokeh.io.webdriver`` should have a public ``General API`` function like for example ``close_webdrivers()``:

```python
#-----------------------------------------------------------------------------
# General API
#-----------------------------------------------------------------------------

def close_webdrivers():
    """Close all webdrivers. Use this after export_png() or export_svgs()."""
    webdriver_control.cleanup()
```

**Additional context**
I now realize that there is ``atexit.register(lambda: webdriver_control.cleanup())`` at the end of the file, which is probably exactly what I am asking for. But it does not work for me, for whatever reason.

I am using Spyder on Windows. I normally use ``Execute in an external system terminal", and this is where my problem happens. But if I use the setting "Execute in a dedicated console" and then close that console after my script has finished, the firefox.exe tasks are actually killed properly. I guess I am experiencing some edge case that is hard to reproduce on other machines.

**Comment by bryevdv** [comment]
@jnettels if something about Spyder is preventing `atexit` from functioning normally, I am not sure what we can do about that. [1] `atexit` is pretty much the only tool at our disposal for this. You might try engaging with the Spyder devs to see if they are aware of any issues with `atexit` or can offer any suggestions. 

Otherwise, I also don't think there is any need to add a new function. Dev API is public, stable API, so you can just use the existing `webdriver_control.cleanup`. "Dev API" only exists as a notion because at one point we wanted to try and distinguish between "very common for every user" API ,and things that were less common. But we are already thinking about dropping this distinction. The only thing that might change about `webdriver_control` in the future is that it might also be raised to be included in `bokeh.io` instead of just a submodule. 

I am going to go ahead and close this with `noaction`. If the Spyder devs can offer any workaround that is appropriate to be included in the library directly, we can certainly re-open. 

[1] And it seems like that might be the case: https://stackoverflow.com/questions/41852743/python-atexit-function-is-not-called-on-spyder-ide
