### ISSUE TITLE
Add style attribute to all widgets

### ISSUE THREAD

**Issue by sdc50** [bokeh/bokeh#10990]
The `Markdown` widget (and its subclasses) have a style attribute enabling you to set specific styles for a particular widget. This would be really helpful to have for all widgets. 

I would like to see the style attribute moved to the base `Widget` class so that all widgets can take advantage of this type of stying.

My current approach is to use `css_classes` on other types of widgets, but this does not have the flexibility of directly assigning styles.

**Comment by bryevdv** [comment]
@sdc50 can you elaborate on exactly the kinds of styling you are thinking of? 

Our reluctance here is based in the fact that the underlying widget implementation is an implementation detail. For example, if we expose `style` on the `Slider` widget, but then one day change the widget implementation form NoUiSlider to IonRangeSlider, there is a good chance that any styles you had set would silently become useless (at best) or actually break the page somehow (at worst). We are reluctant to expose our tracker to issues regarding those sorts of changes.

For markdown widgets, `style` was considered acceptable, because those widgets more or less map directly to basic HTML elements.
