### ISSUE TITLE
[FEATURE] Vectorized Span and Slope annotations

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#11015]
As discussed in https://stackoverflow.com/questions/66498969/how-to-update-span-bokeh-using-columndatasource, a `Span` object can only render a single span line. It does not utilize CDS, and all spans in a plot have to be updated individually.

It would be great to have the option to control a series of spans with one CDS - instead of individual `Span` objects with individual `location` properties. This would be very similar to the existing `LabelSet` annotation.

Two ideas for this:

- We could follow the example of `Label` and `LabelSet` and create an additional `SpanSet` that accepts values for several span lines as a CDS.
- We could update the existing `Span` object to not only accept a single value for its `location` property (resulting in a single span line), but to also accept a CDS (resulting in multiple span lines). 

Using `SpanSet` would be nice for consistency with the existing `LabelSet`. However, having a `Span` object that accepts a single value OR a CDS would be nice because it would keep the number of objects smaller - and to me it seems perfectly reasonable to have a `Span` object that can render one or multiple span lines (this would be closer to the example of a scatter plot - where one object can either render a single shape or multiple shapes, I guess).

This could also be applied to Slope, Band, and BoxAnnotation, I think.

cc @bryevdv

**Comment by mattpap** [comment]
This needs to be discussed and redesigned in the broader scope of issue #9955. In fact I would close this a duplicate.

**Comment by bryevdv** [comment]
That issue is maybe over-broad and also a bit stale. I think it's good to refer to, but I'd like to precipitate out some concrete ideas related specifically for vectorization of annotations, which has come up frequently lately. I have ideas to respond here that I will add when I get chance this week.

**Comment by bryevdv** [comment]
I think what I'd like to  experiment with/investigate is whether a `source` arg can be added to `Label`, `Span`, `Slope` etc in a compatible way. This seems potential do-able since they are currently handle "single values" and DataSpecs can also handle "single values" in addition to column refs. If that is in fact possible, then I would also propose deprecating `LabelSet` as well.

**Comment by gmerritt123** [comment]
On my wish list!

**Comment by mattpap** [comment]
Closing in favour of discussion https://github.com/bokeh/bokeh/discussions/12487.
