### ISSUE TITLE
dates have offset on plot

### ISSUE THREAD

**Issue by abieler** [bokeh/bokeh#1103]
when plotting with the "x_axis_type='datetime'" option, my data points are shifted by 4 hours
on the plot. in the example code below the data points appear at 04:00 and 05:00 instead of
00:00 and 01:00. does it automagically convert to utc (which is +4h from my timezone)?

example:

```
import datetime
import bokeh.plotting as bplt

t0 = datetime.datetime.strptime('2014-08-20T00:00:00', '%Y-%m-%dT%H:%M:%S')
t1 = datetime.datetime.strptime('2014-08-20T01:00:00', '%Y-%m-%dT%H:%M:%S')
y = 1.0

bplt.output_file('dateCheck.html')
bplt.figure(x_axis_type='datetime')
bplt.scatter([t0, t1], [y, y])
bplt.show()
```

**Comment by mwerezak** [comment]
I am having this issue with 0.12.3.
The datetimes are always shown as UTC regardless of tzinfo. Naive datetimes appear to be treated as belonging to the system's timezone.

**Comment by bryevdv** [comment]
@mwerezak this issue is nearly two years old, and many different things are discussed in it. I'm not sure which one you are referring to. If you think you are experiencing a bug, please open a NEW issue, and make sure to include *all of these things*:

* system, library, browser, version information, etc
* a complete, minimal, runnable example code that reproduces the problem
* a very detailed description (screenshots helpful) of what is expected vs what happened

As a final note, just in case there is confusion: the expected behavior is that times are passed on and displayed exactly as-is.

**Comment by mwerezak** [comment]
Okay, that is definitely not the behavior I am seeing. I'll see about writing up an issue tomorrow.
