### ISSUE TITLE
[BUG] Plot is not resized to height after replacement

### ISSUE THREAD

**Issue by snthibaud** [bokeh/bokeh#11093]
#### Description of expected behavior and the observed behavior
I created below code in which I replace a graph with a new one every 2 seconds. After the first 2 seconds, the plot does not have the same height as the window anymore. Is this indeed a bug or can it be circumvented?

#### Complete, minimal, self-contained example code that reproduces the issue

```
from threading import Thread
from time import sleep
from typing import Callable

import networkx as nx
from bokeh.io import curdoc
from bokeh.layouts import row
from bokeh.models import Widget
from bokeh.plotting import figure, from_networkx
from tornado import gen


def run_async_handlers(pre_handler: Callable[[], type(None)], post_handler: Callable[[], type(None)]):
    @gen.coroutine
    def _run_async_handlers():
        post_handler()
    pre_handler()
    Thread(target=lambda: doc.add_next_tick_callback(_run_async_handlers)).start()


def make_graph(g: nx.DiGraph) -> Widget:
    graph_figure = figure(x_range=(-1, 1), y_range=(-1, 1), output_backend="webgl")
    graph_figure.renderers.append(from_networkx(g, nx.spring_layout, scale=0.8))
    return graph_figure


g = nx.DiGraph([(1, 2)])
doc = curdoc()
root_row = row(
    make_graph(g),
    sizing_mode="scale_height")
doc.add_root(root_row)


def add_node(i):
    g.add_node(i)
    g.add_edge(i-1, i)
    root_row.update(children=[make_graph(g)])


def run():
    for i in range(3, 100):
        sleep(2)
        run_async_handlers(lambda: None, lambda: add_node(i))


Thread(target=run, daemon=True).start()
```

**Comment by bryevdv** [comment]
@snthibaud the `sizing_mode` passed to `row` only overrides children's sizing mode *once*, i.e. at initialization time. If you are dynamically adding new children after the fact, you will need to set their sizing modes explicitly.

In the future, if there is a doubt as to whether something is a bug or a usage question, please go to the [project Disourse](https://discourse.bokeh.org/) *first*. If it turns out to be a bug we will certainly encourage you to open an issue. (Also, if you do file an issue, please provide *all the information that the issue template asks for* e.g. the version information that was asked for)

**Comment by snthibaud** [comment]
@bryevdv Thank you! Setting the 'sizing_mode' directly indeed works. I will check the project discourse page first next time.
