### ISSUE TITLE
[FEATURE] Option for DataTable column sorting to place NaNs last

### ISSUE THREAD

**Issue by sggaffney** [bokeh/bokeh#11104]
When sorting a TableColumn with NumberFormatter formatting, NaN values are treated like large numbers: rising to the top when the column is in descending order, and moving to the bottom when in ascending order. This remains the case when you set a value for `nan_format`. It would be nice to have the option to force these to display last in either sorting direction, mimicking the pandas Series sorting behavior with missing data, and MATLAB's MissingPlacement = 'last' sorting option.

(As a workaround in the meantime I've been replacing nans with low/negative numbers and hiding them with CSS + HTMLTemplateFormatter.)

Example creating a table with NaNs (tested in bokeh 2.3.0):
```python
import numpy as np
from bokeh import io as bkio
import bokeh.models as bkm

source = bkm.ColumnDataSource({
    'journal': ['The Lancet', 'Clinical and experimental pediatrics', 
                'Anales de Pediatria', 'Annals of translational medicine', 'CMAJ'],
    'citescore': [10.28, np.nan, 0.43, np.nan, 1.12],
    })
d = bkm.DataTable(columns=[bkm.widgets.TableColumn(field='journal', title='journal'),
                           bkm.widgets.TableColumn(field='citescore', title='citescore', 
                                                   formatter=bkm.NumberFormatter(format='0.0'))], 
                  source=source)
bkio.show(d)
```

NaNs are sorted to the top in descending order:
<img width="611" alt="image" src="https://user-images.githubusercontent.com/5185412/112624371-7a328f00-8e25-11eb-8a65-359d372c8100.png">

**Comment by bryevdv** [comment]
There are four options:

1. sort NaNs first when descencing
1. sort NaNs last when descending
1. always sort NaNs first, ignoring ascending/descending
1. always sort NaNs last, ignoring ascending/descending

For ref the table sorter code is here: 

https://github.com/bokeh/bokeh/blob/8e56697b063b07040bd2ac2a8bd58fab6e619763/bokehjs/src/lib/models/widgets/tables/data_table.ts#L93-L117

We currently do 1 according to the above.  It looks like an option to change NaNs to sort opposite of how they sort now (i.e. adding 2) would just be to inject a configurable sign on 110. 

An options 3. and 4. is a bit problematic since they have some tension with 1 and 2 and avoiding a breaking change may also be problematic. 

I am definitely 👍 to add 2) in a release "very soon" but for 3) and 4) someone will need to put forth a proposal what the user API should look like and and how it will avoid presenting mutually incompatible choices to users.
