### ISSUE TITLE
[BUG] Image orientation upside-down using bokeh.plotting.figure.image

### ISSUE THREAD

**Issue by rynkk** [bokeh/bokeh#11132]
bokeh==2.3, Google Chrome Version 89.0.4389.114 

#### Description of expected behavior and the observed behavior
I would expect the image to be rendered with the right orientation, top of the 2D-array should be visually at the top, the bottom of the 2D-array should be visually at the bottom.

What I found is that the "top-left" of the 2D-array so e.g., img[0][0] is rendered at the origin of the image-plot (so at (0,0)) while I think the "bottom-left" has to be at the origin, e.g. img[-1][0]) 
This is how matplotlibs imshow works and I think this is how bokehs figure.image should work to remain consistent and also behave as expected.

The current way makes sense from the perspective of a coordinate system (for (0,0) take img[0,0]) but it does not make much sense from my perspective, at least.
Every library to load images I can think of and all sample data gets screwed over with the current way image display is handled (unless I manually adjust the loaded images/sample data). So my current workaround is to `np.flipud` on every image I display and generally when I use the figure's coordinate system.

If you run this example you will see exactly the mirroring I mentioned if you look at the values displayed by the HoverTool.

```
from bokeh.io import show
from bokeh.plotting import figure

img = [[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]]

plot = figure(title="image_1", tools=["hover"])
plot.hover.tooltips = [("val", "@image")]

img = plot.image(image=[img], x=0, y=0, dw=len(img), dh=len(img[0]))

show(plot)
```

I found this also mentioned in 2015: [Bokeh Discourse](https://discourse.bokeh.org/t/mirrored-image-along-x-axis/311)

Edit: If this is intended there should be a optional boolean keyword argument like `flip` or `keep_image_orientation` to mimick mathplotlibs `imshow`

**Comment by bryevdv** [comment]
@rynkk It's an arbitrary convention, and Bokeh happened to choose differently early on (e.g. my background was plotting color-mapped surface images of mathematical functions, for which a lower-left anchor makes more natural sense). In any event, it is far, *far* past the time where we could ever consider changing the default behavior. What we could possibly do is offer API or configuration to select a different anchor (while retaining the present default) But there is already an issue for that: #1763 which is why I will close this one as a duplicate. 

Currently, best advise is to flip the image yourself (as a few examples do)
