### ISSUE TITLE
[BUG] Toolbar properties non-nullable

### ISSUE THREAD

**Issue by Haptein** [bokeh/bokeh#11216]
With version 2.3.0 onwards toolbar properties of the kind active_{tooltype} are not nullable.

Reproduction:
```
from bokeh.plotting import figure
from bokeh.io import show
fig = figure(active_inspect=None, tools='hover')
show(fig)
```

This used to be the way to set inactive certain tools by default, so I'm guessing this isn't on purpose.

**Comment by bryevdv** [comment]
The actual toolbar property has been made nullable:

https://github.com/bokeh/bokeh/blob/ed54705d627ae500509e57fe071fc7a60fc8a951/bokeh/models/tools.py#L294-L295

But `figure` has an options class for its kwargs that duplicates some of these, and it was not updated:

https://github.com/bokeh/bokeh/blob/c0c299344c8434dcc0423ea68298ce45930dce3f/bokeh/plotting/figure.py#L1638-L1639

@Haptein for now you should be able to set `active_inspect` to null directly on the toolbar (instead of passing it to figure)

Since this has a simple WAR I will target for 2.4

**Comment by Haptein** [comment]
I didn't even think of trying that, thanks!
