### ISSUE TITLE
Add Support for POST Requests

### ISSUE THREAD

**Issue by aretoo** [bokeh/bokeh#11226]
At the moment, when bokeh receives a POST request, it results in a `405: Method not Allowed` error. Tornado's [RequestHandler](![image](https://user-images.githubusercontent.com/52463928/116617996-5a462d80-a8f3-11eb-9dcd-509da53dd7c9.png)) is compatible with POST requests, but apparently the post() handler hasn't been implemented yet in bokeh. Adding this feature would be very helpful in some particular cases and could extend bokeh's applicability.

**Comment by bryevdv** [comment]
@aretoo Can you explain the use case and usage scenarios in more detail? Are you trying to embed Bokeh server app sessions in other pages, e.g. using `server_document`, but would like that to be able to use POST instead of GET? Or are you looking to add new, different endpoints that can accept POST requests, unrelated to initiating app sessions. You need to walk through exactly the scenario you  would like to be able to accomplish, with *details* and *specifics*.

**Comment by aretoo** [comment]
I am embedding sessions in other pages, but the functionality of the application is highly dependent on the arguments received through `request_args = curdoc().session_context.request.arguments`. All I'm trying to do is to switch from GET to POST and still have access to those arguments in the python application. The use case is simply that I'd prefer to use POST in case private information is included in the arguments. I'm not sure what other specifics would be helpful. I would like to access the arguments without getting a 405 error. I realize the implementation might not be simple, but the usage scenario is pretty simple.

**Comment by bryevdv** [comment]
> in case private information is included in the arguments.

@aretoo This is why it is always critical to express what you are trying to accomplish without referring or assuming any specific implementatio. 

If you are just trying to keep things out of the URL, then `server_session` and `server_document` both already accept a `headers` parameter that can be used to pass data via HTTP headers, i.e. that can be accessed via `session_context.request.headers`. From your description, that should satisfy your need?

**Comment by bryevdv** [comment]
@aretoo Here is what I still don't understand: are you asking for built-in Bokeh APIs to be able to make POST requests under the covers, as a hidden implementation detail, or are you asking that somehow *you* be able to make POST requests directly?

**Comment by aretoo** [comment]
@bryevdv Most of what I want to do isn't really "in code" but I'll try to at least provide steps to reproduce the error including code when possible.Here's an example of a simple Python script that simply reads an argument and prints it:

`from bokeh.plotting import curdoc

request_args = curdoc().session_context.request.arguments

text = request_args.get('text')[0].decode('utf-8')

print(text)
`
I saved that as `post_test.py` and then run `bokeh serve post_test.py`

I'm using [Postman](https://web.postman.co/home) to test it so in Postman, I select "GET" from the dropdown and type `http://localhost:5006/post_test?text=foo` in the box and hit run. It works. 'foo' is printed to the standard out and Postman shows a status of 200. Then I switch the dropdown to "POST" and rerun the exact same thing. This time the standard out shows, '405 POST /post_test?text=foo (::1) 0.44ms' and Postman gives a status of "405: Method not allowed". If the arguments can simply get past the Tornado layer so they are present in the `curdoc` context, that's literally all I'm looking for.

**Comment by bryevdv** [comment]
@aretoo I am afraid this situation still makes no sense to me. You can't embed Bokeh app sessions with a simple raw GET so you would not be able to embed them with a raw POST either. Embeds have to go through the Bokeh embed APIs, e.d. `server_session` or `server_document`. So, the only way adding support for POST would make sense is if those APIs could also be updated to add a POST option. But you just said you don't want to use programmatic APIs so I truly don't understand how this would be useful.

**Comment by bryevdv** [comment]
cc @bokeh/dev in case I am missing some angle on this.

**Comment by philippjfr** [comment]
Also struggling to see any situation where a session handler would need to handle post requests. I can imagine wanting to add another separate handler which accepts POST request arguments, which also allows associating the post request with an existing session but that's different from what's being requested.

**Comment by p-himik** [comment]
@aretoo To make sure everybody's in understanding: assuming this gets implemented so that your Postman scenario works - how _exactly_ do you plan to use it?

**Comment by aretoo** [comment]
@bryevdv "you can't embed Bokeh app sessions with a simple raw GET" Like I said earlier, I'm not the person responsible for implementing the pages that the Bokeh pages are embedded in, so this is a bit out of my depth, but I believe it is done using something like [iframe](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe). I'm not sure how I could be clearer about what I'm requesting. It seems like the issue now is that you don't believe that what I'm asking for is useful, not that you don't understand what I'm asking for... I'll look into exactly how they're doing the embedding and I'll get back to you. Maybe that will help to clear things up.

**Comment by bryevdv** [comment]
@aretoo that would be extremely helpful. Offhand, an `iframe` also does not shed any light on things since standard iframe URLs execute GETs, not POSTs. But I did find this:

https://jsbisht.in/load-iframe-content-using-post-request-with-angularjs/

So although it seems quite unusual, I suppose it's possible people are trying to do something along those lines. But we we would really need to know that for sure, if for no other reason than to make sure that scenario is tested.

**Comment by bryevdv** [comment]
> Also struggling to see any situation where a session handler would need to handle post requests.

I do think it would be possible and maybe not difficult for `server_session` and server_document` to make POST requests, which would allow information to be sent to a session void the request body instead of request arguments in the URL, but:

* There does not seem to be any actual demand for that capability *via the APIs* (including the OP here), and
* I am also not sure that would afford any specific benefit over what it already possible with headers

**Comment by aretoo** [comment]
The requests are being made through [jQuery.get()](https://api.jquery.com/jquery.get/) and [jQuery.post()](https://api.jquery.com/jquery.post/).

**Comment by bryevdv** [comment]
@aretoo I cannot imagine why anyone would do that, or how the result of that would be used, unless they have vendored what is otherwise internal Bokeh code into their own project. Is it possible to put the people doing this into contact here on this issue to explain what it is exactly they are doing?

**Comment by aretoo** [comment]
Alright, I've looked into our deployment further and have learned a bit more about what's going on between Bokeh and the webpage itself. There is a Flask layer intermediating the two and utilizing `server_document()`. So I think that's the main reason for the confusion in this discussion. It looks like I should be able to parse POST arguments within Flask and pass them to `server_document()`.

**Comment by bryevdv** [comment]
@aretoo thanks for the follow-up to close this out!
