### ISSUE TITLE
[FEATURE] Performance Comparisons and Benchmarks

### ISSUE THREAD

**Issue by sirinath** [bokeh/bokeh#11228]
Currently performance comparison between different versions of Bokeh and other libraries is lacking.

With the introduction of BokehJS and WebGL rendering can such benchmarks be added. Perhaps a starting point can be: https://github.com/leeoniya/uPlot/tree/master/bench but expanded.

This should test for handing:
- large volumes of static data
- ultra fast streaming data
- user interactions
  - static graphs
  - streaming graphs

**Comment by ianthomas23** [comment]
We plan to do some performance comparisons between our canvas and webgl backends so that we can provide guidance on which is more appropriate under particular circumstances.  No doubt we will document our benchmarking code and analysis so that others can repeat it if they wish as the results will be system dependent.

But they are internal comparisons within Bokeh.  External comparisons with other libraries needs to be done by someone without affiliation to any of the compared libraries if it is to be taken seriously.  So if such a comparison was to be done I am sure someone here would provide help on the Bokeh side of things, but I think you are unlikely to find anyone here to instigate such a comparison.

**Comment by bryevdv** [comment]
It would be great to develop some benchmarks to run in CI continuously. And just speaking for myself, I would not be opposed at all to mechanically reporting such results. I might be even be inclined to tweet them out at times. But I agree with @ianthomas23 that I would not personally be interested at all in conducting *comparisons* across different libraries for marketing purposes, for all the reasons stated.

cc @bokeh/dev

**Comment by sirinath** [comment]
At least something to show version by version improvements.
