### ISSUE TITLE
Axis should have option to have a fixed orientation

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#113]
Right now axes determine the orientation of the "In" vector based on which side of the plot they're on.  For axis locations of "min" or "max", that's OK, but when a plot has a fixed position in dataspace, then it should be able to have a fixed orientation, i.e. tick labels are always above/below or always left/right of the axis.

**Comment by bryevdv** [comment]
I actually don't think this will be terrible to implement at this point but there are too many bugs left to fix for `0.12.6`, moving to next milestone

**Comment by bryevdv** [comment]
Just hard coding `loc` to return 0 demonstrates that things already "sort of work":

<img width="616" alt="screen shot 2018-04-08 at 15 41 03" src="https://user-images.githubusercontent.com/1078448/38472287-5d989962-3b43-11e8-8895-e598605ebba6.png">

As it stands, there is extra padding for the vacant-but-still-present side panels, and also the axes are not clipped at the inner plot boundary. So I would propose to add an optional `fixed_location` property to `Axis` that is what `loc` returns (if it is set). Then fix up other code paths so that: 

* if there is a fixed location, the axis is added to a render level that gets clipped
* if there is a fixed location, the side panel width/height is collapsed to zero

To be clear, this is a slight abuse of side panels, but anything else would seem to be much more work. In particular, keeping the side panel, and adding the axis to a layout on a side, provides an immediate, already working way to specify which "side" of the axis the tick labels should be drawn on. Otherewise we would need new dedicated properties for those, and then to also figure out interactions with all the existing properties. 

We could also consider an `add_axis` method to plot that would be a little more comprehensible to users than `add_layout`.

**Comment by bryevdv** [comment]
With the merged PR:
```
from bokeh.plotting import figure, show, output_file
from bokeh.sampledata.iris import flowers

colormap = {'setosa': 'red', 'versicolor': 'green', 'virginica': 'blue'}
colors = [colormap[x] for x in flowers['species']]

p = figure(title = "Iris Morphology", x_range=['setosa', 'versicolor', 'virginica'])
p.xaxis.axis_label = 'Petal Length'
p.yaxis.axis_label = 'Petal Width'

p.circle(flowers["species"], flowers["petal_width"],
         color=colors, fill_alpha=0.2, size=10)
p.yaxis.fixed_location = "versicolor"

output_file("iris.html", title="iris.py example")

show(p)
```
<img width="822" alt="screen shot 2018-04-24 at 11 50 29" src="https://user-images.githubusercontent.com/1078448/39207780-b9a705da-47b5-11e8-8f30-4a91b68475d9.png">

(works with categorical coordinates as well)
