### ISSUE TITLE
[BUG] Bokeh websocket connection creates large Sec-WebSocket-Protocol header

### ISSUE THREAD

**Issue by shughes-uk** [bokeh/bokeh#11301]
Bokeh 2021.05

Currently the Cookie header is being included in the header, as well as an extra 'cookies' section which is a copy.

All cookies are whitelisted by default, as are all headers. 

When people have a bunch of cookies this can create a header so large common webservers reject it, in our application's case the python `websockets` library.

The data would also probably compress ok, but if the cookies doubling bug is fixed and it's changed to exclude cookies/headers by default instead of include this problem should be lessened dramatically.

**Comment by philippjfr** [comment]
This is a good point, including these by default was perhaps not a good idea. At the very minimum I should have excluded the cookies header. The reason these were added in the first place was that this was the only way to guarantee that the headers and cookies would be available in a multi-process or multi-node deployment. This is because the initial request containing the HTTP headers and cookies may not arrive on the same process as the websocket connection and so to ensure these are synced we put them in the JWT token which is returned by the initial HTTP request and when the frontend opens the websocket it includes this data in websocket protocol header. However it is also easy to balloon the size of this header this way and in some cases this causes real issues, e.g. when putting the bokeh server behind nginx the default configuration will actually cause nginx to drop these messages entirely unless you configure a larger client header buffer size.

I'd be okay with going with a whitelisting approach but this needs to be communicated and handled carefully since it will mean that headers/cookies people may have relied on are no longer available to them and things will fail silently.

**Comment by bryevdv** [comment]
@philippjfr just to be clear I think @shughes-uk is saying that cookies are *duplicated* inside the token. In which case I think an immediate first step suitable for 2.4 would be to remove the duplication. I don't think there are any compatibility concerns here, if we really must we could even special-case copying the cookies section back into a header as the token is processed. 

Is there a built-in compression on both the Python and JS sides we could also try employing? That would also avoid any compat issues. Then we could leave whitelisting for 3.0 with some deprecation messages sooner. 

Thoughts?

**Comment by philippjfr** [comment]
> just to be clear I think @shughes-uk is saying that cookies are duplicated inside the token.

Yep, got that, to be even more clear the cookies are sent separately but the headers also include a 'cookies' key which contains the cookies as a single serialized string. Since this has to be parsed separately I'd favor dropping the cookies key in the headers rather than the explicit cookies.

>Is there a built-in compression on both the Python and JS sides we could also try employing?

Good question, I don't even think we need JS side compression since the frontend doesn't care about the contents of the token it includes it in the Websocket header without looking at it.

**Comment by bryevdv** [comment]
> Since this has to be parsed separately I'd favor dropping the cookies key in the headers rather than the explicit cookies.

👍 from me

> Good question, I don't even think we need JS side compression since the frontend doesn't care about the contents of the token since it includes it in the Websocket header without looking at it.

Hah! Right, I think using pythons built-in zlib or bz2 on headers and cookies is worth a shot.

Is this a PR you can take a poke at?

**Comment by philippjfr** [comment]
> Is this a PR you can take a poke at?

Yep, I'll have a go.

**Comment by bryevdv** [comment]
I think a separate issue regarding changing the allowlist for headers and cookies is probably appropriate. 

@philippjfr do you have any thoughts about where/how we might communicate a warning that behavior will change in the future? Just any time there are `extra_headers`? Unconditionally on server start until 3.0?

**Comment by philippjfr** [comment]
Definitely should open another issue or keep this one open. 

>do you have any thoughts about where/how we might communicate a warning that behavior will change in the future? Just any time there are extra_headers? Unconditionally on server start until 3.0?

There might be something smarter we can do by making the `RequestProxy` warn on access.

**Comment by bryevdv** [comment]
Seems reasonable. Let's add a comment in the 2.4 release notes as well and link to the new issue there.

**Comment by shughes-uk** [comment]
For reference i believe nginx's default max header size is 4096 

http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers

a few other common webservers also use that limit even though no official limit is defined in the http protocol

**Comment by bryevdv** [comment]
@philippjfr perhaps add a length check and warning in the PR with a note about the allow/block list options?

**Comment by philippjfr** [comment]
>For reference i believe nginx's default max header size is 4096

Right, there's already a note about that [in the docs](https://docs.bokeh.org/en/latest/docs/user_guide/server.html#basic-reverse-proxy-setup):

>To communicate cookies and headers across processes, Bokeh may include this information in a JSON web token, sending it via a WebSocket. In certain cases this token can grow very large causing Nginx to drop the request. You may have to work around this by overriding the default Nginx setting large_client_header_buffers:

```
large_client_header_buffers 4 24k;
```

I'd be +1 on adding the warning if we exceed the size.

**Comment by shughes-uk** [comment]
We don't directly control implementation of the application that is running bokeh server, so a warning would have been very appreciated.

For reference it was dask/distributed and i've flagged it with the oss team there.
