### ISSUE TITLE
[FEATURE] ColumnDataSource with Pandas groupby: Support for sum aggregation

### ISSUE THREAD

**Issue by jmerali3** [bokeh/bokeh#11408]
**Is your feature request related to a problem? Please describe.**
Currently when passing a Pandas groupby object to ColumnDataSource, Bokeh provides new columns for _std, _max, _min, _count, etc. etc. However, there is no support for _sum, which could be useful and is a common way to aggregate data. 

**Describe the solution you'd like**
A <name>_sum column created when passing a groupby object to ColumnDataSource

**Describe alternatives you've considered**
Obviously this could be done explicitly, but this functionality would add more support for Pandas

**Additional context**

*Note: Everyone interacting in the Bokeh project's codebases, issue trackers, and discussion forums is expected to follow the [Code of Conduct](https://github.com/bokeh/bokeh/blob/master/CODE_OF_CONDUCT.md).*

**Comment by bryevdv** [comment]
I am -1 on this suggestion. As it currently stands, the behavior is a simple to explain ("just the result of `.describe`") which is what makes it justifiable as a convenience. Beyond that, adding more complexity does not seem like a good idea to me: 

* What is a critieria for what to add and what not to add? Why just `sum` and not every aggregation? 
* If we make `sum` happen unconditionally we impose the cost on everyone, all the time, whether they want/need those values or not
* If we make it configurable, the feature is no longer nearly as simple to explain, docs, testing,  and maintenance burden increase. 
* Speaking from experience: this will manufacture support burden&mdash;people using older Bokeh versions referring to recent examples will expect `_sum` to exist and file bug reports or questions when it doesn't. 

But mostly, it's better for users to just ask for what they want explicitly (for anything beyond `grp.describe`) especially since it is just a one-line operation: 

```
In [7]: df = pd.DataFrame({'A': [1, 1, 2, 2], 'B': [1, 2, 3, 4], 'C': np.random.randn(4)})

In [8]: agg = df.groupby('A').agg({'B': ['min', 'max'], 'C': 'sum'})

In [9]: source = ColumnDataSource(agg)

In [10]: source.data
Out[10]:
{'A': array([1, 2]),
 'B_min': array([1, 3]),
 'B_max': array([2, 4]),
 'C_sum': array([-0.66656438, -0.63278423])}
```

cc @bokeh/dev

**Comment by jmerali3** [comment]
That makes sense - this could be a slippery slope and does impose a memory cost. That being said, I am surprised the percentiles were included and not sum.

I agree with your counter-suggestion. This would make it a bit easier for newer users to understand 1) how that class handles groupby objects and 2) which aggregation methods are included by default (without calling .column_names) and which need a bit more work to obtain.

**Comment by bryevdv** [comment]
>  That being said, I am surprised the percentiles were included and not sum.

I'm inclined to agree, but that is a question for Pandas devs about `GroubBy.describe` :) 

> I agree with your counter-suggestion. 

:+1: @tcmetzger do you think this might make a `Good First Issue`?

**Comment by tcmetzger** [comment]
> make sure this usage pattern is explicitly demonstrated in the docs/examples.

Yes, that would be a very good first issue, I think!

**Comment by bryevdv** [comment]
OK let's keep this closed and we can use this to help generate the new GFI template.
