### ISSUE TITLE
[BUG] SVG export breaks for Wedges 

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#11475]
#### Software version info
* bokeh v2.3.2
* python v3.6.13
* ipython: v7.24.1

#### Description
When I draw a wedge where the start angle is 0 and the end angle is equal to `2 x pi` the export to `svg` breaks apart, while the export to an `png` and `html` file is working. This is not the case if I round the end angle (e.g. to six digits) the get close to `2 x pi`.

If I show the figure before the export in a jupyter notebook the figure looks fine. After the failed export, the output is a plain white figure. These outputs are a similar representation of the exports.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import pandas as pd
import numpy as np

from bokeh.plotting import show, output_notebook, figure
from bokeh.io import export_png, export_svgs
output_notebook()

df = pd.DataFrame({'start':[0], 'end':[2*np.pi]})

p = figure(
    tools="",
    match_aspect=True,
    plot_width=300,
    plot_height=300
)

p.rect(x=1, y=1, width=2, height=2, alpha=0)

p.wedge(
    x=1,
    y=1,
    radius=1,
    start_angle="start",
    end_angle="end",
    line_color='white',
    source=df,
)


p.xgrid.visible = False
p.ygrid.visible = False
p.xaxis.visible = False
p.yaxis.visible = False

show(p)
export_png(p, filename='cake' + ".png")
p.output_backend = "svg"
export_svgs(p, filename='cake' + ".svg")
show(p)
```

![failed_svg_export](https://user-images.githubusercontent.com/68053396/128147319-0003c1c2-a69a-4ec6-b9b8-5251a9d8f667.PNG)

**Comment by mosc9575** [comment]
@mattpap I am sorry for the missing DataFrame `df`. I have updated the code and the example should be reproducible from now on.

**Comment by mattpap** [comment]
@ianthomas23, this would a good issue for you to tackle. I did some preliminary exploration, but I'm not set on a solution. The problem is that angles are stored as float32 when used in data arrays (vs. scalar angles which are float64), so full circle detection doesn't work reliably. SVG doesn't support drawing full circles with arc path, so either the current (inherited from the original) can be improved, or circles could be drawn in two steps (half circles).
