### ISSUE TITLE
[BUG] line dis- / appears depending on range

### ISSUE THREAD

**Issue by allefeld** [bokeh/bokeh#11498]
I stumbled upon this very strange bug, where the visibility of a line glyph depends on the range of one of the axes. It happened seemingly randomly with data I was plotting, and seems to be triggered by large differences / changes in the order of magnitude, though I wasn't able to determine the exact conditions under which it occurs.

I was able to distill it into the following example, where the same data is displayed in two plots, both times as a circle glyph and a line glyph, with the only difference being the y-axis range:

```python
from bokeh.plotting import figure, show, gridplot

y = [0.2, 1, 1.9, 8e7]

p1 = figure(y_range=(0, 2))
p1.circle(x=range(len(y)), y=y)
p1.line(x=range(len(y)), y=y)

p2 = figure(y_range=(0, 3))
p2.circle(x=range(len(y)), y=y)
p2.line(x=range(len(y)), y=y)

show(gridplot([[p1, p2]]))
```

With `y_range=(0, 2)`, only the circles are visible (left), but with `y_range=(0, 3)` both circles and line are (right):

![Screenshot_20210812_161259](https://user-images.githubusercontent.com/1738353/129221947-71902981-4196-4dd2-9de7-2e6d5533a0bd.png)

There are no pertinent error messages either from Python or in the JavaScript console.

Python 3.8.10, conda 4.9.2, Bokeh 2.3.3  
The bug occurs in both the notebook (VS Code 1.59.0) and the browser (Chrome 92.0.4515.131)  
Debian 10.10

**Comment by bryevdv** [comment]
In my experience, this is an artifact/limitation of the underlying HTML canvas, which will simply not draw lines where one or more coordinates are far outside the canvas viewport. I've never been able to characterize "how far" outside can cause a problem, and I would also 100% assume it varies by browser implementation as well.

Actually fixing this would require manually intersecting every individual line segment with the viewport, and generating and drawing synthetic segments that intersect the viewport border any time one or both ends lies outside. I expect that would absolutely tank performance for the vast majority of cases that would not otherwise run into this, due to the extra computation but also because drawing could not use efficient poly-lines for entire lines. Another side effect would be losing consistent joins, caps, and dashing across an entire line, that would definitely be impossible to preserve. I am not sure there is a good solution, unfortunately. If this is your use-case, you might be better off looking for other tools. 

You might try the webgl or svg backends, in case they do not suffer the same limitation.

cc @bokeh/dev

**Comment by bryevdv** [comment]
Here is an example anyone can run at https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_canvas_lineto to see different browser results:
```
<!DOCTYPE html>
<html>
<body>

<canvas id="myCanvas" width="300" height="150" style="border:1px solid #d3d3d3;">
Your browser does not support the HTML5 canvas tag.</canvas>

<script>
var c = document.getElementById("myCanvas");
var ctx = c.getContext("2d");
ctx.beginPath();
ctx.moveTo(0, 0);
ctx.lineTo(100, 50);
ctx.lineTo(200, 15000000000);
ctx.stroke();
</script>

</body>
</html>
```
As written above, it functions on Chrome, FF, and Safari on OSX:

<img width="1698" alt="Screen Shot 2021-08-12 at 09 40 29" src="https://user-images.githubusercontent.com/1078448/129235146-a393dd0a-c9b5-46a0-91fc-360d2c81ccfc.png">


But add one more zero to the y-coordinate and Safari breaks:

<img width="1692" alt="Screen Shot 2021-08-12 at 09 40 49" src="https://user-images.githubusercontent.com/1078448/129235204-77d13257-4150-4a21-8f48-6e699d97d48a.png">

**Comment by bryevdv** [comment]
I guess all I can really suggest for this is:

* check if svg or webgl backend avoids this problem
* add appropriate guidance/warning to the docs for `line` 

cc @tcmetzger

**Comment by mattpap** [comment]
> check if svg or webgl backend avoids this problem

SVG behaves worse than canvas, and webgl works perfectly, at least in this setup.

**Comment by bryevdv** [comment]
@allefeld can you check with `output_backend="webgl"` on your setup?

**Comment by ianthomas23** [comment]
WebGL backend does suffer from the same problem but only if you zoom in by ~4 orders of magnitude.  This is a known weakness of the current handling of NaNs that is on my list of problems to address.  I've added it as a new item to issue #11050.

**Comment by allefeld** [comment]
`output_backend="webgl"` seems to help, at least in this example. I'll try in in my regular code, thanks!

The strange thing is that it isn't triggered simply by points far outside of the viewport. In my example, if the first number (0.2) is changed to 0.4, lines disappear in both plots, though the large number and the y-range are the same, and the data range is actually slightly smaller.

**Comment by allefeld** [comment]
Unfortunately, in my actual application, WebGL doesn't seem to be an option.

I'm creating a large HTML file with a report on simulation results, which contains 216 plots in total divided over tabs (6 visible at a time, 4 lines in each plot). This file takes a few seconds to render with the canvas backend. With WebGL it takes much longer, so long that Chrome asks me whether I want to abort. When it's finally ready, there are some strange antialiasing artifacts:

![Screenshot_20210813_100504](https://user-images.githubusercontent.com/1738353/129333267-618c8efb-32de-4144-9782-36debb053e20.png)

Datashader doesn't seem appropriate, because each line only has about 100 points, and overplotting is not an issue.

I guess I will have to manually filter out large values, which occur only occasionally.

Thanks for your help!

**Comment by bryevdv** [comment]
> and the data range is actually slightly smaller.

This is consistent. Your example evidently lies very close to straddling the limit exact limit. Making the data range smaller has the effect of making the mapped canvas coordinates, for the same data coordinate outside that range, *larger* (pushing it over the limit)

As for webgl, we have given any consideration to having hundreds of webgl plots on a single page, my suggestion was on the the assumption that there were ~1s of plots. :)

**Comment by jbednar** [comment]
> Datashader doesn't seem appropriate, because each line only has about 100 points, and overplotting is not an issue.

Datashader doesn't have any minimum data size, and doesn't use any heuristics to cull points that are far from the viewport, so it wouldn't be crazy to use it in a case like this where you want predictable behavior for widely ranging inputs. In that case you'd just be using it as an alternative rendering system that doesn't try to be smart about anything, which may be what you want here.

**Comment by tcmetzger** [comment]
I opened #11514 to add a note to the docs. 

I also tried to reproduce this behavior locally: the original example code worked fine in Firefox 91.0 on Win10 and Ubuntu 20.04 - but did not render the last line segment in Chrome on Win10 or Chromium on Ubuntu 20.04. 
Interestingly, setting `output_backend="webgl"` for `p1` and `p2` leads to the last line segment being rendered downward instead of up in Firefox 91 (Ubuntu and win10):
![image](https://user-images.githubusercontent.com/39711796/129622048-ddd6573b-7d1b-4861-bec4-4ef9f7169d76.png)

**Comment by bryevdv** [comment]
marking this  for closure as `upstream` pending #11514

1.
