### ISSUE TITLE
[FEATURE] Support xyzservices in basemap tiles

### ISSUE THREAD

**Issue by martinfleis** [bokeh/bokeh#11500]
**Is your feature request related to a problem? Please describe.**

With the @geopandas team, we have built a new package called [`xyzservices`](https://github.com/geopandas/xyzservices) to serve as a unified place for XYZ tile management. The idea behind this is that other packages will depend on that instead of having their own system and list of supported tiles hard-coded. It would be great to have bokeh on board with the idea, either by supporting `xyzservices.TileProvider` as an input of `add_tile` or even refactoring `tile_providers.py` module to depend directly on `xyzservices`.

`xyzservices` itself does not have any dependencies which makes it a non-problematic dependency.

It is worth mentioning that `xyzservices` stores providers' metadata in JSON under `share`, accessible for anyone if you have a use case for that.

I am happy to do any changes in `xyzservices` needed to make it as useful for you as possible if that allows centralising maintenance of providers in one place.

**Describe the solution you'd like**

1) support `TileProvider` as an input of `add_tile `. 

```py
import xyzservices.providers as xyz

p = figure(x_range=(-2000000, 6000000), y_range=(-1000000, 7000000),
           x_axis_type="mercator", y_axis_type="mercator")
p.add_tile(xyz.CartoDB.Positron)
```

All the info `Tiles` require can be fetched from the `TileProvider` object under the hood.

2) refactor tile management

You can remove a big chunk of the maintenance burden by refactoring tile management in `tile_providers.py` using `xyzservices` directly. In the first step, you can remove all metadata and simply map your existing classes to TileProvider objects. In the second, you can even dynamically support the whole `xyzservices` library of providers instead of the pre-defined set you have now.

**Describe alternatives you've considered**
I know that 2) may sound like a bit ambitious proposal but 1) is pretty straightforward to implement already. So I'd say that having at least the first part would be nice.

Currently, you can extract metadata from the `xyzservices.TileProvider` manually and pass it to `WMTSTileSource` but all that can be skipped.

**Additional context**
Support of `xyzservices` is being implemented across the ecosystem, from geopandas' own packages (new built-in foilum-based plotting and `contextily`) to `leafmap`, `ipyleaflet`, `folium`, and `holoviews`. See https://github.com/geopandas/xyzservices/issues/49 for details.

Your tile management is very similar to the one in `holoviews` hence the proposal is essentially the same here as it is over there. 

If there's anything we would need to implement in `xyzservices` to make all this work, I am all ears.

I am keen to prepare a PR if there is an interest from your side.

**Comment by bryevdv** [comment]
cc @bokeh/dev @brendancol

Thanks for the issues @martinfleis We normally try to avoid new dependencies, but if `xyzservices` is completely self-contained and available on both pip and conda that would go a long way towards easing concerns there enough to at least consider it. I guess my main observation would be that ultimately a Bokeh *Model* has to be what goes in the Bokeh *Document* to be serialized, so there would always be a level of adaptation from any external sources to configure a Bokeh model.

As @jlstevens said it's an easy decision to start with option 1) in the immediate term, so 👍  to that. We are gearing up for a 3.0 release cycle so that would be a natural point in time to consider something a bit more ambitious. I guess what I would like to see is a more detailed proposal of changes for 2) or even a POC pull request. 

In general though, I would love to get out of the business of maintaining these tile provider metadata entirely. I'm definitely sympathetic to that goal.

**Comment by martinfleis** [comment]
@bryevdv Thanks for the reponse!

Option one should be relatively straightforward and there's even no need to import `xyzservices`. What we're doing elsewhere is to do `isinstance(input, dict)` and assume it is a `TileProvider` object, which itself is a subclass of a dict. I'll try to send a PR over the weekend.
 
Regarding option 2, I'll have to look in more detail in bokeh internals to properly understand where should this be processed and in which way but I can try to work out a POC PR.

**Comment by martinfleis** [comment]
> I guess my main observation would be that ultimately a Bokeh Model has to be what goes in the Bokeh Document to be serialized, so there would always be a level of adaptation from any external sources to configure a Bokeh model.

@bryevdv This made me think about the API here, where should the support actually live. Because now, you have something like this:

```py
from bokeh.tile_providers import CARTODBPOSITRON, get_provider

tile_provider = get_provider(CARTODBPOSITRON)

# range bounds supplied in web mercator coordinates
p = figure(x_range=(-2000000, 6000000), y_range=(-1000000, 7000000),
           x_axis_type="mercator", y_axis_type="mercator")
p.add_tile(tile_provider)
```

Where `get_provider` takes `CARTODBPOSITRON` which is a string and creates a `WMTSTileSource`. Should the `xyzservices` support like in `get_provider` then? As
```py
tile_provider = get_provider(xyz.CartoDB.Positron)
```
Rather than in `add_tile` as suggested above. It seems to be more in line with the current API. But I'd rather hear your thoughts on that.

**Comment by bryevdv** [comment]
>  What we're doing elsewhere is to do isinstance(input, dict) and assume it is a TileProvider object, which itself is a subclass of a dict. I'll try to send a PR over the weekend.

If you use our `import_optional` function you can conditionally import the library and skip the related code if the import returns None. We do this in places that can utilize pandas, for example. I think that would be a more robust approach (you can code grep for examples of using `import_optional`)

> Should the xyzservices support like in get_provider then? 

I think that's reasonable to do now for option 1) as it will not affect any compatibility. For a future 3.0 it might be nice to move users away from having to do an explicit `get_provider` step all the time. e.g. if we stop maintaining all tile metadata completely, then this seems possible
```python 
# construct a and return a new tile source internally 
p.add_tile(xyz.CartoDB.Positron)
```
but we would still need to accept manually configured tile sources, since some user run their own custom tile servers, etc. 
``` python
custom_tile_source = WMTSTileSource(...)
p.add_tile(custom_tile_source)
``` 

That's more or less within my bounds of acceptability, but we should poll a wider group, since it is at least slightly warty from a pure API cleanliness perspective to had `add_tile` operate on inputs at two different levels (i.e accepting both fully constructed tile sources, a well as other things it can *turn into* tile sources automagically)

**Comment by martinfleis** [comment]
> but we would still need to accept manually configured tile sources, since some user run their own custom tile servers, etc.

You can also pass a custom `xyzservices.TileProvider` in that case.

```py
p.add_tile(xyzservices.TileProvider(url="https://my_tiles.org/{z}/{x}/{y}.png", attribution="My attribution", name="My tiles"))
```

I am not using Bokeh on a daily basis so I don't have a fixed mental model of your API so this will be eventually up to you to make the API decision.

**Comment by bryevdv** [comment]
@martinfleis That might work. When you submit a POC for option 2, I'd say start with that and we can solicit feedback.

I guess the main question is whether we want to allow/encourage users to modify tile source objects in place (e.g. in a Bokeh server app) and I think I might be inclined to say no (e.g. it would be better to encourage having multiple renderers that are toggled between, or for a single renderer to swap out entire tile sources to make updates)
