### ISSUE TITLE
[BUG] Placement of toolbar location is broken for gridplots

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#11623]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
python:  3.6.
bokeh: 2.3.2

#### Description of expected behavior and the observed behavior
If creating a gridplot with multiple figures the option to place the toolbar location is broken. 

First of all I think it should also accept `None` to hide the toolbar, if wanted. Right now it only supports `above`, `below`, `left` and `right`.

Furthermore the placement of the toolbar looks odd. For example `above` and `below` both return the exact same output. In both cases the toolbar is horizontal  and above the two figures. For `left` and `right`, the toolbar is vertical and above the two figures, too.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.layouts import gridplot
from bokeh.plotting import figure, show, output_notebook
output_notebook()

p1 = figure(width=300,height=300)
p1.line([1,2,3,4], [4,3,2,1])

p2 = figure(width=300,height=300)
p2.line([1,2,3,4], [4,3,2,1], color='red')

p = gridplot([[p1],[p2]])

p.children[0].toolbar_location = 'below'
show(p)
```
 |`p.children[0].toolbar_location = 'below'`|`p.children[0].toolbar_location = 'right`|
|--|--|
|![below](https://user-images.githubusercontent.com/68053396/133603239-d3b82dff-1ec9-4fba-ab86-63bea453e6f6.PNG)|![right](https://user-images.githubusercontent.com/68053396/133603289-008ce1e4-93a1-4f5b-9e18-f7754f3e7211.PNG)|

**Comment by mattpap** [comment]
It works when set as a keyword argument:
```py
p = gridplot([[p1],[p2]], toolbar_location="below") # or "right"
```

**Comment by mattpap** [comment]
> bokeh: 2.3.2

btw. 2.4 is now available, but the behavior is the same.

**Comment by mattpap** [comment]
It makes sense it works like this. Setting `toolbar_location` on a grid plot does two things. First it sets toolbar's location (for knowing its orientation and styling), then it arranges the toolbar and grid container accordingly. So if you change toolbar's location after calling `gridplot()`, but don't rearrange the layout, then this is the expected outcome. In bokeh 3.0 proper support for grid plots (i.e. `GridPlot` model) will be added, so changing toolbar location after creating a grid plot will make sense. I will keep this open as a bug, so that we cover and test this use case.
