### ISSUE TITLE
Document requirement of PEP 604 (py 3.10) type annotation syntax

### ISSUE THREAD

**Issue by douglas-raillard-arm** [bokeh/bokeh#11637]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh 2.4.0

#### Description of expected behavior and the observed behavior

Bokeh 2.4.0 uses PEP 604 annotations such as `int | None`. This PEP has been added to Python 3.10 and tooling working with previous versions of Python can choke on that, leading to a breaking change. To prevent breakage, bokeh 2.4.0 should probably require Python >= 3.10 or avoid using this new syntax, preferring the backward-compatible one (I think `Union[int, None]` is equivalent but I'm not 100% sure).

**Comment by mattpap** [comment]
This new syntax is used only in type contexts (i.e. in annotations). Additionally we use lazy annotations exclusively across the codebase, which effectively makes them behave like string literals, so `|` operator is not needed to be present at run-time. Thus where is no real danger for any tools, that aren't type checkers or similar, to have an issue with this codebase. However, as far I can tell, any popular type checker already supports this syntax, including our type checker of choice: mypy. The only real caveat are type aliases which have to use `Union[...]` syntax as they are a part of the run-time behavior, but those are easy to catch, as they would otherwise prevent our tests from running.

**Comment by bryevdv** [comment]
@douglas-raillard-arm can you be more specific with concrete examples of actual cases where there is a problem?

**Comment by douglas-raillard-arm** [comment]
@bryevdv The tool in question that failed on it is `exekall`, documented at https://lisa-linux-integrated-system-analysis.readthedocs.io/en/master/exekall/index.html

The fix was simple on my side but that should probably still be reported as breaking change in the changelog. I suppose older versions of mypy would choke on that as well. I can understand if type annotations are excluded of the usual semantic versioning guarantees since not many tools are impacted, but making use of a feature (PEP 604) even before the version of Python implementing is out is maybe a bit too soon. `mypy` maybe handles that, but the Python standard way of processing annotations `typing.get_type_hints` does not handle that before 3.10 and raises an exception:

```
def foo() -> "int | None":
    pass

import typing
x=typing.get_type_hints(foo)
print(x)
```

```
$ python3.9 testannot.py
Traceback (most recent call last):
  File "/home/testannot.py", line 6, in <module>
    x=typing.get_type_hints(foo)
  File "/usr/lib/python3.9/typing.py", line 1469, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/usr/lib/python3.9/typing.py", line 290, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/lib/python3.9/typing.py", line 551, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

Maybe the standard lib is not a popular type checker but it's still what most people will turn to when there is a need to process such annotation.

**Comment by bryevdv** [comment]
@douglas-raillard-arm thank you for the additional details

@mattpap do you have any new thoughts? 

My own feeling is that I am inclined to close this without any particular action:

* The type hints and mypy checks, are, first and foremost, for the maintainers of Bokeh, to be able to better maintain the project itself. 

* The usage described above, in my experience, is extremely atypical. I've never once, in thousands of support requests, been asked about use of `get_type_hints` with Bokeh. I've also never heard of the tool that was mentioned 

* Editors and IDEs (vscode, etc) have to be pro-active about extending support ahead of Python releases, and AFAICT, have done so (e.g. I use vscode and have not noticed any issues at all or even thought about this change)

Given all of the above, and:
* over time the issue, such as it is, will simply away itself (and faster now that Python has increased their release cadence and pydata/scipy have settled on ~3-4 releases of support)
* making an actual code changes would be non-trivial effort 

I just can't personally justify the effort to switch to `Union` everywhere. 

For the future @douglas-raillard-arm I would mention that for large releases, we publish "dev" builds for months leading up to the release. I would encourage anyone doing things that are outside typical usage to be pro-active and engage with those dev builds early. If you would like to add a sentence in the release notes, we'd certainly accept a PR. The relevant file is here (standard Sphinx ReST): https://github.com/bokeh/bokeh/blob/branch-3.0/sphinx/source/docs/releases/2.4.0.rst

**Comment by douglas-raillard-arm** [comment]
Sounds good, I mainly wanted to raise awareness since I managed to implement a blanket fix for all future PEP like that that are extending what is accepted by a call to eval(). Hopefully python will soon reach a point where a sane ecosystem around type annotations can be supported. Even basic tools were lacking in the standard lib to e.g. inspect generic args until 3.8, which made all generic either a complete black box or forced into using private attributes.

I unfortunately cannot afford to track dev builds of all dependencies as it represents approx. 5000 modules, so my current approach is to not pin any dependency in GitHub CI so I catch these sort of issues as early as possible, without the extra failures that would necessarily follow from allowing dev versions in pip. The tool walks over all dependencies so I end up parsing annotations of a non negligible subset of scientific python packages, even if they are not directly used in the end.

Thanks for looking into that.

**Comment by mattpap** [comment]
> `typing.get_type_hints`

I wasn't aware of this API when introducing the new syntax, though I'm not sure if it would make any difference to the decisions that were made. In any case, Python 3.10 is just around the corner (4 Oct), so we will make it official that 3.10 is the minimum for static typing purpose, though we will obviously keep run-time syntax and semantics compatible with older supported versions (currently that's >=3.7).

**Comment by bryevdv** [comment]
cc @tcmetzger This best place for documenting this min requirement is probably the contributor's guide, though I am not sure exactly where.  It's not a min requirement to run mypy since mypy can already handle this just fine. But if somone wants to run other specialized or custom typing tools over the codebase, then it (may) apply.

**Comment by tcmetzger** [comment]
@bryevdv I'll include this when I update the remainder of the contributor guide (i.e. the current chapters 'Working with Bokeh models', 'Understanding Bokeh server', and 'Contributing to BokehJS'). I'm thinking about reorganizing things into a section for Python development (that's where info on typing would go), a section for JavaScript, and a separate section for Bokeh's model structure (because the models are relevant both to the TS and Python code).

**Comment by analog-cbarber** [comment]
Well, obviously I am one of those users. Sure I can use 3.10, but if I have a library that supports >=3.7, I find that just in order to build my API documentation I have to either find some hack around this or resort to using 3.10 to build my documentation even though we are mostly not using 3.10 yet.

The fact is that your code is using 3.10 syntax but isn't really 3.10 yet. I know that it looks nicer that way, but it really isn't strictly correct.

I wish this was something that could be fixed by some backport but I am unaware that one exists.

**Comment by bryevdv** [comment]
Why are you building your own versions of the Bokeh docs? I would say that in general, that is just not a good idea. The Bokeh docs rely on several custom sphinx extensions, especially to extract all the type and helpstring  information for thousands of properties on Bokeh models. So if you are building docs with other tools they will absolutely not be complete.

**Comment by bryevdv** [comment]
@analog-cbarber Why don't you describe your actual situation and use case in some details, since currently I don't know whether you are trying to deploy your own version of the entire docs, or you are just trying to include docs for a handful of functions as a convenience for your users. That definitely matters as to whether there is some potential compromise or alternative guidance that might be available to offer.

**Comment by analog-cbarber** [comment]
I have a subclass of a bokeh class in our own library, and it is that class that needs to be documented. I am not building bokeh's documentation.

**Comment by analog-cbarber** [comment]
It's only one class, so I will just figure out some way to hack around it.

**Comment by bryevdv** [comment]
@analog-cbarber may I ask what class? Is this for a custom extension? Or something else? Bokeh models are typically used more like building blocks to assemble via composition so I would genuinely like to understand if there is some use that is more common than we judged.

**Comment by analog-cbarber** [comment]
bokeh.application.handlers.Handler
