### ISSUE TITLE
[FEATURE] Include glyph sizing in plot range calculations

### ISSUE THREAD

**Issue by g-parki** [bokeh/bokeh#11704]
A nice convenience would be to take the glyph size into account for auto ranged plots. In the example below, the circles in the left plot are out of range because the plot is apparently scaled to the x/y coordinates (black).

A tangential observation... The inconsistent sizing/overlap can be partially addressed with `circle.radius_dimension` (see #626), but it doesn't seem robust for a packed circle application like this...

**Screenshot of auto ranged output vs desired**
![image](https://user-images.githubusercontent.com/61096711/135353815-52f5b059-8864-430b-8105-8622e8773bfc.png)

**Example Code**
```
from bokeh.plotting import figure
from bokeh.layouts import row
from bokeh.io import show

x = [0.4595279480396895, -0.6065711356206639, -0.0687886392916304, -0.07637863162673651, -0.5244521855365748, 0.46832138015416175]
y = [0.604836077992458, 0.5442297884573969, -0.6203208740702811, 0.624789852804971, -0.08487633209696635, -0.08487633209696635]
r = [0.16571899322942416, 0.16571899322942416, 0.23436204776786676, 0.37055893402381984, 0.4687240955357335, 0.5240494701550029]

#Auto ranging
a = figure(width=500, height=500, title="Auto Ranged Figure")
a.circle(x=x, y=y, radius=r, radius_units='data')
a.circle(x=x, y=y, radius=.01, radius_units='data', color="black")

#Manually ranging
global_min = min([min((y-r, x-r)) for (x, y, r) in zip(x,y,r)]) - 0.1
global_max = max([max((y+r, x+r)) for (x, y, r) in zip(x,y,r)]) + .1
range = (global_min, global_max)

p = figure(width=500, height=500, y_range=range, x_range=range, title= "Manually Ranged Figure")
p.circle(x=x, y=y, radius=r, radius_units='data')
p.circle(x=x, y=y, radius=.01, radius_units='data', color="black")

show(row(a,p))
```

**Comment by bryevdv** [comment]
A few comments:

* There is some inconsistency across different glyphs. Some currently perform better under auto-ranging than others.
* In a practical sense, anything using circles with a data-space radius really has to use `match_aspect=True`, since otherwise the circles radius will be wrong in one dimension. 

Can you try with `match_aspect=True` ? I believe that will solve the problem and is the correct solution to the problem. Perhaps we can add even yet more documentation support around `match_aspect` and "real circles".

**Comment by bryevdv** [comment]
For the (very old) background, see the ancient issue https://github.com/bokeh/bokeh/issues/517

**Comment by g-parki** [comment]
Nice. `match_aspect=True` looks like it works great with the automatically scaled plot.

![image](https://user-images.githubusercontent.com/61096711/135358822-30ad7bf5-b7d7-45c5-8a26-e518f7588438.png)

**Comment by g-parki** [comment]
> anything using circles with a data-space radius really has to use `match_aspect=True`, since otherwise the circles radius will be wrong in one dimension. 

Perhaps it makes sense to code that in as the default for data-space-radius circles. I think it's a safe assumption that if the user is providing radius data, then the circle size is a meaningful part of the visualization and should scale consistently.

**Comment by bryevdv** [comment]
> Perhaps it makes sense to code that in as the default for data-space-radius circles. I think it's a safe assumption that if the user is providing radius data, then the circle size is a meaningful part of the visualization and should scale consistently.

Unfortunately that's easier contemplated than done. The benefits of a highly modular building-block system is that the blocks can be easily assembled in many ways. One of the downsides is that not all the combinations make sense. This is the sort of thing a higher level library could do easily, because they could have a "bubble chart" chart type where the assumption of matched aspect can be baked in from the start. But in pure Bokeh we have no such luxury, there is just a plot container, into which a user can dump whatever glyphs they want, and we can't know ahead of time what those might be. In fact, a user could even add a circle glyph, and then remove it. Or change it from data radius, to screen size. The only point in time we can say with absolute certainty "this is a plot with data-space radius circles" is right at the point of serialization just before the content is output. That's a pretty awkward time to go changing values invisibly and implicitly. 

We *do* have a way to "validation checks" right at serialization time, to warn or error. E.g. an empty plot with no glyphs, or mismatched ranges and scales. I suppose we could issue an actionable validation warning in this case, that would be better than nothing.

**Comment by mattpap** [comment]
This is a known deficiency of `Circle` glyph (among others), and with a simple patch:
```diff
diff --git a/bokehjs/src/lib/models/glyphs/circle.ts b/bokehjs/src/lib/models/glyphs/circle.ts
index 0713b9591..693278cca 100644
--- a/bokehjs/src/lib/models/glyphs/circle.ts
+++ b/bokehjs/src/lib/models/glyphs/circle.ts
@@ -97,6 +97,16 @@ export class CircleView extends XYGlyphView {
     }
   }
 
+  protected override _bounds({x0, x1, y0, y1}: Rect): Rect {
+    const {max_radius} = this
+    return {
+      x0: x0 - max_radius,
+      x1: x1 + max_radius,
+      y0: y0 - max_radius,
+      y1: y1 + max_radius,
+    }
+  }
+
   protected override _mask_data(): Indices {
     const {frame} = this.renderer.plot_view
```
this can be achieved:
![image](https://user-images.githubusercontent.com/27475/135415761-e1c4570f-944b-4b0f-8d59-ec674c40908c.png)
Tighter bounds will require more computational effort, but are feasible.

**Comment by mattpap** [comment]
Of course this patch will require quite a bit of refinement to make it fully usable.
