### ISSUE TITLE
[FEATURE] Add function to get adjacent nodes by selecting node.

### ISSUE THREAD

**Issue by yakpanda** [bokeh/bokeh#11806]
It would be great to have way to get values of adjacent nodes when selecting a node.
The purpose is to see which nodes are connected each other more clearly.

As discussed in https://discourse.bokeh.org/t/networkx-get-value-of-selected-node-and-adjacency-node/8618:
`NodesAndAdjacentNodes` will be the function for this case.

**Comment by bryevdv** [comment]
I do just want to clarify one thing. Due to the way that selections work generally in Bokeh, the best we are really going to be able to do here is set a single selection that has the "original" node, plus all the adjacent nodes, but no indication of what the "original" node is. 

Doing anything else would be substantially more involved than just adding a new `NodesAndAdjacentNodes` selection policy (i.e. re-vamping selections at a very low level)

**Comment by yakpanda** [comment]
@tcmetzger What do you mean PR?
@bryevdv Understand. That will be enough.

**Comment by tcmetzger** [comment]
@yakpanda I was wondering if you are interested in implementing this idea (or further investigating possible implementations), as outlined by Bryan above and in https://discourse.bokeh.org/t/networkx-get-value-of-selected-node-and-adjacency-node/8618/2. You can find all information about contributing to Bokeh at https://docs.bokeh.org/en/latest/docs/dev_guide.html, including instructions on how to make a Pull Request (PR): https://docs.bokeh.org/en/latest/docs/dev_guide/pull_requests.html 😀

**Comment by crystalmdsouza** [comment]
Hi there! I would love to take a crack at this feature if it is still available! :)
