### ISSUE TITLE
Tests using headless chrome are completely broken

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#11822]
There must have been major changes in Chrome 96, which makes our tests hang.

**Comment by ianthomas23** [comment]
I experienced the hang on running `node make test:integration` earlier today. I assumed it was my fault so did a `git clean -fxd` on the latest `branch-3.0` and the headless tests now run using `HeadlessChrome/96.0.4664.45` but give me 121 failures. Mostly minor text position changes, but also all of the WebGL tests are falling back to using canvas.

**Comment by mattpap** [comment]
After reading this comment, I retried running bokehjs' tests and it worked (well, tests fail and webgl doesn't work), but it magically started to work. I touched nothing in the repository or the OS at the time (no automatic updates in my VMs). CI (linux, as other platforms are still on 95) still doesn't work though.

**Comment by mattpap** [comment]
At least locally I was able to `snap revert chrome` to 95. snap keeps two previous versions. However, I can't (or at least I don't see an option for this), to install an older version (than provided by `latest/stable` channel). I think that, at least on Linux, whenever we upgrade Chrome in bokehjs' tests, we will have to do `snap download chrome` (assuming we'll still use snap), store it in S3 (or something) and download it and install from file.

**Comment by bryevdv** [comment]
At this point I would propose starting to think about compromise alternatives that can offer more stability. What about creating a docker image for running the chome tests, that we only update on a schedule of our own choosing? This could also greatly streamline the process for local development, allowing creating/updating images and baselines purely locally rather than having to navigate the convoluted web UI for GH actions, download and unzip files in just the right place, etc.

**Comment by ianthomas23** [comment]
@bryevdv: @tcmetzger, @IuryPiva, @mattpap and I talked a bit yesterday in our regular update meeting about the possibility of creating the docker image in CI on a regular basis (weekly?) and tagging each image with both the date of creation and the version of chrome. Then you could `docker pull bokeh-dev:chrome94` or similar and relatively easy compile bokeh and run the tests locally with a specified chrome version. This isn't exactly the same as what you are proposing, but is looking in a similar direction.

**Comment by bryevdv** [comment]
> weekly?

I would do this even less frequently. The churn in baseline images is also large burden. We need to confront the actual reality the the browsers are responsible for changes, which obviates the value of the baselines. For the baseline images to have any actual value we need to fix the chrome version for longer stretches. I would say monthly, quarterly, or even (at the extreme) fix the version for entire release branches throughout their life as a default (with manual updates only in case of some exceptional need)

**Comment by ianthomas23** [comment]
@mattpap Thanks for the comment about `snap revert`, I didn't know about this. Now I am back with 95.0.4638.69 and my dev system is functional again.

**Comment by mattpap** [comment]
I need to create s3 bucket for chromium's snaps, but I'm getting "access denied", despite having the right credentials. Is this intentionally disabled? Do I need to use the console for this?

**Comment by bryevdv** [comment]
@mattpap I assume you are using the credentials for `bokeh-ci-user` ? That account does not have `s3:createBucket`

You can tell me what bucket you need (fastest) or I can make you a console login account (you will have to ping me on Slack to exchange credentials)

**Comment by mattpap** [comment]
`bokeh-chromium` or really whatever. I just need to put there the relevant snaps for chromium.

**Comment by mattpap** [comment]
With public read access, so that snaps can get easily fetched without need for installing awscli.

**Comment by bryevdv** [comment]
We should definitely never have any S3 buckets with public read access, given the possibility for accidental or intentional abuse. 

I can create a bucket and put it behind a new cloudfront distribution. What is a good domain name? `snaps.bokeh.org` is very narrow, could we use more general `files.bokeh.org`?

**Comment by bryevdv** [comment]
How big are these snap files? Even with cloudfront there may be non-trivial exfiltration costs

**Comment by mattpap** [comment]
Actually nevermind, I don't have patience anyway to deal with aws. I created `bokeh/chromium` repository and use LFS to store binaries. This approach is implemented in PR #11823.

**Comment by mattpap** [comment]
Fixed by PR #11823.

**Comment by bryevdv** [comment]
@mattpap I am afraid that may not be an option without more plannin

> 
> Git LFS has been disabled on the organization bokeh because you’ve exceeded your data plan by at least 150%. Please purchase additional data packs to cover your bandwidth and storage usage:
> 
>  https://github.com/organizations/bokeh/billing/data/upgrade
> 
> Current usage as of 20 Nov 2021 05:59PM UTC:
> 
>  Bandwidth: 1.55 GB / 1 GB (155%)
>  Storage: 0.14 GB / 1 GB (14%)

**Comment by mattpap** [comment]
Well, at least I was able to verify that the overall approach works. So much for "large file support" with 1 GB of bandwidth. I guess we are back with using S3?

**Comment by mattpap** [comment]
This (among other factors) rules out using LFS for storing baselines. Which, I think, is fine as I've been leaning towards submodules anyway.

**Comment by bryevdv** [comment]
@mattpap I"m not sure why that is the conclusion? Any/all of these services will need to be paid for. We just don't happen to be set up to deal with LFS charges because we have never utilized it previously. Like I said this needs planning. E.g. as a first step, we really would need some ballpark estimate of how much bandwidth per month will be required. Then we can make an informed decision about what route to take. That's true for any of the options.  

But I'd like to re-iterate my suggestion of using a docker image to pin the testing environment on linux, settling for testing only on linux in CI, and  building/maintaining as *little as possible* ourselves, i.e. using established services (dockerhub or ECR) that can be easily paid for, and that can be easily used by other contributors. How many bugs have been fixed because a baseline/image test failed specifically and only on a non-linux platform? Is this much time, effort, expense, and inconvenience really justified?

**Comment by mattpap** [comment]
>  I'm not sure why that is the conclusion?

I implicitly assumed S3 would be cheaper, but apparently both are similarly priced ~$5 per 50 GB of transfer.

**Comment by bryevdv** [comment]
@mattpap You will need to look at cloudfront pricing since any solution with S3 will be fronted by cloudfront https://aws.amazon.com/cloudfront/pricing/

**Comment by bryevdv** [comment]
FYI I wanted to see what a $5 "data pack" actually entailed, so I hit "purchase" just to try to see what information a confirmation might supply, but it just purchased with no confirmation. As a dat point, here is what $5 gets:
<img width="485" alt="Screen Shot 2021-11-20 at 10 47 48" src="https://user-images.githubusercontent.com/1078448/142737781-e44e6a69-c660-48b2-9267-f81a2298e714.png">

**Comment by bryevdv** [comment]
FYI GitHub container registry is currently free AFAIK. Docker free has 200 free image pulls per day.

**Comment by mattpap** [comment]
Even if we switch to docker, this won't happen immediately, so at least we have an interim solution.

As to some rough numbers, we had 1771 bokehjs-ci workflow runs (total; including all reruns) on PRs since bokehjs-ci inception. If we used LFS approach since then, that would give use `1171*150MB = 265.65 GB`, which would require 6 data packs (or $30). This doesn't include workflow runs on pushes, but we didn't run bokehjs-ci on pushes in along while anyway (just fixed this yesterday). We would need another `2*150MB` per run in bokeh-ci (for examples and js-test).

Note however, that we need to update to newer chrome versions anyway on regular basis, because we have to make sure that bokehjs works with ever changing chrome, so we really only need all this between new version is released and before we choose to update, which usually can be done immediately, and in some rare cases after a few days or maybe weeks. I think this is the first such big breakage in a long time. In fact besides baseline update, I don't remember not being able to upgrade to new chrome.
