### ISSUE TITLE
Documentation nitpick re: EditTools

### ISSUE THREAD

**Issue by gmerritt123** [bokeh/bokeh#11850]
### Software versions

N/A

### Expected behavior

Quick edit to documentation for EditTool (abstract class) https://docs.bokeh.org/en/latest/docs/reference/models/tools.html?highlight=tools#bokeh.models.EditTool

In public data attributes: 

<html>
<body>

renderers | An explicit list of renderers corresponding to scatter glyphs that may be edited.
-- | --

</body>
</html>

It should not specifically refer to scatter glyphs due to box and polydraw edit tools taking rect/patches renderers respectively. Caused some confusion here: https://discourse.bokeh.org/t/access-box-select-attributes-set-in-figure/8696/10

Suggest something like:

<html>
<body>

renderers | An explicit list of renderers corresponding to Scatter, Line, Rect, or Patch glyphs that may be edited, corresponding to PointDraw, Line Draw/FreehandDraw, BoxDraw and PolyDraw respectively.
-- | --

</body>
</html>

There might be more clear verbiage here but just writing down at least something :-D... maybe just not specifying a glyph type at all here (i.e. just remove the word scatter), and let the more specific tool documentation say what type of glyph it accepts is best.

Thanks as always.

### Observed behavior

N/A

### Example code

```Python
N/A
```

**Comment by bryevdv** [comment]
Actually looking more closely, I really think an even better solution is to remove `renderers` from the base class `EditTool` entirely, and instead have the edit tool subclasses define their own (more narrowly typed) `renderers` properties as appropriate. Then each tool could also have a help string that is specific to it. 

The `EditTool` base never uses `this.renderers` AFAICT, instead there are only some helper functions that accept `renderers` as en explicit argument so this course of action should not pose any issue. 

cc @bokeh/dev

**Comment by bryevdv** [comment]
Well, I spoke too hastily. There is really only `GlyphRenderer`, it's the glyphs that are what are more fine-grained. So we can't really narrow the type at all in subclasses, since we do need the renderer, not the glyph. At best we could define separate `renderers` properties just in order to afford more tailored help strings. But I am not sure that is worth it, and it certainly violates DRY. 

I supposed another option would be adding a docs mechanism to allow overriding or customizing property help strings on subclasses.
