### ISSUE TITLE
Documentation contradicts itself with regards to markers, Scatter, and Circle

### ISSUE THREAD

**Issue by jangop** [bokeh/bokeh#11909]
### Software versions

Bokeh: 2.4.2

### Expected behavior

Documentation on markers.

### Observed behavior

The [documentation on markers](https://docs.bokeh.org/en/latest/docs/reference/models/markers.html) reads:

> Warning
> The individual marker classes in this module are deprecated since Bokeh 2.3.0. Please replace all occurrences of Marker models with Scatter glyphs. For example: instead of Asterisk(), use Scatter(marker="asterisk").

But, only a few lines down, it says:

> Note
> When you draw circle markers with Scatter, you can only assign a size in screen units (by passing a number of pixels to the size property). In case you want to define the radius of circles in data units, use the Circle glyph instead of the Scatter glyph.

As such, the warning tells us *not* to use `Circle`, but the note tells us to use `Circle`.

### Example code

```Python
Not applicable.
```

**Comment by mattpap** [comment]
`Circle` model is a glyph, not a marker, so it wasn't deprecated. The documentation is both correct and misleading at the same time about this special case (one reason why we are dropping marker models in favour of `Scatter` glyph). Things get even more confusing if we add `Figure`'s glyph methods into the picture, because `Figure.scatter()` allows for `marker="circle"` and `radius`, producing `Cricle` instance instead of `Scatter`.

**Comment by mattpap** [comment]
We may want to fix this if we are going to release 2.4.3. Otherwise, deprecated marker models and related documentation were removed in `branch-3.0`.

**Comment by jangop** [comment]
@mattpap Thank you for clearing that up. `Circle` being listed under `markers` made me believe that it might be a marker. 🤷

**Comment by bryevdv** [comment]
Well, being precise: `Circle` is not a subclass of `Marker`,  but *conceptually* circles are most certainly can be used as scatter markers, when configured with a pixel `size`.  The reason for the special case here that circles are commonly used both as a scatter marker (so given `size` in pixels) but also commonly used in Bubble Charts, etc. (so given a `radius` in data units). 

In any case that entire page no longer exists for the 3.0 branch, so the point is moot. I personally doubt there will be a 2.4.3 release since I expect there would be a lot of CI/build issues to sort out on that branch at this point. So I'd be OK to simply close this issue.

**Comment by jangop** [comment]
> So I'd be OK to simply close this issue.

As an ignorant user, now anxiously waiting for 3.0, I fully support this.
