### ISSUE TITLE
[BUG] Bar plots misaligned if data is numeric and xrange is categorical factor range

### ISSUE THREAD

**Issue by muendlein** [bokeh/bokeh#12053]
### Software versions

Python version : 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
IPython version : (not installed)
Tornado version : 6.1
Bokeh version : 2.4.2

### Expected behavior

Combining numerical data with categorical factor range for bar plots should either throw an error or handle the issue implicitly.

### Observed behavior

Bars are plotted however with an offset on the x axis.

### Example code

```Python
import random
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, HoverTool, FactorRange, Range1d
from bokeh.models.glyphs import VBar
from bokeh.plotting import figure
from bokeh.io import show, output_notebook, curdoc

data = {'x': [1, 2, 3], 'y': [1, 2, 3]} #numeric data
source = ColumnDataSource(data)

xdr = FactorRange(factors=[str(x) for x in data['x']]) #categorical x_range
f = figure(x_range=xdr, plot_width=1000, plot_height=300)

f.vbar(x='x', top='y', width=0.8, source=source)

curdoc().add_root(f)
```

### Screenshots

![bokeh_bug](https://user-images.githubusercontent.com/71090451/159360217-2ddea600-b049-4955-b6db-277cf10157ef.PNG)

**Comment by bryevdv** [comment]
Categorical coordinates must be strings, full-stop. The code above is not expected to work. You need to either:

* convert the x-values to strings, or 
* not use a factor range (it's not clear why you would want or need to, if your data is numeric).

Further guidance about this is a support question topic, so please refer to [Discourse site](https://discourse.bokeh.org) to ask additional questions.

**Comment by muendlein** [comment]
@bryevdv 
I know that categorical coordinates must be strings BUT an error message would be very helpful in this scenario. In particular if the code is not expected to work.

**Comment by bryevdv** [comment]
@muendlein Unfortunately, it's tricky. Bokeh is highly modular/composable and also cross-language. That has tradeoffs in both directions:

* highly modular means easier to test (in isolation) and develop, and affords the flexibility of users putting things together in their own combinations. The downside is that not all combinations make sense, combinatorial explosion means testing every possible combination is not feasible, and it can be difficult to report effectively about error conditions. 
* cross language means that work is centered in one place, BokehJS, with all the other languages just providing thin wrappers to a JSON spec, for the most part. That's great for re-usability and keeping complexity as localized as possible. The downside is that errors that "started" in one runtime (e.g. Python) don't actually really exist until code is running in some other runtime (e.g. JavaScript). Properly, an error for this would appear in the browser's javascript console. 

But even if we want to try to warn in python, there's the question of when there could/should be a warning issued. Since the actual problem does not technically "exist" until the code hits JavaScript, we can't issue an error right when you call `vbar` for instance. We can't ever know if a user won't update the data source *later* to something proper *before calling show*, so making an error there would be too eager. The only place we could issue an error is literally right at the last moment before serializing and sending to JSON, which is a pain because not the error checking is separated from the classes and objects that really should be responsible for that kind of validation.

In fact, we do have a late-validation system for use at serialization time. But it's clunky and adds expense/overhead to every single use, so we generally try to avoid resorting it unless there is some situation that is just too far from the "pit of success" is too easy to fall into, that we have no choice. I don't think this is one of those cases, though.

**Comment by muendlein** [comment]
@bryevdv Thank you for your exhaustive explanation!
