### ISSUE TITLE
[FEATURE] Make bokeh server listen to unix socket

### ISSUE THREAD

**Issue by govinda18** [bokeh/bokeh#12089]
### Problem description

I want to bind the bokeh server([panel](https://panel.holoviz.org/) running on a bokeh server) to a UNIX socket. I could not find a way to do this except for  [this](https://github.com/bokeh/bokeh/issues/5383) which was closed as the logger did not require it anymore.

### Feature description

It would be helpful if it can be done via cli - something like 

```bash
bokeh serve --unix-socket /tmp/socket.sock
```

### Potential alternatives

My use case needs it to be a socket only. Could not find any alternative

**Comment by bryevdv** [comment]
This was previously discussed here (quite some years ago) https://github.com/bokeh/bokeh/issues/5383 In that instance, external changes made it so that sockets were no-longer the only option. Since there was otherwise very little demand for this feature, the discussion was closed. 

There still seems to be very little demand for this feature, so my assessment has not really changed: The best chance for this to be added to Bokeh is if someone with socket programming experience, close to an actual use-case, decides to work on this (with assistance/guidance from the core team). @govinda18 are you interested to work on adding this feature?

**Comment by govinda18** [comment]
Thanks @bryevdv, I have raised a PR with a basic setup that works with my usecase. I do not have a lot of experience with socket programming or bokeh for that matter, please do let me know what else I may be missing here.
