### ISSUE TITLE
Misplaces BokehJS Sphinx embeds

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12101]
@mattpap On current `branch-3.0` the BokehJS sphinx embeds are showing up at the bottom of the page instead of where they are supposed to:

<img width="1131" alt="Screen Shot 2022-04-25 at 19 55 03" src="https://user-images.githubusercontent.com/1078448/165210882-b17c21fd-99bd-4f3b-804a-cba32ea78aca.png">

**Comment by mattpap** [comment]
Those examples use `plt.show()` without a target element, which makes those plots to be appended to `<body>`. So that's all correct behavior. The first one works correctly, because it has custom embedding code. I suppose it would be a nice feature to allow `plot.show()` to append plots after a `<script>` when that `<script>` is located under `<body>` (and  not `<head>`).
