### ISSUE TITLE
y_axis_type='log' does not auto zoom correctly

### ISSUE THREAD

**Issue by tdennist** [bokeh/bokeh#1213]
Code to reproduce:

I'm using bokeh 0.60 on a mac.  I've tried on pc also.  I'm using google chrome as the web browser and ipython notebook.

I've been trying to use y_axis_type = 'log' and the same for the x_axis.  It appears that even though my data starts well below 1.  Say .05 which is quite far in log space, bokeh's default zoom starts the y_axis at 1.  It get this right when not in log mode.  I suspect the zoomer is not taking the log space into account.  I've seen the bug in other plotting libs before.  You can see in the screenshot that the output of the y.min() is ~ .05 which is much smaller than 1.0.   If you pan the plot up you will see a considerable amount of data below 1.

This is the python export of the ipython notebook that produced this example:
```
# coding: utf-8



# In[56]:



from bokeh import plotting

import numpy as np

plotting.output_notebook()

import matplotlib.pyplot as plt

cmap = plt.get_cmap('Spectral')

import bokeh

bokeh.__version__





# In[54]:



x = np.exp(np.arange(100))

y = np.exp(np.random.normal(size = 100))

size = np.random.normal(size = 100)

size -= size.min()

color =cmap(np.random.normal(size = 100), bytes = True)

color = ['#%X%X%X'%tuple(c[:-1]) for c in color]

plotting.scatter(x,y, x_axis_type = 'log', y_axis_type = 'log', size = size*5, color = color)

plotting.show()

y.min()





# In[ ]:
```

**Comment by damianavila** [comment]
status: low priority

**Comment by bryevdv** [comment]
Hi @tdennist  and @rageTrue, after a little digging, I have discovered that the main culprit is that the default range padding on `DataRange1d` leaves the start of the range interval negative. The zoom and mapping code seems otherwise correct when non-negative values are present (even small ones). You can work around this problem as in the following script:
```
from bokeh import plotting
import numpy as np

x = np.exp(np.arange(100))
y = np.exp(np.random.normal(size = 100))
size = np.random.normal(size = 100)

size -= size.min()

p = plotting.figure(x_axis_type='log', y_axis_type='log')
p.scatter(x, y, alpha=0.5, size=size*5)
p.x_range.rangepadding = 0                # Set rangepadding to zero
p.y_range.rangepadding = 0                # Set rangepadding to zero

plotting.output_file("foo.html")

plotting.show(p)
```
I'm not sure how to handle this in the short term. Obviously there needs to be some plumbing/communication, but it's still a question of where the responsibility lies in the code. Also `DataRange1d` is going to be changing to an entirely different implementation in the near future, so I am inclined to wait until then to fix this up more. I am closing this as `wontfix` for now, since there is a workaround, and will note this issues as a reference in the other `DataRange` refactor issue. Thanks and sorry this information took so long.
