### ISSUE TITLE
[FEATURE] Legend click events

### ISSUE THREAD

**Issue by huaracheguarache** [bokeh/bokeh#12185]
### Problem description

When plotting a figure you can create legends that enable you to either hide or mute individual glyphs. This is one simple example with hiding functionality:

```
from bokeh.plotting import figure, show
import numpy as np

x = np.linspace(0, 2*np.pi, 101)

fig = figure()
fig.line(x, np.cos(x), color="red", legend_label="cos(x)")
fig.line(x, np.sin(x), color="green", legend_label="sin(x)")
fig.line(x, np.cos(x) + 1, color="blue", legend_label="cos(x) + 1")

fig.legend.location = "right"
fig.legend.click_policy = "hide"

show(fig)
```

In the example above there are only 3 glyphs that can be hidden, but say you have a plot with more than 20 glyphs and you want to have only one visible. It would be quite tedious to individually have to hide each glyph by clicking its legend.

### Feature description

The solution to this issue could be to provide a way to customise the functionality of legends beyond the hide and mute options already available. I would like it to be possible to create an additional custom legend that can hide/show all glyphs when clicked.

### Potential alternatives

I previously [asked on the Bokeh Discourse forum](https://discourse.bokeh.org/t/is-there-a-way-to-hide-show-all-glyphs-with-one-action/9310) whether it's possible to create a custom legend with the ability to hide/show all glyphs, and I was provided with an alternative solution using CustomJS and a button:

```
from bokeh.plotting import figure, show
from bokeh.models import CustomJS, Button
from bokeh.layouts import row
import numpy as np

from bokeh.models import Button

x = np.linspace(0, 2*np.pi, 101)

fig = figure()
fig.line(x, np.cos(x), color="red", legend_label="cos(x)")
fig.line(x, np.sin(x), color="green", legend_label="sin(x)")
fig.line(x, np.cos(x) + 1, color="blue", legend_label="cos(x) + 1")

fig.legend.location = "right"
fig.legend.click_policy = "hide"

btn = Button(label='Hide All')
cb = CustomJS(args=dict(fig=fig,btn=btn)
              ,code='''
              if (btn.label=='Hide All'){
                  for (var i=0; i<fig.renderers.length; i++){
                          fig.renderers[i].visible=false}
                  btn.label = 'Show All'
                  }
              else {for (var i=0; i<fig.renderers.length; i++){
                      fig.renderers[i].visible=true}
              btn.label = 'Hide All'}
              ''')

btn.js_on_click(cb)
show(row([fig,btn]))
```

It's a good workaround, but it would be more natural for the functionality to be part of a custom legend in my opinion.

**Comment by bryevdv** [comment]
I'm going to tentatively triage this for 3.5 since I don't think it will be a huge lift, hopefully I can carve out some time to look at it.  Offhand, I think a Legend click event just needs to report the legend item index at a minimum, users can use that to access the legend item and the glyhph, etc it is configured with, and decide what do to with that.

**Comment by gmerritt123** [comment]
Just adding a thought/idea here after seeing this topic revived on discourse --> what about hooking up an "active" property to the Legend/LegendItems? This would allow users to simply run the legend items as if they were a Checkbox group (e.g. `js_on_change('active',do_stuff)` ) , and they could configure whatever behaviour, filter or otherwise, that they want.
