### ISSUE TITLE
Misc 3.0 docs issues

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12203]
Catch-all issue for quickly recording small issues with docs leading up to 3.0

* [x] latest theme update breaks page layout (fix or pin before release)
* [x] favicon seems to be missing on latest dev docs deploy
* [x] Search results column seems narrow / extra whitespace 
* [x] On mobile devices, the theme seems to still go to dark mode, at least on my dark mode iPhone. 
* [x] Some pre text still pink
* [x] menus not sticky anymore
* [x] search box text not dark enough
* [x] Too much whitespace in search results
* [x] Gallery metadata fields have double colons
   <img width="174" alt="Screen Shot 2022-07-06 at 21 49 51" src="https://user-images.githubusercontent.com/1078448/177693792-98485615-835d-47f7-8ccf-57462f8e6fa1.png">

cc @tcmetzger if you happen to notice any small issues you can use this issue to quickly make note of them

**Comment by tcmetzger** [comment]
The left and right menus now scroll with the page (i.e. they disappear as you scroll down the page). Instead, they should stay in place.

docs/user_guide/styling.html#using-palettes in the current branch 3.0:
![image](https://user-images.githubusercontent.com/39711796/176793669-0b30db96-176e-4425-8cef-46079ef302cf.png)

The same link in the current 2.4.3 docs:
![image](https://user-images.githubusercontent.com/39711796/176793735-4ef82187-3d75-4233-837b-2b229f1c6619.png)

**Comment by tcmetzger** [comment]
The text in the search input field is grey instead of black, making it very difficult to read (very low contrast ratio)
![image](https://user-images.githubusercontent.com/39711796/176793980-950984b1-b353-4bea-980b-9f7c62ae4773.png)

**Comment by tcmetzger** [comment]
@bryevdv since you mentioned the favicon: We could also drastically simplify things and just upload and link an SVG version of the Bokeh symbol and use that with a simple `html_favicon` config in conf.py. I don't think we really need to supply specific versions and resolutions for different models anymore - especially since SVG would be almost infinitely scaleable (as opposed to the PNGs we use right now). What do you think?

**Comment by bryevdv** [comment]
@tcmetzger that sounds good to me

**Comment by bryevdv** [comment]
Here is the weird search look I mentioned
:
<img width="1200" alt="Screen Shot 2022-06-30 at 19 51 49" src="https://user-images.githubusercontent.com/1078448/176814034-fc6dd72d-875e-43ed-84f8-21f9bb045152.png">

FYI I had to force reload the search page to clear some JS errors, we may also need to figure out some cache-busting on that page... not sure

**Comment by bryevdv** [comment]
@tcmetzger well, actually I guess SVG favicon is not supported on all browsers, notably safari: https://caniuse.com/link-icon-svg

**Comment by bryevdv** [comment]
I'm actually at a loss as to why the existing favicon config is not functioning. It looks identical to the PST docs but it does not even seem to be trying to include anything in the rendered HTML

**Comment by bryevdv** [comment]
I've made https://github.com/pydata/pydata-sphinx-theme/issues/781 about the missing favicons. If worse comes to worst I guess can simply override this block to inject links manually
```
{%- block extrahead %}
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="docsearch:language" content="{{ language }}">
{%- endblock %}
```

**Comment by tcmetzger** [comment]
@bryevdv After (quite) some poking around, I'm fairly confident that both the `sphinx_panels` and the `sphinx_tabs.tabs` extensions are the problem here:
* Disabling the `sphinx_tabs.tabs` extension (and removing all `.. tabs::`) makes the favicons work as expected again. 
* Disabling the `sphinx_panels` extension (and removing all `.. panels::`) seems to fix the issue with the sticky menus when scrolling.

Both extensions seem to be about to be deprecated anyways, and the good news is that according to the [pydata theme's documentation](https://pydata-sphinx-theme.readthedocs.io/en/stable/demo/kitchen-sink/web-components.html?highlight=panels#web-components), we can use the `sphinx-design` extension to replace both problematic extensions.

As a next step, I'll remove the two extensions and replace them with `sphinx-design` - if that indeed solves these issues, I'll make a PR!

**Comment by bryevdv** [comment]
The extra colon on the field lists for metadata appears to be a theme issue, I have submitted https://github.com/pydata/pydata-sphinx-theme/issues/860

**Comment by jarrodmillman** [comment]
Regarding the extra colon, see https://github.com/bokeh/bokeh/pull/12305.
