### ISSUE TITLE
[BUG] Bokeh 3.0.0 cannot serialize Pandas Dataframe

### ISSUE THREAD

**Issue by cuberoot** [bokeh/bokeh#12232]
### Software versions

Python version      :  3.9.10 (main, Jan 15 2022, 11:48:00) 
IPython version     :  (not installed)
Tornado version     :  6.1
Bokeh version       :  3.0.0dev10
BokehJS static path :  /Users/mitaylor/Documents/Adobe/photoshop/ps-dev-metrics/.venv/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  v16.13.2
npm version         :  8.1.2
Operating system    :  macOS-12.4-x86_64-i386-64bit

### Expected behavior

I am trying to port some code that uses Bokeh 2.4.3 to use 3.0.0. 

I expect to be able to JSON serialize a figure that uses a `pandas.DataFrame` and send it to a client to be rendered with BokehJS.

Since it works in 2.4.3, I expect it to also work in 3.0.0

### Observed behavior

The serialization fails because the `json_item()` function does not serialize the dataframe arrays. They still contain `Buffer` objects that cannot be serialized by `json.dumps()` 

### Example code

```Python
import json

import pandas
from bokeh.embed import json_item
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

# create dict as basis for ColumnDataSource
data = {'x_values': [1, 2, 3, 4, 5],
        'y_values': [6, 7, 2, 3, 6]}

df = pandas.DataFrame(data=data)

# create ColumnDataSource based on dict
source = ColumnDataSource(data=df)

# create a plot and renderer with ColumnDataSource data
p = figure()
p.circle(x='x_values', y='y_values', source=source)

dump = json.dumps(json_item(p))
print(dump)
```

### Stack traceback or browser console output

```
Traceback (most recent call last):
  File "/Users/mitaylor/Temp/bokeh-serialize/issue.py", line 21, in <module>
    dump = json.dumps(json_item(p))
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Buffer is not JSON serializable
```

**Comment by bryevdv** [comment]
@mattpap  this seems related to my observation here https://github.com/bokeh/bokeh/pull/12222#discussion_r916107261

**Comment by mattpap** [comment]
> The serialization fails because the `json_item()` function does not serialize the dataframe arrays. They still contain `Buffer` objects that cannot be serialized by `json.dumps()`.

Actually, it does serialize data frames, however data frames containing e.g. numpy arrays will contain references to raw memory, which is encoded in `Buffer` structs. Those are indeed not-directly serializable to JSON, by design. One can use `bokeh.core.json_encoder.serialize_json()` to deal with this. It will encode memory inline as base64 encoded JSON strings. The reason we render `Buffer` structs, is that raw memory can be encoded differently depending on the context and the capabilities of the protocols in use. Thus one can store memory inline base64 encoded with the rest of a serialized document or externally either base64 (this isn't fully supported yet) or binary encoded. base64 can be replaced with another encoding, but base64 is the most effective for the web and our usecases.

**Comment by bryevdv** [comment]
@mattpap sure, but `json.dumps(json_item(p))’ should function
