### ISSUE TITLE
python/js reported version mismatch

### ISSUE THREAD

**Issue by AyushShahh** [bokeh/bokeh#12386]
Things are overlapping in some cases and it is making it difficult to navigate and use the website.
The website behaves normally until you click and go to some sections in the section navigation sidebar.

For example:
![image](https://user-images.githubusercontent.com/71313814/190179713-80fbec7e-dc9c-4460-b82c-7d613da39095.png)
The website behaves normally if you are not on a specific site on section navigation sidebar.

![image](https://user-images.githubusercontent.com/71313814/190171430-22b1b084-000a-4607-8f28-eeb37db0a4c0.png)
But if you click and go to some specific reference, it starts behaving weirdly.

### Browser name and version
Google Chrome: 105.0.5195.102 (Official Build) (64-bit) (cohort: Stable)

**Comment by mattpap** [comment]
Also the reported version of Bokeh is wrong in JS console:
![image](https://user-images.githubusercontent.com/27475/190176811-a831c188-c481-44af-a357-33f058c890ab.png)

**Comment by bryevdv** [comment]
There is a known problem with the newest version of the Sphinx theme, it is already noted in the 3.0 misc docs combined issue. If there is time to fix we will, otherwise we will pin back to the old theme version.

**Comment by bryevdv** [comment]
Wheel package reports correctly: 
```
~/work/bokeh 
30dev310 ❯ python
Python 3.10.4 (main, Mar 31 2022, 03:38:35) [Clang 12.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bokeh
>>> bokeh.__version__
'3.0.0.dev16'
```

**Comment by mattpap** [comment]
Locally I'm getting a roughly correct version as well:
![image](https://user-images.githubusercontent.com/27475/190190127-5c72b68f-fc25-4638-a5d3-95405ab2cce2.png)
(I'm guessing it's not dev16, because of `pip install -e`).

**Comment by AyushShahh** [comment]
@bryevdv I noticed that this python/js version mismatch behaves similarly to what I wrote in the issue.

![image](https://user-images.githubusercontent.com/71313814/190191905-46d293a4-0cd8-4246-9ff9-c89e8dcdf4c7.png)
No error if you are not on a specific site on section navigation sidebar.

![image](https://user-images.githubusercontent.com/71313814/190192305-5e9bfe4e-1f58-40d2-80b8-d9064daf1ece.png)
Throws an error when you navigate to some specific reference on section navigation

**Comment by mattpap** [comment]
A quick work around for the docs' appearance is to disable `justify-content` on `.bd-main.bd-content`:

![image](https://user-images.githubusercontent.com/27475/190211620-9b367804-2588-4858-8ed4-9b2cd3dc914d.png)

I would also increase the width of the main column (in this image it's `.col-xl-7` changed to `.co-xl-12`), because the default is extremely narrow and wasteful of horizontal screen space.

**Comment by bryevdv** [comment]
cc @tcmetzger ^^^

**Comment by bryevdv** [comment]
@AyushShahh FYI we pinned the sphinx version and the docs have since been redeployed, the rendering problems are gone now. 

As for the other, after some exploration all I could figure was that the release build was building the docs using an editable install, and maybe that was the issue. I re-arranged a few things to make sure the docs are built using a real installed package (conda package in this case, since it is built and verified last) in https://github.com/bokeh/bokeh/commit/4f0ad225652aab49b0d86e349f87109d835c368d

This fixed the issue, the versions now match in the JS console printout. Except, it still claims the "identical" versions are mismatched 😕 because the JS and Python dev version formats are slightly different (`-dev` vs `.dev`)

<img width="477" alt="Screen Shot 2022-09-17 at 11 31 42" src="https://user-images.githubusercontent.com/1078448/190871695-de3570b5-f225-44ae-94a1-178544eea284.png">
