### ISSUE TITLE
[BUG] latex in titles - upright characters that should be italic

### ISSUE THREAD

**Issue by zmoon** [bokeh/bokeh#12531]
When LaTeX-style mathtext is used in title, it looks like many symbols are rendered upright that should be italic. This is also inconsistent with the labels, which look ok. I noticed this in these docs examples:

* https://docs.bokeh.org/en/latest/docs/examples/styling/mathtext/latex_schrodinger.html
* https://docs.bokeh.org/en/latest/docs/examples/styling/mathtext/latex_bessel.html

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/15079414/199080639-9942da4e-ae84-492b-a14b-820fd26395cb.png)
![image](https://user-images.githubusercontent.com/15079414/199080691-ab12c2a9-748e-4870-904d-71710267d28f.png)
</details>

Also the ASCII letters and numbers that are part of the title mathtext look almost bold, which could make it hard to differentiate ones that are really supposed to be bold.

**Comment by ianthomas23** [comment]
This is definitely a bug. Here is a reproducer that shows all the places you can currently use LaTeX:
```python
from bokeh.models import Div, FixedTicker, Label
from bokeh.plotting import column, figure, show

latex = r"$$Variable \text{ Text}$$"

p = figure(width=300, height=300, title=latex)
p.circle(1, 1, size=15)

p.xaxis.axis_label = latex
p.yaxis.axis_label = latex
p.axis.ticker = FixedTicker(ticks=[1])
p.xaxis.major_label_overrides = {1: latex}
p.yaxis.major_label_overrides = {1: latex}
p.yaxis.major_label_orientation = "vertical"

p.add_layout(Label(text=latex, x=0, y=0))
div = Div(text=latex)

show(column(p, div))
```
![Screenshot 2022-11-06 at 20-50-42 Bokeh Plot](https://user-images.githubusercontent.com/580326/200194518-0f218321-f5d0-40fc-96f8-42ca278d12e0.png)

The `Variable` is supposed to be italic and the `Text` upright.

The only place this is rendered incorrectly is the title. Both a `Title` and `Label` inherit from `TextAnnotation`, the only difference between them is that the `Title` is bold by default. The problem is here
https://github.com/bokeh/bokeh/blob/2e441ef0af411e4263942b73c99809e735f5d341/bokehjs/src/lib/models/text/math_text.ts#L540
If the text is supposed to be bold we wrap the LaTeX in a `\bf`. This is correct for actual text in the LaTeX string, but not correct for variable names which are supposed to be italic as the `\bf` brings them back upright as well. If you use a
```python
p.title.text_font_style="normal"
```
in the title then it renders correctly, and if you use
```python
Label(text=latex, x=0, y=0, text_font_style="bold")
```
you can render the `Label` similarly incorrectly.

The solution is to find a more appropriate replacement for the `\bf` modifier.

**Comment by bryevdv** [comment]
possibly helpful:

https://tex.stackexchange.com/questions/595/how-can-i-get-bold-math-symbols

**Comment by ianthomas23** [comment]
It seems that `\pmb` gives a pretty good result for almost zero effort.

**Comment by bryevdv** [comment]
Ah that's part of AMS? then yes that seems like a good option too

**Comment by ianthomas23** [comment]
Using `\pmb` on chrome gives this:

![Untitled](https://user-images.githubusercontent.com/580326/200196358-81eea9cf-ddf4-45e8-a024-140513cfa31e.png)

**Comment by ianthomas23** [comment]
A bit more blurry on firefox, but that seems to always be the case for MathJax.

![Screenshot 2022-11-06 at 21-34-43 Bokeh Plot](https://user-images.githubusercontent.com/580326/200196429-b40e18fe-637c-422d-bcf8-6445ea9c465c.png)

I'll go with this.
