### ISSUE TITLE
Unpin Sphinx theme

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#12548]
For the 3.0 release, we manually pinned the version of the PyData Sphinx Theme because newer releases broke our layout customizations.

We need to update some of our customizations to be compatible with newer versions of the theme, so that we can unpin the theme version again.

**Comment by AnishereMariam** [comment]
Hi @tcmetzger, I want to work on this project, but I don't know where to begin. I would appreciate a head start and I can take it from there. Thank you.

**Comment by bryevdv** [comment]
@anisheremariam We are happy to hear that you are interested in this issue. I do want to by completely up front that this issue list likely to require a lot of collaboration and back and forth iteration. Assuming you have a working build environment currently, the first thing to do is to update your installed version of `pydata-sphinx-theme` to the latest version, and try to build the docs. It is possible the docs build will fail outright, but even if it "succeeds" then there will almost certainly be problems with the newly rendered docs (that's why we had to pin the version in the first place). But once it is building to completion, we can at least start off by cataloging the current problems with the docs pages.

**Comment by AnishereMariam** [comment]
@bryevdv, I tried working on this but every time I try to build the docs, I get an error code `(configparser.MissingSectionHeaderError)`. and I have tried adding a Section header to no avail. Do you have any suggestions for me?

**Comment by AnishereMariam** [comment]
I noticed that this issue is related to #12480. Solving one could greatly impact the other.

**Comment by bryevdv** [comment]
Hi @anisheremariam to be honest there are probably multiple issues. One is the docs build issue on Windows, which is going to require some investigation with a VM to figure out, unfortunately. But I don't think it is related to the theme unpinning, per se. Then I would also expect that unpinning the theme could also result in a slew of errors, both of explicit (cause the build to fail) as well as silent (build "succeeds" but looks wrong). 

If you only use Windoes, I would advise probably to hold off on this until something can be done about #12480. Otherwise if you can try to setup and build in a linux VM, or docker container, or WSL, it would be good to know what (different) problems crop up when the theme is unpinned.

**Comment by AnishereMariam** [comment]
I will work on the build in a Linux VM and give you a feedback.

**Comment by tcmetzger** [comment]
Closed with #13094
