### ISSUE TITLE
[FEATURE] Offline documentation 

### ISSUE THREAD

**Issue by 4l1fe** [bokeh/bokeh#12553]
### Problem description

Having Bokeh documentation offline to remove network latency while intensively reading it trough. It also could save some laptop battery and let you to work in a deep forest near a lake without network connectivity 🙂

### Feature description

Due to the [conversation in Discource](https://discourse.bokeh.org/t/download-documentation/9696/6) i was recommended by @bryevdv  to create an issue to request publishing static documentation's files. They are exist already and are generated by CI i guess.

It isn't yet published as practically plots doesn't work without pulling js files from CDN , therefore, documentation usefulness is questionable. At the same time, a lot of examples and information is accessible, so it make sense to download it for offline usage.

**Improvement**
I don't know how long and difficult it takes but for improving usefulness plots could be replaced by images, i think readability become better with it, even if we can't interact with plots.

### Potential alternatives

No ideas.

**Comment by bryevdv** [comment]
The current deployment tarballs generated by the release-build job have a subdirectory containing the full generated docs. I would propose to zip up this subdirectory and just make it publicly available somewhere in the release deploy-job. That's not too much work, per-se, but I don't want to have to maintain and update an "index" of these docs tarballs every time there is a new one. I'd rather have a "file-server" like bucket that will just list all the docs tarballs and users can download whichever they want. I'm not sure if that is possible with S3/Cloudfront, so a little investigation will be in order.

**Comment by BhaswatiRoy** [comment]
Hello @bryevdv 
Instead of putting up the entire documentation in offline mode, can we produce a cheat sheet for the users which covers the points of important plots so that it becomes handy to use? Just like cheat sheets of other py libraries?

**Comment by bryevdv** [comment]
There has not been any additional call for this, so I am going to go ahead and close this with `noaction` simply because I don't perceive a demand commensurate to the amount of work it would entail.

@BhaswatiRoy a cheat sheet is a separate issue, you can open a new issue around that if you like. I will state: it would actually be much better if a user makes a concrete proposal for a cheat sheet, that we can just quickly and lightly edit and run with. For instance: I best learn by looking up examples, I don't personally use or like cheat-sheets at all, so I would be a terrible person to try and author one (and why I won't, myself, make an attempt).
