### ISSUE TITLE
bokeh.embed.components second parameter not optional

### ISSUE THREAD

**Issue by M4urice** [bokeh/bokeh#1255]
`bokeh.embed.components(plot_object, resources)` second parameter resources is not optional, contrary to what is stated in the documentation: http://bokeh.pydata.org/docs/reference/resources_embedding.html#bokeh.embed.components

      File "/Users/some_user/GitHub/some_repo/webinterface/webinterface.py", line 393, in generate_report
          script, div = components(test_line)
    TypeError: components() takes exactly 2 arguments (1 given)

But even if I submit a resource ( `bokeh.resources.CDN` for example), it is not used anywhere and I have to add bokehjs manually. Doing the same with `bokeh.embed.autoload_static` works fine.

Minor detail:
There is no documentation of the parameters for `bokeh.embed.autoload_server`and `bokeh.embed.autoload_static`.

**Comment by bryevdv** [comment]
@mattpap thoughts on this?

**Comment by mattpap** [comment]
`components()` have to know about resources to generate JS/HTML, unless we want to make this code non-reusable. What's strange to me is that `components()` can use different resources than those loaded on a page. I would imagine `components()` to be a method of some class that manages the entire picture. Then passing resources each time wouldn't be necessary, because those would be know from the instance on which `components()` would be called.

**Comment by damianavila** [comment]
The `resources` was removed from components in #2211 and the docs updated.
Closing here.
