### ISSUE TITLE
Rename `select_every_mousemove` to `continuous`

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#12590]
At minimum this should have been called `select_every_gesture`, because region selections are made with pan gesture, which can be triggered by other kinds of pointers than just mouse. However, I find this property way too long (punishingly long) for the functionality it provides, thus I would like to have it renamed to something shorter, like the proposed `continuous`.

**Comment by ianthomas23** [comment]
A shorter name seems much better, and I cannot think of a better option than `continuous`.

As this is a model kwarg in the public API I presume the protocol would be to redirect `select_every_gesture` to the new named argument and issue a `BokehDeprecationWarning`. And then after some length of time and/or certain number of releases we would remove the old argument completely?

**Comment by mattpap** [comment]
We would rename it and introduce a deprecated alias `select_every_mousemove = Alias("continuous")` (give or take deprecation code), and then remove it at some point.

**Comment by bryevdv** [comment]
> At minimum this should have been called select_every_gesture

@mattpap some gentle advice: "should" is a very loaded word. I find that almost every time I want to say something "should" have been some way, it's better if I say instead that something "could" have been some way. Because everything that happened in the past happened for some reason or other, and it seemed like the best option at the time. The reasons are probably not important or interesting, so there's not much value in beating up our past selves over what "should" have been done. 

So yes, this *could* have been `select_every_gesture` But FWIW `select_every_mousemove` was adding in https://github.com/bokeh/bokeh/pull/224 which pre-dates the addition of hammer.js and touch gesture support by a few years, at least. When it was added in 2013, it was, in fact, completely and entirely descriptive. 

> like the proposed `continuous`.

I agree shorter would be nice. I am not sure about `continuous`, specifically. But I guess it will do if no one comes up with anything better.
