### ISSUE TITLE
Rect hit testing on circles is overzealous, at least by the default

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#12592]
I think it's a stretch to consider this a valid selection, at least as the default:

![image](https://user-images.githubusercontent.com/27475/201331522-b8a0f154-8e42-4f01-9c27-484d44bc7fb8.png)

I suppose rect hit testing should consider either centers of circles or require for circles to be full included or make it configurable. I think the original was to consider centers, but this may have changed when indexing of circles changed to improve auto-ranging of circles, so probably it's a regression.

**Comment by mattpap** [comment]
This is even worse when we consider asymmetric circle radius:
![image](https://user-images.githubusercontent.com/27475/201332473-0e1b5858-c783-4e20-87eb-c9c36d68b0f7.png)

**Comment by bryevdv** [comment]
> asymmetric circle radius

Do you mean unequal scales? "large" circles on unequal scales will always be broken in various ways, unless we want to o the route of implementing circles using ellipses, so that they "skew". 

> I think it's a stretch to consider this a valid selection, at least as the default.... I think the original was to consider centers, but this may have changed when indexing of circles changed to improve auto-ranging of circles, so probably it's a regression.

I checked several docs versions all the way from 0.8.2 to 2.4.3 and they all appear to use centers, so definitely a regression.
