### ISSUE TITLE
[BUG] [docs] Serializer cannot serialize decimal.Decimal

### ISSUE THREAD

**Issue by teelei** [bokeh/bokeh#12729]
### Software versions

Python version      :  3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.1
Bokeh version       :  3.0.3
BokehJS static path : \env\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19044-SP0

### Expected behavior

Serialization of the Decimal class worked fine in version 2.4.3.

### Observed behavior

In version 3.0.3, trying to serialize the Decimal class throws an error: `bokeh.core.serialization.SerializationError: can't serialize <class 'decimal.Decimal'>`

### Example code

```Python
from bokeh.core.serialization import Serializer
from decimal import Decimal

ser = Serializer()

ser._encode(10.18) # Works fine
ser._encode(Decimal('10.18')) # Throws error
```

**Comment by mattpap** [comment]
If one uses `Decimal`, then the implication is that one expects fixed point arithmetics. bokehjs doesn't support fixed point arithmetics, only floating point. Due to this, it was misleading and possibly incorrect to support serialization of `Decimals`, which worked by silently converting to a float. To avoid potentially incorrect results, this auto-conversion was removed, and now the user has to do it manually, or use floats from the beginning. If bokehjs gets support for fixed point arithmetics, serialization for `Decimal` will be implemented, but it will be a different serialization from what bokeh 2.4 did.

**Comment by bryevdv** [comment]
Personally I would support closing this with either `noaction` or as a small docs task.

**Comment by benrussell80** [comment]
@bryevdv Where in the docs would be best for a note on this?

**Comment by bryevdv** [comment]
@benrussell80 This is mostly just ticking a checkbox and having some thing documented somewhere to point to in case it comes up. The docstring for `Serializer` seems as good a place as any tho I'll be happy with any location you choose. 

Tangentially, a chapter in the dev guide that documents exactly what can be serialized, and how, under what circumstances (e.g. arrays as buffers over ws or base64 in standalone output) would be a nice thing to have, in case you have an itch to write docs (sometimes people do! mentioning just in case 😄)
