### ISSUE TITLE
Custom extension examples do not work

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12757]
For example, `examples/models/custom.py` generates an empty page with  JS console error:
```
[Log] [bokeh] setting log level to: 'info' (custom.html, line 198)
[Error] SyntaxError: Unexpected token '{'
	(anonymous function) (custom.html:780)
[Error] Unhandled Promise Rejection: Error: could not resolve type 'MyPlot', which could be due to a widget or a custom model not being registered before first usage
```
but other examples I tried also behaved similarly. 

cc @mattpap could this be related to the TS compiler update?

**Comment by mattpap** [comment]
You probably need to rebuild bokehjs fully (remove `build/` and rebuild). Otherwise I can't reproduce this issue.

**Comment by mattpap** [comment]
The example is broken though and fails when clicking on glyphs with:
```
custom.html:127 Uncaught TypeError: Cannot read properties of undefined (reading 'indices')
```

**Comment by bryevdv** [comment]
Not sure, still seeing this on latest `branch-3.1` after `git clean -xfd bokehjs src` and a full rebuild.

**Comment by bryevdv** [comment]
Still able to run this (same error) after cleaning the entire repo and rebuilding, inline or cdn resources 🤷

**Comment by mattpap** [comment]
Can you maybe upload the generated file as a gist? Maybe it's not the extension itself, but perhaps embedding issue on your platform, or something like that.

**Comment by bryevdv** [comment]
@mattpap sure here you go: https://gist.github.com/bryevdv/6f9d0ff97f30358e16b30ca477a3fa09

**Comment by mattpap** [comment]
This file works for me in Chrome and Firefox. There's also nothing immediately wrong on or around line 780. Is it failing in Safari? Have you tried other browsers?

**Comment by bryevdv** [comment]
I had not until now. Works in chrome, fails in safari

**Comment by ianthomas23** [comment]
> Works in chrome, fails in safari

I see the same, works in chrome but fails in Safari 16.2 (17614.3.7.1.7).

**Comment by bryevdv** [comment]
Just confirming this is still an issue on `branch-3.1` HEAD as of this morning. I would consider this a blocker for a 3.1 release

**Comment by bryevdv** [comment]
@mattpap here are screenshots from 2.4.3, 3.0.3 and 3.1.0dev docs respectively (on safari)

<img width="1071" alt="Screenshot 2023-02-22 at 12 30 37" src="https://user-images.githubusercontent.com/1078448/220752193-0982e697-9668-49a7-a772-1a2db3916a7a.png">
<img width="1100" alt="Screenshot 2023-02-22 at 12 31 02" src="https://user-images.githubusercontent.com/1078448/220752199-d13e2b4c-484e-4d2e-9912-8dcc5921b9f5.png">
<img width="1347" alt="Screenshot 2023-02-22 at 12 31 28" src="https://user-images.githubusercontent.com/1078448/220752201-88e8c3d1-0453-4be7-8d82-dd0c38f95fac.png">

**Comment by mattpap** [comment]
I assumed the problem was related to inline resources, but docs use CDN, so the problem must be with the extensions' code. Can you verify that `custom.py` actually works with non-inline resources (server or CDN). Also if you could show me JS console output for the failing docs. It should be possible to narrow this down.

**Comment by mattpap** [comment]
I was able to reproduce this in Epiphany web browser, which is also based on WebKit. The problem is with `static {}` blocks in old-style extensions, which are not supported in WebKit yet. As usually it's behind the curve, but the feature is new enough that we shouldn't be using it generated JS. Everywhere else (bundles, new-style extensions) `static {}` block are transpiled to an older syntax, but old-style extensions got configured improperly. Should be easy to fix, now that I know what's the culprit.
