### ISSUE TITLE
[BUG] No module named 'bokeh.server.tests'

### ISSUE THREAD

**Issue by ninousf** [bokeh/bokeh#12767]
### Software versions

Python version      :  3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0]
IPython version     :  8.8.0
Tornado version     :  6.2
Bokeh version       :  3.1.0.dev1+19.g0e72ad3c
BokehJS static path :  ..../git/bokeh/src/bokeh/server/static
node.js version     :  v16.17.1
npm version         :  8.19.3
Operating system    :  Linux-5.14.0-1056-oem-x86_64-with-glibc2.31

### Expected behavior

following the dev. guide, in the server.html page:

Testing
To test client-server functionality, use the utilities in bokeh.server.tests.utils.

### Observed behavior

ModuleNotFoundError: No module named 'bokeh.server.tests'

### Example code

```Python
import bokeh.server.tests.utils
```

**Comment by mattpap** [comment]
That's https://docs.bokeh.org/en/latest/docs/dev_guide/server.html, section "Testing" at the end of the page.

**Comment by bryevdv** [comment]
That entire chapter is ancient and untouched for many years. It's basically just a very hurried brain-dump written when someone had to move onto other work unexpectedly. Some parts are still valid but a lot of it is either irrelevant now or otherwise out of date. 

I would not be opposed to simply deleting the entire chapter rather than trying to piecemeal "fix" it as-is. We can make an issue to author a proper dev chapter on the bokeh server taking into account ~10 years of hindsight as well as more recent developments (pyscript, etc).
