### ISSUE TITLE
Add a python way to schedule purely js animations

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#128]
Add a python construct that scripts running animations that are purely done in javascript.  This way static examples can be built that have animations.

maybe something like this

```
N = 80
x = np.linspace(0, 4*np.pi, N)

y = np.sin(x)
y2 = np.tan(x)
y3 = np.cos(x)

y_possibilities = [y,y2,y3]

l = line(x,y, color="#0000FF", tools="pan,zoom,resize")

animate(animate.select(y_posibilities), delay="3s", line)

```

that is a very very rough syntax.  But something like that should produce a bokeh object that every 3 seconds switches out the y data range to one of the other possibilities.

**Comment by birdsarah** [comment]
@paddymul @pzwang - want to lay this one to rest now we have js callbacks?

**Comment by bryevdv** [comment]
No this is a different task. This is about being able to script animations by defining a sequence of vis state "waypoints" that should occur at set times, with some transfer function to take the state from one to the next.

**Comment by ijstokes** [comment]
OK, what I was asking for in #5257 was a much simpler version of this, I think, that would "simply" provide smooth data point (or more sophisticated: curve) transitions between one state and the next, rather than an "animation framework" which is, I'm sure, a much more complicated thing.

**Comment by bryevdv** [comment]
No, that's just another way of saying the same thing. Why this is somewhat difficult is because currently all BokehJS glyphs represent directly the data in a CDS. To make smooth transitions, there are two options:

* actually mutate the data in the CDS according to some interpolation (very bad idea to do on the BokehJS side, for a lot of reasons)
* add some new additional level of indirection in between CDS and the values a glyph uses (complicated for a lot of reasons, e.g. what if CDS "truth" is updated in the middle of a smooth transition? how to handle timing, and invalidation, etc *in principle*,  in addition to just new code needed in lots of places)

**Comment by pzwang** [comment]
After a chat with Bryan, we have come to some resolution about how to handle events and model updates while the plot is animating.  Namely, we should add some kind of deep "event system disable" that flags that the entire plot is "transitioning", so while the JS-side model may be updating with values, it does not trigger callbacks or other "data model" changes until the final state is reached.  Any new data events coming in are queued up.  User interactions (mouse, kbd, etc.) are ignored while transitioning.

**Comment by Lnk2past** [comment]
Any chance I could help support this? Has there been any progress on this feature? I am currently doing something hackish with `panel`/`hvplot` to animate some basic transitions, but would love to have this in `bokeh` out of the box. I will request an invite to the dev slack when I am home later if that is a more appropriate place to discuss.

**Comment by bryevdv** [comment]
After 10+ years I am now inclined to simply close this with `noaction`. It's just not a very good fit for Bokeh to begin with, due to the cross-runtime concerns, and I have not perceived a demand for it commensurate to the amount of work it would require. I'm also just not personally sure what actual value it adds to invent values that don't exist in the data. There are definitely other pure JS options available for users that really desire it.
