### ISSUE TITLE
Seaborn PairGrid not supported in mpl.to_bokeh() ?

### ISSUE THREAD

**Issue by mtbannister** [bokeh/bokeh#1283]
I was hoping to bring a seaborn.PairGrid() directly into bokeh to apply the interactivity bokeh offers. Is there a way to do this? Seaborn seems at present to have more condensed ways of creating multivariate grids of plots from pandas.DataFrame() objects, so I'd started in that.

e.g. 
```
from bokeh import mpl
import seaborn as sns
( tnos is a pandas.DataFrame() )
pg = sns.PairGrid(tnos, x_vars=["semimajor_axis", "inclination", "perihelion", "eccentricity"], 
                  y_vars=["perihelion", "inclination", "eccentricity"], 
                  aspect=2, hue="peribin", palette="coolwarm")
pg.map(plt.scatter)
mpl.to_bokeh(fig=pg)
ERROR:astropy:AttributeError: 'PairGrid' object has no attribute 'dpi'
ERROR: AttributeError: 'PairGrid' object has no attribute 'dpi' [bokeh.mplexporter.exporter]
```
---------------------------------------------------------------------------
```
AttributeError                            Traceback (most recent call last)
<ipython-input-132-f207883a11e3> in <module>()
      1 from bokeh import mpl
----> 2 mpl.to_bokeh(fig=pg)

/Users/michele/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bokeh/mpl.pyc in to_bokeh(fig, name, server, notebook, pd_obj, xkcd)
    422     exporter = Exporter(renderer)
    423 
--> 424     exporter.run(fig)
    425 
    426     doc._current_plot = renderer.fig  # TODO (bev) do not rely on private attrs

/Users/michele/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/bokeh/mplexporter/exporter.pyc in run(self, fig)
     43         # Calling savefig executes the draw() command, putting elements
     44         # in the correct place.
---> 45         fig.savefig(io.BytesIO(), format='png', dpi=fig.dpi)
     46         if self.close_mpl:
     47             import matplotlib.pyplot as plt

AttributeError: 'PairGrid' object has no attribute 'dpi'
```

**Comment by joelostblom** [comment]
I believe this issue should be reopened. It seems like seaborn pairgrid is supported in mpld3, but not in Bokeh, although the error is not the same as the one originally posted here.

In short, `mpld3.display()` works, but `mpl.to_bokeh()` doesn't raising a `NotImplementedError`. I also tried passing several different object from the pairgrid, including a `matplotlib.figure.Figure`, but no luck. [Test notebook here](http://nbviewer.ipython.org/github/joelostblom/test_ipynbs/blob/master/bokeh_seaborn_pairgrid.ipynb) and there are some updates on the [mpld3 discussion](https://github.com/mpld3/mplexporter/issues/34) as well.

**Comment by vivekys** [comment]
Getting a different error now. Also the issue is not just with PairGrid. I am observing the error on all of the following.
seaborn.FacetGrid
seaborn.PairGrid
seaborn.lmplot
seaborn.factorplot

Traceback (most recent call last):
  File "/Users/vivek/myCode/bokeh/examples/compat/seaborn/Seaborn-PairPlot.py", line 34, in <module>
    show(mpl.to_bokeh())
  File "/Users/vivek/myCode/bokeh/bokeh/compat/mpl.py", line 77, in to_bokeh
    exporter.run(fig)
  File "/Users/vivek/myCode/bokeh/bokeh/compat/mplexporter/exporter.py", line 51, in run
    self.crawl_fig(fig)
  File "/Users/vivek/myCode/bokeh/bokeh/compat/mplexporter/exporter.py", line 118, in crawl_fig
    self.crawl_ax(ax)
  File "/Users/vivek/myCode/bokeh/bokeh/compat/mplexporter/exporter.py", line 140, in crawl_ax
    self.draw_collection(ax, collection)
  File "/Users/vivek/myCode/bokeh/bokeh/compat/bokeh_exporter.py", line 34, in draw_collection
    super(BokehExporter, self).draw_collection(ax, collection, force_pathtrans, force_offsettrans)
  File "/Users/vivek/myCode/bokeh/bokeh/compat/mplexporter/exporter.py", line 272, in draw_collection
    mplobj=collection)
  File "/Users/vivek/myCode/bokeh/bokeh/compat/mplexporter/renderers/base.py", line 255, in draw_path_collection
    offsets, styles):
  File "/Users/vivek/myCode/bokeh/bokeh/compat/mplexporter/renderers/base.py", line 192, in _iter_path_collection
    if not path_transforms:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by bryevdv** [comment]
Both mpld3 and mplexported are currently unmaintained. I'm afraid we cannot invest ay more of the very limited resources on MPL compat until / if a true serialization solution (MEP25) is implemented by the mpl team
