### ISSUE TITLE
dev guide has incorrect links to executables in the github

### ISSUE THREAD

**Issue by Soot3** [bokeh/bokeh#12909]
examples\plotting\file\marker_map.py and examples\app\sliders.py do not lead to the correct executable from the GitHub directory.

Updated links should show examples/basic/data/transform_markers.py and examples/server/app/sliders.py instead.

**Comment by bryevdv** [comment]
Hi @Soot3 Thanks for the issue! 

As it happens, the `marker_map.py` link was already fixed in https://github.com/bokeh/bokeh/pull/12750 on `branch-3.1` but version 3.1 has not been released yet, which is why you don't see the change on the currently published docs. Hopefully version 3.1 will be released tomorrow! 🤞 

It looks like the `examples\app\sliders.py` is still out of date and needs to be updated, I will triage the issue accordingly!

For anyone who would like to make this update, the relevant source file for the docs is: 

https://github.com/bokeh/bokeh/blob/branch-3.2/docs/bokeh/source/docs/dev_guide/setup.rst

Edit: looks like you already made a PR! 🙏
