### ISSUE TITLE
Candlestick chart broken

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#12917]
ref: https://docs.bokeh.org/en/dev-3.1/docs/examples/topics/timeseries/candlestick.html

Console error is "could not set initial ranges"

<img width="1177" alt="Screenshot 2023-03-07 at 19 56 23" src="https://user-images.githubusercontent.com/1078448/223615862-4c254d74-bba0-4ff8-8f15-26d598130b25.png">

**Comment by mattpap** [comment]
This is due to auto-ranging of box annotations, which seems to be broken when some coordinates are mapped to frame edges. This needs to be fixed, but a quick way to solve this is to add boxes to `center` layout, instead of `renderers`. Adding to center layout removes annotations from auto-ranging. Adding them to `renderers`, however, aligns them closer to glyphs' behavior.
