### ISSUE TITLE
[BUG] Inaccesible Link

### ISSUE THREAD

**Issue by Ajoke23** [bokeh/bokeh#13016]
### Software versions

Python version      :  3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]
IPython version     :  8.5.0
Tornado version     :  6.2
Bokeh version       :  3.1.0
BokehJS static path :  C:\Users\user\AppData\Roaming\Python\Python310\site-packages\bokeh\server\static
node.js version     :  v18.15.0
npm version         :  9.5.0
Operating system    :  Windows-10-10.0.19044-SP0

### Browser name and version

Browser Name: Microsoft Edge, Version: Version 110.0.1587.50 (Official build) (64-bit)

### Expected behavior

I expected it to take me to the github page that shows a complete list of JavaScript models

### Observed behavior

![github](https://user-images.githubusercontent.com/71567200/227136590-00968b5d-1ba2-4e43-aaa1-df51553fef20.PNG)

### Example code

```Python
https://github.com/bokeh/bokeh/tree/2.3.3rc1/bokehjs/src/lib/api/models.ts
```

### Screenshots

From this link "https://docs.bokeh.org/en/dev/docs/user_guide/bokehjs.html", when i clicked on "https://github.com/bokeh/bokeh/tree/2.3.3rc1/bokehjs/src/lib/api/models.ts" it 

![page](https://user-images.githubusercontent.com/71567200/227135953-4e5d37b1-a43f-496a-9f9f-f39547f8a228.PNG)
![github](https://user-images.githubusercontent.com/71567200/227130534-f55d703c-646e-47bc-9849-90b522e49f1e.PNG)

From the first image, the part circle with blue, when clicked on it, it returns error

@bryevdv @pavithraes

**Comment by chinmaychahar** [comment]
Hi @Ajoke23 
The page you're accessing is from a pre-released version. I think you should use the latest version of docs available here - https://docs.bokeh.org/en/latest/docs/user_guide/advanced/bokehjs.html#ug-advanced-bokehjs 

The link to [bokehjs/src/lib/api/models.ts](https://github.com/bokeh/bokeh/tree/3.1.0/bokehjs/src/lib/api/models.ts) works perfectly fine in the latest docs.

**Comment by bryevdv** [comment]
Those are not only pre-release docs, they are *very old* pre-release docs. To be honest, the only change I would make here might to delete them entirely. We are now more specific and use `dev-3.1`, `dev-3.2` etc where the dev docs URL indicates the release branch level (note that `dev-3.2` is a 404 currently, because we have yet to publish a first pre-release for 3.2, so that is expected)

**Comment by bryevdv** [comment]
I have deleted those very old dev docs entirely.

**Comment by bryevdv** [comment]
One other thing about dev docs: they are definitely ephemeral and will always go out of date in some ways at some point. The link above points to a github tag `https://github.com/bokeh/bokeh/tree/2.3.3rc1` because the docs were built for dev tag `2.3.3rc1`. But we do not keep old dev/rc tags on GH permanently. We keep them around until the next minor release, and then typically delete them as clutter, so links like that will always eventually stop working. Dev docs are always a *temporary* snapshot of a point int time, in that sense, they are really only valid while the development of their associated release is ongoing (e.g. `dev-3.1` is valid while version 3.1 is under development, etc)

**Comment by Ajoke23** [comment]
@bryevdv in that case, can it be deleted as it can lead to confusion. I noticed it as a bug without me knowing it's previous released doc

**Comment by bryevdv** [comment]
@Ajoke23 can what be deleted? I have already deleted the very old docs at `en/dev` with no branch id attached.
