### ISSUE TITLE
[BUG] Incorrectly formatted ticks with %f format when time is older than the Epoch

### ISSUE THREAD

**Issue by jmranger** [bokeh/bokeh#13067]
Note: bug title was changed to accurately describe what was fixed, and doesn't exactly match the original bug report below. See the discussion for context. The original issue was resubmitted as #13509.
---

### Software versions

Python version      :  3.9.13 (main, Oct 13 2022, 21:23:06) [MSC v.1916 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.2
Bokeh version       :  3.1.0
BokehJS static path :  C:\ProgramData\Miniconda3\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19045-SP0

### Browser name and version

Visble in both Firefox and Chrome

### Expected behavior

This is a correct result:
![correct](https://user-images.githubusercontent.com/12662295/230246063-7c78d4ce-8146-46fe-aec6-e3a4088c7096.png)
If the code below is modified so the point is in 1969 instead of 1970, I get the incorrect result:
![incorrect](https://user-images.githubusercontent.com/12662295/230246143-a4e560ec-6499-4d12-959f-d86b3e6dda49.png)
I would have expected the microsecond part of the tickers to only contain digits, not a negative sign.

### Observed behavior

See above

### Example code

```Python
import datetime
from bokeh.plotting import figure, show
from math import pi
from bokeh.models import DatetimeTickFormatter


plot = figure()
plot.scatter((datetime.datetime(1970,12,31,1,2,3),), (4,))
plot.xaxis.formatter = DatetimeTickFormatter(
			microseconds = '%Y-%m-%d %H:%M:%S.%3N'
		)
plot.xaxis.major_label_orientation = pi/2
show(plot)
```

**Comment by ianthomas23** [comment]
Thanks for the report @jmranger, I can reproduce it and it is definitely a bug.

Internally in BokehJS we pass around datetimes in posix time (seconds since epoch) and for dates earlier than 1970 this is negative. I think the underlying problem is here

https://github.com/bokeh/bokeh/blob/0da7e85d29e529c2e5278d5021cc75ecbf4b0d3c/bokehjs/src/lib/models/formatters/datetime_tick_formatter.ts#L88-L94

When `t` is negative the rounding returns a negative number and we need it to be positive.

I think this will be relatively easy to fix by changing the rounding so that it deals with negative as well as positive times. Plus new tests, possibly in `bokehjs/test/unit/models/formatters/dateime_tick_formatter.ts`.

**Comment by muendlein** [comment]
@ianthomas23 The `_us` function is only an issue if `%f` is used in the format string as this function not called otherwise. 
The root cause in the example above is the call to the external library:
https://github.com/bokeh/bokeh/blob/0da7e85d29e529c2e5278d5021cc75ecbf4b0d3c/bokehjs/src/lib/models/formatters/datetime_tick_formatter.ts#L85

**Comment by mattpap** [comment]
btw. Axis major labels can be multi-line, so one can avoid rotation if not desirable:
```py
plot.xaxis.formatter = DatetimeTickFormatter(microseconds = '%Y-%m-%d\n%H:%M:%S.%3N')
```
![image](https://github.com/bokeh/bokeh/assets/27475/6b2b7650-05cf-48ef-b305-f1e0734e7b23)

**Comment by muendlein** [comment]
@bryevdv Should this be really closed as the bug only got partially adressed? Using `%3N` is still not fixed yet (bug within the external library).

**Comment by bryevdv** [comment]
@muendlein My suggestion would be to edit this issue to correspond to whatever the PR was able to address, and open a new issue for anything remaining. At least for me, it's confusing and not very helpful to have PRs that "partially fix" some issue. I think it is better to have pure issue-PRs (no associated issue at all) or else a strict 1-1  relation between issues and PRs (with any additional issues as needed, or links between issues) as the standard process. 

Edit: I guess this was not your issue originally. Given there is some question around the unmaintained status of the down stream library I do think a new issue is justified in any case since the issue potentially now has a wider scope. Can you make one that summarizes the current status, and suggest an edit to put at the top of this closed issue?

**Comment by jmranger** [comment]
Original reporter chiming in.

Unless I'm mistaken, the merged commit fixes a closely related but different bug than the one I reported. AFAICT, no solution or workaround has been proposed to the specific issue I'm facing so far. If that's indeed the case, I'm not sure why the issue would be closed.

That said, thank you all for your efforts, and thanks to @mattpap dor the multi-line marker tip. I'll definitely look into integrating that.

**Comment by bryevdv** [comment]
>  I'm not sure why the issue would be closed.

It doesn't really matter at this point, it did get closed with links to it already reported in milestones and release notes for an immediately upcoming release, and undoing that would be alot of tedious and time-consuming busy work that I'm just not going to do. So I'll reiterate my suggestion to: 

* quickly edit this issue to repurpose it to reflect what was actually fixed
* make a new issue for whatever is left

**Comment by jmranger** [comment]
OK. I understand where you're coming from.
On my end, I'm:
- unable to accurately describe what has been fixed
- unable to test the current behavior - I'll have to wait for a released version
so I'd prefer if someone more knowledgeable could do it.

Should I be the one doing it in a few days/weeks, I expect to submit the exact same issue, since I believe that the bug is still fully present - "whatever is left" being 100% of what I described.

**Comment by muendlein** [comment]
> OK. I understand where you're coming from. On my end, I'm:
> 
> * unable to accurately describe what has been fixed
> * unable to test the current behavior - I'll have to wait for a released version
>   so I'd prefer if someone more knowledgeable could do it.
> 
> Should I be the one doing it in a few days/weeks, I expect to submit the exact same issue, since I believe that the bug is still fully present - "whatever is left" being 100% of what I described.

@jmranger 
Step 1: Rename this issue to "Incorrectly formatted ticks with %f format when time is older than the Epoch"  (as this has been fixed)
Step 2: Submit a new issue with the same contents and the title: "Incorrectly formatted ticks with %N format when time is older than the Epoch"
