### ISSUE TITLE
[BUG]  major_label_overrides does not work for hours/minutes/seconds

### ISSUE THREAD

**Issue by user529481** [bokeh/bokeh#13128]
### Software versions

Python version 3.10
Bokeh version 3.1.0

### Browser name and version

Opera GX

### Expected behavior

Gaps in the plot where there are time gaps should be filled in and the ticks updated to the format provided. 

### Observed behavior

Gaps in the time plots are not filled in and the ticks aren't updated. 

<img width="401" alt="Capture d’écran 2023-05-12 à 22 51 51" src="https://github.com/bokeh/bokeh/assets/71951740/fccb2e5d-b101-4fd7-bdf8-b1ee310f34d4">

### Example code

```Python
ts2 = figure(x_axis_type='datetime')

ts2.xaxis.major_label_overrides = {
    i: date.strftime('%H:%M %d/%m/%y') for i, date in enumerate(pd.to_datetime(df.index))
}

ts2.line('time', 'magnitude', source=src)
```

### Screenshots
<img width="401" alt="Capture d’écran 2023-05-12 à 22 51 51" src="https://github.com/bokeh/bokeh/assets/71951740/2f3a0524-84f6-4109-985c-a55e6781abcf">

**Comment by bryevdv** [comment]
@user293811 You have a misunderstanding about the purpose and use of `major_label_overrides`. An axis's ticks are controlled by two separate things:

* ticker -- chooses where ticks will go
* tick formatter -- chooses how to format those ticks

The `major_label_overrides` is a mechanism to manually override the *formatting* of tick locations that are already chosen by a ticker. It will never add new ticks that don't already exist from the ticker. (i.e. it will not, and is not expected to, "fill in any gaps")

Additionally, the overrides rely on exact equality matching of tick locations. However, the underlying units of datetime axes are floating point milliseconds-since-epoch. So in this case, the keys in the dict would have to be floating point timestamp values. As you may be aware, strict equality comparisons of floating point values are often problematic due to rounding or changes in precision, and this exacerbated even further by serializing across different runtimes (e.g. Python<-->JavaScript). For this reason, I would say that `major_label_overrides`  are fundamentally not-useful for floating point tick locations, and this includes datetime values in particular. They are really only useful for integer or categorical tick coordinates, and there's not anything we can do about that. 

There are existing mechanisms to configure or control both tick locations and formatting. But those are usage question, 
so the appropriate venue is the  [community support Discourse site](https://discourse.bokeh.org), not the issue tracker.
