### ISSUE TITLE
Broken link in docs/first_steps/first_steps_9.html

### ISSUE THREAD

**Issue by cdeil** [bokeh/bokeh#13162]
At https://docs.bokeh.org/en/latest/docs/first_steps/first_steps_9.html there is currently a broken link to https://github.com/bokeh/bokeh/blob/master/examples/app/sliders.py

I think you renamed "master" -> "main" and it was moved to `examples/server/app/sliders.py`.

Generally keeping docs versions and Github consistent is probably difficult and it might be better to copy all example files and serve them with the docs instead of linking to Github?

I tried using the bug template form, but honestly it doesn't fit for reporting such docs problems.

**Comment by pavithraes** [comment]
@cdeil Thanks for reporting! 

Most of the examples' codes are available in the docs, [for example range_tool](https://docs.bokeh.org/en/latest/docs/examples/interaction/tools/range_tool.html)

Our Bokeh server examples are the only exception, these examples are hosted separately at https://demo.bokeh.org/

> At https://docs.bokeh.org/en/latest/docs/first_steps/first_steps_9.html there is currently a broken link to https://github.com/bokeh/bokeh/blob/master/examples/app/sliders.py

Also, looks like this is the only hard-coded link to github, I think we can update this link to use the `bokeh-tree` sphinx role, created to keep the docs in sync:

```
:bokeh-tree:`examples/server/app/slider.py`
```

Would you be interested in opening a PR for this?

**Comment by bryevdv** [comment]
Every example that uses the `:bokeh-plot:` sphinx extension (which is nearly all of them) does copy the relevant source code into the built docs. But `:bokeh-plot:` only works with standalone HTML outout, not Bokeh server apps like this one (apps have to be hosted/running somewhere) which I why this case in particular only links into the repo. The `:bokeh-tree:` extensions is a great idea for getting an automatically versioned link to the release tag, just the sentence will need slight re-work since the link text will be `examples/server/app/slider.py`
