### ISSUE TITLE
[FEATURE] Preserve category information for categorical colormapping

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#13200]
### Problem description

As mentioned in #12356, Bokeh's new categorical colormapping "is essentially a reimplementation of Datashader's _colorize function so that all of the data is at the Bokeh level and available for colormapping and inspection." I.e., the reason to do such colormapping at the Bokeh level even though it is already available in Datashader's own source code is so that choosing to do server-side rather than client-side rendering shouldn't mean giving up on Bokeh's inspection support, where feasible. For instance, if you plot a collection of points in categories "a", "b", and "c" and three of them overlap, in Bokeh (here driven by hvplot) you can hover over the overlapping points to see how many points overlap and what categories they are in:

```python
import hvplot.pandas, pandas as pd, numpy as np

x,y = np.random.randn(1000), np.random.randn(1000)
c   = np.random.choice(['a', 'b', 'c'], 1000)
df  = pd.DataFrame({'x': x, 'y': y, 'cat': c})

df.hvplot.scatter(color='cat')
```
<img width="720" alt="image" src="https://github.com/bokeh/bokeh/assets/1695496/b86aed40-ca72-4e07-899f-bb77d34a31bc">

However, as noted in #13193, when using Bokeh's colormapping with Datashader the category names are not currently serialized and thus not available for hovering, which greatly limits such inspection. 

### Feature description

I would propose that when using ImageStack in this way, it is crucial to pass not just the stack itself but also a label for each image in the stack, so that hover information could at least show the number (or weight) of datapoints in each category that contribute to that pixel (e.g. `a: 52, b:2, c:0`).

### Potential alternatives

Currently #13193 proposes showing a list of values in order, e.g. `value: 52, 2, 0`, which does not seem directly usable by viewers of the plot, as they would not be expected to memorize the category ordering.

**Comment by ianthomas23** [comment]
Let's call the label to be displayed for each image in the stack the `name` for the sake of discussion (it could be `label` or `category` or `layer` or whatever depending on context).

I think the difficulty here is working out a sensible API for setting the `name`s. It is easy for the example shown, but we have to support the general case. `ImageStack` like all the image-based glyphs supports multiple images, even though it is usually used with just a single image. So an `ImageStack` with `n` images has an explicit or implicit `ColumnDataSource` containing columns `image`, `x`, `dw`, etc, that have length `n`. If the image or images we are passing in have a number of layers/categories of `name_count` (which is `image[0].shape[2]` in python terminology) and is not necessarily equal to `n`. The initial idea of simply adding a `name` column to the CDS doesn't work as the columns need to be of the same length. e.g.

```python
cds = ColumnDataSource(data=dict(image=[im0, im1], x=[0, 10], name=['plant', 'animal', 'mineral']))
fig.image_stack(source=cds, image='image', x='x', name='name', ...)
```

gives us the usual warning `ColumnDataSource's columns must be of the same length`.

For a single image we could solve this using `name`s that are one level nested, i.e.

```python
cds = ColumnDataSource(data=dict(image=[im0], x=[0], name=[['plant', 'animal', 'mineral']]))
```

so that `len(name) == 1`.

But for two images using the same `name`s one would have to repeat them:


```python
cds = ColumnDataSource(data=dict(
    image=[im0, im1], x=[0, 10],
    name=[['plant', 'animal', 'mineral'], ['plant', 'animal', 'mineral']],
))
```

which isn't ideal. This allows them to differ, and that is probably not desirable as the colormapper applies colors in index order.

There is an alternative which is to set the `name`s on the colormapper, something like
```python
 color_mapper = WeightedStackColorMapper(
    palette=["teal", "yellow", "olive"], names=["plant", "animal", "mineral"], alpha_mapper=...)
 p.image_stack(..., color_mapper=color_mapper)
```
but I don't particularly like this.

We also need to bear in mind that currently we only have one use for `ImageStack` which is with a `WeightedStackColorMapper` to do the Datashader-like categorical mixing. But there will be other uses such as the already suggested `ImageStack` with a conventional `ColorMapper` which has a single layer/category selected at one time and that is color mapped in the usual manner for display and the user can control the selected layer using a widget.

**Comment by bryevdv** [comment]
A few questions of my own: 

* Are we expecting that users would normally be using xarray for labeled arrays? (Do we need to support xarray as an *optional* dependency&mdash;the way we used to with pandas)
* If so, would we restrict labeled arrays to *only* be provided as xarrays? In that case we could ingest the labels and serialized the labels via any convenient internal channel to start, and side-step user-facing API at least for now.
* Otherwise, if we want to support users providing labels for "plain" numpy arrays (some wheel-reinvention I guess) then I think  the only correct option is the repeated one:
    ```
    name=[['plant', 'animal', 'mineral'], ['plant', 'animal', 'mineral']]
    ```
    Because, strictly speaking, there is no requirement that `im0` and `im1` have the same labels, correct?

**Comment by ianthomas23** [comment]
I would like to support plain `numpy` arrays, I don't we can force users to learn `xarray` just for this glyph.

Supporting `xarray` inputs is interesting but we'd have to make some assumptions and I think this might be dangerous. If the input is a 3D `xarray.DataArray` then we can assume the shape is `(ny, nx, nnames)` which is fine. If the input is 4D though, what do we do? We could assume the data is vectorised (using Bokeh parlance) on the first dimension and create an `ImageGlyph` with multiple images. But maybe it is just as reasonable to vectorised on the last dimension.

Also, `xarray.DataArray`s contain coordinates. Do we extract those and use them to set the `ImageGlyph` properties `x`, `y`, `dw` and `dh`? We'd probably have to check (or assume) they are linear coordinates. What if they are logarithmic coordinates? Do we ignore it, or check it and error out? And maybe log coordinates are fine if the axes to display the glyph has logarithmic scales, but at the moment this cannot be checked at glyph creation time.

**Comment by ianthomas23** [comment]
We can't use `name` for the new property here as it already exists on `Model`. I suppose `label` is the next option.

**Comment by ianthomas23** [comment]
Adding the `stack_labels` property occurred in PR #13366. The remainder of this issue, rendering more useful categorical tooltips, is tracked in separate issue #13354.
