### ISSUE TITLE
Non-specific error when the DataFrame Used to construct a ColumnDataSource contains non-string keys

### ISSUE THREAD

**Issue by marceloslacerda** [bokeh/bokeh#13295]
### Software versions

Python version      :  3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46)
IPython version     :  8.14.0
Tornado version     :  6.3.2
Bokeh version       :  3.2.1
BokehJS static path :  /opt/tljh/user/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-6.1.0-10-amd64-x86_64-with-glibc2.36

Consider the following example

```python
import pandas
from bokeh.models import ColumnDataSource
df = pandas.DataFrame({'a':[1,2,3], 1:[1,2,3]})
source = ColumnDataSource(df)
```

It will fail with an error `ValueError: expected an element of ColumnData(String, Seq(Any)), got {'index': array([0, 1, 2]), 1: array([1, 2, 3]), 'a': array([1, 2, 3])}` which tells the user nothing about the source of the problem. This problem is particularly obfuscated when creating large dataframes from dynamic sources.

What's worse is that the user will be pointed to a place that's [not the origin of the problem](https://github.com/bokeh/bokeh/blob/branch-3.3/src/bokeh/core/property/bases.py#L364) when the error actually happens [elsewhere](https://github.com/bokeh/bokeh/blob/branch-3.3/src/bokeh/core/property/container.py#L205C14-L205C14).

Even if the error correctly traced the issue to `bokeh.core.property.container.Dict` the method `validate` conflates the issue of `isinstance` with all invalid key errors and all invalid value errors.

### Expected behavior

A descriptive error should be raised explaining which key validation fails and why

### Observed behavior

The following message is raised:

ValueError: expected an element of ColumnData(String, Seq(Any)), got {'index': array([0, 1, 2]), 1: array([1, 2, 3]), 'a': array([1, 2, 3])}

### Example code

```Python
import pandas
from bokeh.models import ColumnDataSource
df = pandas.DataFrame({'a':[1,2,3], 1:[1,2,3]})
source = ColumnDataSource(df)
```

**Comment by bryevdv** [comment]
Bokeh has an extensive typed property system to mediate the communication between Python and Javascript. It has to handle all sorts of property validation errors for many dozens of types, and it always does so in a completely uniform way, by providing the same two pieces of information every time:

* What type was expected
* What value was received, that did not satisfy the type

For most types, which are simpler, this ends up looking like: 
```
ValueError: expected an element of Int, got "foo"
```
or 
```
ValueError: expected an element of String, got 10.3
```
or
```
ValueError: expected an element of List[Float], got None

```
I hope you will agree that these are useful error messages? [1] So I have to respectfully disagree that the message "tells the user nothing about the source of the problem" because that error message above is exactly the same: it tells you what was expected *(a mapping of strings to sequences)* and what it got that was bad *(a dict with a non-string key 1 inside)*.  [2] Moreover, I personally think there is value in having all the error messages for type validations present in an identical, uniform way. 

But it's true that this type is more complex than a type like `Int`. I guess you are asking for a message that is finer-grained and reports that the (integer) "1" key is specifically the problem? Please be more detailed in your proposal. What exact error reporting do you want to see here? What error should be presented if multiple keys have validation issues? What if they each have *different* validation issues? What if the dict values have validation issues instead of / in addition to key validation issues? What other compound types could use this feature, and what should their error detailing look like? There needs to be some balance between printing informative messages and avoiding the style of C++ compiler errors that spew ten pages of indecipherable output. 

Lastly, since you have delved in to the code are you willing to work on a PR for this feature yourself? This will probably involve implementing some new hook or mechanism to allow for per-type customization of the generic error reporting. (Happy to offer guidance)

Edit: to note that I removed `[BUG]` as the current message exactly reflects the behavior and intent of the generic type reporting system as it was originally designed.

[1] IME they are, in fact, more consistently informative than you get with many Python libraries
[2] This is the information a user needs to locate and identify the problem in *their code*. I don't understand your comment about "origin of the problem", i.e. what the location of the validation logic inside Bokeh has to do with anything, or why it would be useful to end-users in any way.

**Comment by marceloslacerda** [comment]
Maybe I had the wrong expectation. I generally expect that library devs assume that I'll look into the source if they don't understand something about the code. So when I got an exception that I didn't understand (in my defense even knowing what ColumnData stands for I have a hard time finding where it's role is explained) I just assumed that the dev expected that I would dig around the bokeh's source code and find out what I was doing wrong. So when I saw that the origin of the exception was erased I felt like that was a double whammy.

But sure, I would love to work on that issue, generally library devs just ignore my PR requests, it's the first time someone actually asks me to write one (🥲).

Speaking about a possible fix I agree that there are a bunch of ways to remedy this, some you might be more or less inclined to accept as a PR 🥺

The first thing that I would suggest would be to break the nested validation in https://github.com/bokeh/bokeh/blob/branch-3.3/src/bokeh/core/property/container.py#L205C14-L205C14 and append a bit of extra information about the validation error in msg. It wouldn't make everything perfect but at least it would make the error more debuggable.

To make this specific issue less likely to be reported again [prepare_value](https://github.com/bokeh/bokeh/blob/branch-3.3/src/bokeh/core/property/bases.py#L364) upon finding an error could check if the issue is due to mixed types and attach an user friendly message at the bottom of the exception (like the rust compiler often does), that could be helped by adding an extra argument to `ValueError` on `Dict.validate()` with the reason for the validation error.

Another extra extra that could be done to the source-code to prevent the issue from tripping newbies is to add an optional  parameter (default True) to `ColumnDataSource.__init__` that, if true, catches validation errors on `self.data.update(raw_data)` and tries to convery the raw_data columns before finally giving up.

Regarding whether the fine grained exception should accumulate every error found, I think that's a fun solution but that would probably involve me implementing exceptions that are monoids and I think that would end up causing different parts of your source to look too different from each other in how they handle errors. I think the simplest option would be to return the first validation error found.

That's all I can think for now. I'll try to setup a working environment while I wait for you to tell me how you want me to tackle this issue.

Thank you for the cordial reply! I don't get that often. 😊

**Comment by bryevdv** [comment]
> The first thing that I would suggest would be to break the nested validation in https://github.com/bokeh/bokeh/blob/branch-3.3/src/bokeh/core/property/container.py#L205C14-L205C14 and append a bit of extra information about the validation error in msg.

I agree that that is a quick and simple place to implement an improvement. Maybe even just something like:
```
bad_keys = [k for k in value.keys() if key_is_valid(k)]
bad_values = [v for v in value.vakues() if value_is_valid(v)]
```
up front, then if the "success" condition of "dict with no bad keys or values" is not met, those lists can be included in the `detail` message.  I think it would be straightforward to accept such a PR. 

> Another extra extra that could be done to the source-code to prevent the issue from tripping newbies is to add an optional parameter (default True) to ColumnDataSource.__init__ that, if true, catches validation errors on self.data.update(raw_data) and tries to convert the raw_data columns before finally giving up.

I would expect validation errors to happen already on [`source.data.update(bad_data)`](https://github.com/bokeh/bokeh/blob/branch-3.3/src/bokeh/core/property/wrappers.py#L376-L378) are you saying that is not the case?  Validation checks should happen on anything resembling an assignment or mutation. If not, that *would* be a bug, and an MRE would be helpful (in a new separate issue). 

> That's all I can think for now. I'll try to setup a working environment 

Let us know if you run into any issues, we have tried to cover all the bases in the dev docs, but Bokeh is fundamentally a complex project to develop on due to the cross-runtime nature, so sometimes there are still hiccups to getting set up.

**Comment by bryevdv** [comment]
> in my defense even knowing what ColumnData stands for 

Maybe another area where some extra info can improve. `ColumnData` is the actual name of the type, and it is very descriptive in a particular context, but maybe we can improve up on the message having *only* that. The current code does:
```python
 f"expected an element of {self}, got {value!r}"
``` 
I am not sure we can make `str(self)` return anything other than the classname `ColumnData` but maybe the message around it could be improved, e.g. by explicitly mentioning "mapping"
```python
f"expected a mapping type ({self}), got {value!r} with invalid keys: {bad_keys} and invalid values: {bad_values}"
```
We could take more care to not include `bad_keys` if there are no bad keys, etc but this is the general idea. But whatever you think would improve the message without changing `str(self)` would be welcome.

**Comment by marceloslacerda** [comment]
Is this an adequate implementation of Dict.validate to you?
```python
    def validate(self, value: Any, detail: bool = True) -> None:
        super().validate(value, detail)

        key_is_valid = self.keys_type.is_valid
        value_is_valid = self.values_type.is_valid
        msg = f"{value!r} could not be validated"
        if not isinstance(value, dict):
            raise ValueError(f"{msg}. Not a dict" if detail else "")
        bad_keys = [k for k in value.keys() if key_is_valid(k)]
        if bad_keys:
            raise ValueError(f"{msg}. {','.join(bad_keys)} are invalid keys" if detail else "")
        bad_values = [v for v in value.values() if value_is_valid(v)]
        if bad_values:
            raise ValueError(f"{msg}. {','.join(bad_values)} are invalid values" if detail else "")
```

Also I finished setting up the development environment, a couple tests don't seem to pass but I can run ` pytest tests/unit/bokeh/core/property/test_container.py` with no problems.

**Comment by bryevdv** [comment]
@marceloslacerda Good start, just a few suggestions:

Almost all property errors start with something like `f"expected an element of {self}, got ..."` This inclusion of `self` in the message will cause the exact (Bokeh) property type to be included, and I do think that is important. I also just realized that it might be more helpful to report the corresponding keys for any bad values, rather than the values themselves? Just given the values, it would be hard to back out which key it corresponds to inside a the dict. 

So in sketch, maybe something like:
```python
expected = f"expected a dict of type {self}"

if not isinstance(value, dict):
    raise ValueError(f"{expected}, got a value of type {type(value)")

if any(bad_keys := (k for k in value if not key_is_valid(k))):
    raise ValueError(f"{expected}, got a dict with invalid keys: {','.join(bad_keys)}")

if any(bad_value_keys := ((k for (k, v) in value.items() if not value_is_valid(v))):
    raise ValueError(f"{expected}, got a dict with invalid values for keys: {','.join(bad_value_keys)}")
```

I'd suggest playing around with that and opening a PR even if draft (easier to comment on code in a PR)

We could also consider supplying the bad values along with the `bad_value_keys` but especially for CDS data, the values might actually be huge arrays. I think just providing the corresponding keys might be friendlier, but let me know what you think. But also if we do want to include them they will need to be explicitly `str`-ified before passing to `join`.

Lastly, just style nits, we do like vertical space quite alot, and also the judicious application of the walrus operator :)

**Comment by marceloslacerda** [comment]
Hi @bryevdv I made a PR with the suggested changes. There are a few things that I'm not sure about.

* What do you mean "by we do like vertical space quite alot", you mean using more compact code solutions like the `any(...)` in the code?
* Do you have a style guide or code formatter for the project?
* I made a [valid Dict test](https://github.com/marceloslacerda/bokeh/blob/bokeh%2313295/tests/unit/bokeh/core/property/test_validation__property.py#L192) to see if it wouldn't raise an error on a valid dict. I'm not sure that you find it useful.
* The pull request I made failed on a macos build but I see no error message. How do I proceed?

**Comment by bryevdv** [comment]
Thanks @marceloslacerda I've left a few comments in the PR (FYI it's easier/better to keep discussion about the PR itself, in the PR) The failing test is a spurious failure, we currently have some flaky tests unfortunately. Our code style is pretty loose, what we do have is here: https://docs.bokeh.org/en/latest/docs/dev_guide/python.html#code-style  We don't currently use any formatter, `black`'s inexplicable decision to admit AST-unsafe transformations and docstring modifications without any opt-out make it unsuitable for us.
