### ISSUE TITLE
`Stamen` tiles were removed from xyzservices 2023.10.1

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#13490]
From https://github.com/geopandas/xyzservices/releases/tag/2023.10.1:

> Stamen tiles have been removed due to their upstream deprecation. Use Stamen styles of Stadia 

CI is failing with:
```
tests/test_examples.py::test_file_examples[/home/runner/work/bokeh/bokeh/examples/topics/geo/tile_demo.py-example370-config370] 
[INFO] Example run in 0.853s
[PY] Traceback (most recent call last):
[PY]   File "<string>", line 18, in <module>
[PY]   File "/home/runner/work/bokeh/bokeh/examples/topics/geo/tile_demo.py", line 49, in <module>
[PY]     plot.add_tile(vendor_name)
[PY]   File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/bokeh/models/plots.py", line 415, in add_tile
[PY]     selected_provider = xyzservices.providers.query_name(tile_source)
[PY]   File "/usr/share/miniconda3/envs/bk-test/lib/python3.9/site-packages/xyzservices/lib.py", line 292, in query_name
[PY]     raise ValueError(f"No matching provider found for the query '{name}'.")
[PY] ValueError: No matching provider found for the query 'stamen terrain'.
```

**Comment by jbednar** [comment]
We have the same issue in HoloViz, and have not yet figured out whether to switch to Stadia (and thus set up an API key) or something else public.

**Comment by bryevdv** [comment]
We already have a duct-tape solution to replace `"GOOGLE_API_KEY"` with an API stored in a GH secret when building the docs. I don't think it would be much of a chore to add some other key in a similar way. The main nuisance is that in order to be nice to users we have to clutter up the examples with junk like:
```python
if plot.api_key == "GOOGLE_API_KEY":
    plot.add_layout(Label(x=140, y=400, x_units='screen', y_units='screen',
                          text='Replace GOOGLE_API_KEY with your own key',
                          text_color='red'))
```
Perhaps we could do better by adding functionality at the property level? i.e. something like 
```python
api_key = APIKey(placeholder="GOOGLE_API_KEY")
```
Then if the value is `"GOOGLE_API_KEY"` then BokehJS handles popping up a warning on its own, so that we can get rid of the example clutter. If we did this we could also potentially strengthen the duct-tape in the docs code (it could scan for `APIKey` properties automatically instead of hard-coding what placeholders to replace)

**Comment by mattpap** [comment]
Migration guide: https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles.
