### ISSUE TITLE
[FEATURE] Dispatch RangesUpdate events on all range changes

### ISSUE THREAD

**Issue by droumis** [bokeh/bokeh#13507]
### Problem description

If you are listening to a RangesUpdate on a plot, you always want to know when the ranges on that plot update. In the case of updates on a target plot range caused by changes with the RangeTool of a source plot, it appears that RangesUpdates are not dispatched.

@philippjfr, please correct me if I got this wrong or if I am missing something. 

### Feature description

This is related to [#12110](https://github.com/bokeh/bokeh/issues/12110), although that seems more about registering the RangesUpdate event on a range.

### Potential alternatives

None

**Comment by bryevdv** [comment]
@droumis There's nothing we can do here with existing `RangesUpdate` since it is specifically intended for when *two* ranges (the default ranges for a plot) are updated at the same time, e.g. by a wheel zoom tool. In that case `RangesUpdate` solves the issue with users having to register for separate events on separate ranges when what they really wanted was one combined event. But a range in a range tool is not like that combined case. By definition an update from a `RangeTool` could only update a single range. 

Besides the conceptual difficulties, there are also practical implementation issues. `RangesUpdate` is triggered by an API on `Plot` that e.g. a zoom tool on a plot can call. But a range configured on a range tool does not have to belong to any plot in general, and even if it does, there's no "back-reference" to know what plot(s) that might be. And even if there that, what would supposed to happen? Look for changes on a single range then issue a `RangesUpdate` with only update for that one range but not the other? That would literally defeat the entire purpose of `RangesUpdate` by subjecting users to updates for single ranges at a time. which is exactly what is supposed to avoid. 

---

What the other issue alludes to is a mechanism that can provide one combined event when a single range changes both `start` and `end` at the same time. i.e. a `RangeUpdate` (new event, no plural). That's potentially something we could consider adding. It would be generated mostly by tools that might update both `start` and `end` at the "same time" e.g. pan, zoom, range tools. Then users could do:
```
range.on_event(events.RangeUpdate, callback)
```
This *would* be an event on the range, not the plot. 

It would take some investigation on how how and where to fit this in. Presumably a change that updates both ranges on a plot and results in a `RangesUpdate` should also result in `RangeUpdate` being emitted by both the ranges in question. Theres also the questions of whether `RangeUpdate` should exclusively for simultaneous start/end updates or if any update should trigger (if so we probably should annotate the even with exactly what got updated)

**Comment by philippjfr** [comment]
Thanks for the detailed writeup @bryevdv. I've discussed this with @mattpap in the past and I now vaguely remember that he raised some of the same concerns. Putting the technical concerns aside for a minute, from a user perspective when I subscribe to a `RangesUpdate` event on a plot I don't much care what triggered the changes in the range or whether one or both ranges changed. Usually such a callback will trigger some computation and/or render something that is dependent on the current ranges on that plot and if something causes that to go out of sync because only some interactions trigger the event that seems less than ideal.

On the technical side the answer may not be the `RangesUpdate` event but I do think there should be a mechanism to watch for changes on all ranges of a plot that also deduplicates events when start and end is set or multiple ranges are updated at once. The simplest mechanism I can think of for this is some very short debouncing/throttling period where ranges set in short succession do not trigger distinct events. @mattpap might have a better idea though.

**Comment by bryevdv** [comment]
TBH there are a *lot* of deficiencies with `RangesUpdate`. All I don't want is to bolt more junk on top of it. If we need a better more capable solution, that's great, let's build a proper one that satisfies all the requirements from design principles, and deprecate `RangesUpdate`. Of the top of my head:

* need a way to know, for a single range, when "combined" updates happen. This seems like an event on ranges, not plots. The event could happen on any change of `start`, `end`, or both, but needs to indicate what was actually updated or not

* need a way to know, for a plot, when any of its ranges were updated, including "combined" updates, and also to know exactly what was updated (or not). This seems like an even on plots, because it concerns the collection of ranges that a plot has, together. This is like `RangesUpdate` but more capable and flexible, e.g. not just for default ranges since plots can contain additional ranges. 

* These both need to be coordinated together in sensible and described way. Since we are dealing with multiple property updates together, we can't rely on the property system for this. [1] We need to define actual API on plot and range that can be used to make a combined range or combined plot ranges update. Ideally we are confident enough in these APIs that users could use them in JS callbacks because I know they would get used. 

Is there any argument that we don't have to have two separate events, one on ranges, to signal for that single range itself, and one on plots, to signal for a collection of ranges?

[1] The other more route is to develop a generic event system for setting and reporting any multiple properties at once, and then build on top of that. That also seems good/fine but is more work. we might have the same specific range/plot events and API in either case though, since they are of specific interest for users. So we could proceed with just those parts in a specialized implementation to start, and replace with a generic underlying system later.

**Comment by bryevdv** [comment]
> a mechanism to watch for changes on all ranges of a plot that also deduplicates events when start and end is set or multiple ranges are updated at once. 

I only just appreciated this. I think trying to come at it from this angle will not result in happiness. I think it would be complicated and fragile and painful. I just reiterate what I said above: I think we need supported, maintained API for setting multiple range properties at once (or more general API for setting multiple any-properties at once). Those API calls can drive the events from the initiation, which seems much simpler and robust than trying to magic them out of a post-facto observation of lots of events that already happened.
