### ISSUE TITLE
make bokeh relocatable

### ISSUE THREAD

**Issue by bjarthur** [bokeh/bokeh#13628]
### Problem description

after i install with conda, the main bokeh entry point is a python script which hard codes the path to python using a shebang.  like this on my system:

```
#!/home/arthurb/.miniconda3/envs/bokeh/bin/python3.12       ### THIS LINE IS THE PROBLEM
# -*- coding: utf-8 -*-
import re
import sys

from bokeh.__main__ import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

as a consequence, if i want to make a tarball of my application to distribute to users so that they don't have to install conda, like this:

```
cd $CONDA_PREFIX/..
tar czf my-bokeh-app.tar.gz my-bokeh-app
```

bokeh complains that it can't find python.

the workaround is to have my app call bokeh like this:

```
from subprocess import run
run([*(["bokeh"] if platform.system()=='Windows' else
       ["python", shutil.which("bokeh")]),
     ...)
```

but why should it be this complicated, when that shebang could just be the usual `#!/usr/bin/env python`?

### Feature description

use `/usr/bin/env python` in the shebang instead of hard-coding the path

### Potential alternatives

not doing anything

**Comment by bryevdv** [comment]
The entry point script is generated. setuptools and/or conda is doing this. I'm not sure offhand how to make the behavior different or if that's even possible. 

In any case, you could run `python -m bokeh` instead, which will function the same on all platforms.

**Comment by bryevdv** [comment]
I am inclined to close this with `upstream` or `noaction` since I don't think spending time fighting against the default behaviors of these tools will lead to happiness, and there is a reasonable alternative already (we provide a `__main__.py` specifically for this reason). Alternatively, having to perform fixups on vendored packages is common, AFAICT, so another option is simply to patch the entry point script to suit your needs during your own build process. In any case the behavior of these tools with respect to manual vendoring is outside the scope of Bokeh itself. 

But cc @bokeh/dev in case there are other strong opinions.

**Comment by bjarthur** [comment]
bokeh is the only conda package i'm aware of that is not relocatable.  are there others?

**Comment by bryevdv** [comment]
> are there others?

I have no idea, but my point still stands: The `bokeh` executable script is not something we generate. It's literally just the result of the simplest default config for these things

For setuptools:

https://github.com/bokeh/bokeh/blob/ef036a25e91ec2a813fb58a6dfa59e1a6fba9c9f/pyproject.toml#L63-L64

For conda:

https://github.com/bokeh/bokeh/blob/ef036a25e91ec2a813fb58a6dfa59e1a6fba9c9f/conda/recipe/meta.yaml#L10-L17

I'm happy to consider very simple changes to this on a minor release boundary if anyone has any concrete ideas to suggest.

**Comment by bryevdv** [comment]
FWIW I just `pip` installed Bokeh into a conda env, and I see the hard-coded path in that case as well. So offhand I'd speculate that the `setuptools` is responsible for the specific contents of the shebang line, and then that that carries forward to conda since our overall build flow is "wheel-foward". Again, all speculation at this point. 

I would say there is zero possibility that we change our overall build to do anything other than derive conda packages from wheels. It was an enormous lift to get things where they are now, utilizing more modern practices (i.e. PEP 517, not running `setup.py` as a script, etc.), working for both packaging platforms with a single source of truth and being able to handle our specialized requirements to vendor BokehJS inside the packages.

If there are simple `setuptools` configuration changes that will fix things, we can try them. Some ancient SO answers seem to suggest that there may be a configuration but also that sepcial non-default build invocations are required too, which is not encouraging. Don't forget, any changes have to not-break things on Windows. 

Again, `python -m <package>` is the platform neutral way to invoke a Python package "main" and AFAICT, and e.g. from various discussions on DPO, it is in fact starting to be advocated as the preferred method in general.

**Comment by ianthomas23** [comment]
> bokeh is the only conda package i'm aware of that is not relocatable. are there others?

Yes! If I create a conda environment containing bokeh, matplotlib, panel, jupyterlab, etc:

```
$ egrep "#\!/home/iant/.miniconda" * 
2to3:#!/home/iant/.miniconda/envs/t/bin/python3.11
2to3-3.11:#!/home/iant/.miniconda/envs/t/bin/python3.11
bokeh:#!/home/iant/.miniconda/envs/t/bin/python
colorcet:#!/home/iant/.miniconda/envs/t/bin/python
datashader:#!/home/iant/.miniconda/envs/t/bin/python
f2py:#!/home/iant/.miniconda/envs/t/bin/python
fonttools:#!/home/iant/.miniconda/envs/t/bin/python3.11
holoviews:#!/home/iant/.miniconda/envs/t/bin/python
idle3:#!/home/iant/.miniconda/envs/t/bin/python3.11
idle3.11:#!/home/iant/.miniconda/envs/t/bin/python3.11
ipython:#!/home/iant/.miniconda/envs/t/bin/python
ipython3:#!/home/iant/.miniconda/envs/t/bin/python
jlpm:#!/home/iant/.miniconda/envs/t/bin/python
jsonschema:#!/home/iant/.miniconda/envs/t/bin/python
jupyter:#!/home/iant/.miniconda/envs/t/bin/python
jupyter-dejavu:#!/home/iant/.miniconda/envs/t/bin/python
jupyter-events:#!/home/iant/.miniconda/envs/t/bin/python
jupyter-execute:#!/home/iant/.miniconda/envs/t/bin/python
jupyter-kernel:#!/home/iant/.miniconda/envs/t/bin/python
jupyter-kernelspec:#!/home/iant/.miniconda/envs/t/bin/python
jupyter-lab:#!/home/iant/.miniconda/envs/t/bin/python
jupyter-labextension:#!/home/iant/.miniconda/envs/t/bin/python
jupyter-labhub:#!/home/iant/.miniconda/envs/t/bin/python
jupyter-migrate:#!/home/iant/.miniconda/envs/t/bin/python
jupyter-nbconvert:#!/home/iant/.miniconda/envs/t/bin/python
jupyter-run:#!/home/iant/.miniconda/envs/t/bin/python
jupyter-server:#!/home/iant/.miniconda/envs/t/bin/python
jupyter-troubleshoot:#!/home/iant/.miniconda/envs/t/bin/python
jupyter-trust:#!/home/iant/.miniconda/envs/t/bin/python
markdown-it:#!/home/iant/.miniconda/envs/t/bin/python
markdown_py:#!/home/iant/.miniconda/envs/t/bin/python
matplotlib:#!/home/iant/.miniconda/envs/t/bin/python
normalizer:#!/home/iant/.miniconda/envs/t/bin/python3.11
numba:#!/home/iant/.miniconda/envs/t/bin/python
panel:#!/home/iant/.miniconda/envs/t/bin/python
pip:#!/home/iant/.miniconda/envs/t/bin/python
pip3:#!/home/iant/.miniconda/envs/t/bin/python
pybabel:#!/home/iant/.miniconda/envs/t/bin/python
pyct:#!/home/iant/.miniconda/envs/t/bin/python
pydoc:#!/home/iant/.miniconda/envs/t/bin/python3.11
pydoc3:#!/home/iant/.miniconda/envs/t/bin/python3.11
pydoc3.11:#!/home/iant/.miniconda/envs/t/bin/python3.11
pyftmerge:#!/home/iant/.miniconda/envs/t/bin/python3.11
pyftsubset:#!/home/iant/.miniconda/envs/t/bin/python3.11
pygmentize:#!/home/iant/.miniconda/envs/t/bin/python
pyjson5:#!/home/iant/.miniconda/envs/t/bin/python3.11
pyuic5:#!/home/iant/.miniconda/envs/t/bin/python
sip-build:#!/home/iant/.miniconda/envs/t/bin/python
sip-distinfo:#!/home/iant/.miniconda/envs/t/bin/python
sip-install:#!/home/iant/.miniconda/envs/t/bin/python
sip-module:#!/home/iant/.miniconda/envs/t/bin/python
sip-sdist:#!/home/iant/.miniconda/envs/t/bin/python
sip-wheel:#!/home/iant/.miniconda/envs/t/bin/python
tqdm:#!/home/iant/.miniconda/envs/t/bin/python
ttx:#!/home/iant/.miniconda/envs/t/bin/python3.11
wheel:#!/home/iant/.miniconda/envs/t/bin/python
```
This is not a Bokeh issue, it is how Python projects are installed.

**Comment by ianthomas23** [comment]
> if i want to make a tarball of my application to distribute to users so that they don't have to install conda ...

This is a strange workflow. Certainly you can distribute your own code however you wish, but you shouldn't include any of Bokeh's code in your tar file and expect others to be able to use it. They need to install Bokeh themselves, via `pip` or `conda`, preferably in a virtual environment.

**Comment by bryevdv** [comment]
I don't think there is any action for us to take here. If someone (other than me) wants to look into and make concrete configuration change proposals, I'll commit to try to test/evaluate them, and we can re-open.

**Comment by bryevdv** [comment]
> This is a strange workflow. Certainly you can distribute your own code however you wish, but you shouldn't include any of Bokeh's code in your tar file and expect others to be able to use it. They need to install Bokeh themselves, via pip or conda, preferably in a virtual environment.

There may also be tools like `pyinstaller`, etc that can help automate this sort of vendoring. But anyone doing without those tools should probably expect to have to manually do all the fixups and other things that they do, manually, themselves.
