### ISSUE TITLE
DOC Missing vertical gap between grid items in First Steps guides

### ISSUE THREAD

**Issue by raj-pulapakura** [bokeh/bokeh#13631]
I couldn't find an option for submitting documentation-related issues, so I had to resort to this option (sorry if I wasn't meant to use this specific issue type).

## Expected behaviour

There should be a vertical gap between the grid elements on this [doc page](https://docs.bokeh.org/en/latest/docs/first_steps.html#first-steps-guides).

## Observed behaviour

There is no vertical gap between the grid components.

![Screenshot 2024-01-04 153708](https://github.com/bokeh/bokeh/assets/87762282/17753824-1b5d-4afb-9548-5d52a383850e)

## How to fix

Using the Chrome Dev Tools, I've located the relevant CSS that controls this vertical gap.

However I am unsure how to update the CSS in the codebase, which is why I created this issue instead of directly submitting a PR.

![Screenshot 2024-01-04 153851](https://github.com/bokeh/bokeh/assets/87762282/feee31ad-b014-4c96-ae79-a7146ebf1059)
![Screenshot 2024-01-04 153942](https://github.com/bokeh/bokeh/assets/87762282/dbb74c27-7d5a-4b57-a4d3-f57ebd874af5)

**Comment by bryevdv** [comment]
I guess it's not immediately clear to me that adding a gap there is necessarily an improvement. The vertical stacking already has the title header color difference to differentiate the cards. But @tcmetzger should chime in with the desired behavior, and if it turns out to be adding a space then the change can go into `source/_static/custom.css`

**Comment by raj-pulapakura** [comment]
@bryevdv It's true that the header color already distinguishes the next row, but I just thought I would let you guys know instead of keeping it to myself. Tbh it's just a pet peeve, but I'd be happy to fix it if @tcmetzger is alright with it.

**Comment by tcmetzger** [comment]
I think adding that gap makes sense - I even believe it used to be there, and then was probably lost due to some theme updates. Feel free to update this, the CSS is in `docs/bokeh/source/_static/custom.css`!

Please note that our docs are currently not building well on Windows, in case that is what you are using. To build and test our docs locally, I'd recommend you use WSL (if you don't have access to macOS/Linux). https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html and https://docs.bokeh.org/en/latest/docs/dev_guide/documentation.html are probably good starting points!

**Comment by bryevdv** [comment]
@raj-pulapakura did you still want to submit a PR?

**Comment by raj-pulapakura** [comment]
Hi @bryevdv , pardon my inactivity. I was a little busy these past weeks and I was also struggling to build the docs on my Windows machine. Thanks for pinging me, I'll see if I can get this done soon.

**Comment by raj-pulapakura** [comment]
Hi @bryevdv I can't seem to bulid the docs on Windows, and WSL isn't working for some reason. Will have to pass this one on, apologies.
