### ISSUE TITLE
Stadia tiles not displaying

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#13669]
Warning tile reports a 401 error:

<img width="1023" alt="Screenshot 2024-01-25 at 13 12 08" src="https://github.com/bokeh/bokeh/assets/1078448/d3098c5c-b6ce-4ad8-bcbe-acf78d1667ec">

I think this section of the docs is relevant: https://docs.stadiamaps.com/authentication#domain-based-authentication

**Comment by tcmetzger** [comment]
Yes, the thing is: What used to be Stamen (now Stadia) is no longer freely accessible. If I understand correctly, these tiles can still be used with Bokeh (via [xyzservices](https://github.com/geopandas/xyzservices)), but require a key and subscription (as described in https://xyzservices.readthedocs.io/en/stable/registration.html#stadia-maps). 

I'd say we should remove all Stamen/Stadia examples from our docs and replace them with other providers where necessary (such as USGS or other freely accessible providers from this list: https://xyzservices.readthedocs.io/en/stable/gallery.html).

**Comment by bryevdv** [comment]
Are stadia tiles non-free, or only require a registration? We could potentially register the service account and allow-list the `bokeh.org` domain (I think)?

**Comment by tcmetzger** [comment]
They do have a free tier with limited calls ("200,000 credits / month" which, I believe, translates into 200,000 tile requests per month) and that does not allow commercial use (https://stadiamaps.com/pricing/).
Meaning yes, we could probably create a key for bokeh.org, but there is still the risk of us actually hitting the monthly call rate limit, or them changing their terms or call limits without us noticing in the future. Since we are just using these tiles for demo purposes, I'd prefer to use other sources that are actually "free", such as OSM or USGS. 
I think the main purpose of those examples is to demonstrate that Bokeh can display tiles from a wide variety of providers - I don't think we necessarily need to demo Stadia tiles specifically.

**Comment by tcmetzger** [comment]
PR #13671 would look like this:
![image](https://github.com/bokeh/bokeh/assets/39711796/ffa016d3-4b12-4a38-9f3e-5b8c80b2a62b)
