### ISSUE TITLE
Release build fails after PR #13901

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#13902]
See https://github.com/bokeh/bokeh/actions/runs/9134594077/job/25120443390#step:8:185:
```
------ Starting task pack_deployment_tarball
+mkdir deployment-3.5.0.dev4
+cp bokehjs/bokeh-bokehjs-3.5.0-dev.4.tgz deployment-3.5.0.dev4
+cp $CONDA_PREFIX/conda-bld/noarch/bokeh-3.5.0.dev4-py_0.tar.bz2 deployment-3.5.0.dev4
+cp dist/bokeh-3.5.0.dev4.tar.gz deployment-3.5.0.dev4
+cp dist/bokeh-3.5.0.dev4-py3-none-any.whl deployment-3.5.0.dev4
+mkdir deployment-3.5.0.dev4/bokehjs
+cp -r bokehjs/build deployment-3.5.0.dev4/bokehjs
+mkdir -p deployment-3.5.0.dev4/docs/bokeh/build
+cp -r docs/bokeh/build/html deployment-3.5.0.dev4/docs/bokeh/build
+cp -r docs/bokeh/switcher.json deployment-3.5.0.dev4/docs/bokeh
[FAIL] Could NOT pack deployment tarball
    cp: cannot stat 'docs/bokeh/switcher.json': No such file or directory
```

**Comment by bryevdv** [comment]
cc @mosc9575 

Since there were also changes to `switcher.json` I missed in the GH UI that the file location had also been moved. I think the file needs to be moved back, not just because of the error above, but because it does not makes sense for the switcher file to reside inside any given version of the docs. The switcher file concerns _all_ versions of the docs, and therefore should reside outside the built docs. 

I guess I would also just add: I don't actually personally care if the version switcher is broken for local docs. I think we can assume that the `pydata-sphinx-theme` project does their own testing to make sure it works, assuming `switcher.json` is configured correctly.

**Comment by mosc9575** [comment]
I will move the `switcher.json` back and try if `../switcher.json` is a valid path in `conf.py`. If not I revert my changes in this file.
