### ISSUE TITLE
[BUG] Undesirable boundaries visible between adjacent quads

### ISSUE THREAD

**Issue by TheoMathurin** [bokeh/bokeh#14192]
### Software versions

Python version        :  3.12.8 (main, Dec  4 2024, 20:39:59) [GCC 12.2.0]
IPython version       :  (not installed)
Tornado version       :  6.4.2
NumPy version         :  1.26.3
Bokeh version         :  3.6.2
BokehJS static path   :  /usr/local/lib/python3.12/site-packages/bokeh/server/static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-6.11.10-200.fc40.x86_64-x86_64-with-glibc2.36

### Browser name and version

Firefox 133.0 / Chromium 131.0

### Expected behavior

Delineations between adjacent quads should not be visible or at least there should be a way to get rid of them.

### Observed behavior

When plotting a contiguous area of quads, there are gray or white lines visible between quads. To me these artifacts are not desirable, most notably when quads are used to plot images with coordinates that are not evenly sampled (_e.g._ by holoviews' QuadMesh element).

See issue https://github.com/holoviz/holoviews/issues/6467 where the problem was first mentioned.

I've just noticed that the problem still exists but is not as severe in Chromium 131.0.6778.85 on my computer.

### Example code

```Python
from bokeh.plotting import figure, show
import numpy as np

size = 10
top = np.repeat(np.arange(size), size)
bottom = top - 1
left = np.tile(np.arange(size), size)
right = left + 1

p = figure(width=400, height=400)
p.grid.visible = False
p.quad(top=top, bottom=bottom, left=left, right=right, color="#000000")

show(p)
```

### Screenshots

Firefox : 
![Image](https://github.com/user-attachments/assets/ed4f259f-16fc-49aa-97c1-0819ccb89462)

Chromium : 
![Image](https://github.com/user-attachments/assets/fae69037-5861-40e0-8c1f-c4c52009bfdd)

**Comment by ianthomas23** [comment]
This is because we are using "premultiplied alpha" for our alpha (transparency) blending. There is a choice to use it or not. If you use it you get very good alpha blending of images, but at the edges of polygons where the finite antialiasing edges overlap the blending is less good as you have seen. The alternative of using postmultiplied alpha makes these artifacts go away but alpha blending of images is unacceptably poor. All pixel-based renderers have to make this decision, and nearly 100% of them choose premultiplied alpha because the alternative is unacceptable. You can read about it at https://developer.nvidia.com/content/alpha-blending-pre-or-not-pre.

So although this is annoying, it is not going to go away.

**Comment by bryevdv** [comment]
I agree there is probably not much we can do about this. In the past we tried adding an option to `rect` to "dilate" i.e. always round up transformed pixel coordinates, in case users would prefer to suffer potential overlap instead of potential gaps, but IIRC it never really worked well either.

**Comment by TheoMathurin** [comment]
Many thanks for your replies.

If enabling rounding to nearest pixels (as I understand [is done](https://github.com/holoviz/holoviews/issues/6467#issuecomment-2529251416) for `HSpan`/`VSpan`) does not yield good results, I guess there is not much of a solution here indeed. I didn't think such low-level considerations were involved and as I saw that matplotlib plots were not affected by this issue, I thought this could be fixed more or less easily.

**Comment by ianthomas23** [comment]
Matplotlib plots are very much affected by this, for example issue from 12 years ago matplotlib/matplotlib#1188 with lots of links to other issues. I have written almost exactly the same explanation to such Matplotlib issues in the past. There have been conversations about using slightly wider lines at the edges of polygons which can be acceptable if `alpha=0` but is very bad if `alpha<0`. There are other ~hacks~ workarounds too, none of which are universally good.

If you render multiple polygons of the same color and alpha as a single compound polygon, in Bokeh or Matplotlib, then the problem can disappear. So here instead of using `quad` glyphs which are rendered one at a time, use a single `multipolygon` instead. If you are writing Bokeh code directly then this is quite easy.

**Comment by TheoMathurin** [comment]
Alright, I did not know this affected matplotlib too. My test was superficial as it just consisted in switching from bokeh to matplotlib backend in holoviews and the artifacts were not visible at all. Same thing for the code in the docs for `pcolormesh`, but the example given in the issue you mentioned is a counter example. I cannot yet grasp the circumstances in which the issue manifests itself or not and to what extent.

In my use case I have rectangles sharing alpha (which is 1) but not colour. I will try to find a way to mitigate the issue.

Thanks again. Should this issue be closed and tagged as a "can't fix"?

**Comment by ianthomas23** [comment]
> I cannot yet grasp the circumstances in which the issue manifests itself or not and to what extent.

Yes, that is only possible by understanding what is happening at the lowest level of implementation, and that is not something that many people have any reason to look at.

If you are trying to do a holoviews `QuadMesh`, the Bokeh and Matplotlib implementations are fundamentally different. In Bokeh each quad is drawn as a discrete rectangle of a single color with antialiasing along the edges. In Matplotlib it is implemented as a `pcolor`/`pcolormesh` plot which AFAICR is pixel-based, so each pixel within the mesh is rendered just once with the color determined by which quad it maps to, and there are no edge-based artifacts as there are no such edges.

Bokeh does not have a `pcolor` pixel-based plot, because HTML canvas (the default output backend) doesn't haven't an API for this. Writing our own WebGL-based implementation would be fairly simple, a Canvas one would not be simple although I have some ideas of how it could be done. So as with most things in Open Source, all it needs is someone with sufficient time and motivation to do it.

> Thanks again. Should this issue be closed and tagged as a "can't fix"?

Yes please.

**Comment by TheoMathurin** [comment]
> In Matplotlib it is implemented as a pcolor/pcolormesh plot which AFAICR is pixel-based, so each pixel within the mesh is rendered just once with the color determined by which quad it maps to, and there are no edge-based artifacts as there are no such edges.

Yet there seem to be situations where `pcolormesh` does show edges, cf. examples in the issue you pointed to.

I'll close, feel free to tag as you see fit!

**Comment by bryevdv** [comment]
Thanks for the explanations @ianthomas23 I was actually not aware that is how `pcolormesh` functioned, so learning about this difference in more detail is very informative. Although we don't currently have a precedent for any WebGL-*only* features, I'd say it might be worth considering in this case, on the basis that something easy to add, is better then nothing (people have definitely variously asked about `pcolormesh` on more than a few occasions over the years).
