### ISSUE TITLE
GridPlot ignores `title` property

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1449]
It would be nice to be able create nice, large title summing up all individual plots.

**Comment by rothnic** [comment]
Just wanted to mention I added a title for crossfilter's grids as part of #1774, then realized it doesn't render. I left it in in case this is worked on.

**Comment by birdsarah** [comment]
This was not done as part of #4392, but would now be easy to add to the gridplot function: https://github.com/bokeh/bokeh/blob/master/bokeh/layouts.py#L71

**Comment by mattpap** [comment]
@birdsarah, can this issue be closed?

**Comment by bryevdv** [comment]
There are two possible approached:

* have `gridplot` return something like `Column(Div(...), GridPlot(...))` where the div holds the title. This is maybe not great since it may subvert user expectations by returning something that is not `GridPlot` But this could be done with no BokehJS modifications.
 
* Modify the implementation of `GridPlot` on the BokehJS side to render a title when asked

**Comment by bryevdv** [comment]
This issue is no longer valid, the `gridplot` function does not accept a `title` 👍 
```
TypeError: gridplot() got an unexpected keyword argument 'title'
```
This has really never come up as a support issue I am inclined to close with `noaction` and tell people to use `column(div, gridplot)` as a solution.
