### ISSUE TITLE
wheel zoom interaction improvements

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1450]
It's a little unintuitive when you have a big plot, no zoom happens and window doesn't scroll either.

---

This now marked `feature`:

* [x] do not capture mouse events when tool is inactive
* [ ] capability to have tool, but not have it enabled by default

**Comment by ijstokes** [comment]
Here is my suggestion, further to #2113.

1. If this is possible, identify when the mouse pointer with mouse scroll events (to trigger zoom) is the result of page scrolling.  Maybe have a "buffer" zone around the edges of each plot which would identify that the pointer has entered from the edges *while already scrolling*, possibly (probably?) as a result of a page scroll, *rather than* as a result of an intention to scroll-zoom the plot.  I have no idea if that sort of thing is i) possible; ii) practical; or iii) desirable for other UX reasons.

2. Require some kind of "activate interaction" event, like clicking on the plot, before "scroll" events would be captured and interpreted as "zoom".

**Comment by pzwang** [comment]
On Sunday, March 29, 2015, Ian Stokes-Rees <notifications@github.com> wrote:

> Here is my suggestion, further to #2113
> <https://github.com/bokeh/bokeh/issues/2113>.
>
>    1.
>
>    If this is possible, identify when the mouse pointer with mouse scroll
>    events (to trigger zoom) is the result of page scrolling. Maybe have a
>    "buffer" zone around the edges of each plot which would identify that the
>    pointer has entered from the edges *while already scrolling*, possibly
>    (probably?) as a result of a page scroll, *rather than* as a result of
>    an intention to scroll-zoom the plot. I have no idea if that sort of thing
>    is i) possible; ii) practical; or iii) desirable for other UX reasons.
>
>
>
> I think I understand what is being proposed here, and I think it's very
difficult to get right. That scroll buffer would need to be a very large
size in order to trap scroll events for all user scroll speed settings. But
a large buffer would then make it difficult to put plots next to each other
(hstack / vstack) without conflicting event grabs.

Maybe one option is to install a global scroll event watcher on the entire
page that sets a bit "high" for the entire Bokeh library if there was a
scroll event in the last XX milliseconds... Hmm, that might actually work.

>
>    1.
>
>    Require some kind of "activate interaction" event, like clicking on
>    the plot, before "scroll" events would be captured and interpreted as
>    "zoom".
>
> No, that is too difficult for new users to discover, therefore you'd need
to document it or waste screen space talking about it...

>

**Comment by bryevdv** [comment]
Just to note, a few of us have tried to make suggestion 1 succeed and failed. So at this point a concrete code exampleor prototype that demonstrates that this can be made to work  would do more to convince me to spend time on the direction. 

I agree with Peter that suggestion 2 is completely undiscoverable. 

My current notion is just to make it such that that wheel zoom tool is never default active tool. Even if it is the only wheel tool, it would still have to be activated in the tool bar before it can be used. That is probably the best short/immediate term solution.

**Comment by birdsarah** [comment]
Haven't dug in to bokehjs code yet, but excited to take this on in a couple of weeks (after Pycon) if no-one else has. I've been burned by it before, and was on the Charts docs on an iphone today and it wasn't pretty.

**Comment by damianavila** [comment]
Reopened, only first point is addressed by #2703.

**Comment by jbednar** [comment]
It would be great if there could be some movement on point 2 -- it's really very annoying when using the scroll wheel to look at a notebook or other web page with several plots, and then suddenly one of the plots starts resizing, sometimes even messing up the aspect ratio (if I happened to be hovering over an axis).  Zooming using the scroll wheel is great, but only once one is really studying a specific plot, and it's disorienting otherwise.  Right now, just browsing over a document leaves it littered with messed-up plots!  Selecting the wheel zoom tool for the plot specifically seems like a reasonable solution to me.  

I would also vote for wheel zooming not to expand past the data available, by default (since that is almost never useful), but that's a separate matter.
