### ISSUE TITLE
plotting interface: text does not work with data source

### ISSUE THREAD

**Issue by viveksck** [bokeh/bokeh#1468]
While plotting interfaces like line, scatter can take a ColumnDataSiurce as input,  passing a datas source to the text function exposed by plotting interface does not work. 

I have scatter plot with labels which needs to be updated as time progresses, but because I cant bind this to a data source this does not work. 

Something like this does not work:
    `self.textsource.data = dict(x=tx, y=ty, text=labels, angle=angles)`
    `obj.plot_text = obj.plot.text('x', 'y', 'text', 'angle', source=obj.textsource)`

The text is never displayed.

**Comment by bryevdv** [comment]
@viveksck my apologies I should have realized this earlier. There is a special issue with text renderers. There is an ambiguity because field names are specified as strings, which is of course also the input type for `text`. You can make this work but you have to be more explicit. This will work for you (I just verified to be sure):
```
obj.plot_text = obj.plot.text('x', 'y', text={"field":"text"}, 'angle', source=obj.textsource)
```
