### ISSUE TITLE
Need "tooltip manager" to mediate tooltip interactions

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1512]
It is possible that the hover tool may result in multiple inspections, either by hitting: 
- multiple data points for single renderer
- multiple data points across several renderers

Currently a tooltip will be created for every hit, and the tooltips may overlap visually. What is needed is a manager object that controls tooltip behavior for an entire plot. All tools that generate tooltips in the plot area could contribute their tooltip requests to this manager, which would i) limit the maximum number of visible tooltips at a given time, and ii) visually dodge all the active toolips, iii) present some sort of control on the plot to get an "expanded view" when there are otherwise too many tooltips to display.

**Comment by VelizarVESSELINOV** [comment]
:+1:

**Comment by philippjfr** [comment]
A slightly tangential comment, I noticed when profiling plotting a large numbers of points that rendering a bunch of stacked tooltips can become **really** slow. If I recall correctly it was doing a lot of reflowing when they were stacked causing things to freeze up slightly. So it would be good to somehow render them all at once and/or limit the number of tooltips that are shown, because beyond a certain number you can't read them anyway.

**Comment by mattpap** [comment]
This is likely due to tooltips being added one at a time. This is a trivial fix to do.

**Comment by mattpap** [comment]
In fact I fixed that inefficiency last time I worked on this issue, but that work wasn't finished/merged.

**Comment by VolkerH** [comment]
One additional issue is tooltips being clipped. An example is here:
![](https://raw.githubusercontent.com/VolkerH/my_hv_gallery/master/Mar-28-2018%2011-18-58.gif)
Maybe the layout manager for the tooltip could ensure that the tooltip appears below (for the rectangles near the top).

Also, the tooltip is partly transparent - I haven't found the CSS for this.

**Comment by VolkerH** [comment]
As mentioned on the bokeh gitter, I put together a small notebook to illustrate this
https://github.com/VolkerH/my_hv_gallery/blob/master/HoverToolClippingAndTransparencyExample.ipynb

**Comment by brcnblc** [comment]
About the issue [HoverTool() mode 'vline' produces double labels #8559](https://github.com/bokeh/bokeh/issues/8559)

The same exact data point triggers 2 times, on some arbitrary points. 
I suggest simply pooling the data points when a hit point is found for the renderer and checking if the pool if the newly found hit point is added before, in order to overcome the  double showing of same exact data point problem. Of course pool should be cleared on mouse move. Tool tip should be refreshed only when mouse is stable.

**Comment by pjvalla** [comment]
Has there been any update on this?  Simply limiting the number of tooltips would be a huge improvement.  I am working with a scatter plot.  Right now I have to scale the point size, but this can result in either not getting a tooltip or getting too many (resulting in a slow down mentioned by @philippjfr).  This method is a complete hack and not obviously scalable.

**Comment by bryevdv** [comment]
I am closing this in favor of the actual fleshed out proposal for a hit results filter hook in #9087
