### ISSUE TITLE
scatter plot demo with linked density histograms

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1593]
References: #1585

For reference, here are feature that would be nice to have eventually:

* on a single canvas (using kiwi layout)
* with `bokeh-server` but without polling
* without the `bokeh-server` (using a function interface)

But for now we can build this demo with simple grid/table layout and routing events through `bokeh-server` using polling (or in the notebook using `push_notebook`)

**Comment by bryevdv** [comment]
If you are too rushed to build things and try it, here is a video on the Bokeh YT channel:

https://www.youtube.com/watch?v=rdail7yaHU8&feature=youtu.be

**Comment by pzwang** [comment]
Two small issues:

1. If the first selection operation is performed while the shift key is held down, then an exception is raised on Line 97 in the main example source file.  This has something to do with `hhist2` and `vhist2` being lists and not numpy arrays.  Upon cursory debugging, simply doing an `np.asarray()` on them doesn't quite lead to the right behavior, because it looks like the histograms don't get updated... (I could be mistaken about this, however, since I didn't dig into it deeply.)

2. This example needs a better name than the uber-generic "selection_update".  Perhaps "Density histograms" or something suggestive like that..?

**Comment by bryevdv** [comment]
1) is a small bug I had a fix for at some point, but it got lost. Just need to initialize them with `np.zeros_like` instead of a comprehension. 

2) open to any suggestions on name...

putting this in a new issue, though :)
