### ISSUE TITLE
Streaming netcat example for bokeh CLI tool 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1596]
References: #1585 

Description from @pzwang : "piping netcat data into bokeh server or plot rendering in IPyNB output cell" 

This is predicated on ongoing bokeh CLI tool work but this is a concrete target to shoot for for 0.7.1 capability, if possible. Note that the CLI tool should automatically start a `bokeh-server` with memory backend if necessary.

**Comment by fpliger** [comment]
I'm pushing a streaming example that streams realtime data from netfonds to https://github.com/bokeh/bokeh/pull/1565. This is not optimal but is a starting point.

There are a few things that need more work to have it working nicely with an open chart on IPyNB. More specifically:

* charts behaviour when `notebook` and `server` arguments are both specified. I have opened issue #1621 for that 

* bokeh-server/charts default machinery does not behave as cli/notebook rendered chart would expect. This happens because if we create a new chart instance that points to the same bokeh-server plot (sharing the plot name on the server) then we'll have 2 stacked plots on the server instead of having the original plot attributes updated. 

In general this still need to be improved (on charts side?) to make it possible to have a notebook cell with a chart pointing to a server document that can be accessed by a cli instance streaming data from a source. So on the notebook side we'd have something like this:

```Python
from collections import OrderedDict
import pandas as pd
from bokeh.charts import TimeSeries

# Here is some code to read in some stock data from the Yahoo Finance API
AAPL = pd.read_csv(
    "http://ichart.yahoo.com/table.csv?s=AAPL&a=0&b=1&c=2000",
    parse_dates=['Date'])

xyvalues = OrderedDict(
    AAPL=AAPL['Adj Close'],
    Date=AAPL['Date'],
)

ts = TimeSeries(xyvalues, index='Date', title="Demo!", ylabel='Stock Prices', notebook=True, server='clistockdemo1')
ts.legend("top_left").show()
```

that then can be updated if user starts a new CLI instance with:

```Bash
$ bokeh-cli --title "Demo!" --series "bid" --plot_type "timeseries" --input "http://hopey.netfonds.no/posdump.php?date=20141231&paper=AAPL.O&csv_format=csv" --index time --output server://clistockdemo1 --sync_with_source t
```

@pzwang Is this any close to the original idea you had in mind?

@bryevdv @damianavila @hhuuggoo  Do you have opinions about that? Specially what concerns interactions with `bokeh-server`...

**Comment by fpliger** [comment]
As a side note... I think it'd be nice to have a something in charts to let users create a charts from data already present on `bokeh-server`. So, for instance, in the former notebook example there would no need to create an instance of TimeSeries with dummy data to sync with a `plot-server` document. We could just:

```Python

ts = TimeSeries.from_server('clistockdemo1')
ts.legend("top_left").notebook().show()
```
