### ISSUE TITLE
Testing particular bokehjs features using image-diff framework

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#1647]
Currently we use image-diff framework to test entire examples, which is obviously useful, but doesn't provide the finest granularity of tests. I would like to have all features exposed by the low-level API, tested individually and in reasonable combinations (up to some definition of reasonable, obviously we don't want to test all combinations, there are just too many features available). Running such tests will most likely be slow, so at minimum, we will have to run them in a separate travis-ci job or even on our own hardware (@bryevdv, what's the status of setting up jenkins infrastructure?).

Tasks:
- [ ] write tests ;)
- [ ] integrate image-diff with nose (or maybe include those tests in `example/test`)
- [ ] possibly remove some of glyph examples (which tried to imitate what's proposed here)

**Comment by bryevdv** [comment]
I held off on Jenkins due to both lack of personal time and also from not wanting to work on infrastructure that would be soon obsoleted by a Binstar setup. I had hoped the Binstar build would be up and running by now. It's not, but long term that is absolutely the plan. So, I would say the best path forward immediately is to take advantage of what we already have running. Hopefully it is not too difficult to nudge things a little to split off the image diff tests and put them in a separate TravisCI build .

Those subtasks above are pretty big, in particular we should discuss the sorts of image diff tests. Can you make separate issues and link them on each checkbox item?

**Comment by mattpap** [comment]
> Hopefully it is not too difficult to nudge things a little to split off the image diff tests and put them in a separate TravisCI build

That's simple.

> Can you make separate issues and link them on each checkbox item?

I will do it when I start working on this issue.

**Comment by bryevdv** [comment]
estimate: days 
status: some tests + integration should be ready for 0.8, if not all

**Comment by mattpap** [comment]
I didn't yet got back to this work, so most likely this will be finished after 0.8.

**Comment by mattpap** [comment]
I'm going ahead and close this issue, because it doesn't state a clear goal. This issue, as well as many other tests-related issues, should have been created with a set of basic tests in mind. Later this could have been improved with more specific issues. Additionally, some effort was put to actually address this issue and `examples/integration` was created. This isn't exactly what I had in mind here, but is close enough, especially given the available resources we have. Obviously more integration-like examples/tests are always welcome, but it's far better to do this with each PR.
