### ISSUE TITLE
explicit notebook display codes not working 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1659]
In `examples/glyphs/glyph.ipynb` the first two attempts to display the plot fail. They use:
```
from bokeh.utils import publish_display_data
from bokeh.embed import notebook_div
data = {'text/html': notebook_div(plot)}
publish_display_data(data)
```
and 
```
from IPython.core.display import HTML
from bokeh.embed import notebook_div
HTML(notebook_div(plot))
```
respectively. A third attempt that just evals `plot.html` works. The failed output partially renders:
![screen shot 2015-01-09 at 1 46 51 pm](https://cloud.githubusercontent.com/assets/1078448/5686128/fb8c0512-9805-11e4-9fa4-13815b585cde.png)
This was on OSX/safari with Bokeh approximately 0.7.1

**Comment by damianavila** [comment]
This is very weird issue:
It happens:

* if you `run all` the cells
* if you run manually enough fast to recreate the `run all` command
* if you `run all` with just one of the *methods*, they all work
* if you time sleep between the *methods*, the problem is fixed

If I tried the same with some arbitrary html, it is working as expected, so it seems to be something associated with us... it seems that the js is not completely loaded or "displayed" because the next cells take the stage... additionally, if you flip the last cells... always the last one is showed well... it is not the case that plot.html is working and the other ones don't.

One more thing... if I make three different plot objects and try to show them as we show just one, it works as expected... so the problem seems to be related to the fact that the three *methods* are consuming the same plot object...

OK, so far this is my evaluation of the problem... ideas welcome!
It is easy to fix on the surface just delaying each *method* call, but that fix does not go into the root of the problem...

Probably I could open an issue at the IPython repo to see if all the team has a better interpretation of the problem...

**Comment by damianavila** [comment]
ping @bryevdv

**Comment by bryevdv** [comment]
Were you able to solicit any ideas from the IPython devs? This is out of my expertise I don't really have any good ideas. I would say that perhaps there is a problem with the callbacks scheduling a plot render once bokehjs is loaded, but it is clearly rendering the parts that *does* render, correctly, so I don't think that is a problem. Maybe there is some problem in the notebook with shared data sources? Do tow plots with the same data source exhibit the same problem? Or is it really just the case of the same exact plot object. We'll have to open up the JS debugger and start digging pretty deep to get at this, I think.

**Comment by damianavila** [comment]
>Were you able to solicit any ideas from the IPython devs? 

Yes, I can ping the other guys to get some feedback...

>Maybe there is some problem in the notebook with shared data sources? Do two different plots with the same data source exhibit the same problem? 

I have to check that...

>Or is it really just the case of the same exact plot object. We'll have to open up the JS debugger and start digging pretty deep to get at this, I think.

Yes, I will try to dig further on this...

**Comment by bryevdv** [comment]
This is not specific to IPython: if you use `bokeh-plot::` with the same file twice in Sphinx docs, same problem occurs (issue with `autoload_static`?)
