### ISSUE TITLE
Bokeh axis label overlap

### ISSUE THREAD

**Issue by tr8dr** [bokeh/bokeh#1664]
I have a multi-figure Bokeh plot of vertically stacked & aligned figures. Because I want to align the plots vertically, the y-axis labels are rotated to be vertical rather than horizontal.

In certain scenarios, Bokeh **produces too many ticks / labels**, such that the tick labels overlap completely, making illegible. Here is an example:

```python
import bokeh.plotting as bp
import numpy as np

y = np.random.uniform(0, 300, 50)
x = np.arange(len(y))

bp.output_file("/tmp/test.html", "test")
plot = bp.figure(plot_width=800, plot_height=200)
plot.yaxis.axis_label_text_font_size = "12pt"
plot.yaxis.major_label_orientation = 'vertical'

plot.line (x,y)
bp.show(plot)
```
Perhaps could some heuristic on height or using the DOM to determine the expected cumulative render dimensions of the labels.  One or more of the following might be appropriate:
- [ ]  heuristic to determine # of labels for a given geometric dimension
- [ ]  a user-defined formatter where # of labels can be defined
- [ ]  a special formatter for small geometries that just has 3 labels (min, median, max)

Expediently, I would be interested in the last option, as would use often.  Is it possible to do any of these python-side today?

**Comment by bryevdv** [comment]
Hi @tr8dr, this is definitely sometimes a problem. Unfortunately the best advice I can give you at the moment is to consider rotating the labels. In addition to just being horizontal and vertical, it is possible to specify angles. This might be worth looking at?

A few comments:

It's possible to feed the measured label width back into the algorithm that chooses tick locations, it just has not been done yet. 

Additionally, letting the user specify a "hard value" for the number of ticks, that is always respected has also been requested by others, but it's not yet available either. 

Can you provide more context for the last case? I am not quite sure I understand, maybe you could attach a screenshot of a plot that shows the kind of labeling you want? I think you are asking about semantic re-labeling of numeric tick values, but I am not sure. This has also been discussed and is planned, but not available yet. 

The first simplest thing to implement is probably a "fixed" ticker that let's user specify the exact number of ticks they want.

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.

**Comment by bernd-wechner** [comment]
Landed here with similar concerns. Was wondering if Bokeh had some way of specifying "don't overlap labels". Meaning if the requested labels would overlap  back off the labels (draw only every second one, and a minor tick between). Simply because this best done internally (of the Bokeh library) because:

1. It's a very common need, and no need to reinvent the wheel on every site that experiences this desire.
2. It's closer to the bone (inside of Bokeh you know the  fonts used, can do whatever is possible to determine if the glyphs would overlap - inasmuch as HTML/JS make that possible - predicting overlap up front before drawing to the canvas).
