### ISSUE TITLE
Flip images when ranges are reversed

### ISSUE THREAD

**Issue by imaluengo** [bokeh/bokeh#1666]
Hello,

I'm new to Bokeh, and it might be that I'm using the library wrong, but in most of the image libraries the [0,0] pixel refers to the top left pixel of the image, while in Bokeh (I have not been able to change it) the [0,0] coordinate refers to the bottom left pixel of the image. This simple script to load and plot an image:

```
import bokeh.plotting as plt
from skimage.io import imread
lenna = imread('/tmp/lenna.png', flatten=True)
p = plt.figure(x_range=[0,10], y_range=[0,10])
p.image(image=[lenna], x=0, y=0, dw=10, dh=10, palette='Greys9')
plt.show(p)
```

Results with the image plotted upside down, as seen in the attached images (image is also converted to grayscale but this is not relevant):
![lenna](https://cloud.githubusercontent.com/assets/1993103/5695380/18867fe2-9998-11e4-88da-f246b8e22557.png)
![lennaplot](https://cloud.githubusercontent.com/assets/1993103/5695379/188639ce-9998-11e4-9f0e-b76b90e6e6b9.png)

I've tried reversing the range to `[10, 0]` but this results in displacing the image, not fliping the y axis. The only way I've found to plotting it right is by flipping the numpy array `lenna[::-1]` before sending it to plot (but I guess it should be a better way).

Is there a way of doing it? Is it a bug? Or am I using the library wrong?

Thank you

**Comment by bryevdv** [comment]
@imaluengo this can probably be considered a bug, and for the time being your workaround is probably the best option. Note however, that when people construct a "mathematical" image (i.e., derived from some function, where the individual pixels also have meaningful "data space" coordinates) then it typically makes more sense to refer to a lower-left origin. I'm not sure what the best solution to this tension between the different use-cases is, perhaps this should just be a configurable property of the image renderer.

**Comment by imaluengo** [comment]
@bryevdv I understand the difference mathematical images, in fact the mandelbrot example in the gallery uses the lower left pixel as `[0,0]` which as you say, makes more sense.

I've used matplotlib before and I've never wondered about this before because in matplotlib the default origin is the top left pixel (my case use). Searching a bit I found that as you suggest they also use a keyword `origin=` in the call to `imshow` to change between the two options:

http://stackoverflow.com/questions/8396101/invert-image-displayed-by-imshow-in-matplotlib

PS: I thought that it would be useful to see how other libraries behave in order to decide the workaround.

**Comment by jakirkham** [comment]
If it is any reassurance @imaluengo, you are not the only person to wonder this ( http://stackoverflow.com/questions/28195181/bokeh-image-glyph-displays-image-upside-down ) and I would agree with you.

I also like the `origin` solution you suggest here. However, IMHO the default should remain identical to current behavior because of backwards compatibility and the image case is a deviation from the mathematical image, but this will require good documentation as people will be confused.

**Comment by bryevdv** [comment]
Changing this to `task` instead of `bug`, I think the best plan is to add an option e.g. `origin` but to keep the current default behaviour (too late to change now)

**Comment by bryevdv** [comment]
Unfortunately need to get out a release with the tornado fix this week, so this will have to slip to the next milestone.

**Comment by SmallTK** [comment]
I solved the problem temporary 
```
import numpy as np
import PIL.Image

lena_img = PIL.Image.open('lena.png')
width_pixel,height_pixel = 512, 512
size_new = (width_pixel,height_pixel)
lena_img = lena_img.resize(size_new).convert('RGBA')
a = np.array(lena_img)

# stack each tuple (R,G,B,A) to a UINT32,then reshape to (width,height)
img = a.view(dtype=np.uint32).reshape(a.shape[:-1])

# reverse y axis manualy
img = img[::-1]
...

# enjoy
plot.image_rgba(image=[img], x=0, y=0, dw=width_pixel, dh=height_pixel)

**Comment by Imperssonator** [comment]
I'd just like to +1 this issue because it's still a problem in 12.10.

image_url displays images properly, which makes it even more frustrating that image_rgba does not invert the y axis.

To me, any command that is specifically for displaying images should have an inverted y by default. I understand the argument that "mathematical" images don't necessarily want an inverted y, but isn't that what the straight "image" method is for (i.e. taking a scalar array and converting it to an image)? If somebody has gone to the trouble of creating an image array with rgba channels, one would think they designed it to be saved correctly as an image file as well.

Anyway, I would be in support of the proposed keyword fix, but instead of `origin` I would just call it `invert_y` with a default of `false`. `origin` implies translation, not inversion or flipping.

**Comment by Imperssonator** [comment]
I'm going to +1 this because it's still an issue in 12.10.

I would propose adding an option `invert_y` with a default of `false`, which would ensure backwards compatibility. `origin` implies translation, not inversion of any axes.

**Comment by imaluengo** [comment]
Following @Imperssonator, a more general `invert_axis` might be useful in the future. Accepting values like:

    invert_axis=None (default)
    invert_axis=0        # or 'y'
    invert_axis=1        # or 'x'
    invert_axis=(0, 1)  # or ('y', 'x') or 'both'

That would allow to invert both, 'y' and 'x' axis. Who knows. someone might want / find useful to invert the 'x' axis too.

**Comment by Maurau** [comment]
Using flip from numpy also works

`import bokeh.plotting as plt
from skimage.io import imread
from numpy import flip
lenna = imread('/tmp/lenna.png', flatten=True)
flip(lenna,-1)
p = plt.figure(x_range=[0,10], y_range=[0,10])
p.image(image=[flip(lenna,0)], x=0, y=0, dw=10, dh=10, palette='Greys9')
plt.show(p)`

**Comment by Maurau** [comment]
Using flip from numpy also works :

``` python
import bokeh.plotting as plt
from skimage.io import imread
from numpy import flip
lenna = imread('/tmp/lenna.png', flatten=True)
flip(lenna,-1)
p = plt.figure(x_range=[0,10], y_range=[0,10])
p.image(image=[flip(lenna,0)], x=0, y=0, dw=10, dh=10, palette='Greys9')
plt.show(p)
```

**Comment by kammeyer** [comment]
This is confusing to me, as I think of an image as being a function of X and Y, that has defined values on a lattice.  Now the image may be defined on the range say, [0,0] to [512, 1024].  If I set the y axis range to be [1024,0], 0 is the point on the upper left, and 1024 is the lower left.  If I plot lines on these axes, everything works fine.  If I plot an image on this axis, it doesn't work, so to me this is a straightforward bug rather than a different way of looking at the data.  Origin, dw and dh define the mapping between image coordinates and data space, and the plot ranges should define the mapping between data space and screen space.

**Comment by kammeyer** [comment]
So part of this is perhaps I'm not familiar enough with some of the concepts behind Bokeh.  I understand that images are plotted as Glyphs, but when I think of a Glyph, I'm thinking of something like a little X or O to denote a datapoint.  Typically these would have a position in data space, but not an extent in data space.  I think of each pixel in an image plot as being like a scatter point that uses a square as its glyph.  Each pixel has a particular position in data space.

If I'm actually using images as scatter markers for examples (as glyphs), I normally don't want the glyph to flip based on the plot range.  For example, maybe my glyph is an image of a letter, and we're plotting a well log in units of depth.  I don't want the letter to flip upside down just because I happen to be plotting on a reversed axis.  On the other hand, if I'm doing an image plot of the well log of say, depth vs. angle in the well bore or something, I do need the image flipped.  I would also like to be able to do things like have an index on the image that is not necessarily uniform -- maybe I don't sample at every depth evenly.

I understand that this sort of case causes the normal performance optimizations for the web to fail, because you're just trying to splat an image somewhere on the canvas, scaled appropriately, but I think that the optimization may lead to not thinking about pixels as having a position in data space like scatter points or points on a line.

**Comment by bryevdv** [comment]
> I think of each pixel in an image plot as being like a scatter point that uses a square as its glyph. Each pixel has a particular position in data space.

That's an OK mental model, assuming we implement things necessary to make it "true" but that's not currently the case. 

> If I'm actually using images as scatter markers for example (as glyphs), I normally don't want the glyph to flip based on the plot range

Well I guess that's points to making the auto-fiipping configurable as well. But unless I am misunderstanding, not flipping is not consistent with the mental model above? If every pixel of an image has its own position, then flipping the range implies that the image *would* flip.

 Wanting to use images as scatter markers implies anchoring at the center and never flipping (but allowing a rotation, like other scatter markers). I'm not sure but that's maybe best handled by a completely separate marker that makes it clear that it behaves like e.g. circle, or X  or triangle scatter markers. 

> I would also like to be able to do things like have an index on the image that is not necessarily uniform -- maybe I don't sample at every depth evenly.

I think you are going to be drawing your own pixels (i.e. with rects or quads) at this point. 

A tangentially related issue is to support displaying standard image formats like PNG directly. 

There are obviously and evidently quite a few use cases and scenarios for images, and different ways that different people would like them to behave. I suppose it would ideally be the case that someone bite the bullet and try to enumerate these different cases and make a concrete an detailed proposal. That just is not going to be me at the moment.

**Comment by kammeyer** [comment]
I agree with all of this.  What I interpret as the impedance mismatch is that if an image is treated as a glyph with an origin, it only aligns its pixels to data space axes by a sort of engineered coincidence.  The use case where an image is used as a glyph for e.g. a scatter marker is fundamentally different than the case where the image itself is a plot that is associated with two axes.  

Things like setting an origin and extent IMO should be handled by setting an x_index and y_index on the image.  The reason I brought up the nonlinear axes was not that these situations were all that common, but it puts one in the right frame of mind about thinking about the pixels living on axes like a normal plot.  In the general case, where the x_index and y_index are not a linspace, you can't just blit the image and have it work  The system can ensure that the x_index and y_index are a linspace before it uses the blitting approach to rendering the plot, and certainly you could even simply error out until someone wants to implement non linspace image indices.  I do think it would be valuable to have a place in the design of the system that doing something like this fits, whether it's actually implemented or not though.

**Comment by markroxor** [comment]
Flip the image first using `lenna = np.flipud(lenna)`

**Comment by kammeyer** [comment]
This works to get the image to display correctly, but now the indices in in the array that contains the image are not the coordinates of the plot.  For example, suppose you're doing feature extraction from an image and you want to plot scatter markers on top of an image, or you're doing object detection and you want to plot bounding boxes on top of an image.  Now nothing lines up.  The problem as I see it is that the case of using an image as a glyph is fundamentally not the same as using an image as a set of sample points that are plotted on an axis, like a scatter or line plot.  Bokeh doesn't have the second concept yet.

**Comment by kfpotts1** [comment]
@kammeyer This is the issue I'm encountering in my use case. If I want to add any sort of figures or glyphs on the image (rectangles for example) after using np.flipud(img_array), I have to also convert the coordinates for each additional figure, which is not ideal. Ideally something equivalent to changing the origin would be great. Then I would not have to flip the image, nor convert coordinates for additional figures.
