### ISSUE TITLE
bokeh-server not working in 0.7.1 - bad path?

### ISSUE THREAD

**Issue by twoscomplement** [bokeh/bokeh#1711]
I upgraded to 0.7.1 and bokeh-server --dev stopped showing/updating when plots were added. 0.7.0 worked.

These warnings were appearing in bokeh-server output:

2015-01-14 22:49:15,762:WARNING:tornado.access:404 GET /bokehjs/static/css/bokeh.css (127.0.0.1) 1.64ms
2015-01-14 22:49:15,764:WARNING:tornado.access:404 GET /bokehjs/static/js/vendor/requirejs/require.js (127.0.0.1) 1.02ms
2015-01-14 22:49:15,765:WARNING:tornado.access:404 GET /bokehjs/static/js/config.js (127.0.0.1) 0.93ms

Poking around, I found that those files were accessible at /bokeh/ (rather than /bokehjs/). I changed references to /bokehjs/ to /bokeh/ in the installed package and the page is working as expected again.

**Comment by damianavila** [comment]
When you said you upgraded... are you saying you are using 0.7.1 from that specific tag at git?
The `--dev` parameter essentially set up the bokeh server to serve BokehJS files from the bokehjs build directory in the source tree and to serve individual JS files instead of compiled bokeh.js, and it will not work with the packaged Bokeh...

**Comment by twoscomplement** [comment]
I had installed and upgraded bokeh using pip.

**Comment by bryevdv** [comment]
It's possible this was accidentally working before and something accidentally broke it. Maybe we can restore it. I do think long term it would be better to ship the split out js and coffee in separate bokeh-server-dev pkg or something, do as to not inflate the package size more for normal users.

**Comment by damianavila** [comment]
> I do think long term it would be better to ship the split out js and coffee in separate bokeh-server-dev pkg or something, do as to not inflate the package size more for normal users.

And what's the use case? Because if you need to do dev work it is better to deal with the source directly.... but maybe I am missing some important use case...

**Comment by bryevdv** [comment]
Important, probably not, but people want all sorts of things (as this issue demonstrates).However it is true  "--dev" mode does other useful things like starting up in memory backend with some desirable logging policies, this has nothing to do with bokehjs or even bokeh dev. It could be useful to anyone integrating `bokeh-server` with their own web app. That said my main point was that we should remove the files so that the release package is smaller .

**Comment by twoscomplement** [comment]
For the record, I'm using --dev as part of a fast/easy iteration setup: I make changes to my python code, save the file, and can see the plot update in a browser window without requiring further input (I use inotifywait as glue - it seems likely that there are simpler ways to achieve the same end...)

**Comment by damianavila** [comment]
>That said my main point was that we should remove the files so that the release package is smaller .

I agree... removing probably get us a half size package...

>For the record, I'm using --dev as part of a fast/easy iteration setup: I make changes to my python code, save the file, and can see the plot update in a browser window without requiring further input (I use inotifywait as glue - it seems likely that there are simpler ways to achieve the same end...)

thanks for pointing out your use case...
