### ISSUE TITLE
Being able to hide the axis

### ISSUE THREAD

**Issue by matdrapeau** [bokeh/bokeh#1730]
The would be nice to have a way to hide a plot axis if desired.

**Comment by matdrapeau** [comment]
I could start looking on this, but honestly, I have no clues how to handle dev for the coffeescript / js part. Is there any doc or post that could help me there?
thanks

**Comment by bryevdv** [comment]
Hi @matdrapeau that would be awesome! You can find our developer's guide here: 

http://bokeh.pydata.org/en/latest/docs/dev_guide.html  

That has information about setting up a dev environment and building BokehJS from the coffeescript sources. That is the main hurdle. Then, the easiest way to run/rebuild for testing is to just do:
```
% python setup.py develop --build_js
``` 
Note that it's also possible to get a faster "incremental compilation" workflow going but let's start with the simplest thing. Then, I think we could add a `hide` flag to all renderers. In the python here:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/renderers.py#L11

and there in the JS in places like here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/renderer/guide/axis.coffee#L166

check `@mget('hide')` and if it is `true`, just return without drawing. 

Now, this is a little less than ideal because currently you would have to add this check to every `render` in lots of places. @mattpap do you have any suggestions?

**Comment by matdrapeau** [comment]
@bryevdv what about doing the lookup there and not adding the renderer on the pile? https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/common/plot.coffee#L353

Also, I am pretty new to coffeescript, is there an easy way to use some sort of debugger (a la python pdb by example) or what is your typical dev setup for coffeescript and its introspection?

thanks

**Comment by bryevdv** [comment]
@matdrapeau All of the major browsers have "developer tools" I typically use Safari (you have to turn on the develop menu in preferences first). But Chrome has a nice debugger and Firefox has Firebug which is also nice. I am not sure I'd do a great job explaining things but here are a few links that might be helpful:

https://developer.apple.com/library/safari/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/Introduction/Introduction.html
https://developer.chrome.com/devtools
https://developer.mozilla.org/en-US/docs/Tools

One of the simplest ways to set breakpoints is just to add the line `debugger` into the source and re-compile, then open the page with dev tools open. The debugger will pause at the line you put the `debugger` command and then you can inspect state, etc. It's also possible to set breakpoints, etc. using the dev tools GUIs but I'll refer you to the docs above for that. 

Regarding the idea to not put them into `renderers` that is definitely one approach. The issue is that if `hide` changes back, you'd need to keep track of it and put t back in in the right place. I think it might be easier to try and keep everything inside the renderer itself. For axis, also try putting some logic here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/renderer/guide/axis.coffee#L355

if `@get('hide')` is `true` return 0 instead of the computed value. I think that will solve this issue. Also let's start just adding `hide` as an attribute to `Axis` and worry about making it more general later.

**Comment by bryevdv** [comment]
Also, thanks again for looking into this!!

**Comment by matdrapeau** [comment]
@bryevdv I am aware of browser dev tools for js... was wondering how to hook that up directly into the coffeescript sources.

thanks

**Comment by bryevdv** [comment]
Ah ok sorry, yes the simplest thing to do is to put a `debugger` command int the coffeescript sources and then re-compile. (Either with `python setup.py develop --build_js` or by getting the "incremental compilation" setup working)

**Comment by matdrapeau** [comment]
@bryevdv well, I did tried what you said about adding "debugger" at several places into the coffeescript files but nothing is happening in the browser when I run a chart example.
It looks that I need to bind the browser with the "source maps" directly to the coffeescript files, have you already done that?

Also, about returning '0' or nothing, there isn't any differences in the rendered chart axis.

**Comment by bryevdv** [comment]
Have you pushed the code into the PR? If you do that I can try it out, and that might help me formulate a better suggestion. I'm not sure what has to be done to make the source maps work, they have always just worked. @mattpap doe have any suggestions?

**Comment by matdrapeau** [comment]
@bryevdv just pushed...

**Comment by mattpap** [comment]
@matdrapeau, you don't need source maps for debugging. I personally don't use source maps when working with coffeescript (thought, in general, source maps are awesome).

**Comment by matdrapeau** [comment]
@mattpap: When looking into the Gruntfile.coffee it seems that the compilation of coffee script files are compiled with source maps already...

So in order to verify I am not missing any steps, I did added ```debugger``` into the axis.coffee file right after the declaration of the ```render: () ->```.
Then, I compile the coffeescript files using:
```% python setup.py develop --build_js```
Then executing this example:
```% python examples/charts/area.py```
I would expect my browser to open the js debugger before displaying the axis but full image is displayed without any dev tool being opened.
Is it what you also do on your side?

**Comment by bryevdv** [comment]
@matdrapeau ah very sorry, no `debugger` is ignored unless you have already opened the dev tools yourself. So just open them up and reload the page and it should trip on the `debugger` line

**Comment by matdrapeau** [comment]
@bryevdv I am very perplexed... reloading the page with dev tool opened doesn't do much. I am looking at the source of the js code into the file and I don't seen any "debugger" statement too.

**Comment by bryevdv** [comment]
Is it possible you have both a pip or conda install directory in your `site-packages`, as well as a `bokeh.pth` in `site-packages`?

**Comment by matdrapeau** [comment]
@bryevdv only have a bokeh.pth... and the "hide" feature is working as expected. When I build the package, I do see coffee compiling the axis.js file
Did tried with chrome and firefox, none of them are raising the debugger.

**Comment by bryevdv** [comment]
I am afraid I am at a loss.Can you make sure to disable and empty all caches? Sometimes this is an issue as well. Here is more info: http://bokeh.pydata.org/en/latest/docs/dev_guide.html#browser-caching  If this does not solve,  maybe we can have a Google Hangout during the coming week to try and figure out what is going on?

**Comment by matdrapeau** [comment]
@bryevdv browser cache has never been activated.
Gimme a shout on hangout at the same username @ gmail whenever you can.
Thanks a lot

**Comment by matdrapeau** [comment]
@bryevdv I have some time today and tomorrow if you want to go over this issue.
thanks :)

**Comment by bryevdv** [comment]
Hi @matdrapeau tomorrow might work, sorry I am getting slammed this week.

**Comment by matdrapeau** [comment]
@bryevdv would you have some time today?
thanks

**Comment by bryevdv** [comment]
I could spend about 15 minutes at 2pm CST.

**Comment by matdrapeau** [comment]
ok great... just ping me

**Comment by bryevdv** [comment]
Very sorry I missed you I got pulled into a discussion. Tried to msg later but you had logged off.

**Comment by matdrapeau** [comment]
did you added me? I did got any request

**Comment by matdrapeau** [comment]
Finally, the problem was I didn't set this env variable:
BOKEH_MINIFIED=no
the minifying process don't allow source maps to work either.

**Comment by bryevdv** [comment]
The PR is still open?

**Comment by bryevdv** [comment]
If you don't have the bandwidth to work on it  more, I understand, but in any case we need to add this feature.

**Comment by matdrapeau** [comment]
oups... sorry, I hit the wrong button!
I am working on the PR now

**Comment by damianavila** [comment]
Thanks for your work on this @matdrapeau

**Comment by matdrapeau** [comment]
@bryevdv can we close that issue?

**Comment by bryevdv** [comment]
@matdrapeau which issue? this one is closed with the PR merge are you referring to a different one?
