### ISSUE TITLE
Add a dark theme a la Kibana's default

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#1737]
These colors look nice: http://www.elasticsearch.org/overview/kibana/

**Comment by JohnLunzer** [comment]
Poke, poke.

Has this been done? I would like to use Bokeh but would like to get it to go into a "dark" mode. It's not entirely clear that this is possible based on the documentation, there seems to be multiple tens of settings that need to be modified. Can the current "themes" module achieve this simply?

I should note, this feature isn't purely aesthetic, there are legitimate accessibility considerations here for developing graphs for specific types of visual impairment.

**Comment by JohnLunzer** [comment]
After some digging I found this [example](https://github.com/bokeh/bokeh/blob/master/examples/embed/embed_themed.py), which will accomplish a **complete** "dark" theme.

An **incomplete** "dark" theme can achieved more simply via:
```python
curdoc().theme = Theme(json=read_yaml("theme.yaml"))
```
Why incomplete? Because the HTML background style is not affected and thus will remain white, not matching the plot.

I'm struck by how much boilerplate is needed to affect the CSS style of the underlying HTML.

Is there an easier way to adjust the CSS Style? Rather than having to use a Jinja template?

**Comment by bryevdv** [comment]
@JohnLunzer I'd say most use cases involve embedding bokeh plots into larger pages, so the styling options are more geared towards affording the ability to "match surroundings" than anything else. In the context of embedding, Bokeh has no control over the overall page HTML and CSS, so the boilerplate in that example is more symbolic of "this is the HTML and CSS I'm starting with already" and then the theming is "how do I embed Bokeh in a way that matches that". 

If you want your already existing CSS to apply to Bokeh DOM elements, you can use the `css_classes` property:

https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/css_classes.py

but note that the actual plotting happens on an HTML canvas, to which CSS does not apply at all. That (the canvas portion) is really the part that `Theme` applies to.

**Comment by bryevdv** [comment]
going to link this to #99 and and let that issue cover both.
