### ISSUE TITLE
VBox/HBox should accept single list as well

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#1786]
Seen in the wild:
```
# `foo` is a dict with Plots as values
VBox(foo.values())
```

Need checks in these two places:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/widgets/layouts.py#L31
https://github.com/bokeh/bokeh/blob/master/bokeh/models/widgets/layouts.py#L48

to check if `len(args)==1` and if `args[0]` is a sequence (list, tuple, etc), then set `kwargs["children"] = args`

Edit: docstrings should also be updated to reflect the different ways to initialize the `children`.

**Comment by almarklein** [comment]
Working on it now.

I made a superclass ``BaseBox`` that `VBox` and `HBox` inherit from, so that the code for the children property and the `__init__` does not have to be duplicated. Is this ok? Not sure what the effect this has on the client-side or doc generation.

Also, I assume there are plans for other layouts that work in different ways, which is why children and the `__init__` were not defined on the `Layout` class?

**Comment by bryevdv** [comment]
I'm not aware of any specific plans, but that seems reasonable. :) Off the cuff, a `Grid` layout would probably be useful. `BaseBox` is fine, it should just be documented like all the other models and it will automatically show up in the Sphinx reference guide. It has no effect on the client side, what matters is the actual type (and view mode type, really) at serialization time. Serialize a `VBox` in python, get a `VBox` in the client. There are often identical hierarchies on both sides, but this is not required (i.e., no requirement for a `BaseBox` on the client side, too)
