### ISSUE TITLE
Make automated plotting of pandas easier, I need some help!

### ISSUE THREAD

**Issue by vitiral** [bokeh/bokeh#1790]
Hey all,

Check out my pull request:  https://github.com/bokeh/bokeh/pull/1789

For now, it is just an ipython notebook to demonstrate functionality and my thought process.

I'm making a lot of progress with an automated plot of pandas dataframes. At the very least, this should go in the examples folder but I am hopping to create a charts.dataframe function (or something)

I am having some minor issues trying to get the axis from a figure, `f`
```
ya = f.yaxis[0]
ya.bounds = 0, 1000
show(f)
```
![output](http://i.imgur.com/9S6g9Cn.png)

As you can see, it doesn't scale the whole axis.

I need to be able to dynamically scale these axis. What is the best way to do this **after I have already created a figure**

Some other (more minor) issues:
- I'm finding it very difficult to change things once they have been created for pretty much any object. For instance, how do I change a line's color after I have created it? something like: `line = f.line(x,y); line.line_color='red'` Is this possible? Is there a document that overviews the machinery of these internals?
- your `brewer` object only supports up to 14 colors. Is there an object that brews more?
- please tell me if anything like this has been done before. I looked everywhere and couldn't find anything. (except for [this issue](https://github.com/pydata/pandas/issues/6962) where you want better mpl compatibility before you proceed? In my opinion, *pandas* doesn't exploit the full ability of it's plotting. You should take advantage of it!)

**Comment by cloudformdesign** [comment]
By the way, on the whole, I found found working with bokeh *significantly* easier compared with working with matplotlib. You guys have a fantastic library here, and I want to continue to support it in whatever ways I can. The web support is why I came, but I am definitely staying :D

**Comment by bryevdv** [comment]
Thanks of of the kind words and the contribution, @cloudformdesign ! A few quick thoughts:

* `line = f.line(x,y); line.line_color='red'; show(f)` should be fine are you saying this does not work?
* the brewer colormaps are all the existing "colorbrewer" colormaps scraped from the color brewer site, they aren't auto-generated or anything like that
* The reason the MPL compat would be nice is because then bokeh could be used with exisitng code basically as a drop-in replacement.  But I am not opposed to provided better interfaces that use Bokeh more fully on top. Perhaps some day Pandas will adopt them. 
* `bounds` tells the axis "only render between 0 and 1000", regardless of what the plot's current range is. It doesn't scale anything, it just restricts where the axis does get drawn. You probably want to set `y_range` on the plot.

**Comment by cloudformdesign** [comment]
## Line color (Error)
```
f = figure()
line = f.line(x, gdata)
line.line_color = 'purple'
show(f)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-294-9c991e67d40a> in <module>()
      1 f = figure()
      2 line = f.line(x, gdata)
----> 3 line.line_color = 'purple'
      4 show(f)

/usr/local/lib/python3.4/site-packages/bokeh/properties.py in __setattr__(self, name, value)
    548 
    549             raise AttributeError("unexpected attribute '%s' to %s, %s attributes are %s" %
--> 550                 (name, self.__class__.__name__, text, nice_join(matches)))
    551 
    552     def clone(self):

AttributeError: unexpected attribute 'line_color' to Figure, similar attributes are outline_line_color or title_text_color
```
## Colormaps
I saw that they were just a dictionary in the source code. Do you have something that dynamically generates colors? How do you do it "automatically"?

On this note, now do I access color? I guess this is related to the above issue...

## Data Ranges (got it)
```
from bokeh.models import Range1d
dr = Range1d(start=0, end=1000)
f.y_range = dr
show(f)
```

**Comment by bryevdv** [comment]
`line_color` is a property of the glyph, not of the figure. I thought `f.line` returned the glyph, but apparently it returns the figure. There are a few options, probably the easiest, if you want to change a glyphs properties afterwards, is to supply a "name" for it:
```
f.line(..., name="foo")
```
then later you can query for it:
```
glyph = f.select(dict(name="foo"))
glyph.line_color = "purple"
```

**Comment by cloudformdesign** [comment]
Thanks! This is what I needed for now.

My guess is that that is from the old style when you called just `line` instead of `f.line`. Do you think you will change `f.line` to return the glyph in the future

**Comment by bryevdv** [comment]
Off the cuff answer, probably not. We are trying to be averse to breaking changes unless truly necessary and I don't think this would qualify as that. Also the current setup allows chaining `p.line(...).circle(...)` which might be nice, arguably not that important either.

**Comment by cloudformdesign** [comment]
I'm having issues setting the y range name of the standard axis:

```
fig.y_range.name = 'std'
fig.extra_y_ranges = {"small": Range1d(start=small_min, end=small_max)}
fig.add_layout(LinearAxis(y_range_name="small", axis_line_color='blue'), 'right')
...
fig.line(x, y, y_range_name='std')
```
This is causing the graph to look like this:
![no graph](http://i.imgur.com/JiqbbRO.png)

In other words, nothing is plotting

**Comment by bryevdv** [comment]
Have opened issue regarding returning glyph renderers: https://github.com/bokeh/bokeh/issues/2829

Otherwise, no input in nine months, so closing.

**Comment by VelizarVESSELINOV** [comment]
Adding several line() the default color is constant which is unexpected, matplotlib and the others are proposing automatic "smart" color like Tableau20 from Palettable. This part of the issue that was listed here: is it fixed or you have another ticket for this issue?

**Comment by bryevdv** [comment]
@VelizarVESSELINOV the `bokeh.charts` API does automatically do color cycling. The `bokeh.plotting` API does not currently. I think color cycling could be nice but we'd need to figure out a way to "spell" things so that i) users still have complete explicit control ii) backwards compatibility is maintained. A few ideas:
```
p.line(..., color=cycle())          # cycle a default palette
p.line(..., color=cycle("veridian") # cycle a specified palette
```
Another possibility might be some kind of global state on `bokeh.plotting`:
```
bokeh.plotting.color_cycle = "veridian"
```
This is really covered by #2201, I will copy the above to that issue, and we can continue the discussion there. It would be helpful to get your input on a good way to specify this.
