### ISSUE TITLE
Add support for x, y args on charts 

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#1841]
Proposal is to add x, y arguments to charts in order to specify data series names when input is DataFrame (or mapping in general?) with the intention to make it easier for users to understand how use/build charts from mapped data series.

First examples to support:

``` Python
Bar(campaign, x='Visits', y='Google Tracking Code', title="Email Campaign Results", stacked=True, notebook=True).show()
```

and

``` Python
Bar(campaign, x='Visits', y=['a', 'b', ....'z'], title="Email Campaign Results", stacked=True, notebook=True).show()
```

This follows up discussions at #886

**Comment by damianavila** [comment]
As I said in the previous issue :+1: for this...

**Comment by pzwang** [comment]
I haven't been following the discussion but I think I'm seeing the issues, and they touch on some of the discussions we had over a year ago about how to specify data pivoting / faceting etc.  Since this is such a user-facing area of the API, I would like to be very thoughtful about it try our hardest to "get it right" the first time, and not have to break everyone's code (especially beginners' scripts!).

Regarding specific points:

1. @fpliger We can provide more information to the Barplot about how to treat the `y` variable (or the `x` variable, really) by using a slightly different keyword argument like `ycols` or `ynames` to indicate that the list is a list of column names, or conversely we can use `yvalues` to indicate that we're providing a list of literal values.  Alternatively, we can have some top-level symbols like "Index" or something like that and wrap the list in that, but that seems less user-friendly and more likely to collide with other names in the namespace.

2. When it comes to faceting/stacking/etc. "stack" is really only one kind of faceting operation; one can think about rendering faceted VBox or HBox of plots instead of stacking them together in a single plot, and none of the other plot parameters would need to change.  We should think about having top-level primitives for these visual correlates or representations of categorical nesting/pivoting/etc., rather than merely supplying them as part of the kwargs.  That being said, there is a visual hierarchy to these, and only some permutations make sense: so, one can imagine tabs of HBox/VBox of plots, each of which is a stacked-bar or stacked-area plot, but it's a nonsensical operation to "stack" a set of "tabs".

If some of this is unclear, maybe @bryevdv @fpliger we can chat about this today via voice?  (Not necessarily during the weekly bokeh dev call.)

**Comment by fpliger** [comment]
> I haven't been following the discussion but I think I'm seeing the issues, and they touch on some of the discussions we had over a year ago about how to specify data pivoting / faceting etc. Since this is such a user-facing area of the API, I would like to be very thoughtful about it try our hardest to "get it right" the first time, and not have to break everyone's code (especially beginners' scripts!).

Totally agree.

> @fpliger We can provide more information to the Barplot about how to treat the y variable (or the x variable, really) by using a slightly different keyword argument like ycols or ynames to indicate that the list is a list of column names, or conversely we can use yvalues to indicate that we're providing a list of literal values. Alternatively, we can have some top-level symbols like "Index" or something like that and wrap the list in that, but that seems less user-friendly and more likely to collide with other names in the namespace.

Yes, I really think that naming has a big role in the success of such addition. We also need to think if we want to support this only for DataFrames or also 2d mappings in general.


> When it comes to faceting/stacking/etc. "stack" is really only one kind of faceting operation; one can think about rendering faceted VBox or HBox of plots instead of stacking them together in a single plot, and none of the other plot parameters would need to change. We should think about having top-level primitives for these visual correlates or representations of categorical nesting/pivoting/etc., rather than merely supplying them as part of the kwargs. That being said, there is a visual hierarchy to these, and only some permutations make sense: so, one can imagine tabs of HBox/VBox of plots, each of which is a stacked-bar or stacked-area plot, but it's a nonsensical operation to "stack" a set of "tabs".

I've been thinking about this a lot during the big charts refactoring... IMO the options of different representations are many.. I think we should try to "implicitly" support the most obvious ones (like `stacking` and probably `faceting` but I see more advantages in giving the user explicit tools they can use to build their "custom" composition). So basically going more in the direction of the discussions in #1811

**Comment by bryevdv** [comment]
I am available to talk about this today, but @fpliger is sick, so perhaps later this week.

**Comment by iyneedham** [comment]
I hope you all don’t mind me chiming in, as I put in the original request. 

@pzwang, your suggestion in 1. about using different keyword arguments with x and y makes perfect sense.

Re: 2., it might also be worth considering faceting by both axes the way matplotlib and ggplot2 (in R) do:

http://nbviewer.ipython.org/github/ChrisBeaumont/mplfacet/blob/master/guide.ipynb
http://www.cookbook-r.com/Graphs/Facets_(ggplot2)/

Implementing faceting by both axes is probably more than you want to do in 0.9. But following on @pwang's point about getting it right & not breaking users' code in the future, while working on 0.8, perhaps you could come up with an easy-to-read syntax that could accommodate faceting by 1 axis now and 2 axes in a future version.

**Comment by fpliger** [comment]
> Re: 2., it might also be worth considering faceting by both axes the way matplotlib and ggplot2 (in R) do

@iyneedham something like this: http://bokeh.pydata.org/en/latest/docs/server_gallery/crossfilter_server.html

:-)

**Comment by fpliger** [comment]
Sorry for following up so late on this, the last weeks were quite hectic..

FWIW I'd follow @pzwang suggestion and use `xnames` and `ynames` to specify names of the series as a way to select those to be used to x, y coordinates. In this case `xnames` and `ynames` must be either a scalar or lists (where len(xnames)==1 or len(xnames)==len(ynames)). In case len(xnames)==len(ynames)==N, should we create N axis?

There's are a few things in that scenario that clashes a bit with the current implementation:

* we have some charts now that support `index` argument. Should we just rename it to `xnames`?
* Scatter is the the chart that have the most `custom` input type as it expects 2d iterables with (x,y) tuples as elements. Should we keep this type support, replace it with the `xnames`/`ynames` signature or support both?

@pzwang @bryevdv @bokeh/dev how that sounds?

**Comment by damianavila** [comment]
>we have some charts now that support index argument. Should we just rename it to xnames?

mmm... not sure about this one...

>Scatter is the the chart that have the most custom input type as it expects 2d iterables with (x,y) tuples as elements. Should we keep this type support, replace it with the xnames/ynames signature or support both?

Probably we need to make things simple and just support the xnames/ynames signature as in the other charts... the 2d iterable seemed the right signature when I wrote it, but it is not consistent with the other charts implementation right now...

**Comment by fpliger** [comment]
>>we have some charts now that support index argument. Should we just rename it to xnames?

>mmm... not sure about this one...

Yes.. I see drawbacks on both renaming it or adding `xnames` and keep support on for index (this would be confusing IMO).

> Probably we need to make things simple and just support the xnames/ynames signature as in the other charts... the 2d iterable seemed the right signature when I wrote it, but it is not consistent with the other charts implementation right now...

Yes. I know we did discuss this in #1373 but I think we now have more insight to pick the best interface (considering if and how to break previous versions compatibility)

**Comment by almarklein** [comment]
> Yes.. I see drawbacks on both renaming it or adding xnames and keep support on for index (this would be confusing IMO).

Can't we keep support for `index` for a while, raising a deprecated warning when used? In this way old code won't break (yet), giving users time to adjust.

**Comment by bryevdv** [comment]
Yes, whatever we do, we should provide a deprecation path at this point.

**Comment by fpliger** [comment]
I've started working on this in #2088 . Changes are minimal but should give the intentions of the change..

One idea regarding the charts source is that charts that "just use" the input data without any computation don't rename it and use it "as is" (the previous implementation used to append "y_" to the name). Charts that apply computations on the data to build their "own" data to create their chart can prefix "their" series with a "<chart_type>_" prefix in order to make if clear to what charts these series belong to and to avoid overwriting in future scenarios.

Would be nice to have first feedback about the intentions.. :-) ping @bryevdv @damianavila @pzwang

**Comment by fpliger** [comment]
`x_names` is actually a  good replacement of `index` when it was used to received the key of the data series go be used as index(es) but not really good when it was used to explicitly pass an iterable to be used as index on the chart. Now that we have `x_names` and `y_names`, `index` could be a nice argument to keep supporting the previous pattern (probably useful specially when the input is a list of lists or arrays). Of course there are many other ways to solve this(say that the index always have to be specified in the input dataset and used with `x_names`, no accept explicit indexes, etc...) so I'd love to hear others opinion about it..

**Comment by bryevdv** [comment]
@pzwang @fpliger Regarding faceting, etc. I note that stacking and grouping are things that happen "inside" a particular chart, and that faceting is something that happens "outside". But I think they can be brought under a uniform interface. How about something like this:
```
# This is just shorthand to set stack="year" to the Bar chart
Bar(...).stack("year").Bar(...)

# And his is just shorthand to set group="cyl" to Bar Chart
Bar(...).group("cyl")

# But these are construct entirely new plots, configured with the right
# subsets of data, and put them in layouts
Scatter(....).wrap("cyl")
   
Scatter(...).tab("year")

# Aside: all this also suggests, if we are not already, we should defer the
# generation of renderers until the latest possible point before showing
```
These can be combined:
```
Bar(...).wrap("model").stack("year")
```
The advantage being that the user is not burdened with the "inside" vs "outside" nature of the operations.

**Comment by fpliger** [comment]
@bryevdv Nice idea... (can already imagine @damianavila  saying "Yeah! Method chain FTW!" :smile: )

There are a few tricky things to figure out on this... 

* You already mentioned the need to defer all renderers generation to the very last moment before show. It was easier before as `show` was controlled by the `Chart` instance, not it's delegated to the outer `show` method.

* Another issue is that you call those operation on the `chart` object but you need to "pass" them to the builder that you want to take care of this. It's easy(ish) if a chart only have on builder but more tricky if we compose charts


Is the core intention to add a sort of "built-in" faceting/groupping/stacking features (ala crossfilter but implicitly implemented)?

**Comment by bryevdv** [comment]
So thinking about this made me also think about what I didn't like about the previous method chaining. In an attempt to be general and have chained methods for every configurable, we were both redundant (since they could all be spelled as kwargs) and too limiting (because all they did was set the kwargs). I think this idea refines the use case to a specific domain (faceting, etc) which is good for documentation, and also lets the operation of the methods be more general (doing/hiding all the extra work to construct a faceted grid).

**Comment by bryevdv** [comment]
The intent is to be able to spell some of the crossfilter features programmatically, the way you can in ggplot, etc. I agree there are details to sort out especially wrt to composed builders.

**Comment by fpliger** [comment]
With a late night [relaxed] thinking mode on I'm tempted to say that this could be easier expressed (or at least buildable) with explicit unbound callables.. So:

```Python
# This is just shorthand to set stack="year" to the Bar chart
stack(bar, "year")

# And his is just shorthand to set group="cyl" to Bar Chart
group(bar, "cyl")

# But these are construct entirely new plots, configured with the right
# subsets of data, and put them in layouts
wrap(scatter, "cyl")

tab(scatter, "year")

# tabs for each year with plots for every model facet-wrapped
wrap(stack(bar, "year"), "model")

# rows for each year containing chars for each model 
vplot(hplot(bar, "model"), "year")
```

**Comment by bryevdv** [comment]
I actually started writing it that way (except with the fields as the first argument. They both have pluses and minuses I'll have to think about it more to develop a clear preference. One immediate disadvantage of the compositional approach is that it gets unwieldy by three nestings, for sure, with the "field" moving further and further away from the function it applies to.

**Comment by bryevdv** [comment]
pushing to 0.10 after Bokeh mini-summit end of May

**Comment by cstjean** [comment]
I wrote my own scatter_df a year ago, and the interface that I used was that the first two columns were the X and Y axes, while the remaining columns were put into the tooltips. It works well to make quick scatter plots by simply reordering the columns, for instance:

`scatter_df(df[['age', 'income', 'profession', 'gender']])`

I agree that the `x=, y=` syntax is nice too, but I hope there'll be a quick way to add tooltip data, as it's quite useful. Another big win was to have a `color_value='height'` keyword argument, to specify each dot's color.

**Comment by logmod** [comment]
While I second the proposal to add an x,y args interface I think that there are alternative means to make the bar function more user friendly. To make my point clear I will first repeat what is typically not obvious for the casual user.

If the user wants to visualize different datasets in a bar chart, the source may have a tabular form with the columns `[label,valuegroup_1,valuegroup_2, ...,valuegroup_n]` (e.g. `[month, revenue_US,revenue_EU,revenue_other]` or `[region,revenue_jan,revenue_feb,revenue_mar,...]`) These sources cannot be used directly with the current bokeh bar interface, because they are not in the required canonical form.

For the above example the source would have to be transformed from `[label,valuegroup1,valuegroup2,valuegroup3, ...]` to `[label, values, valuegroupname]` (e.g. `[month,revenue,region]`) with an inverse pivot function like Pandas melt:

`pd.melt(df, id_vars='label', value_vars=list(df.columns`[1:]`),var_name='valuegroupname', value_name='values')`

The bar function can then be called with `label='month',values='revenue",stack='region'` to display one bar per month with the global revenue and the regional revenue distribution inside the stacked bar. One group per month with separate bars per region is created with `..., group='region'` .

If the above function and explanations are added to the high-level chart docs and tutorials, this would reduce many of the current confusion and limitations for casual users without the immediate need to change the interface. Today the bar tutorial only permutates the available bar options for a canonical sample source, but does not explain how to transform other data sources into a usable format.

**Comment by fpliger** [comment]
The work on charts interface have already been started and you can grab more info from [wiki discussions dump](https://github.com/bokeh/bokeh/wiki/Bokeh-Days-Working-Document) and the recent related PRs merged into master.

For what concerns the documentation and tutorials, you mean the current master where the #2986 have been merged? This add lots of new documentation bits... If so and you have more specific suggestions I suggest you to open a separate issue that we can use to discuss/plan on.

Charts (and Bar) now support much more complex grouping, agg and other more complex operations. The non-trivial part is related to the differences between datasets users want to make Bar consume and making Bar smart[-ish] enough to normalize those...

**Comment by bryevdv** [comment]
@logmod to reiterate what @flpliger, it's not clear (at least to me) whether you are replying to the discussion above, or to the current new work that started to land in `0.10`. I think perhaps this issue should be closed an new discussion moved elsewhere. Thoughts, @fpliger ?

**Comment by fpliger** [comment]
@bryevdv I was writing a message to propose that then I realized it's probably better to tie this issue with #3024 so we can actually have all charts supporting the new API. I hope to have it ready tomorrow (depending on how long it takes to help trying the new server..). What do you think?

**Comment by logmod** [comment]
I was mainly referring to http://bokeh.pydata.org/en/0.10.0/docs/user_guide/charts.html and not to the github content. I assume that most casual users will check this page first. But also on the Gitub Wiki pages I did not see melt transformations or an x,y arg interface mentioned in the Bar use cases. Sorry if I may have missed something.

**Comment by bryevdv** [comment]
This was done ages ago, changing to `discussion` and closing.
