### ISSUE TITLE
Centered bar chart

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#1851]
Following discussion on #1836, was thinking of implementing a symmetric range. My proposed approach would be:
* subclass Range1d
* add two properties: `center` and `delta`
* use these to set the `start` and `end`, which will result in `end - start == 2 * delta` 

Once this is implemented, some charts e.g. `Bar` may want to have it as an option. But thought I would isolate this first.

I'll wait for a :+1: before pushing ahead.

**Comment by pzwang** [comment]
Thanks for opening the issue.

Is the symmetric range actually more of a Range2d that just happen to be collinear?  I'm not looking for a perfect taxonomic/ontological breakdown of graphing, but more on the practical point that a single position on this range will map to two different positions in screen space.  But maybe that doesn't violate any guarantees that a Range1d makes?

I might be misunderstanding something about what you're thinking for `start` and `end`, but it seems to me that `end - start` must be zero, since `delta` is symmetric around the center?  Or are you thinking about how to adapt this on top of the Range1d?  If so, then I might suggest that we abandon subclassing Range1d, since the conceptual *meaning* of "start" and "end" will be quite different with this range.  (We might consider adding a helper function which produces a synthetic Range1d equivalent for one or both of the half-spaces defined by this symmetric range...)

It's also possible I'm overthinking this. :-)

**Comment by bryevdv** [comment]
Here is how I would handle this. Plots can accept additional named ranges. So, I would handle this by having a `SplitRange` (or something) that coordinates two additional `Range1d` objects. Then individual glyphs can be configured to use either the "left" or "right" half of the `SplitRange`, which really just means being configured with the appropriate additional named range. Then, we need an axis object that can deal with `SplitRange` (by for instance, not stroking label for the the shared point twice). I think we can handle tools by letting split range have a synthetic range (similar to categorical ranges). Tools fiddle with this synthetic range, which the `SplitRange` then uses to update its children ranges.

**Comment by bryevdv** [comment]
To add, I would not make this a subclass of `Range1d` which might mean some of the property instance types will have to be loosened up a bit.

**Comment by birdsarah** [comment]
Hi @pzwang, I'm sorry, I mis-spoke slightly in my comment on #1836.

The "symmetric" range, that I'm proposing here, is not needed for the pyramid plots that I posted an image of. I really did mean a specialized case of the Range1d, and I've realized why symmetric is a bad name for it!

I was just thinking of being able to specify a Range  that runs from -10 to +10 as (center 0, delta 10).  I happen to be working with some data like that, right now, and it just felt more intuitive to me to specify a delta (the default center would be 0).

This is a very minor feature, but my thinking was to be able to have a default in the case of mixed-sign data where you had a "symmetric" axis.

Can we have the discussion of ranges, that facilitate pyramid plots on #1852?

**Comment by birdsarah** [comment]
Following the above confusion that I caused, I think a better name for my intention would be Centered.

(and I have changed the title of this issue as a result)

I'm not particularly tied to implementing a range, we could also put it as a flag on the Bar Chart. I was speculating slightly that this might be something useful for other types of charts and so was trying to think a bit more generically, but that might have taken me in the wrong direction.

**Comment by pzwang** [comment]
Ha, OK - I completely misunderstood.  In cases like this when an API might have two different sets of inputs (start+end or center+width), I generally lean towards picking one or the other as the internal representation, and converting from/into the other form via a method or property.  In the case of the charting interface, we would need to do some basic error checking in the bar() function itself to make sure that the user hasn't specified both sets of parameters, but otherwise I think this approach should work for numerical ranges.

It's worth pointing out that the same does not apply to categorical ranges, since if there is an ordering of the categories, then there is a well defined "start" and "end", but there is not a concept of distance so "width" is ambiguous.  One might choose for it to indicate how many categories, but if the categories themselves are numerical (e.g. age groups, year of manufacture, etc.), then this can be a little confusing.

**Comment by bryevdv** [comment]
Ah yes, I overthought it too. I do agree this kind of functionality can (should) just be layered on top of the existing `Range1d`. I do think the `SplitRange` concept might be useful in some contexts however.

**Comment by bryevdv** [comment]
A general description of the `SplitRange` is just the ability to have `twin axes` that don't stack on top, but instead render side by side.

**Comment by pzwang** [comment]
Yep.  And this is a common enough pattern that we should specialize for the two-axis use case...

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
