### ISSUE TITLE
Donut chart resize/zooming issues

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#1883]
Donut chart present the following issues with zooming:
- text labels to no scale with geometry when using wheel zoom. The more zoom the more text gets bigger compared to the initial layout
- using wheel zoom with mouse on one of the axes maintain the ratio geometry (i'd expect it didn't and geometry follows the only axes being zoomed) but not for text labels (which behave as I'd expect). See example zooming on x axis:

![screen shot 2015-02-13 at 13 26 03](https://cloud.githubusercontent.com/assets/1084690/6187211/f9aedf1e-b383-11e4-9dcd-8cf456258733.png)
- box zooming on specific areas around text labels results in randomly weird outcomes
- Resizing the charts with a different aspect ratio preset similar results mentioned when zooming on one axis. See example:

![screen shot 2015-02-13 at 13 31 09](https://cloud.githubusercontent.com/assets/1084690/6187260/a11224aa-b384-11e4-9999-925abcd6e232.png)

**Comment by bryevdv** [comment]
This all goes back to the same old issue:

https://github.com/bokeh/bokeh/issues/517

Plotting anything that relies on radial symmetry (like circles or wedges) "as-is" in a non 1-1 aspect is basically just broken at a fundamental, mathematical level. I don't see many options beyond:

* some heuristics to turn off certain tools for certain glyphs, at least by default
* letting the actual displayed geometry deform with aspect changes (i.e., circles become ellipses)

Though if there are other ideas I would love to hear them.

**Comment by pzwang** [comment]
Is it really just a tooling issue?  What happens if someone programmatically adds a glyph to a plot that is already anisometric?

I do agree that we need to figure out a way to express this incompatibility - because it is an incompatibility, and realistically no one is ever really going to want these kinds of weird stretchy/distored donut diagrams.  Instead, they want tools for selecting angular categorical ranges and radial sub-trees, etc.

In general I think that many of the data-oriented tools are projection-specific (think about cartesian, cartesian categorical, polar, hyperbolic, map/GIS, etc.).  There's no sense in trying to reuse these kinds of tools across projection types.  However, some other tools like resize and savetool and whatnot are mostly generic.  And yet others like hover, tap, etc. can work on points, and thus seem to be generic across all projection types but their implementations (and interpretations) are different for each projection.  (Note that in this case, the resize tool's only problem is that the plot gets too small - but most plots should have a concept of a "minimum size"; this is not specific to donut charts.)

I think that longer term, it would be useful to think about tools has having an "interaction class" to which they belong, and have the taxonomy/ontology of those be driven by more thoughtful consideration of infovis interaction patterns.  (I'm sure @JosephCottam has much to say about such things. :-)

**Comment by bryevdv** [comment]
`bokeh.charts` has moved to `bkcharts`, this issue should be re-opened there if necessary.
