### ISSUE TITLE
Should _repr_html_ trigger show()?

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#1895]
The `_repr_html_` method gets called in IPython notebooks whenever an object is evaluated on the last line of a cell.  Would it make sense to have this call the `.show()` method?

As a new user trying to use Bokeh in the notebook I generally found myself caught up by the necessity of the following steps

1.  Find where in the namespace to import the appropriate functions
2.  Find the `use_notebook` function in that namespace and then call it
3.  Construct my plot
4.  Find the `notebook=True` kwarg and the `.show` method

While straightforward once you're use to them I did find these frustrating when I was getting my legs.  Perhaps there are cheap solutions to removing some of them?  `_repr_html_ -> show()` is one possible solution to one of these steps.  Presumably there are good reasons to be more explicit though.  Some other thoughts

1.  namespaces: `statsmodels` has a flat and stable `.api` namespace that shields the user from changing internals.  Perhaps that would be a good model for Bokeh to replicate?
2.  `use_notebook`: Perhaps we can identify that we're in the notebook and make this default, much in the way that `matplotlib` is interactive by default in the wonky `pylab` mode.
3.  Construct plot:  This is fairly straightforward.  Hooray!
4.  `notebook=True` and `.show`: Again, perhaps it makes sense to rely on `_repr_html_` in this case.

Probably these things have already been discussed and I'm late to the game.  My apologies for making large suggestions without really having done my homework.  Feel free to disregard.

**Comment by bryevdv** [comment]
`_repr_html` should be enabled when it will work with everything, right now it is broken with widgets (probably some css conflict). 

Bokeh has several different APIs, so I don't think a single `.api` will do. This is really what `bokeh.models` (incredibly stable) `bokeh.plotting` (should be fairly stable now) and `bokeh.charts` (headed rapidly towards stability) are all about. I think in about month (maybe two) all of these different APIs will be very locked down. (I just opened up an issue about API versioning the other day, because we are getting near to a point when that makes sense)

**Comment by damianavila** [comment]
>_repr_html_ -> show() is one possible solution to one of these steps.

I agree on the `_repr_html_` when it is working for everything. There are other options involving post_cell "hooks" but I would go with the first one...

>use_notebook: Perhaps we can identify that we're in the notebook and make this default, much in the way that matplotlib is interactive by default in the wonky pylab mode.

Technically you **can not** know if you are in the notebook! 
But we could enable the `show` in the `_repr_html_` by default because the client will render the best representation available: in the browser it would be the the html representation (the plot embedded) whereas in other places, like a console, it would be just an html/text-based representation of the object...

>Bokeh has several different APIs, so I don't think a single .api will do

I agree on this comment too...

**Comment by mrocklin** [comment]
OK.  Thanks for the explanations!  Closing.
