### ISSUE TITLE
tap_select tool is actually tap

### ISSUE THREAD

**Issue by kgullikson88** [bokeh/bokeh#1926]
The [documentation](http://bokeh.pydata.org/en/latest/docs/user_guide/objects.html#click-tap-tools) says there is a 'tap_select' tool to select a single data point. However, trying to use that tool throws an error that it does not exist. Digging through the code, it looks like there is a tool call 'tap' ([here](https://github.com/bokeh/bokeh/blob/master/bokeh/plotting_helpers.py)), which appears to do the same thing. 

The documentation should be fixed (I would, but I don't know how to do automatic documentation).

**Comment by damianavila** [comment]
@bryevdv what do you think about this... we fix the docs? or we fix the name to be consistent with the "select" idea?

**Comment by bryevdv** [comment]
I'd rather change the docs. Tap tool can be used to trigger actions too. Also, there are two "Box" tools, so that's why there has to be "Box Select" and "BoxZoom". But there's only one "tap" tool, so no need to differentiate. For that matter I'd be more inclined to rename `LassoSelectTool` to LassoTool` for the same reason.

**Comment by pzwang** [comment]
+1 on both of Bryan's suggestions

**Comment by bryevdv** [comment]
Should do, but provide deprecation path for old tool names.

**Comment by bryevdv** [comment]
Most work should already be done in current "x, y names" PR
