### ISSUE TITLE
IPython Interact causes redraw that hides bokeh plot

### ISSUE THREAD

**Issue by aterrel** [bokeh/bokeh#1952]
Here is an example cell from my notebook. If you try to interact with it the plot goes aways. If I `show(plot)` in another cell it works. Would be nice to have this work.

```python
x = np.linspace(0, 2*np.pi, 2000)
y = np.sin(x)

source = ColumnDataSource(data=dict(x=x, y=y))

p = figure(title="simple line example", plot_height=300, plot_width=600)
p.line(x, y, color="#2222aa", line_width=3, source=source, name="foo")

from IPython.html.widgets import interact
@interact(f=["sin", "cos", "tan"], w=(0,100), A=(1,10), phi=(0, 10, 0.1))
def update(f, w=1, A=1, phi=0):
    if   f == "sin": func = np.sin
    elif f == "cos": func = np.cos
    elif f == "tan": func = np.tan
    source.data['y'] = A * func(w * x + phi)
    source.push_notebook()
show(p)
```

**Comment by damianavila** [comment]
The problem here in that two things (Bokeh and IPython) are trying to display at the same time... in fact, I don't know if there is an easy solution for this (probably not easy if there is one)... from the top of my head I can think in a wrapper IPython widget to encompass the Bokeh plot and then use the IPython widget layout machinery to put both the wrapper and the interactive widget in the same box... but this is not trivial, I guess... 
In the meantime, just separating the plot in one cell and the interactive in other one does not seems a big burden... but I will explore some possibilities to try to achieve what you requested.

**Comment by LienM** [comment]
FYI: I tried using interact as a decorator and as is, as well as interactive and they all give that same error:

Javascript error adding output!
ReferenceError: Bokeh is not defined
See your browser Javascript console for more details.

But when I define my widgets manually and interact with them through widget.on_trait_change(name, value), I am able to display both IPython widgets and Bokeh plot, at the same time, in the same cell. 

I'm not sure if this could help you, but I thought I would mention it anyway. 

![image](https://cloud.githubusercontent.com/assets/5683985/9933365/bc100fa4-5d4a-11e5-99b8-7799aadcaaa5.png)

**Comment by bryevdv** [comment]
I don't think there is any way to resolve this in the classic notebook. There may be better options in JupyterLab, where widgets could occupy one output area and a plot some other output area.
