### ISSUE TITLE
Lines plotting in a notebook

### ISSUE THREAD

**Issue by aflyax** [bokeh/bokeh#1957]
Copy-pasting this example: https://github.com/bokeh/bokeh/blob/master/examples/charts/lines.py

Results in: `AttributeError: 'Line' object has no attribute 'ref'`

Trying to execute this code:

``` python
from bokeh.charts import Line
from bokeh.plotting import show, output_notebook
output_notebook()

# income_df = pd.read_csv("income_2013_dollars.csv", sep='\t', thousands=',', index_col='year')
Line(income_df).show()
```

... results in:

`You have to provide a filename (filename='foo.html' or .filename('foo.html')) to save your plot.`

**Comment by bryevdv** [comment]
Two observations: 
* since you are dealing with time series, you want to use `bokeh.charts.TimeSeries`
* the `.show()` method is going away, there will be a docs refresh probably this week. Use the `show` function:
![screen shot 2015-02-23 at 1 41 02 am](https://cloud.githubusercontent.com/assets/1078448/6324262/3e207e7a-bafd-11e4-918a-1b3d9ee2766f.png)

**Comment by fpliger** [comment]
In addition to @bryevdv comment I suspect that you are also using a previous version of Bokeh (`0.7` or maybe `0.7.1`?) because or the reported: `AttributeError: 'Line' object has no attribute 'ref'`

If it's the case I highly recommend you to update to `0.8` or `0.8.1` that should be released later today `charts` interface have seen major changes and this later release and the new decoupled show method that Bryan mentioned is going to replace the `.show` entirely.

For completeness, the reason why this line:

```Python
Line(income_df).show()
```

is not displaying your chart is because `.show` method expects that at least one of the output arguments is specified. So it should work if you provide `notebook=True`
