### ISSUE TITLE
Integration with pandas

### ISSUE THREAD

**Issue by aflyax** [bokeh/bokeh#1958]
When replotting a pandas.plot, the plot comes out with a weird xlim. Example here: http://nbviewer.ipython.org/github/aflyax/Python/blob/master/notebooks/income/bokeh_issue.ipynb

**Comment by fpliger** [comment]
@aflyax please see this related thread #1955 

As mentioned in that issue "our MPL support comes from a third party lib, mplexporter, which is not fully complete. Any bug requests though, should go on its GH tracker: https://github.com/mpld3/mplexporter ."
 
In general it's better to use `bokeh.charts` instead (like it seems to be the case of your other reported issue that I'll be looking in a second :wink: )

**Comment by bryevdv** [comment]
The reason is because several renderers are getting added to the scene with coordinates far from the real data:
![screen shot 2015-02-23 at 1 23 16 am](https://cloud.githubusercontent.com/assets/1078448/6324106/b1a78c10-bafa-11e4-9146-67dbc2396f9c.png)
We use the third party library `mplexporter` to provide MPL compatibility. It is possible there is some way we could be using it differerently (ping @damianavila) But I suspect this is an upstream problem I encourage to raise the issue there at https://github.com/mpld3/mplexporter

**Comment by bryevdv** [comment]
To be clear, the reason is because we use a `DataRange1d` that tries to auto-range the plot based on the data each render has. We could perhaps work around this, if `mplexporter` provides enough information to somehow exclude these renderers from the data range.

**Comment by damianavila** [comment]
I will investigate here if we can come up with a workaround...

**Comment by colinfang** [comment]
I think actually this is because legend conversion is not implemented:  bug #1258 

If you disable legend, it works fine, see

http://nbviewer.ipython.org/gist/colinfang/5f99fc7371d1999e0a0c

**Comment by damianavila** [comment]
Seems the case... let change the bug label to feature request for further exploration.

**Comment by bryevdv** [comment]
Closing. No more work is going to happen on Bokeh MPL compat until/unless MEP 25 is implemented, at which point a comprehensive solution can be looked at.
