### ISSUE TITLE
Patches : passing a list instead of a list of lists result in a silent error

### ISSUE THREAD

**Issue by knightofni** [bokeh/bokeh#1968]
As said in title. It probably should throw an exception, or at least a warning.

Illustrative (not working) example below

```python
source = ColumnDataSource(data=dict(xs=xs, ys=ys)) 
country_glyph = Patches(xs='xs', ys='ys', fill_color=colors[0])
plot.add_glyph(source, country_glyph)
```
![screen shot 2015-02-24 at 10 48 29 am](https://cloud.githubusercontent.com/assets/3415960/6342350/b65f4e50-bc12-11e4-926f-fdaf3750b581.png)

```python
source = ColumnDataSource(data=dict(xs=[xs], ys=[ys])) 
country_glyph = Patches(xs='xs', ys='ys', fill_color=colors[0])
plot.add_glyph(source, country_glyph)
```

![screen shot 2015-02-24 at 10 49 09 am](https://cloud.githubusercontent.com/assets/3415960/6342358/d36f6bba-bc12-11e4-8dab-5c6f7664b6f4.png)

**Comment by bryevdv** [comment]
@mattpap do you have any thoughts on how some validation might be added for this? In general, I think the best that could be done is to check at time of serialization. 

@knightofni Unfortunately there is not really any way to check ahead of time, `Patches(xs='xs', ys='ys')` is a specification that says "get your data from columns named `xs` and `ys` in whatever data source you end up configured with" but the data source does not have to exist yet, could change later, etc. This is the sort of thing that can be checked for more consistently in higher level interfaces, because they assume the responsibility of coordinating all these low level model objects. As I said, I'm not sure using the low level *models* interface is generally advised for common use cases. Is there something in particular you are trying to do that `Figure.patches` cannot accomplish?

**Comment by knightofni** [comment]
@bryevdv I'm trying to have an area chart, and to update its data based on a the selection from a dropdown, embedded in a webpage. My main source of inspiration was this (great) [example!](https://github.com/bokeh/bokeh/blob/master/examples/glyphs/data_tables_server.py) - which is using the models interface. So I was under the impression that this kind of outcome needed the low-level interface. I'd love to be wrong and to be able to use the plotting interface !
 
I wasn't asking for it, but logging this kind of errors in the browser js console would be a great step forward.

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
