### ISSUE TITLE
Patches (from models) fill_color argument throws hard to understand error if given a list of colors

### ISSUE THREAD

**Issue by knightofni** [bokeh/bokeh#1969]
When feeding the Patches method (*from the models interface*) the **fill_color** argument with a list of colors (rather than a single color), bokeh will throw a relatively confusing error (assert error ==> not a dict - see below).

As in the patches method (*from the plotting interface*) it is possible to feed the **color** argument with a list of colors (one for each patch), it feels natural to keep using lists of colors when transitionning form the plotting to the models interface.

suggestion : raise exception with an explicit message along the lines of 'Please pass a single color to the fill_color argument (lists of colors not supported for the patches method)'

(non-working example, just to get the point across)
```python
from bokeh.models import Patches
colors = brewer["Blues"][6]
country_glyph = Patches(xs='xs', ys='ys', fill_color=colors)
```
when trying to display, will throw the follow error

```python
/Users/nicolas/anaconda/lib/python2.7/site-packages/bokeh/properties.pyc in changed_properties_with_values(self)
    688 
    689     def changed_properties_with_values(self):
--> 690         return dict([ (attr, getattr(self, attr)) for attr in self.changed_properties() ])
    691 
    692     @classmethod

/Users/nicolas/anaconda/lib/python2.7/site-packages/bokeh/properties.pyc in __get__(self, obj, owner)
    150     def __get__(self, obj, owner=None):
    151         if obj is not None:
--> 152             return self._get(obj)
    153         elif owner is not None:
    154             return self

/Users/nicolas/anaconda/lib/python2.7/site-packages/bokeh/properties.pyc in _get(self, obj)
    433                 # setval should be a dict at this point
    434                 #import pdb; pdb.set_trace()
--> 435                 assert(isinstance(setval, dict))
    436                 return setval
    437         else:

AssertionError: 
````

**Comment by bryevdv** [comment]
First just for information, the reason that passing a list of colors works in the *glyphs* and *charts* interfaces is because they are much higher level interfaces. They will automatically construct a data source for you, if the plot needs one, if you pass in actual data. Their entire purporse is to make stringing together models more simple. That sort of automation is exactly when should **not** happen with the *models* interface. You are responsible for creating and putting everything together with the *models* interface. 

I'm torn here. The *models* interface is a very low-level facility, it is basically intended purely as a serialization layer, and is intentionally kept as simple as possible. Ideally all the models would just be declarative `HasProps` classes with no logic whatsoever. We have made a few specific concessions to convenience (i.e., allowing `Range1d(10, 20) instead of requiring `Range1d(start=10, end=10)`) but I don't think adding alot of code to **models** is advised. I actually do not think using the *models* interface directly should be generally endorsed, except by developers building especially sophisticated applications. 

@bokeh/dev thoughts?

**Comment by knightofni** [comment]
@bryevdv Just to be clear, i'm not suggesting that bokeh accepts different input type for colors.

Just to have a more descriptive error message. Something in the line of :

`assert(isinstance(setval, dict)), 'You've passed a list of colors. A single color was expected'`

Except that i can't write a good error message, as it don't really know what other cases could bring to that assert statement.

**Comment by bryevdv** [comment]
Well, that particular assertion is in the middle of some very generic serialization machinery, that has nothing in particular to do with patches or colors. Every Bokeh model uses the same code for serializing. 

Now that I think about, there might be a place to provide some better information. @mattpap what about some validations around here:

https://github.com/bokeh/bokeh/blob/master/bokeh/properties.py#L322

that the value is a scalar?

**Comment by damianavila** [comment]
We can probably give some better information, but I agree 100 % with this:

> You are responsible for creating and putting everything together with the models interface.

Because of this:

> The models interface is a very low-level facility, it is basically intended purely as a serialization layer, and is intentionally kept as simple as possible.

As a general though: as far as we are not making things more complex that it should be for the low level API, I am ok with provide better info, but always respecting the idea of the low level API and no turning it into something in the middle between `models` and `plotting`...

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.
