### ISSUE TITLE
Checking with pyflakes/pep8/flake8?

### ISSUE THREAD

**Issue by almarklein** [bokeh/bokeh#1980]
I noticed that there is no CI for style checking. I must admit that I feel rather liberated from complying to the sometimes dogmatic rules of pep8 :) On the other hand some enforcement of style can improve code readability. Is this something that we want at some point?

Although style is just ... style, I've found pyflakes to be helpful for code *functionality*, because it can detect bugs (e.g. using a nonexistent variable name) and unused imports.

**Comment by damianavila** [comment]
We have this discussion previously, we follow pep8, but not religiously... I mean, the main aim of the styling is to improve the readability, so if we have to break some rule to make the code more readable, we do it without any problem, but I repeat, in general we follow the rules...
Since we have some liberties, probably setting up style checking on the CI will trigger a lo of "errors"...
but maybe we can clean the code base a little bit to avoid things like unused imports...

**Comment by almarklein** [comment]
Ok, makese sense. Let's forget about style checking then. But I might have a look what using on;y pyflakes might bring.

**Comment by almarklein** [comment]
Sounds good: *Pyflakes makes a simple promise: it will never complain about style, and it will try very, very hard to never emit false positives.*

**Comment by bryevdv** [comment]
+1 for pyflakes integration. FWIW I have been slowly trying to make things pyflakes clean as I go. All of `bokeh.charts` is in a recent PR, for example.

**Comment by damianavila** [comment]
@bryevdv if we integrate pyflakes in the TravisCI, we would need to change a lot of things we believe is "readable" in the current state... I am not completely opposed... but if we do this... we probably need to do it in stages... because subtle bugs can be introduced with the whole rewrite... and integrating to Travis will push us to it at once...
To summarize, I think the codebase needs a cleanup... but I don't like too much a major clean up at once... so my proposal:

1- Trying to make the codebase pyflakes-compatible in steps (maybe attacking modules as separate PRs. 

2 - Activate pyflakes on TravisCI

and not in the other way...

**Comment by bryevdv** [comment]
@damianavila can you provide specific examples? `pyflakes` is not a style checker. The most common thing I encounter *by far* when making things pyflakes clean is unused imports. Most of the time they are really unused. Sometimes it is intentional (transitive imports). In those cases we can just do:
```
    import foo; foo
```
and that will shut `pyflakes` up.

**Comment by bryevdv** [comment]
There's also not a monumental pile of warnings to begin with:
```
bryan@laptop (git:task/1916_state) ~/work/bokeh/bokeh $ pyflakes . |grep -v tests| wc -l
221
```

**Comment by damianavila** [comment]
well, I don't use pyflakes, and I though it was an style checker... so I guess it would bring a of warnings... maybe I have to look into pyflakes before commenting again... jeje... I will take a look now...

About the transitive import... I think your pattern proposal in nice and we **should** adopt it...

**Comment by almarklein** [comment]
I started with making the server submodule pyflakes clean (because these were the last to appear in the log, which made me fix them first). I found lots of unused imports, a couple of unused variables, and one or two actual bugs. Also something that I'm not sure of. Will submit a PR so we can discuss.

BTW: I ended up using flake8, but then turn the style errors off. Flake8 gives a bit more room for making it ignore stuff: e.g. `import foo  # noqa`  (no idea where the noqa stands for, but it make it shut up). Also `foo = something()  # noqa - aint gonna use foo`.

**Comment by damianavila** [comment]
mmm... interesting... how do you deactivate pep8 warnings in flake8?
and yes, the `# NOQA` (I guess stands for "no quality assurance"??) seems the canonical way to deactivate the warning...

**Comment by almarklein** [comment]
`flake8 --ignore=E,W` 

Normally you can do `flake8 --ignore=W101,E104` etc. to disable specific warnings. The above suppresses *all* style errors and warnings.

**Comment by fpliger** [comment]
as a side note: I really dislike having to add thinks like # NOQA or other thinks just to make pyflakes and friends happy. :-/  (sorry, I really needed to say that jeje)

**Comment by almarklein** [comment]
@fpliger I agree :(  but the benefits outweigh this minor nuisance IMO.

**Comment by damianavila** [comment]
> as a side note: I really dislike having to add thinks like # NOQA or other thinks just to make pyflakes and friends happy. :-/ (sorry, I really needed to say that jeje)

:100:

but if we are adopting it, then we have to find the less worse solution... right now... I would say I am tempted to give :+1: to @bryevdv approach... but maybe there is other things were we have to use the `noqa` and having mixed things is not good neither... so... I am sure yet, where is the better path to follow...

**Comment by mattpap** [comment]
> as a side note: I really dislike having to add thinks like # NOQA

Me too.

**Comment by bryevdv** [comment]
FWIW I have seen 
```
import foo; foo
``` 
used in other projects

**Comment by almarklein** [comment]
Ok, I think we all agree that using PyFlakes is a good idea. However, pyflakes need a little help. And we all agree this sucks. Now to find the approach that sucks the least. I think there's two typical situations (unused imports and unused variables), and two methods that we can use:

    # Method A
    from .spam import foo; bar
    from .spam import foo, bar; foo; bar
    value = only_need_the_side_effects(); value
    
    # Method B
    from .spam import foo  # noqa
    from .spam import foo, bar  # noqa
    value = only_need_the_side_effects()  # noqa

Method A has the advantage that it can also be used with vanilla pyflakes (`noqa` is a flake8 thing). 

Personally, I find method B less ugly. I suppose because you don't add code, just a comment. Also, I imagine that with method A, you'll often add a comment as well, to explain the weird code. That said, I'll go with whatever the majority decides :)

**Comment by bryevdv** [comment]
I would not propose adding a comment for that, I would propose documenting that in our dev docs as the accepted convention for making transitive imports available. I use vanilla pyflakes all the time, btw another reason I prefer method A.

**Comment by almarklein** [comment]
Ok, I suppose it will be method A then; I'll change the PR accordingly.
