### ISSUE TITLE
Custom color palettes with the image glyph

### ISSUE THREAD

**Issue by samhile** [bokeh/bokeh#2015]
The built-in color palettes (brewer) support upto 11 color values. Was there a reason for limiting this to such a small number? I want to plot my continuous (non-categorical) scalar data with a smooth colormap, like this

```
N = 100
x = np.linspace(0, 10, N)
y = np.linspace(0, 10, N)
xx, yy = np.meshgrid(x, y)
d = np.sin(xx)*np.cos(yy)

figure()
ax=subplot(111)
ax.pcolormesh(xx,yy,d,cmap='Spectral')
```
![image](https://cloud.githubusercontent.com/assets/3879759/6481092/856bb7e6-c2ae-11e4-808b-aeb6b3648820.png)

The default pyplot colormaps have 256 values. I have tried sending plotting.image() a custom palette based on matplotlib's, but in passing it to bokeh, i seem to only get the blue channel??

```
N = 100
x = np.linspace(0, 10, N)
y = np.linspace(0, 10, N)
xx, yy = np.meshgrid(x, y)
d = np.sin(xx)*np.cos(yy)

custom=[]
for n in arange(0,256):
    rgba0_1 = cm.Spectral(n)#get 4-tuple RGBa
    rgb0_1 = array(rgba0_1[0:3])#drop the alpha value, convert to array
    rgb0_255 = tuple(int(n) for n in rgb0_1*255)#rescale RBG as ints, back to tuple
    custom.append(tuple(rgb0_255))

p = bk.figure(x_range=[0, 10], y_range=[0, 10])
p.image(image=[d], x=[0], y=[0], dw=[10], dh=[10], palette=custom)

bk.show(p)
```
![image](https://cloud.githubusercontent.com/assets/3879759/6481099/97fc9c36-c2ae-11e4-8c83-5c95425cf3b9.png)

Is this a bug, or me doing something wrong? I would like to see more native support of denser palettes in the long term. And short term, any suggestions how i can work around this?

**Comment by timburgess** [comment]
There is no inherent limitation AFAIK. To create your own palette, <code>from bokeh.models.mappers import LinearColorMapper</code> and then pass a list of the hex codes you want to use when you create the LinearColorMapper. Once that is created, instead of the <code>palette</code> keyword, use <code>color_mapper</code>. So something like <code>.., color_mapper=LinearColorMapper(SSTPalette)</code>.

I am using a large palette and it works fine.
![](http://i1311.photobucket.com/albums/s676/oztimbo/Screen%20Shot%202015-03-10%20at%206.13.55%20pm_zpshmosie1s.png)

**Comment by birdsarah** [comment]
Discussion is now more than 3 months old. Can re-open if renewed interest.

**Comment by tderond** [comment]
This will convert a matplotlib colormap into a bokeh palette:

```python
import matplotlib as plt
import matplotlib.cm as cm
import numpy as np

colormap =cm.get_cmap("Blues") #choose any matplotlib colormap here
bokehpalette = [plt.colors.rgb2hex(m) for m in colormap(np.arange(colormap.N))]
print bokehpalette
```
