### ISSUE TITLE
Ugly buttons when plotting inside notebook on firefox 36

### ISSUE THREAD

**Issue by nevermindewe** [bokeh/bokeh#2024]
bokeh version: 0.8.1
ipython version: 3.0.0
browser: firefox 36 (issue does not occur on Chromium 40.0.2214.111)
OS: Ubuntu 14.04
Arch: x86_64
```
In [2]: bokeh.print_versions()

   Bokeh version: 0.8.1
  Python version: 2.7.9-CPython
        Platform: Linux-3.13.0-45-generic-x86_64-with-debian-jessie-sid
```

How to reproduce:
1. open a new ipython notebook
2. Paste the following code:
```
from bokeh.plotting import figure, output_notebook, show
output_notebook()
tools="pan,wheel_zoom,box_zoom,reset,save"
p = figure(tools=tools, plot_width=500, plot_height=500)
p.line([1,2,3,4,5,5,5,5,6], list(xrange(9)))
show℗
```
3. Run the cell. The output should look like the attached screenshot.
The tool buttons are not as expected.

![bokeh_ugly_buttons](https://cloud.githubusercontent.com/assets/5727768/6491285/39c530b2-c27a-11e4-80b7-a359a1da410b.png)

**Comment by nevermindewe** [comment]
tag: bug

**Comment by bryevdv** [comment]
OK the problem has been identified and is reproducible. The issue arrises if the first cell that runs the `bokeh/__init__.py` is executed a second time. This is because the original output div, which contains a link or `<style>` tag for the CSS, is removed on a subsequent import (since the module is not executed, and `load_notebook` is not called, the second time). I can also potentially imagine problems if something else tries to publish something else in the same cell, but this is unconfirmed. 

@bokeh/core I am not sure we can keep the `load_notebook` in the `bokeh/__init__.py` and have this work in a sensible way, unless there is some way to "publish` to the IPython notebook in a way that will persist if the original cell is cleared. If not, suggest moving `load_notebook` call into `output_notebook` where the output div can always be unconditionally published.

**Comment by bryevdv** [comment]
@nevermindewe please check again with the next dev build (should be one out in the next day or two)

**Comment by damianavila** [comment]
>suggest moving load_notebookcall intooutput_notebook` where the output div can always be unconditionally published.

Just a little late, but this is the proper way I think... and you did it in this way :+1:
