### ISSUE TITLE
ColumnDataSource.from_df bug (does not fill the column_names list)

### ISSUE THREAD

**Issue by knightofni** [bokeh/bokeh#2030]
Creating a ColumnDataSource from a dict works very well, but when using the `.from_df` method doesn't work in the ipython notebook. Apparently `column_names` stays empty after calling `.from_df`.

works :
```
source_fromdict = ColumnDataSource(data=dtest)
```

fails :
```
source_fromdf = ColumnDataSource()
source_fromdf.data = ColumnDataSource.from_df(df)
```

#### [Example notebook](http://nbviewer.ipython.org/gist/knightofni/a961609051378db03bbf)

**Comment by bryevdv** [comment]
Right now, `ColumnDataSource.from_df` returns a `dict` that can be used to initialize a new `ColumnDataSource`:
```
In [22]: from bokeh.models.sources import ColumnDataSource

In [23]: import pandas as pd

In [24]: dtest = {"a": [1,2], "b": [1,2,]}

In [25]: df = pd.DataFrame(dtest)

In [26]: source = ColumnDataSource(data=ColumnDataSource.from_df(df))

In [27]: source.column_names
Out[27]: ['b', 'index', 'a']
```
I think this is a bit silly, and that `from_df` should just return a `ColumnDataSource`. See this comment:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/sources.py#L86

In any case, setting a `data` attribute is not a supported way of initializing a `ColumnDataSource`. If you are aware of some place that describes doing this, please let us know so that we can change it. There is a `data` *argument* that is accepted by the initializer, but that is used to initialize other internal attributes. There is no public `data` attribute.

**Comment by bryevdv** [comment]
To add more info, if you do want to add new columns to an existing column data source, you can use the `add` method:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/sources.py#L128

**Comment by knightofni** [comment]
I picked it up from the example `data_tables_server.py`

here's the relevant code :

```
    def update_data(self):
        df = mpg
        if self.manufacturer_filter:
            df = df[df["manufacturer"] == self.manufacturer_filter]
        if self.model_filter:
            df = df[df["model"] == self.model_filter]
        if self.transmission_filter:
            df = df[df["trans"] == self.transmission_filter]
        if self.drive_filter:
            df = df[df["drv"] == self.drive_filter]
        if self.class_filter:
            df = df[df["class"] == self.class_filter]
        self.source.data = ColumnDataSource.from_df(df)
        self.session.store_document(self.document)
```
