### ISSUE TITLE
Create charts with DataSources

### ISSUE THREAD

**Issue by matdrapeau** [bokeh/bokeh#2039]
Would be nice to be able to create charts using DataSource like this:

```
from bokeh.models.sources import AjaxDataSource
from bokeh.charts import Line

source = AjaxDataSource(data_url='http://localhost:5050/data')
Line(source, index='x', title="Lines", ylabel='y_label')
```

**Comment by matdrapeau** [comment]
I think this is related: https://github.com/bokeh/bokeh/issues/1811

**Comment by fpliger** [comment]
Yes. It's definitely related and #1841 is somehow related too in the broader view.

The tricky part of managing and passing DataSources around is that some charts does not just consume the data input they receive but also compute the related data to be used for their specific chart construction (i.e.: bars, boxplot, donut..). So we not only need to accept explicit DataSources as you suggest, but also need to let a chart know how to use it.

**Comment by matdrapeau** [comment]
@fpliger do you suggest to move the knowledge of the chart construction into coffee?
Is there any other ways to be able to template the construction from python and be able to propagate it into another form than a rendered chart?

**Comment by matdrapeau** [comment]
@bryevdv Wondering if the last big PR (https://github.com/bokeh/bokeh/pull/2109) would simplify this task?
I have no clues if possible to create a chart without any initial values to populate it?

**Comment by fpliger** [comment]
@matdrapeau PR #2088 is doing the first steps in this direction. At the moment it supports ColumnDataSource and I didn't test Ajax yet. 

What do you mean with "a chart without any initial values to populate it"?

**Comment by matdrapeau** [comment]
@fpliger some charts usually calculate few attributes (min / max value of datasource by example) in order to build the graph properties on the backend side.
The ajax data source could constantly pull to get new values but this is done on the js side where chart attributes won't be recalculated.

**Comment by fpliger** [comment]
@matdrapeau Yes.. this is an aspect to consider. The goal of that PR is mainly to start support for this and make charts interface more robust... trying to "get it right" first. Honestly I still need to take a deep look into the ajax data source internals and check how this can be integrated. I'll add it as a reminder in order to try and include tweaks that can be helpful on that PR.

Please let me know if you have any advice or want to jump in and help somewhere!

**Comment by matdrapeau** [comment]
@fpliger I can't wait to see that PR to be landed and start understanding the changes that will involve. Honestly, I still see that feature as a big refactor of the actual design and even if I am willing to help, I really don't know where to start.

The ```DataSource``` had been moved outside of the chart builders scope, which is a good move, but how would you suggest to move the calculation logic outside of the builders? By example, if I look at the horizon builder, we need the values to get the maximum and then split the values in equal ranged folds. If we got the values from an ajax request that will get updated at a periodic interval, having a dynamic html chart is impossible since you won't ever handle these new data in the backend.

**Comment by fpliger** [comment]
@matdrapeau there is hope :-)

I've got a charts version of the https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/ajax_source.py example using `charts.Scatter` with just a 5/6 lines change. (which is very exciting! :smile: ). That said there's a lot to consider, specially for the charts that have computed data on their sources. One of the nice changes on that PR that make this change "easy" for the Scatter chart for instance is that ranges are now DataRange1d instances that delegate ranges computation to the plot renderers...

With that in mind I thing I should not mix this addition on that PR which is already too large. The good news is that I think it could be done...

**Comment by matdrapeau** [comment]
@fpliger this is VERY exciting, I would confess... being able to create charts so easily by providing an external source endpoint. This could lead to a major success of this lib for web development!

So in order to integrate all sorts of chart, you would suggest to implement some primitives into https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/range/data_range1d.coffee to be used by the different charts?
If I look into the different ```_process_data``` functions from chart builders, there is so much differences that would mean to move a lot of logic into coffee then. Isn't there another way to sort that out?

**Comment by matdrapeau** [comment]
@fpliger @bryevdv I've seen that 0.9 had been released... The https://github.com/bokeh/bokeh/pull/2088 wasn't included and I am wondering what is the direction for the charts and ajaxdatasource in the upcoming releases in order to maybe contribute with this current feature request.

**Comment by fpliger** [comment]
@matdrapeau we postponed that a bit because it's a big change to the charts API in general. We'd like to "get it right" from the beginning in order to build a strong interface and promote it to the next level of maturity.
That said, we plan to have discussions regards that during next week. I'd say that most of the work is done and I really want to have it merged for the next release but we can have a more concrete idea next week.
what do you think @bryevdv ?

**Comment by matdrapeau** [comment]
@fpliger have seen that your PR has been closed and haven't heard of any clear statements being made about the charts API as you stated.
Is there a clear direction being made so far that wasn't written somewhere?

**Comment by damianavila** [comment]
@matdrapeau, I close the @fpliger for housekeeping, but I know @fpliger and others have discussed about the PR in a recent bokeh in person meeting. I would left to @fpliger to give you the details on that because I was no present there. I think he (or others) are writing some document on the matter.

**Comment by fpliger** [comment]
@matdrapeau let me apologize for the lack of better communications and a more accurate schedule here. 

We did have many meetings regarding `bokeh.charts` interface as planned. While working on the next API we really realized that the `bokeh.charts` have a lot more tell and it really can extend and fill a lot of usage areas that are lacking in easy and full support. During the meetings and discussions this came out quite clear so the work of defining what the `bokeh.charts` interface evolution should really be turned out to be more complex and extended then expected. It's not only a matter of supporting new `DataSources` or extending the interface with new chart types. It is, instead, a matter of build a solid foundation for an entire design to support rich features like composition, aggregation, faceting and much more. You can see the [related wiki page](https://github.com/bokeh/bokeh/wiki/Bokeh-Days-Working-Document) that we are still formalizing as outcome of that work. 

That said other deadlines have also been put into my stack in the last month so the progress have been slowed down a bit but I and @rothnic are still actively working on moving this forward. I'm not able to define release schedules for this but we are probably going to have a better understanding after the next 0.9.1 release happening in a week or so.

**Comment by matdrapeau** [comment]
@fpliger @bryevdv that's been a while I've looked at the progress of bokeh since I was working with other tools to achieve my goals of generating dynamic graphs using ajax endpoints. Wondering if you guys were able to close this gap using bokeh lately and if this is still on the roadmap?

**Comment by matdrapeau** [comment]
@bryevdv @fpliger is it now possible with all changes made to the charts to be able to create them directly from an AjaxDataSource? Thanks

**Comment by fpliger** [comment]
@matdrapeau sorry but no, unfortunately. The main reason is because the new `charts` cover a much larger set of input types and more complex operations. This brought many more features but also a few drawbacks. First, `charts` do not support dynamic data updates and neither `AjaxDataSources`. One of the reasons is that charts never use the same dataset it receives as input and every chart glyph has it's own computed datasource.

I've started looking at the dynamic updates which is a mandatory step in order to also support `AjaxDataSources` but I'm not really sure I'll be able to add the feature for the next `0.11` release and have no real estimations about the `AjaxDataSources` (and it may turn out to be very hard with the current implementation).  

At this point I'd suggest you to evaluating the plotting interface for this. We can, eventually, try to expose parts of the `charts` interface that do the computations and grouppings so you could still use them to create your datasets. 

Could you elaborate a bit on your use case so we can check if there are alternative solutions we can try to accomodate the need?

**Comment by matdrapeau** [comment]
@fpliger thanks for your feedback, that's sad to see that the new "improved" implementation would be much harder to close the gap between charts and a usual type of DataSources for web operations...

What I'm trying to do is pretty simple, (could be either lazy or eager) loading different charts using an API that provides data to be drawn.

**Comment by bryevdv** [comment]
@matdrapeau is there a reason you can't use the `bokeh.plotting` interface? Your above example is just creating a line, that would work fantastically with updating a `ColumnDataSource`. As an example see the updating plots at the bottom of https://github.com/bokeh/bokeh/pull/3420

**Comment by matdrapeau** [comment]
@bryevdv I kept the example simple as what I really need to use are heatmap, timeseries and horizon graphs.

**Comment by bryevdv** [comment]
Heat map and time series are both also fairly trivial with `bokeh.plotting` in most cases, but Horizon chart unfortunately not as much. As mentioned, the data used to actually plot things like Horizon charts are heavily transformed from the original data in the data source, and right now this transformation happens only in the python API. The idea of implementing some of the charts functionality in the JS side has been proposed, and it could certainly be nice, but right now there are other much higher priorities. If someone wanted to contribute this work we would definitely try to help.

**Comment by datnamer** [comment]
@bryevdv I odn't know if it would help, but there are JS utilities for stats, aggregation, binning etc in this vega utility lib: https://github.com/vega/datalib

**Comment by fpliger** [comment]
@datnamer Thanks for the link. datalib has been on our radar for a while... there is potentially quite a lot of work to move parts of the implementation to the JS side and we had many other priorities on the queue. So, yes, it's still something we consider but I'm not sure it can get efforts in the short term but...... If there is someone with bandwidth and willing to try working on it I'd be delighted to support the effort and help. :-)

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/36)
