### ISSUE TITLE
cannot seem to make x-values different than default in Line

### ISSUE THREAD

**Issue by chanansh** [bokeh/bokeh#2048]
I am trying to alter the example in https://github.com/bokeh/bokeh/blob/master/examples/charts/lines.py
to have my custom x-values through the "index" argument. But it seems to fail...
What do you recommend to do?

```
import numpy as np
from bokeh.charts import Line
from bokeh.plotting import output_file, show
output_file('line.html')
xyvalues = np.array([[2, 3, 7, 5, 26], [12, 33, 47, 15, 126], [22, 43, 10, 25, 26]])
line = Line(xyvalues, index=np.array([5, 6, 7, 8, 9]), title="line", legend="top_left", ylabel='Languages')
show(line)
```
```  
File "C:\Anaconda3\lib\site-packages\bokeh\charts\builder\line_builder.py", line 110, in <listcomp>
    values = [self._values[col][x] for x in xs]
IndexError: index 5 is out of bounds for axis 0 with size 5
```

**Comment by fpliger** [comment]
This is going to be fixed when we merge #1974 (which should be happening very soon).

**Comment by chanansh** [comment]
What is the different between Chart.Line ans just line? 9ne suppose to be high-level and the other low level. I dont understand the difference. 
Thank!

**Comment by fpliger** [comment]
As you've mentioned `charts.Line` belongs to the higher level `charts` interface while `line` expose access to the lower glyph interface which basically displays a single line that connects several points. In the case of Line the difference is not that obvious like with other type of charts, but you can notice that `Charts` just requires one line to take your input and return the `chart` object with the line rendered, while you need at least 2 lines of code to do the same with the lower glyph interface.

The main functionality of the `charts` interface is to provide a set pre-built `Charts` that already take care of calculations and automations, so you can call create those with just one line of code instead of having to write several lines of code using the lower level interfaces. A central role in that scenario is played by `Builder` classes, which task is to consume inputs, create sources, ranges, glyphs, rendered and pass everything to the new chart where they are being drawn into. If you look at the BoxPlot or Donut chart you can see that there is no glyph that does similar things (like with the `Line` chart and the `line` glyph), so the different should be more clear. `BoxPlot` charts, for instance, use rect, circle and segment glyphs to draw the geometries after having calculated all the equations to distribute the received input data. 

Does this make sense? O hope this clarifies your doubts..
