### ISSUE TITLE
multiple y-axes don't plot things independently

### ISSUE THREAD

**Issue by nevermindewe** [bokeh/bokeh#2093]
In the code below, an extra y-axis is created and placed on the right side of the figure.
The x3 and y3 data are plotted against the y axis on the right side of the figure instead of the normal left side.
When the "y3" data is small, the plot looks as expected.
When y3 is changed to 'y3':[5,10,150], the y-axis on the left side of the figure changes its range.
It seems like that shouldn't happen.
The expected behavior is that the y-axis on the left side won't change at all (since the f.circle call explicitly uses the 'extra_y' axis.

```
from bokeh.plotting import figure, show, ColumnDataSource, output_file
from bokeh.models import Grid, GridPlot, LinearAxis, Plot, Range1d, DatetimeAxis

output_file("/tmp/bokeh_test_multiaxis.html")

x1_data = [1,2,3]
y1_data = [4,5,6]

x2_data = [20,30,40]
y2_data = [40,50,60]

#If y3 is changed to 'y3':[5,10,150], the left y-axis range changes.                                                                                            
#It seems like that should not happen.                                                                                                                          
#The desired behavior is to have each y-axis be independent of each other                                                                                       
#  so that we can plot different things on the same figure                                                                                                      
source = ColumnDataSource(data={'x1':x1_data, 'y1':y1_data,
                                'x2':x2_data, 'y2':y2_data,
                                'x3':[5,10,15], 'y3':[5,10,15], 'r3':[.5,.75,1]})

f = figure()
f.extra_y_ranges={"extra_y":Range1d(start=0, end=200)}
y2_axis = LinearAxis(y_range_name="extra_y")
f.line(x1_data, y1_data)
f.line(x2_data, y2_data)
f.add_layout(y2_axis, 'right')

f.circle(x='x3', y='y3', radius='r3', source=source, y_range_name='extra_y')

show(f)
```

**Comment by dyingoptimist** [comment]
putting
```
f.yaxis.bounds = (0,60)
```
makes the situation worse. I have put a few more scenario related to this issue here: https://github.com/dyingoptimist/bokeh/issues/1

**Comment by bryevdv** [comment]
Setting the axis `bounds` only tells the axis not to render itself outside those bounds, it does not set the range of the plot, of that you want, e.g:
```
f = figure(y_range=(0,60))
```
I just tested this and it works as expected. In general having multiple axes with auto-ranging `DataRange`  objects may be problematic for a few reasons, and I am not sure there is much we can do about it. I'd recommend setting the ranges explicitly as about when using multiple axes.

**Comment by jzybert** [comment]
I'm wondering if any progress was put into this issue after it was closed. I'm working on a plot right now that has two y-axes and one x-axis. I'm using the `DataRange1d` class specifically to make use of the `default_span` option. My goal is to have the plot at default ranges (1st y-axis at -200, 200 and the 2nd y-axis at -1000, 1000). What should happen is that the auto-range should only kick in when a streamed value exceeds those bounds. But the problem is whenever a value that should be plotted on the 2nd y-axis exceeds the bounds for the 1st y-axis, both axes begin increasing their range. Is there no way to have two distinct ranges without explicitly defining them with `start` and `end`?

**Comment by bryevdv** [comment]
As I stated above, the best practice with multiple ranges is to manage the range bounds explicitly. However, you can also try setting the `renderers` property of the the DataRange models so that they only range the specific glyphs you care about (by default the auto range any and all glyphs in the plot)

**Comment by jzybert** [comment]
Ah, thank you. Utilizing the `renderers` property I was able to achieve exactly what I was looking for.

**Comment by PierrePivert** [comment]
@jzybert Could you explain how you manage to get those 2 y_axis independent from each other, without having to specify and explicit start and end, but still with the auto-range behaviour when new data "out of the box" are added ?
