### ISSUE TITLE
Branching/Release process discussion

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#2199]
Need to clarify release branching strategy. Motivation: A few releases have had longer testing/build cycles and several PRs that were ready and could have been merged to master were stalled, waiting for the release to complete. Need a process that allows normal dev to continue separately while a release is pending. 

There are basically two proposals that I am aware of:
* Adopt something similar to git-workflow, where the tip of `master` is always the last release, and normal dev takes place off a `dev` branch. A longer example can be found here: http://travisswicegood.com/2015/03/18/workflow-with-git/  

* Alternatively, have a more defined policy for when to split off a (temporary) release branch. Presumably this should occur exactly with a  code freeze so that any release related hot fixes or doc/examples updates would go on the branch and normal dev could continue on `master`

Thoughts? @bokeh/dev @tswicegood @pzwang

**Comment by damianavila** [comment]
I would go with the second option... it is the less disruptive way taking in consideration our current workflow. Our "develop" branch is master... and we are used to push there... since the release is a less frequent event... it is easy to remember that you have to push the release-related PRs to the "release"  branch and you can keep pushing to master to go ahead in the development cycle...

**Comment by tswicegood** [comment]
I'm :+1: for option one (shocking, right?) :-)

The reason is that it provides a clear set of guidelines for where code should go and the direction it should flow.  I've come around on this over the years.  My initial reaction to git-flow was not good -- it felt too much like trying to bring over SVN+CVS semantics to Git.  The value in being able to understand what code is supposed to be where and what state its in is pretty valuable, though.

**Comment by almarklein** [comment]
Maybe I don't understand it completely, but the only difference between using branches "master"  (=develop) and "release" as @damianavila suggests instead of "develop" and "master" (=release), would be the naming, right? 

I mean, could we have the same system that @tswicegood proposes, except that master stays for development and we get a new branch for releases? To me that makes more sense too, because I'm used to thinking of "master" as the development branch.

**Comment by damianavila** [comment]
>would be the naming, right?

Yep... I guess @tswicegood point to some cognitive bias where develop makes direct reference to devel work... but there are a lot of people used to think master as the development branch...
I see value in what @tswicegood says... but I see more value if you are starting a project and not if you are in a project were master was always the devel branch...

**Comment by hhuuggoo** [comment]
the main value in my mind in having master be stable is that newcomers will clone master, and then be confused if stuff is broken (not that master should be broken regularly)

**Comment by almarklein** [comment]
People who want a release version should just conda- or pip-install it, IMO.

**Comment by fpliger** [comment]
I used to work with basically the same flow @tswicegood suggests. It was perfect for that context (saas /w CI/Continuous delivery). Honestly it too some time for me to change mindset (where master is sacred! :smile: ) but I think the current flow of using master "as dev" would work ok for now if we solve the problem regarding holding back dev waiting for the release. 

There is one thing I'm not sure I understand regarding option 2 (release branches) because as @damianavila described here seems a bit different from what I understood in previous discussions. In this case the proposal is to have a new release branch of [tied to] every release or to have a permanent "release" branch from where we tag and release?

**Comment by damianavila** [comment]
>In this case the proposal is to have a new release branch of [tied to] every release or to have a permanent "release" branch from where we tag and release?

You can have a temporary release branch or make it permanent... there is no big differences because the permanent one would be updated just before the code freeze. Unless you have branches for each release which is different to have just one release branch updated on every "release season".

**Comment by tswicegood** [comment]
The biggest value in a git-flow-based approach is the same one that an ORM offers: familiarity.  New developers are going to have to learn a lot whenever they start working with a code base, how to name branches, where they belong, what to branch off of, those are all things they shouldn't have to learn too.

Having one, solid workflow that everyone in the company uses would make it much easier for folks to easily contribute across all projects.  Given that git-flow has been proven to scale appropriately, that's my preference.  It keeps `master` with only released code and ensures that a hot fix that needs to happen can happen quickly without having to worry about what's been merged in.

**Comment by damianavila** [comment]
> Having one, solid workflow that everyone in the company uses would make it much easier for folks to easily contribute across all projects.

OK, if we are really going into this path... with ALL (or at least the majority of) the projects working in with the same procedures, I have no problems to change... because right now, besides the "familiarity" benefits you raised as support of the idea, I think the more moving reason is the protocols unification...

**Comment by tswicegood** [comment]
We should probably get @pzwang to weigh in on this.  I know we've talked about various processes before, but we haven't solidified around one yet.  I put together [this contributing][1] doc to outline the process I would like.

[1]: https://github.com/conda/conda-env/blob/develop/CONTRIBUTING.md

**Comment by bryevdv** [comment]
Agreed. On a purely conceptual level I love the idea of stabilizing as many CIO dev efforts as possible around a common or mostly common process but that's not a trivial task and it's a question whether the benefit outweighs the cost.

**Comment by almarklein** [comment]
I'm still wondering whether it would not be easier to do exactly that, except use `master` for development and have a continuous `release` branch. The point being that if you set-up git, the default branch to pull form is `master`, and if I make a PR on Github, the default branch to make the PR against is `master`. Also, of all people cloning the repo, I think most are interested in having the development version, not a release.

**Comment by almarklein** [comment]
(having said that, it would be more important to have things the same as all other repos, if that's the way we're going)

**Comment by bryevdv** [comment]
Well, we have had some recent experience with keeping a longer running `dev_0.10` branch around, for collecting work for a release further in the future. It seemed to work well enough. I think this combined with our standard procedure for crating a release branch at freeze is sufficient for now. @bokeh/dev any thoughts?

**Comment by damianavila** [comment]
I agree... we should probably open the release branch **early** in the release week so people is aware of that and push the hotfixes to this shared branch... but other than this. I think we are OK as is (with eventual dev branches if they are needed).

**Comment by bryevdv** [comment]
Ok, closing this for now, then.
