### ISSUE TITLE
Expose color and marker cycling to bokeh.plotting 

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2201]
Add more capability to compose palettes using the current implementation of cycle_colors available to charts

**Comment by bryevdv** [comment]
Some ideas, copied from #1790:

The `bokeh.plotting` API does not currently do color cycling. I think color cycling could be nice but we'd need to figure out a way to "spell" things so that i) users still have complete explicit control ii) backwards compatibility is maintained. A few ideas:
```
p.line(..., color=cycle())          # cycle a default palette
p.line(..., color=cycle("veridian") # cycle a specified palette
```
Another possibility might be some kind of global state on `bokeh.plotting`:
```
bokeh.plotting.color_cycle = "veridian"
```

**Comment by tonyfast** [comment]
There is a project called [Cycler](http://matplotlib.org/cycler/) from the matplotlib that might be helpful in this issue.  It was demo'ed recently at PyData NYC.

**Comment by bryevdv** [comment]
We already have a nice cycler, it's just not used anywhere outside of `bokeh.charts`

**Comment by VelizarVESSELINOV** [comment]
Global property to enable this smart color assignment it will be great.

I hope also the assignment of color will be smart enough to use the right palette for the number ```p.line(...)```.

Use-case 1: If there are 5 ```p.line(...)``` use default palette for 5 colors, if the are 20 ```p.line(...)``` use default palette for 20 colors.

Use-case 2: if the user assign ```p.line``` to be red and another green and 3 other to be auto assigned that the algorithm will pick a different colors than the two already used.

**Comment by bryevdv** [comment]
> Use-case 1: If there are 5 p.line(...) use default palette for 5 colors, if the are 20 p.line(...) use default palette for 20 colors.

I don't really see how this is possible for `bokeh.plotting` offhand, at least as described. In particular: there's no way to know ahead of time how many lines you will create. With `bokeh.charts` or possibly a pandas integration, this knowledge is known at a higher level and the choice can be made. The only route I could see would be to defer some kind of "fixup step" to serialization times that went in and tweaked things before emitting the JSON, but that would be a much more invasive and larger chunk of work. 

> Use-case 2: if the user assign p.line to be red and another green and 3 other to be auto assigned that the algorithm will pick a different colors than the two already used.

 If I'm using a palette with 4 green shades (among others) and I set one line to "green" what is the right thing to do? This seems like a research project. Can you point to existing implementations that could be used as a reference?

**Comment by rothnic** [comment]
For charts it is both cycling attributes, but more specifically it is assigning unique combinations of attributes to unique groups of data. So if you think about the pandas.DataFrame.groupby, it is using that internally to iterate at the lowest level of detail used in the chart, which comes from the columns used in the inputs to the chart. 

What charts can do is basically a sql-like join for each of the types of attributes you assign to one-to-many columns into a data source. So, I want to color on sex and age bins, then I want a marker based on disease. So each unique pair of sex/age bin would get a unique color (if enough are in the palette, otherwise it cycles), then each unique disease would get a unique marker (again, if enough exist, otherwise it cycles).

So, charts is probably working on a slightly different problem than cycler, which seems to be more just a stand-alone generator of combinations of things. You'd have to manually handle what they are representing.

See this [Charts Deep Dive - Attributes](https://notebooks.anaconda.org/nroth/deep-dive-attributes) notebook for a walkthrough of some of the charts internals.

**Comment by VelizarVESSELINOV** [comment]
I don't expect the color to be assigned during p.line(...) command, but during the show(p) command that is already aware how many lines are inserted and need to display in the legend and if some fixed colors are already assigned or not.

**Comment by bryevdv** [comment]
Yes, that's the possibility I outlined regarding serialization. I would expect something simpler, first. Anything changing the serialization machinery will require much more extensive testing and development.

**Comment by rothnic** [comment]
It would be nice to register a column in a ColumnDataSource to be supplied by this cycler, which is an alternative to what is in charts currently. The ColumnDataSource would call back to the cycler, which could be some pre-build functionality on the JS side (map between values and color), or a javascript custom callback, or a callback to the python side.

The logic could assign colors based on each row, or the value in some column, or whatever other logic was defined. Assigning colors based on the row would be the same as the line example if using the MultiLine and a data source.

I think automatically cycling something based on the count of the glyphs in the chart would only be useful in simple cases. Typically you don't want to color on the count of glyph objects because that is dependent on the API for defining them. You really want to color on the data that the glyph represents.

**Comment by bryevdv** [comment]
@rothnic just FYI being able to define models the represent column transformations (including color mappings) and ship those to BokehJS to actually be done is high on my priority list after `0.11`

**Comment by stvn66** [comment]
As this issue seems to be stale, and issue #351 has been closed, I submit it would be helpful to provide an example similar to this [SO post](http://stackoverflow.com/a/39840381/3585557) in the documentation to demonstrate how one can use the `bokeh.palettes` with itertools to cycle colors when plotting.  @bryevdv's first comment on #351 makes it seem plotting several lines should by default cycle through different colors but that was not the behavior I experienced.

**Comment by bryevdv** [comment]
So, now that we have JS transforms supporting things like color mappers, what I think we can do is this as by having `cycle` here:
```
p.line(..., color=cycle())    # cycle a default palette
p.line(..., color=cycle())    # cycle a default palette
```
Return a global *transform*, that will be the same for all glyphs configured with it, that will do the cycling on the JS side. That actually seems straightforward. The downside would be that the chosen colors would not be available on the Python side. I think if you need that, you just cycle colors yourself.

**Comment by bryevdv** [comment]
Once https://github.com/bokeh/bokeh/issues/5884 it would make sense to have a transform that cycles marker types as well

**Comment by bryevdv** [comment]
I am going to close this with `noaction`. There has not actually been any discernable demand for it all these years, the problem itself as discussed here is underspecified and contentious, and it would pose technical difficulties. On top, there are now things like categorical and continuous color mappers, as well as a marker mapper for the scatter glyph.
