### ISSUE TITLE
Bokeh Server deployment: config.py very fragile

### ISSUE THREAD

**Issue by bkreider** [bokeh/bokeh#2219]
When deploying config.py is very easy to get wrong and the error is inscrutable and completely wrong.  

For example, a bad config like the following one will result in a gunicorn error: 
"AppImportError: Failed to find application: 'bokeh.server.start'
```python
pub_zmqaddr   = "ipc:///tmp/0"
sub_zmqaddr   = "ipc:///tmp/1"
run_forwarder = False
model_backend = {'start-redis': False, 'type': 'redis', 'redis_port': 7001}
secret_key    = adffw9j3223fygt
multi_user    = True
```

Because secret key is not quoted, it will raise a NameError which is caught by gunicorn while loading the wsgi application.  Here is the gunicorn loading code:
```python
try:
        app = eval(obj, mod.__dict__)
except NameError:
        raise AppImportError("Failed to find application: %r" % module)
```

I propose two enhancements:

1.  Configuration loading needs to handle exceptions better no matter what format is used.  The configuration is user generated, so the code should expect many fat-fingered errors.  How can we make it easy for users to converge on their mistakes?

2. A python file for configuration isn't very robust.  This isn't a big deal if errors are reported, but something like yaml would be forgiving if one doesn't quote strings.  I'm agnostic to actual format as long as it is robust.  I've had other "gunicorn" errors when not quoting the zmq addresses.

**Comment by hhuuggoo** [comment]
so we definitely need better error messages for when the config doesn't parse.  I disagree that the config parsing should be robust - I think configs should be precise and fail clearly when they are wrong.  For example we once blew up a simulation on release day because a list looking like this (in yaml)

exlude_ids = [234234234,23423424,4234234]

when the list should have been

exclude_ids = ["23423423423423","234234234234","234234234"]

and we never noticed this problem before because our iDs from a different system looked like

exclude_ids=[a2329090923, b23203923] causing yaml to interpret them as strings vs ints

**Comment by bkreider** [comment]
>  I disagree that the config parsing should be robust - I think configs should be precise and fail clearly when they are wrong.

I could be happy with fail clearly, but it would be nice to not have to quote everything.  The functions should know if they need a string or an int.  If someone passes in a string "foobar" where they needed an int, it seems like the same as passing in an invalid int value (ie: -10 for a timeout) or the reverse.

**Comment by bryevdv** [comment]
Will hopefully address this in new server work.
