### ISSUE TITLE
examples/plotting/server/remote_image.py broken on windows

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2294]
Raises the following error:

```
Using saved session configuration for http://localhost:5006/
To override, pass 'load_from_config=False' to Session
Traceback (most recent call last):
  File "../../examples/plotting/server/remote_image.py", line 23, in <module>
    source.from_blaze(d.array, local=True)
  File "C:\Anaconda\envs\py27_conda_clean\lib\site-packages\blaze\expr\expressio
ns.py", line 165, in __getattr__
    result = object.__getattribute__(self, key)
AttributeError: 'InteractiveSymbol' object has no attribute 'array'
```

**Comment by azjps** [comment]
Any luck with this issue? Seems to be OS-independent (getting same errors on linux with python 2.7.6, bokeh 0.9.0-20-g480614f, blaze 0.8.0); I get similar errors when trying to retrieve data from any of the example blaze clients (remote_image, serversource, abstractrender, etc).

**Comment by azjps** [comment]
Hmm, so I'm able to get some examples running by starting bokeh-server with (from the bokeh git root)

```bash
python bokeh-server -D bokeh/server/blaze/config.py -v
```

instead of

```bash
python bokeh-server -D remotedata -v
```

I'm assuming this is something that got changed in [this pull request](https://github.com/bokeh/bokeh/pull/1713) that never made it to documentation (i.e. tests/travis/TESTING.md). Unfortunately even after this abstractrender.py just shows empty plots. Am I missing something really obvious here? It doesn't seem to help that "-D remotedata" is used by all of the similar github issues regarding problems with these examples, although that argument makes no sense since multiuserblazeserver tries to load it as a python module.

**Comment by damianavila** [comment]
Previous milestone: 0.9.1

**Comment by fpliger** [comment]
we don't have this example (and bokeh-server) anymore. If there's any related issue with the new server it's worth opening an new issue anyway.
