### ISSUE TITLE
specify arbitrary axis value labels for categorical plots

### ISSUE THREAD

**Issue by jianli** [bokeh/bokeh#2299]
It seems like the only axis value labels that can be displayed are ones that correspond deterministically to the values themselves. As far as I can tell, some `TickFormatter` classes also exist that only display every n values, or format the dates in a certain way.

But sometimes the user would like more control over this. For example:

<img src="https://cloud.githubusercontent.com/assets/1527821/7647795/feed3de0-fb1d-11e4-9f0b-eb55fa6b8868.png" width="200px"><img src="https://cloud.githubusercontent.com/assets/1527821/7647794/feebdcd4-fb1d-11e4-809d-15ee7107a6e6.png" width="200px"/>

I have a [hacky implementation](https://github.com/bokeh/bokeh/compare/master...jianli:custom-tick-labels?expand=1) that lets the user pass in arbitrary labels along with the axis values, which is what generated the plot on the right. However, it doesn't seem like the right way to do it, and I don't know if y'all are already working on a more general solution.

**Comment by bryevdv** [comment]
This could be implemented with a custom `Ticker`, or possibly a custom `TickFormater`. There is an example of the latter at: https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/custom_datetime_axis.py

Closing this for now, since it is more of a support question (please feel free to pose it on the mailing list)
