### ISSUE TITLE
Different sizes not used for selection & nonselection glyphs

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2367]
See the example here:

http://nbviewer.ipython.org/github/birdsarah/bokeh-miscellany/blob/master/notebooks/Different%20size%20for%20selected%20%26%20not%20selected%20demo.ipynb

Simplified for clarity:

``` python
    nonselection = Circle(x='x', y='y', fill_color='gray', size=5)
    selection = Circle(x='x', y='y', fill_color='red', size=25)
    plot.add_glyph(source, nonselection, selection_glyph=selection, nonselection_glyph=nonselection)
```

The size that is used is whatever is passed as the second argument to add_glyph.

**Comment by bryevdv** [comment]
Current behavior is as designed and documented, i.e. only "visual" (line and fill) props are considered for selection/nonselection/hover policies. Changing to `feature` to reflect that it would be new feature development.

**Comment by bryevdv** [comment]
An alternative short-term help would be to issue a validation warning

**Comment by mattpap** [comment]
This is a recurring problem when creating more complex visualizations. Recently I was bit by this in PR #4312, where I wanted to make pie chart's selected slice to stand out, but I can't change selection annular wedge's x, y coordinates, because those are bound to the main glyph.

My proposal is to change definition of `GlyphRenderer` class to:
```
class GlyphRenderer(DataRenderer):
    glyph = Instance(Glyph)
    selection_glyph = Instance(Either(Glyph, Visuals))
    nonselection_glyph = Instance(Either(Glyph, Visuals))
    hover_glyph = Instance(Either(Glyph, Visuals))
```
where `Visuals` is a base class that would be implemented by `<GlyphName>Visuals`. Using `Visuals` instead of a `Glyph` would retain the current, data sharing, behavior. However, using a `Glyph` would mean `GlyphRenderer` would perform all data mapping independently of `glyph`. I think glyphs could implement `Visuals` to reduce code duplication.

**Comment by bryevdv** [comment]
noting that this would fall out of #10403 as I envision it at least
