### ISSUE TITLE
Alerts for the "white screen of death"

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2392]
Sometimes your python code runs without errors, but the plot is empty. You need to know/remember to got the console to figure out what went wrong.

It would be great if we had some kind of warning, or flag to get warnings about this.

ping @mattpap @canavandl

**Comment by birdsarah** [comment]
ping @mistakevin

**Comment by hargup** [comment]
+1 to the issue, it is especially annoying when you are new to Bokeh plotting and can't figure out why is your code not working.

**Comment by mistakevin** [comment]
Simple pop up in PR https://github.com/bokeh/bokeh/pull/2404. Are there any specific feature requests?

**Comment by birdsarah** [comment]
@mistakevin #2404 looks good. I'm excited to try this out before listing out things that may be nice (but may be over-thinking things).

**Comment by chdoig** [comment]
Related to the "white screen of death" is issue #2424. In that case the console displays no error message. I narrowed down the problem to nans in your datasource when using the server. It was really frustrating to debug since there was no error or warning message anywhere. It would be nice to check for `nans` in the data source and display a warning/error message too.

**Comment by damianavila** [comment]
>It would be nice to check for nans in the data source and display a warning/error message too.

Maybe is too narrow target... but probably there is no way to specify a common pattern since the problem can come from several and different sources... so maybe the best we can do is starting to catch some know cases, like the NaN... but not sure it is the correct path...

**Comment by mistakevin** [comment]
After trying many different approaches, the cleanest solution to, at least, a large subset of catalysts for the issue is to simply include the `allow_nan=False` option (documented [here](https://docs.python.org/3.3/library/json.html#basic-usage)) in our `json.dumps()` call. This will better ensure that our output is JSON compliant. This will give the user a `ValueError: Out of range float values are not JSON compliant` in the terminal. 

I believe we can't necessarily just build a better JSON decoder on the front-end, as the JSON breaks during parsing before our Javascript gets a hold of it, hence the absence of a Javascript error and the Python's JSON encoder ironically encodes `NaN`, `Infinity`, and `-Infinity` as themselves (see [here](https://docs.python.org/3.3/library/json.html#json.JSONEncoder)) for use in Javascript, not JSON.

This would put the burden on the user to scrub the data. A tweak to @chdoig's script could look like this:
```
from bokeh.sample data import us_states, us_counties, unemployment
from bokeh.plotting import figure, show, output_server
import math

us_states = us_states.data.copy()
us_counties = us_counties.data.copy()
unemployment = unemployment.data

del us_states["HI"]
del us_states["AK"]

state_xs = [us_states[code]["lons"] for code in us_states]
state_ys = [us_states[code]["lats"] for code in us_states]

county_xs = [us_counties[code]["lons"] for code in us_counties if us_counties[code]["state"] not in ["ak", "hi", "pr", "gu", "vi", "mp", "as"]]
county_ys = [us_counties[code]["lats"] for code in us_counties if us_counties[code]["state"] not in ["ak", "hi", "pr", "gu", "vi", "mp", "as"]]

# Scrub data here
check_list = [state_xs, state_ys, county_xs, county_ys]

for idx1, x in enumerate(check_list):
    for idx2, y in enumerate(check_list[idx1]):
        for idx3, z in enumerate(check_list[idx1][idx2]):
            if z is None or math.isnan(z):
                check_list[idx1][idx2][idx3] = 'NaN'

colors = ["#F1EEF6", "#D4B9DA", "#C994C7", "#DF65B0", "#DD1C77", "#980043"]

county_colors = []
for county_id in us_counties:
    if us_counties[county_id]["state"] in ["ak", "hi", "pr", "gu", "vi", "mp", "as"]:
        continue
    try:
        rate = unemployment[county_id]
        idx = min(int(rate/2), 5)
        county_colors.append(colors[idx])
    except KeyError:
        county_colors.append("black")

output_server("choropleth")

p = figure(title="US Unemployment 2009", toolbar_location="left",
    plot_width=1100, plot_height=700)

p.patches(county_xs, county_ys, fill_color=county_colors, fill_alpha=0.7,
    line_color="white", line_width=0.5)
p.patches(state_xs, state_ys, fill_alpha=0.0,
    line_color="#884444", line_width=2)

show(p)
```

And lastly, I see that we have tried to extend `json.JSONEncoder`, but I'm not sure how far down the rabbit hole we want to go there.

ping @damianavila @bryevdv @birdsarah

**Comment by damianavila** [comment]
See @bryevdv comment here: https://github.com/bokeh/bokeh/pull/2445#issuecomment-115396400
I completely agree... so moving the milestone to short term... this is not something we can solve before the release...

**Comment by birdsarah** [comment]
I'm closing this issue, as the new validation framework gives us a way to add individual ones as they come up.
