### ISSUE TITLE
External charting libraries

### ISSUE THREAD

**Issue by carlskii** [bokeh/bokeh#2409]
Hi, is it possible to use bokeh with the Highcharts libraries ?

**Comment by bryevdv** [comment]
Hi Carl that's a very broad/vague question. Can you explain what you'd like to actually do? In general Bokeh is an alternative/competitive library, so the answer is probably "no" but it would be good to understand exactly what you want to accomplish.

**Comment by datnamer** [comment]
Maybe carl means something like this: http://www.htmlwidgets.org/

**Comment by carlskii** [comment]
Yes - that's the sort of thing I'm referring to, highcharts provides a some very rich data visualisations with an easy to use API. It wasn't obvious that as to whether Bokeh could mimic that level of richness.

Carl

**Comment by datnamer** [comment]
I would tend to agree...whether bokeh can or can't, it will never be able to match every corner case of every JS library. I think having a capability to wrap arbitrary JS libraries would be huge.

**Comment by bryevdv** [comment]
So, we are currently in the process of splitting up BokehJS, and one part of that is that the object model will become extensible, in that people can add new python models and also supply the backbone model/view that it needs to use on the JS side. When this is done, people can do basically what you say, integrate whatever libraries they want. For instance we might continue to provide a (now split-off) default Bootstrap widget set, but others could develop new ones around different libraries.

**Comment by bryevdv** [comment]
Also FYI, this work is targeted for introduction in 0.10 but it is just starting, and we have not set timelines yet.

**Comment by datnamer** [comment]
Cool, looking forward to that!

**Comment by hhuuggoo** [comment]
@datnamer what do you mean wrap arbitrary js libraries?  do you mean automatically provide python interfaces for other js libraries?

**Comment by bryevdv** [comment]
My interpretation: I want a slider. I don't want a bootstrap slider.

**Comment by datnamer** [comment]
@hhuuggoo Automated generation would be amazing, but not sure if that is technically feasible. Minimal use JS like in HTML widgets is almost as good, but not sure if it uses crazy R meta-programming. Really any variant of this capability will be amazing. 

@bryevdv I'm not sure what you mean about a bootstrap slider vs regular slider (I don't know any JS, which is why I'm backing this issue:) ), but if you mean "Bokeh is awesome but there is this  specialized JS library I would like to also  use in my app or import into ipynb. I would like to plug it into bokeh for use from python with a bit of JS" then yes :)

There is so much energy in the JS right now and I think it would be great to harness that. I also think it would help bokeh proper focus on its core competencies and reduce maintenance burden.

**Comment by bryevdv** [comment]
various aspects of this are currently WIP, I think the discussion has run its course (re-open if there are other things to discuss)
