### ISSUE TITLE
DatetimeTickFormatter format attr ignores %n %t chars

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#2413]
When creating custom formats for a DatetimeTickFormatter, the strftime conversion specifications of %n (return line) and %t (tab) are ignored in the rendered tick label.

For example, all three following combinations yield the same label:
```python
format1 = {"year" : ["%Y%m%d %n %H%M%S"]}
format2 = {"year" : ["%Y%m%d %t %H%M%S"]}
format3 = {"year" : ["%Y%m%d %H%M%S"]}
```

This requires either a bugfix or updating the docs to reflect that %n and %t are not valid conversion specs.

**Comment by azjps** [comment]
Not really related to DatetimeTickFormatter, which I believe does do the correct %n -> \n and %t -> \t conversions, but apparently instead an issue with newlines in html canvas: [#994](https://github.com/bokeh/bokeh/issues/994).

**Comment by bryevdv** [comment]
completed with doc update for now

**Comment by anderl80** [comment]
Will this be working in future?

**Comment by bryevdv** [comment]
Hard to say. There was a PR that was started but then closed to add support for line breaks for categorical axes: https://github.com/bokeh/bokeh/pull/8445 That's definitely something we intend to get working in the near-ish future as time and resources permit. That work might be transferrable to DatetimeTickFormatter in some way, with a little work, but it would take some investigation. A simpler path, rather than adding to the already complicated `DateTimeTickFormatter` might be to make sure line creaks work for `FuncTickFormatter` instead.  Then users could create any custom multi-line ticks they want, for date times or otherwise.
