### ISSUE TITLE
Font size in data units

### ISSUE THREAD

**Issue by jcrist** [bokeh/bokeh#2439]
I'd like to be able to set the font size in data units, so that it gets bigger when I zoom in, and smaller when I zoom out. For large figures with data labels, this would be useful for interactive exploration by zooming/panning around the figure. Perhaps there could be a minimum size where it doesn't render at all, since no one could see it.

**Comment by bryevdv** [comment]
see also: #1883 

I agree about the general idea, but I think there are some specifics to work out. I'm not sure it's a matter of "data units" as much as it is of "scale appropriately" from initial size to new sizes (or remain unscaled). So it seems more like a kind of flag. But there are questions: should this be available on the current `text` glyph, or should the behaviour be reserved for some kind of (new) annotation class? both? Also as always, the impossible question: when zooming does not preserve expect, how do you scale "appropriatey" ?

**Comment by bryevdv** [comment]
I think this would be difficult expose cleanly. I think there are too many policy possibilities, e.g. use one axis size for scaling? which one? some combination of both? how to combine sizes? policies for min/max/hiding? Basically just a hard to test and maintain explosion of combinations of knobs and dials for something that is not ultimately that common (it seems).

By contrast, it's not possible for users to add `CustomJS` callbacks (or python callbacks with server apps) to respond to axis dimension changes, to implement whatever text scaling they'd like, in a line or two of code. I think that much sufficient and much preferable.

**Comment by tvt173** [comment]
I would think a single attribute i.e. "text_height" would be sufficient for this to cover most use cases, no?

If set, sizing would be relative to data, with the given height (in data space). I think generally the user is more interested in setting the height than the width of the text, since total width is generally variable with the content of the text anyways, and setting both would distort.

Alternatively, maybe you could implement an alternate glyph/annotation type specifically for these kinds of labels? 

I think there are definitely use cases for this (i.e. when you want text in a box, or you have lots of labels in a big map).

**Comment by DogRandom** [comment]
I also am looking to use this feature.    Text sized in data units, and not scaled with zoom.
A minimum size clipping function to stop rendering altogether.

**Comment by bryevdv** [comment]
This issue is specifically asking  for text that *does* scale. Also in don't know what "a minimum size clipping function to stop rendering altogether" means at all

**Comment by DogRandom** [comment]
re:" what does clipping mean"
I meant when zoomed out far enough that 'data size text' is essentially below the screen resolution, don't render it.  

re: wrong place for comment

Well, I think we are just using different frames of reference.  I want to be able to zoom in and out and have the text be the same size in data units.   From the rendering point of view yes the text should scale at the same proportions as the rest of the plot when zoomed.

**Comment by whyboris** [comment]
An example use case where this would help:

![image](https://user-images.githubusercontent.com/17264277/44467607-4e0d5c80-a5f1-11e8-9fb8-de2a2b12fa20.png)

In this data set, when looking from far away I'd rather not see any text labels -- just the point cloud.
But when I zoom in, at some point it would be good to again see the text labels.

I understand that there are default policy choices to make about when the breakpoint would occur. Also, zooming in very close to the points shouldn't make the text gigantic. 

I wonder if it would be sufficient to simply implement a `hide labels below this zoom level` variable -- avoiding the headache of resizing text to larger or smaller?

**Comment by bryevdv** [comment]
Bokeh has no notion of "zoom level". There is just the range start/end, whatever they are (and which can change independent per axis), and a canvas size. What size to draw is an ill-defined and hard to specify function of all of those things. 

The problem is:

* theres more than one kind of policy (several have been asked for in this thread alone)
* none of them would be easy to implement and none would satisfy everyone
* this is not a common use case in my observation

So, if someone wants to implement a specific solution that satisfies their needs, I am happy to consider it. It's just not something the core team will be able to prioritize, *especially* since, as stated above:

* it's possible to use `CustomJS` or python callbacks (in a bokeh server app) to effect any arbitrary policy for showing, hiding, or resizing text that you might want.

**Comment by sigurdurb** [comment]
Wanted to add an example on how to change the font size with `CustomJS`
Lets say you have a LabelSet that has a text_font_size property.
labelset = LabelSet(some code)
labelset.text_font_size = "400%"
You can then send that as a CustomJS(args=dict(labelset=labelset),code=open(join(dirname(realpath(__file__)), "text_change.js")).read())
Then this could be the content of text_change.js
```
labels.text_font_size = "100%"
labels.change.emit();
```
