### ISSUE TITLE
Selenium Testing w/ Browserstack

### ISSUE THREAD

**Issue by mistakevin** [bokeh/bokeh#2528]
Using Selenium Webdriver along with the Selenium IDE and [Browserstack](browserstack.com) gives a great workflow for testing in the browser. The [Selenium IDE](http://docs.seleniumhq.org/download/) (scroll down until you see "Selenium IDE") is a FireFox add-on that lets you record actions in the browser and assert elements are present by locating and interacting with DOM elements:
![screen shot 2015-07-08 at 12 37 37 pm](https://cloud.githubusercontent.com/assets/4411115/8577419/2bacc100-256e-11e5-8b2d-68fd5d7370d3.png)
This will export python code. With a few adjustments for browserstack, will look like [this](https://github.com/bokeh/bokeh/blob/mistakevin/feature/selenium/bokeh/tests/selenium/test.py)

Then when ran you are able to watch a visual log (or actually interact with!) the test as it is happening on browserstack.com:
![selenium](https://cloud.githubusercontent.com/assets/4411115/8577505/c483536c-256e-11e5-9b5a-a1591ee07a71.gif)

As well as in the terminal:
```
12:23 $ python bokeh/tests/selenium/test.py
.
----------------------------------------------------------------------
Ran 1 test in 15.321s

OK
```

We can set this up on our own without browserstack. In the past, I have used [CircleCI](circleci.com) for all testing by launching a selenium server and actually making a video recording of the DOM interaction, viewable for every build. The selenium server is clunky though, and setting it up with multiple versions of multiple browsers on multiple OSs would be a nightmare, which is where browserstack comes in. Browserstack also supports local testing as seen in the gif.

**Comment by mistakevin** [comment]
ping @birdsarah @mutirri

**Comment by damianavila** [comment]
I would love to see how this evolves... :wink:

**Comment by birdsarah** [comment]
Hi @mistakevin, this is fascinating, thanks for sharing. Some thoughts. Some in response to your post. Some others that have been kicking around for me on the same topic.
---
### Browserstack vs Saucelabs

Easy one to start with - I am very open on this, just noting it down.

> The selenium server is clunky though, and setting it up with multiple versions of multiple browsers on multiple OSs would be a nightmare,

+10000 on this

> which is where browserstack comes in.

Personally, my go to would be Saucelabs (https://saucelabs.com) for the following reasons:
* They offer free testing to open source projects - https://saucelabs.com/opensauce/
* They are a core contributor to selenium
* I see them as a general pro open-source / positive community member (they sponsor selenium meetups, I see them at Pycon etc.)
* ~~pytest-selenium (see below)~~
* Appium (see under testing canvas below)

---
### pytest-selenium

pytest-selenium - https://github.com/davehunt/pytest-selenium - is a plugin for pytest that I've used a little and contributed to a little. There may well be other things out there like it, I just know this one.

We have mentioned switching to pytest in Bokeh before and someone, I believe, already demonstrated, that all the current tests run under pytest.  Regardless, I think our selenium tests can & should be treated as a seperate collection and can be pytest.

I had initially thought that using pytest-selenium with another reason to be pro saucelabs, but I see they've added browserstack integration!

pytest-selenium has the following nice features:
* boiler plate of setting up web drivers
* boiler plate of connecting to saucelabs or browserstack and reporting back failures
* friendly html report (which can include video playback) e.g. https://webqa-ci.mozilla.com/view/Buildmaster/job/marketplace.dev.developer_hub/lastFailedBuild/HTML_Report/ or https://webqa-ci.mozilla.com/job/affiliates.dev.saucelabs/268/HTML_Report/

---
### IDE vs Handwritten (w/ PageObject pattern)

I have never really used Selenium IDE, when I first got started with Selenium, the general message I got from the internet was: http://stackoverflow.com/a/19683493 and so I never really tried it.

As a result, I am much more familiar with the PageObject pattern for building up a series of selenium tests - where you abstract your web page into a class with methods on it, and all your tests call those methods. This abstracts away any changes to page markup and hopefully improves maintainability. While this is very important for web applications, with lots of pages, and ever changing markup, I can see how it might not be important for Bokeh. 

Were you actively proposing IDE over structured handwritten tests? I'm keen to hear more thoughts on this. There's a trade-off between the cognitive load of the abstraction and the readability of an individual test.

With pytest-selenium and the PageObject pattern in hand, you can have complex tests, that read easily e.g. (taken from mozilla's marketplace tests)

````python
    @pytest.mark.skipif('True', reason='Sort not available yet.')
    @pytest.mark.parametrize(('sort_type'), ["Relevancy", "Rating"])
    def test_that_verifies_the_sort_region_from_search_results(self, selenium, sort_type):

        home_page = Home(selenium)
        home_page.go_to_homepage()

        Assert.true(home_page.is_the_current_page)
        search_page = home_page.header.search(self.sort_search_term)
        Assert.equal("Relevancy", search_page.sorted_by)
        Assert.true(search_page.is_sorter_header_visible)

        # Test that the filters are applicable on the results
        search_page.sort_by(sort_type)
        Assert.equal(sort_type, search_page.sorted_by)
        Assert.greater(len(search_page.results), 0)
````
and, if well constructed, should be reasonably robust over time.

On the flip side, there's MUCH more initial setup and new patterns & libraries to learn than the point and click of IDE, which I think is very accessible.

Some relevant questions: How many tests do we think we'll be maintaining (multiple per example)? Are we expecting this to be developed and maintained by core or community contributed?

---

### Separate site of examples to test against

I had an idea for the selenium testing that may solve two problems in one go
1) proper web testing of bokeh (of course)
2) have a gallery of all of our examples 

We have an outstanding issue (#1032) to make better use of the examples. And I know I often answer questions on the mailing list where there is an answer buried in the examples somewhere.

My vision would be to "auto" generate a site out of the examples / re-purpose the examples directory into an app. This may or may not live in a seperate repo (I know @bryevdv is a fan of monolithic repos).

Just like our docs site, I imagine a latest one which is running with the latest build, and a dev / staging one that is running the bleeding edge. Although the full selenium tests could be run locally, this would be very slow (as the examples tests already are). The selenium tests could be run, say, daily against fresh deploy of master. I can imagine a number of different pipelines that would work for us, and my goal would be that we end up with a faster test suite in the bokeh-core because testing of all the examples moves out, but testing of core functionality moves in.

I also think we could use a build like this to run a series of tests against our live docs site to ensure it's behaving as expected.

(I'm aware this is a bit vague at the moment, but hopefully you get the gist of it)

--- 

### Testing canvas

Maybe you've figured this out already, but the big scary monster in the room - testing canvas. Selenium can't do this for us. It can only access dom objects, so it can't hover over a specific point on a plot.

I'm still considering setting up a robot to physically move a mouse over a page to check the hover / tap action! This is a really interesting problem, the I think is worth thought before we get too far down designing our selenium setup.

I am hoping to talk to @davehunt the author of pytest-selenium about this if he has any good ideas.

My thoughts include:
- splitting up the canvas overlay into addressable chunks for testing, and crafting test examples around that.
- looking at what test hooks we'd need to do this manually and decide how much we'd be testing tests vs testing bokeh.
- appium - https://github.com/appium/ & http://appium.io/ an open source project from saucelabs - that  provides "cross-platform test automation tool for native, hybrid and mobile web apps, tested on simulators (iOS, FirefoxOS), emulators (Android), and real devices (iOS, Android, FirefoxOS)." - aside from being able to test our touch interactions, what's got me excited is this line of code: https://github.com/appium/sample-code/blob/master/sample-code/examples/python/android_complex.py#L88 - we can specify a press by screen units. Although this is for a mobile touch event, appium is basically selenium, and its hinting to me that someone has solved the problem of "seeing what happens when you put your cursor in a specific place." 

---

I think that's most of my brain dumped for now.

**Comment by mistakevin** [comment]
Saucelabs would be a great alternative, and pro-opensource is always a great stance. Browerstack also has [free testing for open source projects](https://www.browserstack.com/accounts/subscriptions).

I was initially pulled toward Browserstack due to the [local testing](https://www.browserstack.com/local-testing) feature, keeping all of us developers from having more environment setup, and being able to rapidly test our branch on demand. Though I just saw that Saucelabs also shares that [functionality](https://docs.saucelabs.com/reference/sauce-connect/)!

At my last job, we had a non-programming QA team that we taught how to use the Selenium IDE. We ran PHPUnit tests which (awesomely) ran native Selenese 1 (HTML) tests. These worked about 95% of the time on the Selenium Server, and the main issues we had were timing related (selenium does not integrate with javascript, so no callbacks) and were largely patched by adding a few millisecond pause.

Though, we should definitely keep to tweaking in python. The workflow I was thinking was to build out the skeleton test in the IDE, export it to python, and tweak it while remotely testing our branch.

Also, Saucelabs makes a [Selenium Builder](https://docs.saucelabs.com/reference/selenium-builder/) extension for FireFox that builds Selenium 1 & 2 and can [run it remotely](https://docs.saucelabs.com/reference/selenium-builder/#running-scripts-on-sauce-labs) with a click of a button without exporting anything, so that you can test faster before ultimately exporting to python.

As for testing canvas, we can dive into [fabric.js](http://fabricjs.com/) which features a Canvas-to-SVG parser. SVG elements would be Selenium testable, and would offer the feature to users to export to SVG. But I'm not sure how much of a work it would take to convert our existing canvas infrastructure.

**Comment by bryevdv** [comment]
re: canvas testing. There's a div wrapper around the canvas. Does selenium not support absolute positioning the pointer within DOM elements?

**Comment by birdsarah** [comment]
> These worked about 95% of the time on the Selenium Server, and the main issues we had were timing related (selenium does not integrate with javascript, so no callbacks) and were largely patched by adding a few millisecond pause.

Indeed! Have you ever used custom waits like these

```python
    def wait_for_element_present(self, *locator):
        count = 0
        while not self.is_element_present(*locator):
            time.sleep(1)
            count += 1
            if count == self.timeout:
                raise Exception(*locator + ' has not loaded')

    def wait_for_element_visible(self, *locator):
        count = 0
        while not self.is_element_visible(*locator):
            time.sleep(1)
            count += 1
            if count == self.timeout:
                raise Exception(*locator + " is not visible")

    def wait_for_ajax(self):
        count = 0
        while count < self.timeout:
            time.sleep(1)
            count += 1
            if self.selenium.execute_script("return jQuery.active == 0"):
                return
        raise Exception("Wait for AJAX timed out after %s seconds" % count)
```

> At my last job, we had a non-programming QA team that we taught how to use the Selenium IDE. We ran PHPUnit tests which (awesomely) ran native Selenese 1 (HTML) tests. 

Very cool about PHPUnit

Am happy to take your lead on IDE. Also worth saying I have never maintained selenium tests for a project the size of Bokeh.

@bryevdv - I didn't think so, but that would be great, I've never had to write a test where I tried to do this.

**Comment by mistakevin** [comment]
@bryevdv I could not get mouse positioning to work

**Comment by birdsarah** [comment]
@mistakevin, was just thinking through some of your comments some more and this one stuck out.

> I was initially pulled toward Browserstack due to the local testing feature, keeping all of us developers from having more environment setup, and being able to rapidly test our branch on demand. Though I just saw that Saucelabs also shares that functionality!

I have used Browserstack tunnel for testing a lot, when trying to pinpoint, say an IE8 bug or something. It's cool that saucelabs has got this too now. I'm probably missing something - how does the local testing relate to selenium?

**Comment by mistakevin** [comment]
@birdsarah You can't really tell from the gif above, but I'm forwarding my ports from my local machine (localhost:8000) to Browserstack and running the python unittests containing the selenium commands from there.

**Comment by birdsarah** [comment]
sweet! i have not done that before!

**Comment by mistakevin** [comment]
After researching Sauce Labs as a possible alternative, I was able to pretty much mirror the functionality in Browserstack. To summarize, we can:
* Test locally by port forwarding and running our tests on their machines, pretty much keeping us from having to change/normalize our environments
* Can integrate with our current tests and TravisCI
* Can build tests in the browser with the Selenium IDE or Selenium Builder (firefox plugins)
* 100% python
* Free for open source
* Both services offer plans for interactive vm testing in multiple os/browsers/versions

In my personal opinion, Browserstack seems more polished and a little faster. Their docs also seem easer to peruse.

Where do we want to go from here?
* Get a subscription?
* Start a testing branch?
* Get to testing?

@bokeh/dev

**Comment by mistakevin** [comment]
see https://github.com/bokeh/bokeh/issues/2628 for canvas testing

**Comment by bryevdv** [comment]
We now have implemented a Selenium testing framework (thanks @birdsarah!) I think this can now be closed, and any future bugs or features can go in new, specific issues.
