### ISSUE TITLE
Open source GMapPlot replacement

### ISSUE THREAD

**Issue by avanetten** [bokeh/bokeh#2574]
Would it be possible to overlay data on a map background other than Google Maps?  The GMapPlot option is pretty great, but an open source maps implementation such as Leaflet would be far more usable for many reasons.  

Even better would be to also support the Leaflet.draw plugin which allows the user to draw polygons atop the map.  As far as I can tell, drawing a polygon atop a GMapPlot without any data points added is not possible (one has to draw a grid of translucent data points and use PolySelect).  Communicating Leaflet objects or points back to python/Bokeh would be very beneficial as well. 

Maintaining support for Leaflet event listeners within Bokeh would likely be tricky, but could be very useful.

**Comment by bryevdv** [comment]
We are in the process of making the Bokeh Model system extensible, so that new models can be created and used (and to be able to split BokehJS up into smaller and optional components). Once this is done (hopefully not more than a few months) it will be alot easier to add and test new components like this in a self-contained way. 

That said, it would probably be possible to overlay a transparent canvas on top go a leaflet element, but coordination night be tricky (and almost surely require some JS coding to support). 

I do think you could draw polys on Bokeh canvas tho. See this example in the user's guide for some inspiration:

http://bokeh.pydata.org/en/latest/docs/user_guide/interaction.html#callbacks-for-tools

Probably better to make a proper simple tool for doing this but it could be done with a JSCallback now.

**Comment by avanetten** [comment]
Wondered if there are any updates on this.  As aforementioned, Leaflet would be nice, though support for OpenStreetMaps would also work, and likely be far easier.  I see that GeoJSPlot is slated for removal, so for the immediate future it looks like GMapPlot will be the only option.  I'm also curious if Bokeh will offer any advice or support for pointing a map plot to a custom/offline tile server.  

The example at the link you posted is quite useful, though the callback option only exists for the BoxSelectTool, and not PolySelectTool, which is what I'd prefer to use.  Another complication is that when the link is run on bokeh-server, the rendered rectangle disappears as soon as it is drawn, I'm guessing since the display is constantly updating.

**Comment by bryevdv** [comment]
My hope is to make a "Open Layers" renderer (that could be used for Google, Bing, custom tile sets) that could be added to plots, so that `GMapPlot` could  be removed altogether. There is some initial stabs at this in some customer work but the main obstacle is lack of experience with OLS. New contributors here could certainly help accelerate things.

**Comment by bryevdv** [comment]
A new tile renderer is going into `0.11` that supports almost any tile source that you would like to configure.

**Comment by bryevdv** [comment]
Also `GeoJSPlot` is being removed in `0.11` but it could very easily be added back as a "custom user model".
