### ISSUE TITLE
charts.Scatter doesn't handle unequal-length input

### ISSUE THREAD

**Issue by TorbjornT** [bokeh/bokeh#2592]
An example illustrates this:

```
from collections import OrderedDict
from bokeh.charts import Scatter
from bokeh.plotting import show, output_file

output_file('demo.html')
data = OrderedDict([
    ('a',[[1,1]]),
    ('b',[[2,2], [3,3]]),
    ('c',[[4,4], [5,5], [6,6]])
    ])
scatter = Scatter(data,xlabel='x',ylabel='y',legend='top_left')
show(scatter)
```

The resulting scatter plot will only show the first point of `b` and `c`. Hence the plot shows three points, (1,1), (2,2) and (4,4) instead of six points, as one might expect:

![image](https://cloud.githubusercontent.com/assets/3189311/8774186/bcec90b6-2edb-11e5-928f-ba0683328d29.png)

The same thing occurs when passing a pandas `DataFrame().groupby()` object as input.  I can work around it easily enough by adding NaN entries at the end of the shorter vectors, but it would be nice if it just worked.

I'm running `bokeh` 0.9.1.

**Comment by bryevdv** [comment]
The low-level `ColumnDataSoucrce` object has a hard requirement that all the columns be the same length. I am actually surprised that out new validation machinery does not spit out a warning about this. That said, the high level interface is there to coordinate the low-level pieces in more convenient ways, and it would certainly be possible for it to create more than one `ColumnDataSource` to transparently handle data sets of unequal size. 

ping @rothnic @fpliger

**Comment by rothnic** [comment]
I believe the issue is here: https://github.com/bokeh/bokeh/blob/master/bokeh/charts/_data_adapter.py#L92 and
https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builder/scatter_builder.py#L114

This is an example of passing in pre-grouped data. Data adapter tries to handle both cases, but seems to make the assumption that the groups are of equal length (because the data isn't detected as grouped). @TorbjornT I'd be curious to see what you were trying for the pandas groupby, because it appears it should handle the pre-grouped dataframe.

The alternative for how you could do this with the current charts api proposal (#2442) the following. It looks like this approach isn't yet supported:
```python
data = {'x': [1, 2, 3, 4, 5, 6], 'y': [1, 2, 3, 4, 5, 6], 'label': ['a', 'b', 'b', 'c', 'c', 'c']}
scatter = Scatter(data, 'x', 'y', color='label')
```

But, I do think the more simple pre-grouped approach should still be available as it probably is  more intuitive for ad-hoc graphs. But it far less likely that you'd encounter this type of data in real world relational data stores. We may just need a simple adapter that pushes the grouped data in a column oriented data structure (similar to the dict of lists example I provided above).

Need to consider how you would color or use markers to differentiate in this case. Maybe:
```python
#color only (all same marker)
Scatter(data, ..., color=['a', 'b', 'c'])

#marker only (all same color)
Scatter(data, ..., marker=['a', 'b', 'c'])

#each group gets unique color and marker
Scatter(data, ..., color=data.keys(), marker=data.keys())
```

**Comment by TorbjornT** [comment]
@rothnic Basically something like this:

    import pandas as pd
    from collections import OrderedDict
    from bokeh.charts import Scatter
    from bokeh.plotting import show, output_file

    output_file('demo.html')
    x = [1,2,3,4,5,6]
    y = [1,2,3,4,5,6]
    z = ['a','b','b','c','c','c']
    df = pd.DataFrame(dict(x=x,y=y,z=z))
    sc = Scatter(df.groupby(z))
    bp.show(sc)

Which gives the same result as the above.

**Comment by rothnic** [comment]
@TorbjornT: thanks

Yeah, the grouped dataframe is turned into an ordereddict. The issue is that the data adapter appears to assume that the ordereddict is columnar, and not yet grouped. It is trying to generate indices, based on the length of the first column ('a'), which is 1. This is why the first is only plotted.

Honestly, I'm not quite sure about the intent behind this, so @fpliger might be the best to fix it in the short term. I could make it work for scatter, but will likely break more things that use data adapter. I do have some ideas for how to deal with this in the charts api approach, so this was good to work through. 

In the end, we should be getting to some structure that doesn't care about traditional indexes. Instead, we just need to get to some unique identifier (in this case ('a')->color 1, ('b')->color 2, ('c')->color 3), where each unique identifier is assigned some set of visual attributes. This psuedo-index doesn't identify a unique row, but unique subsets of data that are optionally aggregated and visualized in the same way.

@fpliger: When I was working  through it, I wasn't sure what [this section](https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builder/scatter_builder.py#L188) was doing and ended up rewriting it. Not sure if it is worth using, but this does the equivalent using more of the commonly used pandas api:

```python
            if isinstance(self._values, pd.core.groupby.DataFrameGroupBy):
                pdict = OrderedDict()

                for name, group in self._values:
                    self._labels = group.columns
                    pdict[name] = group[[self._labels[0], self._labels[1]]].values
```

**Comment by fpliger** [comment]
It's definitely a bug and the new design we have been discussing about should automatically fix it..

**Comment by bryevdv** [comment]
@fpliger @rothnic is this still relevant?

**Comment by fpliger** [comment]
IMO it is..

**Comment by rothnic** [comment]
Just adding some notes here after talking to @fpliger. @bryevdv, your input would be useful.

I think one issue here for the new charts interface is whether we should support some nested data structure that represents a specification of the chart, without taking in the regular data/inputs to derive the chart specification. For the new interface, the issue won't necessarily be the unequal length data for this example. It will be that there is too much ambiguity in the data structure to know what to do without coming up with a specific format to consistently parse for each chart..

When blindly receiving this data to convert it into a consistent internal format you have to consider, do the keys correspond to row indices, like a pandas groupby? Do the keys correspond to columns? It is possible that this could differ on a chart by chart basis.

## Summary of the issues to address

### 1. Chart spec input using a json-like approach

In the [first example](https://github.com/bokeh/bokeh/issues/2592#issue-96038232), the keys are the indices and the values are x, y positions. This is a potential format for how we'd specify the chart, where order of the values implies what they should be used for. However, let's consider the case where we'd want to also specify fill color or line color, etc. How would we specify those in this structure? Continue using order, or use a dict?

### 2. Pandas groupby input support

In the [second example](https://github.com/bokeh/bokeh/issues/2592#issuecomment-123203923), the input is a groupby object, which is easier to reason about. X and y are specified as columns, and we would have some index-like thing that identifies the groups of data. Internally, this is what we are getting to for the most part, deriving the index and assigning attributes to each index based on columns.

For **1.**, I'd like to get to this and we could use vega-lite as a source of ideas, while supporting some simplified specification for simple charts so you don't have to write out this huge nested dict. I do think this is further off, however.

For **2.**, I think we could handle this without too many changes in the near term. The thing we'd need to do at some point is handle the specification of coloring by groupby level number or column. So, you could do something like this:  

`Chart(df.groupby(['col1', 'col2']), x='col3', y='col4', color='level 0', marker='level 1')`

Any thoughts on whether or not to support these, or opinions on how they should work?

**Comment by fpliger** [comment]
@rothnic I don't think we should support either options (`1.` keys are the indices and the values are x, y positions and `2.` input is a groupby object).. at least for now... at least until we have a stable iteration of the `charts` API. (imo it's worth keeping this discussion on a different dedicated issue)

What I think we should support (that is related to this issue) is the use case of users providing data that has iterables that are not of the same lenght.. Consider this example:

```Python
data = dict(
            stamp=[.33, .33, .34, .37, .37, .37],
            postcard=[.20, .20, .21, .23],
)

# create a line chart where each column of measures receives a unique color and dash style
line = Step(data, y=['stamp', 'postcard'],
            dash=['stamp', 'postcard'],
            color=['stamp', 'postcard'],
            title="U.S. Postage Rates (1999-2015)", ylabel='Rate per ounce', legend=True)
```

This should be supported on basically on all charts..

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/34)
