### ISSUE TITLE
CI test to make sure bokeh works without heavy dependencies

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#2596]
There should be a separate test that makes sure that bokeh works without ~~~numpy~~~, scipy, pandas, etc. The minimal environment should contain python (obviously), six and preferably nothing more. Make sure to test not only if bokeh imports like this, but test as many plotting APIs as feasible 

*removed comments about charts*

**Comment by canavandl** [comment]
Per issue #2373, pandas is a dependency for charts.

**Comment by damianavila** [comment]
Not sure if there is enough time to include it in 0.9.2, but I agree on the proposal...

**Comment by bryevdv** [comment]
Let's do this as part of a larger effort after `0.11`

**Comment by bryevdv** [comment]
I think I am inclined to just expand this test (or make a new one):

https://github.com/bokeh/bokeh/blob/master/tests/test_no_tornado_common.py

to include pandas scipy and call it a day

**Comment by bryevdv** [comment]
Well that doesn't quite work since we do conditionally import pandas if it is present in some places. We would need an actual different environment. I'm not sure it's worth it, we have not needed this so far and I think a pandas or scipy import would be noticed in review. 

Other idea though, we could add a NO_PD_SP flag to the py3.5 unit test run, and have that rest explicity uninstall pandas and scipy before running unit tests
