### ISSUE TITLE
Tweak legend json format to allow for groups of legend entries and titles

### ISSUE THREAD

**Issue by hafen** [bokeh/bokeh#2602]
It would be nice to have a little more flexibility in what is shown in a legend.  Often a legend might have different groups of legend entries and you want to be able to label each group.  For example:

![rplot](https://cloud.githubusercontent.com/assets/1275592/8843202/b33261aa-30d3-11e5-85e4-458999691b19.png)

I think this could be done very easily - just slightly modify the model for the "legends" attribute to maybe something like below and then update the legend rendering to place the titles above each group.  You could continue to support the more simple legends as they are now but have this as an option.

```
"legends": [
  {
    "title": "group 1",
    "entries": [
      [
        "entry 1",
        [{ "type": "GlyphRenderer", "id": "xxx" }]
      ],
      [
        "entry 2",
        [{ "type": "GlyphRenderer", "id": "xxx" }]
      ],
    ]
  },
  {
    "title": "group 2",
    "entries": [
      [
        "entry 1",
        [{ "type": "GlyphRenderer", "id": "xxx" }]
      ],
      [
        "entry 2",
        [{ "type": "GlyphRenderer", "id": "xxx" }]
      ],
      [
        "entry 3",
        [{ "type": "GlyphRenderer", "id": "xxx" }]
      ]
    ]
  }
]
```

**Comment by bryevdv** [comment]
@birdsarah @hafen does some of the recent legend work (some open PRs) address this?

**Comment by birdsarah** [comment]
Only a little bit. 

Having multiple legends is possible (you just closed an issue about this)

The first legend of the two shown is possible with the open PRs - you'd ask for column 'cyl' when specifying a legend. 

But we don't have a way to make the second PR where you've stripped out / overridden a visual property (color).

I think this is a generally useful thing though. It's something I've wanted for a while for a different use case. My use case is this:
- when building interactives on more than one occasion I find myself making a whole bunch of invisible lines (or some other shape) then when you select something on another plot the selected thing becomes visible.
- I do this because it means there's often no callback code to write just using linked brushing has achieved the effect I want

But it breaks down when I want to build a legend for the plot with the invisible lines, because the main glyph (as oppose to the selection glyph) is taken as the representative point and it has an alpha of 0 and so I get a legend with labels but no visible glyphs.

Another perhaps more common use case is when you set visible glyphs to have an alpha of 0.7 so that when they are selected and alpha is 1.0 the color pops. Often times you want that pop color to be the legend match.

Another use case I can think of is when you'd want the element to indicate what the selection diff looks like e.g. you have a bunch of colored patches but when you select them you get a green border. You want the legend to show a green border but with no particular colored fill to just describe what's visually happening.

Whilst you could do something with being able to pick which glyph is representative, I think it would be useful to build the more general case of saying pick this glyph and this representative point, but then override visual property x.  

When I was thinking about it earlier I thought it might be hard, but now I'm thinking about it more I don't think it's that hard although it would be more work than the other legend PRs.

**Comment by birdsarah** [comment]
Also, the mini-ramble above is at a much higher level than tweaking the serialization format which is the title of this PR.

**Comment by bryevdv** [comment]
I'm going to close this. https://github.com/bokeh/bokeh/issues/6769 is already about adding titles to legends, and it is already possible to add multiple legends (including now with different representative points of the same glyph, see https://github.com/bokeh/bokeh/pull/8218) so there is no JSON changes needed that I can think of
