### ISSUE TITLE
Split up and refine CSS

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2606]
The CSS is big.

It also isn't modular, so people pay a price they don't need to.

In many projects I don't include bokeh css at all and bokeh still works great.

**Comment by bryevdv** [comment]
This should done in mind with the model extensibility. New models should be able to contribute both JS and CSS resources.

**Comment by mistakevin** [comment]
I mention css "scoping" in https://github.com/bokeh/bokeh/issues/2493, which may be indirectly relevant.

**Comment by mattpap** [comment]
Technically this issue is a duplicate. If we split bokehjs, css will be split as well.

**Comment by birdsarah** [comment]
Presumably they can also run semi-independently though. That is we can make progress on the CSS while the JS is in progress. What is the timeline of the JS. Can you link to the JS issue @mattpap?

**Comment by birdsarah** [comment]
ping @mistakevin @mattpap - am i right in thinking you're actively working on splitting up the JS and so the css work is happening as a byproduct?

**Comment by mattpap** [comment]
It was a little surprising to me that widgets were split off as late as September 2015. Yeah, I know, I did it my self, but it feels more like 2014. So, this issue is pretty much fixed, because now `bokeh.min.css` is around 70 kB. This is still more than necessary and there are some styles that can be simplified or removed. Additionally, in PR #5166, `src/less` was reorganized to bring some structure to it.
