### ISSUE TITLE
Propose new JupyterCallback

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2620]
At the Europython sprints, @akloster was showing is really nice work integrating Bokeh & Jupyter notebooks. 

We looked at his code and discussed for a while what a good spelling would be.

The end result of that is a proposal for a `JupyterCallback` that be usable in the same pattern as the current JSCallback to keep a consistent interface.

So in a notebook, you would do something like this:

``` python
from random import random
from bokeh.models import Callback, ColumnDataSource
from bokeh.plotting import figure, output_notebook, show

output_notebook()

x = [random() for x in range(500)]
y = [random() for y in range(500)]

p = figure(plot_width=400, plot_height=400, tools="lasso_select", title="Select Here")

data_source = ColumnDataSource(data=dict(x=x, y=y))
p.circle('x', 'y', source=data_source)

mean_source = ColumnDataSource(data=dict(ym=[0.5, 0.5]))
p.line(x=[0, 1], y='ym', source=mean_source)


def update_mean(mean_source):
    selected = cb_obj.selected['1d'].indices
    data = cb_obj.data_source.data
    # calculate mean
    mean_source.data_source.data = new_data


data_source.callback = JupyterCallback(update_mean)

show(p)
```

@akloster, was still thinking about it, but seemed to be drawing closer to not using the Jupyter widgets to make this work but some lower level code. He had already implemented a demo which did an update source and a selection callback which worked really nicely - although they were not with this spelling.

We also discussed what would be suitable tests for this as it's hard to test interactivity on the ipython notebook (we didn't come to any conclusions).

**Comment by akloster** [comment]
In the example above, there is no Indication of a DataSource being explicitly updated to the Browser. Is that intentional, so that there is an "on change" callback to mean_source.data_source.data which sends the data?

@birdsarah had the idea of implementing a JupyterDataSource. This could either do the update automatically, by calling a "update" method, or maybe even "show(data_source)". It would be nice if there would be a way to bundle multiple data source updates, because the plot would then only redraw once, improving the smoothness.

**Comment by birdsarah** [comment]
> there is no Indication of a DataSource being explicitly updated to the Browser.

Actually, I expect the line `mean_source.data_source.data = new_data` to update the data source and subsequently update the data in the browser plot. Does that make sense? Maybe it's not clear?

**Comment by birdsarah** [comment]
Maybe: `mean_source.data_source.update(new_data)` would be clearer.

**Comment by damianavila** [comment]
This is really interesting

>@akloster, was still thinking about it, but seemed to be drawing closer to not using the Jupyter widgets to make this work but some lower level code.

Thinking into use comms directly??

>He had already implemented a demo which did an update source and a selection callback which worked really nicely - although they were not with this spelling.

Do yo have the examples somewhere?

>We also discussed what would be suitable tests for this as it's hard to test interactivity on the ipython notebook (we didn't come to any conclusions).

Can we know the highlights of that discussion?

Thanks!!

**Comment by bryevdv** [comment]
I think the number one thing to improve interactions with the notebook is to use comms to update the data sources. Going the reverse direction, having the ability to have Bokeh events call into python code also seems really useful, but we need to be careful. It's is a non-trivial feature, that has potential intersections with other ongoing bits of work. Bokeh itself is going to be getting a binary comms protocol over WS, and so that ought to be considered. For instance, it's possible that a new tornado-based bokeh server core could just be run under/with the Jupyter server, which would allow much machinery to be re-used.

**Comment by akloster** [comment]
I have implemented a Bokeh update using only a comm channel (without widgets) in my pysiology library.

https://github.com/akloster/pysiology/blob/master/pysiology/assets/bokeh_update.coffee
https://github.com/akloster/pysiology/blob/master/pysiology/notebook.py#L159-L182

Regarding binary websocket protocols... I'm all for a binary way to send arrays over websockets or json communication. Currently this is not as much of an issue because it looks as if the canvas drawing is slower than the json parsing and unless websockets are used, web servers tend to gzip the data anyway. 

An alternative is to base64 encode the binary array. This turns out to be bigger than json for small integers, but it can be a big saving for floating point data.

I don't believe the protocol should be tied to the actual transport method. Some applications will embed Bokeh and update the time series from values generated in their javascript itself, or derived from their own backbone/ajax/websocket connections, and others will use the Bokeh Server.

It's trivial for the library user to tell how the data source can be most efficiently updated, for example replacing it completely, appending, rolling or even updating just a small range of the data. But it's very hard for a computer to figure this out on his own.

It can also be important to update multiple data sources in a one-time batch, because otherwise there may be artifacts when displaying multiple sources in one plot. (The redraw is triggered after the update function is done.)

**Comment by bryevdv** [comment]
> Regarding binary websocket protocols... I'm all for a binary way to send arrays over websockets or json communication. Currently this is not as much of an issue because it looks as if the canvas drawing is slower than the json parsing and unless websockets are used, web servers tend to gzip the data anyway.

Can you elaborate on this? For instance what range of data sizes have you observed this, and how was it measured?

> An alternative is to base64 encode the binary array. This turns out to be bigger than json for small integers, but it can be a big saving for floating point data. 

I've thought about this, and also thought about just requiring NumPy for the transport. It's definitely possible to ship numpy arrays directly over web sockets into JS typed arrays (I made a proof of concept recently)

> I don't believe the protocol should be tied to the actual transport method. Some applications will embed Bokeh and update the time series from values generated in their javascript itself, or derived from their own backbone/ajax/websocket connections, and others will use the Bokeh Server.

The protocol is just message fragments, mostly JSON but some of which can optionally be binary buffers. It doesn't have to be sent over web sockets and the binary buffers could be sent as JSON lists. Not sure if that's what you mean or not. 

> It's trivial for the library user to tell how the data source can be most efficiently updated, for example replacing it completely, appending, rolling or even updating just a small range of the data. But it's very hard for a computer to figure this out on his own.

Yup, the new WS protocol is expressly being designed to support explicit operations for partial updates, patching, and streaming. 

> It can also be important to update multiple data sources in a one-time batch, because otherwise there may be artifacts when displaying multiple sources in one plot. (The redraw is triggered after the update function is done.) 

Ditto.

**Comment by akloster** [comment]
The length of a Base64 encoded string of bytes is basically 4*(n/3), where n is the number of bytes.

In the worst case, you can imagine an array of int64 (8 bytes). The base64 encoding would be like 13 characters per value, whereas the json (decimal) representation for integers between -9999999999 and 99999999999 would be smaller. Of course, that is an extreme example, but it still applies to smaller int sizes.

In Floats the competing strategy would be to format them decimally such that they only resolve to the level of pixels in the plot. Or even get rid of the point.

The speed of canvas vs json parsing is that json writing/parsing is virtually instantaneous, and Bokeh drawing thousands of lines isn't. Nothing more fancy ;-)

**Comment by bryevdv** [comment]
Well, are you specifically thinking of JSON parsing *in the browser*? I am still dubious of the "virtually instantaneous" claim, but I could at least appreciate that it's not as big a concern on the ingest side of things. Rather, it's the problem of converting a numpy array to a list, then the list to JSON, then sending the JSON on the other side that I believe is causing so much performance trouble.

**Comment by damianavila** [comment]
>  have implemented a Bokeh update using only a comm channel (without widgets) in my pysiology library.

https://github.com/akloster/pysiology/blob/master/pysiology/assets/bokeh_update.coffee
https://github.com/akloster/pysiology/blob/master/pysiology/notebook.py#L159-L182

Nice, I saw your questions on Jupyter gitter the other day... Glad to see Jason gave you some hints to proceed with this path... thanks for working on this!!

**Comment by akloster** [comment]
This afternoon I implemented a simple Snake game running in the notebook, using a Jupyter widget for Input and Bokeh for graphics:

https://github.com/akloster/bokeh-snake

A short demonstration video:

https://www.youtube.com/watch?v=eM1ycBFyu48

**Comment by damianavila** [comment]
Great demo!!

**Comment by bryevdv** [comment]
Cool! Do you mind if I tweet this out?

Bryan

**Comment by akloster** [comment]
No problem, it was meant for dispersal...

**Comment by bryevdv** [comment]
Bokeh server apps can now been embedded in notebooks which I would regard as a much more robust option. Given that  this can be accomplished by users with `kernel.execute` I am not inclined to add somethig to the core library that otherwise encourages it.
