### ISSUE TITLE
Renderers are still sorted improperly

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#2674]
Offending code is in `sortKey` which accepts a renderer view, but treats it as a renderer (a model), thus sorts by `undefined`.

**Comment by mattpap** [comment]
Fix in mattpap/0.9.2-fixes.

**Comment by mattpap** [comment]
Apparently this was "fixed" in #2393.

**Comment by bryevdv** [comment]
I'm not sure this is a regression if they were never sorted properly. The above PR did reliably fix the MPL examples that were broken at the time for whatever reason. If you are cleaning this up, I have thee recommendations:
* change the `'id` to something like `.sorter` since `id` is a terrible name but also used elsewhere which is confusing
* change the other variable names to be explicit about what is a model and what is a view, that's the confusion that allowed this in the first place.

**Comment by mattpap** [comment]
#2744

**Comment by mattpap** [comment]
> The above PR did reliably fix the MPL 

No it didn't, look at the report in #2744.
