### ISSUE TITLE
Non-unit specs accept still allow `units` field

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#2680]
At some point `x` and `y` properties' types were changed to `NumberSpec` which is `data` units only. However, you can still set `screen` units. Obviously nothing will happen in bokehjs and no errors or warnings will be shown anywhere. This results in `iris_splom` example being broken, because text is displayed in `data` units, very far from actual data.

**Comment by mattpap** [comment]
btw. How I'm supposed to put text on screen in `screen` units? Set `x`, `y` to 0 and configure `x_offset` and `y_offset` instead? @bryevdv, this is migration guide you want to leave off after 1.0.

**Comment by mattpap** [comment]
btw. `NumberSpec` for coordinates doesn't feel right when combined with categorical data.

**Comment by bryevdv** [comment]
@mattpap At some point there was a large PR and a long discussion. TLDR: efficient spatial indexing with glyphs that could positioned in screen coordinates, or worse, a mix of screen and data coordinates was impossibly broken and unworkable. But that's OK, because it was realized that if you want to position things with screen coordinates, it's almost certainly the case that what you actually want is an annotation of some sort. So, the plan is for things like the text on iris splom to become proper annotation objects. @canavandl is working on adding new annotation types (h/v spans, text, math text, etc.) right now. 

You will have to be more specific about how are you setting the units to screen, and provide actual code. When I set  `x_units = "screen"', it is caught by the general machinery that triggers on unknown properties:
```
In [2]: from bokeh.plotting import output_file, figure, show

In [3]: p = figure()

In [4]: p.circle(x=[1,2,3], x_units="screen", y=10)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-a82adcf41efd> in <module>()
----> 1 p.circle(x=[1,2,3], x_units="screen", y=10)

/Users/bryan/work/bokeh/bokeh/_glyph_functions.py in func(plot, *args, **kwargs)
     35 
     36         # create the default and nonselection glyphs
---> 37         glyph = _make_glyph(glyphclass, kwargs, glyph_ca)
     38         nsglyph = _make_glyph(glyphclass, kwargs, nsglyph_ca)
     39 

/Users/bryan/work/bokeh/bokeh/plotting_helpers.py in _make_glyph(glyphclass, kws, extra)
    142         kws = kws.copy()
    143         kws.update(extra)
--> 144         return glyphclass(**kws)
    145 
    146 def _update_legend(plot, legend_name, glyph_renderer):

/Users/bryan/work/bokeh/bokeh/plot_object.py in __init__(self, **kwargs)
     88 
     89         if not block_events:
---> 90             super(PlotObject, self).__init__(**kwargs)
     91             self.setup_events()
     92         else:

/Users/bryan/work/bokeh/bokeh/properties.py in __init__(self, **properties)
    355 
    356         for name, value in properties.items():
--> 357             setattr(self, name, value)
    358 
    359     def __setattr__(self, name, value):

/Users/bryan/work/bokeh/bokeh/properties.py in __setattr__(self, name, value)
    369 
    370             raise AttributeError("unexpected attribute '%s' to %s, %s attributes are %s" %
--> 371                 (name, self.__class__.__name__, text, nice_join(matches)))
    372 
    373     def clone(self):

AttributeError: unexpected attribute 'x_units' to Circle, similar attributes are radius_units
```
So I am not really certainly what you are referring to when you say it still accepts screen units.

I agree "NumberSpec" feels weird for categorical data and that the "Spec" hierarchy can be tightened up more.

**Comment by bryevdv** [comment]
Guessing you mean this?
```
In [10]: p.circle(x=dict(value=10, units="screen"), y=10)
Out[10]: <bokeh.plotting.Figure at 0x108a04240>
```
Sure enough, we can probably expand our validation to check the values for correctness. That would be a welcome addition, but a few comments:
* If you had provided code from the start it would have saved me 15 minutes trying to guess what you meant
* I would be very surprised if the number of people trying to set the units this way is greater than a handful
