### ISSUE TITLE
Add npm cache flush to travis install

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2702]
We had a few issues on travis today, where travis couldn't finish installing because `npm ERR! cb() never called!`

@mistakevin pointed me to the SO post: http://stackoverflow.com/questions/15393821/npm-err-cb-never-called

Things seem to be back to normal now, but we could add `npm cache clean -f` to the travis install to try and prevent this happening again.

Not sure what the potential downsides are.

**Comment by mistakevin** [comment]
@damianavila @birdsarah @bryevdv 
[Here](https://github.com/npm/npm/issues/5920) is a more in depth discussion on the issue. It seems to be due to a number of bugs in `npm`. I noticed that `npm` is behind on travis: `npm version 1.4.28` (currently `npm` is at `2.*`) , as well as node on travis: `node version v0.10.36`, (currently at `0.12.*`). That discussion suggests that the issues have been resolved in `npm 2.*`, so we should try updating and see if we hit the same number of errors. I manage `node` and `npm` on my machine with [`nvm`](https://github.com/creationix/nvm), which is really convenient. Simple commands like `nvm install stable`and `nvm use stable` make managing environments a breeze.

**Comment by damianavila** [comment]
I would like to start seeing the most updated versions of node/io and npm, so +1 to start trying to figure out the update unless there is sometime tying us to this old versions...
About `nvm`, I do not know too much about it... I guess that will be a second step after the update...

**Comment by mattpap** [comment]
Just to note, I had similar issues with building bokeh-scala last week and switching to node.js 0.12 solved this.

**Comment by mistakevin** [comment]
To start using `nvm` we should just need to add
`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.25.4/install.sh | bash`
or
`wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.25.4/install.sh | bash`
then
```shell
nvm install stable
nvm use stable
```
to our `build.sh` to get the latest stable node and npm

**Comment by damianavila** [comment]
>To start using nvm we should just need to add

Well, I guess you can tempt me with a PR :wink:

**Comment by mistakevin** [comment]
(hopefully) resolved in PR https://github.com/bokeh/bokeh/pull/2706

**Comment by damianavila** [comment]
Let's close it for now...
