### ISSUE TITLE
pandas compatibility example fails to show time axis

### ISSUE THREAD

**Issue by michaelaye** [bokeh/bokeh#2721]
Using this notebook: https://github.com/bokeh/bokeh/blob/master/examples/compat/pandas/pandas.ipynb

I produced this bokeh plot with it:
![bokeh_pandas_plot](https://cloud.githubusercontent.com/assets/69774/9279016/c43821ec-4271-11e5-85b7-93cb83d1b114.png)

but the time x-axis should look like this:

![unknown-1](https://cloud.githubusercontent.com/assets/69774/9279020/ce489a9a-4271-11e5-83ea-8a6e014ac70f.png)

The timeseries capabilities of pandas are really important for my work, so unfortunately I cannot use bokeh at all until this is fixed, even so I really would like to due to its better handling of large amounts of data points.

Version: today's master (d2ef2fa8e59)

**Comment by bryevdv** [comment]
Our pandas plotting support is reliant upon the third party `mplexporter` library, which is not a complete compatibility layer, and may never be. There is work (by the MPL team) to make a more robust serialization scheme for MPL that other projects (like Bokeh) to use. But that is on their schedule and out of our hands, and AFAIK will not be ready until next year some time. It's also possible the Pandas project could decide to support Bokeh directly, but again, that is out of our hands. 

However, it's always possible (and I would say better) to just use Bokeh's own plotting API's directly, rather than relying on compat layers. Here is a time series example using the `bokeh.plotting` API:

http://bokeh.pydata.org/en/latest/docs/gallery/correlation.html

and here is other using the `bokeh.charts` API:

http://bokeh.pydata.org/en/latest/docs/gallery/stocks_timeseries_chart.html

**Comment by michaelaye** [comment]
Good to know that it's easy to use pandas data frames with Bokeh's API directly, because when one searches the Bokeh documentation for pandas the first hit is the compatibility page http://bokeh.pydata.org/en/latest/docs/user_guide/compat.html that's why I used that.

**Comment by bryevdv** [comment]
That is actually very good feedback. It's very easy to overlook things that seem obvious because of familiarity, but that are not at all obivous to new users. Have made an issue to amend the docs here: https://github.com/bokeh/bokeh/issues/2722

**Comment by michaelaye** [comment]
:+1: I will see how it goes for me and add things to that issue if I find anything that could be improved for the docs. I haven't searched everything yet, but for example it would be good to have a pandas example that does not need to resort to use OrderedDict. I understand that in the stocks_timeseries_chart it's only used to fish out the wanted columns from the other 3 dataframes, but I think it's important to show us beginners that one can just drop a timeseries dataframe into the bokeh Timeseries wihout anything else required (tried it, works smoothly, even with `index=df.index`), otherwise on first glance it looks like that the Timeseries `requires` OrderedDicts as input.

**Comment by bryevdv** [comment]
As it happens, we are currently working on an even more pandas-friendly interface to `bokeh.charts` and some of the work has already started. See:

https://github.com/bokeh/bokeh/pull/2720
