### ISSUE TITLE
Add text annotation

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#2749]
I'm proposing a text annotation, with two modes:
-  Stand-alone text annotations where a user simply wants to put text on a plot in x,y space.
-  Text annotations on glyphs (e.g. where a user wants to label x,y scatterpoints)

The first would be similar to BoxAnnotations (appended to the plot renderers), but it's unclear to me the best way to link annotations to a glyph. I would appreciate feedback on this.

**Comment by birdsarah** [comment]
@canavandl - can you provide more detail on what you mean by "linked"?

I'm trying to think through a few cases, but you've probably done more thinking on this already. 

I'm assuming a standalone text annotation doesn't move while the plot/points move, but I'm assuming a text-annotation that's "linked" to a glyph does move when the plot/points move. In this case, how is this different from a text glyph powered by the same data source as the points?

**Comment by canavandl** [comment]
As I imagine it, a standalone text annotation can be set to either screen or data space (which is how the new box annotations work). In terms of annotating individual glyphs, text annotations would be very similar to text glyphs, but hopefully with a little syntactic sugar.

Hunt proposed a "named glyph" attr to link text annotations to glyphs (roughly) like:
```python
p = p.add_glyph(Rect(xs, ys, width=width, height=height, name='rect', source=source))
p = p.renderers.append(TextAnnotation(text='text', offset='2px', glyph='rect', source=source))
```
where the location of the text annotations is abstracted away. I like the concept, so I'm going to implement it to see how it works in practice.

**Comment by tobyhodges** [comment]
I spent a fair bit of time figuring out the best way to add text annotations to annular wedge glyphs. I agree that simply plotting text glyphs is an easy and appropriate way to add text annotation to rect, quad, scatter, circle etc. glyphs that have an appropriate central point. 

However, for [annular] wedges, the best position for an annotation is probably offset at an angle from the central point around which the glyph is drawn. I had to convert polar to Cartesian coords to get the 'central' point of the glyphs, as the angle changed for each glyph. Speaking for myself, I'd love to see a way to annotate wedges/annular wedges more easily, for when the Donut chart method won't do the job.

**Comment by bryevdv** [comment]
Those are good observations, if we are going that route it might do better to delegate suggested offset computation to the glyphs themselves.

**Comment by tobyhodges** [comment]
I agree. I actually was coming here to suggest that I try to rustle up a PR for exactly that when I found this thread. Really looking forward to seeing what @canavandl has come up with :)

**Comment by bs1234** [comment]
+1 if this will include the ability to add text _outside_ the plot area itself (for example over, or beyond, an axis).  And especially if that axis is categorical rather than numeric.

A simple example here:
https://stackoverflow.com/questions/32612937/adding-text-in-bokeh-when-using-categorical-axis

In case it's of interest: I believe Matlab achieved this by differentiating between "axes" (a single chart) and "figure" (an object that held one or more charts). Text could be added to either. The "figure" co-ordinates ran from (0,0) at bottom left to (1,1) top right. Text that was added to a figure could then be outside any axes.
Note: the bokeh 'figure',I believe, is more similar to the matlab axes than the matlab figure.

I'd be keen to hear if plotting text outside the chart area (outside a bokeh figure) is part of this issue. Or indeed to be educated if it's already possible.

Well done on a great package.

**Comment by bryevdv** [comment]
@bs1234 yes there is a plan to expose more/different/possibly nested coordinate systems. It's going to be a little bit of work, and we need to let a few other ongoing larger changes settle down.

**Comment by bryevdv** [comment]
The `Label` PR was just merged.

**Comment by tobyhodges** [comment]
Thanks @bryevdv @canavandl !
