### ISSUE TITLE
Changing the axis type via widgets

### ISSUE THREAD

**Issue by ilayn** [bokeh/bokeh#2765]
First of all, a big thanks goes to everyone created this library. I'm a very recent user but so far I'm really happy and impressed. 

I'm a little bit uncomfortable with starting this issue here. Because I'm not sure if this is the right place for feature requests. So please close this if it is not so and apologies in advance for the noise.  

I have asked [a question on SO](http://stackoverflow.com/questions/32170143/changing-the-axis-type-in-bokeh-via-a-select-widget) but then I got a little more curious and I've started to read the code of the Figure class and saw that this might not be even possible. Because inside the `__init__()` all kinds of ticker calls and other preparations are done. 

Thus, I wanted to both ask whether this is status-by-design or is it too difficult to implement. 

The nonworking code I have for an Ipython notebook is given below (repeated from the SO question)

    import numpy as np
    from bokeh.plotting import figure, output_notebook, show
    from bokeh.models import Callback, ColumnDataSource
    from bokeh.models.widgets import Select
    output_notebook()

    a = np.arange(100)
    b = np.abs(np.random.rand(1,100).flatten())*4
    source = ColumnDataSource(data=dict(a=a,b=b))
    
    axis_type_changer = Callback(args=dict(source=source),
                                code="""
                                //<-----What should come here? 
                                """) 
    
    myselect = Select(title="Y-axis type",
                      value="linear",
                      options=["linear","log"],
                      callback=axis_type_changer)
    
    f = figure(x_axis_type='linear',y_axis_type='linear')
    f.line('a','b',source=source)
    show(myselect)
    show(f)

As a minor side issue is there any particular reason that the widget assumes the full length of the notebook space?

**Comment by azjps** [comment]
Unfortunately I think all of the axes are (as of now) initialized once in the "constructor" of the figure, so I don't think it can be directly changed via a JS Callback. This blurb gets as far as updating the figure's `attributes` but not re-initializing the plot:

```python
import numpy as np
from bokeh.io import vform
from bokeh.plotting import figure, output_notebook, show
from bokeh.models import Callback, ColumnDataSource
from bokeh.models.widgets import Select
output_notebook()

a = np.arange(100)
b = np.abs(np.random.rand(1,100).flatten())*4
source = ColumnDataSource(data=dict(a=a,b=b))

f = figure(x_axis_type='linear', y_axis_type='linear')

axis_type_changer = Callback(args=dict(f=f),
                             code="""
                             f.set("x_mapper_type", cb_obj.get("value"));
                             f.trigger("change");
                             console.log(f);
                             """)

myselect = Select(title="Y-axis type",
                  value="linear",
                  options=["linear", "log"],
                  callback=axis_type_changer)
    
f.line('a','b',source=source)
show(vform(f, myselect))
```

If you don't have to do it in a static html file or a notebook, It should however be pretty easy to do such via bokeh-server.

**Comment by ilayn** [comment]
Oh I see. It's a pity but I appreciate the complication. Is it possible to reinitialize the figure in-place? I don't mind loosing the zoom configuration etc. 

Indeed, I have to do it in a notebook as much as possible for my user profile. 

Thanks though, at least this is some confirmation for my instinct.

**Comment by azjps** [comment]
The easiest solution I can think of is to use a [`Tabs` widget](http://bokeh.pydata.org/en/latest/docs/user_guide/interaction.html#tab-panes) instead, one tab panel which holds a figure with `x_axis_type=linear` and the second tab panel which holds a figure with `x_axis_type=log`, assuming you don't mind the widget change. That might be nicer in some ways, since zooms/pans will be kept when flipping between tabs.

**Comment by ilayn** [comment]
While tabbing might not be ideal because of the huge changes in the curve shape, you have given me the idea that I will simply change units at the tooltip indicators. Because I really don't need to see the shape of the curve in the linear scale. I just need the magnitudes. 

So that looks like my way out at least at this time of the development. Thanks a bunch for the insight and help!

**Comment by bryevdv** [comment]
FWIW I am interested in improving the plumbing so that updates like this are more easily accomplished. See e.g., https://github.com/bokeh/bokeh/issues/2758

**Comment by angembonda** [comment]
Hi @bryevdv  i know this issue has been closed since a long time but i still got a question. I am  a beginner with bokeh and having difficulties updating my x-axis. Already tried a lot of different form with CustomJS and without (like in movies sample) but none seem to function. I am using bokeh version 2.0.2 and my code looks as follows:

`from bokeh.plotting import figure, output_file, show
from bokeh.models import Slider, Select, widgets, ColumnDataSource, CustomJS
from bokeh.layouts import column, row, gridplot, Spacer, layout
from bokeh.models.tools import HoverTool
from bokeh.transform import factor_cmap
from bokeh.palettes import Category10_3
import pandas
import numpy as np
df = pandas.read_csv("carsDE.txt", delimiter='\s+', index_col=False)
source= ColumnDataSource(df)
model = np.unique(source.data['Model']).tolist()
herkunft = source.data['Herkunft'].tolist()
output_file('index.html')

p = figure(
    y_range = model,
    plot_width = 400,
    plot_height = 1000,
    title = 'Cars DE',
    x_axis_label = 'Verbrauch',
    y_axis_label = 'Modell',
    tools = "pan,box_select,zoom_in,zoom_out,reset"
  

)




g= p.hbar(
    y = 'Model',
    right = 'Verbrauch',
    left = 0,
    height = 0.4,
    fill_color = factor_cmap(
        'Herkunft',
        palette=Category10_3,
        factors= ["American","Japanese","European"]
        
    ),
    fill_alpha = 0.9,
    legend = 'Herkunft',
    source=source
)
p.legend.location = "top_right"
p.legend.title= "Herkunft"
p.legend.click_policy="mute"

# Add Tooltips
hover = HoverTool()
hover.tooltips = """
    <div>
    <h3>@Model</h3>
    <div><strong>Hersteller: </strong>@Hersteller</div>
    <div><strong>Verbrauch: </strong>@Verbrauch</div>
    <div><strong>Zylinder: </strong>@Zylinder</div>
    <div><strong>Hubraum: </strong>@Hubraum</div>
    <div><strong>PS: </strong>@PS</div>
    <div><strong>Gewicht: </strong>@Gewicht</div>
    <div><strong>Beschleunigung: </strong>@Beschleunigung</div>
    </div>
    """
p.add_tools(hover)

select1 = Select(title="X Axis", options=['Verbrauch', 'Baujahr', 'Hersteller'], value="Verbrauch")
select1.js_on_change('value',
     CustomJS(args=dict(source=source, p=p,g=g), code="""
                                            
                                             x = select1.value;
                                             p.xaxis.axis_label = x;                                          
                                             g.set("right", cb_obj.get("value"));
                                             g.trigger("change");
                                             console.log(f);

                                            """)
                    )
inputs = column(p,
              Spacer(width=50, height=400, sizing_mode='scale_width'), sizing_mode='scale_width')
widgets = column(select1, height=150, width=50, sizing_mode="fixed")
layout = column(row(inputs, widgets), sizing_mode="stretch_both")
show(layout)`

**Comment by namitachhibba** [comment]
> The easiest solution I can think of is to use a [`Tabs` widget](http://bokeh.pydata.org/en/latest/docs/user_guide/interaction.html#tab-panes) instead, one tab panel which holds a figure with `x_axis_type=linear` and the second tab panel which holds a figure with `x_axis_type=log`, assuming you don't mind the widget change. That might be nicer in some ways, since zooms/pans will be kept when flipping between tabs.

Very apt! Thank you very much!
