### ISSUE TITLE
CoffeeScript style-guide/linting

### ISSUE THREAD

**Issue by MistaKevin** [bokeh/bokeh#2766]
This issue is a general discussion around a CoffeeScript style guide (though could be expanded to include python). Some options are:
 
* Create our own style guide
    * Pros
        * Fully customizable
        * Start small
    * Cons
        * Takes time
        * Disagreements, discussions, apathy on particular styles could drag on
        * Enforcement will be spotty, at best.
        * How do you announce updates?
* Use a pre-written open-source style guide (such as [this guide](https://github.com/polarmobile/coffeescript-style-guide) mentioned by @canavandl)
    * Pros
        * Already done for us!
    * Cons
        * Enforcement
* Introduce a linting library such as [coffeelint](http://www.coffeelint.org/) 
    * Pros
        * Already done for us!
        * [Customizable](http://www.coffeelint.org/#options)
        * Tool integration
            * [CLI](http://www.coffeelint.org/#usage)
            * [Gulp](https://www.npmjs.com/package/gulp-coffeelint)
            * [API](http://www.coffeelint.org/#api)
    * Cons
        * Probably start with several rules, coding time will slow down at first, frustrations will arise
        * When introducing a new linting library into an existing codebase, it's sometimes difficult to make the little 2-3 line changes that fix bugs. If there are any linting errors on the page, you'll have to fix those too if linting is enforced.

Enforcement options
* Incorporate it as a pre-commit [git-hook](http://www.git-scm.com/book/en/v2/Customizing-Git-Git-Hooks)
    * Skippable for small bugs/hotfixes `git commit -nm "The -n flag will skip any hooks"`
        * Contributors will have to manually add it to their `.git/hooks/` folder
        * Might be a good time to introduce a post-merge hook to:
            * Update libraries (python/npm)
            * Update git-hooks
    * Enforce it as part of our build with [gulp-coffeelint](https://www.npmjs.com/package/gulp-coffeelint)
        * Most totalitarian method
        * Must be sure to only lint new/changed files

We did linting at my past gig for frontend and backend. My experience was that it was slow going at first, and enforcement was a drag, but once the codebase was 100% linted, coding and code reviewing went much faster. We incorporated precommit and post-merge githooks, and they are pretty nifty.

@bokeh/dev

**Comment by bryevdv** [comment]
Whatever we do we should delete/clean up the ancient bokehjs docs dir, e.g.

https://github.com/bokeh/bokeh/blob/master/bokehjs/docs/html/docs/style_guide.html

**Comment by hsparra** [comment]
I like the idea of using an existing library and of a pre-commit hook or as part of the build/test process. Looking at CoffeeLint it allows setting of error/warn/ignore per rule so an incremental approach would be fairly easy. It looks like the majority of the issues in the default configuration is the line length rule, which we could disable or make a warning in the near term.  An approach like:

1. Set rules to ignore or warnings
2. Fix all of the occurrence of 1 issue
3. Set that rule to error
4. Rinse and repeat 1 issue at a time

**Comment by havocp** [comment]
My vote is an automated tool; manually-enforced guides are a big time waster. Best tool is one that auto-applies the fixes, especially for simple formatting stuff. Second best is a linter. Either way the ideal if feasible would be to clean the whole codebase up front because otherwise future commits end up with unrelated style and lint fixes cluttering them.

**Comment by birdsarah** [comment]
I'm willing to volunteer to do, at least, a chunk of clean-up if it's useful. If a few of us did it we could probably get it done quickly.

**Comment by fpliger** [comment]
+1 for automation....

**Comment by damianavila** [comment]
mmm... automation?? I don't like anything enforcing me a style... I do not write too much coffee, but the goes same for python (or any language): I would not like it... there are plenty of reason to break the style to improve the readability.
I would accept a lint, it could be useful... but I really hate any automated tool enforcing you to write code in a **accepted** way...

**Comment by almarklein** [comment]
I think without enforcement bad style will surely creep in over time. However, I agree with @damianavila that enforcing a style can be a pain too. My vote would be to enforce a style, but a relatively small subset. Similar to what we did with pyflakes.

**Comment by hsparra** [comment]
I think it is good to know what the variation in styles are so there is a certain amount of consistency. The nice thing about a tool is that it can highlight the variations since it does not have emotions. Then, ideally, with the data you have a discussion and modify (or disable) the rule if it makes sense. Sometimes the variations help highlight nuances that others may not be aware of. I believe any style enforcement mechanism should not be dogmatic, the real world is too complicated. What are the goals of the automation? Readability, usage of certain design patterns in given situations, consistent naming, provide information on the underlying code structure, check some basic things about the code so people can spend their time focusing on more important aspects than a trailing space, being able to use another tool just to use a tool, etc? The goals should guide the usage of the tool and the usage will probably evolve over time.

**Comment by bryevdv** [comment]
It think some things may be hard to automate. One convention we have (that I like) is to use parens for function application:
```
    @foo(bar, baz)
```
*except* for the require statements at the top, which I think read much more clearly without:
```
HasProperties = require "../common/has_properties"
```

**Comment by mattpap** [comment]
@bryevdv, this case is actually pretty easy (as long as you use ASTs instead of regexes).

**Comment by bryevdv** [comment]
OK that's good to know, always happy to be informed.

**Comment by mattpap** [comment]
I'm fine with automation when it's just hinting, but automatically rewriting my code is a big no. If I structure  my code in a certain way, I have a reason for that.

**Comment by havocp** [comment]
For something like indentation is there really some contextual reason to do it differently from the automated rule?

All I care about for stuff like indentation is that PRs don't contain "noise" from people's editors reformatting stuff. and that it's consistent within the file.

Other rules are more judgement calls and then I'd say don't have a rule, automated or otherwise.

All that really matters are the "big" rules like indentation, where everyone doing their own thing will make the PRs and git history a mess.

**Comment by fpliger** [comment]
> mmm... automation?? I don't like anything enforcing me a style... 

@damianavila I didn't intend automation as a tool to fix broken style.. I was thinking more about hinting. I'm -1 on something rewriting our code.

**Comment by bryevdv** [comment]
we have implemented a custom linter for our codebase including coffee, and can add more rules if desired (open new specific issues)
