### ISSUE TITLE
Scientific Citation 

### ISSUE THREAD

**Issue by LeeBergstrand** [bokeh/bokeh#2768]
My lab group has recently utilized Bokeh for building plots for a recent publication. We wish to cite it. How do you recommend we cite Bokeh?

**Comment by bryevdv** [comment]
I'm not sure offhand. Do you have a suggestion, or examples of ways other OSS projects are cited?

**Comment by LeeBergstrand** [comment]
#### Here are some examples:

- [Citing packages in the SciPy ecosystem](http://www.scipy.org/citing.html)
- [Citing R packages in your Thesis/Paper/Assignments](http://www.blopig.com/blog/2013/07/citing-r-packages-in-your-thesispaperassignments/)

**Comment by canavandl** [comment]
The Colour project that I used to contribute (https://github.com/colour-science/colour/) to uses Zenodo (https://zenodo.org/) to host releases and provide a DOI for citations. It looks like it uses git-hooks to keep up-to-date. I sent the project owner an email about whether or not he'd recommend it.

I'll update the issue when I hear back, but I think it's a good way to go.

**Comment by mattpap** [comment]
[Here](https://github.com/sympy/sympy#citation) is another example, this time from SymPy.

**Comment by canavandl** [comment]
Per @KelSolaar (the colour-science lead): 

"As for Zenodo I'm doing it manually, I used the hooks once but I wasn't comfortable having that automatically trigger once you tag the master. If you screw your release for whatever reason you'll end up with a Zenodo DOI for it because of that. The other even more important reason not to do it is that (when I initially tested the stuff) you couldn't pre-reserve the DOI, meaning the DOI was never in sync with the release tag: You tag your master, Zenodo kicks in, generates a DOI for you but now your tagged version is using the DOI of the previous Zenodo upload if that makes sense.

Now what I do is I pre-reserve the DOI by manually uploading a temporary release, I update the DOI in the repo, tag my master, then I upload that release to Zenodo manually and publish it."

It sounds like Zenodo isn't an optimal solution for Bokeh citation. For the colour project (the python implementation of a bunch of specific algorithms), being able to cite or download a specific release for reproduciblity makes the Zenodo hassle more worthwhile. I think adding a citation blurb to the README like SymPy is the better choice.

**Comment by bryevdv** [comment]
The README is an OK location, but it's not a primary place for information, it should go in the Sphinx docs on pydata.org too.

**Comment by bryevdv** [comment]
In master will show up in docs for next dev-build and subsequent releases.
