### ISSUE TITLE
toolbar not working in Chrome, works in Firefox

### ISSUE THREAD

**Issue by PaulSpaven** [bokeh/bokeh#2771]
Date: 2015-08-27
I saw a similar comment on a Google Group, along with the moderator's request that it be added as an issue here on GH. I searched this repo, but did not find a similar issue, so here it is:

Wheel zoom and pan work fine, but no other toolbar options work in Chrome (but they work fine in FF). I am working through the Bokeh quickstart in a Jupyter Notebook.

Chrome Version: Version 44.0.2403.157 m  (latest and greatest)
Firefox Version: 40.0.2 (latest and greatest)
Bokeh Version: 0.9.2
Python: 3.4.3 in Anaconda 2.3.0 (64-bit)
Windows 10 Home

Bokey is fantastic, OBTW. Keep up the GREAT work!

**Comment by bryevdv** [comment]
Is there any JS console output in the browser?

**Comment by PaulSpaven** [comment]
I'm a n00b at all this, so I'm not quite sure. I do, however, get this feedback in my Jupyter notebook when I execute:
BokehJS successfully loaded.
Warning: BokehJS previously

**Comment by bryevdv** [comment]
Here's more info (specifically for Chrome):

https://developer.chrome.com/devtools

**Comment by bs1234** [comment]
I had a similar issue (using chrome but unable to select bokeh tools).
Turns out it was related to chrome expecting a touch screen.
 
In case it's of use to others, here was my problem:
https://stackoverflow.com/questions/31618177/unable-to-select-bokeh-tools

And the resolution:
http://bokeh.pydata.org/en/latest/docs/faq.html#are-the-tools-not-working-in-chrome-cromium

**Comment by jdugge** [comment]
Issue is being discussed at #1848
