### ISSUE TITLE
Bug in linear_color_mapper palette generation

### ISSUE THREAD

**Issue by dwf** [bokeh/bokeh#2801]
Problem demonstrated [here](http://nbviewer.ipython.org/urls/gist.githubusercontent.com/dwf/3a1fe69fc287b600ad14/raw/bc41d84d44da84bf41fa7cf7df29dc26bd290e03/Bokeh%2520Image%2520Weirdness.ipynb). Basically some of the images get rendered as weird outlines by Bokeh but by nothing else, including matplotlib (see the matplotlib reference below). Looks like an overflow problem maybe? Except dividing by 255.0 and thus casting to float64 doesn't fix it, so I think it must be an overflow problem *after* it's converted back to uint8 for rasterization.

Here's a [self-contained example](http://nbviewer.ipython.org/urls/gist.githubusercontent.com/dwf/d6cb127fff520420da86/raw/d19c28a23c0b4340d65e03f97ae3dc3c4c56c083/Bokeh%2520Image%2520Weirdness%2520Self-Contained.ipynb) reproducing the problem, with the data included (rather than relying on a third party package).

**Comment by dwf** [comment]
These are grayscale images from 0-255, by the way. Another reason I think this is a Bokeh bug: `image_rgba` with the pixels shoved into the first 3 MSB of a uint32 array with 0xFF on the alpha channel renders just fine.

**Comment by dwf** [comment]
To add to this, pulling the data out of the JSON suggests (perhaps this is obvious to those more familiar with Bokeh's architecture) that the problem is between model and canvas, i.e. somewhere in BokehJS.

**Comment by dwf** [comment]
The problem is [here](https://github.com/bokeh/bokeh/blame/master/bokehjs/src/coffee/mapper/linear_color_mapper.coffee#L71-L79). On [line 78](https://github.com/bokeh/bokeh/blame/master/bokehjs/src/coffee/mapper/linear_color_mapper.coffee#L78), `new_palette[i]` is unceremoniously assigned a value of `palette[i]`, with none of the type checking logic from inside the loop. JavaScript of course decides to simply use zero for reasons on which I don't even want to speculate. So, this only works correctly for palettes that are already numbers. Definitely a bug.

But what I don't understand is why there is any need to extend the palette length by one in the first place. That seems unnecessary.

@tswicegood It seems you were the author of this line. Can you explain `new_palette` needs to be of length `palette.length + 1`?

**Comment by bryevdv** [comment]
@dwf the reason for extending the palette is so that the range the mappable range can be an entire closed interval. Consider I have three colors in my palette: `[red, blue, green]`. Now I want to map numbers in the range `[0, 3]` evenly to those colors. So that's easy enough right? Just divide evenly:
```
0 < x < 1  => red
1 < x < 2  => blue
2 < x < 3  => green
```
whoops, those are strict inequalities! Where does 3 get mapped to? If we want to be able to map efficiently by taking a `floor` operation after scaling our real input range *and* be able to handle the "endpoint" of a closed range in a reasonable way, the fairly accepted way to do it is just to extend the palette by duplicating the last color. 

I need more info on why you link line 78 is the problem? It is:
```
new_palette[new_palette.length-1] = palette[palette.length-1]
```
By *definition* the indices are for each array are *less* than the array length, which is why there is no checking. That is, `array[array.length-1]` should be expected to work unconditionally, always.

**Comment by dwf** [comment]
Okay, that makes sense. What doesn't make sense to me is why, in the original notebook up above, some images are getting mapped to 0...palette.length - 2 and thus displaying correctly, while others are getting mapped to 0...palette.length - 1 and not. Shouldn't it be, in theory, always using `new_palette[new_palette.length - 1]` for the maximum value in the 2D grid?

**Comment by dwf** [comment]
Actually, nevermind; it seems that it could be masked by peculiarities in the data. The image not displaying properly in my example seems highly correlated with the max value not being 255 ([here's a map of the original example images](https://imgur.com/AUek39E), the blue ones have a max value of 254). I suppose I don't actually care precisely how it works so long as data don't get remapped in a way that stretches the interval near the top. :)
