### ISSUE TITLE
Picking a date for when PRs must have tests

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2864]
We still have a good number of PRs that come in without tests.

The longer this goes on the less coverage we have, and, I believe it makes things harder for new contributors. 

I'd like to propose that we pick a date/release after which we won'd accept PRs without tests. I would say we could start as soon as after the 0.10 release.

Speaking for myself, as new contributing to the codebase, but still with a good amount of visibility on it, I find that I'm either introducing bugs or that on PR review someone points out another part of the codebase to consider.

In addition to this, the release review process is getting increasingly time consuming as we produce more and more complex features that interact with each other.

I know that even good testing isn't a magic bullet but I do think it would help reduce the burden on PR review, and give new committers more confidence.

**Comment by bryevdv** [comment]
I've added statements to the developer guide basically to this effect. I don't think there can be a blanket hard and fast rule, due to the fact that Bokeh has many different kinds of components and work going on, and not all of it is amenable to testing or certainly unit testing:

* e.g. there's an open PR to add docker support that's just config files
* porting to Typescript PRs where what is important is that *existing* tests continue to work as-is
* Work on build/test automation that can't really be tested without just exercising it

A non-trivial amount of work falls under descriptions like this. So, I think we can go forward with some rules of thumb:

* The python tests are currently at about 90% coverage. Almost anything that touches actual python bindings code should come with tests to improve this number. 

* Pretty much all BokehJS work that is not simple porting/refactoring should come with tests. There's also alot of tests to back-fill for BokehJS and we should try to encourage anyone to add tests at any time.
