### ISSUE TITLE
Dialog widget in flask app do not appear in browser

### ISSUE THREAD

**Issue by matejmertik** [bokeh/bokeh#2884]
Hi guys,

I am using Bokeh for developing scientific app within bokeh applet on bokeh-server (in a way of slider_app example). I have a challenge considering a Dialog widget. As I am not creating session and document (I tryed with cursession and curdoc but the currsession is NoneType object) I can not use the mechanism for saving object in document and document in session which would then execute callback and trigger the dialog in browser. 
I am creating dialog in the class similar that all widgets, but when I am trying to show it with the click on button (self.dialog.visible = True) the dialog does not appear. I thought that _dirty and _callback_dirty properties would help as they did when I am updating ColumnDataSources but they do not. Can somebody help me explain, how I can trigger that the dialog will go from python server side to the js at client in this scenario? Is there some demo? 

Here is my short code in input_change(self, obj, attrname, old, new) function that catch click of the button:

if obj is self.button:
	self.dialog.visible = True
	self.dialog._dirty = True
	self.dialog._callbacks_dirty = True

The SavePreview dialog in tools is working normaly also browser allows use of the windows.

**Comment by bryevdv** [comment]
Hi @matejmertik this discussion refers to the old `bokeh-server`, which has been completely removed, which is why I am closing this issue. The new server has been demonstrated to be much more stable and robust. If you find you have problems with the new server, please open a new issue, but please be sure to include a complete, minimal, runnable test case to reproduce the problem. It is very difficult (sometimes impossible) for us to provide guidance or investigate without code to reproduce the issue.
