### ISSUE TITLE
GMapPlot points disappear on zoom

### ISSUE THREAD

**Issue by avanetten** [bokeh/bokeh#2939]
Points frequently disappear when zooming in the maps_cities.py example (https://github.com/bokeh/bokeh/blob/f5d2327ae1bc7eca08bbd82dbe34049016063cf4/examples/glyphs/maps_cities.py)

![screen shot 2015-10-02 at 1 37 29 pm](https://cloud.githubusercontent.com/assets/3974238/10253344/eded5f74-690a-11e5-83cd-40ecc13991e7.png)
![screen shot 2015-10-02 at 1 37 41 pm](https://cloud.githubusercontent.com/assets/3974238/10253352/f0e5e69c-690a-11e5-8a4d-e433114ae480.png)

**Comment by bryevdv** [comment]
I believe this is only an issue with webgl enabled plots.

**Comment by birdsarah** [comment]
@avanetten - I'm confused, they haven't disappeared in the screenshots you have attached here - I can see them e.g. a collection of spots above San Benedetto. The alpha is very low so when they are not dense (because you're zoomed in) then they are very faint. If you set alpha to 1, you'll see them when you're zoomed in, but the zoomed out map will look ugly.

I'm marking this as invalid, but feel free to re-open.
