### ISSUE TITLE
Cannot pass a field to line_dash glyph property

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2960]
on 

Get error: 

```
ValueError: expected an element of either Enum('solid', 'dashed', 'dotted', 'dotdash', 'dashdot'), Regex('^(\\d+(\\s+\\d+)*)?$') or Seq(Int), got {'field': 'mycolumns'}:w
```

I think it's  valid to specify line_dash (or pretty much any property via a column of data) via `value`or `field`.

**Comment by bryevdv** [comment]
You mean you think it should be? That's possibly reasonable, but that is not the current behavior. The only things that can accept "fields" are the `Spec` properties. There is no `Spec` for this complicated composite property type, which is why it can only take one value. We have talked about making a generic way to "spec-ify" arbitrary other properties, and that would probably be the way to go to pursue this.

**Comment by birdsarah** [comment]
Interesting, I had not delved this deep in to properties before.

Yes, I'd like to see https://github.com/bokeh/bokeh/blob/master/bokeh/mixins.py#L108
`DashPattern` become `DashPatternSpec`

I like the idea of everything being a `Spec` and complex ones can have their constraints computed.

**Comment by birdsarah** [comment]
is there an existing issue for the more generic 'spec-ified'?

**Comment by birdsarah** [comment]
is there an existing issue for the more generic 'spec-ified'?

**Comment by bryevdv** [comment]
@birdsarah, see https://github.com/bokeh/bokeh/issues/1426

**Comment by bryevdv** [comment]
Came up again in newly linked issue, only makes sense for `MultiLine`, related to #6997

**Comment by bryevdv** [comment]
There's has not raised any additional interest in ~3 years. I don't think there is a justification to add this complexity, but happy to consider a PR if one shows up.
