### ISSUE TITLE
custom Bar chart hover tooltips

### ISSUE THREAD

**Issue by wsfax** [bokeh/bokeh#2965]
version: 0.10.0

It is not possible to display custom values as tooltip on mouse hover.

    from bokeh.charts import Bar, show
    from bokeh.models import HoverTool

    data = {'ID': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'Total': [0.0, 20.0, 0.0, 6.0, 8.0, 0.0, 8.0, 5.0, 8.0, 1.0, 2.0]}

    p = Bar(data, label='ID', values='Total', width=400, tools='hover')

    hover = p.select(dict(type=HoverTool))
    hover.tooltips = [('Value of ID',' $x'),('Value of Total',' @Total')]

    show(p)

![image](https://cloud.githubusercontent.com/assets/15049259/10393096/2173d6e8-6e8d-11e5-8373-84a149d8fb3d.png)

**Comment by tonyfast** [comment]
HoverTools on high-level charts are not directly intuitive.  The input data structure is stored in the glyphs on High-level charts.  The original input data structure kept as a column data source.

If you change the tooltip to the snippet below, you should see the total.

```python
hover.tooltips = [('Value of ID',' $x'),('Value of Total',' @y')]
```

Here is [a notebook that relates to this issue](http://nbviewer.ipython.org/gist/tonyfast/7edc7e7b140b83794d89)

**Comment by wsfax** [comment]
ok @tonyfast your solution works except that it should be `@height` not `@y`

but this is not solving the problem I am trying to show here, maybe the example I gave was not good.

suppose now my data is like this:
`data = {'ID': [0, 1, 2], 'Total': [1, 20, 4], 'Desc': ['a', 'b', 'c']}`

Now I can display those information on mouse hover as follow:
'ID' values: @x
'Total' values: @height
'Desc' values: how can you display these values??

**Comment by wsfax** [comment]
Is this a limitation on the charts api? can someone confirm?

As a new user, my impression is that the charts api is very limited or at least not very well documented.

**Comment by bryevdv** [comment]
Bokeh has several APIs, at different levels. The ` bokeh.charts` API is indeed the newest of them, and has only just settled down. However there are still certainly many conveniences and features yet to build out. 

If you look a `bokeh.plotting` examples that use the hover tool, you will often see that they construct a `ColumnDataSource` with all the data needed for the hover tool. Since all Bokeh plots are ultimately the same pile of objects, regardless of what API was used to create them, it is definitely possible in a technical sense to make this work. Charts have the same `ColumnDataSources` internally that any other plots do. But the main idea of `bokeh.charts` is to be a very high level API, which means lower level details (like the data sources) are often handled for you. So, to make this work, you will have to dig around and find the right `ColumnDataSource`, and add new columns (e.g. "Desc") to its `.data` dictionary attribute by hand. 

For sure, this could be made easier. If you have suggestions for how you might like to be able to spell this in python using the charts API, those suggestions would be appreciated. As always, code is also appreciated, we are always interested in new contributors. 

ping @rothnic

**Comment by wsfax** [comment]
thanks for the explanation.
I do agree with you that hiding the `ColumnDataSource` in the charts api make things easier to get quickly started.
However; it also does make other things (like tap,hover tools) more difficult to achieve compared to the plotting api.

I guess from a python high level api point of view; native python types should be supported. So for my specific example I would do it this way:

    data = {'ID': [0, 1, 2], 'Total': [2, 13, 5], 'Desc': ['a', 'b', 'c']}
    p = Bar(data, label='ID', values='Total', width=400, tools='hover')
    hover = p.select(dict(type=HoverTool))
    hover.tooltips = [('Value of ID',' @ID'),('Value of Desc',' @Desc')]

Now the mapping is clear for the user `@AnyDictKey`

**Comment by xguse** [comment]
@bryevdv:

I have the same concern as @wsfax here.  I understand that the charts api is still young.  While I __do__ think that this is functionality that belongs in the charts api over the long run; my interst in the immediate term is to get help on where the ColumnDataSource objects live in the object returned by a charts api class call so that I can do it myself.

Can anyone help me out there?

thanks!

Gus

**Comment by bryevdv** [comment]
@xguse Sure, `Chart` is a subclass of `Plot`, and `Plot.renderers` is a list of all the renderers a plot has. Some of these will be `GlyphRenderer` and those have a `.data_source` attribute which is the `ColumnDataSource`  used by that renderer to draw things.

**Comment by rothnic** [comment]
This is an area that I want to look across the charts/glyphs to see what is the best option. There were cases where the combination of glyphs or the way the glyphs were differentiated, I couldn't use a single, shared ColumnDataSource consistently. So for the majority of the cases each "group" of data the chart differentiates, there will be a separate glyph renderer, which has a ColumnDataSource.

What I need to do is make sure that the label for each "group" is available in the data sources. The reason that the glyph data source is different than the input one is because of aggregation. Imagine you had a dict where there was more than one value associated with a, b, and c. When the data is collapsed down into the rendered data, we just need to keep the label. The data is available because this is what the "DataGroup" class is doing, is relating a unique data label to unique visual attributes.

Not that it helps you now, but just to show you what is going on under the hood:

![image](https://cloud.githubusercontent.com/assets/452052/11567879/e449f566-99ae-11e5-8f21-c71a5cd9557c.png)

@bryevdv: I could easily add this label column to all the glyph renderer data sources in a quick PR

**Comment by bryevdv** [comment]
@rothnic that seems like a fairly quick and useful thing, they they renderer could be selected with:
```
chart.select(dict(name="foo"))
```

**Comment by mdering** [comment]
Sorry, I still don't really see how this works. I have a bar chart that I'm using to show a sort of score calculated from a number of attributes as y, and x is each sample (a name). I'd like on hover to be able to show each of these attributes individually as text. Is there some way I can do this?

**Comment by aussio** [comment]
@mdering I was just looking at this as well so I figured I would reply. There is some example code within the [PR linked above](https://github.com/bokeh/bokeh/pull/3312). 

When you make a Chart, you can use whatever attributes you've used within the chart within the Hover. So if you have a Chart with: `Chart(data, x='displ', y='mpg', color='cyl', marker='cyl', line_color='origin')` you will have access to `'cyl'` and `'origin'` for your hover, so you can use something like:

`Chart(..., hover=[('cyl', '@cyl'), ('origin', '@origin')])`

Hope that helps!

> ps. Sorry for spamming anyone else.

**Comment by slilienfeld** [comment]
Hi all, just wanted to check back in on this.  Has there been progress on this?  I see issue #3312 supports referencing other dataframe columns in the hover as long as they are passed to other chart attributes.  What about updates on the best way to pass columns to the hover tool that are not directly associated with any chart attribute?

**Comment by bryevdv** [comment]
@slilienfeld There is nothing to report on this, there are many higher priorities and very few people with time at the moment. If it's something you are interested in looking at, I can point you in the general direction. 

Otherwise, there are some features in `0.12.2` and coming soon in `0.12.3` that make creating bar charts, with legends, color mapping, and tooltips much much simpler with `bokeh.plotting`. I would suggest that as an alternative.

**Comment by slilienfeld** [comment]
@bryevdv thanks for the update.  Would love to be able to assist on this issue - happy to take a look at the relevant code but unfortunately am pretty inexperienced in python, so not sure how much help I'll be.  Really appreciate all the work being put into Bokeh.

Will definitely take a look at those new features you mentioned.
