### ISSUE TITLE
interact with bokeh plots from Javascript in notebook

### ISSUE THREAD

**Issue by wsfax** [bokeh/bokeh#2987]
Is it possible to interact with a bokeh plot from another javascript within pynb ?

see this example to better understand the situation: http://nbviewer.ipython.org/gist/wsfax/11edfe0673991c3cabd0

basically I would like to click on an html button in my pynb that calls a javascript "exec_code" function. Now from that javascript function is there a way to call my `s.callback` that I defined in bokeh?

To make it simple I want to click on "Call s.callback" push button and see the "hello" pop up message.

**Comment by bryevdv** [comment]
Certainly this is possible, all Bokeh views are available in `Bokeh.index` and from there can be searched for the callback, which you could execute yourself. There may be better or other ways. However we are now referring all general support questions to the mailing list so that a wider audience has a chance to answer (and so we can keep the tracker more manageable) Please do ask this question there: https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh
