### ISSUE TITLE
Selection bug for plot of multiple columns on the same plot from the same data source

### ISSUE THREAD

**Issue by amcpherson** [bokeh/bokeh#2989]
When I use multiple plotting calls (eg Figure.scatter) to plot multiple columns from the same data source, there is a bug causing problems with selecting data points.

A minimal example reproducing the error is below, and can be run with bokeh-server.  Upon selection of data points they are either unselected or flicker and remain selected.

```
import numpy as np
import pandas as pd

from bokeh.plotting import figure
from bokeh.models import Plot, ColumnDataSource
from bokeh.properties import Instance
from bokeh.server.app import bokeh_app
from bokeh.server.utils.plugins import object_page
from bokeh.models.widgets import HBox


class TestApp(HBox):
    extra_generated_classes = [["TestApp", "TestApp", "HBox"]]

    plot = Instance(Plot)
    source = Instance(ColumnDataSource)

    @classmethod
    def create(cls):
        obj = cls()

        data = pd.DataFrame(np.random.randn(20, 4), columns=['x', 'y', 'z', 'w'])

        obj.source = ColumnDataSource(data=data)

        obj.plot = figure(tools='box_select')
        obj.plot.scatter('x', 'y', asdf=1, source=obj.source)
        obj.plot.scatter('z', 'w', source=obj.source)

        obj.children.append(obj.plot)

        return obj


@bokeh_app.route("/test/")
@object_page("sin")
def make_sliders():
    app = TestApp.create()
    return app

```

**Comment by azjps** [comment]
I don't believe that charting multiple slices of a single ColumnDataSource in a single figure is explicitly supported. It should work if you provided two separate ColumnDataSources, one for ['x', 'y'] and the other for ['z', 'w'].

On the js side, each ColumnDataSource is associated with a single selection manager which stores a single selection slice. [The selection tools](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/tool/gestures/box_select_tool.coffee#L60) update the selection manager for each glyph renderer in a loop, so a selection in your example would probably arbitrarily select rows associated with the second series charted.

I somewhat doubt this will be "fixed" anytime soon, but I'd suppose the way to go about fixing it would be to construct selection managers per renderers instead of per ColumnDataSources. That might not be desirable though since ColumnDataSources selections can be done in other ways in the UI besides through chart renderers.

**Comment by amcpherson** [comment]
For my particular use case, I need to represent each data point with two scatter points in a 2d plot, and selection of either should select the pair, and also select a row in a corresponding data table.  Perhaps the way forward would be for me to create a custom glyph for plotting this type of data.

**Comment by amcpherson** [comment]
Ill admit I havent looked at the internals, but I am not sure why an interaction, such as a box select, doesnt trigger a single update of the selection slice, which then in turn triggers an update of each glyph according to the new slice.

**Comment by azjps** [comment]
I see, I misunderstood your use case (I thought you wanted to be able to have multiple independent selections on your ColumnDataSource). It shouldn't be too hard to add a patch to bokehjs to append multiple selections in the  in the selection tool loop:

```coffee
    # bokehjs/src/coffee/tool/gestures/box_select_tool.coffee#L60
    for r in @mget('renderers')
      # Reset all selection indices
      r.get('data_source').get('selection_manager').clear(@plot_view.renderers[r.id])
    for r in @mget('renderers')
      ds = r.get('data_source')
      sm = ds.get('selection_manager')
      # Append selections if multiple hits on the same selection manager
      sm.select(@, @plot_view.renderers[r.id], geometry, final, true)
```

(Although, I don't know if this actually works or if it has any bad side effects. My knowledge of the internals is likely not much better than your's :smile:) 

I think it would be even nicer for bokeh to accept "selection groups" where the entire group becomes selected when any one row is selected. I do imagine it would be a relatively common request when charting mixed datasets.

**Comment by bryevdv** [comment]
This is a very old issue state in terms of the original bokeh server which is long gone. Along with some of the current work around filterable and groupable CDS, there is also a (currently stubbed) Wiki document to discuss a complete overhaul of the selection machinery in bokeh here:

https://github.com/bokeh/bokeh/wiki/Selection-Architecture-Refactor

I'm going to close this issue and would encourage anyone to contribute thoughts about requirements, etc in the wiki doc.
