### ISSUE TITLE
Selection on new Scatter chart

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#2994]
See this notebook: https://notebooks.anaconda.org/birdsarah/scatter-chart-select

The selection is not selecting the items I expect it to inside the box. Other items are remaining selected while some are deselected.

Here is the plot with nothing selected:
![screen shot 2015-10-14 at 5 37 30 pm](https://cloud.githubusercontent.com/assets/1796208/10500102/458d17f8-729b-11e5-87ae-213d33c081d4.png)

With selection box in top left:
![screen shot 2015-10-14 at 5 42 28 pm](https://cloud.githubusercontent.com/assets/1796208/10500104/4a4bae30-729b-11e5-8c63-dab961359f33.png)

And selection box in bottom right:
![screen shot 2015-10-14 at 5 42 45 pm](https://cloud.githubusercontent.com/assets/1796208/10500107/4f7f1590-729b-11e5-9391-942e171696b0.png)

To my eye, there are dots outside the selection selected.

**Comment by birdsarah** [comment]
ping @rothnic @fpliger

**Comment by bryevdv** [comment]
@canavandl please check if this is still happening.

**Comment by fpliger** [comment]
The reason this happens is that charts have one specific datasource per glyph so when you select the upper or bottom corners not all datasources are caught... Here's what happens when hitting the center area..

<img width="648" alt="screen shot 2015-12-30 at 3 29 15 pm" src="https://cloud.githubusercontent.com/assets/1084690/12057802/722d02fe-af0a-11e5-994d-3bdc76799d32.png">


I can't think of an "easy" fix atm.. I think the charts case have exposed a few scenarios for a sort of composite datasource where we can specify depencies and derived sources (this would be helpful also when we need to access the original data when hovering or interacting with an Aggregated glyph).

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/30)
