### ISSUE TITLE
DataTable sorting appears to be broken by np.nan

### ISSUE THREAD

**Issue by SimonBiggs** [bokeh/bokeh#3040]
Sorting in a DataTable appears to be broken when sorting with columns that contain np.nan. An example of this can be found here:

http://simonbiggs.github.io/electronfactors

By pressing the "Prediction Diff. (%)" column sometimes the items immediately adjacent to the rows containing np.nan are not sorted correctly. Two examples when this occurs is if sorted by "Model factor" then "Prediction Diff", or if sorted by "Prediction Diff" four times.

**Comment by dennisobrien** [comment]
There are a few issues related to applying a formatter to Nan, Infinity, or -Infinity.
#3120 
#2922

**Comment by bryevdv** [comment]
@SimonBiggs I realize it has been some time but I'm currently doing some cleanup work around data tables. Do you have a complete code sample that reproduces the issue that you can share?

**Comment by SimonBiggs** [comment]
I should be able to find it. Give me a few days. Try me again if I forget.

**Comment by bryevdv** [comment]
I added these lines 
```
mpg = mpg[:10]

import numpy as np
mpg['cty'][5] = np.nan
``` 
to `models/file/widget.py` to test. When I sort the adjacent columns, the sort appears correct, regardless of whether I also sort the column with the nan in it (which itself sorts badly, but there's a nan so not sure could be done). So I think any issues with adjacent columns have been fixed by recent work on implicit table indices. If there is still a reproducible problem, please open with complete *python* code to reproduce, as well as instructions, screenshots, etc

**Comment by SimonBiggs** [comment]
Will do. Thanks Bryan.
