### ISSUE TITLE
Re-implement bokeh-server index page 

### ISSUE THREAD

**Issue by dwf** [bokeh/bokeh#3087]
*This description is somewhat out of date to where the discussion has gone, and seems to be Bokeh 0.10 specific.*

I'm hitting a weird snag when trying to update an image plot. This is Bokeh 0.10.0 running on Linux x64, with Chrome 46.0.2490.80 on Mac OS X 10.10.5.

What I'm trying to do is continually update a plot with (quite a few) small images arranged in a grid (code to reproduce the problem below, run it with `--store-datasource` and `--store-document` to cause the broken behaviour).

It works if I `store_object()` on the figure object (except it annoyingly resets the viewport), it works if I `store_object` on the Image renderer's datasource but *don't* `store_document` after that (that results in the plot title not being properly updated). (Of course, if I *just* `store_document`, I get the plot title updating but not the actual images.)

But if I `store_object` on the `data_source` and then `store_document`, I might get my desired behaviour for a little bit, but then weird things start happening. Only a subset of the images get updated, some of the images have weird artifacts, or things stop updating altogether and I see JavaScript SyntaxErrors in the JS console. I've seen a bunch of them, here are a few of the tracebacks:

```
Uncaught SyntaxError: Unexpected number
(anonymous function) @ socket.coffee:61
triggerEvents @ backbone.js:207
Backbone.Events.trigger @ backbone.js:148
WebSocketWrapper.onmessage @ socket.coffee:36
(anonymous function) @ socket.coffee:1
jsnlog.js:589 Bokeh: load_models: start
```

```
Uncaught SyntaxError: Unexpected token ,
(anonymous function) @ socket.coffee:61
triggerEvents @ backbone.js:207
Backbone.Events.trigger @ backbone.js:148
WebSocketWrapper.onmessage @ socket.coffee:36
(anonymous function) @ socket.coffee:1
jsnlog.js:589 Bokeh: load_models: start
```

```
Uncaught RangeError: Source is too large
ImageView._set_data @ image.coffee:39
GlyphView.set_data @ glyph.coffee:120
GlyphRendererView.set_data @ glyph_renderer.coffee:69
triggerEvents @ backbone.js:208
Backbone.Events.trigger @ backbone.js:148
_.extend.set @ backbone.js:368
HasProperties.set @ has_properties.coffee:140
load_models @ load_models.coffee:91
(anonymous function) @ socket.coffee:63
triggerEvents @ backbone.js:207
Backbone.Events.trigger @ backbone.js:148
WebSocketWrapper.onmessage @ socket.coffee:36
(anonymous function) @ socket.coffee:1
```

```
socket.coffee:21 WebSocket connection to 'ws://localhost:5006/bokeh/sub' failed: Invalid frame header
```

etc. etc.

Below is some code that reproduces. When running with both options, try zooming in and out around the viewport a bit, that seems to trigger it a little bit faster.

```python
import argparse
import time
import numpy
from bokeh.session import Session
from bokeh.document import Document
from bokeh.models.mappers import LinearColorMapper
from bokeh.plotting import figure


parser = argparse.ArgumentParser()
parser.add_argument('--store-document', action='store_const',
                    const=True, default=False)
parser.add_argument('--store-datasource', action='store_const',
                    const=True, default=False)
args = parser.parse_args()

doc = Document()
session = Session(root_url='http://localhost:5006/')
session.use_doc('docname')
session.load_document(doc)
palette = [('#%2x%2x%2x' % (c, c, c)).replace(' ', '0')
           for c in range(256)]
mapper = LinearColorMapper(low=0., high=100., palette=palette)
plot = figure(x_range=(0, 10), y_range=(0, 10))
data = (numpy.arange(100, dtype='float32').reshape(100, 1, 1) *
        numpy.ones((100, 28, 28), dtype='float32'))
plot.image(list(data), dw=0.95, dh=0.95, x=numpy.arange(100) // 10,
           y=numpy.arange(100) % 10, name='image_glyph',
           color_mapper=mapper)
doc.add(plot)
plot.title = 'START'
session.store_document(doc)
time.sleep(10)
for i in range(500):
    renderer = plot.select(name='image_glyph')[0]
    data_ = data.copy()
    numpy.random.shuffle(data_)
    data_ += numpy.random.uniform(0, 5, size=data.shape)
    renderer.data_source.data['image'] = list(data_)
    if args.store_datasource:
        # Everything *seems* to work okay doing this as long as we don't
        # store_document at the end of the loop (and then the plot title
        # doesn't get updated).
        session.store_objects(renderer.data_source)
    else:
        # Everything works okay if we do this, except that the viewport
        # positioning of the plot is reset.
        session.store_objects(plot)
    plot.title = 'Iteration {}'.format(i)
    if args.store_document:
        # If we do this AND do a store_objects on the data source, we
        # run into all sorts of weird WebSocket errors on the JavaScript
        # console, and the plot just stops updating.
        session.store_document(doc)
    time.sleep(5)
```

**Comment by birdsarah** [comment]
Hi David,

Bokeh server has been completely re-writtenand pushed into masterand
will be coming out with Bokeh 0.11.

There are still rough edges in master, and there's currentlyno
docs.....but you may be better off trying there.

The good news is, things are much simpler now, so in spite of both of
those caveats things should be easier.

There's a dev build out: conda install -c bokeh/channel/dev bokeh

In addition, the examples should all be up to date on master
(https://github.com/bokeh/bokeh/tree/master/examples) for how to work
with the new server. Something like
https://github.com/bokeh/bokeh/blob/master/examples/plotting/server/line_animate.py
shows updating a datatsource. And for updating the title should be as
simple as:
https://github.com/bokeh/bokeh/blob/master/examples/app/sliders_applet/sliders_app.py#L105

In particular you use:

session =push_session(curdoc())
session.show()

and then you can just update the datasource

ds.data["y"] =y *i

Hope this helps,

Sarah Bird

**Comment by dwf** [comment]
Hi Sarah,

Thanks for getting back to me so quick. I tried out the new Bokeh, and it seems to work a bit better! The updating doesn't seem to break like it does with 0.10.x.

I was deliberately trying to not use `curdoc()`, `cursession()` etc. and opt for explicit management, as multiple parts of the same program might be interacting with different documents via different sessions in my setup. However with the new interface it seems like one only needs to interact with that module-level state at initial setup time, and thereafter plots stay linked to their respective sessions, which is quite handy.

Unfortunately the index page that we'd been using as a quick-and-dirty monitoring dashboard has gone away. :disappointed: Any idea whether that's coming back or how one might go about constructing one (basically enumerating the server-side documents and displaying them each in an iframe or something)?

**Comment by birdsarah** [comment]
Hi David,

Glad to see you've made some progress.

Idon't think there are any immediate plans for the dashboard to come
back. Bryan or Havoc may have a better notion of this.

I think part of the point of the server re-write was to dramatically
simplify it down to its core function of keeping a document in sync
between the server and client, which you've now seen it's doing better.
So I'm not sure it'll be coming back. That said Iremember a previous
thread where someone was talking about the server homepage being acheap
dashboard so there may be community interest in some kind of add-on that
supports this.

Ihaven't had enough of a chance to play with the server yet to know how
you'd roll one yourself although I can't imagine itwould be too difficult.

Sorry to not be more help,

Bird

**Comment by dwf** [comment]
Yep, I've been having a look around the server/ and application/ directory,
making note of the terminology being used for things.

Seems like I want for a debug dashboard is a Handler subclass that iterates
over the ApplicationContexts in the BokehTornado object, and then iterates
on the sessions. Of course, that means touching underscored attributes...

**Comment by havocp** [comment]
I'd support adding a debug-inspector kind of page to server/urls.py but it should probably be for `--develop` mode only. An "index" kind of page could also be useful, that would be available in production, which might initially be similar to debug but it would be more user friendly (just links from document.title to app or something, no sessions, listing sessions would be insecure if Internet-facing). 

To avoid underscored attributes I'd say add the needed methods, or pass the needed stuff to the handler in tornado.py, I'm not sure which one feels right (depends on what's needed).

For a case like yours though maybe you really want support for building a custom page... ? We want to make it clearer/better/documented to build a Flask or Django or Pyramid or whatever app "around" the Bokeh server. Another idea would be to allow a Bokeh app to query info such as the other apps on the same server, so you could write an index app in Bokeh itself, however there's a little chicken and egg going on there that could be interesting to figure out.

Re: curdoc() for push_session you don't have to use it you can make your own Document instance. For a `bokeh serve` script you do need to set up curdoc though.

**Comment by bryevdv** [comment]
Just to add my persepctive: an "index" page is still on our To-Do list, but it's not really a high priority at the moment. Our primary use case centers around a "spin up a server (or servers) per app" type usage. But I don't think it would be too terribly hard to add an index handler (that could be optionally enabled). If you're interested in wokring on it, we could definitely help, (e.g we have a designer who could guide the visual styling if you get a basic implementation working). 

As Havoc mentions, a custom page is another options, and the new server can actually be configure with additional, custom Handlers via an "extra_patterns" argument very easily:

	https://github.com/bokeh/bokeh/blob/master/bokeh/server/tornado.py#L41

This might even be a better starting place to experiment with various ideas.

Bryan

**Comment by dwf** [comment]
Hmm yes I saw that argument.

To help frame how we use Bokeh, let me try and briefly explain our setup. We have a [library for doing machine learning research](/mila-udem/blocks). The typical experiment (here's a short [example](https://github.com/mila-udem/blocks-examples/blob/master/mnist/__init__.py)) involves doing descent on some objective function, which we break down into a "main loop" that drives a (minimization) "algorithm", and also zero or more "extensions", basically stateful callback objects that get run at various user-configured stages. These can do things like print reports, save checkpoints, and stick values in a log, the last of which it's sometimes nice to monitor with a graph. We [use Bokeh in one such extension](https://github.com/mila-udem/blocks-extras/blob/master/blocks/extras/extensions/plot.py) (and I privately have another similar extension that plots images, which I currently use in conjunction with a slightly modified version of this thing to concurrently plot line graphs and images in separate server-side documents). 

Our users are building short scripts that try out some idea, not really building full-fledged applications. They might be running several of these in parallel, perhaps on a cluster, all reporting to one Bokeh server. The existing `bokeh-server` index page is a nice way to see whatever plots have been configured in the script without having to keep track of separate URLs for different documents/plots.

@bryevdv I'd be happy to try my hand at it, probably not earlier than next week though. Though I have some questions about the design of things.

One thing I'm interested by: @havocp mentioned that internet-facing list of sessions would be bad, but what used to be called "Documents" on the server seem to be called "sessions" now, or at least indexed by something called a "Session ID". Am I misunderstanding that?

Also, I see some logic in the codebase to clean up inactive "sessions" after a timeout. Am I to understand that these new documents/sessions don't stick around indefinitely like they used to? Are they tied to the lifetime of the client-side object in some way?

**Comment by havocp** [comment]
The old server was a persistent "place to publish documents," keeping them in Redis. Part of the problem with the old server is that it conflated "the application" (the canonical or template document) with "the current state." So for example, if you moved a slider, that changed the slider's value for everyone using the app.

The new server doesn't really rename documents to sessions, instead it splits these two things apart. There's now Application which is like a document factory or template, and Session which is a live document instance used by one browser tab.

output_server still works but it's really only useful for say messing around with a local notebook because it isn't creating any persistent state, just a transient session.

If you haven't seen it, these documents may be helpful:
 https://github.com/bokeh/bokeh/wiki/BEP-5:-New-Document-API-and-document-driven-server
 https://github.com/bokeh/bokeh/wiki/Porting-guide:-new-Bokeh-server

For a scenario like yours, one stopgap possibility would be something super simple such as a directory full of scripts, and then run `bokeh serve` to launch all of them in the server; do a cron job or something that restarts `bokeh serve` if any new scripts are dropped in the directory. I think we may not have a way to launch multiple scripts at once in `bokeh serve` right now, but the underlying code (the Server class) supports doing so, what's missing is only command line syntax or config file. I'll add the multi-app case to our todo list.

There are security issues with this obviously if any of the apps or users are "untrusted" but it sounds like you're all behind one firewall.

So what I was saying is that the index page in production should list applications rather than sessions, but for debug kind of purposes, and possibly also for your purpose, it could list sessions. An issue in your situation though is that the sessions are just in memory, not in Redis.

In an internet-facing setup, sessions would normally have cryptographically-random names because we don't want user A to connect to the session for user B and mess with their instance.

I apologize for the churn here vs. old bokeh-server.

**Comment by dwf** [comment]
I see. Yes, we're basically just relying on plots being in memory as it is now -- we're not super concerned with keeping the data there being uber-persistent, as we typically do checkpointing of the MainLoop object, from which we can construct whatever plots we like after-the-fact. But when you say "transient", how transient are we talking? :smiley: Will sessions persist until explicitly destroyed (or is it at least possible to configure the Bokeh server that way)? Might they cease to exist if they aren't pushed to or accessed for a while? 

Is `output_server` going away in the medium-to-long term? Are we foolish to rely upon it?

If I understand correctly, we were using the new Bokeh server "as intended", we would have a server running one or more application instances (maybe one for our line plots from a particular experiment, one for our line plots from a different experiment, one for our image plots from another experiment) with which our experiments communicate somehow, which each receive the data from a running experiment. When someone accesses the Bokeh Application (which is running inside a Tornado application of our design, which maybe indexes the Bokeh applications that are registered), *that* spins up a session which creates the actual plots for the user to interact with, and that session is per-user and persists for some indeterminate amount of time. Do I have that right? And we'd need to develop some wire protocol for feeding data to these Bokeh applications from any running experiment, either by sharing some kind of database backend or ZeroMQ socket or possibly some kind of HTTP-based communication?

**Comment by havocp** [comment]
Sessions time out right now if there are no connections using them, but we were going to make that configurable. Another possibility would be to only time out auto generated session IDs and not human readable ones.

I don't think there's anything wrong with output_server it just has the limitation that sessions are transient. push_session is also often more useful now since it keeps the connection open which may be more efficient.

You shouldn't have to develop your own IPC. The idea is to add more stuff in bokeh/application/spellings such as a RedisHandler or really whatever handlers are useful, and so to add more data to an app you could shove the data in Redis for example. Though a handler which listened on zeromq or something is certainly another option. There's also a new add_periodic_callback feature which landed on master today which could be used to poll for updates from any source.

**Comment by havocp** [comment]
One other thing I thought I might elaborate on, it should be reasonably straightforward to replicate exactly what the old server provided, with a couple of functions like:
```
   store_document_in_redis(redis_url, document)
   document = load_document_from_redis(redis_url)
```

Then you'd make a `bokeh serve` script that does `load_document_from_redis` and watches or polls Redis for changes, and your publish script instead of output_server would store_document_in_redis. That would be approximately what the old server did. If you stored the doc in Redis as a giant string (document.to_json_string / from_json_string) the load/store in Redis would be a few lines of code, though it would be possible to come up with a fancier scheme no doubt where the document was broken down into more like a native Redis data structure.

Or one could even skip Redis and put the json in a file...

We should probably have an example along these lines.

**Comment by birdsarah** [comment]
I've renamed this from `store_object on Image data source followed by store_document causing WebSocket errors` to `Re-implement bokeh-server index page` because that's where the meat of the discussion on this issue now is. I hope that's ok @dwf. Feel free to shout / change it back if you're not happy.

**Comment by bryevdv** [comment]
OK, I think this issue got a bit off-topic, and is also a dupe of #322
