### ISSUE TITLE
Data streaming for charts

### ISSUE THREAD

**Issue by softengash** [bokeh/bokeh#3142]
Using bokeh 0.10.0

For data streaming, key is to update the data source and the plot gets updated with the latest data. But how to achieve the similar thing for a chart(bar chart)?

Is there any attribute for charts using which its data (data frame or x/y) can be updated?

Kindly advise.

**Comment by bryevdv** [comment]
Not currently but this recently came up for me as well. ping @rothnic @fpliger 

It would be very nice if an existing chart could be "reused" by simply changing the `data` param to a new DataFrame, keeping everything else (as much as possible) the same.

**Comment by fpliger** [comment]
+1

It's probably more a matter of finding the better (convenient) API for this and shouldn't be hard

**Comment by softengash** [comment]
is there any workaround to get its data updated (customJS and/or streaming) for now?

**Comment by fpliger** [comment]
Definitely not for customJS (and this should be a hard task)..
Streaming is the most easiest one (or less hard). @rothnic do you have a simple solution out of the box? 
Trying to figure out quickly about this we could make the builder recompute al the groups with the new data and then remap those on the existing renderers.. 

I'll try to play with it later today.

**Comment by fpliger** [comment]
After quickly looking at how this could work, I will take that back. I don't think it'd be "hard" to do it but a but a bit cumbersome as the different actors in place (`Charts`, `Builders`, `CompositeGlyphs`, `DataGroup`) are too strongly coupled. If we changing this making them more loosely coupled where it makes sense (data transformations i.e.) and keep some tracking of these and the related CompositGlyphs/Renderers we can make it happen.

Again, I'd wait for @rothnic here as I may be slipping out something ...

**Comment by rothnic** [comment]
I think the main issue here is high level charts can produce many different outputs and may transform the input data. It isn't actually the input data that needs to be "updated", it is the internal derived data that is feeding the glyph renderers. It is a bit different than the typical bokeh example because usually the quantity of glyph renderers and glyphs are constant, and you are varying the data. With charts, you can change the input data, but the number of glyph renderers/glyphs can change as well.

What needs to happen is the composite glyphs should yield rows for a data source and glyphs. The reason it must yield glyphs as well is because some attributes of glyphs cannot be vectorized at the moment into a ColumnDataSource (e.g., line pattern). The builder would manage the received rows and glyphs and its glyph renderers. I've been planning to do this, but have been waiting for the server refactor to settle in a bit so I don't waste time chasing moving parts.

While they are somewhat coupled at this point, I think it is much less than it may seem. There is a little bit of cleanup needed due to just trying to get things working at this point, but CompositeGlyphs have from the start been created to be usable completely on their own. The main thing they are producing is consistent data that can feed a glyph. It encapsulates the type of logic such as, "if I received x, but not y values, then I do z", while also simplifying the interface so that it only take a single attribute. CompositeGlyphs do not accept an array of colors, for example.

## Current
- table-like data => Builder => DataGroups with unique attributes
- array or arrays + unique attributes taken from DataGroups => CompositeGlyph => GlyphRenderer(s)
- Builder => legend items, ranges, glyph renderers to Chart

## What I think needs to happen
- table-like data => Builder => DataGroups with unique attributes
- array or arrays + unique attributes taken from DataGroups => CompositeGlyph => Rows of data
- (first time) Builder => legend items, ranges, glyph renderers to Chart
- (subsequent times) Builder => legend items, ranges, data to update glyph renderers

[Here](https://gist.github.com/rothnic/54b049eaa26fe0ec1f2d) was a quick workaround for an interactive Chart before the current server refactor. I still needed to deal with avoiding the need to have lots of glyph renderers. This isn't relevant to what I just discussed, but does show where I'm collecting the new derived data produced by the composite glyphs to update the existing glyph renderers.

I'll see if I can get an example working.

**Comment by rothnic** [comment]
Ok, this is pretty hacky because I'm working around the issues that I described above that should be fixed, but [here is a working interactive bar chart](https://gist.github.com/rothnic/1264a204776d711afeb4).

I think some of the confusion is because I'm using HasProps both for convenience of type checking etc, and for future potential serialization. However, the majority of charts never goes to the javascript side, it is just used to automate the generation of data, glyphs, and renderers. In the linked script I create an initial bar chart, then create a new one on each update, and use the new one's data to update the data on the initial bar chart.

**Comment by rothnic** [comment]
Here is a gfycat of what that looks like. Click on the image below, or hover if you have imagus/hoverzoom. (Ignore the axis labels)

[![image](https://cloud.githubusercontent.com/assets/452052/11291991/1b7d12ea-8f0d-11e5-9401-ddea7bcdc2e0.png)](http://gfycat.com/InexperiencedShrillBasil)

**Comment by phumke** [comment]
+1

This is great is exactly what I was looking for.  Would this also handle updates to the source data?  Do you have a rough eta on when you might be able to include this into the baseline?

A couple of other issues that looked related and could be solved with this as well were #2039 and #3026.

**Comment by Punchwes** [comment]
now the code didn't work any more....is there any solution to achieve the same thing

**Comment by bryevdv** [comment]
Please provide more info. Versions, what changed, etc.

**Comment by Punchwes** [comment]
the code he shows above, you said it can't work with bokeh >0.9@bryevdv

**Comment by Punchwes** [comment]
and i tried using rect to create interactive bar, but i failed to transmit my x data into rect's x_range.
my x_data is a CSV file(which has many rows), I have no idea how to transform it into array or list.

**Comment by modvezina** [comment]
I'm currently using Bokeh 0.12.1 is there a workaround for this situation.  Is there some way to update the data with some kind of 'refresh' button instead. My stacked bar chart use 12 slider as variable for the calculations to build the DataFrame. I am not looking for speed or fluidity, I want to show the result .

**Comment by bryevdv** [comment]
Bokeh `0.12.1` has new `vbar` and `hbar` glyph methods, that make it much simpler to create bar-like charts from the `bokeh.plotting` interface. The `bokeh.plotting` interface is much more suited  for streaming data, at least at present. So my suggestion for now, if streaming/updating is a requirement, would be to use `vbar` and `hbar` instead.

**Comment by modvezina** [comment]
@bryevdv  vbar and hbar are not displaying for now. I suppose it's generalized because the [examples](http://bokeh.pydata.org/en/0.12.1/docs/reference/plotting.html) don't display either.  

1. Where should I address the issue?
2. Is this temporary?

**Comment by bryevdv** [comment]
@modvezina that appears to be a bug with "auto-range" specifically with respect to `vbar` and `hbar`. The example you linked works e.g. if you add `x_range=(0,4), y_range=(0,4)` as arguments to `figure`. I would suggest setting the ranges explicitly as an immediate workaround. 

Can you file a separate GH its for this bug?

**Comment by bryevdv** [comment]
@modvezina actually no issue is needed, it turns out a broken index is the same underlying problem for hit-testing vbar/hbar for hover. I have  PR ready and will close the other issue with it.

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/29)
