### ISSUE TITLE
Document breaks with roots that are also in non-root layouts

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#3146]
Following discussions in #3131

Currently:

```
f = figure()
```

Works:

```
f = figure()
vbox = VBox(children=[f])
curdoc().add_root(vbox)
```

Breaks  because it's both a root and a child. When you render a document to HTML, we render all the roots in a sequence (sort of in an implicit vbox). So if you also add a root plot to another container, that plot is in two places, which bokehjs doesn't support.

We  already have a validation warning, but it makes the convenience figure() API a little confusing. Maybe a solution is to make embed.coffee ignore roots that are also in non-root layouts.

**Comment by havocp** [comment]
A fix here could be similar to the fix for https://github.com/bokeh/bokeh/issues/3117 , that is it's another check to make before we `render_model`. It's simple enough to add an "is this root in a layout also" check there.

A way to make this hard is that a model can be in only one place at first, but then be added in multiple places later; or vice versa, in two places then only in one. Also, being both a root and in an hbox isn't the only possible problem, a model could also be in two hboxes for example. In theory we should handle those cases. However, doing so would be pretty hard I think, so maybe we should start with the easy thing and screen out or screen in rendering roots based on whether they are reachable from another renderable root. (Renderable = has a `default_view` perhaps, as noted in #3117)

I don't know. Now that I write that down, I hate solving this in a known-broken (does not dynamically update) way, and I also think handling dynamic updates would be too hard. So that whole approach might be bad.

Another possible approach could be that when a container like HBox is constructed, it would remove all passed-in children from the roots as a side effect, much like `vplot` does: https://github.com/bokeh/bokeh/blob/57203a7668687aacf92c47795affd7da0c83d017/bokeh/io.py#L461
This is sort of a weird side effect, but maybe it's less trouble than trying to fix things up on the client side.
With this approach the validation warning would not happen.

I think I like either the `_remove_roots` in HBox/etc. answer, or the validation warning like now, as solutions.

**Comment by bryevdv** [comment]
I agree there are not great options. I think I like the `_remove_roots` in `HBox` etc. If we do that can we also deprecate `hplot` and `vplot`, etc?

**Comment by havocp** [comment]
hplot would still add the HBox as root, while HBox doesn't.

 I kind of feel that figure/hplot create a lot of confusion to save the one add_root line.

but they are also widely used APIs.

If they were called add_figure, add_hbox etc that would be a lot clearer ...

**Comment by bryevdv** [comment]
My other problem with `hplot` is that it can hold more than plots. It is is a bad name (my fault) but I'd like to rectify this situation before `1.0`, ideally deprecating whatever needs deprecating now. 

One options woul be `hbox`, `vbox`, `grid`, `figure` are all "smart" and manage adding to documents. But `HBox`, `VBox`, `Grid`, `Figure` are all just "dumb models". That would have a nice informal upper/lower case convention that would be OK to point to. But that breaks down if `Charts` are going to  manage adding themselves to docs. 

The `add_XYX` is an interesting idea, but it also would have convention broken by `Chart` So is there anything reasonable to do differently with charts? If not I think my slight preference is for the first above, just to keep `figure` (which is entrenched at this point).

**Comment by bryevdv** [comment]
Fixed by recent layout work
