### ISSUE TITLE
Fix commented out `push_notebook` method from ColumnDataSource

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3149]
In ColumnDataSource there is a commented out method `push_notebook` https://github.com/bokeh/bokeh/blob/master/bokeh/models/sources.py#L222

It seems to have been removed around the time of the great server redo, in a commit called "lots of cruft removed, tests running" https://github.com/bokeh/bokeh/commit/d27a848192d9f57d8d895e8fa8864c94bcc8fbe5

Should we just get rid of it? ping @damianavila @bryevdv @havocp @fpliger

**Comment by bryevdv** [comment]
No it needs to be restored, the notebooks with ipython widget interactors depend on it. Ideally it is restored in a better way that does not leak memory but just getting back to where we were would be OK for now.

**Comment by havocp** [comment]
One idea to implement this would be to keep a global set of all Document instances that have been rendered by embed.coffee, accessible as Bokeh.embed.documents or something. Then have a Bokeh.embed.update_model that looks for a
provided model ID in each rendered Document and updates it. There's an issue with how and whether to handle references to other plot objects in the update; simplest is to say they aren't allowed. The issue here is that the model being updated may refer to models that the rendered doc doesn't know about, but we don't know what it knows about, so how do we provide needed models without sending the entire doc.

Or totally different idea: make bokeh.io in output_notebook mode able to send diffs. That is, whenever you show() we record the json we sent... next time you show() we only send what's changed? or maybe don't overload show() have a special API for this that can checkpoint a doc and then diff a modified doc vs a checkpoint, and apply a diff? I have something much like that in coffee script already.

not sure.

**Comment by damianavila** [comment]
> just getting back to where we were would be OK for now.

I agree...

**Comment by damianavila** [comment]
Interesting ideas... but just to give you context, the memory leak comes from the fact that we are using the display machinery to "show"/send the changes... we need to use something deeper, like comms, I guess, to send the "update" info regardless of the way with deal with the update itself...

**Comment by havocp** [comment]
above ideas not meant to solve the mem leak, just get it working again :-)

to solve the leak I wonder if there's some way to effectively run a transient server, or some way to have a self-deleting script tag...

**Comment by fpliger** [comment]
> just getting back to where we were would be OK for now.

+1

**Comment by havocp** [comment]
I wonder if script tags can remove themselves from the Document at the end of the JS... ?

**Comment by bryevdv** [comment]
I'm going to make a stab at using Jupyter comms based on this info:

http://stackoverflow.com/questions/33845775/send-json-data-to-jupyter-notebook-frontend-via-comm/33846113#33846113

Basic idea: 
* keep index of all documents as @havocp suggested
* keep everything currently as it is, except
* `push_notebook` will:
  - construct patch messages (just for the data source)
  - tunnel them over comms to `document.apply_son_patch`

**Comment by fpliger** [comment]
this has been closed by https://github.com/bokeh/bokeh/pull/3370
