### ISSUE TITLE
Add "-m" option for "bokeh serve" command line for multi-user  

### ISSUE THREAD

**Issue by charleywan2004** [bokeh/bokeh#3159]
Thank you for adding address option to bokeh serve command line!

Can you add "-m" option for "bokeh serve" command line for multi-user, which is available for previous "bokeh-server"?

I compared version 10 and version 11. In v11, there is no "session.py" under "bokeh" directory, how to enable multi-sessions then?

Can you provide a small example of using it with multi-user authentication?

Thank you very much!

**Comment by fpliger** [comment]
@charleywan2004 new bokeh server have been heavily simplified and redesigned focusing on making it faster, simpler, easier to use and deploy (among other things). Basically it focus now on what it should really be doing and stripping out what it shouldn't be doing. That's why the new server that is coming out with the new `0.11.0` release really has no notion of authentication and authorization (because it is a topic that has no "right answer" and depends one way many different business logics. There are too many options that can be used and too many different needs to satisfy. There is no way the bokeh server "can do it right" for everyone).  The same applies to basing the server on a specific web framework like flask. In fact both these have been stripped out.

For such features, that are a higher level features on top of bokeh server service, I think the best approach is to use it for what it made for: serve plots (or bokeh objects if you want). With this in mind you can build your own auth layer to manage authorization & authentication and create bokeh server sessions to manage these with your own business logic needs.

I'd suggest to take a look at:
https://github.com/bokeh/bokeh/wiki/BEP-5:-New-Document-API-and-document-driven-server

and 

https://github.com/bokeh/bokeh/wiki/Porting-guide:-new-Bokeh-server

to better get the new bokeh server intentions.

> I compared version 10 and version 11. In v11, there is no "session.py" under "bokeh" directory, how to enable multi-sessions then?

Yes, `Session` as it used to be is gone but now we have different session objects (https://github.com/bokeh/bokeh/blob/master/bokeh/client/session.py). You can find the client session being used in a few examples in the [plotting/server section](https://github.com/bokeh/bokeh/tree/master/examples/plotting/server) and you can also find how to write a new bokeh app that can be server directly from `bokeh server` in the examples [app section](https://github.com/bokeh/bokeh/tree/master/examples/app)

**Comment by bryevdv** [comment]
@fpliger lays out things very well. One additional observation is that it was realized that since bokeh documents allow for arbitrary python callback code to be executed, it is *absolutely essential* to have process isolation per user. This is one of the main driving concerns for removing multi-tenancy. 

It is possible (at least, I can potentially imagine) a "multi-user publishing" mode when several users could publish to a single server but that would have to be for standalone plots with callbacks completely disabled. Right now our main, immediate focus is getting the scalable server-per-user use-case completely covered.

**Comment by charleywan2004** [comment]
Thank you so much!

Here is how I added an authentication web server by using "bottle" server

'''
from gevent import monkey; monkey.patch_all()
from bottle import route, request, template, static_file, run, redirect
import random
import os
from subprocess import Popen
import time

@route('/login') 
def login():
    return '''
        <form action="/login" method="post">
            Username: <input name="username" type="text" />
            Password: <input name="password" type="password" />
            <input value="Login" type="submit" />
        </form>
    '''
@route('/login', method='POST')
def do_login():
    usr = request.forms.get('username')
    pwd = request.forms.get('password')

    if usr=="username" and pwd=="password":
        session_id=str(random.getrandbits(128))
        Popen('python BokehPushSession.py '+ session_id + ' ' + 'None' + ' ' + 'http://BokehServerAddress:port/' )
        link = "http://BokehServerAddress:port/?bokeh-session-id="+session_id
        time.sleep(5) 
        redirect(link)
    else:
        redirect('login')

root='C:\\'
@route('/static/<filename>')
def server_static(filename):
    return static_file(filename, root=root)
    
run(server='gevent',host=WebServerAddress,port=port, debug=True)

**Comment by bryevdv** [comment]
@charleywan2004 nice thanks for the update! I think it should be possible to do this without the `Popen` but we might still have some things to fix up yet before the release.

**Comment by bryevdv** [comment]
There will be a nice django example in `bokeh-examples` repo (currently under development) that demonstrates auth (with djang) and configuring a served session per-user. Please re-open if there are other thing to discuss

**Comment by sigurdurb** [comment]
@bryevdv You mentioned django examples under ```bokeh-examples```, are there any up-to-date examples on the way? 
I currently have a bokeh server running a graph with streaming data and I still have to implement on how to talk to the django models from server_lifecycle and I'm not sure if that will be any trouble but I also don't know how to get the graphs into the django templates in a somewhat responsive manner, any suggestions or examples I should take a look at? 

Thanks for all your work on Bokeh.

**Comment by amir-rafieian** [comment]
Hi Bryan, Hope you can help us with the example for user authentication and serving multi-user, thanks in advance.

**Comment by duynguyen2411** [comment]
Hello, I'm using Bokeh 1.0.4, I want to set multi-user mode. Can you help me, Bryan?

**Comment by bryevdv** [comment]
@duynguyen2411 This issue refers the the first generation Bokeh server, which has been gone for several years now. Nothing here is applicable to the current Bokeh server, which is entirely agnostic about users. By which I mean: it can certainly serve to many users at a time no problem, but it does not enforce any sort of authentication notions on its own. There are simply too many options for auth, so choosing what is best for your use case is left up to users. All that said, GH is not the correct place for support. Please feel free to post a topic on the Bokeh discourse site:

https://discourse.bokeh.org/c/community-support

But for best results, please provide much more detail about what you are actually trying to accomplish.
