### ISSUE TITLE
Bokeh Line Plot

### ISSUE THREAD

**Issue by gmur24** [bokeh/bokeh#3203]
Hi Folks - Can I ask your help. I'm used to matplotlib where I can change my xticks to just simple plt.xticks(old ticks, new ticks). How do I do it in Bokeh? I currently have a numerical xticks (months in num). I want to map it to a categorical ones - Names of Month. Any help? Thanks!

**Comment by bryevdv** [comment]
@gmur24 First, for general support questions, it is probably better to use the Bokeh Users Mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

Or possibly StackOverflow:

http://stackoverflow.com/questions/tagged/bokeh

The GH tracker his primarily intended to capture and discuss issues and questions around Bokeh software development. Either of those places will have have wider audiences, with more people that can help than the GH tracker. 

Categorical Axes are illustrated in the User's Guide: 

http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#categorical-axes

As you can see, you will need to pass a list of strings that you want to show up as the category labels, and you will pass these names as your x values as well (i.e., you will need to map the month number to its corresponding month name, for every x value.) 

We have future plans to be able to specify client-side mappings in several places around Bokeh, so that you could just send the month numbers, and a mapper that mapped the numbers to the name for the tick labels. But that is future work.
