### ISSUE TITLE
List methods at top of documentation for Figure class

### ISSUE THREAD

**Issue by hsparra** [bokeh/bokeh#3245]
At the top of the Figure class documentation it would be helpful to have a list of the methods supported by Figure. Currently a user has to scroll down the list to see all the methods. A simple find on this string "method" does not work. Ideally the list of methods would hyperlink to the corresponding entry farther down the page.

**Comment by bryevdv** [comment]
This was fixed in https://github.com/bokeh/bokeh/pull/6506/commits/33fe31d024f688839d43234e05a38bd148875706 and this issue will be closed as soon as that PR was merged. 

Outcome:

<img width="829" alt="screen shot 2017-06-20 at 14 42 26" src="https://user-images.githubusercontent.com/1078448/27352608-ea30afd0-55c6-11e7-9576-b440c1d9bd3d.png">

Additionally, un-useful type descriptor typed for glyph method args were switched to link useful property types.
