### ISSUE TITLE
Button or Toggle.disabled=True does not gray out the Button or Toggle 

### ISSUE THREAD

**Issue by charleywan2004** [bokeh/bokeh#3252]
I understand there is issue (i.e. Slider ignores changes to the model #3169) in "all components should respond appropriately when if their properties change". Not only slider does not respond to "value" property change, but also does button or toggle not respond to "disabled" property change (i.e. when I set or reset disabled property, the button or toggle does not change its appearance.)

Looking forward to the version 11 release.

**Comment by bryevdv** [comment]
I believe this issue was resolved in #3169, so I am closing this discussion to clear up our tracker. If there is still an issue in Bokeh `0.11.1` or newer, please make a new issue and be sure to include a complete, minimal, runnable example of code to reproduce the problem, so that we can use it to start investigation.
