### ISSUE TITLE
Tools are not intuitive

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3267]
I was reminded of this thanks to @mattpap's UndoRedo PR #3524.

See the screenshot below:
<img width="641" alt="screen shot 2015-12-07 at 11 32 02 am" src="https://cloud.githubusercontent.com/assets/1796208/11637507/b28debc4-9cd6-11e5-9052-7066ff7d8b39.png">

All the items highlighted in red affect range. The ones on the left change it, the three on the right reset it. People already get confused that selections don't get reset when you hit the reset button, 

I understand why the tools are in those groups - it makes a lot of sense behind the scenes, but i'm not sure it's a meaningful distinction for users.

My suggestion would be to regroup the tools as follows:
- Pan, BoxZoom, WheelZoom, Reset, Undo, Redo - "moving" group
- Tap, BoxSelect, Lasso, etc - "selecting" group
- Hover, Crosshair - "inspecting" group (I'm not sure inspecting is a meaningful name for users)
- Save, Help - "other"?

**Comment by bryevdv** [comment]
I think all the "button actions" should go in one place, especially if reset/undo/redo start to reset selections as well. I suddenly realize I have no idea what "redo" means in the context of plots, either. I would find those lumped in wth pan/zoom, etc to be very confusing. 

It's worth experimenting with moving/selecting/action breakdown otherwise though, I think.

**Comment by birdsarah** [comment]
Can @SaraSchnadt do some user testing? This seems like a pure UX issue.

**Comment by timsnyder** [comment]
>  I suddenly realize I have no idea what "redo" means in the context of plots, either

Maybe undo/redo are mildly confusing names and they should be called Back/Forward or Prev/Next?


Looking at [the docs for action tools](http://bokeh.pydata.org/en/0.12.2/docs/user_guide/tools.html#actions) I'm unclear whether Undo/Redo will reset the selection or not because Undo says:
> The undo tool allows to restore previous state of the plot.

If Undo/Redo only reset the range, we should at a minimum clarify the docs.

**Comment by bryevdv** [comment]
This seems unlikely to happen
