### ISSUE TITLE
Bokeh server won't serve your session if you don't have a token

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3287]
A plot lands on your webpage when the script tag (probably generated by autoload_server) requests a particular session from your bokeh server.

We could add in a token mechanism so that that script also comes with a token and bokeh server will refuse to serve a session without the required token.

(have I got that right @bryevdv)

wider discussion at #3279

**Comment by havocp** [comment]
I was thinking for the browser client, the session id itself should be the token (i.e. the session id is considered a secret).

The token I was trying to describe on the call is specifically a secret known to say your Django server, which the Django server uses to create a session. The secret is required in order to make new sessions. Bokeh server would reject attempts to create a session without proving knowledge of the secret, and would reject attempts to use a nonexistent session id.

So the secret would probably be provided to bokeh server like `bokeh server --session-creation-secret=LONG_SECRET_STRING` and then when the Django server goes to create a session, it would provide a hash of the secret with a timestamp, or something along those lines. bokeh server recomputes the hash with the same timestamp and requires the timestamp to be within a few seconds of the current time (to prevent replays). This is essentially the same auth mechanism used by Amazon's web services API for example (http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html ). They also include the content of the request itself in the hash, which is probably wise.

If we wanted to we could make it `bokeh serve --admin-secret` or something (instead of `--session-creation-secret`) with the idea that it could also be used for other "privileged" operations in the future, the secret is like a `sudo` for bokeh server.

**Comment by bryevdv** [comment]
The missing half (a mode so that doc_handler will refuse to auto gen session ids) was implemented at some point:

https://github.com/bokeh/bokeh/blob/master/bokeh/server/views/session_handler.py#L34-L36
