### ISSUE TITLE
Data not always bytes

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#3299]
I occasionally get the following error when running bokeh serve on the following script

### Error

```python
ERROR:tornado.application:Exception in callback <bound method BokehTornado.keep_alive of <bokeh.server.tornado.BokehTornado object at 0x7f9d767ef9e8>>
Traceback (most recent call last):
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/tornado/ioloop.py", line 1039, in _run
    return self.callback()
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/bokeh/server/tornado.py", line 182, in keep_alive
    c.send_ping()
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/bokeh/server/connection.py", line 44, in send_ping
    self._socket.ping(str(self._ping_count))
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/tornado/websocket.py", line 266, in ping
    self.ws_connection.write_ping(data)
  File "/home/mrocklin/Software/anaconda/lib/python3.4/site-packages/tornado/websocket.py", line 697, in write_ping
    assert isinstance(data, bytes)
```

### Script

```python
import numpy as np
from datetime import timedelta, datetime

def update_data(*args, **kwargs):
    td = timedelta(milliseconds=100)
    now = datetime.now()

    source.data = {'time': [now - td * i for i in range(100)],
                   'cpu': np.random.random(100).cumsum(),
                   'memory': np.random.random(100).cumsum()}

from toolz import first
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, Range1d

source = ColumnDataSource({})
update_data()

p = figure(x_axis_type='datetime', y_range=Range1d(0, 100))
p.line(x='time', y='cpu', source=source)
p.line(x='time', y='memory', source=source)

from bokeh.io import curdoc
curdoc().add(p)
curdoc().add_periodic_callback(update_data, 100)
```

    $ bokeh serve script.py

**Comment by bryevdv** [comment]
What version of python?

**Comment by bryevdv** [comment]
ping @havocp

**Comment by mrocklin** [comment]
I should say that this didn't cause a serious issue, just in the logs.

Python 3.4, Tornado 4.3 (also tested on 4.2), Ubuntu 14.04

**Comment by havocp** [comment]
need an encode there in Python 3 it looks like

**Comment by RutgerK** [comment]
Not sure if its entirely related, but i had the exact same error when running the "scikit-learn example" from the webinar. Here is the gist from Bryan i used, on 0.11.0dev3 (Win 64x):
https://gist.githubusercontent.com/bryevdv/f102f2e07e369975f0d7/raw/6cb36d8adef7ff926be4929204016937c26125c7/sklearn_bokeh.py

I launched the example with the ip address of my machine to listen on, when the error occurs while viewing on the same machine, it still keeps working. Similar as to what Matthew describes.

However, when viewing the visualization from a different machine on the same network, it stops working. You can still interact with the front-end (work the sliders etc) but the plot doesn't update anymore. Since this last behavior is slightly different, I'd figured i mention it here in case anyone else experiences the same.
