### ISSUE TITLE
bokeh command leaves IOLoop.current set

### ISSUE THREAD

**Issue by havocp** [bokeh/bokeh#3309]
I think the bokeh command ends up using IOLoop.current() (the default in tornado.py) which means inside a ScriptHandler people can add stuff to IOLoop.current(). This is dangerous because said stuff they add will outlast the session. They can even add stuff "accidentally" by simply invoking a coroutine or creating a future I believe.

A possible fix is that in ScriptHandler we should unset IOLoop.current() while invoking the application script.

**Comment by havocp** [comment]
It's hard to deal with this because if you unset IOLoop.current or IOLoop.instance tornado will keep making up new IOLoop to put there. One approach here is to subclass IOLoop and override all the add-a-callback methods with methods that explain what's going wrong, then install() that as the instance and make_current() as current, so any attempt to use the global IOLoops will fail. Inside bokeh itself, we should always pass around the ioloop explicitly.

**Comment by mrocklin** [comment]
I agree that it's probably a good idea for Bokeh to have its own `IOLoop`.  

I obviously find access to Bokeh's `IOLoop` to be quite handy but yes, it'd probably be good if I wasn't dumping coroutines directly into it, particularly given the ephemeral nature of sessions.  

A `Document.add_callback` method that supported coroutines and associated those coroutines to a document might be nice.  In this case bokeh could support concurrent user code and also clean up coroutines associated to documents once a session terminated.

**Comment by havocp** [comment]
Another trick here is that coroutines (the wrapper created by `@gen.coroutine`) depend on an accurate IOLoop.current, so we do have to set it correctly when we're actually running coroutines.

I've built some tests for timeout/periodic coroutines. They fail and I'm in deep tornado internals trying to figure out how to make them go. Once they work, an add_callback is trivial (and is the same as a 0-timeout timeout, I guess).

**Comment by bryevdv** [comment]
@havocp @mrocklin is the `add_callback` described above materially different from `add_next_tick_callback`? I'm inclined to close in any case,  there have not been any bug reports from people adding their own things to the `IOLoop` so I'd just chalk that up to something people probably wouldn't know to attempt in the first place unless they had some idea what they were doing.

**Comment by mrocklin** [comment]
@bryevdv I'm not sure I know enough about `add_next_tick_callback` to answer.  After rereading the notes above here are the points that I extract:

1.  Bokeh assumes that it is running on the global Tornado IOLoop.  Some applications (like dask) start separate IOLoops apart from the global one. This is useful, for example, when running Bokeh in a separate thread so that we don't block the user interaction thread.  If you want Bokeh to run while also allowing users to type then this *might* come up, although I suspect that you can avoid it in the Jupyter notebook (if you don't mind bokeh blocking when a cell runs).
2.  There should be a mechanism to start coroutines for a document and have them cleaned up when the document finishes.  I would expect this to be of use for non-trivial server applications.  I would expect this to increase in importance as developers become more comfortable with async/await.

Neither of these are blocking issues for Dask, so I agree that it's probably a good idea to not think about these issues until some other user shows up asking for them.  That being said I suspect that they are still live and valid issues.  I would expect either to come up in a sufficiently complex server application.

**Comment by havocp** [comment]
My impression from my original comments above is that anyone using tornado or async APIs directly would probably run into this. My guess is that most don't do so or if they do they don't know to report the resulting issues. (issues here could look like a server that slowly degrades under load for example)

**Comment by bryevdv** [comment]
Absent a concrete plan after 30 months, Im going to close this.
