### ISSUE TITLE
Support asynchronous coroutines in `add_timeout_callback`

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#3310]
In order to support event driven updates without blocking a user might employ a tornado coroutine

```python
@gen.coroutine
def watch_for_updates():
    while True:
        msg = yield event_stream.next()
        bokeh_document.data['x'] = msg['x']
```

This is nice because the user is not restricted to single call updates or to fixed-interval PeriodicCallbacks, but can update state as external events dictate.

### Example

A tiny example of doing this (that just waits a second between updates) follows:

```python
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource, Range1d
from bokeh.io import curdoc
from datetime import datetime
from tornado import gen
from random import randint

state = {'time': list(),
         'cpu': list(),
         'memory': list()}

def update():
    print("Hello!")
    source.data['time'].append(datetime.now())
    source.data['cpu'].append(randint(0, 100))
    source.data['memory'].append(randint(0, 100))
    source.trigger('data', source.data, source.data)

@gen.coroutine
def track_worker():
    while True:
        yield gen.sleep(1)
        print("World!")
        # update()  # this would be nice, but is unsafe
        doc.add_timeout_callback(update, 0)  # we do this instead

source = ColumnDataSource(state)
p = figure(x_axis_type='datetime', y_range=Range1d(0, 100))
p.line(x='time', y='cpu', source=source)
p.line(x='time', y='memory', source=source)
doc = curdoc()
doc.add_root(p)

track_worker()
```

### Possible improvements

The `track_worker` coroutine is careful not to affect bokeh state, which depends on various locks.  Instead it safely calls `add_timeout_callback(update, 0)`, handing the bokeh-state changing code into bokeh in a way that is hopefully safe.

It would be nice if we instead gave this coroutine to bokeh directly so that it could manage locks and such before waking us up.

```python
@gen.coroutine
def track_worker():
    while True:
        yield gen.sleep(1)
        # doc.add_timeout_callback(update, 0)
        update()

doc.add_callback(track_worker)
```

**Comment by havocp** [comment]
#3321 fixes async callbacks but there's a caveat which will still be a problem here: the session lock is held for the entire duration of the callback. This is because Tornado gives us a Future for the whole callback, the gen.coroutine wrapper hides the individual steps in the generator, so there's no way to drop the lock between steps. We have to hold it until the future completes. If we could drop it for individual steps it would probably cause semantic trouble anyway because random requests could be processed between steps.

The lock will prevent any incoming requests, so we won't process any client events during a callback even though the callback is async.

Anyway I think writing this program will require some amount of manual hoop-jumping (some sort of mechanism to get the IO out of a session context). Will have to keep thinking on it.

**Comment by havocp** [comment]
This "lifecycle hooks" idea would provide a place to add callbacks that don't always have the document lock.
https://github.com/bokeh/bokeh/wiki/Server-lifecycle-hooks
In the particular case at hand, it's also a huge optimization to listen for new data process-wide instead of per-session.
