### ISSUE TITLE
Overlapping bins in Bokeh charts Histogram example

### ISSUE THREAD

**Issue by ahmadia** [bokeh/bokeh#3315]
```
import pandas as pd
import numpy as np
from bokeh.io import output_file, show

# build some distributions
mu, sigma = 0, 0.5
normal = pd.DataFrame({'value': np.random.normal(mu, sigma, 1000), 'type': 'normal'})
lognormal = pd.DataFrame({'value': np.random.lognormal(mu, sigma, 1000), 'type': 'lognormal'})

# create a pandas data frame
df = pd.concat([normal, lognormal])
df[995:1005]

from bokeh.charts import Histogram
hist = Histogram(df, values='value', color='type', bins=50, legend=True)
show(hist)
```

![image](https://cloud.githubusercontent.com/assets/512293/11726004/9ab53784-9f4a-11e5-8183-cd79e9d87727.png)

**Comment by ahmadia** [comment]
There's also bad spacing in a couple of other places.

**Comment by jsignell** [comment]
Histogram seems to be trying to use the Bar machinery and forcing the center to a string so that it can be used as a categorical. 

The issue is probably at:
bokeh/charts/stats.py line 377  centers = centers.astype(str)

The chunk of json that is troubling, looks like this:            
         "x": [
                "2.0"

The whole print out is here:
https://gist.github.com/jsignell/7122693eda4ead043af0c569078cd574
