### ISSUE TITLE
Quads with JS Callbacks

### ISSUE THREAD

**Issue by Discmt** [bokeh/bokeh#3319]
Hi Everyone,

I'm pretty new to Bokeh so I'm not entirely sure if the solution I'm looking resides in some functionality to BokehJS. Regardless I'd like your help in telling me what I can do.

I am trying to implement a type of treemap within BokehJS on my notebook, and the problem I run into is that it doesn't seem like quads take callbacks. Is there way I can get them to take callbacks.

**Comment by bryevdv** [comment]
Hi @Discmt thanks for your interest in Bokeh. As Bokeh gains more users, our issue tracker is growing  unmanageable.  We are having to be a bit more disciplined about directing people to the mailing list for general support questions, so that the issue tracker can be reserved for development-related discussions. There are more people on the mailing list who can potentially help, so it is a better resource for support questions in any case. That is why I am going to close this issue, I hope you will repost your question on the mailing list, which is here:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

I will that I don't understand what you mean when you say "it doesn't seem like quads take callbacks" (because I don't know what it could mean for a quad to take a callback in general) so please explain a little bit more on the mailing list exactly what kind of interaction you are trying to achieve.

**Comment by Discmt** [comment]
That's fine thanks. Didn't see mailing list so I assumed we had post here for help.

**Comment by bryevdv** [comment]
No worries! :)
