### ISSUE TITLE
pypy compatibility broken

### ISSUE THREAD

**Issue by sonium0** [bokeh/bokeh#3328]
As I understand there is an effort to be compatible with pypy which means to make the pandas dependency optional.
This is currently broken by bokeh/crossfilter/models.py where a pandas function is used. I think there would be a numpy analog.

**Comment by bryevdv** [comment]
Hi @sonium0 To the extend that Bokeh works with PyPy, we are definitely pleased. But this is not currently an explicit priority, mostly because none of the Bokeh core devs are PyPy users, to my knowledge, and because we only have limited time and resources and many other currently higher priority tasks. If an active PyPy user wanted to come on a new contributor to the project and help maintain PyPy support, that would certainly be welcome. But to be clear, Bokeh is a large project, and some parts of it will always depend on Pandas. In particular the `bokeh.charts` high level API makes extensive use of Pandas for grouping and aggregation and statistical transformations. Additionally, the crossfilter is being re-written to make use of the auto faceting capabilities that `bokeh.charts` affords, so it to will continue to depend on Pandas. However, there is currently work underway to pull the crossfilter out of the core library and turn it into a example Bokeh application. In this way it will be much more easily extended and modified by users to suit their own needs (including not using `bokeh.charts` or Pandas if someone want to do that). 

However, we are making an effort to remove Pandas as a dependency of the whole package, and to make Bokeh complain clearly and loudly when you try to try to use a part of Bokeh that does require Pandas. Please see https://github.com/bokeh/bokeh/pull/3323 for more details.

**Comment by bryevdv** [comment]
The work to make pandas optional, and also to remove crossfilter from the core library has been completed, so I will close this now. Please re-open if there is more to discuss.
