### ISSUE TITLE
Slider size from python code to css

### ISSUE THREAD

**Issue by Pegase92** [bokeh/bokeh#3346]
Good afternoon,

Will it be possible to have a new attribute in the Slider object class that may define the size (i.e. the width) , instead of being defined in the bokeh.min.css ? This will be heplfull.

Many thanks

Benoit

**Comment by brendancol** [comment]
I was thinking it would be nice to have a `css_properties` dictionary on some widget base class which would allow users to supply arbitrary css properties to be place at the element level.  User Defined Widgets / Layouts are coming soon, but the code for such an extension would look like this:

```
from bokeh.properties import Dict, String
from bokeh.models.widgets import BaseBox

class StyleableBox(BaseBox):
    __implementation__ = '''
        _ = require "underscore"
        build_views = require "common/build_views"
        ContinuumView = require "common/continuum_view"
        BaseBox = require "widget/basebox"

        class StyleableBoxView extends ContinuumView
          tag: "div"
          attributes:
            class: "bk-vbox"

          initialize: (options) ->
            super(options)
            @views = {}
            @render()
            @listenTo(@model, 'change', @render)

          render: () ->
            children = @model.children()
            build_views(@views, children)
            for own key, val of @views
              val.$el.detach()
            @$el.empty()

            css_props = @mget("css_properties")
            if css_props? then @$el.css(css_props)

            for child in children
              @$el.append(@views[child.id].$el)
            return @

        class StyleableBox extends BaseBox.Model
          type: "StyleableBox"
          default_view: StyleableBoxView

          defaults: ->
            return _.extend {}, super(), {
              children: []
              css_properties: {}
            }

          children: () ->
            return @get('children')

        module.exports =
          Model: StyleableBox
          View: StyleableBoxView
        '''
    css_properties = Dict(String, String, default=None)
```

Any love for adding a couple of element level css properties as a `Dict(String, String)`?

**Comment by birdsarah** [comment]
I'm working on layout which changes this, but i recently added this feature on a branch I was working on.

Here's the commit: https://github.com/bokeh/bokeh/commit/1b050a47a09b5c70137b17ace202027bbf9ad340

**Comment by birdsarah** [comment]
Confirm as part of #4392.

**Comment by birdsarah** [comment]
This is still buggy:

`r_slider = Slider(start=0, end=255, value=init_color_value, step=1, width=600, title="R")`

In notebook:
* If `show(Row(r_slider))` - works and responds to specified width of slider
* If `show(WidgetBox(r_slider))` - does not respect width of slider - need to set width on WidgetBox
* If `show(r_slider)` does not respect size

In file:
* If `show(Row(r_slider))` - works and responds to specified width of slider
* If `show(WidgetBox(r_slider))` - nothing shows!!! (open another issue?)
* If `show(r_slider)` slider doesn't really show.

**Comment by birdsarah** [comment]
So, the latest state of things - just before 0.12.0dev12:

* if you specify a width on a slider, and wrap it in a widgetbox `widgetbox(children=[Slider(width=150)])` it doesn't work - the widget box grows to be as large as the page and the slider takes the size of the widget box
*  if you specify a width on a slider, and wrap it in a row `row(children=[Slider(width=150)])` it does work - this is odd because row will wrap the slider in its own widgetbox
* you can also do `widgetbox(children=[Slider()], width=150)` to get a widgetbox of the correct size with a slider that size inside it.

Whilst this is is a little annoying, it's also kind of convenient because you can do this `widgetbox(children=[Slider(), Slider(), Slider(), Slider()], width=150)` and get a widgetbox with four sliders of width 150 inside it.

I'm ok with this behavior for now until more concrete use cases start to shake out because
1) this starts to get fairly complicated when you have more than one kind of widget in a widget box and a complex layout
2) there is now a way to specify the slider size you want in python

**Comment by birdsarah** [comment]
This finally got better, please see 0.12.0rc3 and please do re-open this issue if it's not working for you.
