### ISSUE TITLE
Add a server option to run some code on setup

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3352]
See this line in my demo app:
* https://github.com/bokeh/bokeh-demos/blob/7764c281797760ef37ac87054320bc8f5e0fc041/happiness/viz/individual.py#L49

This runs django.setup() so that bokeh can use the django orm.

It only needs to be run once.  Instead of that except block, it would be nice if I could do something like:

`bokeh serve my_app.py --startup-script=startup.py`

I'm imagining it would then run once on the `invoke` of `Serve` Subcommand

ping @havocp @bryevdv - what do you think?

**Comment by havocp** [comment]
https://github.com/bokeh/bokeh/wiki/Server-lifecycle-hooks would give you an `on_application_load`, but if you had two apps in one server it wouldn't give you a way to run a script before both apps. `on_application_load` could probably check whether django was already setup or something though... ?

Another option would be to write a little custom launcher to use instead of `bokeh serve` - if we added a little more API, this could potentially be something like:
```python
  import django
  from bokeh.application import serve
  django.setup()
  serve(["myapp.py"])
```

**Comment by bryevdv** [comment]
Oh interesting, I had imagined communicating model data to sessions, not that Bokeh app code would touch, e.g. Django models directly. But I see the sense in that. 

I'm not a fan of `serve(["myapp.py"])` mostly because I don't see how it would work if you wanted to scale. I'd rather enforce something like server startup hooks only allowed when there is one app or similar.

**Comment by havocp** [comment]
`serve(['myapp.py'])` I meant to be identical to `bokeh serve` just invoked from Python rather than bash.
But it's true you would give up the ability to run in a generic "bokeh app container."
@almarklein had asked for API like that too.

I do think a way to put these hooks in your app would be nicer than having to abandon the bokeh command.

**Comment by bryevdv** [comment]
is "startup hooks" => "only one app" unreasonable?

**Comment by havocp** [comment]
I was thinking about solutions there. We could say for example that we run all on_application_load hooks for all apps, before we run session hooks or modify_document for any apps. So you'd put your global setup in any of the app load hooks and it would work ... seems ok? Or if you made your setup idempotent you could put it in all the apps that need it so they can also be run by themselves. 

We could do a separate --setup-script but I feel like it would be difficult to define its "meaning" (when does it run, before/after what, when does it reload, what APIs can it use, etc). Also if we did a thing where people could publish apps, we really need everything to be part of the app, vs off to the side somewhere.

**Comment by bryevdv** [comment]
Yes I am not a fan of a `--startup` either, I think this should all be handled through the event system, which I think is what you are also suggesting.

**Comment by bryevdv** [comment]
lifecycle hooks were implemented

**Comment by birdsarah** [comment]
sweet - thanks!
