### ISSUE TITLE
Text selection from figure axes or hover

### ISSUE THREAD

**Issue by mlovci** [bokeh/bokeh#3365]
I'd like users to be able to copy text from the axis labels, hover tooltips and legends. Now, it doesn't look like I'm able to select any text on figures, is there a way to enable this feature that is available but hidden?

Thanks!

**Comment by bryevdv** [comment]
Bokeh renders to HTML5 Canvas or WebGL Canvas, there are no DOM elements, I don't see how this could feasible.

**Comment by bryevdv** [comment]
Closing to clear up the tracker, I don't see any immediate actions that can result from this discussion unfortunately. As a suggestion, if copying text is an important priority, you can add a JS callback to tap tool that updates some other div in your document, with the info for the tapped location, and then presumably that could be copied because it is just text.
