### ISSUE TITLE
Improve DataRange updating policies re: server usage

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#3408]
Reference: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/common/client.coffee#L232

In the above ML discussion it was discovered that the auto-ranging that `DataRange1d` does was causing a huge spike in traffic back to the server from the browser (every render, basically) when there was no need for it. In general, BokehJS should be examined for such inadvertent and "magic" updates triggering pushes to the server. But `DataRange1d` seems to be a big culprit, and just switching to  explicit ranges in the example offered dramatic performance improvements. So, for a "quick fix" I'd like to modify `DataRange1d` to play more nicely. Here is my initial proposal:

* Add properties `start_policy` and `end_policy` that accept: `never`, `once`, `always`

The default would be `once` which would mean that auto-ranging would only happen once, on first load, and not again subsequently. Should there also be a way to "reset" the state so that ranging happens once (again)?

I'd also like to take the opportunity to get rid of the compute properties on `DataRange1d` so that it can be reflected simply to the server like any other model:

* `start` and `end` are simple normal properties inherited from `Range1d`

The `DataRange1d` would update `start` and `end` as described by the policy, so no computed props would be needed. 

Thoughts, @bokeh/core and esp. @mattpap @havocp @birdsarah ?

It think I can have this work done in under a day (including tests) once there is agreement on a plan, but time is short for `0.11` so we would need to come to agreement very soon.

**Comment by havocp** [comment]
In the problem case, `start` and `end` were actually changing right? Meaning we should not be sending change notifications if we keep computing the same range... if we are, then that's the first bug to fix perhaps?

On the other hand, if the range keeps changing the actual start and end values, it seems like the animation might _need_ the different range? Or if it's changing for no good reason by a very small amount, could there be a solution where we try to "round off" the autocomputed range in order to prevent "noise" in the auto-range?

Another question - I'm wondering why it caused stutter to send two floats to the server... what am I missing here, does changing the range somehow cause more traffic than that, or maybe the issue is that changing the range causes a bunch of client-side rendering work?

**Comment by bryevdv** [comment]
> In the problem case, `start` and `end` were actually changing right? Meaning we should not be sending change notifications if we keep computing the same range... if we are, then that's the first bug to fix perhaps? 

Yes thanks for pointing that out explicitly, we should avoid triggering actual updates then the values don't change, and I would make that part of this as well. 

I think the "rounding" idea is also interesting, I will have to think about it a bit. 

Also yes you're probably right that two floats (plus message overhead) is probably not problematic in and of itself. But I think that renders triggering range changes triggering updates (which then end up coming back and triggering more renders) results in a vicious cycle of much extra work.

**Comment by bryevdv** [comment]
Regarding rounding, we do already have Heckert in BokehJS, we only use it for picking nice numbers, give a range, but it can be used to suggest nicer encompassing bounds for a given range too.

**Comment by bryevdv** [comment]
BTW not really for the same PR, but I'd like to do this with an eye towards adding either features to `DataRange1d` or a new range subclass that is much better for "following" updating data sets (e.g. a fixed time window around the latest data in a streaming stock ticker)

**Comment by bryevdv** [comment]
@pzwang did you have thoughts you wanted to add? I'd like to get started on something very soon.

**Comment by bryevdv** [comment]
`DataRange1d` has another problem: it updates its own `renderers` every `update` (every render basically) which triggers a server update as well. Will be first fixing this in another PR, though,

**Comment by pzwang** [comment]
I do have some thoughts but don't have enough time right now to type them all out.  Will try to capture the main points...

The concept of start and end "policies" is the right one, but I think it would be too obscure to call them that, especially with the options named "never/once/always".  I think users would be scratching their heads and what this was supposed to represent.

The fundamental root of this problem is that the range is manifesting a behavior (auto-ranging) on the server-side, which embodies the Model in the MVC approach.  However, the actual numerical values are actually a View.  We find ourselves getting in trouble here, because syncing up the numerical values between client and server is actually syncing two Views, and not the underlying Model.  (Actual numerical values as limits are just a shorthand for specifying something like ExactLimitPolicy.)

I think it's good to do things like not fire events if values haven't changed, but this is somewhat of a hack.  However, it may be a sufficient hack to solve this problem, without having to build out a bunch more API...

I am in 100% agreement with you that the idea of a "following" or "tracking" mode falls within the sphere of concern of this issue, e.g. a range policy of Min+Window or Max-Window would also need to be implemented in the JS and the server side, and we need some way to avoid debugging and "debouncing" all sorts of auto-update issues.

**Comment by bryevdv** [comment]
> I think it's good to do things like not fire events if values haven't changed, but this is somewhat of a hack. 

I'm not sure I agree. Independent of anything else, and even if things are idempotent, sending change events when there are no changes seems like a bug to me. 

The other PR #3416 actually improves things greatly already as well, so I will take a stab at this approach, first:

* no change events when values are not new
* add an "auto" option to range padding that uses Heckbert to find a nice enclosing interval so that small data changes don't result in actual range changes.
