### ISSUE TITLE
setup.py by default should just build bokeh-js

### ISSUE THREAD

**Issue by yurivict** [bokeh/bokeh#3413]
I tried to make the FreeBSD port, and setup.py fails with questions about bokehjs. It should just build it by default it it is missing. Why ask these questions "1. Use existing?, 2. Build from scratch?" when there is no existing build?

**Comment by bryevdv** [comment]
Bokeh is a very large cross language language project with a non-trivial build. The question you are seeing is in regard to the client library, BokehJS, which is actually written in CoffeeScript and has to be first compiled to Javascript. Additionally many Javascript dependencies need to first be installed with `npm`. To build and install Bokeh from scratch, you have to build a matching BokehJS client library, there is no getting around this. We can't possibly check in a large JS library with every commit, the repo size would grow beyond all reasonable measure in no time. You can find instructions for installing the required JS dependencies and toolchain here:

http://bokeh.pydata.org/en/latest/docs/dev_guide/building.html#install-npm-and-node

And instructions for configuring `setup.py` purely from the command line here:

http://bokeh.pydata.org/en/latest/docs/dev_guide/building.html#python-setup

All of that said, I ***strongly encourage*** you ***not*** to attempt to distribute builds from pure repository source. If you must make distribute "source" builds for a port, I encourage you to only use `sdist` tarballs of official releases (available on PyPI). These "source distributions" ***do*** have a matching, correctly pre-built BokehJS library included, and do not require all the JS toolchain support to use and install. (i.e. you can run `python setup.py` and everything will just work) The reason I am suggesting this is because anything you attempt with pure repository source will almost certainly be more fragile than our build automation, and the possibility of users encountering problems will be high. We frankly cannot afford the support burden such a situation might cause.

**Comment by yurivict** [comment]
Do you make official releases for FreeBSD though?

**Comment by bryevdv** [comment]
No we make available "sdist" package tarballs, and conda packages, either of which you are welcome to re-package.

**Comment by bryevdv** [comment]
To elaborate: We don't have access to FreeBSD resources for continuous integration testing, AFAIK no one on the current team uses or has any FreeBSD experience. Additionally, no one has ever asked about Free BSD in almost three years. I would certainly be happy if there were official FreeBSD packages, but it's not something the current team is capable of prioritizing in any way. If you have the time and resources to make a commitment and would like to volunteer to be a build maintainer for FreeBSD, please do let us know,

**Comment by yurivict** [comment]
I will try to make the FreeBSD port. Would appreciate if you would answer some occasional questions in case if I get stuck.

**Comment by damianavila** [comment]
>I will try to make the FreeBSD port. Would appreciate if you would answer some occasional questions in case if I get stuck.

Nice, let us know any issues and we will try to help you.
