### ISSUE TITLE
Tools UX enhancement

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [bokeh/bokeh#3436]
I don't understand why crosshair and hover tool are second level options that requires one extra click to check them.
<img width="203" alt="toolsextramenu" src="https://cloud.githubusercontent.com/assets/8209940/12032246/f1f1cefc-adca-11e5-98de-65ec6a0c9386.png">

My suggestion is to add one icon for each of the tools (crosshair and hover) and make them available as the others.

As you can see in the screenshot you have extra bullets outside the box, which is not great if want to keep the two level tools option.

**Comment by bryevdv** [comment]
Hi @VelizarVESSELINOV the reason that they are second level is that there are potentially many of them --- e.g., either multiple hover tools, or new inspectors we have not added yet (axis tooltips, etc.) With all the other tools, the toolbar is already quite crowded. There really just isn't room (and we also don't have any visual assets for icons for those)

The one extra click has been fixed in master, AFAIK, and I don't see the list bullets either. Before I mark this as a bug can you provide more information about platform, browser, and versions? (Or confirm whether the issue exists on master or a recent dev build)?

**Comment by VelizarVESSELINOV** [comment]
As you can see in my example: I have 3 tools and 2 of them are available with extra click.

I'm using Mac 10.11.2:
 - Chrome Version 47.0.2526.106 (64-bit)
 - Safari Version 9.0.2 (11601.3.9)
 - Google Datalab with Jupyter Version: 0.5.20151127
 - Bokeh 0.10

**Comment by bryevdv** [comment]
@VelizarVESSELINOV I think I misunderstood your "extra click" comment, there used to be a bug where the checkboxes did not respond t the first click. You just mean that the accessed by first clicking on the dropdown? I can see that you have only three tools on this particular plot, but I think my general observations still hold.  

ping @SaraSchnadt do you have any UX thoughts here?

**Comment by VelizarVESSELINOV** [comment]
My UX expectation is that if I have enough space and I have a limited number of tools, they will be available together with the same level accessibility one click/one icon.

**Comment by VelizarVESSELINOV** [comment]
Another example bad behavior of extra click when the toolbar is above the menu box is partially displayed outside the visual boundaries:
<img width="169" alt="uxoutsidetheborder" src="https://cloud.githubusercontent.com/assets/8209940/12038465/2f1316c8-ae0d-11e5-9e3c-2bf3a6e14171.png">

**Comment by bryevdv** [comment]
ping @birdsarah might have thoughts as well

**Comment by mattpap** [comment]
This issue isn't relevant anymore, because tool buttons' dropdown menus were removed at some point.
