### ISSUE TITLE
reveal.js slideshow demo does not work with server

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#3463]
ping @damianavila Reveal seems to not like the way Bokeh server sessions are handled

Suggest just removing for `0.11`

```
examples/embed/slideshow.py:
 DOES NOT WORK AT ALL
```

**Comment by bryevdv** [comment]
Note: this demo has been removed from the repository for now.

**Comment by audiolion** [comment]
did this only fail with bokeh server? or with the flask_server as well?

**Comment by bryevdv** [comment]
> did this only fail with bokeh server? or with the flask_server as well? 

I don't have any way to answer this. The tracker really intended for bug reports, asking "will something work" is better left for the mailing list, where there is a much bigger pool of potential respondents:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by bryevdv** [comment]
Also, I am just going to close this, if anyone with reveal.js wants to contribute a reveal.js example, it would certainly be accepted.

**Comment by audiolion** [comment]
Sure I will move to the mailing list, but what I was asking was in the context of the issue that you originally reported. There was a [slideshow example back in 0.10.0](https://github.com/bokeh/bokeh/tree/0.10.0/examples/embed/slideshow), it stopped working in 0.11.0 with `bokeh serve` so it was removed for the "short-term" label added to fix it, but hasn't been re-added since.

The original example was using `flask` but in the issue you reported

>> Reveal seems to not like the way Bokeh server sessions are handled

which means that it might have still been working with `flask`, just not the new `bokeh serve` code. Then you removed the flask example, so I am asking you if it was still working with `flask` when you decided to remove it.

I wanted to create a `Bokeh` app that displayed ~200 plots with a lightbox/slideshow/carousel type format instead of having a super long html page, or some kind of plot pagination and found that old example and this issue, I don't care if I use `flask` instead of Bokeh's server, so I wanted to know if the example was only broke for bokeh server.

Clarifying the scope of the bug seems to be within the realm of the issue tracker.

**Comment by bryevdv** [comment]
> which means that it might have still been working with flask, just not the new bokeh serve code. Then you removed the flask example, so I am asking you if it was still working with flask when you decided to remove it.

To be honest I don't understand what you are asking. What do you mean by "flask" do you me some flask app of yours, or do you mean the old flask-based `bokeh-server` from `0.10` and before?
