### ISSUE TITLE
ViewModel Error on 0.11.0dev

### ISSUE THREAD

**Issue by jakirkham** [bokeh/bokeh#3531]
Seeing this error on 0.11.0dev. Could somebody help me to decipher this? I am not quite following it. I have two graphs that I am combining by using `VBox` before I plot them in a notebook and write them out to an HTML file.

ERROR:/opt/conda/lib/python2.7/site-packages/bokeh/core/validation/check.pyc:W-1004 (BOTH_CHILD_AND_ROOT): Models should not be a document root if they are in a layout box: Figure, ViewModel:Plot, ref _id: 007077a7-d6dc-4b48-8d6e-fe067385d190, Figure, ViewModel:Plot, ref _id: e657caa0-9d64-4b27-8424-58e12a5e50a4

**Comment by bryevdv** [comment]
This is something we will need to document or figure out how to handle better. `figure` is a convenience function to create a `Figure` object, and add it to the top level of your document. But then you also put it in a `VBox` and (presumably) add that as a root for the document as well. And that is the complaint: your `Figure` is in a top level layout, but also a top level model itself. Solution (currently) is simple: use `Figure` instead of `figure`.

**Comment by jakirkham** [comment]
Ah, ok, thanks for clarify @bryevdv. Yes, that does seem to fix it.
