### ISSUE TITLE
Can't get $color working in HoverTool for symbols

### ISSUE THREAD

**Issue by guillochon** [bokeh/bokeh#3628]
I'm trying to get the little color swatch to appear in my HoverTool on my plot, but the $color command does not seem to be working. The plot doesn't have any "fills" as it's just lines and symbols, but I'd like to show the color of the symbol currently being hovered over. Is there another specification besides `fill_color` I should use? I couldn't find other examples in the docs.

Here's my current HoverTool specification:

``` Python
    hover = HoverTool(
        tooltips=[
            ("MJD", "@x{1.11}"),
            ("Magnitude", "@y{1.111}"),
            ("Error", "@err{1.111}"),
            ("Instrument", "@instr"),
            ("Band", "@desc"),
            ("Color", "$color[swatch]:fill_color"),
            ("Source ID", "@src")
        ]
    )
```

and here's the plotting lines

``` Python
        p1 = Figure(title='Photometry for ' + eventname, x_axis_label='Time (' + catalog[entry]['photometry'][0]['timeunit'] + ')',
            y_axis_label='AB Magnitude', x_range = x_range, tools = tools,
            y_range = (0.5 + max([x + y for x, y in list(zip(photoAB, photoerrs))]), -0.5 + min([x - y for x, y in list(zip(photoAB, photoerrs))])))
        p1.add_tools(hover)
```

...

``` Python
        p1.circle('x', 'y', source = source, color=bandcolorf(band), legend=bandname, size=4)
        p1.multi_line([err_xs[x] for x in ind], [err_ys[x] for x in ind], color=bandcolorf(band))
```

**Comment by bryevdv** [comment]
The `fill_color` in the example is just a column data source column name. In this case `fill_color` which happens to be the default created column for fill colors. `line_color` and `text_color` are the default field names for the other properties you mentioned. 

(Gentle reminder that the mailing list is the best place for general support questions.)

**Comment by guillochon** [comment]
Apologies, thought this might have been a bug. Will use the mailing list for these sorts of issues.

**Comment by bryevdv** [comment]
No apologies necessary, just trying to keep the tracker under control :)

**Comment by guillochon** [comment]
Sorry to keep spamming here, but both `text_color` and `line_color` do not work. Also, the entire row does not appear in the HoverTool at all, even though it is defined:

![image](https://cloud.githubusercontent.com/assets/4998058/12246440/7aed0e40-b87c-11e5-927a-a2a7a42ffad3.png)

**Comment by bryevdv** [comment]
Not spamming, that does seem like a bug then. For reference here is the BokehJS code:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/tool/inspectors/hover_tool.coffee#L192

Can you see if there is any output in your browser's JS console?

**Comment by guillochon** [comment]
There is an error related to multiline, which spawns as soon as I move the cursor into the plotting area:

    bokeh-0.11.0.min.js:63 Bokeh: 'point' selection not available for MultiLinen.cerror
    @ bokeh-0.11.0.min.js:63n.sendLogItemsConsole
    @ bokeh-0.11.0.min.js:63i.sendBatch
    @ bokeh-0.11.0.min.js:63i.log
    @ bokeh-0.11.0.min.js:63t.log
    @ bokeh-0.11.0.min.js:63t.error
    @ bokeh-0.11.0.min.js:63e.hit_test
    @ bokeh-0.11.0.min.js:9e.hit_test
    @ bokeh-0.11.0.min.js:9e.inspect
    @ bokeh-0.11.0.min.js:5e._inspect
    @ bokeh-0.11.0.min.js:15e._move
    @ bokeh-0.11.0.min.js:15y
    @ bokeh-0.11.0.min.js:19m
    @ bokeh-0.11.0.min.js:19p
    @ bokeh-0.11.0.min.js:19h.trigger
    @ bokeh-0.11.0.min.js:19e._mouse_move
    @ bokeh-0.11.0.min.js:5(anonymous function)
    @ bokeh-0.11.0.min.js:5tt.event.dispatch
    @ bokeh-0.11.0.min.js:62g.handle
    @ bokeh-0.11.0.min.js:61

**Comment by bryevdv** [comment]
Right, point hit testing is not implemented yet for `multi_line`, you can suppress that warning by parring just the circle renderer to he hover tool `renderers` property (which is a list of renderers that the hover tool should do hit testing against, but default it tries to hit every renderer) I don't think that is the issue here but it might be worth a try in case there is some interaction that's not expected.

**Comment by guillochon** [comment]
I'd like to see this reopened, if possible, since I do think it's actually a bug.

**Comment by bryevdv** [comment]
@guillochon can you confirm if this is still a problem? If so I will put it for `0.12.6`

**Comment by kernc** [comment]
As you [clarified on StackOverflow](https://stackoverflow.com/a/41708787/1090455), `$color`'s `field_name` needs to be a column from data source. I suppose @guillochon's `bandcolorf()` returned a specific hex color, or an array of colors.

This limitation is unfortunate and a source of confusion for, as I see it, two reasons:
1. The `$color` specifier is prefixed with a dollar sign which in other cases indicates "special, _known_ fields" — and glyphs' color _is_ known.
2. When a separate data source isn't used, Glyph argument names stand for data columns. E.g.
    ```py
    fig.vbar(df.index, width, df.Open, df.Close, fill_color=cmap)
    fig.add_tools(HoverTool(tooltips=[('values', '@x, @width, @bottom, @top']))
    ```

    As `@top` and `@bottom` and `@width` and `@x` work as `@` field names, and as glyphs inherit `LineProps` and `FillProps`, it isn't clear why `@line_color` (`line_color`) shouldn't work as field name passed to `$color`.

**Comment by bryevdv** [comment]
This should fall out of #7674 I will link here to make sure to include this as a test of that work, but otherwise close this as duplicative.

**Comment by bryevdv** [comment]
In the above example, with `fill_color=cmap` things don't work because *there is not actually a column anywhere with the colors*.  There is a column with some other data, then the colormapper converts those to colors, on the fly, in the browser, at render time. With the `CustomJSHover` in #7674 it should be possible to dig around the glyph and get the information directly. I am dealing with a family medical situation otherwise I would try to work up an example. Hopefully I can get to something concrete in a few weeks. 

Regarding it being a "workaround" I would not consider it that. `$color` was added very early on, mostly as an afterthought, before the Bokeh model system, and in particular before `CustomJS` type things, were fully fleshed out. If I had things to start over, I would not add `$color` at all, rather I would add a general capability that lets users tailor things to their needs, rather than a limited, but yet extremely complicated partial feature like `$color`. i.e. I'd add a  flexible general purpose tool exactly like `CustomJSHover`, and promote that as the right, supported way to do things.
