### ISSUE TITLE
Provide lower-level plotting interface to customize created Chart objects

### ISSUE THREAD

**Issue by dloss** [bokeh/bokeh#3629]
I would like to create my plots using the high-level Charts interface and then customize some properties using the lower-level plotting interface. 
For example: `hm = Heatmap(data); hm.xaxis.visible = False`.

Related SO question: 
http://stackoverflow.com/questions/31619836/can-i-access-the-lower-level-bokeh-plotting-interface-from-a-higher-level-cha

**Comment by datnamer** [comment]
+1

Also stacking,   combining and transforming statistical type glyphs/ charts would be awesome.

**Comment by rothnic** [comment]
The current chart implementation is based off of Plot, which is kind of equivalent to Figure, except it tries to be mostly dimensionally independent.

The referenced link is trying to access Figure properties, which are a higher level interface. Since Chart is a Plot, you have access to all low level props/methods as Plot, so there isn't anything that will stop you from modifying the Chart further. You just have to look through and find what you want to change.

We could consider specific changes to the charts input options, but just wanted to be clear that you can toggle an axis visibility as is. Check the chart.renderers for where the axes are stored.

**Comment by dloss** [comment]
@rothnic I guess the relationship between Figure and Chart/Plot isn't really clear to me. I think it would be helpful if this was explained in the "Defining Key Concepts" chapter of the documentation -- e.g. by adding glossary items for "Figure" and "Plot".

**Comment by fpliger** [comment]
We should indeed make it more clear on the docs. 

We have had some discussions about making Chart inherit from Figure and this would bring many useful things and is definitely we will be considering soon.

**Comment by dloss** [comment]
That would be great. Being able to treat a Chart like a Figure was what I was hoping for.

**Comment by bryevdv** [comment]
The glyph methods from `Figure` were adde to charts some time ago.
