### ISSUE TITLE
Use a different error for "can't open socket" vs "404"

### ISSUE THREAD

**Issue by havocp** [bokeh/bokeh#3653]
The errors in session push and pull, e.g. 

https://github.com/bokeh/bokeh/blob/4f519bf4cac9b696550aae8ca1653e489f57f76b/bokeh/client/session.py#L270 

suggest starting "bokeh serve"

But this error will also happen if your app_path is wrong which means the server is started already.
It would be better if the connection recorded whether the failure was a network failure or an http error code, and the specific errno or http error. Then if we fail on 404 we can say "check your app path" rather than "start bokeh serve"

Remember to change both push and pull... for bonus points remove the cut and paste error handling between them so a single place has to be fixed.

**Comment by Soflon1** [comment]
Hi,

do I understand it correctly, that the goal is to create an easy way to access the reason for the connection error from the ClientConnection class  (https://github.com/bokeh/bokeh/blob/57da24a50e53c8b97e6efa155272e1a9379a9689/bokeh/client/connection.py) and raise an error matching this reason?

If so, I would suggest adding specialised DISCONNECTED classes in the states.py file (https://github.com/bokeh/bokeh/blob/57da24a50e53c8b97e6efa155272e1a9379a9689/bokeh/client/states.py) for the given disconnect causes and create a way to access those through the ClientConnection class. 

If this sounds like the correct way to solve this issue to you, I will try my luck implementing it.

Best Regards,
Sönke

**Comment by bryevdv** [comment]
@Soflon1 A summary of the issue is this:

There are two ways a client connection can fail:

* The Bokeh server is not started at the given network address, at all
* Bokeh server is started at the given network address, but the app path is not good

Currently, both of these scenarios report the same error and suggest "start a Bokeh server" 

The ask is to differentiate these two situations for so that better errors can be given to users. In the first case, a network error, the advice should continue to be "start a Bokeh server". In the second case, a 404 HTTP return code, the advice should be "bad app path, check app path"  

 I'm not sure that this can be handled with DISCONNECTED states, however, because DISCONNECTED implies a connection was already first made, then lost. In both these cases, no connection has ever been made yet.
