### ISSUE TITLE
Docs on widgets & interactions should link to the Callbacks & Events section

### ISSUE THREAD

**Issue by pzwang** [bokeh/bokeh#3656]
A blurb should be added to the "Adding Widgets" section of the docs (http://bokeh.pydata.org/en/latest/docs/user_guide/interaction.html#adding-widgets) that points people to the Server Guide part on applications, so they know what it looks like to actually write a non-JS callback function for various widgets.

http://bokeh.pydata.org/en/latest/docs/user_guide/server.html#userguide-server-applications

**Comment by clairetang6** [comment]
@pzwang I agree that it would be great if there was an easier way to find an example of python callbacks/handlers in the documentation. But something that might be confusing with just that link is that in the widgets section, it says to add callbacks by using .on_change, whereas the example in the server applications uses .on_click (which I don't think is found anywhere in the documentation except in the Reference). 

The statement in the Adding Widgets section, "The current value of interactive widgets is available from the .value attribute." is also confusing since not all widgets use the .value attribute. Some use .active and the Button uses .clicks. 

In general, I think this section could use some more information. Being able to run arbitrary Python code to modify a visualization is a huge selling point for me with Bokeh, and I couldn't figure out even how to start using the widgets from just that section. 

I could write up some stuff that I would have liked to see in the User Guide. I don't know exactly what other work is being done with the callbacks and events ([Issue about .on_change API used by widgets](https://github.com/bokeh/bokeh/issues/3115)) or their timelines, but it seems like more information in this section would be really helpful.

**Comment by bryevdv** [comment]
@clairetang6 a writeup to add more info would be *extremely* welcome and appreciated. I do think there is some work to do before 1.0 to clean up and regularize things, and hopefully add a real "event"  message for "fire and forget" type events like button presses, but I'd say those are at least a couple of months out so more info about what is there right now would be very valuable.

**Comment by clairetang6** [comment]
I think this issue can be closed. There is still nothing pointing people to the Server Guide, but the section on Adding Widgets was expanded in this [PR](https://github.com/bokeh/bokeh/pull/3997), including examples of how to write python event handlers.
