### ISSUE TITLE
Add option to check if session exists

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3725]
When building the happiness demo, I am storing session ids in the django database and reconnecting to them periodically (using `pull_session`) to update data. If the bokeh server gets restarted, or if the sessions time out, those sessions will now be empty.

It would be nice if there was a utility to check whether a session actually exists. Two options spring to mind:

1) A client utility 

``` python
from bokeh.client import verify_session_exists

# verify_session_exists(session_id, url='default', app_path='/', io_loop=None)
# simplest usage, returns True or False
exists = verify_session_exists('d234dgw-56wrgsfgaet54-3453w5')
```

2) An option on pull_session

``` python
from bokeh.client import pull_session

# pull_session(session_id=None, url='default', app_path='/', io_loop=None, autocreate=True)
# returns None if session doesn't exist and so wasn't created
session = pull_session(session_id='d234dgw-56wrgsfgaet54-3453w5', autocreate=False)
```

**Comment by birdsarah** [comment]
ping @havocp

**Comment by havocp** [comment]
This does seem useful. I would recommend the `autocreate=False` option because it's both more efficient and avoids a race condition (where the session vanishes in between checking for it and connecting to it). To implement this I would suggest the following:

 * add a `self.get_argument("autocreate-session")` in the same way we get protocol version and session id query params here: https://github.com/bokeh/bokeh/blob/master/bokeh/server/views/ws.py#L66-L71 , parse the query param into a boolean
 * pass autocreate flag in to _async_open
 * _async_open should pass it in to create_session_if_needed, which would
   `raise gen.Return(None)` instead of creating, if autocreate=False
 * in _async_open, currently it does create_session_if_needed and then
    get_session; but create_session_if_needed already returns the session, 
    so I'm not sure why. change to `session = yield create_session_if_needed`
 * if session is None in _async_open, self.close() with some distinctive error code (existing examples: https://github.com/bokeh/bokeh/blob/master/bokeh/server/views/ws.py#L81 )
 * on client side, if autocreate=False set the query parameter; then if connection fails, it may be simplest to let this throw an exception so nonexistent session is handled the same way as failure to connect or whatever? that should Just Work with no changes, you'd have to make client changes to check the error code if you wanted autocreate=False to fail in a special way like returning None for the session.

**Comment by bryevdv** [comment]
I think I a going to go ahead and close this with `noaction`

* we don't really encourage this kind of usage (modifying a session up front, yes, but not re-connecting and tweaking it later)
* direct query check would likely be susceptible to race conditions
* has not been any other feedback requesting in 4 years
* could potentially be rolled in to the issue for "pre-flight" check
