### ISSUE TITLE
ENH: output_file_string to output generated HTML as string

### ISSUE THREAD

**Issue by nipunbatra** [bokeh/bokeh#373]
Why this may be useful?
When we may wish to render HTML ourselves, say in a web app, over an AJAX. This for use cases when one wishes to use own server, instead of bokeh-server.

reference: https://github.com/jakevdp/mpld3/issues/71

**Comment by ZhanruiLiang** [comment]
This shouldn't be closed with the reason described in the last comment. @nipunbatra was using HTML(html) just for the sake of demo. What he really want was to output html as string instead of file. And output_notebook() cannot do this. 
Please verify if this is implemented(given it's 2.5 years later) or reopen.

**Comment by bryevdv** [comment]
@ZhanruiLiang I'd like to discourage you from commenting on on very old closed issues. Bokeh is incredibly different from 2.5 years ago, and most of the information in this issue is wholly out of date and not applicable. It's also better to take support questions (e.g. "How do I...?") to the mailing list *first*. If it turns out there is no way to do something, then a feature request issue could be appropriate (if there is not already one open). Finally, try to make use of the docs. The answer to your question is the very first section in "Embedding Bokeh" chapter of the user guide:

http://bokeh.pydata.org/en/latest/docs/user_guide/embed.html#standalone-html

**Comment by damianavila** [comment]
@ZhanruiLiang  http://bokeh.pydata.org/en/latest/docs/user_guide/embed.html#standalone-html
