### ISSUE TITLE
push-only, or widget-only sync modes 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#3745]
A reasonable use case is a streaming app that wants to push updates to clients, but does not have any need to receive some or all events back from the client. For example, an updating timeseries plot can generate many range start/end updates back to the server. It should be possible to tell the client that these should not be sent, which will improve the scaling behavior of streaming apps when these assumptions hold. Some possibilities:
- a "full" mode where all events are sent (what we have now)
- a "none\* mode where the client only reacts, but does not generate any messages back to the server at all
- an "auto" mode where only models that have callbacks attached to them get events sent back to the server
- "widget-only" mode where only widget events are sent back to the server

@bokeh/core thoughts?

**Comment by almarklein** [comment]
Do you see these modes as global, or per-model? If the latter, the possibility to set the mode to "none" or "one-way" sounds like a simple and effective solution. In the use-cases where this problem occurs the problem is usually related to specific models, I presume.

The "auto" mode seems like it could be quite a bit more work. The widget-only sounds a bit arbitrary to me.

**Comment by birdsarah** [comment]
`Full` and `none` and `auto` modes sound great.

I have a question: Imagine a callback that's attached to range. The server is processing the data and pushing it down to the client, when it arrives, the data changes, so the range changes, does that trigger an event back up to the server?

If yes, then I can imagine a mode where the above scenario does not trigger an event, but when a user interacts with a range - pans/zooms then we do want to trigger an event. This maybe what you meant by widget mode - but in my mind widgets and tools are slightly seperate.

The thing that springs to my mind is some kind of incremental approach where we start with a models-like interface. So, you can have `full` or `none`. As a "power-user" I pick `none` and then I manually add my triggers just in the same way that we do `plot.add_tools(HoverTool(tooltips=None, renderers=[])` we could now also specify triggering at a low-level interface.

This might help us to build up some real-world applications and then look at the use cases we want to simplify. Of course, we have lots of dark users and so we may not get that insight unless we build a "helpful" mode like "auto" and then see what complaints we get about it.

Either way, I think we would want that low-level trigger interface, so I'd be keen to think more about what that would look like - because it's not clear to me off the top of my head.

**Comment by bryevdv** [comment]
I've not perceived any real demand for this and it currently seems like it would be unecessary complication.
