### ISSUE TITLE
Delay on Hover Tool Mouseover

### ISSUE THREAD

**Issue by brittainhard** [bokeh/bokeh#3780]
Currently, if you are using the Hover tool and you mouseover a datapoint, the tooltip containing information for that datapoint shows up instantly. It would be nice to be able to add a delay between when you mouseover a data point and when the tooltip shows up.

In this case, an option like `tooltip_delay=0.4`, where `0.4` is the number of seconds.

**Comment by bryevdv** [comment]
What is the rationale for a delay?

**Comment by mattpap** [comment]
E.g. to avoid flickering. When you have small gaps between data points, you will observe hover showing up, hiding and showing up again rapidly, which is annoying. But maybe this is a different issue from what's requested here.

**Comment by bryevdv** [comment]
I don't see how this would solve flickering, for that you'd need a delay to *hide* and that seems untenable. In any case this seems unlikely so closing

**Comment by Dylan-opdam** [comment]
I would be interested in this feature as well.
I have a plot with many data point close together (the hover tool covers a significant portion of the data points). As soon a the cursor enters the plot the hover tool pops up and keeps switching to a new data point as I'm moving it to the intended data point. This makes it difficult to find the data point I wanted, since my hover tool includes external images this generates unnecessary traffic, and it just look sloppy.

A delay would solve this issue, allowing a user to move the cursor to the intended data point and once settled there for x seconds the hover tool pops up.
