### ISSUE TITLE
Reset should call the responsive resize.

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3783]
Bryan noticed on the happiness demo that resize causes the plot to shrink.

It actually causes the plot to shrink or grow depending on whether responsive view is making plot bigger or smaller. 

I'm guessing that reset is resetting the plot_width and plot_height (which I don't think it used to do) and then the responsive resize code is not being called.

**Comment by birdsarah** [comment]
You can see this same phenomenon in `howto/charts/excel.ipynb`

**Comment by birdsarah** [comment]
I see #1683 was marked as fixed via #3254 - I'm guessing that's the source of this bug. ping @mattpap

**Comment by jbednar** [comment]
I'm not sure if it's the same problem as you're seeing, but the "reset" tool doesn't seem to be generating a callback for our (admittedly highly customized) callback setup in https://github.com/bokeh/datashader/blob/master/examples/nyc_taxi.ipynb).  I.e., our Python callback function is called on any zoom or pan, and the reset tool correctly resets the ranges, but it doesn't seem to generate a call to our Python code.  After the reset, I have to then zoom or pan a little to get the image redrawn.  Again, this could be our fault, as part of our own JavaScript code we're using, but I don't *think* so, because we haven't done anything special for the reset tool, at least not deliberately.  So I think our problem has the same source as what you are reporting here, and hopefully the same fix.

**Comment by philippjfr** [comment]
>our Python callback function is called on any zoom or pan, and the reset tool correctly resets the ranges, but reset doesn't seem to generate a call to our Python function.

Note that the python callback is executed through a regular ``CustomJS`` callback. Reset events definitely do not trigger callbacks attached to the ``x_range`` or ``y_range`` currently.

**Comment by birdsarah** [comment]
Confirm under #4392

**Comment by jbednar** [comment]
> Confirm under #4392

Is that a statement, i.e. you confirm that it still applies under 4392, or a question, asking us to confirm that it still applies under 4392, or...?

**Comment by birdsarah** [comment]
It's a ToDo. I believe that it's done, but I want to check. #4392 is the layout clean-up PR.

**Comment by birdsarah** [comment]
There are other issues with the resize and reset tool since the layout came in, but the original bug reported on this issue is now fixed. That is, if you now hit reset on a responsive plot, it does not weirdly resize to an original "fixed" size.

**Comment by jbednar** [comment]
Thanks!
