### ISSUE TITLE
How do you pass arguments to an app?

### ISSUE THREAD

**Issue by jaredsagendorf** [bokeh/bokeh#3793]
I'm very new to using Bokeh, and trying to implement a research project with it. As I understand it, I can set up a bokeh server to serve some application on a specific port/host, and then use a server like nginx to serve static content. 

What I want to implement is a bokeh server that will serve some specified app, where that app produces visualizations of a specific dataset, which is passed as an argument. Essentially I'm building a database, which stores many datasets, and I want to query the database, retrieve some specific dataset which the user chooses, and then have the bokeh app produce the graphics for that specific dataset. 

Can someone point me to an example of how to pass arguments to an app through the bokeh server?

p.s. I'm also new to git hub, so I'm sorry if this is not the appropriate place for questions.

**Comment by copperwire** [comment]
I'm sure someone will come by with a better tip - but a way to solve your problem is with callbacks and sources. 

An example would be a button that prompts the user for a file in such a manner. 
 
    def handler():
              pass
     button = bokeh.models.widgets.Button(label = "foo")
     button.on_click(handler)

Where the `handler` function grabs a file in a manner you prefer. It can also be used to set data in an instantiated plot.
    
    
    figure_object  = figure() 
    source = ColumnDataSource(data = dict(x = [ ], y = [ ]))
    figure_object.line("x", "y", source = source)
    
Where you in the handler function would grab the data from your file in arrays `u` and `v`. You could then do something like this to update the plot.

    def handler():
           source.data = dict(x = u, y = v)

When coupled with a server this type of interaction updates plots in realtime and should hopefully be applicable to your project. The server syntax you need is simple. You need to run a bokeh server from the command line by 

    bokeh serve

which starts a server. In your file you need to push the session to the server, show the document and loop continuously to take updates in the plot 

		session = push_session(curdoc())
		session.show()
		session.loop_until_closed()

**Comment by bryevdv** [comment]
Closing this, just because I think it is covered by some other issues. In particular #3349 covers sending some initial state to apps at startup.
