### ISSUE TITLE
Computed Transforms

### ISSUE THREAD

**Issue by hsparra** [bokeh/bokeh#3825]

**Comment by justacec** [comment]
@hsparra Can you provide me a little information on what the core concept of this feature would be?  I know that I might infer something from the title, but I do not want to guess.

**Comment by birdsarah** [comment]
@justacec, @hsparra has been helping us with project management, @bryevdv is the best person to anwer that question.

**Comment by justacec** [comment]
@bryevdv Is this where you would like to address the proposed transforms that you were discussing in my linear color mapper PR?

**Comment by bryevdv** [comment]
@justacec yes this issue would be great (sorry I should have linked to it!)

**Comment by justacec** [comment]
@bryevdv I started to play with this and then realized that, at least at first glance, that there are several Mapper classes which implement what you were looking for.  Specifically, I am speaking about the LinearMapper, LogMapper, and CategoricalMapper classes.  They also seem like a good place to be since transforms are more like a mapping from one space to another space.

Separately, you had suggested a Jitter transform.  This transform would not be reversible and its use would most likely be for visualization only.  Gplot implements this as a position.  Would it be better if Jitter in Bokeh followed a similar strategy?

**Comment by bryevdv** [comment]
Sorry for short reply --- on phone. The mappers you mention are not what was described in the other issue. Mappers are configured with ranges and maps between those ranges. The other issues describe interpolators that are configured with the sequence of points to interpolate. I see transform are the more general noninvertible case, and mappers as a special case of invertible transform.

**Comment by bryevdv** [comment]
Just to add more color around just a few of the things this one facility would help enable:

* custom tick formatting (e.g. Geo ticks from ugly UTM to nice lat/lon for display)
* custom field transforms in hover tools (several people asking about on ML right now)
* interpolation functions for other mappers (e.g. your color mapper)
* jitter and other visual dodging 
* improving the implementation of categorical variables 
* client (browser) side color mapping
* derived and computed columns in the browser
* others...

This is a *huge* feature. 

Another difference between these things and existing mappers has occurred to me: mappers require configuration on the client side, BokheJS has to set them up with one or more ranges (in the browser) in order for them to do their job. `Transform` models *don't* need anything extra. They are entirely configured from python, and the corresponding JS models are immediately ready to be used, with no extra config in the browser. So given that, maybe they should be made more explicitly different. E.g. `compute` and `v_compute` (or `execute` and `v_execute`) on the JS side, instead of looking similar to one-way versions of mappers.

**Comment by bryevdv** [comment]
@justacec if you'd prefer, I could take a stab at the foundational parts of this then you can add just the bits needed for your PR in your PR. Or if you'd like to work up this PR too, let me know.

**Comment by justacec** [comment]
Sure.  I started to play with it but then got diverted.  Lets see what
foundation we can get put together.

On Sat, Feb 20, 2016 at 10:23 AM, Bryan Van de Ven <notifications@github.com

**Comment by bryevdv** [comment]
Hi @justacec here is a rough start for a `bokeh.models.traansforms` module:
```
'''

'''
from __future__ import absolute_import

from ..core.enums import StepMode
from ..core.properties import abstract
from ..core.properties import Either, Enum, Float, Instance, Seq, String, Tuple
from ..model import Model
from .sources import ColumnDataSource


@abstract
class Transform(Model):
    ''' Base class for ``Transform`` models that represent a computation
    to be carried out on the client-side.

    JavaScript implementations should implement the following methods:

    .. code-block: coffeescript

        compute: (x) ->
            # compute the transform of a single value

        v_compute: (xs) ->
            # compute the transform of an array of values

    '''
    pass


class Jitter(Transform):
    ''' Apply uniformly sampled random jitter to data.

    '''

    interval = Float(default=0.8, help="""
    The width of the random sample interval to use for jitter.
    """)


@abstract
class Interpolator(Transform):
    ''' Base class for interpolator transforms.

    Interpolators are configured with ``values`` which can either be:

    * A literal sequence of values:

    .. code-block: python

        interp = Interpolator(values=[2, 5, 10, 12, 16])

    Or a tuple ``(data source, column name)`` that specifies a column from
    a `ColumnDataSource` that should be used as the values to interpolate:

    .. code-block: python

        interp = Interpolator(values=(source, "earnings"))

    '''

    values = Either(Tuple(Instance(ColumnDataSource, String)), Seq(Float), help="""

    """)


class LinearInterp(Interpolator):
    ''' Compute a linear interpolation between the points given by ``values``.

    '''
    pass


class LogInterp(Interpolator):
    ''' Compute a log interpolation between the points given by ``values``.

    '''
    pass


class StepInterp(Interpolator):
    ''' Compute a step-wise interpolation between the points given
    by ``values``.

    '''

    mode = Enum(StepMode, default="after", help="""

    """)

```

There's also a small diff to add the new enum for `StepInterp`:
```
diff --git a/bokeh/core/enums.py b/bokeh/core/enums.py
index 7e2abca..e6482f5 100644
--- a/bokeh/core/enums.py
+++ b/bokeh/core/enums.py
@@ -166,3 +166,6 @@ ScriptingLanguage = enumeration("javascript", "coffeescript")
 
 #: Specify a start/end value
 StartEnd = enumeration("start", "end")
+
+#: Specify a mode for stepwise interpolation
+StepMode = enumeration("before", "after", "center")
```

**Comment by bryevdv** [comment]
I think if we implemented just what is above, that would be a perfect PR to demonstrate how to add on more transforms later as needed. Is this enough for you to get started? I would expect each of the corresponding JS models to be very small, sometimes just a few lines of code. 

After this is merged we can work up how to use it in your color mapper PR.

**Comment by justacec** [comment]
Let me take a look at it this evening, but I would image that it is good to
go.

On Mon, Feb 22, 2016 at 12:18 PM, Bryan Van de Ven <notifications@github.com

**Comment by justacec** [comment]
Ok..  working on it now...

**Comment by justacec** [comment]
I started with your base code and have now slightly modified the stock LinearColorMapper to use the Jitter transform which implements kind of a cool fuzzy effect.  I will push all of these changes up and get them in a consolidated pull request after some more refinement.

<img width="571" alt="screen shot 2016-02-27 at 2 36 39 pm" src="https://cloud.githubusercontent.com/assets/5904886/13374912/c2265eee-dd5f-11e5-9f96-b5aa7409651e.png">

**Comment by fpliger** [comment]
@justacec great! Do you have it somewhere we can take a look at (or give a hand)? Would be happy to give some support if you'd like ;)

**Comment by justacec** [comment]
I have it here in code right now and will put forward a pull request once I
get it cleaned up.  I am having a GIT issue right now.  I think.  I have
somehow got my two different branches confused with each other (one for the
ComputedTransforms and the other for the delayed_slider_callback).

**Comment by justacec** [comment]
@fpliger Just wanted to let you know that I have begun a PR to support this request.  The code to generate the above image is not included as I had to modify the stock LinearColorMapper and did not want to put that in.  I am going to make a duplicate LinearColorMapper, put those changes in there, and then put in the code necessary to make the above example tonight.

**Comment by fpliger** [comment]
@justacec awesome, thanks! Depending on how late I'll be at home I'll start looking at it tonight or tomorrow morning. That's very exciting!
