### ISSUE TITLE
push_notebook doesn't seem to work display updated table content

### ISSUE THREAD

**Issue by jms90h5** [bokeh/bokeh#3838]
The attached sample notebook demonstrates that the contents of a displayed table doesn't update with push_notebook after modifying its data source.

(This was last tested in v0.11.1)

[push_notebook_table_test.ipynb.zip](https://github.com/bokeh/bokeh/files/120385/push_notebook_table_test.ipynb.zip)

**Comment by canavandl** [comment]
This is kind of a nasty bug.

So the issue is that a DataTable isn't a Component subclass (like plots and layout objects i.e. HBox, VBox), but rather a Widget. When push_notebook() is called to update the data table, it captures the "Document" state then makes the appropriate changes.

Because a DataTable isn't a Component subclass, it isn't added as a root to the Document state:

<img width="1100" alt="screen shot 2016-02-21 at 10 18 09 pm" src="https://cloud.githubusercontent.com/assets/2198981/13209547/9a32f3da-d8ea-11e5-8973-e01cd41aa267.png">

So bokeh doesn't see it needs to update the table.

A current work around is the wrap the DataTable in a layout object (here using vplot), which will add the data table as a child root to the Document:

<img width="1125" alt="screen shot 2016-02-21 at 10 18 31 pm" src="https://cloud.githubusercontent.com/assets/2198981/13209557/ccaaa4f2-d8ea-11e5-857f-01c2aeb496b0.png">

Going forward though, we need to refine the management of widgets inside the curdoc.

ref issue: #3117

**Comment by canavandl** [comment]
ping @havocp @bryevdv 

Hopefully this can help inform your layout improvements

**Comment by jms90h5** [comment]
Thanks for taking the time to chase this down and the workaround works great.  So for me right now it would be ok to close the issue.  However, if you want to keep it open to cover the internal widget management enhancements that might make some sense also.  I'll defer to you to close this particular issue or not.

**Comment by canavandl** [comment]
I'm glad the work-around works for you. I'll leave the issue open, so that other people can find it if they have problems and we have record of the defect. Thanks for opening an issue!

**Comment by bryevdv** [comment]
This is now working. Current results with the supplied notebook (with a few updates):

<img width="727" alt="screen shot 2017-05-11 at 21 51 59" src="https://cloud.githubusercontent.com/assets/1078448/25980421/13bba56e-3694-11e7-82ab-cf369719fee8.png">
