### ISSUE TITLE
Box and wheel zoom not working for me in Chrome on Ubuntu

### ISSUE THREAD

**Issue by cthrall** [bokeh/bokeh#3857]
Last night, I was using Chrome on OS X to render data using Bokeh in a Jupyter notebook. The box and wheel zoom buttons worked fine. I was able to pan and zoom no problem.

This morning, I browsed to that same notebook in Chrome on my laptop that's running Ubuntu 14.04 and clicking on the box and wheel buttons does nothing. The blue indicator on the buttons doesn't light up.

Both box and wheel zoom buttons do work when I'm using Firefox.

I see the same behavior when I embed my Bokeh chart in a page that's rendered by a Flask web app. I've attached the source for that page.

Thanks very much for making Bokeh, by the way!

[bokeh.html.zip](https://github.com/bokeh/bokeh/files/125446/bokeh.html.zip)

**Comment by birdsarah** [comment]
Hi @cthrall, thanks for your interest in Bokeh. 

As Bokeh gains more users, our issue tracker is growing unmanageable. We are having to be a bit more disciplined about directing people to the mailing list for general support questions, so that the issue tracker can be reserved for development-related discussions. There are more people on the mailing list who can potentially help, so it is a better resource for support questions in any case. That is why I am going to close this issue, I hope you will repost your question on the mailing list, which is here:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
