### ISSUE TITLE
Charts ignoring manually defined ranges in call

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3860]
See notebook here: http://nbviewer.jupyter.org/github/birdsarah/bokeh-miscellany/blob/master/set%20range%20on%20chart.ipynb

This correctly sets the `x_range` to what the user wants:

``` python
x_range = Range1d(20, 30)
p = Scatter(df, x='mpg')
p.x_range = x_range
```

But this does not:

``` python
x_range = Range1d(20, 30)
p = Scatter(df, x='mpg', x_range=x_range)
```

I've checked for Scatter and Bar - I'm guessing it's true for all Charts

**Comment by rothnic** [comment]
The initial iteration of the charts I had the builders providing the range because the range depends on the axis type and the axis type you'd use depends on the data that is being plotted against that axis. In general the way bokeh/bokehjs handles different kinds of axes/ranges that are interdependent makes this difficult from the standpoint of a generalized chart.

In the work I was doing for interactive charts I had some rework in there for how builders communicate back to the chart their range information, then the chart manages the ranges. That is in the charts/interactive branch.

Just wanted to provide that context.

**Comment by fpliger** [comment]
Yeap, just had a look at this.. Right now we are just not considering the explicit ranges arguments at all (which we shouldn't). 

For some charts is easier then others but in general I think we should user the consenting adults policy here. If users explicitly pass the ranges as arguments we should just use them and (maybe??) fire an warning that users should be aware that custom ranges should match the data they are plotting..

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/17)
