### ISSUE TITLE
`bokeh serve` should (perhaps optionally) allow some apps to fail

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#3861]
Right now it appears `bokeh serve` requires all listed apps to exist and run successfully.  It would be nice to have an option where `bokeh` won't bork out if one of the apps fails for some reason.  I'd even say it would be good to have this as the **default** and the _option_ should be something like `--strict` which would require all apps to start and run successfully: the failure of one would abort bokeh server.

The scenario where this came up: we have a supervisord-managed bokeh server that mirrors demo.bokehplots.com and has a list of bokeh apps.  We added an additional app, but due to the way this is done at some points that app is not present (the path is invalid).  We'd still like `bokeh serve` to work for the other listed apps.

**Comment by birdsarah** [comment]
ping @havocp

**Comment by havocp** [comment]
I think I would find "happily start up with an app that doesn't exist" surprising behavior. But I'm just one data point.

- if a deploy script or tool starts a server, often it should fail (rather than pretend to succeed but not have an actual app running), so the script can do whatever it does on failure
- if I'm developing locally and typo the app name I'd think I want an error message and then retype the command

What would be at the apps url if the app didn't exist - a blank page like we do for an empty directory, or some kind of explanatory message, or a 404?

**Comment by havocp** [comment]
I love #3862 as an elegant solution to this scenario of dynamic app list

**Comment by bryevdv** [comment]
closing absent further comment or discussion. The conf file in the other linked issue seems reasonable to pursue.
