### ISSUE TITLE
Error with histogram

### ISSUE THREAD

**Issue by andrefilipemb** [bokeh/bokeh#3875]
I am trying to create a Histogram with Bokeh and I'm getting the following error. The histogram is completely wrong.

For example

I have this list:

[1205.0, 2527.0, 1745.0, 1556.0, 493.0, 2276.0, 556.0, 1928.0, 2641.0, 1897.0, 1891.0, 1545.0, 1307.0, 1692.0, 1543.0, 1282.0, 775.0, 2032.0, 1240.0, 473.0, 1612.0, 605.0, 327.0, 946.0, 541.0, 1539.0, 529.0, 628.0, 1453.0, 297.0, 703.0, 269.0, 751.0, 245.0, 1182.0, 515.0, 435.0, 383.0, 457.0, 730.0, 614.0, 414.0, 324.0, 776.0, 611.0, 544.0, 538.0, 579.0, 806.0, 459.0, 458.0, 626.0, 621.0, 544.0, 535.0, 385.0, 401.0, 614.0, 665.0, 488.0, 172.0, 142.0, 37.0, 453.0, 355.0, 22.0, 502.0, 273.0, 720.0, 582.0, 198.0, 198.0, 597.0, 516.0, 815.0, 402.0, 605.0, 711.0, 614.0, 468.0]

And when I try to create a histogram:

hist = Histogram(val)
show(hist)

I get: (the Y-axis is completely wrong) ... How can I solve this?
Thanks

**Comment by birdsarah** [comment]
Hi @andrefilipemb, our issue tracker is becoming too large to manage easily. We have to reserve it for feature requests and bug reports only, to have any hope of taming it. This kind of support question should go to the general public mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

We hope you post there, and then if there turns out to be a bug we welcome you opening a new issue with the specific bug report.

**Comment by twaugh** [comment]
Er... this exact question *did* go to the mailing list, and the advice was to file an issue.
https://groups.google.com/a/continuum.io/forum/#!search/histogram/bokeh/JTsX9Hx-1sY/cGsUfqPvDAAJ

**Comment by twaugh** [comment]
```
from bokeh.charts import Histogram
from bokeh.plotting import output_file, show
hist = Histogram([300, 300, 300, 400, 400, 500])
output_file('/tmp/output.html')
show(hist)
```

**Comment by twaugh** [comment]
![histogram](https://cloud.githubusercontent.com/assets/6985468/13460102/45b1d38e-e070-11e5-9e38-4ce2f375c484.png)

Note how the Y-axis counts 500 values for one bin, when clearly there are only 6 values in the entire data set.

Also note how we'd expect a histogram much weighted to the left than the right, i.e. count(300) is 3, count(400) is 2, count(500) is 1.

**Comment by fpliger** [comment]
thanks @twaugh for the follow up on this and the code to reproduce.. I think this is actually a (weird?) bug, will try later and reopen the issue if confirmed..

**Comment by fpliger** [comment]
This is definitely a bug (lnteresting one :) ).. reopening...

**Comment by fpliger** [comment]
Issue should be here: https://github.com/bokeh/bokeh/blob/master/bokeh/charts/glyphs.py#L603-L605

Which I'd be tempted to remove this part (since I miss the possible scenarios) but seems to fall into a very specific case... so need more more tests before just removing that.. 

pinging @rothnic for some historical knowledge :-)

**Comment by sushmit86** [comment]
Has this been resolved ? I am having a similar issue

**Comment by damianavila** [comment]
@sushmit86 solved here: https://github.com/bokeh/bokeh/pull/3988, should be available for the next release (or in the next devel build if you want to test it early).

**Comment by axelpale** [comment]
A **quick fix** is to decrease the number of bins. For example, my histogram breaks with 15 bins but works as expected with 14 bins. It seems that the more values you have, the more bins you can use.
