### ISSUE TITLE
Color tuples not working as expected

### ISSUE THREAD

**Issue by jiffyclub** [bokeh/bokeh#3892]
Using Bokeh 0.11. I've tried this with `Scatter` and `Bar` and in neither case does specifying `color=(r, g, b)` or `color=(r, g, b, a)` work:

``` python
fig = bc.Scatter(
    df, x='xcol', y='ycol', color=(255, 0, 92))
show(fig)
```

``` python
fig = bc.Bar(df, values='value_col', label='category', agg='mean', color=(0, 255, 92))
show(fig)
```

In both cases Bokeh silently ignores the color argument and plots using the default red. There are no errors.

Specifying colors as CSS names or six-character hex strings works as expected. This seems similar to #2161, but that's been closed a long time.

**Comment by fpliger** [comment]
This is a bug on charts. It should support color tuples. That said, it's more likely that an user specifies palette with a list of colors instead of a color argument (since it ends up coloring everything loosing whatever grouping color information you may have).

That said, also palette do not support palettes of color tuples.

**Comment by canavandl** [comment]
Hi @jiffyclub 

You need to enclose your color tuple in another list or tuple:

```python
fig = bc.Scatter(
    df, x='xcol', y='ycol', color=[(255, 0, 92)])
show(fig)
```

without the enclosure, bokeh thinks the color arg is a sequence of colors like ['red', 'blue', 'red] for the scatter points, instead of a single color tuple.

However, the fact that malformed color argument fails silently is definitely bad.

**Comment by jiffyclub** [comment]
Thanks for the tip @canavandl! That was not clear from the documentation: http://bokeh.pydata.org/en/0.10.0/docs/user_guide/styling.html#specifying-colors

**Comment by bryevdv** [comment]
If necessary, this issue should be re-opened in the `bkcharts` repo.
