### ISSUE TITLE
How to add a custom model?

### ISSUE THREAD

**Issue by doomsplayer** [bokeh/bokeh#3900]
Hi developers:
I have a custom model currently:
```
from bokeh.plotting import Figure
from bokeh.core.properties import Dict, String, List

class EnhancedFigure(Figure):
    __implementation__ = """
    Plots = require "models/plots/plot"
    class EnhancedFigure extends Plots.Model
        type: "EnhancedFigure"
    module.exports =
        Model: EnhancedFigure
    """
    variables = Dict(String, String)
    category = List(String)
```
and I wrote it into bokeh server's initiate file(`bokeh serve bootstrap.py`). Everything goes fine except for the autoload_server.
`autoload_server` will cause the javascript complaining about `Bokeh: Failed to repull session Error: Module `MyFigure' does not exists. The problem may be two fold. Either a model was requested that's available in an extra bundle, e.g. a widget, or a custom model was requested, but it wasn't registered before first usage.`

So, how to register the model to javascript side?
P.S. Is there any place to put these noob questions into? e.g. irc or google group

**Comment by doomsplayer** [comment]
Solved, I've used bokeh 0.11.0 where "models/plots/plot" does not exist at that time.

**Comment by bryevdv** [comment]
Hi @doomsplayer I'm glad you found the solution, and I am sorry we did not get to this earlier. Our user base and issue tracker are both growing and we are still trying to find ways to effectively manage that with the current limited team. 

The mailing list is probably the best place for questions like this, because theres a larger potential audience who can answer questions there. It is located at:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

Thanks!

**Comment by doomsplayer** [comment]
@bryevdv thanks for the notification
