### ISSUE TITLE
Add xaxis, yaxis accessors to Chart class

### ISSUE THREAD

**Issue by dennisobrien** [bokeh/bokeh#3908]
From a discussion on the mailing list.

Chart objects do not have an easy, obvious way to get access to the xaxis and yaxis.  For comparison, Figure has a number of convenient property accessors.

- xaxis - returns a list of x axes "above" and "below" if they exist
- yaxis - returns a list of y axes "left" and "right" if they exist
- axis - returns a list of all axes
- legend - returns a list of all legends
- xgrid - returns a list of x grids
- ygrid - returns a list of y grids
- grid - returns a list of all grids

Chart has a few class variables with these names already.
- legend
- xgrid
- ygrid

First question:  What new methods should be added to Chart?
xaxis and yaxis are clear.  But what about legend and grid?  Do the names need to be changed to prevent collision with the class variables?

Second question: What should be returned?  A list, or just the Axis object?
Chart objects only have a one xaxis and one yaxis, so returning a list might not make sense here.

**Comment by bryevdv** [comment]
I think the existing names should be deprecated (removed outright? we can maybe make setters that warn, and make the getters return the relevant new things), and replaced with ones to match `Figure` (or we could see if `Chart` can just subclass `Figure` though I'm not sure that would work). 

I do think it should return a "splatable" list like `Figure`, though. Both for consistency/documentation as well as to keep open the possibility of multiple axes. Have discussed being able to combine two charts into one, and in some cases it might make sense to have the combined chart have multiple axes.

**Comment by fpliger** [comment]
IMO Subclassing Figure should be the way to go (if we don't find big implementation details preventing this that I can see atm)

**Comment by bryevdv** [comment]
I *think* the "Model subclass" machinery should work OK, but it's definitely not been tried for more than one level of inheritance.

**Comment by fpliger** [comment]
Just to give more info that should be helpful to someone actually working on this.

Some of these details on the Charts interface that differs from Figure are due to some historical leftovers. When `Chart` implementation started the approach as definitely less flexible and was not clear it should actually share any interface with Figure at all. The idea of adding `builders` that would "build" a `Chart` using it as a sort of blank canvas and adding all the components needed (glyphs, renderers, axis, ranges, legend tools, etc..) came in a second (or even third? :-) moment. 

Not only, but there are also some other considerations that should be taken carefully while doing/thinking about it. For instance, would this influence the current work towards making charts interactive? Should we have some limited support for specific "special" charts? (i.e, donut or horizon charts have specific internal details that would make it "hard" to change or add things with a plotting like interface...).

I do expect some naming clashes that will need to be fixed (specially with tools and ranges/axis). And @dennisobrien question about naming collisions gets it right.. 

To answer the second question, I think we should make an effort to make `Charts` just an extension (or slight limitation if needed) of the `Figure` API.

That said, I still think it's the way to go and shouldn't be terribly hard (if there are no surprise along the way). :)

@dennisobrien please let me know if you'd like to work on it.. I'd be happy to help.

**Comment by dennisobrien** [comment]
Hi @fpliger 

I'm interested in working on this.  It would be a good opportunity for me to dive into the design and interfaces for `Chart` and `Figure`.  I will need to study the code before I feel confident enough to make an implementation change proposal.  Changing `Chart` to subclass `Figure` instead of `Plot` seems straightforward with the exception of the name collisions.  And any other surprises along the way.

I'm interested in any ideas and feedback you have.

Should I proceed with a PR so we can discuss more concretely?

thanks,
Dennis

**Comment by dennisobrien** [comment]
I finally set aside some time to make `Chart` inherit from `Figure` (instead of `Plot`) and made the necessary changes to make things work.  (Still testing.) I have a few questions.

1) Some confusion (on my part) about class variables in the `Chart` class.
`Chart` has a class variable `legend` while `Figure` has an instance property `legend` (getter only).  `Chart.legend` is a `PropertyDescriptor` object.  I was kind of mystified how these class variables did not cause interference between two `Chart` objects with different values for `legend`, but it seems that once a `Chart` object is created, `builders.create_and_build` is called which calls `Chart.add_builder` and `Chart.start_plot` and those methods do all the getting of the class variables and store the values as instance variables.  I'm curious why the class variables?

2) The class variable `legend` in `Chart` does not interfere with the instance getter `legend` in `Figure`.
In fact, `self.legend` in `Chart` goes to `BasicProperty.__get__`, not `Figure.legend` property.  I don't think it's good to have both because they have different semantics.  In `Chart` it is `True` or a string or a location while in Figure it is a list of `Legend` objects.  They could co-exist but at the cost of confusion.  But removing it from `Chart` will break existing code unless this is a different solution.  Any thoughts about how to move forward?

BTW, the same applies for `xgrid` and `ygrid`.

I'll commit a branch with the changes so we can discuss more concretely.

cheers,
Dennis

**Comment by dennisobrien** [comment]
I ran into a few issues running the examples.

```
/usr/bin/python3.4 /home/dennis/workspace/bokeh/examples/charts/file/bar_multi.py
Traceback (most recent call last):
  File "/home/dennis/workspace/bokeh/examples/charts/file/bar_multi.py", line 9, in <module>
    bar_plot = Bar(df, label='cyl', title="label='cyl'")
  File "/home/dennis/workspace/bokeh/bokeh/charts/builders/bar_builder.py", line 323, in Bar
    if len(chart.x_range.factors) == 1 and not label:
AttributeError: 'DataRange1d' object has no attribute 'factors'
```

The code:
```
    if len(chart.x_range.factors) == 1 and not label:
```

The `BarBuilder` object has an instance variable `x_range` which is a `FactorRange` but the `Chart` object is now getting `x_range` set in its superclass `Figure` via `helpers._get_range`, defaulting to a `DataRange1d`.  When `Chart` subclassed `Plot` instead of `Figure`, it picked up the `x_range` class variable from `Plot`.  I tried passing "x_range" in the keyword args passed to `create_and_build` for `Bar()` but `create_and_build` separates the keyword args for the builder and the chart based on the properties of the builder.  I'm still trying to figure out how the `x_range` set in `BarBuilder` was accessible to the `Chart` returned from `Bar()`.
https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builders/bar_builder.py#L323

I'd appreciate any insights or advice to help untangle this if possible.

cheers,
Dennis

**Comment by bryevdv** [comment]
>  I was kind of mystified how these class variables did not cause interference between two Chart objects with different values for legend

A lot of metaprogramming. Those class variables actually end up adding "properties" to every instance, the point being that it's very simple for anyone to write a new model:
```
class Foo(Model):
    bar = Int(help="some dial to twiddle")
``` 
and now instances of this class automatically can:
* serialize themselves to JSON properly
* do type and value validation to report usage problems as early as possible
* be automatically documented in the reference guide 

On both the python and JS sides, we can and likely will also use the properties to be able to auto-generate GUI forms for editing model properties. If you are at all familiar with the "Traits" library, our properties are basically a pure-python version of that idea, with specific customizations useful for Bokeh as well. 

All of this greatly lowers the bar for making models, since they are completely declarative, and almost never require writing any actual code. There's more info here: http://bokeh.pydata.org/en/latest/docs/dev_guide/objects.html#models-and-properties

The collisions between `legend`, `xgrid`, and `ygrid` are unfortunate, and very problematic. I am not sure there is anything that can be done to have `Chart` inherit from `Figure` that won't lead to some breaking change.  A few options I can think of:

* remove them from `Chart` (this breaks any current uses of them on `Chart`)

* Make both `Figure` and `Chart` have properties like:
```
    legend = Either(Bool, Instance(Legend))
```
where setting to `True` makes a default legend of some sort (for both `Figure` and `Chart`) and `False` disables any legend, or passing a `Legend` is an option to give an explicit legend.  (Alternatively  we can specify a "transform" to handle bool values and turn them into a default legend or `None` on the python side, this would probably be better)

This second option would break any usages of `Figure.legend[0]` I have no idea how prevalent that usage is, I *expect* not much, the who point of "splattable" lists was to be able to avoid  the indexing, but can't know for sure. Perhaps t would be worth polling the ML for thoughts. I think the second option is better but I am also loathe to do break *anything* to do with `Figure`

**Comment by bryevdv** [comment]
ping @bokeh/dev for thoughts, @mattpap your thoughts especially would be welcome here

**Comment by mattpap** [comment]
@bryevdv, I will happily contribute, but first I have to finish TS API.

**Comment by bryevdv** [comment]
After some thought, I think it is a mistake to have `Chart` subclass from `Figure` as there are assumptions about `Figure` that do not apply to `Chart` (and vice versa). One option would be to put all of this functionality on to `Plot` but in the interest of keeping "code" out of low level models, I think the best thing is to simply copy glyph methods from `Figure`:

https://github.com/bokeh/bokeh/blob/master/bokeh/plotting/figure.py

to Chart:

https://github.com/bokeh/bokeh/blob/master/bokeh/charts/chart.py

**Comment by fpliger** [comment]
>> After some thought, I think it is a mistake to have Chart subclass from Figure as there are assumptions about Figure that do not apply to Chart (and vice versa).

@bryevdv Could you provide more details about this? I totally see this when speaking about `Chart` assumptions that do not apply to `Figure` but less in the oposite case... I think `Chart` would not only benefit from `Figure` glyphs methods, but also from the added properties... I see potential conflicts on ranges/axes management though..

**Comment by bryevdv** [comment]
The `Figure` initializer accepts keyword argument and does actual processing related to ranges and axes that should never be done for `Chart`. Basically everything in the `Figure` initializer is not applicable to `Chart`.

**Comment by bryevdv** [comment]
@fpliger to be clear, I agree Chart would benefit from them: I am proposing to simply add them by hand, ins read of subclassing.

**Comment by fpliger** [comment]
👍

**Comment by bryevdv** [comment]
Regarding, `xgrid`, `ygrid`, and `legend`, given the work started in #4237, I propose the following:
* remove the properties from chart
* add the python property getters as-is from `Figure` 
* add new `Chart` specific python property `setters` that support the "setting" functionality of the current Bokeh properties, with deprecation warnings

Thoughts @bokeh/dev @dennisobrien ?

**Comment by bryevdv** [comment]
Another idea I would not be opposed to is to move the readonly pythonproperty gettters  `xaxis`, `xgrid`, etc. down to `Plot`
