### ISSUE TITLE
Tasks for Improved Layout

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#3914]
Initial rough task dump, in no particular order for now

* [ ] tests for layout algorithm. Especially be sure to cover all the different constraints that Box implements
* [ ] move all layout code to views rather than models
* [ ] drive all render/layout requests through a single function on `Document`
* [ ] make Plot and other widgets implement Layoutable
* [ ] make slider, input, etc. consistently spaced when in a box (so visually there's the same whitespace between each item in a column in particular)
* [ ] add "framed" property to group by border or shading items in a box
* [ ] add control over individual component sizing:
   * set minimum width, height, or both
   * set maximum width, height, or both
   * set aspect ratio (either width or height must then be unset) (can you set a range for aspect ratio?)
   * set whether to be the same size as rest of box or not
   * be sure incoherent size constraints warn or are impossible
* [ ] get rid of HTML table for toolbar / make toolbar a layout-able widget
* [ ] see if canvas layout can somehow be unified with or use similar mechanisms as box layout
* [ ] replace hbox and vbox with Row and Column

**Comment by birdsarah** [comment]
@bryevdv I have opened an issue https://github.com/bokeh/bokeh/issues/4164 which describes the big picture and the proposed work.

I think we can close this issue. Of the above todos you've written I'd break them into the following groups:

In proposal #4164 in one way or another
* [ ] get rid of HTML table for toolbar / make toolbar a layout-able widget
* [ ] replace hbox and vbox with Row and Column
* [ ] see if canvas layout can somehow be unified with or use similar mechanisms as box layout
* [ ] tests for layout algorithm. Especially be sure to cover all the different constraints that Box implements (given that PR shoudl have tests)
* [ ] make Plot and other widgets implement Layoutable (Layoutable isn't a thing - but there are things like it)
* [ ] make slider, input, etc. consistently spaced when in a box (so visually there's the same whitespace between each item in a column in particular)

Don't think we should do this:
* [ ] move all layout code to views rather than models (I couldn't find a way to do this although I have cleaned up layout code a lot)

Do we need this for now?
* [ ] add "framed" property to group by border or shading items in a box (this is a nice idea that could come later)
* [ ] drive all render/layout requests through a single function on `Document` (re-factoring the rendering on top of the solver/constraints stuff proved too much for my brain)
* [ ] add control over individual component sizing:
   * set minimum width, height, or both
   * set maximum width, height, or both
   * set aspect ratio (either width or height must then be unset) (can you set a range for aspect ratio?)
   * set whether to be the same size as rest of box or not
   * be sure incoherent size constraints warn or are impossible

For the last one - parts are in #4164, but I think other features can come along after an initial layout implementation.

**Comment by bryevdv** [comment]
I agree with closing this in favor of the other issue, and also with the things that can be done later.
