### ISSUE TITLE
Responsive Bokeh in an iframe works...backwards?

### ISSUE THREAD

**Issue by guillochon** [bokeh/bokeh#3928]
I have some Bokeh embedded in an iframe on a page, and I recently turned on the "responsive" flag for my figures to render them better on mobile. The responsive flag does seem to affect the figure size as I shrink the window, but the figure actually *grows* when I shrink the window. In fact, once the window is small, any window resize operation results in the figure growing.

Here's an example page where I've turned on the responsive flag: https://sne.space/sne/SN1987A/

The figures are each embedded in an HBox and a VBox, i.e. VBox(HBox(figure)). Any ideas what's going on here?

**Comment by mattpap** [comment]
`VBox` and `HBox` are terrible hacks and don't work well together (they will be replaced in next release). I would start from removing this nesting.

**Comment by guillochon** [comment]
@mattpap Replace them with what?

**Comment by mattpap** [comment]
If you have only `Plot`s then you could use `GridPlot`. Otherwise, `VBox(HBox())` (or the other way round) nesting rarely works. My suggestion is to verify that layouts aren't the source of the issue with responsive plots.

**Comment by guillochon** [comment]
I have `Figure`s and `Slider`s within the `VBox` and `HBox`. I don't think I have other options for laying out the `Slider` controls on the page without using box constructs. But please correct me if I'm wrong.

**Comment by birdsarah** [comment]
@guillochon responsive doesn't work inside HBox, VBox, or any layout - this is documented: http://bokeh.pydata.org/en/0.11.0/docs/reference/models/plots.html#bokeh.models.plots.Plot.responsive

(The effect your seeing has nothing to do with an iframe - you'd see it on a plain page too)

As @mattpap said, we are working on new layout.

Until then, I would recommend using `embed.components` to get individual plots in your html. Here's a page showing this in action: http://cecp.mit.edu/pages/economic-growth.html
Here's the code that made it: https://github.com/mit-jp/cge-tools/blob/master/crem_presentation/site/content/viz/national_comparison_economic.py#L69

I'm going to close this as the bug is documented and we're working on a much better fix.

**Comment by guillochon** [comment]
@birdsarah Do `Slider` objects work in `embed.components`? I'm able to use components for my plots, but not if I include a `Slider`, I get the following error:

> bokeh-0.11.0.min.js:1 Uncaught Error: Module `Slider' does not exists. The problem may be two fold. Either a model was requested that's available in an extra bundle, e.g. a widget, or a custom model was requested, but it wasn't registered before first usage.

**Comment by guillochon** [comment]
@birdsarah Also, I'm getting very strange behavior on iOS where the plots just grow and grow and grow when the responsive flag is enabled, check out this page on iOS for an example (not sure if this is happening on Android too): https://sne.space/sne/SN1572A/

**Comment by guillochon** [comment]
Just FYI for me personally I just disabled responsive and turned on horizontal scrolling on the page. Looking forward to the new layout options when they arrive!

**Comment by birdsarah** [comment]
@guillochon, apologies for the delay, had a spam fail with my github notifications

> @birdsarah Do Slider objects work in embed.components?
Yes

The error is probably occurring because you also need to include the bokeh-widgets.js (and css) in your html template.

> Also, I'm getting very strange behavior on iOS where the plots just grow and grow and grow when the responsive flag is enabled

I'm 95% certain this is due to use of HBox/VBox etc.

Regardless, new layout will be doing away with all of this. It's a big chunk of work but it's going well. Hopefully more updates in a couple of weeks.
