### ISSUE TITLE
Custom Extensions are not available when using bokeh.client

### ISSUE THREAD

**Issue by the-neworder** [bokeh/bokeh#3930]
Hi,

I'd like to control my plots directly with the bokeh-client (without creating a bokeh app). So I first start the server with:

`bokeh serve`

Then I execute [custom_datetime_axis.py](https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/custom_datetime_axis.py) where 
`output_file("custom_datetime_axis.html", title="custom_datetime_axis.py example")`
is replaced with:
`output_server("custom_datetime_axis.html")`

The execution of **custom_datetime_axis.py** fails with the server side message:

`File "/usr/local/lib/python2.7/dist-packages/bokeh/model.py", line 72, in get_class`
`raise KeyError("View model name '%s' not found" % view_model_name)
KeyError: u"View model name 'DateGapTickFormatter' not found"
`

The reason why this fails is that only the name of a Formatter is sent to the server. The server then expects to have this Formatter available somewhere which is not the case since its custom and has been created in **custom_datetime_axis.py**.

By copy and paste the DateGapTickFormatter class to:
`/usr/local/lib/python2.7/dist-packages/bokeh/models/formatters.py`

The example works again. This is however the worst possible solution. Is there any clean way to do this?

**Comment by bryevdv** [comment]
Architecting the new server so that it deals with real python objects directly afforded dramatic improvements in almost all aspects: reliability, maintainability, scalability, performance, and ease of use. However, are there certainly trade-offs (as always). In particular as you've correctly identified: real python objects *must* live on the server. I am not sure there is anything technically that can be done about that, unfortunately. It may be simply that custom models are only compatible with server apps. If that is determined to be the case, we could detect and warn about the situation. 

But, ping @bokeh/dev in case there are ideas I am overlooking.

**Comment by havocp** [comment]
I think the long-term solution to this is to allow first-class third-party extensions, that is, you should be able to install a package that provides both the server-side and client-side for a new model. Bokeh itself could install all or most of its models as extensions like this. Then the way you'd do this is simply to install the dependency and `bokeh serve` would find it.

On some level all that's missing is a way to get Bokeh to find a model without having to stuff it into `bokeh.models`.

In Bokeh 0.11, a possible workaround is to run a minimal Bokeh server script that includes the custom model and some minimal document, in order to get the custom model loaded; then modify that document from the client side script. That is do `bokeh serve mythingwithcustommodel.py` and then you can still connect to that and make changes from the client side. All that's special about `bokeh serve` with no script is that the initial document is empty (and, I guess, that the URL is `/`).

**Comment by the-neworder** [comment]
Thank you for your suggestion. I will try to create such a minimal server script.

**Comment by the-neworder** [comment]
For anyone who is interested in the workaround:

I created the following structure in the current folder:
```
visualize_server.py
models/
  - custom_models.py
```

visualize_server.py:
```
import imp
imp.load_source("custom_models", "./models/custom_models.py")
```
custom_models.py:
```
from bokeh.models.formatters import TickFormatter, String, List

# create a custom model for a new tick formatter
class DateGapTickFormatter(TickFormatter):
    ''' A custom TickFormatter useful for skipping dates

    Axis labels are taken from an array of date strings
    (e.g. ['Sep 01', 'Sep 02', ...]) passed to the ``date_labels``
    property.

    '''
    date_labels = List(String, help="""
    An array of date strings to map integer date indices to.
    """)

    __implementation__ = """
        _ = require "underscore"
        Model = require "model"

        class DateGapTickFormatter extends Model
          type: 'DateGapTickFormatter'

          format: (ticks) ->
            date_labels = @get("date_labels")
            return (date_labels[tick] ? "" for tick in ticks)

        module.exports =
          Model: DateGapTickFormatter
    """
```

The server is started in this folder with:
```
bokeh serve visualize_server.py
```

On the client:
```
output_server("custom_datetime_axis.html")
```
has to be replaced with:
```
output_server("custom_datetime_axis.html",app_path="/visualize_server")
```

**Comment by bryevdv** [comment]
Great workaround, thanks @havocp Perhaps this could go in a documentation section somewhere until there is some better solution.

**Comment by bryevdv** [comment]
> I think the long-term solution to this is to allow first-class third-party extensions, that is, you should be able to install a package that provides both the server-side and client-side for a new model.

This is also a great idea. I was trying to imagine pickling or serializing models automatically somehow but this seems much simpler and cleaner.

**Comment by MilesMcBain** [comment]
The workaround doesn't seem to work with the `push_session(app_path = ...)` interface. I notice it is deprecated.

If I supply the whole `url` including the "app dir" as suggested in the deprecation message, then when I try to view in the browser the paths to the bokeh JS libraries are broken and aren't resolved.

**Comment by bryevdv** [comment]
@MilesMcBain In order to look into this, please provide a complete test case to reproduce this problem. 

However, I'd also like to re-iterate that I do not recommend using `bokeh.client`, for all the reasons stated in the docs. It has intrinsic drawbacks that will never be overcome. Running applications directly in a Bokeh server (whether with a separate `bokeh serve` process, or Bokeh server embedded as a library) is *always* going to be more efficient, more scalable, and more reliable.

**Comment by MilesMcBain** [comment]
Thanks for your recommendation. I think I will follow it, so this is not a pressing issue for me. If you want to chase down the issue I put together a reprex for you: https://github.com/MilesMcBain/bokehissue3930_testcase

**Comment by bryevdv** [comment]
I'm absolutely no of the mind that running code *outside* the bokeh server is a bad and not supportable usage. `bokeh.client` is useful for:

* testing

* customizing individual sessions pulled from a real app runining *in* a bokeh server, before forwarding to a specific user. 

The usage of running `bokeh serve` with all the code *outside* the server in a separate script is a mis-feature.
