### ISSUE TITLE
Preview/Save menu hiding behind plot on website?

### ISSUE THREAD

**Issue by michaelaye** [bokeh/bokeh#3954]
I just tried the preview/save function on this example:
http://bokeh.pydata.org/en/latest/docs/gallery/candlestick.html
and the result looked like this:
https://www.dropbox.com/s/3a6l141vqle2ybe/Screenshot%202016-02-26%2016.10.01.png?dl=0
which is confusing at the least (same in Safari and Chrome, all on OSX, all current versions)
I also couldn't get to save anything, when I did right-click->save as on the remainder of that little preview window, it only offered to save something in html, i tried to change that extension to png, but the browsers (both) insisted that it would have to be html.

**Comment by bryevdv** [comment]
@michaelaye I am wondering if this is specific to the deployed versions on the website. Can you say if this happens when you run examples locally?

**Comment by birdsarah** [comment]
Thanks for the report @michaelaye, looks like we have a css bug on bokehplots.com - you can see that preview is working here, for example: http://demo.bokehplots.com/apps/sliders

I'm going to close this issue here. And open it in the bokehplots.com repo: http://github.com/bokeh/bokehplots.com

Nice catch!

**Comment by birdsarah** [comment]
https://github.com/bokeh/bokehplots.com/issues/2
