### ISSUE TITLE
Unable to set ColumnDataSource.selected via python

### ISSUE THREAD

**Issue by the-neworder** [bokeh/bokeh#3981]
I would like to preselect one of the following rects before sending them to the browser:
![screenshot from 2016-03-01 18 29 13](https://cloud.githubusercontent.com/assets/17453385/13460515/4d878f94-e07b-11e5-95b9-0b4bf07a83c1.png)

However, setting
```
source.selected['1d'] ['indices'].append(0)
```
does not have any effect when doing it on the server side.

Is this a bug or a desired behavior?

**Comment by mattpap** [comment]
The problem here is that you're modifying a nested data structure in-place, but this isn't reflected in bokeh's properties system. One thing you can do is `source.trigger('selected', None, source.selected)` to tell bokeh about those modifications. Another approach is to set a new value, i.e. `source.selected = {'1d': {'indices': [0]}}`.

**Comment by the-neworder** [comment]
Many thanks, your answer helped me a lot.
