### ISSUE TITLE
BoxAnnotation does not update consistently

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#3992]
When trying to update a BoxAnnotation it only updates the first time you push the new data, any subsequent changes get ignored unless you change some other plot attributes as well. I've also looked whether the events are getting sent and that seems to be the case, so it's probably an issue with triggering an update on the Coffeescript end.

Here is an example:

```python
from bokeh.sampledata.glucose import data
from bokeh.plotting import figure, show, output_notebook
from bokeh.models import BoxAnnotation

output_notebook()

TOOLS = "pan,wheel_zoom,box_zoom,reset,save"

#reduce data size
data = data.ix['2010-10-06':'2010-10-13']

p = figure(x_axis_type="datetime", tools=TOOLS)

p.line(data.index.to_series(), data['glucose'],
       line_color="gray", line_width=1, legend="glucose")

low_box = BoxAnnotation(plot=p, top=80, fill_alpha=0.1, fill_color='red')
mid_box = BoxAnnotation(plot=p, bottom=80, top=180, fill_alpha=0.1, fill_color='green')
high_box = BoxAnnotation(plot=p, bottom=180, fill_alpha=0.1, fill_color='red')

p.renderers.extend([low_box, mid_box, high_box])

p.title = "Glucose Range"
p.xgrid[0].grid_line_color=None
p.ygrid[0].grid_line_alpha=0.5
p.xaxis.axis_label = 'Time'
p.yaxis.axis_label = 'Value'

show(p)
```

If we now adjust the the ``top`` of the low_box like this:

```python
from bokeh.io import push_notebook
low_box.set(top=100)
push_notebook() 
```

nothing happens. If we also set a new title it does update:

```python
from bokeh.io import push_notebook
p.title = 'Update test'
low_box.set(top=100)
push_notebook()
```

**Comment by bryevdv** [comment]
Here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/annotations/box_annotation.coffee#L14

There probably needs to be added

```
@listenTo(@model, 'change', @render)
```
and 
```
@listenTo(@model, 'change', @plot_view.request_render)
```
in the branches respectively. Can you try that/make a small PR?

ping @canavandl can you remind the rationale for `data_update` event?

**Comment by bryevdv** [comment]
I imagine it is so that all the box parameters can be updated using the `update` function, causing the box to be re-drawn, potentially without a BB change event. But that doesn't mean we shouldn't respond to actual BB change events when they do happen. 

Can't a silent update just be:
```
@set({left: left, right: right, top: top, bottom: bottom}, {silent: @get('silent_update')})
if @get('silent_update')
  @trigger('data_update')
```
and then also add
```
@listenTo(@model, 'change', () -> @model.trigger('data_update')
```
so that changes trigger a re-draw (by going through the internal `data_update` event path)

**Comment by philippjfr** [comment]
Thanks for figuring this one and the other one (#3993) out so quickly.

>Can you try that/make a small PR?

I'm a bit busy atm but should be able to submit a PR for this and the ``Span`` issue over the weekend.

**Comment by canavandl** [comment]
@bryevdv - I think the intention of the `data_update` event was so that the box_select_tool could update it's overlay attr (a box annotation model), then trigger a rerender of the view. I'm almost done w/ the box_annotation refactor and am working on this issue - i'll ping @philippjfr on the PR for review
