### ISSUE TITLE
Hover tool

### ISSUE THREAD

**Issue by Vutsuak16** [bokeh/bokeh#4041]
Does the hover tool works for line and scatter plots?
It doesn't seem to work in my case.

**Comment by bryevdv** [comment]
Hi @Vutsuak16, please take general support questions to the public mailing list:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/plots/plot.coffee#L639-L644

In addition to having a larger audience of people who can potentially answer, it also helps keep the issue tracker manageable, but reserving it for bug reports and feature requests. 

However, I can say that the hover tool does work with lines. I'd suggest sharing some code and version information when you post to the mailing list, otherwise it is much more difficult to offer concrete advice.

**Comment by Vutsuak16** [comment]
Thanks Bryan I will reply back later with my code. Thanks a lot :)
