### ISSUE TITLE
Generalize the configuration of axes

### ISSUE THREAD

**Issue by soupault** [bokeh/bokeh#4042]
One of my most common use cases in the visualization is to present _an overview of some system's dynamics, plotting ~10-20 signals on the vstacked graphs (from 2 to 5 signals per plot)_. Usually I use as many extra axes as possible in order to keep the good perception ratio (up to 4 y-axes and 2 x-axes at the same time). For sure, there are other use cases, but, please, consider this as an example.

I was using `matplotlib` a lot, but it has some issues with sharing the plots for further analysis. At the same time, `bokeh` has very nice capabilities to zoom the shared plots, easily select data / data intervals, etc.

To facilitate the visual style configuration (labels, limits, scales, colors, markers, etc) I usually use either nested dict or DataFrame. This helps to keep the same visual style / axes config across the plots. This is the way it works for me:

- Create `signal -> visual style` mapping;
- Allocate grid of plots (`axis[0], axis_right[0], axis_right2[0], axis_upper[0], ..., axis[n], ...`);
- Create `subplot, axis -> signal` mapping;
- Iterate over mapping to plot the signals and apply the visual styles. 

Looking at `bokeh`, I see that the regular plotting pipeline slightly differs, but still is more or less the same. The only thing that is really missing (at least as I'm aware of), is the possibility to iterate over base x/y-axes and extra x/y-axes in the same way.

Here is the example how it works:
```
import numpy as np
import pandas as pd
 
from bokeh.io import gridplot, output_file, show
from bokeh.plotting import figure
from bokeh.models import LinearAxis, Range1d
 
output_file("test.html")
 
df = pd.DataFrame([])
df['time'] = [1, 2, 3, 4, 5]
df['temperature'] = [30, 31, 32.5, 33, 31]
df['humidity'] = [10, 30, 50, 20, 40]
df['sensor'] = [0.22, 0.12, 0.14, 0.08, 0.04]
 
s1 = figure(title=None)
s1.x_range = Range1d(start=-1, end=6)
s1.y_range = Range1d(start=25, end=35)
 
s1.extra_y_ranges = {
    'humidity': Range1d(start=0, end=50),
    'sensor': Range1d(start=0, end=0.25)
}
 
s1.line(x=df['time'], y=df['temperature'],
        color='orange', legend='temperature')
s1.line(x=df['time'], y=df['humidity'], y_range_name="humidity",
        color="blue", alpha=0.5, legend='humidity')
s1.line(x=df['time'], y=df['sensor'], y_range_name="sensor",
        color="red", legend='sensory data')
 
s1.xaxis.axis_label = 'Reference Units'
s1.yaxis.axis_label = 'Temperature'
s1.add_layout(LinearAxis(y_range_name='humidity', axis_label='Humidity'), 'left')
s1.add_layout(LinearAxis(y_range_name='sensor', axis_label='Sensor'), 'right')
 
show(s1)
```

And example how I'd appreciate it to work (just to show the concept):
```
import numpy as np
import pandas as pd
 
from bokeh.io import gridplot, output_file, show
from bokeh.plotting import figure
from bokeh.models import LinearAxis, Range1d
 
output_file("test.html")
 
df = pd.DataFrame([])
df['time'] = [1, 2, 3, 4, 5]
df['temperature'] = [30, 31, 32.5, 33, 31]
df['humidity'] = [10, 30, 50, 20, 40]
df['sensor'] = [0.22, 0.12, 0.14, 0.08, 0.04]

s1 = figure(title=None)

s1.x_ranges = {
    'reference units': Range1d(start=-1, end=6),
}
s1.y_ranges = {
    'temperature': Range1d(start=0, end=50),
    'humidity': Range1d(start=0, end=50),
    'sensor': Range1d(start=0, end=0.25)
}
 
s1.line(x=df['time'], y=df['temperature'], 
        x_range_name='reference_units', y_range_name="temperature",
        color='orange', legend='temperature')
s1.line(x=df['time'], y=df['humidity'], 
        x_range_name='reference_units', y_range_name="humidity",
        color="blue", alpha=0.5, legend='humidity')
s1.line(x=df['time'], y=df['sensor'], 
        x_range_name='reference_units', y_range_name="sensor",
        color="red", legend='sensory data')
 
s1.add_layout_x(LinearAxis(x_range_name='reference units', axis_label='Reference Units'), 'bottom')
s1.add_layout_y(LinearAxis(y_range_name='temperature', axis_label='Temperature'), 'left')
s1.add_layout_y(LinearAxis(y_range_name='humidity', axis_label='Humidity'), 'left')
s1.add_layout_y(LinearAxis(y_range_name='sensor', axis_label='Sensor'), 'right')
 
show(s1)
```

**Comment by bryevdv** [comment]
Hi @soupault Thanks for the detailed information. From your quick comment on gitter I thought you were proposing a new feature, but seeing the details, I think this is actually just a support issue. IIUC you just don't want the default axes created, because you want to control things more closely? If so there's two approaches I could suggest:
* definitely possible using `bokeh.models` since you have to put everything together from scratch. But there are some utils in `bokeh.plotting.helpers` that you could use to help put things together 
* staying with `bokeh.plotting.figure`, you can just instruct `figure` not to create any default axes, by passing, e.g., `x_axis_location=None` as an argument)

(side note: looking at the docs, I think this option is not documented well enough, if you'd be interested in contributing a PR to document it better, please let us know)

I'm going to close this issue, just because we are reserving the GH issue tracker for bug reports and feature requests to have some hope of keeping it manageable. If the above info is not enough to get started (or does not work) I'd encourage you to take the discussion to the public mailing list at:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

In addition to devs, there's a larger community of users who can potentially help there.
