### ISSUE TITLE
Multi-file bokeh server example

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#4050]
I would like to create a multi-page Bokeh web application. After reading the following documents on using a directory structure I still have trouble setting things up.

http://bokeh.pydata.org/en/0.11.0/docs/user_guide/server.html#directory-format

I suspect that many of my questions could be resolved if I were to refer to a small example that used multiple .py files.  I checked the source repository and, while there were several excellent server examples I couldn't find on that used multiple files.  Is this application in scope?

**Comment by canavandl** [comment]
ping @havocp

**Comment by havocp** [comment]
There are various options here.

 * If you just want multiple python files for code organization, that should be possible inside a bokeh app directory (there was a fix for this from @bryevdv I think that I saw go by a while ago)
 * If you want multiple URLs, the only "native" way to do that with bokeh server is to have multiple applications. That is, `bokeh serve foo.py bar.py baz` where baz is a directory containing `main.py`, will give you the URLs `/foo`, `/bar`, and `/baz`
 * If you find yourself wanting a routes file and a template language and stuff, then you probably can't use `bokeh serve` (though #3962 might be nice in the future). There are two options:
   - write your own script with its own `main()` and create a `Server` manually, with `extra_patterns` (I think we have an example somewhere? I think @brendancol has done this some. Essentially the idea here is to use Tornado directly as a web framework. One advantage is you have only a single process with this.)
   - write a web app with a general web framework (doesn't have to be Tornado) and then embed Bokeh plots into that framework from a separate `bokeh serve` process (as in @birdsarah 's "happiness" demo). The main advantage here is that you have the full power of whatever web framework you want to use.

The idea of `bokeh serve` is to enable people to make these simple data-centric web apps without messing with routes, javascript, http, templates, html, css, etc., so as soon as you WANT to mess with those things in any significant way, you're probably outside the `bokeh serve` sweet spot and want to think about embedding Bokeh instead of making a "pure" Bokeh app.

#3962 however would be nice to see, and we should probably also have easy ways to include a notebook widget or other "switch between multiple displays" functionality within a Bokeh app (without having to do multiple apps). Putting an index page rather than a 404 at `/` would be nice too so multiple-app servers will have a page that shows the list of apps. If you could use either of those features would be great to see them happen.

**Comment by mrocklin** [comment]
In case two, with `bokeh serve foo.py bar.py baz/` what are the requirements/relationship between `foo.py` and `baz/`?  In what ways is `baz` special?

**Comment by bryevdv** [comment]
@havocp I definitely don't want to run down rabbit holes around multiple endpoints and routing, but have recently concluded that it's probably OK to expose some hooks and let people dig their own rabbit holes. E.g, letting an app correspond to a *pattern* of endpoints, and supplying the actual matching endpoint as an argument to the app, so it can switch or route or do whatever.

**Comment by bryevdv** [comment]
@mrocklin neither is special, there is no relationship between them at all. It starts two apps, one at `/foo` and another at `/bar`, that's it. The "directory" format is merely a convenience, if your app has multiple python modules or data files or whatever, it's convenient to keep them all under one directory.

**Comment by mrocklin** [comment]
Ah, so to make sure I have things straight: 

*  There are two ways to specify an app, a single script or a directory with main.  
*  Bokeh serve can serve several apps simultaneously, of either kind.
*  Different routes are entirely separated and are served by different processes.

I'm happy going to a more typical web application when things become more complex.  I'd still like to see how far I can get within Bokeh's rather convenient setup.  I'll probably switch to managing the bokeh `Server` manually when (if?) I ever get there.  Pointing to an example like this would be valuable to me.

**Comment by bryevdv** [comment]
2 out of 3 :) 

> Different routes are entirely separated and are served by different processes.

They are served by the same asynchronous tornado serve.

Can you let us know what could be added here to make things more clear:

http://bokeh.pydata.org/en/latest/docs/user_guide/server.html#directory-format

Also, we will definitely be adding a "custom jinja" template option to apps, which I hope will let them easily satisfy basically at least an single page app without having to resort to a separate web app server to embed in

**Comment by mrocklin** [comment]
I think what happened with the docpage is that I was looking for the answer to "How do I run multiple scripts from the same server?" and I mistakenly associated my question to the `directory-format` section, which led me to wrong conclusions.  Perhaps if there were a clearer section of how to run `bokeh serve` with multiple scripts I would have avoided the `directory-format` red herring.  If such a section exists, then perhaps add a warning note redirecting to it "**Looking for how to serve multiple scripts?  Check out LINK instead*"

**Comment by bryevdv** [comment]
@mrocklin that's a great idea I will add a section for that

**Comment by havocp** [comment]
@bryevdv definitely think a way to get the query parameters and/or route from SessionContext would be useful. I know there was discussion of it on some issue ( @birdsarah wanted it at one point building the happiness demo too iirc). One tricky thing is that the route/parameters probably don't make much sense except on the page load that _creates_ the session, that is, they would be ignored if you open the same session a second time. But in our default/typical setup, every tab has its own session so it's fine. I dunno. Anyway basically yes I agree with you, guess I'm hijacking this issue ;-) it should be its own issue/discussion.

**Comment by bryevdv** [comment]
Closing as inactive discussion.

**Comment by rchossein** [comment]
Is this still the case that when you have a multi-file (multi-dashboard) bokeh server, you can't have custom html/css files for each dashboard? (we need a separate URL for each dashboard)

**Comment by bryevdv** [comment]
@rchossein that's never been the case. This issue was about making single conceptual bokeh apps that had multiple pages allowing for communication of state between the different pages. If you want to just point Bokeh server at 5 different directory-style apps, each with their own template, that's always been possible.
