### ISSUE TITLE
--host whitelist doesn't trust 127.0.0.1 by default

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#4051]
It looks like by default bokeh server doesn't trust requests sent to `127.0.0.1`, nor the address of localhost on local network interfaces.  Perhaps it should?  This had me confused for a while.

```
mrocklin@workstation:~/workspace/distributed$ bokeh serve distributed/diagnostics/bokeh/status.py
DEBUG:bokeh.server.tornado:Allowed Host headers: ['localhost:5006']
DEBUG:bokeh.server.tornado:These host origins can connect to the websocket: ['localhost:5006']
INFO:bokeh.server.tornado:Rejected connection from host '192.168.1.141:5006' because it is not in the --host whitelist
INFO:bokeh.server.tornado:Rejected connection from host '127.0.0.1:5006' because it is not in the --host whitelist
```

**Comment by mrocklin** [comment]
Alternatively is there a way to ignore the whitelist?

**Comment by mrocklin** [comment]
Perhaps we could accept something like `--host *` or `--host *:80`

This is similar to what you see in other services like the Jupyter notebook.

**Comment by bryevdv** [comment]
Here is where the whitelist is checked, if you'd like to try and make a small PR to focus discussion: 

https://github.com/bokeh/bokeh/blob/master/bokeh/server/tornado.py#L29-L42

**Comment by koganm** [comment]
Hi guys,

Is this working on 0.12.0dev8? Looks like I am still getting this issue:

$ bokeh serve --host *:5006 --port 5006
2016-05-09 14:15:23,552 Starting Bokeh server version 0.12.0dev8
2016-05-09 14:15:23,591 Starting Bokeh server on port 5006 with applications at paths ['/']
2016-05-09 14:15:23,592 Staring Bokeh server with process id: 9328
2016-05-09 14:16:10,081 Rejected connection from host 'localhost:5006' because it is not in the --host whitelist

I'm trying to do a pull_session from a separate bokeh app to connect to the server on url http://localhost:5006. Everything works correctly when i just do bokeh serve and test locally. I could be messing something else up. 

Thanks

**Comment by bryevdv** [comment]
the host whitelist only compares the HTML `HOST` header, it should not have a port. In fact `--host:<port>` should probably raise an error.  Can you try it without the port? I don't know offhand when `dev8` came out so I can't say for sure, and I am on my phone so it is hard to check.

**Comment by koganm** [comment]
Hi Bryan,

Thanks for your reply - that makes sense, I tried without the port and it looked good.

I ended up resolving my own issue since I realized I was passing the url param in push_session in the wrong order (it was being passed in as the session id) so when I used the explicit 'url' param keyword in invoking that function, everything ran smoothly and I was able to connect to my remote server.
