### ISSUE TITLE
bokeh.charts.Histogram incorrect output

### ISSUE THREAD

**Issue by pauljmorrison** [bokeh/bokeh#4066]
I'm running into an issue where `bokeh.charts.Histogram` is showing incorrect output.

This issue is discussed here:

https://groups.google.com/a/continuum.io/d/topic/bokeh/JTsX9Hx-1sY/discussion

This impacts Bokeh 0.11.1.

Here's a minimum working example that should illustrate the problem:

```
import numpy as np
from bokeh.plotting import figure, show
from bokeh.io import hplot, output_file
from bokeh.charts import Histogram

from bokeh import __version__
print(__version__)

output_file('mwe.html')
plot_list = []

a_var = np.random.normal(500,6,500)

pcharts = Histogram(a_var)
plot_list.append(pcharts)

hist, edges = np.histogram(a_var)
ppltting = figure()
ppltting.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:])
plot_list.append(ppltting)

show(hplot(*plot_list))                       
```

Here is the output. 
![mwe](https://cloud.githubusercontent.com/assets/11462206/14027997/c79b7726-f1d0-11e5-84c0-8d279211e1f5.png)

Thanks!

**Comment by bryevdv** [comment]
@pauljmorrison I believe this has been fixed. This is what I get with your code on current master:
<img width="644" alt="screen shot 2016-03-24 at 2 24 38 pm" src="https://cloud.githubusercontent.com/assets/1078448/14028766/3ac05136-f1cc-11e5-9f3c-ed232575208a.png">

If you have the ability to build and test from a GH checkout it would be nice to verify from you that it is working as expected. Otherwise, I hope to have an easily installable dev build out fairly soon. 

I'm going to close this as `invalid` for now simply because I believe it has already been fixed, but certainly if it is discovered that is not the case it is appropriate to re-open.
