### ISSUE TITLE
Open bokeh plots in new tab

### ISSUE THREAD

**Issue by Safariba** [bokeh/bokeh#4079]
Is there any possibility that we open a bokeh plot inside the notebook and then after clicking on it we have it in a new tab?

**Comment by canavandl** [comment]
That may be difficult because clicking on the plot manages a bunch of other interactions (selecting/panning/zooming). If you're hoping to interactively create a plot in the notebook then view it in a browser tab, you might try running the `output_file` method inside of the notebook. Then every time you call `show(plot)`, a new browser tab w/ your plot will open.

**Comment by bryevdv** [comment]
Apart from the technical problem that clicking already has meaning in many context, there's also no reason you can't do both `output_file` (to get a new tab) and `output_notebook` (to get things inline). They are not mutually exclusive. I think this is covered by existing functionality (which makes me hesitant to want to add any additional functionality that would have to be maintained) so I am closing this.
