### ISSUE TITLE
Specifying external URLs for resources

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#4127]
There are many instances where external (JS, CSS) resources are necessary or useful:

* `GMapPlot` needs to load Google APIs
* Custom User Models that wrap 3rd party JS libraries
* Katex+Fonts for LaTeX label support

Currently, the only options are to include explicit code in the BokehJS model to load external resources (as `GMapPlot` does) or to embed Bokeh models in a custom template that provides the necessary script or other tags. The proposal is to make it possible for Bokeh models to specify any required external resources in a self-contained manner. 

The primary tasks seem to be:

* [ ] Add hooks or properties to `Resources` to support specifying external JS, CSS links, etc
* [ ] Modify current templates and embedding to use these resources correctly
* [ ] Create a convention for `Model` to specify any necessary resources declaratively (e.g., perhaps a `__resources__ = [...]` class variable or similar) 
* [ ] Automatically collect any `Model` specific resources to be reported by `Resources` so that they are used during document serialization

Possible considerations: 
* need to load resources before "realizing" a document 
* de-dupe if a resource shows up twice?

@bokeh/dev comments? Is this the right breakdown of work?

**Comment by canavandl** [comment]
My comments from the mailing list:

In order to add LaTeX support (via KaTex) I have to vendor in some font files. While doing this I ran into two issues:

First:

My plan is to add the katex library as a dependency in packages.json, so that'll be pulled in by npm and isn't a problem. I also need to add some style resources (a couple of less files and font files), that get bundled into the bokeh css resources. My initial plan was to add a bokehjs/src/vendor/katex-0.5.1 directory containing the less and font files, then add a src/less/katex.less file that imports the styles and base64 encodes the fonts (similar to how we handle the font-awesome resources).

The problem is that a couple of the necessary font files are over the IE8-safe limit (32kb) when encoded, so gulp-less won't encode them without adding an { ieCompat: false } flag.

I don't have enough domain expertise to know if/how bad this is. Potential solutions are:

Add the { ieCompat: false } flag
Manually base64 encode the fonts and add them to the src/less/katex.less file
Other
Second:

Font files are huge and KaTeX includes a ton of fonts! (https://github.com/Khan/KaTeX/blob/master/static/fonts.less) Assuming we don't want to add 500kb of fonts to our css resources, I commented out all but the four that seem most important and use a single format (assuming that that woff has the same browser support as bokeh per https://github.com/Khan/KaTeX/wiki/Font-Options), but bokeh.css and bokeh.min.css still increase by 180kb (roughly doubling in size). Again, I'm unsure how bad this is. Potential solutions are:

Just go with it, as-is
use another latex implementation (on quick glance, using MathJax would have the same font problems)
don't support latex
load fonts from CDN and don't bundle them?
create another css resource: fonts.css
don't include fonts at all (the latex layout still works, but the font styling doesn't happen)
Other

**Comment by canavandl** [comment]
With my LaTex experience described above, I have a couple of additional considering regarding handling external resources.

* LaTeX supports a ton of fonts (and fonts are relatively big files, ~ 20-40kb). Depending on what LaTeX expression a user hopes to create, different fonts will need to be loaded (bold/italic/script/math characters/etc.). The proposed __resources__ `Model` property would have to be configurable in order to be able to download only the desired fonts.
* Another reason for configurable __resources__ would be to support loading fonts from a local `statics` directory on a deployed Bokeh plot. 
* Appropriately warning or trying to handle situations where resources are set to "inline" but the document uses external resources (presumably for off-line mode use).
