### ISSUE TITLE
Documents on Bokeh server not displaying

### ISSUE THREAD

**Issue by Sugandha94Agrawal** [bokeh/bokeh#4211]
I am running bokeh-server on windows and when I go to localhost:5006 on my browser, it shows the bokeh page with my document, but when I click on the document, nothing is displayed. I am unable to figure out why the plot isn't showing up. For example I am running the sliders.py example (I modified it since the curdoc().add_root line keeps giving me the error that the Document object has no attribute 'add_root')

Any help in running the examples on github using bokeh-server on windows would be extremely helpful!
![untitled](https://cloud.githubusercontent.com/assets/8963421/14723950/830461be-07e1-11e6-9980-1b25413bc8d3.png)

**Comment by bryevdv** [comment]
Hi @Sugandha94Agrawal The screen shot you are showing is from the **old** `bokeh-serve` version of the Bokeh server that existed before the `0.11` release. The old version of the Bokeh server has been completely removed and is no longer supported. The new server is vastly more stable, performant, better documented, and simpler to use. The reason you are getting the error for `"Document object has no attribute 'add_root'"` is because that is a new feature that only exists for Bokeh versions  `0.11` and newer. It will not work on older versions of Bokeh because is did not exist on older versions of Bokeh. 

You have two options:

* Upgrade to Bokeh `0.11` or newer and use the new server, described in much detail here:

http://bokeh.pydata.org/en/latest/docs/user_guide/server.html

* If you cannot upgrade, you should consult examples and documentation specific to your version (instead of looking at `master` which is the newest code). For example, the examples for Bokeh `0.10` can be seen at:

https://github.com/bokeh/bokeh/tree/0.10.0/examples/

**Comment by Sugandha94Agrawal** [comment]
Thank you so much first of all for your prompt reply. I opted to use bokeh-server (the old version) instead of the new server that uses the bokeh serve command because even after fixing the path variable, I just can't get bokeh serve to run on windows command prompt. The newer version as per my understanding doesn't use redis (which doesn't have support for windows) so that shouldn't be a problem. 

I get this error when I run bokeh serve: "bokeh" is not recognized as an internal or external command, operable program or batch file. Is this an issue typically associated with windows compatibility or is it likely that I have some error in my configuration?

**Comment by bryevdv** [comment]
@Sugandha94Agrawal I believe that issue is fixed in `master` and will be present in the `0.12` release. In the mean time, you can always also run the new bokeh server like this, on any platform:
```
$ python -m bokeh serve
2016-04-21 16:35:40,561 Starting Bokeh server version 0.12.0dev8-48-g4ec5380
2016-04-21 16:35:40,564 Starting Bokeh server on port 5006 with applications at paths ['/']
2016-04-21 16:35:40,565 Starting Bokeh server with process id: 11784
```

**Comment by Sugandha94Agrawal** [comment]
Thank you so much, that worked!
