### ISSUE TITLE
HoverTool stops working on heat map after refresh/update

### ISSUE THREAD

**Issue by wcopeland** [bokeh/bokeh#4233]
When initially drawing a heat map with the hover tool enabled, everything seems fine. If heat map data are refreshed/updated, the hover tool does not display information for the majority (if not all) data points.

Sample code:
http://pastebin.com/g2Vn4dag

This conversation has been brought up a few times, most recently on the mailing list:
https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/Fnu8DjokgDg

**Comment by bryevdv** [comment]
I only now just noticed this example uses categorical (factor range) coordinates for the heatmap. I have a suspicion (unconfirmed) that this may have something to do with the problem. There are some issues around how we handle categorical coordinates that could use attention at some point. 

As a workaround, can you try replacing the entire heatmap with a new plot every selection update?

**Comment by bryevdv** [comment]
The code above did not work because it was not run as a bokeh server application. `on_change` with real python callbacks only functions on the bokeh server (the bokeh server is what actually runs the python code, a standalone Bokeh document with `show` is just HTML and your browser has no way to do anything with python code). With usual `curdoc().add_root(...)` instead of `show` the updates work fine:

<img width="570" alt="screen shot 2018-06-23 at 06 50 19" src="https://user-images.githubusercontent.com/1078448/41810358-f24dde10-76b1-11e8-963e-0ce9b15c267f.png">
