### ISSUE TITLE
Seabourn plots with Bokeh server

### ISSUE THREAD

**Issue by carlskii** [bokeh/bokeh#4257]
Not an issue, but a question. I have already have several seabourn plots that currently create PNG images. Does Bokeh support a easy way to shift these plots across to an HTML templated views ?

**Comment by bryevdv** [comment]
Hi @carlskii For support questions please use the public mailing list:

https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh

So that we can keep the issue tracker reserved for feature requests and bug reports. 

I will say there is an MPL compat layer that affords some measure of capability for converting things, out of the box, but it is not comprehensive, and not all MPL (and hence Seaborn) plots will work.
