### ISSUE TITLE
bokeh timeseries stepbuilder missing x axis

### ISSUE THREAD

**Issue by sambhav8** [bokeh/bokeh#4268]
https://groups.google.com/a/continuum.io/forum/#!mydiscussions/bokeh/JNzZ1yYLIsg

**Comment by birdsarah** [comment]
@sambhav8, it would be really great if you could make this a full issue by adding all the relevant information here in github: 

* Description of expected behavior and the observed behavior
* Self-contained example code that generates the issue (if possible)
* Stack traceback and/or browser developer tools console output

Someone's going to have to do this eventually for this issue to move forward and it would be great if you could help out by doing this.

**Comment by sambhav8** [comment]
i tried to use bokeh for the timeseries example timeseries.py 0.11.1  i can see axis Date with linebuilder but with step builder it missing


Code to reproduce is example/timeseries.py 

Attach error and expected behaviour 
![missinglabel on x axis](https://cloud.githubusercontent.com/assets/19164230/15004179/62b333b8-11e6-11e6-92fe-bd8c32474dfd.png)

**Comment by bryevdv** [comment]
Should be re-opened in https://github.com/bokeh/bkcharts if still relevant.
