### ISSUE TITLE
Add vanilla Tornado routes to server

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#4270]
My application manages global state from which all sessions draw.  Under normal operation this state feeds various ColumnDataSources that feed various plots on the screen.  However, I would also like to provide static JSON views of this data. 
-  navitgate to hostname:5006/myroute/ , get fancy visual plot
-  navigate to hostname:5006/myroute.json , get data dump of state at that time

I suspect that I can do this now by registering a tornado.WebApplication in with the tornado event loop in a `server_lifecycle.py` file and by listening on a separate port.  Ideally I'd like to host on the same port though.  I'm also curious if there is (or should be) a way to do this that intentionally plays nicely with the Bokeh server.

**Comment by bryevdv** [comment]
Just to be clear, there is only one set of data to display to any client that navigates to `hostname:5006/myroute.json` ? Not different data per-session?

**Comment by mrocklin** [comment]
Correct.

**Comment by bryevdv** [comment]
The story for using `Server` programmatically has improved since this issue, and you can definitely add routes that way by passing in `extra_patterns` to `BokehTornado`. I think for this more advanced use case that is the correct approach, rather than adding complexity to the simpler `bokeh serve` code path.
