### ISSUE TITLE
Hook for callback upon document init

### ISSUE THREAD

**Issue by ghost** [bokeh/bokeh#4272]
For any kind of plotting that shall start without having the user doing anything in the first place, like an animation of data, or periodic update from (time based) calculations, _without_ having to use a bokeh server, a hook that triggers a callback at page load would be needed.

**Comment by bryevdv** [comment]
So I'm aout to look at a callback when the Bokeh document is initialized. Will that suffice? I'm not sure page load is workable, generally, given context like embedded server apps, and the jupyter notebook.

**Comment by artur-scholz** [comment]
Yes, that will be sufficient. Just so that the callback gets called after the first time the plot has been rendered.

**Comment by bryevdv** [comment]
The recent events work by @jlstevens should have played most of the foundation for this.

**Comment by jakirkham** [comment]
Just curious, what is the current status on this?

**Comment by foobarbecue** [comment]
Any good workarounds?

**Comment by chesucr** [comment]
The best approach I found is [here](https://stackoverflow.com/questions/42794556/how-to-check-if-my-bokeh-server-application-is-loaded-on-electron). Take a look to the "Update 3" to check if all the elements are already rendered. It is not a good workaround, but.... let me now if you get any better solution

**Comment by foobarbecue** [comment]
I ended up using a MutationObserver similar to this: https://stackoverflow.com/a/38882022/616730

**Comment by bryevdv** [comment]
As requested in the linked issue above, it would be extremely useful if there is a standard way for a doc init callback to access HTML query parameters for purposes of customization.

**Comment by chesucr** [comment]
Triggering a callback when the page is loaded would be useful in many cases. Let me explain another use case where calling a function would be convenient as well.

When the user interacts with some controls and buttons and some rendering is made. If this process take a while because many computations are needed, then the whole interaction may be slowed down.

This can be improved if we show the data gradually or partially to the user. If we have a form with serveral plots hidden (under tabs for instance). We can compute the visible data first, and then, when it is loaded an rendered, the data used in the background plots can be updated. The user will not notice it if we are lucky.

More information about the use case I am facing is [here](https://stackoverflow.com/questions/55501408/how-to-call-a-js-function-or-python-method-when-a-glyph-is-completely-rendered).

I discarded DataShared because I need to use selection tools and interact with the samples individually.

Let me know if you find out a better solution apart from improving the algorythm efficiency.

**Comment by p-himik** [comment]
A more clean workaround:
```python
class IdleDocObserver(Model):
    on_idle = Instance(Callback)

    # language=TypeScript
    __implementation__ = """\
        import {View} from "core/view"
        import {Model} from "model"
        import * as p from "core/properties"

        export class IdleDocObserverView extends View {}

        export namespace IdleDocObserver {
            export type Attrs = p.AttrsOf<Props>
            export type Props = Model.Props & {on_idle: p.Property<any>}
        }

        export interface IdleDocObserver extends IdleDocObserver.Attrs {}

        export class IdleDocObserver extends Model {
            static init_IdleDocObserver(): void {
                this.prototype.default_view = IdleDocObserverView
                this.define<IdleDocObserver.Props>({on_idle: [p.Any]})
            }
            
            _doc_attached(): void {
                super._doc_attached()
                const execute = () => this.on_idle!.execute(this)
                if (this.document!.is_idle)
                    execute();
                else
                    this.document!.idle.connect(execute);
            }
        }
    """
```

If you use `show` or `save`, pass an instance of `IdleDocObserver` along with all your roots as a list as the first argument. If you use `bokeh serve`, just add the observer to the document as a root.
A usage example can be seen here: https://stackoverflow.com/a/61285022/564509

**Comment by wolfiex** [comment]
Linked example does not run.

**Comment by bryevdv** [comment]
Noting that `DocumentReady` was added in 2.2 but currently only for Bokeh server apps, e.g. 
```
curdoc().on_event(DocumentReady, load_weather)
```
We would like to add for `CustomJS` but this will be tricky due to implicit documents, might require requiring explicit document manipulation (to have a target doc to call `js_on_event` on)

cc @philippjfr was there a different issue for the current work you just added?

**Comment by bsdis** [comment]
Is there any way this can be hacked or worked around somehow?
I really need to have bokeh customJS insert callback functions into window object on init. Its very problematic that this init feature is not available. I would be happy to spend time helping to develop a functionality like that if necessary. Where would I get started?

**Comment by jundl77** [comment]
So one thing I found that is a workaround for me at least is checking if html elements have loaded yet in JS, and creating a callback to that check again and again until the elements I need have loaded. Here is the gist of the idea:

It's incorrect javascript syntax, but you get the idea (I don't work in js much anymore and I was too lazy to look it up).

```js
function allElementsLoaded()
{
    for elemId in getElements()
    {
        let elem = document.getElementById(elemId);
        if (elem == null)
        {
            return false;
        }
    }

    return true;
}

function onDocumentLoaded() {
    if (!allElementsLoaded())
    {
        setTimeout(function(){ onDocumentLoaded(); }, 3000);
        return;
    }

    // do magic
}
```

In any case, this works for my use-case, hopefully, this is viable for others as well.

**Comment by sg-s** [comment]
> curdoc().on_event(DocumentReady, ...)

@bryevdv can you expand on this? what's the second argument here? i want to run some JS code when the page loads (i want to use localstorage)

**Comment by bryevdv** [comment]
> what's the second argument here

A Python function. Currently only Python callbacks (in a Bokeh server app) are supported for document init events. A CustomJS option has yet to be implemented.

**Comment by sg-s** [comment]
@bryevdv thank you! how does the python callback set something that triggers a `CustomJS`? i'm happy with a clunky solution if it works!
