### ISSUE TITLE
Testing infrastructure bug/wish list

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#4285]
NOTE: this will be updated and refined gradually.
- [x] don't display unrelated (especially `DEBUG`) logs in the main log
- [ ] unify test output from different test runners (if or as much as possible) (especially `gulp test`)
- [x] restore original logic around javascript errors/warning/messages
- [ ] images in examples' report should have fixed size (as originally), so that we don't have to wait for all images to load to be able to use the report. Otherwise the page jumps and one can't focus on an example.
- [ ] integration tests should be aware of failures in javascript and not proceed unless bokehjs and plots loaded properly
- [x] some examples' images are no different, yet there is full black diff image generated and uploaded
- [x] LABEL WHICH IMAGE IS EXPECTED, AND WHICH IS ACTUAL

**Comment by birdsarah** [comment]
If you'd like me to not comment on this issue, while your thinking evolves, then do let me know.

> integration tests should be aware of failures in javascript and not proceed unless bokehjs and plots loaded properly

+1 - Do we need a BokehJS hook for this?

In addition, the selenium tests currently fail in a completely unintelligible way if the python part of the test fails. Need to handle this much more gracefully.

> some examples' images are no different, yet there is full black diff image generated and uploaded

Yes - I've noticed this too - not sure what the cause is - maybe there's a diff that we can't see - that doesn't make any sense though.

> images in examples' report should have fixed size (as originally), so that we don't have to wait for all images to load to be able to use the report. Otherwise the page jumps and one can't focus on an example.

I understand your reasoning, but I really didn't like the squashed images. I found it made it harder to parse the examples report as a whole. Happy to think of compromise solutions - like fixed height boxes with scrolling images inside them. Having a grid to of fixed-height boxes to make the whole report more compact.

I would also add (as you said, there's probably more in my brain, but I just thought of this):
* I find it confusing that in the examples report, the actual/test-generated image is on the left and the expected/reference is on the right. For whatever reason I intuitively expected actual images to be on the right. In the integration screenshot tests, the images are on the right. We should be consistent, and maybe we should add extra information in both reports so its super clear (especially if you're new) which is the reference image and which is the test image.

**Comment by birdsarah** [comment]
> don't display unrelated (especially DEBUG) logs in the main log

I did a quick thing on this in my latest PR - e.g. https://travis-ci.org/bokeh/bokeh/jobs/128202446; but I still get a bunch of boto stuff at the end.

**Comment by birdsarah** [comment]
Things that could be better from a recent test run.

The core bug here was that plots not wrapped in a layout were not rendering - there was a javascript console error "Error: unsatisfiable constraint".

Travis job: https://travis-ci.org/bokeh/bokeh/builds/129342869

Problems:
* examples tests passed
* examples test report (if you look at it is unhelpful) - the blank space on the left which is actually displaying a failure doesn't really indicate that and wierdly the image link on the right is wrong.
* the selenium tests did fail but in a crazy unhelpful way - https://travis-ci.org/bokeh/bokeh/jobs/129342874

This relates to one of the items on the list "integration tests should be aware of failures in javascript and not proceed unless bokehjs and plots loaded properly".

This issue seems to provide hints on how to capture browser logs: https://github.com/SeleniumHQ/selenium/issues/1161

**Comment by birdsarah** [comment]
Edited above, I guess S3 was having a moment when I chose to look at the examples test report - looks fine now.

**Comment by birdsarah** [comment]
Edited above again - there is a problem with py2 in this case (not sure if it's general yet)

**Comment by birdsarah** [comment]
OK. Found it.

```python
log = selenium.get_log('browser')
errors = [l for l in log if l['level'] == 'SEVERE']
```
in my broken example returns:

```
[{'timestamp': 1462999443317, 'type': '', 'message': 'Error: unsatisfiable constraint', 'level': 'SEVERE'}]
```

So testing that the length of `errors` is 0 is straight forward. The challenge is that in the current set-up we'd have to do that on every test after the lines.

```python
    save(plot)
    selenium.get(output_file_url)
```

Now those 3 lines are required boiler plate for any selenium test so I don't think it's crazy to have a third. We could definitely factor it out to something easy like:

```python
    save(plot)
    selenium.get(output_file_url)
    assert_no_console_errors(selenium)
```
Of course any time something changes we'd need to check that - for example - what if there was a console error that only happened on resize or when you hit a button.

This may be down to the tester.

Although worth noting that doing `get_log` empties the log. So we would be able to detect new errors.

Finally, I haven't read this yet, but it looked interesting (it may be a different kind of logging): http://elementalselenium.com/tips/54-logging

**Comment by birdsarah** [comment]
So the difference in helpfulness is such an improvement when you test for the error, so I've added in a first crude cut to my latest PR (https://github.com/bokeh/bokeh/pull/4308/commits/f1eeddc6d05d27449e60047bd642009f28310679).

I'm sure there's many future improvements on this, but its a step in the right direction.

**Comment by birdsarah** [comment]
Wierdly the above commit seems to still not be doing the right thing on saucelabs - although I can see that it is getting the log and the log has the correct information in it. Still getting the epic INTERNAL ERROR messages.

**Comment by birdsarah** [comment]
Just sticking this here for now.

We need some kind of check list for manual tests:
* we don't have selenium tests for webgl so need to test manually - including interactions e.g. #4633 regression
* we don't have any tests for zooming the webpage in and out e.g. #4611 regression

**Comment by mattpap** [comment]
I opened new issues for the remaining tasks and closing this one. Since introduction of projects on github we should use those instead of meta issues that pretty much can't ever be closed.
