### ISSUE TITLE
AjaxDataSource Data Initialization

### ISSUE THREAD

**Issue by bthcode** [bokeh/bokeh#4298]
Using AjaxDataSource from an INLINE page fails to plot without a workaround to initialize the source.data member.

The issue was identified and diagnosed here:

http://stackoverflow.com/questions/37083998/flask-bokeh-ajaxdatasource

Bokeh version:

~ > bokeh info
Python version      :  2.7.11 |Anaconda 2.4.1 (x86_64)| (default, Dec  6 2015, 18:57:58) 
IPython version     :  4.2.0
Bokeh version       :  0.11.1

Code example with workaround labeled:

```
from flask import Flask, jsonify
from jinja2 import Template
import math

from bokeh.plotting import figure
from bokeh.models import AjaxDataSource
from bokeh.embed import components
from bokeh.resources import INLINE
from bokeh.util.string import encode_utf8


app = Flask(__name__)

x, y = 0, 0

@app.route("/data", methods=['POST'])
def get_x():
    global x, y
    x = x + 0.1
    y = math.sin(x)
    return jsonify(x=[x], y=[y])

template = Template('''<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Streaming Example</title>
        {{ js_resources }}
        {{ css_resources }}
    </head>
    <body>
    {{ plot_div }}
    {{ plot_script }}
    </body>
</html>
''')

@app.route("/")
def simple():
    streaming=True
    source = AjaxDataSource(data_url="http://localhost:5000/data",
                            polling_interval=1000, mode='append')

    # This line is the workaround - if you comment it out, the plot will not render
    source.data = dict(x=[], y=[])

    fig = figure(title="Streaming Example")
    fig.line( 'x', 'y', source=source)

    js_resources = INLINE.render_js()
    css_resources = INLINE.render_css()

    script, div = components(fig, INLINE)

    html = template.render(
        plot_script=script,
        plot_div=div,
        js_resources=js_resources,
        css_resources=css_resources
    )

    return encode_utf8(html)

app.run(debug=True)
```

**Comment by bryevdv** [comment]
Thanks for the detailed report @flailingsquirrel

**Comment by bryevdv** [comment]
The error is raised here:

https://github.com/bokeh/bokeh/blob/9491d517a84edc528ac84970cb338b5c24ac1d66/bokehjs/src/coffee/core/properties.coffee#L57-L62

Basically the assumptions are too strict for `AjaxDataSource`. I see two possible solutions:

* Add a type check there, and don't throw the exception if the source is a `RemoteDataSource`
* instead of reaching in and looking at `source.data` directly, implement a protocol, so that sources can define their own levels of "strictness" (this just means add some methods to ask data sources about whether they have a given column or not, instead of looking by hand directly at `data`)
