### ISSUE TITLE
Speeding up tests for the next release without annoying people!

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4327]
So, recently we've undone some of the changes that I made to the testing infrastructure which allowed tests to run much quicker. Specifically we have turned off:
1. Fail on first fail (so if a test fails the whole run bails)
2. Test parallelization

There were good reasons for doing this:
1. The parallelization caused test failures to be much more obtuse and seemed to make the test suite more flaky. 
2. The fail on first fail could be frustrating if you had a lot of errors, because you'd see one fail, fix it, but then you'd find the next one, then fix it, etc. Because people don't seem to run the examples tests locally, this appeared to be a problem here, but it is on the examples tests where bailing early had the opportunity to save us the most time.

I agree that we need a better permanent solution so that we can get the benefits of parallelization and failing fast without it just bringing new & different problems.

However, I see a big release coming up that I'm guessing is going to have a lot of small fixes when it comes to freeze time. 

So, my suggestion is to implement something like the `[ci disable examples]`. By default, tests will be run parallelized and failing fast, but you can opt-out by running `[ci run carefully]` or something and it will run all the tests and not parallelize them. 

I hope this means that we can reduce bottlenecks at release time. If it doesn't work, it would be a simple hotfix to switch back to the system we have now, so I'm hoping it's a low-risk experiment.

Also, I don't see any point in doing the opposite of opt-in with `[ci run fast]`. I think most people wouldn't remember so we wouldn't see the savings in travis time which is the point of this suggestion.

**Comment by birdsarah** [comment]
ping @mattpap @bryevdv

**Comment by mattpap** [comment]
I'm going to close this issue as wontfix, because failing on first error is not acceptable for any serious development (tests results are not only there to gives green/not green indication, but also tell exactly what's wrong) and it's unlikely we will find time to implement parallelization of tests, which also is unlikely to give any speedup on travis ci. Note that `[ci disable examples]` was implemented at some point. There is also a long list of more fine grained issues tackling the problem of long test run times.
