### ISSUE TITLE
Ugly border in GMapPlot?

### ISSUE THREAD

**Issue by ResidentMario** [bokeh/bokeh#4350]
I'm not sure if this is "working as intended", but I daresay from my perspective as a user it isn't. When you create a GMapPlot it creates, along with the map, a huge ugly border, as shown:

![screen shot 2016-05-21 at 11 59 57 pm](https://cloud.githubusercontent.com/assets/3466341/15452257/27aa1b78-1fb6-11e6-8b48-0ef256d82a9a.png)

I can't seem to find a way of removing it (aside from maybe messing with the underlying JS after the file has been generated?).

Is this a library error?

Here's a MWE:

    from bokeh.io import output_file, show
    from bokeh.models import GMapPlot, GMapOptions, DataRange1d, ColumnDataSource, Circle, PanTool, HoverTool

    map_options = GMapOptions(lat=40.7484, lng=-73.9857, map_type = "terrain", zoom=10)

    GMap = GMapPlot(x_range = DataRange1d(), y_range = DataRange1d(), map_options = map_options , title = "Eneumerate",
            plot_width=800, plot_height=300)

[See also this Stack Overflow question](http://stackoverflow.com/questions/37370404/how-do-i-remove-the-border-from-a-bokeh-gmap-plot).

**Comment by birdsarah** [comment]
Thanks for the report. I am seeing that here too: http://bokeh.pydata.org/en/latest/docs/user_guide/geo.html

But I swear it didn't used to be like that, I wonder if something's changed in the GoogleMaps API.

Thanks for the report.

**Comment by birdsarah** [comment]
I am also seeing it here: http://nbviewer.jupyter.org/github/bokeh/bokeh-notebooks/blob/master/tutorial/00%20-%20intro.ipynb and I know for sure it wasn't there when I gave this tutorial a few weeks ago.

Must be a GMaps change. Thanks again for the report.

**Comment by bryevdv** [comment]
I am fairly certain this was caused by the mismatched defaults, and fixed by #4434 just merged. Some of the default that needed fixing up were specifically these. Here is a screenshot from current master:

<img width="896" alt="screen shot 2016-06-07 at 5 15 02 pm" src="https://cloud.githubusercontent.com/assets/1078448/15876546/8be1d96c-2cd3-11e6-869d-8f786f557392.png">

Closing for now. @ResidentMario we should have a dev build you can easily try out in a day or two. Please re-open if you see the issue persist then.
