### ISSUE TITLE
API issue: title_standoff, title_padding, title_offset

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4381]
We used to have a property `title_standoff`, we now have a property `title_padding`. 

They don't do the same thing. In the case of an above title (which used to be the only option), `title_standoff` would move the title away from the plot, but `title_padding` moves the title along the axis of the text (to the right in the case of an above title).

To add to the confusion that's not what I would expect padding to do. I would expect it to pad all sides of a title. I would call it title_offset, especially as it's called x_offset and y_offset in the Label implementation.

I do think for title we need something like plot's min_border. where you can set it all or pick a side to add border/padding to.

ping @canavandl

**Comment by canavandl** [comment]
To summarize what you're proposing:
* renaming `title_padding` to `title_offset` for consistency (which sounds like a good idea)
* implementing `title_offset` (to set on all dimensions) and `title_padding_left/right/top/bottom` instead of the 1D "right-hand" offset currently in master.

And as an API/orientation question: Would setting title_offset_left on a "left" title moving the text to the right or up? (i.e. is the direction of the padding in terms of the text orientation or the frame?)

It might also be necessary to decide on an API for text annotation bounding box padding (#4416).

ping @bryevdv because I know you had opinions on this title_offset API

**Comment by birdsarah** [comment]
The main thing I'd like to see changed is `title_padding` -> `title_offset`. Padding has a specific meaning in CSS-land and it's the space on every edge between a boxes edge and the contents. Even if CSS land is not a world many of our users come from, we use padding in the CSS-way in Legend https://github.com/bokeh/bokeh/blob/master/bokeh/models/annotations.py#L106. 

```python
    legend_padding = Int(10, help="""
    Amount of padding around the contents of the legend.
    """)
```

I'm going to put in a PR for this rename so it makes it into 0.12 and we don't give ourselves extra future work.

**Comment by birdsarah** [comment]
I realized when I was doing the PR that `Title.title_offset` was redundant and it should just be `Title.offset` (I also fixed up title_align in the same manner).
