### ISSUE TITLE
Axis label size change does not trigger a re-alignment

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4394]
When @bryevdv was testing the new layout, he was surprised that when he interacted with a grid of plots and zoomed to the point where axis labels were longer than before that other plots didn't update their alignment.

Should we implement / provide an option for that - I worry that it might decrease performance.

**Comment by bryevdv** [comment]
@mattpap did you say there was a one line change needed to fix this and a few other layout-not-updating issues? If so we need to get that in soon.

**Comment by mattpap** [comment]
@bryevdv, I think (though I'm not 100% sure) that this case is not handled by the "fix" you mentioned, and even if it was handled, it would likely degrade performance beyond any usability. I would like to fix this, but it requires some broader thought. In particular, this requires an invalidation algorithm. Having one would solve any performance issues, because we wouldn't need to update everything every time.
