### ISSUE TITLE
Trigger event when bokeh finishes rendering

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4401]
At the moment, we do a rather un-graceful trigger of a window resize at three delayed time intervals to try and get the page in the right shape when it a responsive layout loads.

However, if your browser took more than 100ms to load the event you're going to end up with some ugly looking layout. e.g. when loading: https://cdn.rawgit.com/birdsarah/bokeh-miscellany/master/new_layout_tests/words_and_plots.html

![bad layout](https://almarklein.stackstorage.com/index.php/apps/files_sharing/ajax/publicpreview.php?x=2168&y=540&a=true&file=bokeh012.png&t=rK47xyhiMC8U9oY&scalingup=0)

(thanks @almarklein)

Having an event at the end of bokeh render has been requested in the past: #2150 but with the responsive layout I'm putting this into the bug category as anything that will get us to a better way to trigger resize after render would be good. 

The current resize code is here:

https://github.com/bokeh/bokeh/blob/birdsarah/4164_rework_layout/bokehjs/src/coffee/models/layouts/layout_dom.coffee#L35-L39

```coffeescript
    if @model._is_root is true
      resize = () -> $(window).trigger('resize')
      _.delay(resize, 50)
      _.delay(resize, 100)
      _.delay(resize, 200)
```

**Comment by brianray** [comment]
https://github.com/bokeh/bokeh/pull/4171 may also be solved at the same time

**Comment by clairetang6** [comment]
Hi @birdsarah, I don't think I'll have the time to finish this right now, but I'll try to write down what I've learned here so that whoever is going to pick this up will know what I know! 

I haven't figured out the best way to know when the rendering has finished (and really only have vague ideas now), but during my investigation, I think I found a bug that is causing incorrect layouts when resize is called (the first time and some other times depending on the requested width and height). Below, I'm showing what happens when you first take out the current resize code (see bottom of first post in this issue) and then trigger resizes in chrome's responsive mode. The first resize to 887 width has the last toolbar in the wrong position. The second resize to 987 is also incorrect. Then resizing back to 887 fixes the layout. Finally, going back to 987 breaks the layout again.

![commit1](https://cloud.githubusercontent.com/assets/4241244/15870962/24f41c8c-2ca7-11e6-91a8-30e5e570acd2.gif)

This seems to be caused by a leftover suggested value for the width of the cartesian frames in the plots. When the resize event is triggered by the document resizing, the listeners for views that are laid out respond by suggesting new values to the solver for their widths and heights. When the plot canvas responds, it updates the width and height for its canvas view, but it  _doesn't__ update the width and height for the cartesian frame. 

To fix this bug, I put a call to plot canvas's `update_constraints` inside the `resize` method, which gives the following result where all resizes result in correct layouts. 

![commit2](https://cloud.githubusercontent.com/assets/4241244/15871521/e8a9800c-2ca9-11e6-89a7-a09823f0d132.gif)

These two states can be reproduced by my branch, clairetang6/4401_responsive_layout_bug, which contains two commits. The first one produces the first gif. In it, I comment out the current resize code and added console.log statements that were useful in finding the bug. I also changed the `build_views` function to take its caller as a parameter so that I could log out which model was calling it. The second commit fixes the bug** and produces the second gif. 
 
When this bug fixed, the problem of determining when rendering is finished to trigger the resize becomes more straightforward. The majority of the time I was working on this, I was trying to understand the constraints and why a resize might result in an incorrect layout. But if a resize instead was always correct, then it should be the case that only one resize is necessary when the rendering is done.  

**not super well tested but works in this case and seems to be reasonable.

**Comment by almarklein** [comment]
@bryevdv @birdsarah 

I've proceeded with this, working on a branch off master with @clairetang6 's fix-commit cherry-picked in. I'm trying to see how all render requests and resize events propagate through the various components. 

I commented all `_.delay(resize, x)`, which means there is no call to `plotcanvas.resize()` (or any other resize related code). When I then call `document.resize()` directly, I need to call it *three times* for the plots to appear correctly. When I resize the window after that, the plots are responsive, but doing a manual call to `document.resize()` will still trigger small changes.

It thus appears that as it is now, the layout system is iterative, and needs 3 passes initially and 2 passes for every change in size. Is this expected? If not, any ideas why this could be? I'll dig deeper in the meantime.
