### ISSUE TITLE
Non-equal proportion split in layouts

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4407]
Currently when you're working in a responsive mode (such as width_ar or box) and you add multiple plots to, for example, a row those plots will be given equal amounts of space. So two plots will take up 50% each of the row, three plots will take up 33% of the row each.

But you may want to have a row with three plots with at 25-25-50% split. There's currently no way to build that with a responsive layout.

**Comment by bryevdv** [comment]
@birdsarah if you can make a quick high level outline of the work required I can look into implementing this.

**Comment by birdsarah** [comment]
I have no clue what it would take, other than that we'll need to modify `box.coffee` - which I would suggest we don't do until we've added tests for it. ping @havocp.

**Comment by havocp** [comment]
One possibility (maybe you did this already?) is to add a flag to any widget which opts it out of the equal-sizedness:
https://github.com/bokeh/bokeh/blob/03911a49d2edddf114abf7353bab7e4108167fc2/bokehjs/src/coffee/models/layouts/box.coffee#L126-L134

This flag lets you have for example some sort of control on the left that you want to use minimal space, then a plot on the right that uses most available space, for example.

If desired, rather than a single boolean you could use a "stretch" of 0.0 to 1.0, like Phosphor. stretch of 0.0 means if there's excess space, this item takes none of it; 1.0 means it takes its full share. The exact formula is in the phosphor boxlayout and would have to be converted into constraints I suppose. I am not a giant fan of "stretch" because it doesn't seem to map to any visual concept such as alignment, it's sort of an arbitrary number to mess with but it isn't usually "what I mean." When do you set "stretch=0.7"? It isn't intuitive to me, it's kind of a weird arbitrary number.

An alternative idea that may be nicer... For ratios like 25/25/50, one could nest a row in a row (not sure if this already works but perhaps it should if not):
   `row(row("25", "25"), "50")`

Ideally what happens if you nest a row in a row like that is that the outer axes in the nested row are aligned properly, so if you have:
  `column(row(row("25", "25"), "50"), row("A", "B"))`

Then the left axis of the first "25" should be aligned with the left axis of "A", and the right axis of the second "25" should be aligned with the right axis of "A"

I think this might Just Work or close to it and solve the main use-cases, but I don't know.

**Comment by sashabaranov** [comment]
This is very much needed to enable color bars with vertical titles: https://stackoverflow.com/questions/46841919/bokeh-colorbar-vertical-title-to-right-of-colorbar

**Comment by bryevdv** [comment]
@sashabaranov Please see https://github.com/bokeh/bokeh/pull/7708 It's likely that kind of template based approach is going to be the recommended path for anything that requires more control.

**Comment by bryevdv** [comment]
@mattpap is there a good example of this from #8085?

**Comment by mattpap** [comment]
There are a few tests in https://github.com/bokeh/bokeh/pull/8085/files#diff-92d703ed75c577b9af901bbfa11e5690R155.

**Comment by bryevdv** [comment]
Noting that we need examples/docs to follow on

**Comment by jundl77** [comment]
What is the state of this? It seems it exists, right? But I couldn't find any examples. Could you briefly comment how to use this?

**Comment by jnettels** [comment]
I started looking through https://github.com/bokeh/bokeh/pull/8085/commits to see if I found any hint about how to use this, but there are just too many commits... was this ever documented?

**Comment by bryevdv** [comment]
#8085 was a giant piece of work, unfortunately coming back to polish/finish up some things fell through the cracks. 

@jnettels I've opened #10401 to document these better, if you by chance could drop a small complete example in a comment there it would be extremely appreciated. 

cc @mattpap in case you can add any helpful comments for @jundl77
