### ISSUE TITLE
Add support Title/Label bounding box padding

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#4416]
Add support for text annotation bounding box padding (Title and Label). Currently the bounding box dimensions are roughly the text dimensions plus a small, hardcoded padding. It would be nice to have this padding be configurable in the plot.min_border/min_border_\* manner (i.e. a `text_padding` attr that sets all dimensions and `text_padding_left/right/top_bottom`

**Comment by anthonydouc** [comment]
Interested in addressing this issue - with perhaps a little guidance if possible. 

As far as I can tell, the currently available settings are limited to title.offset which effectively sets a left and right margin to the title. The vertical margin remains fixed at a value of 5 (https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/annotations/title.ts#L22).

I would think one of the following approaches is reasonable:
- add a single new parameter to specify the top/bottom margin and retaining the current title.offset
- add different top/bottom/left/right margins and an overall title padding (and remove title.offset)

Keen to understand which would be preferred (or an alternative if I have missed the mark there).

**Comment by p-himik** [comment]
I would not remove `offset` - the name is already used in other similar places.
I would just extend `offset` to support 1/2/3/4-value tuples (although, this is a backwards incompatible change if we decide to treat a single value as a 4-value tuple where all values are the same, to be consistent with CSS) and _maybe_ add `offset_{left|right|top|bottom}` properties.
"_Maybe_" because I'm not sure how often they will be used. And if it's not that often, having 4 extra properties (many more if there are other models where such change needs to be made) just for some rare use-case seems wasteful.

**Comment by anthonydouc** [comment]
Currently offset value shifts the title in a direction parallel to the plot. I would of thought a reasonable compromise is to have `offset_vertical` and `offset_horiztonal`? That just extends the current functionality to shift the title perpendicular to the plot. It also overcomes and avoids defining four additional parameters or a four tuple. If that sounds good i will implement the change soon.
