### ISSUE TITLE
Change in handling of `alpha=None`

### ISSUE THREAD

**Issue by dhirschfeld** [bokeh/bokeh#4421]
Demo notebook @ https://anaconda.org/dhirschfeld/alphabug/notebook

Previously `alpha=None` implied `alpha=1`. With the latest git master this has changed to imply `alpha=0`.

i think I prefer the original definition, not the least because it means I don't have to change my code :stuck_out_tongue:

**Comment by bryevdv** [comment]
@dhirschfeld This one is hard. I am loathe to break anyone's code, but if this was ever the case (I believe  you when you say it was) then it was completely unintentional. It's also completely inconsistent with, e.g. the more explicit `line_color=None` and `line_alpha=None` that we have demonstrated probably since `0.3` or so. The `color` and `alpha` kwargs are just shorthands to set line and fill props at the same time, so I don't think we can justify not bringing things into alignment. Out of curiosity, since `alpha=1` is already the default, whats the use-case for setting `alpha=None`? Since it is the default, my hope and expectation is that that difference will not affect many users.

**Comment by dhirschfeld** [comment]
Having a consistent api is certainly a good enough reason to change the behaviour.

I had some generic argument handling code that passed through `kwargs.get('alpha')` which I've now changed to `kwargs.get('alpha', 1)` so I'm happy for this to be closed. It's probably worth mentioning in the release notes though as it *is* a change in behaviour...

**Comment by bryevdv** [comment]
@dhirschfeld absolutely :) there will be extensive release notes on this release, mostly deprecations that still work, but a few actual changes
