### ISSUE TITLE
Strange behaviour and some other issues with ggplot

### ISSUE THREAD

**Issue by giancds** [bokeh/bokeh#4424]
Hey folks, I'm using Bokeh together with ggplot. 

I'm seeing some strange behaviors when converting the ggplot to Bokeh. I'm trying to make some scatterplots using my custom dataset: [dataset.csv.zip](https://github.com/bokeh/bokeh/files/295767/dataset.csv.zip)

If I use only ggplot, the code work as a charm:

```python
import pandas as pd
from ggplot import *
df = pd.read_csv("dataset.csv")
g = ggplot(df, aes("wVerb", "wNoun", "col2")) + geom_point()
print(g)
```
![correct](https://cloud.githubusercontent.com/assets/3305726/15747290/fb3e792e-28d1-11e6-8aeb-c2f559f64a63.png)

If I try to render the same figure using Bokeh, the data gets messed up:

```python
import pandas as pd
from ggplot import *
from bokeh import mpl
from bokeh.plotting import show, output_file
df = pd.read_csv("dataset.csv")
g = ggplot(df, aes("wVerb", "wNoun", color="col2")) + geom_point()
g.make()
output_file("mpl_subplot.html", title="mpl_subplot.py example")
show(mpl.to_bokeh())
```
![wrong](https://cloud.githubusercontent.com/assets/3305726/15747494/e80d0af4-28d2-11e6-9e21-13f9b13ad698.png)

If I try to call Bokeh to render the same plot but without colors, I get a gray figure: 
```python
import pandas as pd
from ggplot import *
from bokeh import mpl
from bokeh.plotting import show, output_file
df = pd.read_csv("dataset.csv")
g = ggplot(df, aes("wVerb", "wNoun")) + geom_point()
g.make()
output_file("mpl_subplot.html", title="mpl_subplot.py example")
show(mpl.to_bokeh())
```
![wrong1](https://cloud.githubusercontent.com/assets/3305726/15747347/3c419be0-28d2-11e6-8161-0b7964395ab0.png)

By the way, if I call `g.draw()` as per the Bokeh examples, I get an error `AttributeError: 'ggplot' object has no attribute 'draw'`. To make it work I had to use `g.make()`

If I try to pass the ggplot object to `mpl.to_bokeh()`, I get an error `AttributeError: 'ggplot' object has no attribute 'canvas'`.

Hope this does turn into a big issue as I would not like to stop using Bokeh.

Thanks for your time,
Gian

**Comment by bryevdv** [comment]
HI Gian, as the issue template stated, we need information about versions, in general. In this case even more than normal is needed, since there are lots of moving parts: Bokeh, ggplot, matplotlib, ... Any of those might be the problem, or have changed, so it is impossible to speculate or try to reproduce what you are seeing without more information.

**Comment by giancds** [comment]
Hi @bryevdv,

My bad on that. The versions I'm currently using are:

Bokeh = 0.11.1
ggplot = 0.9.3
matplotlib = 1.5.1

All of them seems to be the latest stable version.

Gian

**Comment by bryevdv** [comment]
Regarding `make` vs `draw` the version of ggplot I have installed (0.6.5) has `draw`, and raises an `AttributeError` on `make` so it seems ggplot has made breaking API changes at some point, which is not  anything we have control over. 

When I try your code with `geom_line` I do see output, but with `geom_point`, I see no output in the plot, but the console provides the error:
```
bryan@0199-bryanv  /tmp $ BOKEH_RESOURCES=inline python foo.py
ERROR:/Users/bryan/work/bokeh/bokeh/core/validation/check.py:W-1001 (NO_DATA_RENDERERS): Plot has no data renderers: Plot, ViewModel:Plot, ref _id: a50ee319-5efc-4006-848f-f6ecc0eacfab
``` 
This is indicative to me that the third-party library we rely on, `mplexporter` either has a problem or has gotten out of sync with MPL. This is not too surprising since `mplexporter` relies on private MPL APIs and is definitely not complete. For true MPL compatibility we are waiting on [MEP 25](https://github.com/matplotlib/matplotlib/wiki/MEP25) to provide a complete and stable JSON serialization for MPL. Until that stability exists, we can't really devote our very limited resources. Unfortunately any timeline for MEP 25 is also out of our hands. I can't speculate on when it might be available, that is entirely up to the MPL team.  We have always been very clear in our documentation that MPL compat is an incomplete work in progress: http://bokeh.pydata.org/en/latest/docs/user_guide/compat.html

In the mean time, there are two options:

* if you have enough familiarity with MPL, you can offer to try and fix up things up to handle `geom_point`, and we would certainly try to help as best we could. We always welcome new contributors, and certainly this kind of contribution would be very appreciated by many people.

* use native Bokeh APIs directly. Bokeh can render a very wide variety of plots and charts and offers complete control over visual aesthetics and presentation. 

Otherwise, I hope you will check back in the future after MEP 25 is available for us to provide true and complete MPL compatibility.

**Comment by bryevdv** [comment]
Fixed, with caveats about marker types
