### ISSUE TITLE
Multiple renders ocurring

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4439]
May be related to #4170.

May be related to performance #4395 

May be relevant to #4401 

Bokeh is rendering more times than it needs to seemingly all the time - on selection, on resize, on slider change. You always get two renders.

Also, wierdly as soon as you select / click on the slider (before moving it) you get two renders.

**Comment by clairetang6** [comment]
After lots of digging, I found a bug in the throttling of ```request_render```. This bug is causing other problems such as the double render after selection in [this issue](https://github.com/bokeh/bokeh/issues/4170). 

As discussed in [these comments](https://github.com/bokeh/bokeh/pull/4171#issuecomment-209959527), ```request_render``` should request for a render so that multiple calls to ```request_render``` in one throttling interval only causes one render. However, when there are multiple calls to ```request_render```, there is a bug that is causing the second ```request_render``` to set up a second render even if the first one is pending.
