### ISSUE TITLE
Cannot make html of bokeh successfully

### ISSUE THREAD

**Issue by yingwei13mei** [bokeh/bokeh#4465]
When I have downloaded  the bokeh zip package，and excute “make html” command to generate the html doc in directory “...\bokeh-master\sphinx", it pops up those messages: "Running Sphinx v1.3.1

Extension error:
Could not import extension bokeh.sphinxext.bokeh_jinja (exception: No module named 'bokeh.sphinxext.bokeh_jinja')"
I cannot find the missing module "sphinxext.bokeh_jinja', and I have installed all the required pkg from anaconda. why I still miss "sphinxext.bokeh_jinja" ?   And where could I get this module to fix this problem?

**Comment by bryevdv** [comment]
Hi, are you referring to the tarball that on GitHub? Those are source tarballs, and do not contain a "built" version of BokehJS. They are generally useless, and we never advise anyone to use them for any reason, but unfortunately GitHub creates them automatically on tagging. I would remove them entirely, if I could. 

You need to actually install Bokeh in one of the standard ways. There are extensive installation instructions (including for "dev" builds) here:

http://bokeh.pydata.org/en/latest/docs/installation.html

Or if you want to run from "bleeding edge" repo master, there are develop setup instructions here:

http://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html

There are also additional dependencies needed to build the docs, since some of the examples make use of other specialized python libraries that the core library does not require. There are instructions for building the documentation here:

http://bokeh.pydata.org/en/latest/docs/dev_guide/documentation.html

We try to keep our issue tracker reserved for bugs and feature requests. In the future, please check out the docs site first, and also direct general support questions such as this to the public mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
