### ISSUE TITLE
To-Do: Add Migration Label

### ISSUE THREAD

**Issue by HuntJSparra** [bokeh/bokeh#4519]
Add a migration label for issues, discussions, and bugs regarding migrating between versions.

**Comment by bryevdv** [comment]
@bokeh/dev the idea here is to make a new label that can be applied to merged PRs to note that the change might need migration information in the release notes. I'd propose to make a new plain label, fairly bright red that just says `MIGRATION` in all caps. The rationale is that when merging a PR, people probably have in mind what migration related information is there, but that there is not really a place to record this at that time since we construct release notes at release time. This is to help facilitate gathering the migration information for the release notes.

**Comment by bryevdv** [comment]
@bokeh/dev OK I have gone ahead and added the label, and updated BEP-1. Right now it is very difficult to keep track of things that might need to be mentioned in a migration guide, and we have to do something, so let's try this. Please, going forward, if a PR has implications that should be mentioned, add the `MIGRATION` label when merging.

**Comment by bryevdv** [comment]
For 1.0 planning we can figure out what kinds of things can be automated (deprecations, etc.) but some thing will always need manual curation (e.g. no interfaces changed, but some new best practice is available)
