### ISSUE TITLE
models/legends example broken

### ISSUE THREAD

**Issue by HuntJSparra** [bokeh/bokeh#4561]
![unknown](https://cloud.githubusercontent.com/assets/19802403/16160887/363fa13c-3490-11e6-9219-3d245c2b2261.png)

No errors in console.

**Comment by birdsarah** [comment]
More information about this error was available here: https://github.com/bokeh/bokeh/issues/2006#issuecomment-226185464 I'm posting here:

This has improved with #4343 but is not fixed in some general case:

* two right axes now works
* three right axes now works

* four right axes doesn't work and fails as above

<img width="777" alt="screen shot 2016-06-15 at 6 17 56 am" src="https://cloud.githubusercontent.com/assets/1796208/16081139/0f16816e-32c1-11e6-8b50-7f06dbbfbfb8.png">


* you seem to be able to have unlimited left axes with up to three right axes

<img width="777" alt="screen shot 2016-06-15 at 6 17 27 am" src="https://cloud.githubusercontent.com/assets/1796208/16081099/db8cfd64-32c0-11e6-95a2-006d36e8ca0b.png">

Similarly (but slightly different) you can only have three things on top axis. Two axes + title or three axes.

<img width="658" alt="screen shot 2016-06-15 at 6 21 24 am" src="https://cloud.githubusercontent.com/assets/1796208/16081198/67e650f8-32c1-11e6-80f5-cb1c3a22b354.png">

 A total of four and things break.

<img width="681" alt="screen shot 2016-06-15 at 6 22 00 am" src="https://cloud.githubusercontent.com/assets/1796208/16081224/800f8212-32c1-11e6-8ff3-20a45880a501.png">

Code for these tests is here: https://github.com/birdsarah/bokeh-miscellany/blob/master/new_layout_tests/test_titles.py

I'm going to close this because we've fixed the original bug. There's clearly an issue still left here, but it seems like a corner case and I'd rather wait to see if it affects someone before sticking in backlog.

**Comment by birdsarah** [comment]
The reason this has surfaced now is because everything got a default title.

This quick fix to the example should be to set `title=None`. And then the main fix is solving this in the general case.

**Comment by HuntJSparra** [comment]
Can confirm title=None does fix it.

**Comment by mattpap** [comment]
This was fixed in one of recent layout PRs.
