### ISSUE TITLE
Initialization problem on `scale_width` plots

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4608]
On grid / complex layouts with `scale_width`. The initialization isn't getting quite enough of a kick and the axes are getting slightly buried:

<img width="675" alt="screen shot 2016-06-21 at 12 23 57 am" src="https://cloud.githubusercontent.com/assets/1796208/16221305/e776a4a6-3746-11e6-88ba-5467e8960c96.png">

**Comment by birdsarah** [comment]
Adding in an extra resize first time round fixes this, but I'd like to fix this in a way that doesn't cause a big slow down on plot initialization for everyone.

**Comment by mattpap** [comment]
@bryevdv, where does this come from? I recall seeing it, but I can't find it now.

**Comment by bryevdv** [comment]
@mattpap I'm not sure what you are referring to by "this"?

**Comment by mattpap** [comment]
I mean this screenshot. It seems familiar, but I'm not sure if this was removed at some point.

**Comment by bryevdv** [comment]
I think that was used to demo color palettes in the docs at one point but was removed foreign too slow, and replaced with new sphinx extensions for palettes

**Comment by bryevdv** [comment]
@mattpap it was a `bokeh.charts.Area` example that's why it's gone (though it was also slow):

https://github.com/bokeh/bokeh/blob/0.12.0/examples/charts/file/palettes.py

**Comment by mattpap** [comment]
OK, thanks. I forgot about charts at this point.

**Comment by bryevdv** [comment]
fixed by #8085 Initial broser output for anscombe with stretch_both and scale_width:

<img width="1266" alt="screen shot 2019-01-30 at 21 30 13" src="https://user-images.githubusercontent.com/1078448/52032585-7077a000-24d6-11e9-81d0-9454158c34db.png">
<img width="1266" alt="screen shot 2019-01-30 at 21 30 53" src="https://user-images.githubusercontent.com/1078448/52032586-7077a000-24d6-11e9-9922-c6e314af2369.png">
