### ISSUE TITLE
Stop doing two calls to _resize on every resize

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#4643]
After the new initialization work, we ended up with two calls to _resize in the document's resize method.

This is obviously inefficient.

If I'm remembering correctly from conversations with @almarklein, we all agree that it's necessary on initialization to do two passes - because things need to be rendered once and then resized according to their size.

I was hoping subsequent double calls wouldn't be necessary, but it seemed to be necessary on windows.

**Comment by almarklein** [comment]
I think there are actually two issues:
* The "resize-pass" (without rendering) needs to run twice, because different apply constraints that are inter-dependent. Maybe if the constraints are applied in a more "coherent" manner, one pass could be sufficient? It would need some refactoring though. At the time I played a bit with changing the order by which different resize handlers were called, without success. This seems to be  a problem on all OS's on the first draw, and on every draw in Windows.
* For the layout to work correctly, at least one render pass is necessary. Apparently there are constraints set or bounds defined or something during the rendering. I think that ideally this would not be the case.

**Comment by bryevdv** [comment]
@mattpap is this still the case?

**Comment by mattpap** [comment]
Yes.

**Comment by bryevdv** [comment]
@mattpap If I understood some of your other comments, this is in fact unavoidable? Can this be closed as `invalid`?

**Comment by mattpap** [comment]
As long we support widgets that can size themselves, and that's the default for widgets, then two passes (or more like 1.5 passes) are necessary. The thing is that widgets have to render themselves and set base dimensions, before layout can proceed to size dimensions that aren't governed by widgets. For example, sliders size dimension orthogonal to their orientation, so layout can size the dimension along orientation. So, it is unavoidable, but can be greatly improved. Alternatively we can make widgets first class citizens of layout, which previously was infeasible, but with recent changes to widgets it isn't anymore.
