### ISSUE TITLE
BokehJS Charts not respecting plot size

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#4689]
@mattpap perhaps it's a usage error, but I could not get any `Bokeh.Charts.pie` or `Bokeh.charts.bar` to respect any of the following: `width`, `height`, `plot_width`, `plot_heigh`. Also tried passing to `gridplot` or showing just single charts.

**Comment by mattpap** [comment]
It used to work. Most likely broken around merge of layout PRs.

**Comment by mattpap** [comment]
> width, height, plot_width, plot_height

It would be nice to get explanation why we arrived with both sets in the low-level API.

**Comment by mattpap** [comment]
This doesn't work because charts API uses `plot_*` properties, which are used only at plot initialization time. They are listened to through `change` event and even trigger re-render, just don't do anything at this point. Perhaps they should be be removed altogether (see comment at `plot.coffee:114`). Right now resizing a plot via any other API (including server) won't work. I presume using `width` and `height` directly would work though.

**Comment by bryevdv** [comment]
> It would be nice to get explanation why we arrived with both sets in the low-level API. 

 I assumed `width` and `height` were your choices for the JS API, even though they are different than the actual properties. 

I'd probably prefer `plot_width`, etc throughout even tho they are a bit verbose.

**Comment by birdsarah** [comment]
I never quite got to grips with the difference between `plot_width` and `width` during the layout work. I just tried to honor whatever was there and new things I stuck to `width`.

I'm -1 on `plot_width`, I think `plot.width` or `figure.width` or `chart.width` is easier to understand than `plot.plot_width`, `figure.plot_width` etc.

My gut feeling is that I'd be in favor of removing the occasional references to `plot_width` as part of an API clean-up leading into 1.0.

**Comment by mattpap** [comment]
This was fixed somewhere around the new layout.
