### ISSUE TITLE
Incorrect rendering of embedded Bokeh server app in 0.12

### ISSUE THREAD

**Issue by beenje** [bokeh/bokeh#4693]
Bokeh server app doesn't render properly when embedded in a Flask app with autoload_server (Bokeh 0.12.0).

This can be reproduced with the following example:

app.py:
```
from flask import Flask, render_template
from bokeh.embed import autoload_server

app = Flask(__name__)

@app.route('/')
def index():
    script = autoload_server(model=None, app_path="/sliders")
    return render_template('index.html', bokeh_script=script)
```

templates/index.html:
```
<!DOCTYPE html>
<html lang="en">

  <body>
    <h1>Bokeh app test</h1>
    <div class="bokeh_app">
      {{ bokeh_script|safe }}
    </div>
  </body>

</html>
```

Run this flask app and the sliders.py example from bokeh/examples/app:
`bokeh serve --host localhost:5000 --host localhost:5006 sliders.py`

This gives the following with Bokeh 0.12.0:
![bokeh_0 12 0](https://cloud.githubusercontent.com/assets/425499/16456761/935c6766-3e08-11e6-944c-125a15b2084e.png)

Somethink like that (Bokeh 0.11.1) is expected:
![bokeh_0 11 1](https://cloud.githubusercontent.com/assets/425499/16456776/a62459f8-3e08-11e6-9ae4-a24c8b23d1c9.png)

**Comment by canavandl** [comment]
I'm unable to reproduce. I get:

<img width="747" alt="screen shot 2016-06-29 at 4 03 51 pm" src="https://cloud.githubusercontent.com/assets/2198981/16468766/1663972e-3e13-11e6-8ff7-43e8a30a4bfe.png">

It looks like your bokeh.min.css and bokeh-widgets.min.css aren't loading. Can you check your browser console (network tab) and see if/why they're 404-ing? Do you have any network reason why those resources wouldn't load?

**Comment by beenje** [comment]
I don't see any error:
![flask_bokeh](https://cloud.githubusercontent.com/assets/425499/16471531/9a80a458-3e5d-11e6-9fd1-027de6129598.png)

I pushed the example I used on github: https://github.com/beenje/flask_bokeh_app

**Comment by canavandl** [comment]
It is a bug.

All of the bokeh CSS is enclosed under the `bk-root` class name. The bokeh elements embedded via this autoload_server configuration are enclosed under a `bokeh-container` class name, so the css selectors don't align.

See here: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/embed.coffee#L171

The immediate solution is to set the class of the div containing the bokeh document as `bk-root`, like below:

index.html
```html
<!DOCTYPE html>
<html lang="en">

  <body>
    <h1>Bokeh app test</h1>
    <div class="bk-root">
      {{ bokeh_script|safe }}
    </div>
  </body>

</html>
```

We'll have to open a PR to resolve though. Thanks again for creating the repo to reproduce, that made finding the root cause a lot easier!

**Comment by beenje** [comment]
Thanks for the workaround and the fix!
