### ISSUE TITLE
Error after setting GMapPlot.api_key as string

### ISSUE THREAD

**Issue by cenveoanalyst** [bokeh/bokeh#4720]
Apparently Google has unexpectedly changed the rules on us in requiring API keys forcing the devs to make a last minute change. To assist them in migrating Bokeh into compliance, I am documenting an issue I noticed when using my api key as a string per the expected behavior they advised. When I set GMapPlot.api_key as a string (in both '' and """) the plot comes up blank and the Java Script console reveals:

Uncaught TypeError: Cannot read property 'addEventListener' of undefined

Code snippet:

`GMapPlot.api_key = 'MYAPIKEY``'

Javascript line erroring out:

`a.addEventListener){var e=d?4:1;a.addEventListener(b,c,d);c=new mb(a,b,c,e)}else a.attachEvent?(c=new mb(a,b,c,2),a.attachEvent("on"+b,nb(c))):(a["on"+b]=c,c=new mb(a,b,c,3));return c};_.B.addDomListenerOnce=function(a,b,c,d){var e=_.B.addDomListener(a,b,function(){e.remove();return c.apply(this,arguments)},d);return e};`

**Comment by bryevdv** [comment]
Hrm, If there was a problem here I believe it has since been resolved. See, e.g.

http://bokeh.pydata.org/en/dev/docs/user_guide/geo.html#google-maps-support

which is functioning correctly as is the example under `examples/models/maps.py`.  I'm just going to mark as `invalid` since that's the current situations and it did non get proper triage earlier (apologies @cenveoanalyst )
