### ISSUE TITLE
Discussion: cmap_func_generator ValueError/warning when Returning >256 Values

### ISSUE THREAD

**Issue by HuntJSparra** [bokeh/bokeh#4726]
Functions such as magma and plasma under bokeh.palettes can return more than 256 values, however they can only return 256 UNIQUE colors.

Should we add:
- A missable warning

OR
- A ValueError that gets the message across albeit at the cost of their code working (easy fix though)

Relates to #4696

**Comment by bryevdv** [comment]
ping @bokeh/dev

**Comment by almarklein** [comment]
It's about this, right? https://github.com/bokeh/bokeh/blob/f9a28ab7165023180b519239b5f8952f4e97a6d1/bokeh/palettes.py#L489-L499

**Comment by bryevdv** [comment]
Yes

**Comment by almarklein** [comment]
I think this should be an error, because someone doing `magma(n)` with `n>256` is *expecting* to get more than 256 colors, which won't happen.

**Comment by hsparra** [comment]
I think this should be a warning, and here is my thinking (probably not Pythonic). When I am going to shade some graph, I am not making precise decisions, and if so, can I really distinguish the difference of 1/256 of a shade of grey visually, much less something more? I am plotting my data to get a general high level view, such as does my data tend to fall into one area, is the grey darker past a certain point? I may have 300, or even a 1000 buckets I have grouped my data in, and these buckets are important. I am probably fine if my 1000 buckets are compressed down into 256 shades for my graph. A warning is good, however I would be vexed if I had to go and regroup all my data just so I could use shading. What a hassle for something that  is being eyeballed. In effect the compressing of my 1000 bins into 256 bins has no material effect most of the time, if ever. If y plot was all dark gray, that would tell me I probably have some outliers at the lower end that I might want to examine. However, not having 1000 shades did not matter, because It would probably still look the same to me. 

**Random fact** humans can only distinguish about 30 shades of grey. So it could be argued that 256 is already a little overkill.

Now if there was something that changed the underlying analysis, such as if the count of NaNs was being included in the count of observations in computing an average (made up), then I would want an error (hopefully informative) because that could have a material effect on the computed average.

**Comment by bryevdv** [comment]
@hsparra you can have 1000 bins and still use `grays(256)` you don't have to re-group anything. The purpose of a color mapper is to take the data (however many "bins" it has) and map it to a list of colors (however many "bins" that has), specifically so that there *isn't* a burden to have to match up the bins by hand on both sides. In fact, I would expect the same input data to behave basically identically with `grays(256)` or `grays(1000)`, but I agree with @almarklein that it's better to apply the principle of Least Surprise. To me `grays(1000)` implies a 1000 color palette, and that is absolutely what you don't get. That's surprising, I think, and so therefore I'd still prefer to make it an error.
