### ISSUE TITLE
Feature request: Correctly infer x/ylabel names from pandas.Series

### ISSUE THREAD

**Issue by femtotrader** [bokeh/bokeh#4747]
Hello,

plotting a timeserie doesn't work "out of the box".

Here is what I'm doing in a IPython notebook.

``` python
import pandas_datareader.data as web
df = web.DataReader("GOOG", "yahoo")
ts = df['Close']

from bokeh.io import output_notebook
from bokeh.charts import show
from bokeh.charts import TimeSeries
output_notebook()

p = TimeSeries(ts)

show(p)
```

And what I get:

![screenshot_bokeh_timeseries](https://cloud.githubusercontent.com/assets/5049737/16569170/7e5b019a-4233-11e6-98b3-c6d42fbc56e8.png)

There is in fact 3 issues / enhancements :
- time series name (`ts.name` is `'Close'` and so, as it's neither a blank string neither `None` this should be used instead of `'value'`
- time series index name (`ts.index.name` is `'Date'` and so, as it's neither a blank string neither `None` this should be used instead of `'index'`
- x-axis is incorrect

```
ts.index
DatetimeIndex(['2010-01-04', '2010-01-05', '2010-01-06', '2010-01-07',
               '2010-01-08', '2010-01-11', '2010-01-12', '2010-01-13',
               '2010-01-14', '2010-01-15',
               ...
               '2016-06-20', '2016-06-21', '2016-06-22', '2016-06-23',
               '2016-06-24', '2016-06-27', '2016-06-28', '2016-06-29',
               '2016-06-30', '2016-07-01'],
              dtype='datetime64[ns]', name='Date', length=1636, freq=None)
```

Kind regards

**Comment by canavandl** [comment]
Hi @femtotrader 

The x-axis scale issue has been resolved in the newest Bokeh 0.12.0 release. 

In terms of inferring the x and y axis labels, we should probably get the `df.index`'s `name` attr and use that. In terms of the y-axis though, it's a bit trickier because the chart supports multiple lines (i.e. perhaps showing Open, Close, and Mid-day prices), so it's unclear to be best infer the correct label in there.

In either case, it's easy to set the x and y-axis labels:

```python
import pandas_datareader.data as web
df = web.DataReader("GOOG", "yahoo")
ts = df['Close']

from bokeh.io import output_file, show
from bokeh.charts import TimeSeries

output_file('times.html')

p = TimeSeries(ts, xlabel='Date', ylabel="Close Price ($)", legend=False)

show(p)
```

<img width="623" alt="screen shot 2016-07-05 at 11 41 51 am" src="https://cloud.githubusercontent.com/assets/2198981/16592256/78b7ba7c-42a5-11e6-8884-5aec057ffc70.png">

**Comment by femtotrader** [comment]
Hi @canavandl 

thanks for your prompt answer I will try to update my Bokeh install.

`ts` is a Pandas Series, not a DataFrame so I think name should be infered correctly in such a case.

Kind regards

**Comment by canavandl** [comment]
I'm thinking you're right (re: pd.Series and inferring axis labels). We'll open an issue about it.

**Comment by Maggie-M** [comment]
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/43)
