### ISSUE TITLE
Default heigth and width Donut charts

### ISSUE THREAD

**Issue by bjorn-bakken** [bokeh/bokeh#4771]
bokeh.charts.Donut has default plot_height=400, but bokeh.charts.defaults has height=350. When combined with other charts in a (horizontal) layout this "cuts off" top and bottom of the donuts if you don't set plot_width (and possibly plot_height) explicitly.

To me it seems plot_height and plot_width in Donut are unnecessary. Other basic charts don't have plot_width ad plot_height as arguments as far as I can tell.

I'm no hardcore programmer, so apologizes in advance if I'm missing something..

**Comment by stvn66** [comment]
@bjorn-bakken, can you upload a snippet of code to demonstrate this?

**Comment by stvn66** [comment]
The default for Donut is that `plot_height` and `plot_width` are both 400.  This produces a circle with the correct aspect ratio.  It sounds like you prefer the default to instead be 350 x 350, is that right?

**Comment by stvn66** [comment]
The defaults behavior seems to work fine for me.  I was able to use them to apply the same size to both a donut and bar chart.  The donut plot will cutoff the top If the height is less than the width, but this is not a defaults problem.  

That said, I am not sure why Donut has a default `plot_height` and `plot_width` as it seems to be the only chart with a default different from the others.  Perhaps this is by design.  If not, it would be a simple thing to remove the defaults for donut, keeping the others the same. @bryevdv ?

**Comment by bryevdv** [comment]
bokeh.charts has moved to https://github.com/bokeh/bkcharts this should be re-opened there if appropriate.
