### ISSUE TITLE
Docs: Google Maps Down

### ISSUE THREAD

**Issue by HuntJSparra** [bokeh/bokeh#4774]
The Gmaps example under http://bokeh.pydata.org/en/latest/docs/user_guide/geo.html is down due to Google's API update. A warning or key should be added unless it is felt the gmaps example should be removed.

<img width="747" alt="screen shot 2016-07-08 at 3 54 34 pm" src="https://cloud.githubusercontent.com/assets/19802403/16701270/499d1a58-4524-11e6-8b6c-06effdf91fb8.png">

**Comment by jakubLangr** [comment]
Can confirm bug. Happens to me as well.

**Comment by bryevdv** [comment]
Well it's not exactly a bug, Google changed their TOS to always require an API key, we have no control over that. We also currently have no budget to deploy a key that might potentially receive alot of traffic, so my immediate suggestion is an image screen shot with a note about API key necessity.

**Comment by jakubLangr** [comment]
Yeah I understand. I can definitely contribute a screenshot but I'm not
sure if that will help because it looks exactly like the one above except
different number of points. So no way of registering a private key with
Bokeh? Even that would be a great help!!

Le lun. 15 août 2016 21:36, Bryan Van de Ven <notifications@github.com> a
écrit :

**Comment by bryevdv** [comment]
@jakubLangr Yes, an `api_key` property was added to `GMapPlot` recently in response to the Google change:

http://bokeh.pydata.org/en/latest/docs/reference/models/map_plots.html#bokeh.models.map_plots.GMapPlot.api_key

**Comment by bryevdv** [comment]
@birdsarah is there any reason not to just put a key in that does not have billing enabled? If there's some surge in usage it will just stop working for the day, but the daily limit is 25k

**Comment by birdsarah** [comment]
> @birdsarah is there any reason not to just put a key in that does not have billing enabled? If there's some surge in usage it will just stop working for the day, but the daily limit is 25k

I don't see why not. I think that sounds like a great plan. And if it doesn't work out for some reason, we can revisit.

**Comment by bendichter** [comment]
Yes, I would appreciate this change. Even if it exceeds the call limit in the docs, it will give correct example code. Currently it is unclear from the docs how to add the google api key. Is it an argument to GMapOptions or GMapPLot? Is the argument api=, api_key=, id=, or something else? The help on those two functions does not answer this, either.

It would also be nice to link to instructions for obtaining a free API key, like https://github.com/googlemaps/google-maps-services-python

We can include a note that explains it may not work due to the usage limit, but should work with a fresh key. Alternatively, is there a way of caching the results so we don't have to hit the api every time?

**Comment by bryevdv** [comment]
@bendichter just FYI every bokeh model property is documented in the reference guide, including this one:

http://bokeh.pydata.org/en/latest/docs/reference/models/map_plots.html#bokeh.models.map_plots.GMapPlot.api_key

**Comment by bendichter** [comment]
thanks @bryevdv, I didn't know that. I'm very new to bokeh. There are still several inconsistencies though. 

1. When I try to use the mapping functions without a key as shown in the documentation, I get the following error message: 
```.../bokeh/core/validation/check.py:E-1005 (MISSING_GOOGLE_API_KEY): Google now requires API keys for all Google Maps usage: GMapPlot(id='AIza...', ...)```
This would suggest that the argument is ```id```, but the link you sent me says it is ```api_key```. 

2. The documentation has the line:
```map_options = GMapOptions(lat=30.29, lng=-97.73, map_type="roadmap", zoom=11)```.
```lat```, ```lon```, and ```zoom``` are listed as arguments for the ```MapOptions``` class, but not the ```GMapOptions``` class. If I understand, ```GMapOptions``` is a subclass of ```MapOptions``` and optionally takes all of its arguments, but I don't see that stated in the documentation you sent me. It's also not in the help for GMapOptions.

**Comment by bryevdv** [comment]
@bendichter The example in the documentation is going to be updated. But it will take some time. In order obfuscate the key in the the user's guide example, some customizations will have to be made to our docs build system. There are 750 issues andd very few people working on them. If you'd like to improve the validation warning, a PR contribution would certainly be appreciated, the file is here: https://github.com/bokeh/bokeh/blob/master/bokeh/core/validation/errors.py

**Comment by bendichter** [comment]
I get that, thanks for the hard work. I just had several points of frustration using the documentation and I wanted to make sure I communicated them to the team. I took a look at the file you linked and it looks like (1) has already been fixed.
