### ISSUE TITLE
Render bokeh control inside bootstrap carousel

### ISSUE THREAD

**Issue by jdimatteo** [bokeh/bokeh#4813]
Bokeh controls render in the wrong place in a bootstrap carousel.

A couple workarounds: `.bk-toolbar-wrapper.bk-layout-null{ position: absolute; }` or `toolbar_location="above"`

This is described in some more detail here:
http://stackoverflow.com/questions/38388676/render-bokeh-control-inside-bootstrap-carousel

This is reproducible here: https://github.com/jdimatteo/flask_bokeh_app/tree/carousel

**Comment by bryevdv** [comment]
@jdimatteo does explicitly setting `toolbar_location="right"` also solve the problem? If so, my guess is the default is getting set as `None` which translates to `null` on the JS side, and then `None`/`null` is interpreted as "right side" in some places, but also allowing the `null` to make it into the templated CSS class.  If so that should be easy to fix.

**Comment by jdimatteo** [comment]
@bryevdv no, explicitly setting `toolbar_location="right"` does not fix the problem.  Sorry for the late response, and thanks for following up on this

**Comment by bryevdv** [comment]
There's pretty much zero chance that I will be able to fix this, and it seems to not be a common case. Now with PNG/SVG export, those actually seem like better options for a carousel anyway, so closing this.
