### ISSUE TITLE
Hovertool does not show tooltip of last glyph

### ISSUE THREAD

**Issue by Djeez2** [bokeh/bokeh#4853]
See the example on the website: 
http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#hovertool

When hovering over the tooltip of the right-most circle (index 4), the tooltip does not show.

This does not work in Bokeh 0.12.0 but used to work correctly in previous versions as can be verified by going to the user guide webpages of earlier versions such as 0.11.1

**Comment by bryevdv** [comment]
@birdsarah This issue seems to be due to the snug toolbar, it is somehow interfering with mouse event capture. If the toolbar is moved to the bottom, or if a pan tool is added and the plot is panned, then the point on the far right reacts as expected with the hover.  I think this has to be addressed before `0.12.1` maybe raising the `z-index` of the events-catching transparent div to make sure it is higher than the toolbar?

<img width="448" alt="screen shot 2016-07-21 at 8 44 19 am" src="https://cloud.githubusercontent.com/assets/1078448/17025010/9d7320dc-4f1f-11e6-80eb-b9cd1f1bd31a.png">


<img width="366" alt="screen shot 2016-07-21 at 8 44 55 am" src="https://cloud.githubusercontent.com/assets/1078448/17025016/9f86047a-4f1f-11e6-84c2-eda49e630256.png">

**Comment by bryevdv** [comment]
Yes, `bk-toolbar-wrapper` is extending into the plot:
<img width="1021" alt="screen shot 2016-07-21 at 8 49 22 am" src="https://cloud.githubusercontent.com/assets/1078448/17025113/1abc665c-4f20-11e6-8ba1-b0dc58213dd9.png">

**Comment by bryevdv** [comment]
Raising the `z-index` to 1000 manually does solve the issue, is that the best solution?
<img width="446" alt="screen shot 2016-07-21 at 8 51 14 am" src="https://cloud.githubusercontent.com/assets/1078448/17025172/5bea0d64-4f20-11e6-902d-7ab98845c4ee.png">
