### ISSUE TITLE
Fixed version in version.coffee causes constant "version mismatch" warning

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#4882]
I'm not sure what the intent was behind this, but in development mode this warning is useless. I presume `version.coffee` should be generated/templated and should include the actual version of bokehjs. Otherwise we can just skip it (in development mode).

**Comment by bryevdv** [comment]
@mattpap My preferred solution is to bump the version in all published BokehJS versions, including dev builds and RCs. 

The intent is to catch when e.g. people use `bokeh.components.embed` and add (wrong version) script tags, which has happened on a number of occasions.

**Comment by bryevdv** [comment]
After discussion with @brittainhard, identified this as the work to complete:

* have `deploy.sh` call `update_version.py` on dev builds and release candidates, in addition to full releases, so that BokehJS versions are updated on all published artifacts. 

* skip the version match test in `document.coffee` on any python version that is not a dev build, RC, or full release

Some possible details: 

* would be ideal not to push to NPM except on full releases. Might need a new check to prevent this. 

* this will make making dev builds slightly more verbose, having to provide the "previous version" the same as with full releases. Maybe there is a way to automate this, though.

**Comment by birdsarah** [comment]
ping @bryevdv - I'm still seeing a problem with 0.12.2dev2 - reopen?

**Comment by bryevdv** [comment]
`version.coffee` failed to update again on `0.12.2dev3`

**Comment by bryevdv** [comment]
Running `version_update.py` by hand, it seems it was not tooled to deal with `dev` or `rc` versions strings.

**Comment by bryevdv** [comment]
<img width="405" alt="screen shot 2016-08-17 at 9 25 14 am" src="https://cloud.githubusercontent.com/assets/1078448/17740010/a8bc0c68-645c-11e6-9837-61f29d9d5a6d.png">
