### ISSUE TITLE
`on_keypress` for `TextInput` widgets

### ISSUE THREAD

**Issue by guillochon** [bokeh/bokeh#4902]
Currently, it appears that the `on_change` event only fires when a `TextInput` box is defocused by the user, not on a keypress by keypress basis. It would be great if there was a separate `on_keypress` event that would fire with every keystroke. It appears that `AutocompleteInput` already does something like this to accomplish its completions, but a more general event handle would be useful.

**Comment by bryevdv** [comment]
The quickest immediate option is probably to write a custom extension to do what you want. To put this into the core library will probably mean developing the "event' notion that has been suggested in the past, but that will require planning and deliberation in addition to implementation and testing (so, a fair amount of time)

**Comment by seanlaw** [comment]
Where can I find a good example of a custom extension? Is that different from using CustomJS?

**Comment by bryevdv** [comment]
@seanlaw there is a new chapter in the users guide with several examples and information about the general process:

http://bokeh.pydata.org/en/latest/docs/user_guide/extensions.html

**Comment by bryevdv** [comment]
@philippjfr is there a separate issue for the UI events work that Holoviews is asking for? If so I assume this could be marked as a dupe.

**Comment by philippjfr** [comment]
There is this issue about it: https://github.com/bokeh/bokeh/issues/5278

It's worth considering how these things relate. In his original PR @canavandl implemented a UIEvents bus that could be installed on any ``Plot`` object and did not explicitly include keypress events (although we want those too). However this issue suggests that what we want is even more general than that since it would be nice if widgets could also trigger other events, which means an implementation solely for ``Plot`` models wouldn't be sufficient. I'm meeting @canavandl later to discuss it a bit and will summarize our discussion.

**Comment by bryevdv** [comment]
I am going to close this based on discussion elsewhere. Obviously anyone can write any extension they want or need, but I am not interested in having key-logging tools built directly into core bokeh.
