### ISSUE TITLE
Bokeh server relative import – No module named ‚my_own_relative_import‘

### ISSUE THREAD

**Issue by chrstof** [bokeh/bokeh#4943]
Hey Bokeh-Team,

I try to import a class from a file in a neighboring folder by using: 

`from folder.file import my_class`

Running the script and producing an `output_file('test.html')` works fine! Running the same script using:

`bokeh serve my_file.py --show`

yields the following error:

```
Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x00000000069D68D0>: No module named 'folder'
File "my_file.py", line 31, in <module>:
from folder.file import my_class Traceback (most recent call last):
"*Python34\lib\site-packages\bokeh\application\handlers\code_runner.py", line 83, in run
    exec(self._code, module.__dict__)
  File "*\my_file.py", line 31, in <module>
    from folder.file import my_class
ImportError: No module named 'folder'
```

As I said, running the code in python works fine, all local references are clear. Running the same code with` bokeh serve my_file.py` yields the error.
I can avoid this by appending the full path of the neighboring folder:
```
import sys
sys.path.append('C:\Full\Path\folder')
```

but in this file I load other references of my project and again and again. I do not want to append all subfolders to the path and I do not want to change the relative import in all these files to absolute paths. 

Is there a solution I couldn’t find?

MetaData:
Bokeh server version 0.12.1
Python 3.4
             platform : win-64
        conda version : 4.1.11
    conda-env version : 2.5.1
  conda-build version : 1.20.0
       python version : 3.5.2.final.0
     requests version : 2.9.1
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
         offline mode : False
    is foreign system : False

By the way, it’s a great project, thanks for all your effort!

**Comment by bryevdv** [comment]
If you use a "directory style" app, then the app directory is automatically appended to `sys.path` and any modules in the same directory as the app `main.py` can be imported directly. That is probably the best (possibly only) option. 

Please note, general support questions like this should be directed to the mailing list so that we can reserve the issue tracker for bugs and feature requests. If you do want to continue this discussion on the mailing list, please supply a zip file with a complete minimal code sample with the exact directory hierarchy in question. It's difficult to guess exactly what is going on from a text description.

**Comment by chrstof** [comment]
Thanks for your answer. I thought it's a bug or issue that I cannot load relative paths. I'll consult the mailing list with an example.
Thanks again.
