### ISSUE TITLE
ColorBar - Log scale not correct

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5020]
Was muddling around the LogColorMapper today and as a result was looking closer at this:

<img width="519" alt="screen shot 2016-08-22 at 10 02 02 pm" src="https://cloud.githubusercontent.com/assets/1796208/17880783/164f0e3c-68b4-11e6-99ae-1bfaf181f48a.png">

The numbers and the colors don't match up. On the lower plot, 20 is clearly in the yellow zone - which is what I would expect for log10 mapping.

It looks to me like the log ticks on the colorbar are on a natural log.

But LogColorMapper uses log base 10.

To be honest the log conversions confuse me, so I had a play around for a while but I'm not sure where the error's creeping in. ping @canavandl @bryevdv

**Comment by birdsarah** [comment]
More notes:
* LogColorMapper has been around for a long time
* The recent data mapping PR just uses the palette -> data conversion piece of LogColorMapper.

Other Log things are:
* LogMapper (which ColorBar uses)
* LogTickFormatter - which accepts a base argument via Adaptive Ticker (that defaults to log 10)
* LogAxis

The LogMapper has a bunch of tests, LogTickFormatter and LogAxis don't have tests. LogColorMapper has some old tests and some new tests.

**Comment by canavandl** [comment]
AFAICT, both the `log_mapper` and `log_color_mapper` use natural log. One tiny difference is that the log_color_mapper actually uses `Math.log1p` which is the same as `Math.log(x + 1)`, in order to handle values between 0 and 1. This will add some weirdness to small values (less than 10?), but that's usually below the range of values that `log` is used for.

I don't know how your made your Viridis3 plot, but mine seems accurate:

<img width="630" alt="screen shot 2016-08-23 at 12 30 11 pm" src="https://cloud.githubusercontent.com/assets/2198981/17902564/6a38dc84-692d-11e6-93cd-512a84e59e6f.png">

```python
import numpy as np

from bokeh.io import show
from bokeh.models import ColorBar, LogTicker
from bokeh.models.sources import ColumnDataSource
from bokeh.models.mappers import LinearColorMapper, LogColorMapper
from bokeh.palettes import Viridis6, Viridis3
from bokeh.plotting import figure

x = np.linspace(0, 100, num=2500)
y = np.random.normal(size=2500) * 2 + 5
source = ColumnDataSource(dict(x=x, y1=y, y2=y - 10))

log_mapper = LogColorMapper(palette=Viridis3, low=0, high=1e2)

p = figure(x_axis_type='linear', toolbar_location='above')
opts = dict(x='x', line_color=None, source=source)
p.circle(y='y1', fill_color={'field': 'x', 'transform': log_mapper}, legend="Log mapper", **opts)

colorbar = ColorBar(color_mapper=log_mapper, location=(0,0), orientation='horizontal', legend_padding=0)

p.add_layout(colorbar, 'below')

show(p)
```

Here's an example using the LogAxis, which also seems fine:

<img width="643" alt="screen shot 2016-08-23 at 12 13 41 pm" src="https://cloud.githubusercontent.com/assets/2198981/17902601/8c111204-692d-11e6-8b6f-1fd6764a3256.png">

```python
import numpy as np

from bokeh.io import show
from bokeh.models import ColorBar, LogTicker
from bokeh.models.sources import ColumnDataSource
from bokeh.models.mappers import LinearColorMapper, LogColorMapper
from bokeh.palettes import Viridis6, Viridis3
from bokeh.plotting import figure

x = np.logspace(start=0, stop=6, num=2500)
y = np.random.normal(size=2500) * 2 + 5
source = ColumnDataSource(dict(x=x, y1=y, y2=y - 10))

log_mapper = LogColorMapper(palette=Viridis6, low=0, high=1e6+1)

p = figure(x_axis_type='log', toolbar_location='above')
opts = dict(x='x', line_color=None, source=source)
p.circle(y='y1', fill_color={'field': 'x', 'transform': log_mapper}, legend="Log mapper", **opts)

colorbar = ColorBar(color_mapper=log_mapper, location=(0,0), ticker=LogTicker(), orientation='horizontal', legend_padding=0)

p.add_layout(colorbar, 'below')

show(p)
```

I suspect the issue is related to setting the high/low values of the LogColorMapper. Perhaps you could share some code?

**Comment by birdsarah** [comment]
BAH! I feel like I'm in the twilight zone.

The code was from the new example plotting/file/color_data_map.py

Here's what it looks like this morning:

<img width="431" alt="screen shot 2016-08-23 at 12 09 10 pm" src="https://cloud.githubusercontent.com/assets/1796208/17906063/80f20372-692a-11e6-91a6-450b12e024d8.png">
