### ISSUE TITLE
Can't use `{'value': ...}` dataspec with Patches/MultiLine

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5025]
Patches and MultiLine take xs/ys not x/y.

If you try and use the manual dataspec and set a value, rather than a field. e.g. `MultiLine(xs=[1, 2, 3, 4], ys='field_name')` you get the following error:

``` python
ValueError: expected an element of either String, Dict(String, Either(String, Instance(Transform), Instance(ColorMapper), Float)) or Float, got {'value': [2010, 2011, 2012, 2013, 2014]}
```

bokehjs will also need updating for this to work.

**Comment by bryevdv** [comment]
I'm not sure BokehJS will need updating, this might just be type checking that does not quite fit. I'd suggest being precise and making a separate `DataSpec` type that checks for sequence literals that can be used specifically by `Patches` and `MultiLine`, rather than adding that to the `Either` for the current `DataSpec`.

**Comment by birdsarah** [comment]
> I'm not sure BokehJS will need updating. It might, or this might just be Python type checking that does not quite fit. 

I did the quick hack python side before I opened the issue and it isn't sufficient you get an error bokehjs side.

**Comment by bryevdv** [comment]
Marking this `invalid`:

* Glyphs have always actually required field names not values (missed that earlier), it's `bokeh.plotting` that automagically puts values in CDS for you
* can no longer mix fields/values at all (as done above)
