### ISSUE TITLE
Embed Session with layout and loop_until_closed() not rendering in Django

### ISSUE THREAD

**Issue by RobbiePritchard** [bokeh/bokeh#5031]
I created a session using
`    session = push_session(curdoc())
`
curdoc() contains a layout using
`        layout=column(row(Spacer(width=40), input1, input2, Spacer(width=100), input4),row(scatter, Spacer(width=40), stack), row(widgetbox(dtable)))
`
 `       
curdoc().add_root(layout)
`
while showing the session using 
`        session.show()
`
`        session.loop_until_closed()
`
works fine. 

I would like to embed this into a Django application. Currently I am creating the session and returning it.
        `the_script = autoload_server(model=None, session_id=session.id)`

and then throwing this into the `<head>` of my django applciation using `{{the_script|safe}}`. Yet I get no graph shown while the `<script>` returned is:

```
<script
    src="http://localhost:5006/autoload.js?bokeh-autoload-element=94f5051c-e25d-48f4-b130-dbb950f103f7&bokeh-session-id=JCPp8UV6iqf8d1Angzo2GnX0mSrzRVyBiFhxasuW24Lg"
    id="94f5051c-e25d-48f4-b130-dbb950f103f7"
    data-bokeh-model-id=""
    data-bokeh-doc-id=""
></script>
```

while using chromes web inspector its showing 
```
"
<
"
```

How can I get the graph/layout displayed? Thank you

**Comment by bryevdv** [comment]
@havocp do you have any offhand observations?

**Comment by havocp** [comment]
are you running the bokeh loop inside a django process? what process is each piece of code in?

**Comment by RobbiePritchard** [comment]
I currently have `  ...  session = push_session(curdoc())
    session.loop_until_closed()
    return session.id` in a python file which I call with `        the_script = autoload_server(model=None, session_id=details_graph.returnScript())
` in the django's view.

**Comment by RobbiePritchard** [comment]
I got it to the point where I can see the graph without the `session.loop_until_closed()`. Yet the sliders don't work, and the graphs don't follow the same layout that` session.show() ` follows.

**Comment by havocp** [comment]
loop_until_closed() blocks forever (well, until the session is closed), so it's important not to run that function inside django or django will lock up. If your document doesn't set up any python callbacks, you can probably just drop the loop_until_closed(). If you do want python callbacks attached to the bokeh document, you would need the bokeh process separate from the django process to host them. If your sliders don't work that sounds like python callbacks aren't running (because you have no bokeh main loop inside the django process).

Unfortunately there's no way to send Python code to the bokeh server with push_session. The python callbacks have to be over in the Bokeh app from the start.

Potentially an approach to take is to write most of your Bokeh code as a bokeh app (run with `bokeh serve myapp.py`). There was recently a PR to give the Bokeh app access to the http request parameters that created each session, so django could pass parameters configuring each session, if that's needed. For example django could pass some JSON or some kind of database ID or other information to each new session of the Bokeh app, and then the Bokeh app would use that information. Only if that's needed of course, if all your Bokeh sessions are the same, there's no need for this.

**Comment by RobbiePritchard** [comment]
I will be running multiple unique bokeh apps, potentially at the same time. would the `bokeh serve myapp.py` still be a viable option? Would I need a separate `bokeh serve myapp.py` instance for each app? such as `bokeh serve myapp1.py, bokeh serve myapp2.py`   Would the `bokeh serve myapp.py` contain the `loop_until_closed()`?

**Comment by havocp** [comment]
You can run multiple apps like `bokeh serve myapp1.py myapp2.py` and then supply the app path to push_session and autoload_server to select the app you want. It can also work to run a separate server on a separate port for each app (an advantage of that is visibility into per app cpu usage).

You wouldn't need the loop or the session push inside the apps because it is done for you, check out the bokeh examples for examples. myapp.py runs once for each new session.

**Comment by bryevdv** [comment]
There are several example apps hosted at https://demo.bokehplots.com with links to their source code. There's also lots of information about running and deploying the Bokeh server here: http://bokeh.pydata.org/en/latest/docs/user_guide/server.html

I'm going to go ahead an close this since it seems to be a general support question, which should be directed to the public mailing list: https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
