### ISSUE TITLE
Investigate replacing jquery with jquip

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5039]
As part of ongoing efforts to trim the fat in bokehJS. Can we replace JQuery with JQuip - https://github.com/mythz/jquip

"The core jquip.js is only 6.6KB (minified and gzipped) - a fraction of the size of jQuery."

@bokeh/dev I was mistaken jquip isn't maintained by my friend @samastur, we've just used it on projects.

**Comment by samastur** [comment]
jQuip is not actively developed and in my tests jQuery was noticeably faster. It is also possible to create a custom build of jQuery to reduce its size, but that is unlikely to get you anywhere close to jQuip's size. It shouldn't matter though as both fit into one IP packet as long as jQuery gets loaded after HTML and CSS (so that TCP ramp-up does its work).

**Comment by bryevdv** [comment]
I think this can be closed, there are other efforts aimed at reducing BokehJS dependencies and size
