### ISSUE TITLE
push_notebook doesn't work in 0.12.2dev8

### ISSUE THREAD

**Issue by physinet** [bokeh/bokeh#5047]
The following Jupyter notebook cells worked in 0.12.1 and 0.12.2dev7. In dev7, I often had to wait a while before running the second cell would work. In dev8, I get the error message: "Cannot find a last shown plot to update. Call output_notebook() and show() before push_notebook()"

```
from bokeh.io import push_notebook, output_notebook, output_file, show
output_notebook(hide_banner=True)
```

```
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure
import numpy as np

x = np.linspace(0, 2*np.pi, 2000)
y1 = np.sin(x)
y2 = np.cos(x)

source1 = ColumnDataSource(data=dict(x=x, y=y1))
source2 = ColumnDataSource(data=dict(x=x, y=y2))

p = figure(title="simple line example", plot_height=300, plot_width=600, y_range=(-5, 5))
p.line(x, y1, color="#FF0000", alpha=1, line_width=2, source=source1, name="foo")
p.line(x, y2, color="#0000FF", alpha=1, line_width=2, source=source2, name="bar")

show(p)
source1.data['y'] = 2*y1
push_notebook()
```

**Comment by philippjfr** [comment]
In a recent PR we changed the behavior for notebook interactions in the notebook slightly, in order to be able to push updates to a plot you now have to explicitly request a notebook_handle from ``show``. Simply replace ``show(p)`` with ``show(p, notebook_handle=True)``. @bryevdv I suppose the documentation should be updated to reflect this.

**Comment by bryevdv** [comment]
I added the MIGRATION tag to the PR specifically to ensure this breaking change is noted in the documentation.
