### ISSUE TITLE
Read the docs documentation

### ISSUE THREAD

**Issue by syamajala** [bokeh/bokeh#5069]
I see there is a bokeh project on read the docs available at https://readthedocs.org/projects/bokeh/ but it has never had any successful builds. Would it be possible to get that fixed?

It would be nice to have the documentation available on there because it is very easy to download documentation for offline use from read the docs.

**Comment by bryevdv** [comment]
We have put extensive work into building, automating, and maintaining the extensive docs at http://bokeh.pydata.org Additionally, a cursory look at the RTD build appears to expect that a simple `python setup.py install` will work, but Bokeh's build is substantially more complicated (because  BokehJS also has to be compiled from CoffeeScript, unlike "normal" python projects) Any change to our build automation is risky and must necessarily involve extensive and often time-consuming testing. We are a very small team and are already swamped with more work than we can accomplish. Unfortunately, putting any team resources into duplicating what already exists is not a justifiable use of time. If someone else wants to try and make this work, we will certainly answer any questions as best we can.

**Comment by syamajala** [comment]
Is there any bokeh documentation available offline? The system I develop on doesn't have internet access due to security restrictions, however, I am allowed to put documentation on a usb stick and bring it in with me. I tried building the documentation myself, but it doesn't include CSS and uses various things from CDN.

**Comment by timsnyder** [comment]
Hi @syamajala, I see what you are seeing when I do a local build of the docs and then serve them locally with `make serve`.   There are definitely resources that come from the internet, without some special setup, the timeouts take forever on those resources and make the local docs unusable.

Looking at the places where those resources are included in the docs (e.g. ` sphinx/source/bokeh_theme/layout.html`), I don't see an obvious "offline" mode being available.  I can envision creating and testing an offline mode for the docs.  It would require that a connected machine to build the docs but then an airgapped machine could serve them locally.

I see value in being able to have a usable offline copy of the docs but I would want @bryevdv or one of the other core devs to think it was a good idea and that they would be willing to accept a reasonable PR before putting work into it.  One of the more experienced devs might have an easy recipe for looking at locally built docs while offline.  

BTW, @bryevdv, I looked into the RTD build flow when this ticket was opened and then closed.  I think that we could pretty easily put a redirect page (like the one on http://bokehplots.com) at RTD.  If you would be interested in a PR for that, I could finish figuring it out.
