### ISSUE TITLE
Changes pushed to notebook are lost upon reopening notebook

### ISSUE THREAD

**Issue by physinet** [bokeh/bokeh#5104]
If I run all the cells in [`Basic Usage.ipynb`](https://github.com/bokeh/bokeh/blob/master/examples/howto/notebook_comms/Basic%20Usage.ipynb), save the notebook, close it, and reopen it, the plots do not reflect any of the `push_notebook` updates. The plots instead appear as they do right after `show`ing them. Which behavior was intended? I would like to have the plots look as they did just before closing the notebook.

**Comment by bryevdv** [comment]
The current behavior is the intended behavior. Offhand, I am skeptical that a technical path to implement what you are suggesting even exists, unfortunately.

**Comment by physinet** [comment]
Really? I don't know enough about how `push_notebook` updates the plots to understand why this is the case. What I'm aiming to do is have a plot initialize and then update in a loop, and I'd like to see the final version of the plot when reopening the same notebook.

A cheap fix is to just `show` again once done updating, or save figures to html using the example [here](https://github.com/bokeh/bokeh/blob/master/examples/embed/embed_multiple.py). This will satisfy my needs for now, but please consider this as a feature request.

**Comment by bryevdv** [comment]
`push_notebook` opens up a notebook comms websocket connection between the notebook frontend and the running jupyter kernel, so that the (in-memory) JS representation of the plot can be updated. It is really 100% dependent on having a running python kernel, and I don't see how that could ever be avoided. Additionally entire purpose of `push_notebook` is to provide an efficient way to update plots *without* re-publishing cells (because that might be expensive). Making the changes persistent in some way would necessarily mean re-publishing cells (somehow, though I'm not sure how that would or could work either), which I would deem to be completely contrary to `push_notebook`s primary purpose.
