### ISSUE TITLE
Pan and Zoom tools should be configurable (limit to x or y axis only) via UI

### ISSUE THREAD

**Issue by kbrose** [bokeh/bokeh#5135]
Getting the warning "UserWarning: PanTool are being repeated" when using the distinct tools "pan" and "xpan". I would expect there to not be a warning here.

Code to reproduce:

``` python
from bokeh.plotting import figure
from bokeh.plotting import show
p = figure(tools='pan,xpan')
p.line([0, 1, 2, 3], [1, 0, 3, 2])
show(p)
```

Warning message:

```
[...]\Anaconda2\lib\site-packages\bokeh\plotting\helpers.py:322: UserWarning: PanTool are being repeated
```

Bokeh info:

```
>bokeh info
Python version      :  3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
IPython version     :  4.0.3
Bokeh version       :  0.12.2
BokehJS static path :  [...]\Anaconda2\lib\site-packages\bokeh\server\static
```

**Comment by timsnyder** [comment]
I question the usefulness of that warning as well.  There are clear use cases where having duplicate pan tools is nice.

As an experiment, I gave all of the helper strings to `examples/plotting/file/iris.py` to see what would happen:
```
diff --git a/examples/plotting/file/iris.py b/examples/plotting/file/iris.py
index e7a7f9b..54c74f0 100644
--- a/examples/plotting/file/iris.py
+++ b/examples/plotting/file/iris.py
@@ -1,10 +1,11 @@
 from bokeh.plotting import figure, show, output_file
+from bokeh.plotting.helpers import _known_tools
 from bokeh.sampledata.iris import flowers
 
 colormap = {'setosa': 'red', 'versicolor': 'green', 'virginica': 'blue'}
 colors = [colormap[x] for x in flowers['species']]
 
-p = figure(title = "Iris Morphology")
+p = figure(title = "Iris Morphology", tools=','.join(_known_tools))
 p.xaxis.axis_label = 'Petal Length'
 p.yaxis.axis_label = 'Petal Width'
```

The universe didn't melt.  UX seems okay in terms of the tools working like they are supposed to. 

At least the message is using `warnings.warn` and [could be ignored](https://docs.python.org/2/library/warnings.html#the-warnings-filter)

**Comment by timsnyder** [comment]
@kbrose the string tool names are helpers that get expanded into tool objects when the plot is constructed.  The warning is telling you that you have two different PanTools on your plot.  I'm assuming you want the two PanTools because your original post calls them 'distinct'.  

However, from a UX perspective, it might be a bit confusing to have two tool icons that are the same and thus the helpers issue a warning to let you know that you will have two PanTool objects that will each have the same icon.  They will only be distinguished by the hovertext on the tool icon.

If you want to filter these messages, here is an example of the required code:
```python
from bokeh.plotting import figure
from bokeh.plotting import show
from warnings import filterwarnings
filterwarnings('ignore', message='.*being repeated', category=UserWarning, module='bokeh\.plotting\.helpers')
p = figure(tools='pan,xpan')
p.line([0, 1, 2, 3], [1, 0, 3, 2])
show(p)
```

I think that it might be helpful to add some more information to this warning message.  What do you think of having it say something like this:
```
...bokeh\plotting\helpers.py:322: UserWarning: PanTool are being repeated. While this will function, it may lead to UX confusion because there will be multiple copies of the same icon in the toolbar. See: http://pointer.to.userguide.explaination
```

@kbrose, would a bit more explanation in the message and a pointer to a location in the User Guide address your concerns?

**Comment by timsnyder** [comment]
(Via gitter, bryevdv says)[https://gitter.im/bokeh/bokeh?at=57d568a8cba69fe735046345]:
>  i guess my preferred change would be to make a single pan tool configurable via the UI rather than have multiple pan tools but that's a slightly larger undertaking
> The warning could be more careful for pan and zoom and also check that the dimension is identical
> Then it would not warn for pan and xpan

**Comment by kbrose** [comment]
@timsnyder 
The warning did not concern me too much, it was just a nuisance more than anything, Showing the same icon for both could definitely lead to confusion (I had to hover-over the tool to know which was which). I think making the pan/zoom tools have a toggle option for the dimension sounds like a good way to go.

Thanks for looking into this!

**Comment by timsnyder** [comment]
@kbrose, do you mind if we change the title of this issue to "Pan and Zoom Tools should be configurable via the UI"?  Since I'm not a member of @bokeh/core and didn't open the issue, I can't edit the title.

When we make the pan tools configurable via the UI, there are certain aspects of the zoom tools that could also benefit from a context menu on their toolbar button.  As I mentioned in the beginning of #4841:
> Does it make sense to expose zoom-only mode on wheel-zoom? I personally find it awkward to use wheel-zoom when it pans and zooms at the same time. This could be implemented easily now by programmatically eliding the 'center' parameter to scale_range(). Perhaps it could be implemented as wheel-zoom button having a dropdown radio-button list like tap tool that lets the user choose to lock down the center of the plot and only scale in and out

I have this ticket in [my personal list of stuff to look at](timsnyder/bokeh/wiki/Things-to-work-on)

**Comment by bryevdv** [comment]
Having more work than people means that some things will simply take awhile to get done.  I think this is still worth doing, even if I can't speculate offhand when resources will be available to dedicate to it..

**Comment by kbrose** [comment]
My apologies @bryevdv. I was going through my open issues trying to clean up ones that had been addressed. I saw that some PRs had referenced this and thought it had been taken care of (I've stopped using Bokeh in the meantime so I wasn't able to thoroughly verify).

**Comment by Roald87** [comment]
I recently used plotly and there you can simply limit zooming to the y or x axis by not moving too much (say +/- 10 pixels) into the other direction. Quite intuitive and no need for extra buttons. 

Additionally isn't it possible to enable panning (scroll mouse button click) and scroll zoom (scroll button) and selection zoom (left mouse click) at the same time? Then you can get rid of most of the buttons. Maybe use a double tap to reset the plot?

**Comment by antoine-gallix** [comment]
I have the same problem. Until this issue get fixed, the following code will suppress the warning:

```python

import warnings

warnings.filterwarnings(
    'ignore',
    '.* are being repeated',
    category=UserWarning,
    module='bokeh.plotting.helpers',
)


```

**Comment by mattpap** [comment]
Pan, zoom and other tools now can be configure in the UI, e.g. for pan tool:

![image](https://user-images.githubusercontent.com/27475/190243277-984fee93-b96a-47bf-af84-696a4911be34.png)

This was implemented across multiple PRs in bokeh 3.0-dev. Specifically pan tool config menu was added in PR #11915. Additionally, box zoom tool also supports auto mode since PR #12277. I will consider this issue resolved. If there are further concerns or requests, please submit new issues.

**Comment by bryevdv** [comment]
@mattpap I do want to mimic the behavior of other tools, e.g. where dragging horizontally without much vertical movement (within a tolerance) automatically uses only an x-zoom, etc. without any button or context interactions needed.  Is there a separate issue for that? If not, this should be re-opened.

**Comment by mattpap** [comment]
I would open a new issue (or issues) to be explicit about the particular requirements, because at this point this issue is hard to follow.
