### ISSUE TITLE
Labels on Axis do not like ":" character ;-)

### ISSUE THREAD

**Issue by Pegase92** [bokeh/bokeh#516]
Good afternoon,

While settings label axis with character ":", labels was not displayed on the screen.
My need was to display time (format H:M:S) as xaxis label. Nothing change if I add  x_axis_type = "datetime".

Many thanks for Bokeh library and your works ...

Pegase92
# 

Code example that is running correctly : 

```
from bokeh.plotting import *
output_file("boxplot.html")
figure()
hold()
Etiquette=['A','B','C','D','E']

segment(Etiquette,[0,0,0,0,0,0,0,0,0,0,0],Etiquette,[-1,2,3,2,0],x_range=Etiquette,line_width=2, line_color="black",plot_width=1200,plot_height=500)  

rect(x=Etiquette,y=[-.5,1,1.5,1,0],width=0.5,height=[-1,2,3,2,0],fill_color='blue',plot_width=1200,plot_height=500,tools=TOOLS)

show()
```
# 

Code example that is not running correctly (xaxis labels are not displayed) : 

```
from bokeh.plotting import *
output_file("boxplot.html")
figure()
hold()
Etiquette=['00:00:00-00:00:01','00:00:01-00:00:02','00:00:02-00:00:03','00:00:03-00:00:04','00:00:04-00:00:05']

segment(Etiquette,[0,0,0,0,0,0,0,0,0,0,0],Etiquette,[-1,2,3,2,0],x_range=Etiquette,line_width=2, line_color="black",plot_width=1200,plot_height=500)  

rect(x=Etiquette,y=[-.5,1,1.5,1,0],width=0.5,height=[-1,2,3,2,0],fill_color='blue',plot_width=1200,plot_height=500,tools=TOOLS)

show()
```

**Comment by birdsarah** [comment]
Just had this at Europython with @abele trying to make a categorical heatmap with timestamps as one of the axes, that looked like this: `['2015-01-31 00:00:00', '2015-02-28 00:00:00', '2015-03-31 00:00:00']`

Bokeh 'failed' silently with no warning in the console or the notebook - the plot was blank.

The following labels worked `['2015-01-31', '2015-02-28', '2015-03-31']`

I'm thinking that, while we work out the right spelling, we could add a warning.

**Comment by damianavila** [comment]
A warning was added by #2617, still the problem stand, so I will keep this open...

**Comment by Pablo-Galaviz** [comment]
The warning says error and it is annoying. I hacked renderers.py (in my local source):

		    if len(value.split(':')) > 2:
                        broken.append((vm[label]['field'], value))
                        break

instead of 
		    if ':' in value:
                        broken.append((vm[label]['field'], value))
                        break

**Comment by bryevdv** [comment]
@Pablo-Galaviz it's an error that causes BokehJS to fail to render, it's supposed to be annoying? It will become even more so: in `0.10` validation errors will start to raise exceptions. A PR that adding "BOKEH_VALIDATION" option to `bokeh.settings` to control turning validation on or off would certainly be considered, if you'd like to submit one. 

Regarding your change, the only difference I can see is that it allows values like `":begin"` and `"end:"` with the colon not in the middle? I agree that on the surface, this is seemingly "closer" to how the JS splits and tests for the delimiter, but it's not actually different:
```
":begin".split(":")
```
and 
```
alert("end:".split(":")
```
both return length two lists (with an empty string as one of the elements). If this change lets something  "work" for you in some way, it might be interesting to see a complete runnable example, since I would not expect it to behave any differently. 

@bokeh/core I hate to pile more on something that is a hack in the first place, but is it worth considering making the delimiter configurable (e.g.,via `BOKEH_CAT_SEPARATOR=";"`) in the short term, until the underlying problem can be fixed more comprehensively?

**Comment by damianavila** [comment]
> A PR that adding "BOKEH_VALIDATION" option to bokeh.settings to control turning validation on or off would certainly be considered, if you'd like to submit one.

Yep, could be useful...

>@bokeh/core I hate to pile more on something that is a hack in the first place, but is it worth considering making the delimiter configurable (e.g.,via BOKEH_CAT_SEPARATOR=";") in the short term, until the underlying problem can be fixed more comprehensively?

I am OK with that for a short term resolution.

**Comment by Pablo-Galaviz** [comment]
Just to clarify, when I said 'it is annoying' I was referring to the following example:

from bokeh.charts import Bar, output_file, show

# prepare some data
data = {"y": [6, 7, 2, 4, 5], "z": [1, 5, 12, 4, 2]}

# output to static HTML file
output_file("bar.html")

# create a new line chat with a title and axis labels
p = Bar(data, cat=['C1', 'C2', 'C3', 'D1', 'D2'], title="Bar example",
        xlabel='categories', ylabel='values', width=400, height=400)

# show the results
show(p)

The example works properly but with the warning (error). The categories are using : to define the bars in the chart.

**Comment by birdsarah** [comment]
I think this is a bug and we should open a new issue. Running @Pablo-Galaviz's example (and have also checked with the Bar Charts in our examples).

The warning is:
````ERROR:/home/bird/Dev/bokeh/bokeh/bokeh/validation/check.py:W-1003 (MALFORMED_CATEGORY_LABEL): Category labels are malformed: [field:caty] [first_value: C1:0.333333333333] [renderer: GlyphRenderer, ViewModel:GlyphRenderer, ref _id: 3ad8d365-63af-420c-a0f0-7318cccd1047]
ERROR:/home/bird/Dev/bokeh/bokeh/bokeh/validation/check.py:W-1003 (MALFORMED_CATEGORY_LABEL): Category labels are malformed: [field:catz] [first_value: C1:0.666666666667] [renderer: GlyphRenderer, ViewModel:GlyphRenderer, ref _id: c6d7cbb9-d53a-4714-9ab5-1094c6774344]````

The renderer.data_source.data is:
````
{'cat': ['C1', 'C2', 'C3', 'D1', 'D2'],
 'caty': ['C1:0.666666666667',
  'C2:0.666666666667',
  'C3:0.666666666667',
  'D1:0.666666666667',
  'D2:0.666666666667'],
 'catz': ['C1:0.333333333333',
  'C2:0.333333333333',
  'C3:0.333333333333',
  'D1:0.333333333333',
  'D2:0.333333333333'],
 'midy': array([ 3. ,  3.5,  1. ,  2. ,  2.5]),
 'midz': array([ 0.5,  2.5,  6. ,  2. ,  1. ]),
 'stackedy': array([  4. ,   8.5,  13. ,   6. ,   4.5]),
 'stackedz': array([ 0.5,  2.5,  6. ,  2. ,  1. ]),
 'width': [0.8, 0.8, 0.8, 0.8, 0.8],
 'width_cat': [0.2, 0.2, 0.2, 0.2, 0.2],
 'y': [6, 7, 2, 4, 5],
 'z': [1, 5, 12, 4, 2],
 'zero': array([  7.,  12.,  14.,   8.,   7.])}
````
It seems to be warning about values not just keys?

**Comment by abele** [comment]
@birdsarah it shows key and first malformed value.
The goal of this PR is to give newcomers some transparency why chart is rendered blank. I think it's already to complicated for workaround.

**Comment by bryevdv** [comment]
@birdsarah maybe there has been some confusion around things. The things that cannot have colons on them are categorical coordinates. If the values are used as categorical coordinates, it seems appropriate to error out  on them. @pzwang suggested maybe using `::` as an "escape sequence" as a short term workaround. I'm not sure, ideas welcome. If this issue is just a statement of the fact that colons are not currently allowed in categorical coordinate values, we can close it as a duplicate. I can't tell if there is a new issue or not.

**Comment by bryevdv** [comment]
FYI If I were to propose short term fix it would be:
* add `BOKEH_CAT_SEPARATOR` option
* change the default separator to `;`

**Comment by birdsarah** [comment]
> @birdsarah maybe there has been some confusion around things. The things that cannot have colons on them are categorical coordinates. If the values are used as categorical coordinates, it seems appropriate to error out on them.

got it - thanks!

I like changing the default seperator to `;;`

**Comment by mattpap** [comment]
> add BOKEH_CAT_SEPARATOR option

I see that this is supposed to be a short term fix, but shouldn't we just make category separator configurable on a data source, through a property?

**Comment by bryevdv** [comment]
That also seems reasonable.

**Comment by bryevdv** [comment]
OK so the the check added previously was too broad. It is checking *values* which can contain colons, in addition to range values (which cannot). I will add a PR to at least remove the offending check. That will improve things for now, at least somewhat.

**Comment by bryevdv** [comment]
Long term solution is to support nested coordinate systems. This issue should track an effort on the short-term fix: to make the separator optionally configurable to something other than `:`

**Comment by philippjfr** [comment]
Ran into this again when formatting datetimes in a categorical axis? Any progress on this?

**Comment by NfNitLoop** [comment]
Lost hours this week due to this bug. Couldn't figure out why some of our graphs were suddenly breaking despite changing none of our code. Turns out that some of the labels (which we generate from data in our database) now have `:` in them, so started causing Bokeh to silently render an empty graph.

**Comment by bryevdv** [comment]
@NfNitLoop I'm certainly sorry to hear that you lost time due to this issue. No one wants any bugs, but the devs are only all too human, and the simple math of `# of issues / # of dev hours` dictates that some things will take a long time no matter what (until or unless more contributors come on board)

Fixing this correctly, it turns out, depends on a deeper refactor of the way Bokeh handles categorical variables in general, and also how it might handle nested coordinate systems. I had hoped that it might be able to be resolved for `0.12.5` but we have run out of time for that release unfortunately. However, it is one of my top priorities for `0.12.6` so will hopefully be fixed in a dev build fairly soon.

**Comment by bluenote10** [comment]
I run into this as well in one of my very first steps with Bokeh, but it took me a few weeks to figure out what it was. Since I didn't find this issue at first, I've also prepared a JSFiddle to demonstrate the issue on BokehJS side: https://jsfiddle.net/bluenote10/L2wmhmo9/

I'm not sure if changing the separator to something more unlikely is technically a fix, it will just show up with different data (maybe even harder to figure out why).

+1 for nested/hierarchical factor ranges, which could solve these issues cleanly as far as I can see.

**Comment by birdsarah** [comment]
WAAAAATTTTTTT - well done team.

**Comment by bryevdv** [comment]
> WAAAAATTTTTTT - well done team.

We made categoricals great again
