### ISSUE TITLE
Reset tool fails when figure passed width instead of plot_width, etc. 

### ISSUE THREAD

**Issue by rocheseb** [bokeh/bokeh#5185]
Hello,

I made the following code to illustrate the following issue:

the Reset tool should not change the pixel size of figures containing plots using data from callback-filled ColumnDataSource objects.

One would expect the Reset tool to work as the button in this code:

```

from bokeh.plotting import Figure
from bokeh.models import ColumnDataSource, CustomJS, RadioGroup, Button, VBox
from bokeh.layouts import gridplot
from bokeh.resources import CDN
from bokeh.embed import file_html

x0 = range(10)
x1 = range(100)
y0 = [i for i in x0]
y1 = [i*2 for i in x1][::-1]


fig=Figure(height=250,width=800)

source1=ColumnDataSource(data={"x":[],"y":[]})
source2=ColumnDataSource(data={"x0":x0,"x1":x1,"y0":y0,"y1":y1})

p = fig.line(x='x',y='y',source=source1)

callback=CustomJS(args=dict(s1=source1,s2=source2,px=fig.x_range,py=fig.y_range),  code="""
    var d1 = s1.get("data");
    var d2 = s2.get("data");
    var val = cb_obj.active;

    d1["y"] = [];
    d1["x"] = [];
    var y = d2["y"+val];
    var x = d2["x"+val];

    var min = Math.min( ...y );
    var max = Math.max( ...y );

    py.set("start",min);
    py.set("end",max);

    var min = Math.min( ...x );
    var max = Math.max( ...x );

    px.set("start",min);
    px.set("end",max);

    for(i=0;i<=y.length;i++){
        d1["y"].push(d2["y"+val][i]);
        d1["x"].push(d2["x"+val][i]);
    }

    s1.trigger("change");
    """)


radiogroup = RadioGroup(labels=['First plot','Second plot'],active=0,callback=callback)
radiobox = VBox(radiogroup,width=100)

callback2=CustomJS(args=dict(radiogroup=radiogroup,s1=source1,s2=source2,px=fig.x_range,py=fig.y_range), code="""   
    var d1 = s1.get("data");
    var d2 = s2.get("data");
    var val = radiogroup.active;

    d1["y"] = [];
    d1["x"] = [];
    var y = d2["y"+val];
    var x = d2["x"+val];

    var min = Math.min( ...y );
    var max = Math.max( ...y );

    py.set("start",min);
    py.set("end",max);

    var min = Math.min( ...x );
    var max = Math.max( ...x );

    px.set("start",min);
    px.set("end",max);

    for(i=0;i<=y.length;i++){
        d1["y"].push(d2["y"+val][i]);
        d1["x"].push(d2["x"+val][i]);
    }

    s1.trigger("click")
    """)

button = Button(label='Reset axes',button_type='success',callback=callback2)
buttonbox = VBox(button,width=100)

grid = gridplot([[radiobox,buttonbox],[fig]])

outfile=open('TEST.html','w')
outfile.write(file_html(grid,CDN,'Reset'))
outfile.close()
```

**Comment by bryevdv** [comment]
@rocheseb I can't tell from your description what is happening with the reset tool. Here is what the reset tool does:

* resets data bounds to their original values
* clears any selections on data sources
* resets the canvas size (e.g. `plot_width` and `plot_height`) to its original dimensions

Is it the last one you are not liking? That behavior was added after sustained requests by user for it to do that. If that is what you'd like to be different, then the immediate answer is for you to write your own custom extension tool. If you wanted to make a PR to add a configuration option to the existing built-in tool that would be considered. 

If that is *not* what you mean, then you will have to explain further, because I don't understand. In particular, it's usually more clear to give a "broken" and point out what you think it should *not* be doing.

**Comment by bryevdv** [comment]
@rocheseb this actually has to do with using `Figure` instead of `figure` (I have updated the title accordingly. Here is a minimal example that shows `figure` works. FWIW I'd recommend using the function`figure` instead of the class`Figure` directly 
```
from bokeh.plotting import figure
from bokeh.io import output_file, show

x0 = range(10)
y0 = [i for i in x0]

p = figure(height=250,width=800) # reset would fail with Figure
p.line(x=x0, y=y0)

output_file("foo.html")
show(p)
```

**Comment by bryevdv** [comment]
@rocheseb additionally, the actual property names are `plot_width` and `plot_height`, not `width` and `height` 

This is also the crux of the isuse. The function `figure` accepts `width` and `height` as a convenience, and converts them to the real property names internally. The class `Figure` does *not do this*, so passing `width` and `height` *should* generate an error. But it doesn't due to an unxpected interaction -- the parent class `LayoutDOM`does have  properties `width` and `height` which soaks up `width` and `height` values, and does so in a way that accidentally causes the initial figure size to be "right" but does not configure things for the reset to to work correctly. Long story short: use `figure`, use `plot_width` and `plot_height`

@mattpap @birdsarah what to do about this? could detect and convert `width` and `height` in `Figure` initializer? Not super fond of having different ways to spell things, but that's the history we are saddled with, so it might be the best option.  Whatever we do all the glyph method examples  in `figure.py` should be updated to use `plot_width` and `plot_height` (they don't currently)

**Comment by alex-waters** [comment]
Thanks for resolving this!

Given that the solution is to use `figure()` when setting dimensions, that makes it a challenge to use the reset button within `bokeh.charts` with a plot of non default dimensions. Ie this won't work great with reset:

`from bokeh.charts import Area, show, output_notebook, defaults
import numpy as np
import pandas as pd

defaults.width=800
defaults.height=500

x = np.array([1,2])
y = np.array([1,2])

data = pd.DataFrame({'x': x, 'y': y})

defaults.width=200
defaults.height=300

chart = Area(x='x',y='x', data=data)

output_notebook()

show(chart)`
