### ISSUE TITLE
bokehjs plotting API is broken after PR #5017

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5218]
bokehjs' examples weren't tested, so here we are. `bokehjs/examples/legends` fails with `Cannot read property 'prototype' of undefined`.

**Comment by birdsarah** [comment]
I was trying to look at this. I went into the bokehjs directory

    $ cd bokehjs

I ran the examples the way I always have

    $ ./node_modules/gulp/bin/gulp.js examples

The js files were then added to my top level directory so that my git status now looks like this

```
(bokeh_34) ➜  bokehjs git:(mattpap/5218_api_markers) ✗ pwd
/Users/caged/Dev/bokeh/bokeh/bokehjs
(bokeh_34) ➜  bokehjs git:(mattpap/5218_api_markers) ✗ git st
On branch mattpap/5218_api_markers
Your branch is up-to-date with 'origin/mattpap/5218_api_markers'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        anscombe.js
        burtin.js
        charts.js
        donut.js
        hover.js
        legends.js
        linked.js
        stocks.js
        tap.js

nothing added to commit but untracked files present (use "git add" to track)
```

When I try and look an example, unsurprisingly, it fails:

```console
Failed to load resource: net::ERR_FILE_NOT_FOUND - file:///Users/caged/Dev/bokeh/bokeh/bokehjs/examples/anscombe/anscombe.js Failed to load resource: net::ERR_FILE_NOT_FOUND
```
I can manually edit `bokehjs/examples/anscombe/anscome.html` to point correctly, and the example looks fine. But obviously that's not the ideal solution.

Any thoughts about what's going wrong here?

**Comment by birdsarah** [comment]
Update: Comment posted to #5219 which is what I meant to do

**Comment by birdsarah** [comment]
If the js examples aren't part of our CI something like this is going to happen again.

**Comment by mattpap** [comment]
@birdsarah, yeah it will. Need to find some time to include this in the test suite.
