### ISSUE TITLE
`mpl deprecation warning` for converting simple `plt.scatterplot` to `bokeh`

### ISSUE THREAD

**Issue by jolespin** [bokeh/bokeh#5275]
```
import bokeh
print(bokeh.__version__)
# 0.12.2

# Plot from Matplotlib

# Tools (Not sure how to add this when converting from `matplotlib` or `Seaborn`)
hover = HoverTool(
        tooltips=[
            ("index", "@index"),
            ("(x,y)", "(@t, $y)"),
            ("desc", "@desc"),
        ]
    )

# Data
DF_data = pd.DataFrame([a, np.sin(np.pi*a), np.cos(np.pi*a)], index=["t", "sine", "cosine"], columns=["t_%d"%_ for _ in range(100)]).T
DF_data["desc"] = ["info about this" for _ in DF_data.index]

# Matplotlib
fig, ax = plt.subplots(figsize=(15,5))
ax.scatter(data=DF_data, x="t", y="sine", s=np.linspace(0,100,100), alpha=0.5, color="green")
ax.scatter(data=DF_data, x="t", y="cosine", s=np.linspace(0,100,100)[::-1], alpha=0.5, color="teal")

# Convert to Bokeh
bokeh.io.show(bokeh.mpl.to_bokeh())
```
The error:

> /Users/Mu/anaconda/lib/python3.5/site-packages/bokeh/core/compat/bokeh_renderer.py:257: UserWarning:
> 
> Path marker shapes currently not handled, defaulting to Circle
> 
> /Users/Mu/anaconda/lib/python3.5/site-packages/matplotlib/artist.py:221: MatplotlibDeprecationWarning:
> 
> This has been deprecated in mpl 1.5, please use the
> axes property.  A removal date has not been set.
> 
> /Users/Mu/anaconda/lib/python3.5/site-packages/bokeh/core/compat/bokeh_renderer.py:290: UserWarning:
> 
> Path marker sizes support is limited and may not display as expected

The output plot:
![screen shot 2016-10-03 at 2 32 59 pm](https://cloud.githubusercontent.com/assets/9061708/19054918/61c3066a-8976-11e6-8bab-522f6b1b04fa.png)

**Comment by bryevdv** [comment]
I'm afraid there is not much we can do about this. The actual MPL code is in a third-party library that is no longer maintained. We do not have the resources to put into taking over that project. In any case MPL support is only partial. For something as simple as this you are far better off using native Bokeh APIs instead of MPL compat.

**Comment by jolespin** [comment]
No worries, that makes perfect sense.  I was surprised that was even a functionality to begin with b/c of how complicated it could get.  I originally looked into it b/c I was trying to do something like ```sp = bokeh.charts.Scatter(data=DF_data, x="t", y=["sine","cosine"])``` so I could plot 2 "series" on same plot.  Is it possible to do this from `bokeh.charts.Scatter`? Or can this only be achieved via `bokeh.plotting`?

**Comment by bryevdv** [comment]
`Scatter` works best with "tidy" data frames, so if you had a "type" column that had values "sine" or "cosine", you could do: `Scatter(df, "t", "y", color="type")`

**Comment by jolespin** [comment]
I tried the above method:
![screen shot 2016-10-03 at 3 13 07 pm](https://cloud.githubusercontent.com/assets/9061708/19056095/168c40a2-897c-11e6-9555-66ab8ca4bb38.png)


```
sc = bokeh.charts.Scatter(data=DF_melt, x="t", y="values", color="data_type")
bokek.io.show(sc)
```

but got the following ```ValueError``` which is essentially all of of my `y` values:

> ValueError: expected an element of either List(String) or List(Int), got [0.0, 0.06346651825433926, 0.12693303650867852, 0.1903995547630178, 0.25386607301735703, 0.3173325912716963, 0.3807991095260356, 0.4442656277803748, 0.5077321460347141, 0.5711986642890533, 0.6346651825433925, 0.6981317007977318, 0.7615982190520711, 0.8250647373064104, 0.8885312555607496, 0.9519977738150889, 1.0154642920694281, 1.0789308103237674, 1.1423973285781066, 1.2058638468324459, 1.269330365086785, 1.3327968833411243, 1.3962634015954636, 1.4597299198498028, 1.5231964381041423, 1.5866629563584815, 1.6501294746128208, 1.71359599286716, 1.7770625111214993, 1.8405290293758385, 1.9039955476301778, 1.967462065884517, 2.0309285841388562, 2.0943951023931957,

**Comment by jolespin** [comment]
One more quick question, `bokeh.charts.Scatter` doesn't take `alpha` keyword.  I tried `background_fill_alpha` and `border_fill_alpha` but nothing changed.  If I;m going to be changing the alphas, should I just stick w/ `bokeh.plotting`?

**Comment by bryevdv** [comment]
@jolespin yes if you need to control the alpha then currently you should definitely stick with `bokeh.plotting`. It would not be too difficult (I don't think) to add support for an alpha setting on some charts, but it can't be a high priority at the moment given all that there is to do. If you are interested in looking into it, I an point you in the right direction. 

I should also mention that there are some improvements coming in `0.12.3` that make mapping colors and alphas directly to data columns much easier with `bokeh.plotting`. I don't have time to elaborate this morning but you can check recent PRs, or await the release announcement. 

I am going to close this issue, since the discussion has turned to support type questions. Those are more properly directed to the mailing list: https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh
