### ISSUE TITLE
box select does not work with vbar but tap tool does 

### ISSUE THREAD

**Issue by baldr1k** [bokeh/bokeh#5298]
The following code illustrates the issue when run with bokeh serve

```
from bokeh.models import ColumnDataSource
from bokeh.plotting import curdoc, figure

import logging
logger = logging.getLogger('test')

def on_selection_change(attr, old, new):
    logger.info('selection change')

source = ColumnDataSource(data=dict(bins=[0, 1, 2], counts=[1, 10, 20]))
doc = curdoc()

p = figure(tools="box_select,tap")
source.on_change('selected', on_selection_change)

b = p.vbar(x = 'bins', bottom=0, width=1, top='counts' , source=source)
# c = p.circle(x='bins', y='counts', source=source)

doc.add_root(p)
```

Using vbar tap tool fires selection change but box select does not.
Using circle both tools fire selection change.

Python version      :  3.5.1 |Continuum Analytics, Inc.| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)]
IPython version     :  5.1.0
Bokeh version       :  0.12.2

**Comment by bryevdv** [comment]
This is because "rect" hit testing is not implemented on `VBar` and `HBar`. It's never been quite clear to me what the policy would be. I suppose if the selection box intersects the bar in any way that counts? or does it have to enclose the bar completely? 

In any case, what would be needed would be to add a `_hit_rect` method to `vbar.coffee` and `hbar.coffee`. It would be analogous to the `_hit_point` method already there:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/glyphs/vbar.coffee#L70-L79

Except instead of using the index to search for "point" hits, it would need to compute it the selection geometry rectangles hit the bars. This would make an excellent PR for a new contributor (since it is very self-contained). If you'd like to work on it, I'm happy to answer any questions. It's very likely that you would be able to get to it before anyone on the core team would be able to turn to it.

**Comment by baldr1k** [comment]
Either policy would work for me. I see it as a 1d selection though, if the box select had worked I'd have used the dimension attribute of the tool to only select in width.

I am time poor but will have a look at it as this feature would enhance my project.
The main issue is I am completely ignorant of coffee script/JS languages and how they integrate into bokeh.

Would finding and editing bar.coffee on my local installation work for testing, or is there some toolchain/build process required?

**Comment by birdsarah** [comment]
>  It's never been quite clear to me what the policy would be. I suppose if the selection box intersects the bar in any way that counts? or does it have to enclose the bar completely? 

I would suggest it's "overlaps the centroid" because that's how it works for circles and other markers. I think that's also a nice compromise between not inadvertently selecting something and not requiring people to select all the way to the edge.

**Comment by sigurdurb** [comment]
This is also a problem with line. Like in the stocks example that person has to make circles in same points as the line goes through for the xbox_select to work. I would like to see box selecting on lines work like that without the need for a circle; So only color the line on the coordinates it is being selected. Could that be implemented or is there any reason why it is not, maybe box_select could have some modes to define either behavior @birdsarah ?

**Comment by bryevdv** [comment]
@sigurdurb Selection was not implemented on lines because until recently, lines would draw themselves very poorly in the presence of selections (they would just connect "missing" areas") @clairetang6 improved this situation in master, so extending selection to lines should now be reasonable and fairly easy. However, please make a separate issue so that we can prioritize things independently.
