### ISSUE TITLE
Use our own bokeh channel and avoid using conda-forge

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#5299]
Using conda-forge channel has raised some issue with timing on TravisCI.
We should avoid to add conda-forge and only get the packages we need from our own bokeh channel.
Previous ref comment: https://github.com/bokeh/bokeh/issues/5105#issuecomment-250470393

@bokeh/dev

**Comment by bryevdv** [comment]
Backdrop: conda-forge dependencies seem much looser, and using condo-forge pulls in way more packages than using the default channel. I believe this is part of the recent slowdown (the majority of the time increase is inside `travis_install`) There was general agreement on Flowdock to return to default repo + bokeh channel only.

**Comment by birdsarah** [comment]
FWIW, the addition of conda-forge was so that we don't have to maintain our own testing packages (which aren't available on defaults).

Before making the switch back, we need to make sure we can install all the pytest/pytest-selenium/selenium things at the versions that are available on conda-forge.

**Comment by birdsarah** [comment]
Updated ^^^
