### ISSUE TITLE
Multiple callbacks to one widget

### ISSUE THREAD

**Issue by mmamsalg** [bokeh/bokeh#5334]
Hi, 

I find myself trying to plug a callback to multiple DataTable objects. Is the widget to object relationship currently one to one ? If not can you please provide me with an example ? Here's a snippet of the code: 
There are two dropdowns, the zone_menu and the fuel_menu. They have callbacks to different tables, through the class instantiated as 'web' - it's a rather big object, let's just paste this for now: 

web = WebX()
...   ... 
```
zone_menu  = web.zone_menu
fuel_menu  = web.fuel_menu
msg_filter = web.msg_filter
csv_button = web.csv_button
  ```
I would like that the fuel_menu.callback pushed changes onto both the web.unit_table and web.fuel_table through the unit_table_callback and the fuel_table_callback through something of an add function: 
```
fuel_menu.callback = web.unit_table_callback
fuel_menu.add_callback = web.fuel_table_callback
```
Is this possible ?

**Comment by bryevdv** [comment]
Hi @mmamsalg the Issue tracker is not the place for general support questions, we reserve it for feature requests and bug reports, in order to try and keep it even remotely manageable. For community provided support, please go to the [public Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh)
