### ISSUE TITLE
Examples for ColorBar or ColorMappers?

### ISSUE THREAD

**Issue by TonyPlaysGuitar** [bokeh/bokeh#5343]
I'm not really sure if those are bugs or just me not understanding the logic behind the color mappers, but the only thing I was able to make work is the LinearColorMapper by copying your example from the 12.2 release.

The moment I try to replace
`color_mapper = LinearColorMapper(palette=RdYlGn11, low=0, high=100)`
with
`color_mapper = ContinuousColorMapper(low_color='firebrick',high_color='navy', low=0, high=100)`
I get a message about broken javascript:

> Javascript error adding output!
Error: Module `ContinuousColorMapper' does not exists. The problem may be two fold. Either a model was requested that's available in an extra bundle, e.g. a widget, or a custom model was requested, but it wasn't registered before first usage.
See your browser Javascript console for more details.

Some related questions include
* what's the extend of field transformations? Can I use a custom/lambda functions?
* description of mappers has a warning that low/high values must be set in order for colorbar ticks to show, but if `low>high`, no ticks will be shown
* can a colorbar be drawn outside, kind of like you do with legends? Doing that now
`p.add_layout(color_bar,'right')`
does not produce anything good

**Comment by bryevdv** [comment]
Hi, `ContinuousColorMapper` is an internal base class. There is no reason to ever try to instantiate it directly. There are `LinearColorMapper` and `LogColorMapper` subclasses that you might want. 

As for an example of colorbars outside plot areas, as well as using `low_color` and `high_color`, please see:

https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/color_data_map.py

which looks like: 

<img width="827" alt="screen shot 2016-10-11 at 10 15 52 pm" src="https://cloud.githubusercontent.com/assets/1078448/19295193/dafd7480-9000-11e6-84e0-414c60cc8f37.png">

Lastly, the high and low for coordinate mappers is not related to the `high_color` or `low_color` of coordinate mappers. 

Closing this, since it turns out more to be a support type question (please continue on the mailing list)
