### ISSUE TITLE
Custom models distribution without compiler on the server side

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [bokeh/bokeh#5345]
Running Bokeh in the cloud environment (like Google App Engine) gives this error:

```
An internal error occurred:
node.js is needed to allow compilation of custom models ("conda install -c bokeh nodejs" or follow https://nodejs.org/en/download/)
```

The setup, it is working fine on my local computer, but on cloud version looks like in the latest version 0.12.3. some extra dependency is added to node.js that was not in the previous version.

It will be nice if the error message is giving more hints about which custom model is creating all the issues. In my case I have several Bokeh plots (and some of them have a custom model like https://github.com/bokeh/bokeh/issues/4690#issuecomment-229694803).

This compilation problem creates challenges for distribution when the package is only managed by pip install -r requirements.txt and no option to add conda install -c bokeh nodejs.

The dependency is very subtle and not well documented.

**Comment by bryevdv** [comment]
The change to pre-compilation on the python was necessary in order to allow custom extensions to inherit from other custom extensions. This is needed both for future planned facilities outside the core library, and also was very widely asked for in a community discussion. We did mention in the release migration notes that `bokeh-compiler` had been removed. However, we probably could have elaborated on that more. Bokeh is a large project with a small team and we are often working completely at the limits of our available human resource capabilities, so things sometimes slip through, despite our best intentions. However, I will try to make a point to expand our documentation to be more explicit about the new requirement for nodejs when using custom extensions. 

@mattpap would it be possible to "pre-pre-compile" custom extensions? That is, could we have some way to create a python module on one system with node, that could be transferred and imported for use on another system without node?

**Comment by canavandl** [comment]
I agree that @bryevdv 's suggestion would be nice. Yesterday I wrote an extension coffeescript and ran it locally, then grepped the output html document for the compiled JS and copied that into a new __implementation__ for production. It could image something like:

```
from bokeh.util.compiler import Compile

js_implementation = Compile(MyCustomModel)
```

**Comment by bryevdv** [comment]
@canavandl I might even suggest a `bokeh` command line tool for this:

```
bokeh compile extension_source.py -o extension.py
```
I can't say I'd be thrilled about this, but it would provide some kind of release valve for anyone that wan't to use extensions but can't install node on a server or whatever.

**Comment by mrocklin** [comment]
Should this problem go away if I include javascript code rather than coffeescript?

**Comment by bryevdv** [comment]
I would expect it to, but I have not had a chance to try.

**Comment by mrocklin** [comment]
At first glance this does not appear to be the case.  Anything special I should do to inform Bokeh that the text I'm sending in JavaScript rather than CoffeeScript?

**Comment by bryevdv** [comment]
possibly yes, try 
```
__implementation__ = JavaScript(js_code)
```
where `JavaScript` is in `bokeh.util.compiler`

**Comment by mrocklin** [comment]
The problem persists even with this change.

**Comment by bryevdv** [comment]
Well, then I was wrong, and more investigation will be required.

ping @mattpap

**Comment by mrocklin** [comment]
Looking at the implementation in `bokeh/util/compiler.py` it looks like Bokeh doesn't currently check on the language until *after* it has checked for the presence of nodejs.

**Comment by bryevdv** [comment]
nodejs may be needed to resolve the import/require statements in any case. We will have to get some feedback from @mattpap

**Comment by mattpap** [comment]
The choice of language doesn't make any difference when it comes to whether nodejs is needed or not. Even with plain JavaScript we have to resolve dependencies (`require()`  and `import/export`) and those dependencies may not be JavaScript, but whatever we support (CSS, Less, CoffeeScript, Eco, TypeScript). To get a sane implementation we have to go all the way and support everything we do support, especially when it comes to custom models. With CustomJS we default to plain JavaScript and no dependency resolution for backwards compatibility and because CustomJS is usually simple code.

**Comment by mattpap** [comment]
This issue is blocked on #5315. When this is fully resolved, bokeh will store either final bundle or individual compiled sources, and check SHA1 signatures to decide if recompilation is needed or not. This way this issue will boil down to a packaging problem. We have to address this anyway, because currently custom model generation slows down bokeh considerably, because they are recomputed every time resources are requested.

**Comment by krinkere** [comment]
When trying to deploy my app on heroku, i ran into same issue... hope for this bug to be fixed soon

**Comment by bryevdv** [comment]
We cache extensions after first use but still do need an option to distribute in cases where to other users or systems where nodejs is not present. pre-compiled extensions should be locked to the version they were created for, though.

**Comment by philippjfr** [comment]
What would it take to make this happen? I'd be interested on working on this since we have a number of custom models now and compiling them each time is pretty slow.

**Comment by jbednar** [comment]
>it would provide some kind of release valve for anyone that wan't to use extensions but can't install node on a server or whatever.

It seems like supporting precompiling would help not just in cases where node can't be installed, but in any cases where custom models are in heavy use, which is becoming a limiting factor for our work.  I'm happy to volunteer Philipp for this, as he's the one most directly affected by the slow current approach. :-)  But it may be something most easily addressable by another Bokeh dev.

**Comment by bryevdv** [comment]
With #8336 there are now some dev API hooks available to override model caching. These are stable API, anyone can use them now. But the plan is to get some feedback from real world usage with these, before diving into file formats and locations that could support a more public capability.  (Further work will go under new issues)

**Comment by philippjfr** [comment]
For reference [here](https://github.com/pyviz/panel/pull/103) is a PR on the ``panel`` library I have been developing which makes use of this hook and the functions in the ``bokeh.util.compiler`` module to compile and save the cached implementation during a package build and load them when bokeh attempts to compile the models.
