### ISSUE TITLE
No way to cleanup used memory

### ISSUE THREAD

**Issue by sashabaranov** [bokeh/bokeh#5355]
When you embed bokeh plots by manually inserting div and script you get from `components` there is no obvious way to clean up the memory when you no longer need plots. This results into memory leaking.

Example code can be found here: https://github.com/sashabaranov/bokeh-leak-example

Also this issue on stackoverflow: http://stackoverflow.com/questions/39895717/remove-bokeh-plot-without-leaking-memory

```
% bokeh info
Python version      :  2.7.12 (default, Sep 30 2016, 15:42:31)
IPython version     :  Not installed
Bokeh version       :  0.12.3
BokehJS static path :  /Users/sashab1/.virtualenvs/bokeh-leak-example/lib/python2.7/site-packages/bokeh/server/static
```

**Comment by bryevdv** [comment]
@sashabaranov can you elaborate? Memory leaking in the server or in the browser?

**Comment by sashabaranov** [comment]
@bryevdv In browser. (Sorry for not mentioning)

**Comment by sashabaranov** [comment]
Hey @bryevdv, is it possible to increase priority for this? We are using bokeh in monitoring service and using page-reload as memory cleanup is a real bummer.

**Comment by bryevdv** [comment]
@sashabaranov are you able to help out? Offering experience and assistance is the 100% very best way to increase priority on this. Long story short: I am actually not a JS expert by any stretch, and I don't really know where to begin (this is why python side memory issues have been able to be dealt wit already)

**Comment by bryevdv** [comment]
Well that is something I can and am happy to help with, the first step would be to get BokehJS building locally: 

https://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html

**Comment by sashabaranov** [comment]
I've set up development environment and continued playing with [example](https://github.com/sashabaranov/bokeh-leak-example) above.

My current routine to clean up all plots data is:

```javascript
function cleanup() {
    for (doc_ix in Bokeh.documents) {
        var doc = Bokeh.documents[doc_ix];
        for (mdl_ix in doc._all_models) {
            Bokeh.documents[doc_ix]._all_models[mdl_ix].destroy();
        }
        Bokeh.documents[doc_ix]._roots[0].destroy();
        delete Bokeh.documents[doc_ix]._roots[0];
        delete Bokeh.documents[doc_ix];
    }

    for (prop in Bokeh.index) {
        if(Bokeh.index.hasOwnProperty(prop)) {
            console.log("Removing bokeh plot: " + prop);
            if (Bokeh.index[prop]) {
                delete Bokeh.index[prop];
            }
        }
    }
    $(".bk-root").remove();
}
```

However, there is still some data present. I've used Firefox memory tool and it says that there are some objects somehow connected with Signalling part of Bokeh. Do  you have any clue how to reset all signalling state?

**Comment by bryevdv** [comment]
cc @mattpap

**Comment by mattpap** [comment]
> (...) it says that there are some objects somehow connected with Signalling part of Bokeh.

Signaling API should be self cleaning due to usage of weak maps. Though it's possible something went wrong during implementation.

**Comment by sashabaranov** [comment]
@mattpap does the `cleanup()` mentioned above make sense to you? Is there something else to clean up? Is `.destroy()`intended for deleting object or for something else?

**Comment by sashabaranov** [comment]
@mattpap ping

**Comment by mattpap** [comment]
This is a good starting point, especially as a temporary measure before proper APIs are implemented in bokehjs. One important thing is missing, there should be `Bokeh.index[prop].remove()` to destroy root views and all their children recursively (this is partially covered by `$(".bk-root").remove()`). In general, we will need review object life cycle management in bokehjs, because there are a few places where we completely ignore proper memory management (e.g. `Document.clear()` exists, but it doesn't call `destroy()` method on models at any point).

**Comment by dracorpg** [comment]
Hello all,

As developer of a product that tends to create and destroy quite a bit of Bokeh plots in its web UI (and thus currently requires a periodic hard refresh in order not to explode after some time) I'd like to join in the conversation :)
We did investigate the matter several months ago without great success - definitely not a JS expert myself neither - but now want to spend some time actually trying to help fix this upstream for good. Bokeh is a really nice project and I think it deserves being made truly production-ready!

First, the memory leak is very easy to reproduce using Jupyter Notebook : just run again and again a cell that show()s a figure with many (say 100k) points and memory consumption will skyrocket (durably - no forced GC will do good).

Places where we spotted global references that might be causes of resource leaking:
1. Bokeh.index, [a map from root-level model IDs to their view object](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/base.ts#L58-L62), which includes a reference to the containing DOM div element => index entries left behind keep the figure's entire DOM sub-tree from being GC'd
2. Bokeh.documents, [an array of all documents that were ever instantiated](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/document.ts#L193-L216) => document entries left behind as-is keep the figure's entire model tree from being GC'd
3. **document** and **window** global objects have several event listeners registered onto them by bokehjs (and maybe some libs like hammerjs)

From our experience, calling .clear() on a document [deletes its root model hence the entire model tree](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/document.ts#L375) & emits RootRemovedEvent which triggers [add_document_standalone.unrender_model(), removing its entry from Bokeh.index](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/embed/standalone.ts#L15-L60).

So calling doc.clear() solves point 1 and minimizes the memory leaked by point 2 (a document by itself does not take up much room without its model tree). Then manually removing the entry from Bokeh.documents should solve point 2 completely. This is what we currently do to clean up a document after the div containing its view is removed from DOM:
```
    doc.clear();
    const i = Bokeh.documents.indexOf(doc);
    if (i > -1) {
      Bokeh.documents.splice(i, 1);
    }
```
This is more selective than Sasha's code, but apart from being a little bit less "nuclear option" I believe the end-results to be identical.

So our target culprit for continued leaking is now point 3. I shall come back to you soon with more investigation results on that front.

**Comment by sashabaranov** [comment]
Glad @dracorpg joined :)

Firefox has some memory tooling and I've made snapshots in case they might be helpful to understand this issue.

Using [example](https://github.com/sashabaranov/bokeh-leak-example) from above I've produced three page snapshots:

1. Empty page
2. Page with 10 plots
3. Page after cleanup (waited some time for memory footprint to drop).

Those are attached in  [snapshots.zip](https://github.com/bokeh/bokeh/files/2410105/snapshots.zip) and here is an [instruction](https://developer.mozilla.org/en-US/docs/Tools/Memory/Basic_operations) on how to load them.

**Comment by dracorpg** [comment]
As promised, here are the event listeners that each Bokeh view registers on global objects and never un-registers afterwards:
1. "pointerup", "pointermove" & "pointercancel" on **window** via Hammer.js in [UIEvents._configure_hammerjs()](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/core/ui_events.ts#L79)
2. "keyup" and "keydown" on **document** also in [UIEvents._configure_hammerjs()](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/core/ui_events.ts#L119-L120) (although it has nothing to do with hammerjs)
3. "resize" on **window** in [LayoutDOMView.connect_signals()](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/layouts/layout_dom.ts#L245)

The event listener handlers registered by bokehjs itself are anonymous functions to which no other reference is kept, so they become effectively impossible to remove afterwards since removeEventListener() requires the handler reference to be passed back.
In contrast, Hammer.js always registers as handler a function to which it has a reference, and so should be able to remove them cleanly (seems to me the destroy() method should properly un-register the listeners, despite the docstring saying otherwise).

Seems to me the solution here would involve adding a few destroy methods & non-anonymous handlers to properly clean up all these event listeners... and hope there are not too many leak sources left :)

@sashabaranov Firefox 62 does not want to load your memory snasphots - I'm able to reproduce the leak easily anyway, but all I could deduct from both F12 "memory" tab and about:memory is that the increasing bloat definitely comes from JS Object, Array & ArrayBuffer. I'm by no means a frontend developer, so this is all a bit over my head really :)

**Comment by bryevdv** [comment]
@dracorpg @sashabaranov I just want to thank you very much for digging into this and running down these details, your experience is extremely valuable and appreciated

**Comment by sashabaranov** [comment]
@dracorpg can't express how badly do I want your dev build! :)

**Comment by dracorpg** [comment]
Okay, so first I have to tell that the tinkering I mentioned earlier was done by hacking directly the output bokeh.js. I have now hastily translated this into the TypeScript source, but haven't got to build it yet (bokeh does not want to build with node.js 10.x, which is what I have installed and use for my product) so I can't confirm it works. Actually reading it again, I am pretty sure it will NOT transpile in its current state because I acted like I was writing Python or JS, but TypeScript is much stricter about dynamically defining attributes :)

This disclaimer having been put forward, if you guys want to have a look at the kind of changes required (actually quite little) here they are for now: https://github.com/dracorpg/bokeh/commit/2cee845a0680e3611e219cff282c0ec72e211844

**Comment by bryevdv** [comment]
@dracorpg have you had a chance to go through this:
 
https://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html#devguide-setup 

?

**Comment by dracorpg** [comment]
@bryevdv yeah, actually the build does fine... except that bokehjs' *package.json* requires node >8.8 <9 so I would have to install an older version of node which probably won't play nice alongside the version 10 I have currently installed (and need day-to-day). Haven't bothered doing that yet... in the meantime I hacked the upper version limit out of *package.json* and *node make build* seems happy to try and transpile what I'm giving it.

Getting my custom bokeh[.min].js to load in the notebook without installing the full-blown development version of the Bokeh Python package was a bit of a pain, so instead of trying to trick it into loading just bokeh.min.js from somewhere else on my disk I ended putting my ipynb right next to my local git version of bokeh so that *import bokeh* would load it. Works fine to load the altered js with 'inline' and 'relative' resource loading modes.

Now I'm just pissed off because proper context capture of 'this' with addEventListener basically requires an intermediate anonymous function/closure (what bokehjs does currently) but being able to call removeEventListener requires that a reference is kept to this function created on-the-fly, which TS won't just let me store as a runtime-declared attribute. Here I am trying to find the least un-elegant way out of this. Man, isn't Python simpler...

Anyway it's getting late here, thanks guys for the support but I guess the pull request will have to wait for me to learn some real frontend development skills tomorrow.

**Comment by bryevdv** [comment]
I going to go ahead and lose this specific issue for now. There will be a dev build with #8278 available later today. I think there is more work to do in the future in other areas but those will be best served with new focused issues. (If there is any ongoing issue with the fix specific to #8278 we can re-open of course)

**Comment by sashabaranov** [comment]
I have hard time reproducing cleanup, what are you using exactly @dracorpg ?

```js
function cleanup() {
    for (prop in Bokeh.index) {
        if(Bokeh.index.hasOwnProperty(prop)) {
            console.log("Removing bokeh plot: " + prop);
            Bokeh.index[prop].remove();
        }
    }
}
```

**Comment by sbancal** [comment]
I prepared a [Codepen](https://codepen.io/sbancal/pen/LYzgGgW) to illustrate the bug I get ... but it finally proves the problem is somewhere else because I don't get these Bokeh plots remaining in that demo.

**Comment by sashabaranov** [comment]
@sbancal this tool may help you: https://github.com/nolanlawson/fuite
