### ISSUE TITLE
Plot legend shows value instead of text specified

### ISSUE THREAD

**Issue by Rubyj** [bokeh/bokeh#5365]
On a Plot legend (bokeh 0.12.3), if the name for the legend is the same as the name for the column in the data source, the value will be displayed int he legend instead of the name. Is this expected behavior?

Example:

```
from bokeh import plotting
from bokeh.models import ColumnDataSource, Range1d
from bokeh.io import curdoc, show
import pandas as pd

data = [{"right1": 10, "right2": 14, "right3": 17,
         "right4": 22, "right5": 37, "right6": 44,
         "right7": 49, "right8": 59}]

source = pd.DataFrame(data)
source = ColumnDataSource(source)

fig = plotting.figure(width=1200, height=900)

fig.hbar(y=1, right="right1", left=0, height=0.5, fill_color="blue", source=source, legend="right1")
fig.hbar(y=1, left="right1", right="right2", height=0.5, fill_color="green",
         line_color="black", source=source, legend="right2")
fig.hbar(y=1, left="right2", right="right3", height=0.5, fill_color="yellow",
         line_color="black", source=source, legend="right3")
fig.hbar(y=1, left="right3", right="right4", height=0.5, fill_color="orange",
         line_color="black", source=source, legend="right4")
fig.hbar(
    y=1, left="right4", right="right5", height=0.5, fill_color="red", line_color="black", source=source,
    legend="right 5")
fig.hbar(
    y=1, left="right5", right="right6", height=0.5, fill_color="purple", line_color="black", source=source,
    legend="right 6")
fig.hbar(y=1, left="right6", right="right7", height=0.5,
         fill_color="grey", line_color="black", source=source, legend="7.")
fig.hbar(
    y=1, left="right7", right="right8", height=0.5, color="black", line_color="black", source=source, legend="*8.",
    fill_alpha=.12, line_alpha=.12)

curdoc().add_root(fig)

show(fig)
```

As you can see, in the legend for the first 4 hbar(s), the value for that hbar is displayed instead of the text specified in `legend=`

**Comment by bryevdv** [comment]
@Rubyj Yes, this is a new feature that allows legends to be automatically  generated by grouping values in a column data source for a single glyph. In conjunction with a categorical color mapper this can often greatly reduce code needed. If you don't want this behaviour, there are two options:

* change the column names to something else, so as not to match the `legend` string value
* be explicit that you don't want the legend to look at field names: i.e pass`legend=dict(value="foo")` to the glyph function 

ping @birdsarah this is the second time today this question has come up. Perhaps we need better documentation support

**Comment by Rubyj** [comment]
@bryevdv Great! Thank you for this explanation. It was probably unclear to me because the functionality has recently changed.

**Comment by bryevdv** [comment]
@Rubyj No, I did not do a good job calling this change out in the migration notes. I had assumed that most names currently passed as values for `legend` would not match column name, but that seems not to be a safe assumption.

**Comment by birdsarah** [comment]
> @birdsarah this is the second time today this question has come up. Perhaps we need better documentation support

Agreed and I think this is coming up because of documentation of `figure` automagic. I feel that we don't have one place to document it all. The user guide covers different aspects, but the reference has no clear place to catalog all the assumptions and defaults that figure does for you.

I think http://bokeh.pydata.org/en/latest/docs/reference/plotting.html is impenetrably long. 

Maybe it's just a case of improving the `figure` docstring substantially from the 1 line that there currently is.

**Comment by birdsarah** [comment]
The user guide currently says: http://bokeh.pydata.org/en/latest/docs/user_guide/annotations.html#legends

> It is also possible to create multiple legend items for the same glyph when if needed by passing a legend that is the column of the column data source.
> 
> If you do not want this automatic behavior, you can use the field() or value() functions from bokeh.core.properties, to be explicit about your intentions. See examples/app/gapminder/main.py for an example. Alternatively, you can not specify any legend argument, and manually build a Legend by hand. You can see an example of this in examples/models/legends.py:

**Comment by bryevdv** [comment]
@birdsarah in retrospect it might have been better not to make anything try to "autodetect", and instead just required `label=field("foo")` to be used to ask for the new functionality explicitly?

**Comment by birdsarah** [comment]
I think it's entirely inline with our current API of how we handle column data source columns `(x="col1", y="col2", legend="col3")`

There is of course a question of how you get from A to B. In a post 1.0 world I'd be in favor of changing default behavior slowly over multiple releases, but we're not there yet and there's a lot to do.

**Comment by dhirschfeld** [comment]
I don't want to come across as overly critical as I really appreciate bokeh and the thought  and effort you all put into developing it... but I really think this is a *terrible* change.

It's completely unintuitive (at least to me) and worse - the behaviour changes  depending on whether or not your legend text happens to line up with the column data source labels. I think bokeh is trying to be far too smart/magic here.

Even if there are some use-cases where this would be a desirable feature, I can't believe that the benefit would outweigh breaking what I would consider the vastly more common case - that being if the user supplies a string label for the legend that means they want that text to be the legend text, not to have it looked up in the ColumnDataSource.

In all the examples I can see on the website to specify the legend text you just pass the string you want. With this change that widely advertised interface will change/break if you happen to pass in a ColumnDataSource with the same column names.
![image](https://cloud.githubusercontent.com/assets/881019/22137874/66c01de8-df29-11e6-81bd-f059b1691f3d.png)

**Comment by dhirschfeld** [comment]
Example of how this has broken all my plots:
![image](https://cloud.githubusercontent.com/assets/881019/22137965/ef5b9dc6-df29-11e6-91ed-d454dd5f128a.png)

There is only a single line on the plot, it can't make *any* sense to have a thousand labels in the legend!

**Comment by bryevdv** [comment]
On a phone, but you want 

    from bokeh.properties import value
    legend=value("Sunset")

Which explicitly states that it should be interpreted as a fixed value, not a field name. 

Bryan

**Comment by bryevdv** [comment]
FWIW this is consistent with the way string `DataSpecs` have been handled for years, and I would say suffers from the same fundamental issue, namely that data values and column names are both strings. For other data types we can infer intent unambiguously. But defaulting to "column interpretation" is clearly the right choice for glyph properties (otherwise `field(...)` would have to be used *everywhere* all the time.) In the interests of consistency and having the behavior be identical as much as possible, I think that makes it the right choice here, too. 

Given that there is an easy way to override the auto-grouping behavior (use `value(...)`) and given that this kind of feature was both requested and also, in my estimation, generally well-received, my inclination is to suggest that the solution is:

* additional examples and documentation
* possibly a validation warning if the number of legends would be "large" e.g. above 10 (or whatever) with a message on exactly how to use `value`

Is there anything else to discuss? I am loathe to make any breaking changes to this now.  ping @birdsarah

**Comment by birdsarah** [comment]
> additional examples and documentation
> possibly a validation warning if the number of legends would be "large" e.g. above 10 (or whatever) with a message on exactly how to use value

I think those are both great ideas.

I 100% agree that having the behavior be consistent with other data columns is the right approach. 

@dhirschfeld I feel your pain and I'm sorry we broke your plot. I don't think the error is the new feature as much as it was having inconsistent behavior in the first place.

@bryevdv I also think that Lines (and by extension Patches) are going to be a gotcha here because they interpret the ColumnDataSource differently than all our other glyphs and I think that's compounding our problem.

**Comment by bryevdv** [comment]
> I also think that Lines (and by extension Patches) are going to be a gotcha here because they interpret the ColumnDataSource differently than all our other glyphs and I think that's compounding our problem.

That's absolutely a good point and I think they can and should be special-cased in the glyph methods

**Comment by dhirschfeld** [comment]
Thanks @bryevdv - good to know there's a way to do it, however I think the case of wanting to specify the text rather than the column to look up is so much more common that the esoteric syntax should be used for the latter case - i.e. if you actually *do* want to specify a column you should do that explicitly with:
```python
legend=field("column_name")
```

Maybe this is a case where consistency for its own sake leads to a  worse user experience. Of course, my opinion is coloured by the fact that I just can't see a case where I would actually want a column lookup. Was there a PR with some examples where this change was discussed so I can try to get a better handle on the intended use-case?

The common case (at least in my usage) is having a DataFrame with each column representing a line I want to plot with the names (legend text) being given by the column labels. Without the new `value('...')` syntax this now gives crazy and obviously wrong results.
 
If this change is here to stay I'd suggest that in the documentation all instances of explicitly specifying the legend text be changed to use the `value('...')` syntax so that it's documented/discoverable. Given that not using the `value('...')` syntax may give different results dependent on the column names, specifying legend text with a simple string should probably be discouraged.

**Comment by foobarbecue** [comment]
The way to make this work is now:

    from bokeh.core.properties import value
    legend=value("Sunset")

because bokeh.properties has become bokeh.core.properties .

I have to say, I'm a new bokeh user and this legend thing was a major speedbump that cost me about an hour. Couldn't find the answer until I came across it here.

**Comment by willigott** [comment]
@foobarbecue: Thanks a lot for this; your workaround works perfectly fine! Just ran into the same issue and your answer saved me a lot of time.

**Comment by bryevdv** [comment]
After tinkering with the reference PR I have decided to take no action. Apart from the performance concern of validating this, there is no good way to silence the warning in cases where the warning fires, but a large legend *is* intended. We have since this issue was made increased the documentation support around using `value`. Perhaps in the 2.x timeframe we can consider changing the behavior in some breaking way that avoids this case while still leaving grouped legends simple to achieve.
