### ISSUE TITLE
LinearInterpolator does not work correctly

### ISSUE THREAD

**Issue by semcogli** [bokeh/bokeh#5370]
I am on bokeh 0.12.3 and just tried to replicated the youtube tutorial (https://www.youtube.com/watch?v=9FlUFLmaWvY) using gapmingder data set. However, after following command:

size_mapper=LinearInterpolator(
x=[data.population.min(), data.population.max()],
y=[5,50]
)

China was completely missing on my Bokeh plot. After some fail and trial, I found that I had to change to " data.population.max()+1" to get China back. I don't think it is supposed to work like that. Correct me if I am wrong. 

BTW, the gapminder population data I got was different from the tutorial. The population data ranged from 1952 to 2007. Min and max values were (60011, 1318683096). Thanks.

Add bokeh info:

Python version      :  2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) 
IPython version     :  5.1.0
Bokeh version       :  0.12.3
BokehJS static path :  /home/da/anaconda2/lib/python2.7/site-packages/bokeh/server/static

**Comment by bryevdv** [comment]
Can you post the entire code you tried? It is difficult to diagnose without a complete, minimal, runnable example to reproduce whatever problem you are seeing.

**Comment by semcogli** [comment]
Here you are.  The final figure supposed to have two big circles. But there was only one (India). China only showed up after I change the max to 1+.   Thanks.
--------------------------------
import pandas as pd
import numpy as np
from bokeh.plotting import figure, show, output_notebook
from bokeh.models import NumeralTickFormatter
from bokeh.models import ColumnDataSource, HoverTool

output_notebook()

data=pd.read_csv('./data/gpm2.csv', index_col='year')
print data.dtypes
data.head()

PLOT_OPTS =  dict(
    height=400,
    x_axis_type='log',
    x_range=(100,100000),
    y_range=(0,100)
)

source =  ColumnDataSource(dict(
        x = data.loc[2007].gdpPercap,
        y = data.loc[2007].lifeExp,
        country = data.loc[2007].country,
        population=data.loc[2007].population,
        continent=data.loc[2007].continent
    ))

from bokeh.models import LinearInterpolator
size_mapper=LinearInterpolator(
x=[data.population.min(), data.population.max()],
y=[5,50]
)

p=figure(tools=[HoverTool(tooltips=[('country','@country'),('population','@population{int}')])],**PLOT_OPTS )

p.circle(
x='x',y='y', size={'field':'population', 'transform': size_mapper},
    alpha=0.6,
    source=source
)
show(p)

**Comment by birdsarah** [comment]
you're also going to need to share the specific csv file you used in order to replicate.

**Comment by birdsarah** [comment]
@bryevdv seems unlikely but I did do that demo in python 3 and am wondering whether there's a python2 thing. But, seems unlikely because just the raw number would be passed down to the JS.....is the number big enough to fall into some int handling problem?

**Comment by semcogli** [comment]
Hi, Sarah

here's the data. BTW, I like your youtube tutorial. Good work : ) 
[gpm2.zip](https://github.com/bokeh/bokeh/files/536394/gpm2.zip)

**Comment by birdsarah** [comment]
This is definitely a bug. Haven't tracked down the root cause, but I've put up a notebook that clearly shows it here: http://nbviewer.jupyter.org/github/birdsarah/bokeh-miscellany/blob/master/gapminder-nc/Linear%20Interpolator.ipynb

Here are two screenshots. The top one uses the +1 trick. Note that in the bottom one (without +1) China just doesn't appear at all - makes me think that it's size has been set to NaN (as opposed to doing a clamp). 

Two things:
1) We should do a clamp
2) Even without the clamp, this should have worked


<img width="400" alt="screen shot 2016-10-18 at 6 53 55 am" src="https://cloud.githubusercontent.com/assets/1796208/19480622/ea4cdb5c-94ff-11e6-919c-5c3972b6e1a2.png">
<img width="400" alt="screen shot 2016-10-18 at 6 53 43 am" src="https://cloud.githubusercontent.com/assets/1796208/19480621/ea4839c6-94ff-11e6-90ed-4c0176107e80.png">

Thanks for the keen eye @semcogli.
