### ISSUE TITLE
DataTable css conflict with bootstrap css

### ISSUE THREAD

**Issue by schlichtanders** [bokeh/bokeh#5398]
thanks for bokeh!
Working with the `DataTable` I found an layout issue when combined with bootstrap css. Please look at this kind of minimal working example:
https://gist.github.com/schlichtanders/897b33daa846d4a08ba6e0f2ee5b2d75
In the python file the html one is constructed using jinja2 and bokeh `components`.
The important flag is `USE_BOOTSTRAP`.

If `USE_BOOTSTRAP=True` then you can see that the header of the table is broken (too small height and bad separator placement).
However if `USE_BOOTSTRAP=False` everything works as expected.
Hence some css classes seem to interact unexpectedly.

I hope the example files can help to track down this issue

Python version      :  2.7.6 (default, Jun 22 2015, 17:58:13) 
IPython version     :  4.0.1
Bokeh version       :  0.12.3

**Comment by mattpap** [comment]
@schaunwheeler, this is because bootstrap sets `* { box-sizing: border-box }`, which apparently is visibly incompatible with SlickGrid and, in fact, should be incompatible with entire bokeh's CSS. What we can do is to set `.bk-root * { box-sizing: content-box }` or switch to the better box model (which I doubt we have resources to do, especially to improve SlickGrid).

**Comment by mattpap** [comment]
On a side note, GitHub is so stupid at times. How hard is to autocomplete participants of an issue when using "mentions" syntax, instead of some random people that, I presume, never participated in this project or at least are not involved in this issue. I presume this yet another variation on this social network nonsense.

**Comment by schlichtanders** [comment]
thanks a lot for the hint!
I just added the line `.bk-root * { box-sizing: content-box }` to my html extra stylesheet and it works

**Comment by bryevdv** [comment]
@schlichtanders this should be fixed in #5421 which will be available in a dev build in the next few days (or you can try building locally) please let us know if there are any continued problems or issues.

**Comment by schlichtanders** [comment]
thanks a lot for developing bokeh!
