### ISSUE TITLE
HBar and VBar need to be added to the User Guide

### ISSUE THREAD

**Issue by hsparra** [bokeh/bokeh#5403]
The HBar and VBar glyphs are missing from the glyph section of the User Guide. They are in the Reference section.

**Comment by ricdea** [comment]
+1 I'd find this really useful. I'm trying to set up a population pyramid but am struggling to understand how HBar works (or if there's a better way to do this).

In particular, is there a way to add legends to HBars?

**Comment by birdsarah** [comment]
@ricdea, there is an hbars example here (including with legend) https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/bar_chart.py 

If you have follow-up questions, please ask on mailing list https://groups.google.com/a/continuum.io/forum/#!forum/bokeh so that this issue can remain on topic.
