### ISSUE TITLE
[ENH] Help widget tuned for end user

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#5430]
Enhancement request:

The "help" widget seems useful, except it takes the user to a developer-oriented documentation page with code examples.  If it were possible to have an end-user-centric page that would be a preferable destination.  Something that concisely described how to interact with a Bokeh plot and how the widgets work.  If it were possible to have a "targeted" page that only described the widgets on a particular plot that would be great.

**Comment by bryevdv** [comment]
I don't really see how we could make a targeted page for only the tools of the plot easily but we could certainly make a less dev-centric page (or perhaps section) that covered all the tools.

**Comment by birdsarah** [comment]
The help url is configurable if that helps?

**Comment by macrocosme** [comment]
Hi everyone, 

I think that my question is somewhat related to this thread. 

Currently, when we click the help tool, the default behaviour opens a new tab and goes to the specified URL set with `HelpTool.redirect`. How could I go around this default and instead of opening a new tab and going to a url, on click, run a bit of javascript to make a popover div show up?
