### ISSUE TITLE
[ENH] Add JS callback for streaming data

### ISSUE THREAD

**Issue by cloud-rocket** [bokeh/bokeh#5435]
This feature request follows [preliminary discussion in groups](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/5kar6-glxf4)

It'd be great to have a per-chart JS callback durng data stream update (new data is about to be displayed), so custom frontend elements (Glyphs) will be updated accordingly. 

Thanks
Meir Tseitlin

**Comment by bryevdv** [comment]
What I'd actually like to possibly is make a general mechanism for adding callbacks to any property change on the JS side, to make it consistent with the python side. Then could do:
```
source.on_change('data', some_python_function) # python callback for the server

source.on_change('data', some_customjs) # js callback for in the browser
```
I'll play around with this first in case it is not too hard to do the general thing, that is preferable. If not, I'm not opposed to adding one more ad-hoc callback on datasource updates for the time being.

**Comment by mattpap** [comment]
> `source.on_change('data', some_customjs)`

Given the fact that we want to make bokehjs' APIs more stable, we should consider having:
```
source.props.data.on_change(some_customjs)
```
(this may be pseudocode, I'm not sure if this way I will get a property descriptor).

**Comment by bryevdv** [comment]
@mattpap I'm fine with that on the JS side, my example above was intended to be python code:
```
callback = CustomJS(code="...")
source.on_change('data', callback)
```
That would result in a callback on the JS side in the rendered document. If there's a better/more idiomatic way for the JS API that is different that's fine with me, but also an orthogonal concern

**Comment by bryevdv** [comment]
In the linked PR this is possible with
```
source.js_on_change('stream', CustomJS(...))
```

please note that this is per-datasource, not per plot. If you need to update plots or glyphs, you can make them available by passing them as `args` to the `CustomJS` callback as always. This is also triggering of the standard `"stream"` event, so there's not any guarantee about what order the callback vs internal BokehJS stream updates happen. If this is a problem, it's conceivable to add a new `"stream-pre"` event or something in a later PR, but we should test out the simple thing first, because it is probably OK as-is.
