### ISSUE TITLE
[ENH] filled / labeled iso contour plots

### ISSUE THREAD

**Issue by s-m-e** [bokeh/bokeh#5440]
I've been pulling my hair out over this last night - **bokeh does not seem to support contour plots** out of the box yet (?). I could not find any documentation or issue on github, so I thought I open one and collect all information I could find so far.

Relevant question at StackOverflow:
http://stackoverflow.com/questions/33533047/how-to-make-a-contour-plot-in-python-using-bokeh-or-other-libs
In a comment, @bryevdv states

>  A high level canned contour plot bokeh.charts.Contour is still an open feature request as of Bokeh 0.10 but will hopefully be in one of the next few releases. It would be a nice project for a new contributor, if you are interested in helping please stop by the Bokeh mailing list or GH tracker.

Possible **workarounds** do exist based on matplotlib's contour functions:
http://stackoverflow.com/a/37633519
or the bokeh-tools written by @asher-pembroke
https://github.com/asher-pembroke/bokeh-tools

In 2015, as far as filled contour plots were concerned, the show stopper seemed to be the fact that bohek did not support polygons with interior holes at the time.
https://groups.google.com/a/continuum.io/forum/#!search/contour/bokeh/IG0LZCG12Oc/rnzUEh7FbIwJ

There is a pull request merged back in 2014 mentioning iso contours, though I do not quite understand what it actually implemented (server side?) and how it can be used: #976

**Comment by bryevdv** [comment]
Correct, the blocker for implementing this is polygons with holes. And the blocker for that is that every other currently supported glyph can be accommodated by the ubiquitous column data source. But data for multi-polygons-with-holes will necessitate adding and supporting some entirely new data sources. But this is a non-trivial task, and while it's true that there are Geo/GIS uses for polys with holes, the pragmatic reality seems to be that many Geo/GIS applications can get by without them. 

So, this is a fairly large outlay of work, for a fairly narrow use-case (mostly just contour plots). Combined those facts with the very tiny number of currently available devs, and the many other important competing priorities, and it's fair to say this has to fall into the "longer term" bucket, unfortunately. I'd very much like to polys with holes and contour plots into Bokeh, but I can't speculate on when that might be able to happen. There is a possibility of some new funding sources for Bokeh coming in in 2017, which could help support things like this, but nothing is certain about that yet.

One avenue that someone interested enough could pursue is to make a custom extension model of some sort. If users did some ground work on experimenting with extensions, that might pave the way to make it easier for something that eventually makes it into the core library.

Re: #976 that related to an old part of Bokeh called "abstract rendering" which has since been completely removed (much of that functionality was continued in the datashader project)

ping @birdsarah

**Comment by bryevdv** [comment]
At this point this would be more appropriate for something above Bokeh, e.g. HoloViews 

cc. @philippjfr @jlstevens
