### ISSUE TITLE
Allow ResetTool boundaries be updated 

### ISSUE THREAD

**Issue by briangerke** [bokeh/bokeh#5443]
I'm currently creating a figure and serving it over bokeh server. I want to be able to interactively update the axis range when I load a new data set. I can accomplish this by changing the x_range.end value (for example), but when I do this, the plot's ResetTool will reset the axis range to the original value. I've had it confirmed via the mailing list that this is the expected behavior. But it would be nice if it were possible to update the default range for the ResetTool just as one can update the plot's access range

Below is a simplified version of what I want to accomplish. If we serve this via bokeh_server, and click on the 'zoom' button, I would like the ResetTool to leave the new axis ranges alone

```

from bokeh.plotting import figure, curdoc
from bokeh.models import Button
from bokeh.layouts import column

def zoom():

    p.x_range.end *= 1.2
    p.y_range.end *= 1.2

   '''Here it would be nice to be able to do something like
    p.select(ResetTool).x_range.end *= 1.2
    p.select(ResetTool).y_range.end *= 1.2
   '''


p = figure(plot_width=300, plot_height=300,
           x_range=[0,5], y_range=[0,5])
           
p.circle(x=range(11), y=range(11))

b = Button(label='zoom out')
b.on_click(zoom)


curdoc().add_root(column([p,b])
```

**Comment by bryevdv** [comment]
So the current `ResetTool` implementation is very dumb, and delegates everything back to the plot:
```
  do: () ->
    @plot_view.clear_state()
    @plot_view.reset_range()
    @plot_view.reset_selection()
    if @model.reset_size
      @plot_view.reset_dimensions()
```
To accomplish this ask I think we'd need to make the reset tool fairly generically configurable with:

* a set of model properties
* their associated "reset" values

Then activating the tool just applies those reset values to all the properties. I think this would have a few advantages: moving code out of `Plot` which is always a good thing, and possibly making the reset tool much more customizable, which is good because different people expect it to do different things.  

Thoughts, @bokeh/dev ?

**Comment by jbednar** [comment]
I'm all in favor of having this functionality.  In fact, I thought I'd filed an issue requesting it, though I can't find it now; maybe I just asked @canavandl directly.

**Comment by mattpap** [comment]
@bryevdv, what you propose isn't in line with what the user asks for (at least as far my understanding goes). The user has the following situation:
```
state_0 (initial) -> state_1 -> ... -> state_n -> unsaved user changes (pan, zoom, etc.)
```
and reset tool always goes back to `state_0`, whereas the user wants `state_n`. I'm not sure right now how to spell the API and how to maintain this state. Note this shouldn't be confused with state that is maintained for undo and redo tools.

Also, making reset tool configurable as proposed above is a bad idea, because how are you going to indicate to a consumer of a plot what reset tool actually does? With a very long tooltip? This is similar situation to what we have with hover tool, where a user doesn't know which button (previously checkbox) relates to which tool. Another case used to be pan vs. xpan vs. ypan, but now all have unique icons, so at least there is visible distinction.

**Comment by mattpap** [comment]
This may have something to do with animations. Consider situation where there's an animation and a user pauses it and then pans, zooms, etc. Reset tool when used should restore the last key frame, not the initial one. Here each key frame relates to state from my earlier comment.

**Comment by bryevdv** [comment]
@mattpap in many cases the user and the creator are the same person (i.e. people working themselves in notebooks) in which case the customizations do not need to be discoverable. Allowing the tool to be generically configured is a "relief valve" specifically for that class of user.

**Comment by jbednar** [comment]
Personally, I don't care whether it is the actual reset tool that is configurable, or something with a different name and icon that supplies the same functionality but in a configurable way.  I.e., if you really want to preserve the semantics of the Reset tool as an icon and as a name, that's fine, but there's still a clear need for a tool that resets *some* things and not others, and does so in a way that allows a user to express the types of resetting that are useful in a particular domain.  I have a very specific request of that type from a client project, but I bet there are quite a lot of similar issues from other people, hence the suggestion to simply make reset be configurable.

**Comment by bryevdv** [comment]
My personal preference is to make the current tool configurable with defaults that match the current behavior

**Comment by briangerke** [comment]
To help clarify the original request, what Bryan is proposing is exactly
what I am asking for: a configurable tool, with defaults that match the
current behavior.

To make the need perhaps a bit more concrete: what I am trying to build
here is a visualization tool that allows the user to load one of several
data sets. The plotting ranges are set dynamically depending on the data
set that has been loaded. A ResetTool that resets to the original plot
parameters for the default data set is essentially useless in this context,
and definitely counter to a naive user's expectations.

**Comment by jbednar** [comment]
@briangerke, I have also sometimes had precisely the issue you have -- needing to apply my own domain knowledge to make the standard reset tool work "properly" for a given special case, i.e., as a naive user would expect.  I also separately have a need for a "special" type of reset, which is slightly semantically different from the usual one (in my case, resetting only the x dimension to match the data range, not both dimensions).  @mattpap's objections do apply to this second usage of mine, because it's not precisely what the reset tool usually means.  So in that case a slightly different icon, name, etc. would arguably be appropriate.  But that would take more work, and like Bryan suggests, I think the simplest and best approach to cover all these cases is just to make the reset tool itself configurable, and use some other way to convey to the user any semantic differences that might grow out of that.

**Comment by rmchurch** [comment]
Two thoughts:
1. One easy solution would be creating "back arrows", like in Matplotlib, which allow you to go to the n-1 state (this might require lots of clicking if you have done several zoom/pan 
operations, and would have to be disabled when data is updated)
2. I personally would like, instead of a keyword to the reset tool, a keyword to the p.circle (or whatever, image, plot, etc.) call, something like "reset_update=True", signifying that when the source is updated, the reset tool should be updated to the new bounds.

**Comment by jbednar** [comment]
For my own part "back arrows" would be nice to have, but would not achieve my own goals, which is to auto-range in only one dimension.  In my use case, there is no correct state to return to, because what I'm trying to avoid is the tedious and error-prone manual adjustment involved.

**Comment by bryevdv** [comment]
I don't think the plot or renderer is the appropriate place. Having a property that is sometimes meaningful and other times meaningless (e.g. when there is no reset tool at all on a given plot) is confusing and hard to document. 

Regarding a back button, there is already an undo tool:

http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#undotool

**Comment by bryevdv** [comment]
I think I am inclined to close this in favor of #6320, which would afford the same capability by exposing properties on the range, which actually seems cleanest and simplest.

**Comment by jbednar** [comment]
Sounds good to me!
