### ISSUE TITLE
bokeh 0.12.*: no longer accepts undefined data attributes in ColumnDataSource

### ISSUE THREAD

**Issue by rs2** [bokeh/bokeh#5448]
The following snippet used to work in 0.11.*, but doesn't in 0.12.3 as the latter requires that all fields are defined upfront. 

What's more confusing is that you need to reload the page for any more plots, or even this error, to be displayed once again. Surely this is not a feature? :smile: 

```
source = ColumnDataSource(data=dict(x=[], foo=list('bar')))
p = figure(plot_width=400, plot_height=400, title='foo bar')
p.circle('x', 'y', size=20, source=source)
show(p)
```

The error was:

```
Javascript error adding output!
Error: attempted to retrieve property array for nonexistent field 'y'
See your browser Javascript console for more details.
```

**NB**: What's not helpful is setting `data=defaultdict(list)` results in the same error.

**Comment by bryevdv** [comment]
In what sense did it previously work to show a plot with a missing column? I'm not sure what's being asked for.

**Comment by rs2** [comment]
The snippet above used to generate a valid (empty) plot that could further be updated by manipulating the source. In 0.12.0 `show(p) ` raises the `Javascript error` exception that prevents changes to this or any subsequent plots. This is clearly a regression.

**Comment by bryevdv** [comment]
That's not necessarily true that it is a regression, if the previous behavior was purely accidental and unintentional, which I would say is definitely the case. If you refer to a column, it needs to exist. BokehJS is a very large and complicated runtime, in order to have any hope at maintainability, various things that were previously unenforced assumptions have had to become more strict, and this is one instance of that. The "empty plot" that you describe was actually a common and repeating source of bug reports and support requests.

**Comment by bryevdv** [comment]
Can you elaborate on what the use-case of benefit of ever looking at an empty plot (empty because it is not fully configured correctly) is? 

My initial inclination would actually be to make this error earlier and louder with a python side validation error. But I'm trying to keep an open mind.

**Comment by rs2** [comment]
Bryan, I agree, it would make more sense to either have a loud Python-side
validation message or fallback to 0.11.* and allows empty data sources.

My use case: I subscribe to a message queue and update source values as the
messages come in. This approach results in less flicker compared to
re-re-rendering the whole plot. I therefore start with an empty data source.

**Comment by bryevdv** [comment]
@rs2 But you know the *names* of the columns in advance, correct? In those cases I do, e.g.
```
ColumnDataSource(data=dict(x=[], y=[], ...))
```
Which is admittedly slightly clunky but also works perfectly well, and this is at least a somewhat specialized scenario.

**Comment by rs2** [comment]
@bryevdv correct, I know the names of the fields upfront, and the following works (I have more than 2 fields, hence `defaultdict(list)` would be preferred :smile: 

```
ColumnDataSource(data=dict(x=[], y=[], ...))
```

**Comment by ChickenProp** [comment]
I don't currently have a snippet, but I encountered what sounds like the same problem a few days ago. I was doing something like

    fig = figure()
    fig.rect(x='x', y='y', width=1, height=1, source=dataframe)

where `dataframe` was a pandas dataframe with `x` and `y` columns. I then tried `y='y+0.5'` in the `fig.rect()` call, to see if that would work. `show(fig)` gave an error, complaining about the nonexistent column "y+0.5", which is fair enough. But when I went back to the original, it kept giving that error. I had to start a new session to make it go away.

I should be able to give a session transcript within the next few days, if that would help.

**Comment by rs2** [comment]
`output_notebook` seems to reset the state, but I concur, @ChickenProp 's example is indicative of the issue.

**Comment by bryevdv** [comment]
>  I then tried `y='y+0.5'`

As an aside `0.12.5` should have a `CustomJSTransform` that will enable this sort of thing (slightly more verbosely)

> But when I went back to the original, it kept giving that error. I had to start a new session to make it go away.

Well, the reason it happens is because the "implicit notebook Document" keeps accumulating state. Basically, the possibility of arbitrary out of order cell re-execution in notebooks is a nightmare. We could either:

* get rid of all the implicit state, but making things potentially tediously explicit all over the place, all the time, or
* live with things like this and having to call things like `reset_output` or `curdoc().clear()` explicitly occasionally. 

I personally think the latter is a better compromise but I am open to ideas.

**Comment by bryevdv** [comment]
It's possible there is another approach that creates an implicit document per cell, but that would be non-trivial to implement. Additionally, the notebook itself does not have good hooks to detect when cells disappear (due to deletion or re-execution) and *also* allows for un-deletion (!), so dealing corectly with all of those cases and trying to clean up things reasonably is a hard problem.

**Comment by ChickenProp** [comment]
This suggestion is completely uninformed, since I haven't even looked at the code, and it seems kind of hacky even then, so feel free to ignore it. But would it be feasible to do the quick codepath in a try: block, and if it raises an exception, silently flush the state and try again?

(One issue I can see is that you'd probably want some infrastructure for testing that the quick codepath works when it should, so you'd need more than just a try block. It's not as simple as it naively seems.)

Another way to mitigate this, from the perspective of inexperienced users, might be simply to add a note to the error message to try calling `reset_output`.

**Comment by bryevdv** [comment]
The ship has sailed regarding any changes to notebook behaviour. Perhaps in the future when classic notebook support can be dropped in favor or only JupyterLab, we can revisit some of these things in the context of better manageable JLab extensions. 

Re: the other question, `CustomJSTransform` now exists, if it is really necessary to "bootstrap" columns that don't actually exist in a CDS.
