### ISSUE TITLE
slow generation of plots , Read cdn.pydata.org message

### ISSUE THREAD

**Issue by Timereversal** [bokeh/bokeh#5476]
it takes long time to generate Figure plot .
Read cdn.pydata.org message appear long time  on the bottom of mozilla firefox.

############ message from mozilla #####################################
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.js:140

#################chrome audit message########################### 

Optimize the order of styles and scripts (1)
1 inline script block was found in the head between an external CSS file and another resource. To allow parallel downloading, move the inline script before the external CSS file, or after the next resource.

#################################################
bokeh info 
python version :3.5.2 Anaconda 4.0.0  64 bit 
ipython version 4.1.2
bokeh version 0.12.3
------------------------------------------------------------

**Comment by bryevdv** [comment]
@Timereversal I am unable to reproduce any problems with CDN loading. Are you certain this is not a local network issue for you? Can you try to reproduce this on other networks? 

Alternatively, if you are seeing a problem with code of your own, and not one of the example, please provide a complete minimal runnable tests case that reproduces so that it can be investigated.

**Comment by Timereversal** [comment]
After i tested with only 1 plot and 1 line ,it seem to be related with my code , the first function call is ok, but after checking the html output of the second function call on jupyter, the html contains some information of the first call. also the size of the html increase every time i call the function with the same parameters.


below is my code .

df_1 = df_4g.groupby('Cell Name')

show_graphic_multi_4(df_1,['x'])  
show_graphic_multi_4(df_1,['y'])  

`
def show_graphic_multi_4(df,list_cells):

	list_max = []
	list_traffic_max_DL = []
	list_traffic_max_PRB = []

	# color definition
	u = 0
    
	#for i in df.groups.keys():
	for i in list_cells:
		print(i)
		list_max.append(df.get_group(i)['L.Traffic'].max())

	print(list_max)
    
	py = figure(x_axis_type="datetime",y_range=(0, max(list_max)*1.2 ), title = "Traffic User Max")
	print(py)
	line_list_user_max = []

 	for i in list_cells:
 		print(i)
 		line_list_user_max.append(py.line(pd.to_datetime(df.get_group(i)['Time']),df.get_group(i)['L.Traffic'],color=Spectral6[u] ,legend =i,line_width=2))
		u=u+1
    
	output_file('test_time_25.html')
	show(column(py))`

**Comment by bryevdv** [comment]
The notebook is a challenging environment for systems like Bokeh, and many choices involve less than ideal trade-offs. You might try calling `bokeh.io.reset_output` in between each plot generation.  Since this is more of a support discussion at this point I will close (please use the mailing list for general support)
