### ISSUE TITLE
BokehTornado.stop should not stop the IOLoop

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#5494]
`BokehTornado.stop` currently calls `self._loop.stop()`, which kills any other application running on the same IOLoop.  Loop creation and deletion should maybe happen outside at the CLI level.

```python
+++ b/bokeh/server/tornado.py
@@ -368,8 +368,6 @@ class BokehTornado(TornadoApplication):
         if self._ping_job is not None:
             self._ping_job.stop()
 
-        self._loop.stop()
-
     @property
     def executor(self):
         return self._executor
```

**Comment by mrocklin** [comment]
It looks like in `_start_async` this also adds a signal handler that kills the IOLoop on a `SIGTERM`

```python
    @gen.coroutine
    def _start_async(self):
        try:
            atexit.register(self._atexit)
            signal.signal(signal.SIGTERM, self._sigterm)
        except Exception:
            self.exit(1)

    def _sigterm(self, signum, frame):
        print("Received SIGTERM, shutting down")
        self.stop()
        self._atexit()
```

Which also calls `stop`

**Comment by pitrou** [comment]
Seconded. A library (as opposed to an entire application or CLI script) should generally not install signal handlers unconditionally. As for atexit handlers, they should be limited in their scope as well (i.e. cleaning up the library's own resources is fine, but closing another library's resources - such as the Tornado IO loop - is not).

As an additional suggestion, since the `start()` method has an optional `start_loop` parameter, so should the `stop()` method have an optional `stop_loop` parameter.

**Comment by bryevdv** [comment]
FWIW this was all modeled after the Jupyter notebook server code. I didn't have any experience with tornado when this was written. @pitrou would you be interested in working up a small PR for this?

**Comment by pitrou** [comment]
I definitely can do that. Are there any particular guidelines for PR submission?

**Comment by bryevdv** [comment]
Here's what would make this PR perfectly complete:
* updated docstrings
* any relevant tests
* a section in the server chapter of the users guide about programmatic server starting

I recognize you may not have the bandwidth for all of that, if not, if you allow maintainers to collaborate, then I can add any remaining bits you don't have time to work on. Otherwise, the PR just needs to reference this issue in the opening comment, along with any other information you'd like to provide.
