### ISSUE TITLE
Fix DatePicker widget

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5506]
Based on discussion in PR #5451:

>> (...) but its styling is badly broken currently

> It think it's not only currently, but it has been for 1.5+ years (since introduction of CSS class prefixes). If > no one complained for that amount of time and given that we never had a single example using it, then "a use" seems more like "no use".

I think we should consider removing it. Just note that I introduced this widget, I think just for the sake of having a widget for whatever jquery-ui supports.

**Comment by bryevdv** [comment]
Well, I think a date picker is a reasonably valuable thing to have. I am not sure the JQ one is salvagable, though. I don' t think we can control the styling in a way that could fix it, at least not without heavily modifying it. What about this:

https://github.com/dbushell/Pikaday

It claims to have no dependencies and is 5kb minified and zipped.

**Comment by bryevdv** [comment]
To be clear I'd also be content to demonstrate wrapping that date picker (or some other one) as a custom model in a way that people could easily copy/use, too, and not having one in the core library at all.

**Comment by mattpap** [comment]
I did some calculations and assuming data table would be moved to a separate bundle (this implies moving jquery-ui as well and removing/moving date picker and autocomplete widget as well) and replacing all sliders with nouislider, then we could get `bokeh-widgets.min.js` reduced to estimated  60~70 kB and `bokeh-widgets.min.css` to 40~60 kB. This doesn't involve further slimming down bootstrap, which, I think, can be reduced at least by half (saving about 20 kB). Those calculations include removal of font-awesome (PR #5525).

**Comment by azjps** [comment]
FYI I've had reasonable success using custom extensions based on [jquery-air-datepicker](http://t1m0n.name/air-datepicker/docs/), which seems to be pretty well maintained.

**Comment by pkgandhi** [comment]
Hi @azjps : I am having hard time to implement the datepicker into my python code. Do you mind sharing example/snippet of how you ingested the air-datepicker using custom extensions? 
Thanks!

**Comment by azjps** [comment]
Hey, unfortunately I don't think I'll be able to provide any code right now (waiting on compliance policies and such, to be on the safe side). Here's some suggestions though:

- The [custom extensions](http://bokeh.pydata.org/en/latest/docs/user_guide/extensions.html) examples do describe the general idea pretty well.
- The main pitfall I encountered was how to include JQuery and have JQuery plugins work correctly; this might not be the bokeh-devs' recommendation but the path of least resistance for me was to supply it as a `__javascript__` resource via [CDN](https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.js).
- For air-datepicker you will also need to provide `datepicker.css`, `datepicker.js`, `datepicker.{language}` from CDN.
- Since your widget will likely be pretty static outside of having callbacks on changing the input's value, it should be fine to define everything in `initialize`. You can construct the `datepicker` object using something like `$(@$el.find("input.bk-widget-form-input")).datepicker(...)`. Note the `$()` to invoke the global JQuery plugin.
- From there the rest is about reading the air-datepicker docs and picking out what features you need. The `onSelect` callback will likely be a useful callback to change your `@model`.
