### ISSUE TITLE
hbar plots not showing correctly on IE11 / Edge

### ISSUE THREAD

**Issue by tetanushamster** [bokeh/bokeh#5523]
Bokeh version 12.3

Tested with the following code:

```
import numpy as np
from bokeh.io import curdoc
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource

arr = np.arange(200,301)
y = [k for k in range(101)]
source_m = ColumnDataSource(data=dict(y=y, display=arr))

plot = figure(plot_height=400, plot_width=600, title="There is no system but GNU, and Linux is one of its kernels.",
              tools=["save"],
              x_range=[-450, 450],
              y_range=[0, 101])

m_plot = plot.hbar(right='display', y='y', source=source_m, line_width=6, line_alpha=0.5, color="blue")

curdoc().add_root(plot)

```

The hbars wont show on the afformentioned browsers, whereas Chrome / FF / Safari seem to work fine.
Bryan has already proposed a workaround by explicitly supplying a height-parameter to the hbars.

Desired feature: Make hbars great again.

**Comment by bryevdv** [comment]
Initial guess is perhaps some default values are arriving as `null` on IE for some reason.

**Comment by bryevdv** [comment]
Hi @tetanushamster Thinking more about this, I think maybe the fact of this "working" on other browsers is only an accident? It seems to be that `height` *should* be required. After all, there is really no reasonable default height that can be picked, since the spacing of the bars can be completely arbitrary. Thoughts? (and changing this to `discussion` for now)

**Comment by bryevdv** [comment]
More information: With some recent changes, this is what happens if you run the above code with the most recent checkout on `master`:
```
[bryan:/tmp]$ ~/work/bokeh/bin/bokeh serve --show foo.py
2016-12-09 09:12:27,594 Starting Bokeh server version 0.12.4dev7-55-g9210f28
2016-12-09 09:12:27,601 Starting Bokeh server on port 5006 with applications at paths ['/foo']
2016-12-09 09:12:27,601 Starting Bokeh server with process id: 4483
2016-12-09 09:12:28,028 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x114590e48>: hbar() missing 1 required positional argument: 'height'
File "foo.py", line 15, in <module>:
m_plot = plot.hbar(right='display', y='y', source=source_m, line_width=6, line_alpha=0.5, color="blue") Traceback (most recent call last):
  File "/Users/bryan/work/bokeh/bokeh/application/handlers/code_runner.py", line 83, in run
    exec(self._code, module.__dict__)
  File "/private/tmp/foo.py", line 15, in <module>
    m_plot = plot.hbar(right='display', y='y', source=source_m, line_width=6, line_alpha=0.5, color="blue")
TypeError: hbar() missing 1 required positional argument: 'height'
```
Since there is now an explicit and good warning about the missing required value, I'm definitely inclined to just close this issue. 

I definitely think the "working" versions we accidents due to platform and implementation specific details of the non-IE browsers.

**Comment by bryevdv** [comment]
@tetanushamster I am going to close this for now. Thanks for starting this discussion I think it was a good explicit point to draw out.
