### ISSUE TITLE
Correctly handle data values <= 0 on a log scale

### ISSUE THREAD

**Issue by StevenCHowell** [bokeh/bokeh#5549]
This is a continuation from issue #5389, partially adressed by PR #5477.  There persists an issue where negative data is not handled correctly.  All data <= 0 should be discarded before generating the plot.

As is, if `values = np.linspace(-0.1, 0.9), a JS error complains that it "could not set initial ranges", probably because `log(n)` for `n<=0` is not defined.

**Comment by clairetang6** [comment]
Taking a quick look at this, the problem is definitely because the computed start for the range is NaN. I remember there was code (that I took out) which was labeled hotfix, where the minimum data value was set to 1 whenever it was < 0. That fix also lead to weird behavior (flipped ranges) because the set minimum of 1 could be greater than all of the other data values. Especially in the log plotting context, it is impossible to guess at a minimum value. 

The best thing to do would be to set the minimum data value to the the minimum value that is still > 0. But the min data value is saved into the `bounds` for each renderer and the ranges only use that and don't access all of the data values. 

I want to try out a few things to see what would be the best solution. @bryevdv @StevenCHowell do you think it is worth it to first add back the hotfix? I could make that small PR tonight and then figure out a better way to fix it. 

Also, the workaround now would be to supply a range start and end.

**Comment by StevenCHowell** [comment]
@clairetang6, for the hotfix, setting it to 1 will obviously create other problems (typically my data ranges from 0 to 0.3 ish).  As you say, something more like the following would be more appropriate:
```
x_min = min(x[x > 0])
```

**Comment by bryevdv** [comment]
I'm moving this one to `0.12.5`
