### ISSUE TITLE
What is the reason that bokeh does not allow NaN values? json.dumps(allow_nan=False)

### ISSUE THREAD

**Issue by ragesz** [bokeh/bokeh#5581]
A had the same problem described [here](http://stackoverflow.com/questions/38821132/bokeh-valueerror-out-of-range-float-values-are-not-json-compliant/41213102#41213102):
when saving or showing the bokeh plot I also got the following error:

> ValueError: Out of range float values are not JSON compliant

I found that in `/core/json_encoder.py` source file at `serialize_json()` function there is the `allow_nan=False` argument in `json.dumps()`. But I don't know why. Is there a reason or maybe NaN values could be allowed?

If an `x` or `y` data point is NaN then simply this data point should not be plotted. And if only a HoverTool data point is NaN then nothing should be displayed (only on HoverTool's tooltip).

**Comment by bryevdv** [comment]
The reason Bokeh does not send nan values in JSON is because the JSON standard itself does not support NaN values, despite the non-standard-conforming `allow_nan` flag that python offers. I think was a pretty egregious oversight to not have nan/inf as part of the JSON spec, but its also wholly  outside of our control. Browser support cannot be guaranteed, which leaves us no choice but to be conservative in our actions. Please look forward to a binary array protocol that is currently being worked on in https://github.com/bokeh/bokeh/pull/5544
