### ISSUE TITLE
Subset the data based on Criteria

### ISSUE THREAD

**Issue by pkgandhi** [bokeh/bokeh#5611]
Hello,

Is there a way we can subset data from ColumnDataSource using specific criteria, like we do in Pandas:

e.g. df[df['Year'] == 2014]

Thanks!

**Comment by bryevdv** [comment]
Hi @pkgandhi in order to have some hope of keeping the issue tracker maintainable, we ask that it be reserved for bug reports, feature requests, and development-related discussion *only*. For general support questions, please use the public mailing list:

 https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh
