### ISSUE TITLE
cannot run simple tutorial code

### ISSUE THREAD

**Issue by manuel1581** [bokeh/bokeh#5617]
In the Introduction Bokeh tutorial located at: http://goo.gl/bJcKr4
that I was following from the euroscipy bokeh 2015 youtube video

There is a piece of code:
import utils
p = utils.get_gapminder_plot()
show(p)

that more than I'm looking at the web I cannot find why I'm not able to run it.

Would you guys mind help me out here?
THankyou

**Comment by bryevdv** [comment]
Hi, 

In order to try and keep the issue tracker humanly manageable, we ask to reserve it for bug reports, feature requests, and dev-related discussions *only*. For general support questions such as this, please use the public mailing list:

https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh

By using the mailing list, the growing support burden can be shared among a larger audience of potential answerers, and the answer is also archived for the benefit of other users.
