### ISSUE TITLE
matplotlib compatibility doesn't work in 0.12.4

### ISSUE THREAD

**Issue by amichaut** [bokeh/bokeh#5736]
Examples of to_bokeh usage provided in example/compat don't work anymore since 0.12.4 release. 
For instance, mpl.plot.py leads to an empty webpage.

**Comment by bryevdv** [comment]
I just checked, that example is working for me as expected, as are all the deployed gallery examples that depend on mpl compat. You will have to be more specific about your setup, since it is evidently something that is particular to your situation. It's always a good idea to just give as much information as possible, (i.e., all the information specifically requested in the pre-filled issue message) from the very start. 

All that said, @pzwang the current MPL compat is both not very good, and also unmaintainable. I'd personally like to consider removing it all together. Ping @bokeh/dev for comment as well.

**Comment by amichaut** [comment]
Sorry for that... I don't know what happened but I can't reproduce the bug I experienced. 
Apologies.

**Comment by bryevdv** [comment]
No worries, glad it's working for you now.
