### ISSUE TITLE
Feature: datetime axis date format

### ISSUE THREAD

**Issue by michaelaye** [bokeh/bokeh#575]
I can't find any way to change the date-format of datetime axes, so I guess it's not implemented yet and this is a feature request.

I'm especially keen of NOT having the confusing American format, but instead have a sequence akin to ISO standard like the following when zooming into a big timeseries:

yyyy --> yyyy-mm --> mm-dd

and not

yyyy -> mm/yyyy --> mm/dd

How can you live like that?? ;)

**Comment by rchossein** [comment]
is it still not possible to change the datetime axis date format in Bokeh library? I am using Python for the visualisation; I can add a bit of JavaScript to my code but don't want to have my plot completely in JavaScript. I just want to change the format to sth like ```12:13 pm``` but have problems there. My chart is a line chart updating every one hour, and Bokeh shows my ```12hr 13hr``` instead of what I want it to show. Any comment would be appreciated.
