### ISSUE TITLE
set upper/lower bounds individually

### ISSUE THREAD

**Issue by axil** [bokeh/bokeh#5779]
Setting both limits of an axis is easy:

    p = figure(x_range=[1, 5])
    or p.set(x_range=[1,5])

Setting lower bound only could be done though using (nonexisting) `p.get_x_range()` but as discussed in https://github.com/bokeh/bokeh/issues/4371 it is not possible to get calculated values of the `x_range` in python because the calculation is done on the client side.

It'd be great if one could set only one limit manually and let bokeh calculate the other one for example using this notation:

    p = figure(x_range=[1, None])

(it doesn't work right now).

**Comment by bryevdv** [comment]
Hi @axil there is a way to do what you ask, if I am understanding your question. However, the issue tracker is not the appropriate place for general support questions. We reserve it for bug reports and feature requests *only*, in order to keep it manageable. And also so that general support answers are archived in a more accessible place (the mailing list).

Please ask your question again on the public mailing list:

https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh

**Comment by axil** [comment]
@bryevdv I truely believed it was a feature request ) ok

**Comment by axil** [comment]
In case someone lands here from google, the proper way of doing it (if I understand correctly) is:

```
from bokeh.models import DataRange1d
p = figure(x_range=DataRange1d(start=1))
```
