### ISSUE TITLE
migration notes and exceptions about MPL compat. 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5788]
MPL compat does not work with MPL 2.0, and is unlikely to ever until or unless MEP 25 is implemented. The `0.12.5` release notes should make mention of this, and importing the MPL compat fiunctions should raise an error if MPL >= 2.0 is installed.

**Comment by bryevdv** [comment]
Alternatively @pzwang @bokeh/dev I would also support deprecating MPL compat now, with complete removal on `1.0`.  It's barely functional when it works, often does not work at all, and is unmaintainable in its current form.

**Comment by mattpap** [comment]
+1 for deprecation.

**Comment by damianavila** [comment]
+1 as well.

**Comment by pzwang** [comment]
*sigh*  May we always have the courage to dream of the future, but the fortitude to acknowledge the present reality.

+0

**Comment by pzwang** [comment]
One additional comment: I'd like to make sure that blocking on MEP-25 is not a "perfect is the enemy of the good" situation.  Not being able to offer seaborn compatibility is really not great, especially given the situation with `bokeh.charts`.  Altair is still very new and not widely adopted or documented, although I expect it will get there in the fullness of time.

Without a good high-level charting API, we are left with a structural, strategic deficiency.

**Comment by jbednar** [comment]
HoloViews is a good high-level charting API.

**Comment by bryevdv** [comment]
We only currently "support" a fraction of seaborn, and not well. Many (most?) seaborn charts do not currently work and never have. Basically what is in the gallery now, is it.

**Comment by mattpap** [comment]
> We only currently "support" a fraction of seaborn (...)

This is pretty much what I base my +1 on. Perhaps we should have a wider discussion regarding high level charts and what to do about `bokeh.charts`.

**Comment by bryevdv** [comment]
> Perhaps we should have a wider discussion regarding high level charts and what to do about bokeh.charts.

We should. FWIW my tentative intention is this:

* make supporting Altair/Vegalite a priority for `0.12.6` 
* make a cleanup and  overhaul of `bokeh.charts` (but no API changes) a priority for `0.12.7` 

Feedback on this plan is welcome, however.

**Comment by bryevdv** [comment]
ping @tacaswell

**Comment by jbednar** [comment]
I'd vote for deleting bokeh.charts, because it's a dead end for users -- some stuff is easy to do using that API, but the amount of work that it would take for it to become fully usable in real-life scenarios is mind-boggling.  What it would need is full support for lots of different chart types, a full system for customizing and choosing style options, and full support for laying out charts into complex figures.  Plus it would be nice to have full support for datashader-backed plots, and full support for custom interactivity.  All of those things are what HoloViews provides for Bokeh plots already, today.

So I don't think we should try to build a competitor to HoloViews.  I think we should just use it, as the high-level data-science API for bokeh.

**Comment by bryevdv** [comment]
Are there chord or donut charts in holoviews? What about streamline or quiver plots? (which I'd very much like to add)

**Comment by tacaswell** [comment]
Out of curiosity, what did we break in 2.0?

**Comment by bryevdv** [comment]
@tacaswell I have no idea and less than zero bandwidth to investigate. But my understanding is that mplexporter (which is AFAICT now entirely unmaintained) depended on some internal and private details of MPL. I am not surprised that it would break.

**Comment by philippjfr** [comment]
>Are there chord or donut charts in holoviews? What about streamline or quiver plots?

Been meaning to add a donut chart for ages but haven't gotten around to it. I initially prototyped an [AnnularWedge](https://anaconda.org/philippjfr/annularwedge/notebook) Element, which could be used for donuts, but I think we should have a simplified donut element rather than adding something quite so complex. I've not looked at chord plots, but in theory I'd be happy to port some of the charts code to HoloViews. We also have a [VectorField](http://holoviews.org/Tutorials/Elements.html#VectorField) Element, which can be used to plot streamline and quiver plots, but I have not yet implemented it in bokeh.

The main thing we'd need to really promote HoloViews as an alternative to charts is to add documentation to explain how to mix and match HoloViews and bokeh code by working directly with the underlying plot objects rather than handling all of that in the background.

**Comment by bryevdv** [comment]
I'm not categorically opposed to making Holoviews the "high level API for Bokeh" but to do that needs some things:

* a decision to that effect
* commitment of resources
* a plan to market/advertise/demonstrate the results widely in the bokeh docs

**Comment by jbednar** [comment]
Yes, precisely.

**Comment by bryevdv** [comment]
For sure,  lots of things have broken our builds in the last week, but for reference MPL updating when I didn't intend it to (which sure, is also a conda issue) just cost me another few hours and an aborted dev release build:

https://github.com/bokeh/bokeh/issues/5803

My point is that just to stress that maintaining this is not something I can manage effectively anymore.

**Comment by bryevdv** [comment]
...aaaaand it just failed again.
