### ISSUE TITLE
Hard pass/fail test of some kind of basic glyph drawing

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#5800]
The examples reports are useful but are no substitute for automation. The project needs test(s) for basic glyph drawing that will actually result in a hard failure if results are not pixel-matched to expected results. 

To start, perhaps this could be a single large plot with no grids, axes, toolbar, etc, that simply draws a few representatives of each glyph. This does not give fine resolution into problems immediately, but would be a "canary in the coalmine" that at least indicates when *some* problem with basic rendering has been introduced.

**Comment by bryevdv** [comment]
I'm not sure if this goes in `0.12.5`, obviously it is overdue and the sooner, the better. 

ping @mattpap

**Comment by mattpap** [comment]
>  (...) some kind of basic glyph drawing

In the context of the recent regression, basic drawing actually worked and the failure was related to a limited set of functionality and thus limited subset of examples. Given this, the proposed solution wouldn't help here and we would have to still refer to unreliable examples' tests, as they currently are. I think that given our limited resources, we should fix existing infrastructure which we already should know well, instead of invest time in something brand new.

**Comment by mattpap** [comment]
What to do to fix examples' tests? First of all, as much as they are automated, their intrinsic property is that you can't decide whether a change is intentional or is a result of a regression or a bug in newly introduced code or example. Thus human intervention will be always necessary in case of image differences. However, currently there is no possibility of a test run with no image differences and there are plenty of differences during each, because notebook and server tests don't work at all, MPL compat produces randomly different images even if there are no random numbers involved, there are some examples using unseeded random generators (jitter) and timeouts are used to determine when bokehjs finished rendering, which leads to examples randomly not rendering at all or rendering partially or fully. We need to fix those and then we will know if there are differences or not. If there are, then one will have to inspect differing images and decide if there's an issue or not. It used to work like this a long time ago and for a brief window of time. Additionally, JS errors must be reported in the test long and don't allow to proceed to image diff (this is a big and unappreciated regression).

**Comment by bryevdv** [comment]
> the failure was related to a limited set of functionality and thus limited subset of examples.

My interpretation of things is a bit different: the change made things *work* in a limited case, and caused it to *fail* everywhere else (i.e., all the existing common cases). This is exactly the situation I was proposing to try and automate detection. I'm not necessarily proposing anything new either, perhaps:
* a single new selenium test 
* a single new example test and way to mark a subset of example tests as "strict"

You are absolutely correct that we can't currently expect *all* examples to be runnable and pixel-comparable in a completely automatable fashion. And I am not sure we ever could fix up, e.g. whatever causes the seaborn examples to look slightly different. What I am saying is that there is *some* set of simple, focused, purpose-specific  things that could (and therefore should) be written and compared automatically. And furthermore, that a set of initial strict things could be added to testing immediately. That is, we should not wait for something perfect tomorrow, instead of having something valuable today.
