### ISSUE TITLE
from bokeh.palettes import ... does not resolve

### ISSUE THREAD

**Issue by TiemenSch** [bokeh/bokeh#5813]
**Description**
When I try to import a palette from bokeh.palettes, I get an "Unresolved import" error by PyDev (Eclipse). Up until now all other packages of bokeh load just fine. 
```python
from bokeh.palettes import Viridis6 as palette  # Import unresolved: palette
```
When ran, the import works just fine however! That's the strange thing. Perhaps the module's structure is somewhat unconventional for PyDev to understand? It does this for all bokeh.palettes, I just took Viridis as an example.

**Software version information** `bokeh info` 
Python version      :  3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
IPython version     :  5.1.0
Bokeh version       :  0.12.4
BokehJS static path :  C:\Users\Me\Miniconda3\lib\site-packages\bokeh\server\static
node.js version     :  v5.5.0
ERROR:[WinError 2] System cannot find file. (<- translated that from Dutch, exact EN description could differ)

So it does throw some error at info, but I do not know what it is missing.

**Comment by bryevdv** [comment]
Yes, `bokeh.palettes` uses the "module hack` to install a class in place of the module. This is so that all the palettes can be read-only properties on the class that return a new clean copy of a palette every time it is accessed. The reason for this is because it was previously easy for users to modify the palettes in place, which had global effect and lead to easy-to-make but subtle bugs. 

I'm not a PyDev user, so I'm not sure offhand what could be done to make it happy. If there is some linting comment directive or something that can add to quell PyDev's checker, that seems easy and reasonable to do.

**Comment by bryevdv** [comment]
@TiemenSch I am not sure there is anything we can do anything on our end (so I am closing this issue) but based on this StackOverflow post:

http://stackoverflow.com/questions/1702043/how-can-i-make-the-pydev-editor-selectively-ignore-errors

it does look like there is a pragma comment that you can add to your code that would silence these messages, something like:
```
from bokeh.palettes import Viridis6 as palette #@UnresolvedImport
```

**Comment by golmschenk** [comment]
This also seems to occur with PyCharm. Likely any IDE that uses static code inspection (which used for speed considerations) will run into this issue.
