### ISSUE TITLE
Control glyph order

### ISSUE THREAD

**Issue by patricktokeeffe** [bokeh/bokeh#5823]
There needs to be a way to control the vertical stacking of glyphs. They are not displayed in the order they are created. The lack of Z-order control means I cannot do something as simple as displaying a line glyph on top of a `BoxAnnotation`. Instead I have to resort to using certain colors and alpha values.

I think other annotations are impacted too. For example, how do I constrain a `Label` to only appear within the plot window? I haven't figured this out and am guessing it's related to the display layers.

Yes, I've read #696 and it shouldn't have been closed. [This commit](https://github.com/bokeh/bokeh/pull/1484/commits/0f95a36204cb3da7504357c228c5cdba24b1e526) is the only one I see related to Z order and it did not expose control the user.

**Comment by bryevdv** [comment]
By default, annotations render on top of glyphs, since that is the more common use-case. If you'd like to put them in a different render level, you can set a different render level for them:

http://bokeh.pydata.org/en/latest/docs/reference/models/renderers.html#bokeh.models.renderers.Renderer.level

http://bokeh.pydata.org/en/latest/docs/reference/core/enums.html#bokeh.core.enums.RenderLevel

e.g. all `'underlay'` renderers are rendered before all `'glyph'` level renderers. 

Among the renderers in a given render level (e.g. glyphs) things are rendered in the order they are added.

**Comment by patricktokeeffe** [comment]
> Among the renderers in a given render level (e.g. glyphs) things are rendered in the order they are added.

Ah the missing piece. Shoot. Thanks

**Comment by bryevdv** [comment]
No worries, please re-open if there are any other problems this information does not cover

**Comment by dubreuia** [comment]
> If you'd like to put them in a different render level, you can set a different render level for them:

This is exactly what I'm looking for, but I don't know how to do it. I have a `BoxAnnotation` that I want to render in the `underlay` level (under my `quad` glyphs), how do I change the render level of the box annotation?

Thanks
