### ISSUE TITLE
Impossible to change x or y range in TapTool callback

### ISSUE THREAD

**Issue by agilly** [bokeh/bokeh#5863]
I have posted a more complicated version of this issue as a question on stackoverflow ([here](http://stackoverflow.com/questions/42163716/setting-figure-ranges-using-taptool-in-bokeh)). 

However the underlying behavior may be more basic than that. In the below example, I am just trying to make a click on a point zoom the x-axis around that point. However, nothing happens when a point is clicked. I have checked that the values of `xr.start` and `xr.end` have the right values at the end of the callback (using `alert`), they do. This works when setting ranges on another figure (e.g. `p2.x_range`) but not the current one, as mentioned in the SO question.

I am running bokeh version 0.12.4, Python 3.4.3, in a notebook (IPython 4.0.1).

```python
from bokeh.io import show, output_notebook
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource, CustomJS, TapTool
output_notebook()
data=pd.DataFrame()
data['x']=[1, 2, 3, 4]
data['y']=[1, 2, 3, 4]
data['col']=['red', 'red', 'red', 'red']
p=figure()
src=ColumnDataSource(dict(x=data.x, y=data.y, col=data.col))
p.circle('x', 'y', color='col', source=src, size=20)

cb_click = CustomJS(args=dict(source=src, xr=p.x_range), code="""
index_selected=source.selected['1d'].indices[0]
dat=source.data
xr.start=dat['x'][index_selected]-0.5
xr.end=dat['y'][index_selected]+0.5
""")

p.add_tools(TapTool(callback=cb_click))

show(p)
```

A corollary of this effect is that when the `x_range` or `y_range` is changed, and a callback makes some modification to a source passed as argument, the plot resets and zooms out to its original boundaries. This makes it impossible to do any work with zooming parameters in interactions and callbacks. This only happens when the ranges are changed _programmatically_, adding a `box_zoom` tool and adjusting ranges manually allows the addition/modification of glyphs without triggering a reset.

**Comment by bryevdv** [comment]
cc @mattpap this is weird, the range does update if you click on a point a second time.

**Comment by bryevdv** [comment]
So, looking briefly into this again, this works as expected with 
```
p=figure(x_range=(0,5))
```
So this has to do with `DataRange1d` specifically. Remembering more, I believe data ranges can be set *initially* but do not respond to changes to `start` and `end` after that. I don't think there is any way to do so, either. There is no way to tell if `start` is being set because a *user* is setting it, or because the range it self is auto-ranging and setting it. We would need some new property or API for that, which would add complication to an already very complicated model. Given than, and also that:

* there is an alternative approach that works (use `Range1d`) 
* this has been the only report or question about this 

I am inclined to take no action.
