### ISSUE TITLE
js_on_change for ColumnDataSource

### ISSUE THREAD

**Issue by koganm** [bokeh/bokeh#5944]
can you guys please point me to an example of using js_on_change with a glyph's data_source 'selected' event?

we've tried defining a CustomJS object per your examples here http://bokeh.pydata.org/en/latest/docs/user_guide/interaction/callbacks.html#customjs-for-generic-events but the JS code does not appear to fire when we select a point:
js_callback = CustomJS(args={}, code="...")
p.data_source.js_on_change('selected', js_callback)

would it matter that we also have a python callback attached to the data_source selected event?

thanks for your help

**Comment by bryevdv** [comment]
Hi,

In order to keep the tracker manageable, we reserve it for bug reports, feature requests, and development related discussion. For general support questions, please use the project mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

Or the gitter chat channel.

**Comment by azjps** [comment]
While I don't know if this is relevant, there does seems to be some incorrect wiring for the `DataSource` properties like `selected`, see for example #5701 (which is the opposite situation, unable to propagate changes in python model to JS). I was stumped by all of the bokeh callback magic when I briefly tried debugging since its harder to debug absence of a callback.

**Comment by koganm** [comment]
got it, thanks for looking into this. mainly we just want to be able to execute arbitrary javascript code whenever a point or set of data-points is selected in a plot. i suppose a hacky way to do this would be to use OpenURL with tap.callback and inject some javascript into the URL to be executed, if that would work.
