### ISSUE TITLE
flask_embed.py won't run

### ISSUE THREAD

**Issue by niloxx** [bokeh/bokeh#5980]
#### File
[bokeh/examples/howto/server_embed/flask_embed.py](https://github.com/bokeh/bokeh/blob/0.12.4/examples/howto/server_embed/flask_embed.py)

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Windows 7 x64 Python 2.7 Flask 0.11.1 Chrome

#### Description of expected behavior and the observed behavior
When `server.start()` is called the server executes in the console process and stops the execution of the rest of the Flask app. In order to run the flask app, `server.start()` has to be deleted. Otherwise, the example works fine.

**Comment by niloxx** [comment]
[PR #5981](https://github.com/bokeh/bokeh/pull/5981)

**Comment by bryevdv** [comment]
Hi @niloxx thanks for taking the time to make an issue and a PR. However, I think the actual issue is that those examples on master were only recently added with he `0.12.4` release, will only run properly with version `0.12.4` and newer, and that you are using an older version of Bokeh than that. Can you confirm what version of Bokeh you are using by running `bokeh info` ?

**Comment by bryevdv** [comment]
ping @niloxx can you report and confirm what version of Bokeh you are using?

**Comment by bryevdv** [comment]
Can confirm that `start` is no longer blocking (see example in PR). The solution is that updating to Bokeh > `0.12.4` is required to run these examples.

**Comment by niloxx** [comment]
Hey @bryevdv , sorry for the late answer. You were totally right, my bokeh version was 0.12.2. Thanks for checking it!

**Comment by bryevdv** [comment]
Glad it's sorted out :)
