### ISSUE TITLE
Events with feedback / Simple RPC

### ISSUE THREAD

**Issue by volkerjaenisch** [bokeh/bokeh#5983]
This post starts as a discussion on [Reference](https://github.com/bokeh/bokeh/pull/5941).

Currently Bokeh handles JS Events as "fire and forget" when they are propagated to the Python Handlers.
This is due to the current protocol layer messaging events as changes in the model state:
1) A JS Event (e.g. change an axis by mouse operation) results in the change of a JS model property
2) The JS model change is reflected (utilizing the websockets connection) in the Python model
3) The change in the Python model results in a change Event on the Python side.
4) The Python change event triggers a python handler.

This technique is not capable to realize a JS to Python RPC (Remote Procedure Call). In particular a feedback from the Python handler to the JS Event is not possible.

The above mentioned PR will bring a new "Event" token to the Bokeh websockets protocol. But this improvement will not give us a feedback mechanism.

I would like to discuss possibilities to improve the communication layer of Bokeh. Let's discuss something like CORBA or another distributed Component-Communication protocol you prefer as an **ideal** for Bokeh to approach. Bokeh will never and should never become so complex as e.g. CORBA but we can learn from them.

Any protocol is better than to signal "something has changed in model.component.property", only. 

Volker

**Comment by bryevdv** [comment]
Also marking this as a `feature`. I think "corba-*super-ultra-light*" is not unreasonable and also mostly attainable using existing infrastructure. Will have to elaborate more on some design ideas later, but if you have ideas to share now @volkerjaenisch please record them here.

**Comment by bryevdv** [comment]
Just to note that per #2812 we should expose a JS mechanism for triggering named functions as well.

**Comment by bryevdv** [comment]
@volkerjaenisch @sandrarum I am pleased to hear that you may be able to work directly on accelerating this feature. I'll try to give a high level outline of a possible work plan here, and we can drill down into details as needed. First, here is the PR that added the "events" message and capability:

https://github.com/bokeh/bokeh/pull/5941

I think in some ways this work will be simpler, but that PR represents a self-contained chunk of work to add a new message so I think it will be a useful reference. 

Additionally, I think we should concentrate on making a PR that is limited in scope:

*Add `RPC-REQUEST` and `RPC-RESPONSE` messages to support calling JS code from Python.*

I think it is an open question if async, "fire and forget" RPC (in either direction) needs to be added as something separate and new. I think it is possible the existing events either already cover that case, or can be made to straightforwardly. 

----

We should probably spend some time figuring out what the Python API is/should look like, because that will have ramifications. The first question e.g., is how is the code for the JS function to call supplied? One idea would be to use `CustomJS` or something like it, because it already affords easy and simple access to any Bokeh models you want to configure it with. 

```

curdoc().add_function("myfunc", CustomJSFunction(args=dict(...), code="""
    # JS code goes here, what should return? unspecified JSON is one option 
""")

curdoc().call("myfunc") 
```

My guess is that you want more than to have function params "baked in" as existing models passed to args. So it would be good to get your input on requirements to know best what ways to consider extending this basic idea. 

---

Once these questions are resolved, the (very) high level tasks would be:

1) define new protocol message types in Python and JS. On the Python side messages are now under `bokeh.protocol`. On the JS there are not defined classes for messages, they are all handled under `src/coffee/client` however. 

2) Create handlers for the messages on the appropriate sides (often methods on Session objects but may be elsewhere)

3) Figure out the best way to store and communicate the JS functions on a document (there is similar to question for "namespace models" that has not been resolved)

4) Implement the APIs to set up, use, and respond to the handlers for the messages.

**Comment by JEGBergqvist** [comment]
Potentially relevant in this context, re comments @ https://github.com/bokeh/bokeh/issues/8728#issuecomment-470665620

Not sure if it's applicable or not, it's an attempt to reduce the scope to increase feasibility of the task.

Best regards, Gabriel

**Comment by nanthony21** [comment]
Is there still no good way of doing this?

**Comment by bryevdv** [comment]
I think at this point, the best solution is to utilize `DataModels`, and present it as a recipe pattern than can be applied, rather than something we add to the library directly. At this point I'd regard actual RPC as simply out of scope. 

Here is a working POC with Bokeh 3.0

```
from bokeh.core.properties import Float, Int
from bokeh.model import DataModel
from bokeh.models import ColumnDataSource, CustomJS, Slider
from bokeh.plotting import figure, show, curdoc

class FuncThing(DataModel):
    amp = Float(default=0.1)
    freq = Float(default=0.1)
    phase = Float(default=0)
    offset = Float(default=-5)

    _trigger = Int(0)

    def run(self, **kw):
        self.update(**kw)
        self._trigger += 1

    def __init__(self, code, *args, **kw):
        super().__init__(*args, **kw)
        callback  = CustomJS(args=dict(args=self), code=code)
        self.js_on_change("_trigger", callback)

func_thing = FuncThing("console.log(args.amp)")

slider = Slider(value=0.1, start=0, end=10)
slider.on_change("value", lambda attr, old, new: func_thing.run(amp=slider.value))

curdoc().add_root(func_thing)
curdoc().add_root(slider)
```
That will "run" the JS code from the Python callback (this is a toy example but the principle works in general)

@bokeh/core I am interested in comments. Would a (better) example demonstrating this technique and/or a user guide section be sufficient to close this old issue?

**Comment by nanthony21** [comment]
Thanks, this is an improvement over what I am currently doing, I wasn't aware of `DataModel`. Is there any reason that `CustomJS` can't just have a `trigger` method that does exactly this?

**Comment by ansgar-t** [comment]
> [...] Here is a working POC with Bokeh 3.0 [...]

Is Bokeh 3.0 required to make this work? (I'm using panel which requires bokeh < 2.5.0, so I can't upgrade.)

**Comment by bryevdv** [comment]
> Is there any reason that CustomJS can't just have a trigger method that does exactly this?

Late reply, but more or less it is just a non-trivial amount of more work, and this option already exists. CustomJS expect to be "attached" to something either via `on_change` or `js_on_change` and those methods give them a place to "live" in the document automatically. To support just calling `trigger` on "bare" `CustomJS` there will have to be some new way to collect the calback models and some new place for them to live on documents. Documents are already very complicated and also foundational. Any changes there will require very extensive testing. Again. `DataModel` exists now. 

I am not going to personally put more effort into this at this point, and I am skeptical that anyone else will, either (they can certainly re-open if that is not the case)
