### ISSUE TITLE
Provide an API to disable the hover tool programmatically

### ISSUE THREAD

**Issue by nleclercq** [bokeh/bokeh#6004]
The hover and crosshair tools are enabled by default when added to the toolbar. 
There's currently no equivalent to active_drag, active_scroll, or active_tap to control the hover tool state.

**Comment by nicain** [comment]
Is there any option to make, for example, the crosshair tool not-visible on the toolbar, and therefore note turn-offable by the user?  I have a very bloated toolbar, and  I never intend the user to be able to disable the crosshair tool.  Even if the visibility on the toolbar is required, it would be nice to have a required option so that it cannot be meddled with by users...

**Comment by bryevdv** [comment]
@nicain the only option currently is to hide the entire toolbar. I'd suggest a separate issue for a feature to show/not show specific tools in the toolbar.

**Comment by bryevdv** [comment]
@nleclercq  apologies I did not realize there was already an issue, this is a dupe of #5599
