### ISSUE TITLE
Box select rendered incorrectly on bokehjs linked example

### ISSUE THREAD

**Issue by flaviut** [bokeh/bokeh#6005]
Tested on latest master.

1. Build bokehjs and the "linked" example.
2. Navigate to the linked example, and use the box select.

Expected behavior:
![](http://i.imgur.com/aVxLQzv.png)

Actual behavior:
![](http://i.imgur.com/3yF1bAc.png)

The following diff fixes the issue:

```diff
diff --git i/bokehjs/src/coffee/models/annotations/box_annotation.coffee w/bok
index 6ba12d6..42a7f9c 100644
--- i/bokehjs/src/coffee/models/annotations/box_annotation.coffee
+++ w/bokehjs/src/coffee/models/annotations/box_annotation.coffee
@@ -55,10 +55,10 @@ export class BoxAnnotationView extends AnnotationView
     @el.style.width = "#{sw}px"
     @el.style.top = "#{stop}px"
     @el.style.height = "#{sh}px"
-    @el.style.borderWidth = "#{@model.line_width.value}px"
-    @el.style.borderColor = @model.line_color.value
-    @el.style.backgroundColor = @model.fill_color.value
-    @el.style.opacity = @model.fill_alpha.value
+    @el.style.borderWidth = "#{@model.line_width}px"
+    @el.style.borderColor = @model.line_color
+    @el.style.backgroundColor = @model.fill_color
+    @el.style.opacity = @model.fill_alpha
 
     # try our best to honor line dashing in some way, if we can
     ld = @model.line_dash
```

I also mentioned this in the gitter channel: https://gitter.im/bokeh/bokeh?at=58cc0e85b809ca5f4a555cca

**Comment by bryevdv** [comment]
ping @mattpap this is in reference to the BokehJS API, I can confirm that the JS example does have the green dotted overlay, which AFAICT should not be the default. I'm less sure about the proposed change. Since we use dataspec's to mix in the line and fill properties (maybe a mistake?) it seems like the `.value` is necessary. But perhaps I am missing something?

**Comment by mattpap** [comment]
The issue isn't with bokehjs API or `BoxAnnotation`, but with overly complicated properties' initialization logic. All dataspecs of overlays in tools are initialized improperly, e.g. `line_color: "black"` instead of `line_color: {value: "black"}`. However, the code in `BoxAnnotation` is suspicious on its own, because why would we allow dataspecs here and consider only scalars. We also have to make sure that whatever is done, CSS and canvas rendering modes work the same.

**Comment by mattpap** [comment]
After a closer look, `BoxAnnotation` doesn't make any sense. Most of its properties are vectorized, but I don't see any code in the implementation responsible for rendering of multiple boxes.
