### ISSUE TITLE
Optionally turn off validation

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#6042]
Data validation is important, but also costly.  For applications that are already verified to work correctly and that run in resource constrained environments (such as alongside any other resource-constrained application) it would be nice to be able to turn it off.

I can achieve a significant speedup by commenting out the lines that start with `self.validate` in `bokeh/core/property/bases.py`.  It would be nice to be able to achieve the same thing by setting a configuration variable.  Does bokeh have a standard place to put configuration options like this?  One way to approach such a change might look like the following in bokeh code:

```python
from .config import config

if config.get('validate', False):
    self.validate(...)
```

And the following in user code

```python
from bokeh.config import config
config['validate'] = False
```

**Comment by bryevdv** [comment]
Would an env var suffice? We have machinery already for that in the `settings` module

**Comment by mrocklin** [comment]
So I guess I could change `os.environ` within my code and expect it to affect Bokeh?  Question: when does bokeh check the environment variables?  If it is only at import time then the two solutions will race.  If someone imports Bokeh, then imports my code (dask) and then Dask affects the environment variable then we won't see an effect.  

Another (perhaps better) option would be to set this as a parameter on a Server or Model object.  This would also allow me to be cavalier with my plots (about which I am confident) while not screwing up the plots that users might be making in other places in the same process.

**Comment by bryevdv** [comment]
Settings are checked upon use, see

https://github.com/bokeh/bokeh/blob/master/bokeh/settings.py

Some kind of flag on `Document` might make the most sense if we go that route.

**Comment by mrocklin** [comment]
I'd be happy to specify validation on a per-document basis.  Should this just be a `.validate` property hanging off of the document or is there a better place to put something like this?

**Comment by mrocklin** [comment]
Do properties have reference back up to their document?

**Comment by bryevdv** [comment]
@mrocklin properties themselves don't but the models they are on (which the properties can access), do

I think a (python) property on document is perfectly fine (one of the reasons `Document` is preferred is since it is *not* a Bokeh model, this should not be a Bokeh property that gets serialized). I'd suggest a longer or more descriptive name, e.g. `perform_property_validation` which defaults to `True`

**Comment by mrocklin** [comment]
It looks like Properties don't have a link back to their model?  If so then presumably we need to tell a property if it should be validated on construction.  I've been unable to track down where this occurs (is it centralized somewhere?)

**Comment by bryevdv** [comment]
Well, it occurs to me that there is another problem, namely that models don't necessarily start out in documents, but validation happens all the time. So I think an env var or config is probably the only option. I lean slightly toward the former because the marginal effort of adding a new env var is much less than creating a whole config file system where there currently is none.

**Comment by bryevdv** [comment]
This was done at some point:

https://bokeh.pydata.org/en/latest/docs/dev_guide/env_vars.html#bokeh-validate-doc

**Comment by mrocklin** [comment]
Question:

From the docs

> BOKEH_VALIDATE_DOC

> Whether to perform a validation check on the document before outputting. Accepted values are yes/no, true/false or 0/1. *Setting this variable to a negative value for a document that is known to be correctly configured may yield performance improvements.*

Is there a way to set this on a per document basis?  If so, how?  My apologies if this is mentioned somewhere obvious.  I checked that page and then grepped a bit through source but didn't find anything.

**Comment by mrocklin** [comment]
I'd like to enable this for Dask's dashboard programmatically, but don't want to affect other folks' plots.

**Comment by bryevdv** [comment]
There's not any document setting, so if that's what's desired I suggest a new issue. It's worth explicitly pointing out there are two kinds of validation:

* The "whole-document" consistency checks that happen right when a document is serialized, and
* various type validation checks that happen when properties are set, some of which might be somewhat expensive

It would be good to be clear about which one (or both) you are hoping to circumvent

**Comment by bryevdv** [comment]
I'd rather have a new clean and simple issue and let this one have been for clarifying discussion. FYI I don't think its possible to turn off type validation per-document, but I think it could be turned off per-process, i.e. a specific running bokeh server could be configured to not perform them. I assume that's sufficient since I don't think users would be interacting with your bokeh server.

**Comment by mrocklin** [comment]
Following on in https://github.com/bokeh/bokeh/issues/8138
