### ISSUE TITLE
Feature request: Add support for user-defined custom mappers

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6081]
Currently it's possible to set the x/y_mapper_type as a string, with the options linear, log or datetime. A user requested the ability to define a custom mapper (to implement a cube-root axis), which is not currently possible.

Mappers aren't currently models in Bokeh, but only BokehJS.

**Comment by pstjohn** [comment]
Adding a few more examples as the user who requested the feature.
The matplotlib example for a custom scale is [here](http://matplotlib.org/examples/api/custom_scale_example.html),
[A similar example for a square-root axis](http://stackoverflow.com/questions/42277989/square-root-scale-using-matplotlib-python)

In general, its nicer to define the data scale explicitly rather than re-name axes tickmarks. (Especially when zooming, I would imagine).

Here's a matplotlib example where I want log(Ignition delay) vs. 1/T. While I could just label the axis as '1/T' and plot the resulting fraction, its helpful to see the real temperatures on the x axis.

![all_summary](https://cloud.githubusercontent.com/assets/2576846/24417050/27a34e78-13a4-11e7-8658-c84a207dbb76.png)

**Comment by bryevdv** [comment]
Since we already have `Transform` and mappers are fairly similar, the lest disruptive path is probably to make mappers be subclasses of transforms. Otherwise we end up with two very similar but apparently different things.

**Comment by bryevdv** [comment]
Scheduling for `0.12.6` AFAIK mappers are the last non-python-model holdouts, it's time to close that chapter in bokeh history. The gorpy mapper type hinting (e.g. for log mappers) can go away when this is done, as well.

**Comment by bryevdv** [comment]
related: #5268

**Comment by bryevdv** [comment]
With #6260 it is now possible to implement custom extension models for user-defined custom Scales. It might also be nice to have a `CustomJSScale` but that can be a separate issue for later.
