### ISSUE TITLE
ClientSessions aren't supported via `on_event` interface

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6092]
Bokeh 0.12.5

to reproduce:

1) run `bokeh serve` in a terminal
2) in another terminal, run `python demo_script.py`
3) Pan inside of the plot and not that the event_callback message isn't printed

contents of demo_script.py
```python
from bokeh.plotting import figure, curdoc
from bokeh.client import push_session

plot = figure(height=800, width=1000, tools="pan")
plot.rect(x=[1, 2], y=[1, 1], width=1, height=1)

def event_callback(event):
    print("EventCallback:Pan")

plot.on_event("pan", event_callback)

def property_callback(attr, old, new):
    print("PropertyCallback:RangeChange")

plot.x_range.on_change("start", property_callback)

doc = curdoc()
doc.add_root(plot)

session = push_session(doc)
session.show()
session.loop_until_closed()
```

**Comment by canavandl** [comment]
It appears that they Bokeh Server process only listens for UI Events, but doesn't have to machinery to pass a UI Event to the client session.

**Comment by bryevdv** [comment]
I am no very much of the mind that the only appropriate use of `bokeh.client` is to pull sessions in order to make user/session specific modifications to them before embedding with `server_session`. Running callbacks in external processes outside the Bokeh server was never a good idea, and is even less defensible now that the bokeh server can be used programmatically as a library. This is simply out of scope.
