### ISSUE TITLE
`ImageURL.{w,h}` use data units by default

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6095]
This is broken yet again. `w` and `h` uses `DistanceSpec` which uses `data` units by default. Even help entries for both of those properties say that values are in pixels.

**Comment by bryevdv** [comment]
@mattpap I don't see where the help entries say that. I see:
```
    h = DistanceSpec(help="""
    The height of the plot region that the image will occupy.
    .. note::
        This is not the number of pixels that an image is tall.
        That number is fixed by the image itself.
    .. note::
        This may be renamed to "dh" in the future.
    """)
```
Which is only saying that `h` is *not` the height of the image, in pixels (the image simply is however tall it is in pixels). The intent with `w` and `h` is to set what size region the image should be scaled to. Why should that not be in data units?If using image URL as a cheap "tile" source data units are in fact what you'd want. I'm not convinced this should be changed.

**Comment by bryevdv** [comment]
Actually I think what used to happen, and what might be reasonable, is that if `w` and `h` are not specified, then the pixels dimensions of the image are used, and interpreted as data space values.

**Comment by bryevdv** [comment]
ping @bokeh/dev I'd like to propose:
```
h = DistanceSpec(default=None, help="""
    The height of the plot region that the image will occupy in data space.
   
    The default value for this is ``None``, in which case the height of the image (in pixels)
    will be used as the *data* space height. 
        
    """)
```

**Comment by StevenCHowell** [comment]
This seems reasonable.  

Would this allow for setting the plot region to be square?  This has been something I have wanted to be able to do when plotting geometric shapes/structures (and I'm sure there is an issue for it somewhere).  Simply setting `width` and `height` does not work b/c it does not include the axes (and legend if it is outside).

**Comment by bryevdv** [comment]
@StevenCHowell no this is unrelated to fixing the central region plot area aspect, which has as separate issue (https://github.com/bokeh/bokeh/issues/474)

Implementing the idea I suggested above is problematic. I forgot the image (and hence its dimensions) are not immediately available. I think the answer it to keep this a `DataSpec` but change the default units to `screen`. That we can make resonably work with `None` meaning "same units as the image itself" because  the dimension computation can be punted until render time (as it sort of already is)
