### ISSUE TITLE
Have deploy script use Github API token to avoid rate-limiting issues

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6102]
Currently if there are release issues and the deploy script has to be run more than once, the script fails due to GitHub API rate-limiting. This is because the deploy script queries a bunch of issues to make sure they're resolved.

It was suggested that API called with a GitHub token aren't rate-limited, so a solution would be to have the deploy check if a ``GITHUB_API_KEY`` env var is set and, if so, use it.

**Comment by bryevdv** [comment]
I think the best way is to modify `read_url` to check for `os.environ.get("BOKEH_GITHUB_API_TOKEN", None)` and use proper `Request` as described here:

http://stackoverflow.com/questions/23659744/access-github-api-using-personal-access-token-with-python-urllib2

if the token is not `None` add the value as "token" as that link describes, otherwise leave it off.
