### ISSUE TITLE
Datepicker : Gives ValueError('Unknown string format',) on changing to update textbox

### ISSUE THREAD

**Issue by divyamounika** [bokeh/bokeh#6134]
# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### Screenshots or screencasts of the bug in action

Hello, I am new to bokeh and python. I was trying to update a graph based on date picket value but it gives me above error. I tried to generate a simple textinput update based on datepicker value but still it gives me same error. I am using Internet explorer and Jupyter notebook and starting bokeh server using bokeh serve --show file.ipynb
<img width="673" alt="error" src="https://cloud.githubusercontent.com/assets/25967668/24967170/d5475c42-1f6e-11e7-8b9a-d903a1c89ac3.PNG">

**Comment by bryevdv** [comment]
As stated in the instructions above:

* you will need to provide a complete code sample in order to investigate potential bugs, without that it's not possible for us to do anything

and

*  the proper place for general technical support (which this seems like) is not here, it is the mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
