### ISSUE TITLE
Improve Jupyter support to print or "Download as > PDF via LaTeX (.pdf)"

### ISSUE THREAD

**Issue by StevenCHowell** [bokeh/bokeh#6172]
When using Bokeh in Jupyter notebooks, generating a PDF and/or printing out the notebook produces poor results.  Currently, directly printing a notebook makes all the content larger than expected/natural and uses the space terribly, producing a terrible printout.  Using "Download as > PDF via LaTeX (.pdf)" strips out all the images, only printing the text.  I discussed this some with @bryevdv and Jupyter developers on Gitter so I created this issue to promote further discussion.

In science, I find it helpful to include printed results in a physical notebook to be able to provide a chronological reference for later review and showing collaborators, without having to find the project on my computer.  It would be nice/helpful to have a cleaner way to create a PDF and/or print out the notebook, either printing using smaller, better-formatted text, or by improving the LaTeX rendering.  I am not sure which would be easier.

Jason Grout shared that they "...have the same sort of issues with bqplot and altair - rendering that is done in the front end."

Brian E. Granger shared that "JupyterLab has an API that custom output renderers can use to save the PNG automatically.  That is what Altair is doing. https://github.com/altair-viz/jupyterlab_vega/blob/master/labextension/src/output.js#L69"

Perhaps this API provides the best solution.

**Comment by bryevdv** [comment]
There is no way we can solve this in general. Bokeh is capable of outputting complex layouts of multiple plots and widgets. Generating PNG output for the general case involves farming the entire document out via Selenium to a separate headless browser process for remote evaluation and screen capture. That can be done from *Python*, but doing it at static render notebook render time means doing it from *JavaScript*, and that is simply 100% not possible. 

***At absolute best***, we could potentially support only the output of single canvas plots, using basically the same technique there. Not gridplots (because those are multiple canvases) and not any widgets. But I wouldn't be especially happy with any solution that can't give immediate detailed feedback about unsupported cases, because I don't really want to invite the support burden of "why doesn't this work" when users try configurations that *can't* work.

**Comment by bryevdv** [comment]
I'm going to close this because I simply do not see any viable technical path forward. The only reasonable suggestion I can make is to use `output_mode="svg"` for plots in notebooks that you want to export in this manner. I think that should work, modulo some know SVG output problems (that already have their own issues).
