### ISSUE TITLE
bokeh-api documentation improvement suggestions

### ISSUE THREAD

**Issue by aerusso** [bokeh/bokeh#6184]
The [Developing with JavaScript](http://bokeh.pydata.org/en/latest/docs/user_guide/bokehjs.html) page is very helpful, but a few (important) things were not mentioned on this page:

1. All *three* of bokeh-x.y.z.min.css bokeh-x.y.z.min.js and bokeh-api-x.y.z.min.js must be used and **in that order**.
2. Rendering into an html element is supported by  `Bokeh.Plotting.show(object,html_object)`
3. Changes to data sources can be propagated to graphs by calling `data_source.trigger("update")`

Is there a way for me to submit a full minimal html example to be included on that page?

**Comment by bryevdv** [comment]
> Is there a way for me to submit a full minimal html example to be included on that page?

Not trivially. I've been meaning to work on a new `bokehjs-plot` Sphinx directive that would make it easy to embed BokehJS examples in our docs, but I have not had the opportunity to do so yet. It's possible to include raw HTML in Sphinx docs though, so that's probably the best approach to get "real" plots on that page for now. If you are interested I can provide more information.

**Comment by bryevdv** [comment]
For reference, the ReST source for that page is here:

https://raw.githubusercontent.com/bokeh/bokeh/master/sphinx/source/docs/user_guide/bokehjs.rst

And some docs about raw HTML pass through are here:

http://docutils.sourceforge.net/docs/ref/rst/directives.html#raw-data-pass-through

**Comment by aerusso** [comment]
Maybe in the short term, just the HTML can be included, and later on we can figure out the best way to properly include an illustration of the example? My pull request #6203 does exactly this, and also identifies some other outdated comments about BokehJS API.
