### ISSUE TITLE
Make bokeh_plot work in Sphinx by default without GOOGLE_API_KEY

### ISSUE THREAD

**Issue by cdeil** [bokeh/bokeh#6193]
I have a project where I'd like to use `bokeh.sphinxext.bokeh_plot` for the Sphinx docs and ran into this error:

https://travis-ci.org/gammapy/gamma-cat/builds/225367662#L750
```
Sphinx error:
The GOOGLE_API_KEY environment variable is not set. Set GOOGLE_API_KEY to a valid API key, or set BOKEH_DOCS_MISSING_API_KEY_OK=yes to build anyway (with broken GMaps)
make: *** [html] Error 1
```

Yes, I can make it go away by setting:
```
export BOKEH_DOCS_MISSING_API_KEY_OK=yes
```

But it seems weird, to have to do something concerning GOOGLE_API_KEY if I'm not using GMaps.

Wouldn't it be better to change the setup so that people like me that don't use GMaps don't have to do anything to use Bokeh, and then people that do want to use GMaps have to set this up?

**Comment by bryevdv** [comment]
Sure it would be perfectly reasonable to make things more configurable.  Ideally I think this could be controlled by some config values in the Sphinx `conf.py`, something like:
```
bokeh_plot_replace_google_api_key = True              # defaults to False
bokeh_plot_google_api_key_var = "MY_GOOGLE_API_KEY"   # defaults to GOOGLE_API_KEY
```

Unfortunately, given that there are (AFAIK) only a handful of users of this extension, and there are other pressing problems affecting many thousands of users, I probably won't be able to prioritize working up a PR for this myself anytime soon. That's especially true since there is a serviceable workaround. However, making the change should within reach to most Python devs. I'd be happy to answer questions and review a PR if you are interested in making one. The relevant code is here:

https://github.com/bokeh/bokeh/blob/master/bokeh/sphinxext/bokeh_plot.py#L92-L98

Docs for registering new sphinx config vars are here:

http://www.sphinx-doc.org/en/stable/extdev/appapi.html#sphinx.application.Sphinx.add_config_value

Such vars are then accessed via the `Config` object:

http://www.sphinx-doc.org/en/stable/extdev/appapi.html#sphinx.config.Config
