### ISSUE TITLE
"Save" button stops responding when add_glyph is used

### ISSUE THREAD

**Issue by xtophercook** [bokeh/bokeh#6234]
I've noted a small bug with the "save" feature when using image files on a Bokeh plot. I've made a simple set of graphs which plots a simple scatter, then overlays with some image figures.

Here's an example.

```
output_notebook()

iris = [[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2]]

df = pd.DataFrame.from_records(data=iris, columns=['sepall', 'sepalw', 'petall', 'petalw'])
marker = 'http://www.libriscrowe.com/non/Images/Iris05.gif'
df['url'] = marker 
source = ColumnDataSource(df)
p = figure(title="Iris data", x_axis_label = "Width", y_axis_label = "Length", plot_width=800, plot_height=500)
p.scatter('sepall', 'sepalw', color='purple', line_color="black", source=source)
flower = ImageURL(url='url', x='sepall', y='sepalw', w=0.05, h=0.1, anchor="center")
p.add_glyph(source, flower)
show(p)

```
This all draws perfectly well - but the "save" function does not work when the add_glyph line is included. The button is visible, but nothing happens when you click it. I have tinkered: when you remove the add_glyph lines from this script, the save button works again. The same is true for the exported HTML versions of the graphs - not just a Jupyter thing.

As I say, a small thing.

**Comment by xtophercook** [comment]
Hey @bryevdv, 

I've made a version which replicates the issue for me. Same in Chrome or Edge. I'm running 3.6.0 Anaconda custom (64-bit). 

Best,

Chris

**Comment by bryevdv** [comment]
@xtophercook thanks,  can reproduce, unfortunately there is not really anything we can do about it with the current save tool. The actual issue is not `add_glyph` in general, but `ImageURL` specifically. Running your code and looking at the JS console shows:

<img width="454" alt="screen shot 2017-05-03 at 14 44 17" src="https://cloud.githubusercontent.com/assets/1078448/25683039/46b3f02e-300f-11e7-98fd-e26a2c1a07d1.png">


And a little digging turns up this:

http://stackoverflow.com/questions/2390232/why-does-canvas-todataurl-throw-a-security-exception

Long story short, 

> If the image is coming from another server I don't think you can use `toDataURL()`

It's conceivable that we could set `c.setAttribute('crossOrigin','anonymous')` on the canvas. That would require some consideration (at most probably as an explicit opt-in configuration) However, even if we do that, this **still will not work** unless the host serving the images (which we and users have no control over, in complete generality) have specified a permissive CORS policy.

Ping @canavandl @mattpap in case you have any thoughts to add. Given the ongoing work on programmatic image generation I am inclined to just close this as `wontfix`

**Comment by xtophercook** [comment]
That's fair enough. Just thought I'd raise it - am really enjoying bokeh, so thanks!

**Comment by bryevdv** [comment]
@xtophercook thanks for the kind words, please check out #6189 #6229 for the other work I mentioned

**Comment by bryevdv** [comment]
Going to go ahead and close per discussion above
