### ISSUE TITLE
Feature Request: Documentation as pdf

### ISSUE THREAD

**Issue by castalheiro** [bokeh/bokeh#6250]
i want to request you to provide an option in sphinx make file to produce latex sources.

Using the project source files from version 0.12.5 i had to perform the following changes to successfully generate a pdf containing project documentation:

- install nodejs (6.10.3), flexx (0.4.1), numpy (1.11.3+mkl), scipy (0.19.0), matplotlib (2.0.1)

- set environment variable BOKEH_DOCS_MISSING_API_KEY_OK = yes

- remove sphinx 'bokeh.sphinxext.bokeh_palette_group' and 'bokeh.sphinxext.collapsible_code_block' extensions from conf.py file

- add the following lines to make.bat file 

if "%1" == "latex" (
	%SPHINXBUILD% -b latex %ALLSPHINXOPTS% %BUILDDIR%/latex
	if errorlevel 1 exit /b 1
	echo.
	echo.Build finished; the LaTeX files are in %BUILDDIR%/latex.
	goto end
)

- convert bokeh_serve.svg, bokeh_serve_client.svg, bokeh_serve_scale.svg, and document.svg to pdf because \sphinxincludegraphics latex instruction is unable to handle svg images

i tested the changes above in both windows 10 and ubuntu 16.04, with python 2.7.13

**Comment by bryevdv** [comment]
@castalheiro Given that bokeh was created for and specifically targeted towards *interactive* visualizations in browsers, the documentation is also heavily geared towards that as well. In particular, the documentation contains ~100 live Bokeh plots inline. None of these will render correctly (or probably at all) in LatTeX output. Because of these limitations, non-HTML output is not really a priority for us at all. If you'd like to submit a Pull Request, we'd be happy to consider it, as long as it does not interfere with the current HTML docs building process in any way. 

For instance:

> remove sphinx 'bokeh.sphinxext.bokeh_palette_group' and 'bokeh.sphinxext.collapsible_code_block' extensions from conf.py file

This is definitely not acceptable to do unilaterally. Perhaps there could be an environment variable that caused them not to be included (they would always need to be included by default)

**Comment by bryevdv** [comment]
@castalheiro as I mentioned this is not something we would take on ourselves, so I am going to go ahead and close this in order to not clutter the tracker. However, as I also mentioned, we'd certainly be happy to consider a PR that did not disturb the current docs build.
