### ISSUE TITLE
Add parameter to autoload_server to control loading of JS/CSS resources

### ISSUE THREAD

**Issue by jphalip** [bokeh/bokeh#6341]
When embedding a plot from a separate server, the JS/CSS resources are then systematically loaded from that same server as well. For optimization purposes, I'd like to load those resources from a separate caching server instead living at a separate domain (e.g. 'cdn.pydata.org'). To achieve this I'd need a way of telling the plot server to *not* return those resources.

So it'd be great if a new `load_resources` parameter (defaults to `True`) could be added to `bokeh.embed.autoload_server()`. This parameter would then be passed on as a querystring parameter to the `autoload.js` script, which would then be used by the `AutoloadJsHandler` on the plot server to decide whether or not to include those resources when rendering the `AUTOLOAD_JS` template.

Does that sound reasonable? If so then I'm happy to provide a patch for this.

Thanks!

**Comment by bryevdv** [comment]
Well, half the point of `autoload_server` is really to load the resources (It's right there on the label! :) ). If you want to load resources yourself,  I think that's reasonable, but rather than adding a parameter to `autoload_server` that makes it not-load-things in some situations (which is complicated/confusing) I'd suggest a new function with a different name, e.g `embed_server` or something. I think it could (should) re-use the existing machinery (i.e. that kind of parameter would be fine, internally) so I don't think it would be much more work than what you've proposed. Thoughts?

**Comment by jphalip** [comment]
That makes sense to me! Since the actual purpose of this is to only load the websockets connection, maybe this new function could be named `websockets_server`?

**Comment by jphalip** [comment]
Yes `connect_server` is probably better. I'll work on a patch to see how that works. Thanks!

**Comment by bryevdv** [comment]
Great, look forward to seeing it, thanks!
