### ISSUE TITLE
Add signatures to model objects 

### ISSUE THREAD

**Issue by tonyfast** [bokeh/bokeh#6372]
#### Description of expected behavior and the observed behavior

This [gist](https://gist.github.com/tonyfast/c8a0db352e26bb211f1d07166b3ee7e0) illustrates the value of providing function signatures when interactively developing in the notebook. 

The experience at the moment relies on the the pydata docs or `models.Glyph.properties()` to expose a glyph's model parameters.  Providing function signatures or argspec options would enhance an interactive development experience with Bokeh, especially for new users.

The screenshot below forcefully illustrates this use case in the notebook; the benefits extend to other development tools.  

![](https://cloud.githubusercontent.com/assets/4236275/26704534/b4edbd90-46fd-11e7-8a13-d81e5bdb2a0a.png)

##### Complications

The major complication with this feature request is that multiple version support requires some logic.  Fortunately, all of these considerations are well document in a few PEPs.

**Comment by bryevdv** [comment]
@tonyfast definitely agree that would be useful. We already do something similar to generate comprehensive docstrings for the glyph methods:

<img width="1116" alt="screen shot 2017-06-02 at 13 41 08" src="https://cloud.githubusercontent.com/assets/1078448/26739892/284fd958-4799-11e7-9956-8cd08feba81d.png">

My only concern is that `.properties` is not a super cheap thing to call, and the amount of dynamic function signature mucking we do already seems to make the Bokeh import a little slow (I'm pretty sure this is the cause but do still need to validate for certain). But a few questions:

* `__signature__` is python 3 only correct? Is there anything similar in python 2.7? How could this be handled across versions?

* Do you have any ideas about how this could be done "once" ? i.e. at install or packaging time, so that the signatures don't have to be computed dynamically on every import?

**Comment by tonyfast** [comment]
I was unaware of the docstring in the `plotting` module, thats rad.  It would certainly be possible to attach a signature to a `plotting` instance.  If `__signature__` were attached when `__doc__` is then the glyph parameters will seen in the signature without expanding the tooltip.

Reading through the HasProps class it seems that it would be tough to assign the signatures because the classes haven't been instantiated.  It is possible to force the `Model.__init__.__signature__`, but that is kind of weird.

An intermediate solution is to create [type stubs](https://github.com/python/typeshed) for the models; they contain annotations and default values.  When a model is created  `__init__.__signature__` would attach the type file's signature.  I believe Bokeh's ordered architecture would make it possible to programmatically generate the stub files.  

I am not really sure about cross version support to be honest.  I'll dig around.

**Comment by bryevdv** [comment]
Another reason this has to wait until python 2 is dropped: model properties would need to all be keyword-only args.

**Comment by bryevdv** [comment]
Adding this to 2.0 just in order to remember to think about it. It's possible some p[art of this can be done in the short term. Will split off issues as appropriate.

**Comment by mattpap** [comment]
How this issue stand in the context of static typing bokeh, which will allow us to fill in all those signatures?

**Comment by bryevdv** [comment]
I have no idea. I moved it to 2.0 to make sure to investigate and figure
out what if anything should be done within that time frame (maybe this just
gets closed at this point)

**Comment by bryevdv** [comment]
@mattpap I think this issue is orthogonal to that. Static typic for Bokeh only really applies to functions in the API. This issue is about providing real signatures for Bokeh modes, with named kwarg-only parameters for all the properties, instead of just a bare `**kwargs` in the initializer. My main concern is simply performance. Ideally these could be computed and inserted at build time (or maybe via compiling `.pyc` before shipping, I don't know offhand)

**Comment by bryevdv** [comment]
noting that #9586 adds singatures to glyph methods and it was pretty simple. Main concern with doing it for all models is potential for import time increase, though I think we may already be doing most of the work already, so maybe no big deal
