### ISSUE TITLE
Removing glyphs by figure.renderers has problem with box select tool

### ISSUE THREAD

**Issue by samuelandjw** [bokeh/bokeh#6423]
bokeh 0.12.5, Python 3.6.1, Windows 7, Chrome

(Please refer to the code below) When the program started, the figure was empty. I pressed the button to generate a random point and plot that point on the figure (I named it "random_point" to help searching for it easier). By pressing the button again, I searched the random point plotted previously, deleted it and plotted a new random point. In the callback function of the code, the previously plotted random point was found by `select` method of the `fig` object, the found glyph was removed from `fig.renderers` list (I don't know a better way to remove glyphs from a figure), and another point was plotted.
When I pressed the button for the third time, although the previous point was removed from `fig.renderers` and the previous point disappeared from the figure as expected, `fig.select` still found the previous point. This is due to that the box select tool still held reference to the previous point. If I uncommented `fig.toolbar._property_values['tools'][0].renderers.remove(old_point[0])`, the previous plotted point would be removed successfully.

The code:
```
from bokeh.plotting import figure
from bokeh.layouts import layout
from bokeh.plotting import curdoc
from bokeh.models import Button, Range1d
from random import uniform

def on_lick(*args):
    old_point = fig.select(name="random_point")
    print(old_point)
    if len(old_point)>0:
        fig.renderers.remove(old_point[0])
        # fig.toolbar._property_values['tools'][0].renderers.remove(old_point[0])

    fig.circle(x=uniform(-1,1), y=uniform(-1,1), name="random_point")

fig = figure(tools="box_select")
fig.x_range = Range1d(-1, 1)
fig.y_range = Range1d(-1, 1)

btn = Button(label="generate a random point")
btn.on_click(on_lick)

curdoc().add_root(
    layout([[fig,btn]])
)
```

**Comment by bryevdv** [comment]
The issue is the Box Select tool that you have added. Selection tools also hold on to references to renderers, which means they will still be returned by `select`, even if you remove them from `.renderers`. If you change the line to 
```
fig = figure(tools="")
```
You will see the example start to behave as expected. I will say that a much more well-demonstrated for updating points is to leave the glyph and the data source intact, and to update the `.data` attribute of the data source This is a well-worn path and demonstrated in almost every example we have.

If you really need to swap out renderers, you will need need to remove the renderer from the tool's renderer list but a better way to do that is

```
fig.toolbar.tools[0].renderers.remove(old_point[0])
```

Also, since this is more of a general support question, I am redirecting to the mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
