### ISSUE TITLE
Enable exclusion of selenium tests for static image export

### ISSUE THREAD

**Issue by marcuskd** [bokeh/bokeh#6441]
Running Bokeh unit tests on 0.12.6.dev7...

py.test -m "not (examples or integration or js or quality)" bokeh

reports 3 failed tests. In discussion with @bryevdv looks like they are selenium tests for the new static image export feature. Would be useful to add a new mark for them so that they can be excluded easily.

**Comment by bryevdv** [comment]
@canavandl should we make a new tag for this, or add it to `integration` ?

**Comment by bryevdv** [comment]
Some projects, e.g. have a `slow-tests` tag for a subset of unit tests. I don't mind adding it to `integration` though, either. 

It would be nice to also see if that plugin to make a "negative" or "unlabeled" category works or not. I'd like to be able to do `py.test -m unit` and get everything that is not otherwise tagged.

**Comment by bryevdv** [comment]
I think I will try to add support for `pytest-unmarked` as well. That was previously closed as `wontfix` in https://github.com/bokeh/bokeh/issues/3906 because the plugin used a private `pytest `API but the list of things to exclude to get the plain unit tests is getting too long. If it stops working at some point there's actually minimal effect except to local usage.

**Comment by bryevdv** [comment]
Outcome:
```
py.test -m unit # run all unit tests (including selenium)

py.test -m"unit and not selenium" # exclude selenium unit test

```
