### ISSUE TITLE
npm detection doesn't work on windows (in native console)

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6462]
It's not clear right now if this is a problem with conda package installing npm in wrong directory or detection algorithm is too presumptuous. Previously it used to work in git bash.  `examples/custom/font-awesome` is affected.

**Comment by mattpap** [comment]
ping @mingwandroid

**Comment by mingwandroid** [comment]
Can you give me some reproduction steps? I'm not terribly familiar with node.js.

**Comment by bryevdv** [comment]
* clone bokeh repo
* conda install bokeh (wait for 0.12.6, building now...)
* conda install nodejs

run `examples/custom/font-awesome/font-awesome.py`

**Comment by p-himik** [comment]
It worked (and still should) in Git bash because it can execute shell scripts. When you install Node.js via Anaconda on Windows, you get two files for npm - `npm`, which is a shell script, and `npm.cmd`, which cmd executes when you run `npm` inside it.

On Windows, `Popen` uses [`CreateProcess`](https://msdn.microsoft.com/en-us/library/ms682425.aspx). From its documentation: If the file name does not contain an extension, .exe is appended. Therefore, if the file name extension is .com, this parameter [application name] must include the .com extension.

Also, check this [interesting line](https://github.com/bokeh/bokeh/blob/master/bokeh/_version.py#L79):
```python
# remember shell=False, so use git.cmd on windows, not just git
```
It shouldn't work with any value of `shell` if Git is available only as `git.cmd`. But on Windows (at least, on my PC), it's available as `git.exe`, so omitting the extension is ok.

**Comment by chesucr** [comment]
I think I had a similar issue here. I am working on DOS (Anaconda Prompt) on Windows. I followed the [installation steps](https://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html#id8). `npm install --no-save` worked well. But when I did

    python setup.py develop --build-js

The message "Building BokehJS..." appeard but it got stuck. So Bryan told me to build it with `gulp build` directly. So I had to:

    cd bokeh\bokehjs\node_modules\.bin
    gulp build

I went back to bokeh folder again

    python setup.py develop --install-js

And it seems that npm is missing

    python -m bokeh info

    Python version      :  3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]
    IPython version     :  (not installed)
    Bokeh version       :  0.12.14-25-g675aacf72
    BokehJS static path :  C:\[...]\bokeh\bokeh\server\static
    node.js version     :  v8.9.1
    ERROR:[WinError 2] The system cannot find the file specified

**Comment by chesucr** [comment]
A post update. I can confirm that with the release `1.0.0dev2` this is working on Windows:

    npm install --no-save                   # bokehjs folder
    python setup.py install --build-js      # root folder

So the `gulp` command is not needed anymore

**Comment by bryevdv** [comment]
Also working for me with 1.1dev9

<img width="787" alt="screen shot 2019-03-07 at 3 56 29 pm" src="https://user-images.githubusercontent.com/1078448/53997593-9f92ba00-40f1-11e9-8671-786430f07d37.png">
