### ISSUE TITLE
Add muted_* parameters to multi_line

### ISSUE THREAD

**Issue by Sigmun** [bokeh/bokeh#6476]
It would be nice to have the possibility to set "muted" parameters to a multi_line plot. Do you know if it could be implemented ?

**Comment by nleclercq** [comment]
A recent legend feature allows to do that: `figure.legend.click_policy = 'hide'`

**Comment by bryevdv** [comment]
@Sigmun without more context I can't tell if this is a feature request or a support question. For now, I am closing it as the latter. Please use the mailing list for general support:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

If it's determined that something you want to do is not currently possible, please open a new issue with more information (e.g.  detailed example code that you'd like to be able to write, together with a description of the expected behaviour)
