### ISSUE TITLE
Vertical axes aren't aligned in `plotting/file/categorical`

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6477]

**Comment by bryevdv** [comment]
@mattpap The plots in that example are in a `Row`, so I am not sure why vertical axes should be aligned. Unless you mean the vertical heights should be the same across the row? In which case that is already true after #8085 

<img width="1248" alt="screen shot 2019-02-02 at 11 34 25" src="https://user-images.githubusercontent.com/1078448/52168380-9d969f00-26de-11e9-83e9-ed9adaf8f30a.png">

So I will close this since everything looks as expected. Please re-open if I have misunderstood something.

**Comment by mattpap** [comment]
I meant horizontal axes.

**Comment by bryevdv** [comment]
Well, they are aligned now too :)
