### ISSUE TITLE
bokeh.embed example animated.py fails in bokeh version 0.12.6

### ISSUE THREAD

**Issue by beeekey** [bokeh/bokeh#6484]
Hello

bokeh.embed example animated.py fails in bokeh version 0.12.6 with:

 File "animated.py", line 31, in <module>
    from bokeh.embed import server_session
ImportError: cannot import name server_session

any ideas?

Kind regards
Ben

**Comment by bryevdv** [comment]
`server_session` is newer than `0.12.6` you will need to look at a version of the example from the tag corresponding to the release (instead of `master`) or download the version-specific examples tarball that is published with every release (see: https://bokeh.github.io/blog/2017/6/13/release-0-12-6/)

**Comment by beeekey** [comment]
ty, very much.
