### ISSUE TITLE
WebGL was requested and is supported, but bokeh-gl(.min).js is not available, falling back to 2D rendering.

### ISSUE THREAD

**Issue by ruoyu0088** [bokeh/bokeh#6490]
I can't use `webgl` mode in Jupyter notebook, and the here is the warning:

```
WebGL was requested and is supported, but bokeh-gl(.min).js is not available, falling back to 2D rendering.
```

the source code:

```
from bokeh.io import output_notebook, show
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure
output_notebook()

fig = figure(output_backend="webgl")

circle_source = ColumnDataSource(data={"x":[0], "y":[0], "r":[1], "color":["#000000"]})
fig.circle(x="x", y="y", radius="r", fill_color="color", line_width=0, line_color=None, source=circle_source)
show(fig)
```

**Comment by mattpap** [comment]
You need to split `output_notebook()` into one cell and plotting code into another one.

**Comment by ruoyu0088** [comment]
@mattpap I already splitted the source code into two cell. 

I [found](https://github.com/bokeh/bokeh/blob/master/bokeh/resources.py#L142) that the default components of `BaseResources` doen't include `"bokeh-gl"`. I am using following code to fix this:

```
from bokeh.io import output_notebook, show
from bokeh.resources import Resources
output_notebook(Resources(mode="cdn", components=["bokeh", "bokeh-gl"]))
```

**Comment by canavandl** [comment]
I'm reopening is as a documentation issue. We should add mention of the need to explicitly add bokeh-gl as a component to output_notebook in the notebook user guide.

**Comment by bryevdv** [comment]
Marking as GFI tho note if we move to pure webgl rendering this issue will become moot.

**Comment by mattpap** [comment]
Is this even an issue still? `output_notebook()` is supposed to add all bundles regardless of specific models used.

**Comment by mattpap** [comment]
> (...) if we move to pure webgl rendering this issue will become moot.

This needs to be independently discussed, but it's an unlikely scenario in my opinion, especially if it means dropping SVG support.

**Comment by bryevdv** [comment]
@mattpap No, it does appear to be fixed:

<img width="735" alt="Screen Shot 2020-02-19 at 5 32 57 PM" src="https://user-images.githubusercontent.com/1078448/74892251-f5ca2e80-533d-11ea-9db9-2d85dc2c2fbc.png">

> This needs to be independently discussed, but it's an unlikely scenario in my opinion, especially if it means dropping SVG support.

Last time we talked about it you were in favor of getting down to one codepath. In any case for SVG at this point, rather than rely on some Rube-Goldberg Python->JSON->headless browser->Canvas->canvas2svg mess that relies on unsupported 3rd party library, I'd consider writing a simple non interactive JSON->SVG backend directly using one of the Python SVG libraries. Something I plan on investigating, at any rate.
