### ISSUE TITLE
ModuleNotFoundError ( after update 0.12.5-py36_1 --> 0.12.6-py36_0)

### ISSUE THREAD

**Issue by lhaeberle** [bokeh/bokeh#6524]
After a bokeh update from 0.12.5-py36_1 to 0.12.6-py36_0 I get with `import` a ModuleNotFoundError:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-ba16eef4d7ed> in <module>()
      8 from bokeh.sampledata.les_mis import data
      9 from bokeh.charts import defaults
---> 10 from bokeh.charts.attributes import CatAttr, cat
     11 from bokeh.models import HoverTool, Ticker, AdaptiveTicker, SingleIntervalTicker
     12 from bokeh.models.widgets import Panel, Tabs, Select, RadioButtonGroup

ModuleNotFoundError: No module named 'bokeh.charts.attributes'
```
A downgrade 'fixes' this issue. 
I'm running macOS version 10.12.5, jupyter notebook version 5.0.0
I also installed bkcharts `conda install bkcharts`

Any idea?

**Comment by bryevdv** [comment]
Hrm, I guess we missed that possibility in the `bkcharts` migration. In any case the correct thing to do for the future in all cases (including this one) is to replace all `bokeh.charts` imports with `bkharts` since the `bokeh.charts` compat shim will be removed completely in the not too distant future:
```
In [1]: from bkcharts.attributes import CatAttr, cat

In [2]:
```
