### ISSUE TITLE
Add support for plots in polar coordinates

### ISSUE THREAD

**Issue by GCBallesteros** [bokeh/bokeh#657]
I miss the functionality to do polar plots out of the box. I hacked a script to do them but it can't be easily resized because it relies on drawing circles which always have a 1:1 aspect ratio so figure sizes and data ranges have to be manually fine-tuned.

**Comment by bryevdv** [comment]
This has been identified as a priority for GEOST.

**Comment by bryevdv** [comment]
Comments: fairly easy to add the mapper as well as a `PolarFrame` on the JS side. Fairly easy to expose in **models** interface. And **charts** interface can use it as needed as well, but the hardest place to incorporate it will probably be the **glyphs** interface, and we may punt on that for now (can be done incrementally later)

**Comment by Harrison-G** [comment]
:+1:

**Comment by mredaelli** [comment]
Any news on this issue?

**Comment by w4nderlust** [comment]
:+1:

**Comment by bryevdv** [comment]
I'm inclined to pull back on this somewhat. There are many places internally that assume a separable coordinate system (because ultimately the HTML Canvas API only separable cartesian coordinates). Tracking those all down and making sure they are all changed properly is both risky and potentially expensive (in terms of effort). *However*, it is now possible to do things like this:
```
from math import pi

from bokeh.io import show
from bokeh.models import ColumnDataSource, CustomJSTransform
from bokeh.plotting import figure

p = figure()

source = ColumnDataSource(data={
    'color' : ['red', 'blue'] * 20,
    'r'     : [1, 2]*20,
    'theta' : [2*pi/360 * x for x in range(0, 360, 9)],
})

polarx = CustomJSTransform(args=dict(source=source), v_func='''
var new_xs = new Array(source.data.r.length)
for(var i = 0; i < new_xs.length; i++) {
    new_xs[i] = source.data.r[i] * Math.sin(source.data.theta[i] )
}
return new_xs
''')

polary = CustomJSTransform(args=dict(source=source), v_func='''
var new_xs = new Array(source.data.r.length)
for(var i = 0; i < new_xs.length; i++) {
    new_xs[i] = source.data.r[i] * Math.cos(source.data.theta[i] )
}
return new_xs
''')

p.circle(x=dict(field='r', transform=polarx), y=dict(field='r', transform=polary),
         color='color', size=15, alpha=0.8, source=source)

show(p)
```

<img width="608" alt="screen shot 2018-06-20 at 14 55 13" src="https://user-images.githubusercontent.com/1078448/41686722-f4b5e7ca-7499-11e8-82ea-cd6689046694.png">

So what I would  be much more interested to discuss is what (Python-side) conveniences can we add, what examples can we add that demonstrate these techniques, etc. Also in knowing what if any cases do not fit into this kind of approach so we can be clear about that in the docs.

**Comment by bryevdv** [comment]
Just noting that the current work allows specifying a polar transform centered at any location on a plot. This takes care of the data side of things. In the interest of keeping issues focused, I will add a separate issue for the follow-on work to add a "polar axis" annotation that can be used in conjuction.
