### ISSUE TITLE
ColumnDataSource.stream() setter argument is not documented

### ISSUE THREAD

**Issue by snowch** [bokeh/bokeh#6577]
I'm trying to figure out how to store state in my [callback()](https://stackoverflow.com/questions/44841436/how-to-store-and-retrieve-state-in-a-callback) method so that I can maintain a pointer to the current location in my source database.  I've been looking through the bokeh source code and I noticed an argument that looks interesting, but it isn't documented:

```
    def stream(self, new_data, rollover=None, setter=None):
        ''' Efficiently update data source columns with new append-only data.
        In cases where it is necessary to update data columns in, this method
        can efficiently send only the new data, instead of requiring the
        entire data set to be re-sent.
        Args:
            new_data (dict[str, seq]) : a mapping of column names to sequences of
                new data to append to each column.
                All columns of the data source must be present in ``new_data``,
                with identical-length append data.
            rollover (int, optional) : A maximum column size, above which data
                from the start of the column begins to be discarded. If None,
                then columns will continue to grow unbounded (default: None)
        Returns:
            None
        Raises:
            ValueError
```

https://github.com/bokeh/bokeh/blob/master/bokeh/models/sources.py#L211

**Comment by bryevdv** [comment]
This argument should never be used by users, it's documented on the very low level property descriptor:

https://github.com/bokeh/bokeh/blob/master/bokeh/core/property/descriptors.py#L141-L150

@philippjfr AFACT this parameter in the public API is only used in `Document.apply_json_patch`. Perhaps we could rename `.stream` to `._stream` and have `Document` use that internally, then the public `.stream` API could remove `setter` entirely.

**Comment by bryevdv** [comment]
Or we could just add a note that says it's not for general use.

**Comment by mattpap** [comment]
> we could rename .stream to ._stream and have Document use that internally, then the public .stream

I would prefer this approach.

**Comment by philippjfr** [comment]
>Perhaps we could rename .stream to ._stream and have Document use that internally, then the public .stream API could remove setter entirely.

That seems sensible to me.

**Comment by bryevdv** [comment]
@snowch regarding your actual problem that you are trying to solve, the mailing list is probably the best place:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

Since you have already been looking into the bokeh source code, would you be interested in working up PR to remove `setter` from the public API (of `stream` and a few other functions)?

**Comment by snowch** [comment]
Thanks @bryevdv.  

I'm having a bit of a think in terms of my direction with bokeh.  Originally, I was looking for something like shiny + shiny server, but for python.  However, It seems that there is a steep learning curve. to create dashboards programmatically with bokeh server.  For example, my next challenge is to figure out how to add authentication to my dashboard app, and it's proving difficult to work out where I do that.  I've been through the tornado docs and started looking through the bokeh code to try to figure out where the frameworks are integrated and where I need to add login interceptors, however, having to go though code and understand two frameworks is quite challenging.  Also, I'd prefer not to delve into any framework source code.  I've seen a few references to the happiness demo - it sounds like the goal of that demo was to show how you can build a dashboard application with bokeh.  Maybe that is the missing piece to my puzzle?

In parallel, I'm going to start evaluating a different approach by creating a data webservice along with a browser visualisation library like d3.

**Comment by bryevdv** [comment]
@snowch Since there are so many different possible routes to authentication and validation, and since we are not experts, the general notion at least for now is that the best approach is a "hands-off" one, i.e. for people layer authentication in front of Bokeh apps. For example by putting the app behind a reverse proxy that limits access based on authentication. Unless I am mistaken, this is basically the [same approach taken by Shiny server](https://auth0.com/blog/adding-authentication-to-shiny-server/). That said, Tornado *does* have a hook for authentication, it's just not easily exposed to Bokeh apps at the moment. We are looking at making that available for the next release. This is the relevant issue in case you are interested in following progress: https://auth0.com/blog/adding-authentication-to-shiny-server/

**Comment by gregfreeman** [comment]
I'll handle this issue
