### ISSUE TITLE
No link to integration tests' report after PR #6542

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6578]
This https://github.com/bokeh/bokeh/pull/6538#issuecomment-311080939 is the link I'm talking about.

**Comment by bryevdv** [comment]
I remembered this needed to be done at some point, and then forgot to actually put it back in. Will get to it this week sometime.

**Comment by bryevdv** [comment]
@mattpap I'd like to clear out the top level of the S3 bucket into a couple of separate folders, instead of dumping everything into one top level folder. Right now there are: 

* folders for examples results, named by version e.g. `0.12.7dev3-23-a76e83`
* folders for integration reports, named by travis job `23498534`

I'm guessing the examples tests always need to be able to access by the version. I think it could be OK to store the integration results by the tag as well. In which case I'd suggest perhaps
```
bokeh-travis
  + -- results
         + -- 0.12.7dev3-23-a76e83
         |      + -- examples
         |      + -- integration
         |
         + -- 0.12.7dev3-24-435f2f
         |      + -- examples
         |      + -- integration
```
This would leave the top level clear to add additional folders for anything necessary, and would have all travis results for a single version under one folder, with the folders sortable. 

The alternative would be to split by test type at the top level with `examples` and `integration` folders, that had sub-folders for each version underneath. 
```
bokeh-travis
  + -- examples
  |      + -- 0.12.7dev3-23-a76e83
  |      + -- 0.12.7dev3-24-435f2f
  |
  + -- integration
  |      + -- 0.12.7dev3-23-a76e83
  |      + -- 0.12.7dev3-24-435f2f
```

I don't have a strong preference. Thouhgts?

**Comment by bryevdv** [comment]
I guess I should say, I like the second for conceptual separation, but I acknowledge the first is probably more practical (i.e. for periodic cleanup, or for ever needing to access directly from the S3 console)

**Comment by bryevdv** [comment]
Tho I do note that the current bucket folders are like this:
```
0.12.7dev1-0896cf2`
```
They don't have actually the monotonic sequence number since the last tag. I guess ideally I'd like a way to preserve the ordering, but perhaps that's not possible with shallow clones. That's one thing that using the Travis job id possibly has as an advantage, but I doubt it will work for the examples image comparision.
