### ISSUE TITLE
How do I trigger a datetime axis with bokehJS

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#658]
I don't know how to do this.  Should I set a flag in options for makePlot?

**Comment by PBrockmann** [comment]
Would it be possible to accept for datetime axis the ISO 8601 because this is the format proposed by NCSS (https://www.unidata.ucar.edu/software/thredds/current/tds/reference/NetcdfSubsetServiceReference.html#Reference) ?

Here is an example of what can be done with bokehjs 0.6.0 http://jsfiddle.net/c9e3ptfa/
I have not been able to run it using last 0.7.1 I read that interface was broken so need to wait hopefully for 0.8. Is it correct ?

I am very enthousiatic to adopt bokehJS (because I need ajax calls for updating) after having experimented IPython notebook use of bokeh.

**Comment by bryevdv** [comment]
@PBrockmann that would be a very nice feature, do you have any suggestions for auto-detecting those dates, or testing whether conversion fails? Does `Date.parse` throw an exception in case parsing fails? If so it should be fairly simple to include this capability. If the axis try is datetime, I would imagine speculatively trying to convert the first item and if that succeeds, attempting to convert the entire list.

**Comment by PBrockmann** [comment]
Humm. Finally perhaps it should be left to the user side. This service send me back anyway string I need to convert. Here is another jsfiddle http://jsfiddle.net/PBrockmann/mc73mfne/ with an NCSS request. For sure folks from Unidata will be interested.
What about the 0.7.1 interface ? Really broken ?

**Comment by bryevdv** [comment]
@PBrockmann Yes, unfortunately the JS interface is currently broken. As was mentioned the old interface was really never intended for wide public consumption it was just an engineering tool created to help with the early stages of development. But we do want to have a "real" JS interface, and that is what #1515 is about. This is targeted for 0.8 in mid-Feb, and I hope to begin work on it in earnest next week.

**Comment by PBrockmann** [comment]
Ok I stay tuned and really ready to switch and adopt bokehJS for different scientific projects I am involved in. Very cool.

**Comment by PBrockmann** [comment]
Succeed to update a simple bokehJS with an ajax NCSS request
http://jsfiddle.net/PBrockmann/mc73mfne/
with last 0.8. Great.
About the option x_range and y_range set to
  x_range: [31536000000, 4102444800000],
  y_range: [-2, 3]
it seems that they need to be specified. I would like to let them set automatically.

**Comment by PBrockmann** [comment]
Updated version with 0.12 release
http://jsfiddle.net/PBrockmann/mc73mfne/

**Comment by bryevdv** [comment]
@PBrockmann That's awesome, would you be interested in submitting a PR to add that example? The user's guide section on the JS interface is still new and could use more content.
