### ISSUE TITLE
rect not behaving correctly with zero height

### ISSUE THREAD

**Issue by gbakalian** [bokeh/bokeh#6583]
Python 2.7.12
Bokeh 0.12.6

```
from bokeh.plotting import figure, show, output_file, 
output_file('test.html')

a = figure(plot_width=400, plot_height=400)
a.rect(range(4),[0.0, -5.0, -4.0, 5.0],
        [0.5]*4,[0.0, 10.0, 8.0, 10.0])
show(a)
```

I would expect this piece of code to plot 3 rectangles which y coordinates would be [0,-10], [0,-8],[0,+10]. 
At the place I am getting 3 rectangles with the following y coordinates : [-10,-20],[-8,-16],[0,-10]

n.b.

it works perfectly fine if I remove the coordinate of the empty rectangle at the beginning ...

```
a = figure(plot_width=400, plot_height=400)
a.rect(range(3),[-5.0, -4.0, 5.0],
        [0.5]*3,[10.0, 8.0, 10.0])
show(a)

```

**Comment by bryevdv** [comment]
The problem actually seems to be the zero-height rect, not the negative y values:

* The plot is also wrong with a zero height rect and all positive hieghts

* the following code with no zero height but with negative height rects does work:
    ```
    from bokeh.plotting import figure, show, output_file
    output_file('test.html')

    a = figure(plot_width=400, plot_height=400)
    a.rect(x=range(3),y=[-5.0, -4.0, 5.0],
        width=[0.5]*3,height=[10.0, 8.0, 10.0])
    show(a)
    ```

<img width="409" alt="screen shot 2017-07-04 at 07 23 26" src="https://user-images.githubusercontent.com/1078448/27829941-b5704e5e-6089-11e7-9dd4-85a7691299a8.png">

As an immediate workaround, I'd suggest either filtering zero-height rects completely or setting their height to be non-zero but making them invisible with an `alpha=0` etc

**Comment by bryevdv** [comment]
@clairetang6 The problem is in `_map_dist_corner_for_data_side_length` It checks the first values of `vpt0` and `vpt1` to pick one list to be `vptcorner`, but when height is 0, it picks the wrong one, which flips the plot drawing. 

The following diff fixes the code above, but then then "Rect RectView hit-testing _hit_point should work when axis is log" test fails. Any ideas?
```
diff --git a/bokehjs/src/coffee/models/glyphs/rect.coffee b/bokehjs/src/coffee/models/glyphs/rect.coffee
index bea1f3cfc..310ae48b3 100644
--- a/bokehjs/src/coffee/models/glyphs/rect.coffee
+++ b/bokehjs/src/coffee/models/glyphs/rect.coffee
@@ -136,11 +136,14 @@ export class RectView extends XYGlyphView
     vpt0 = scale.v_compute(pt0)
     vpt1 = scale.v_compute(pt1)
     sside_length = @sdist(scale, pt0, side_length, 'edge', @model.dilate)
+    vpt_corner = new Float64Array(vpt0.length)
     if dim == 0
-      vpt_corner = if vpt0[0] < vpt1[0] then vpt0 else vpt1
+      for i in [0...vpt0.length]
+        vpt_corner[i] = if vpt0[i] < vpt1[i] then vpt0[i] else vpt1[i]
       return [sside_length, canvas.v_vx_to_sx(vpt_corner)]
     else if dim == 1
-      vpt_corner = if vpt0[0] < vpt1[0] then vpt1 else vpt0
+      for i in [0...vpt0.length]
+        vpt_corner[i] = if vpt0[i] < vpt1[i] then vpt1[i] else vpt0[i]
       return [sside_length, canvas.v_vy_to_sy(vpt_corner)]
```

**Comment by bryevdv** [comment]
Making the check non-strict fixes the problem and also passes tests, but I'm not sure this isn't just a bandaid:

```
diff --git a/bokehjs/src/coffee/models/glyphs/rect.coffee b/bokehjs/src/coffee/models/glyphs/rect.coffee
index bea1f3cfc..d40ca19f9 100644
--- a/bokehjs/src/coffee/models/glyphs/rect.coffee
+++ b/bokehjs/src/coffee/models/glyphs/rect.coffee
@@ -137,10 +137,10 @@ export class RectView extends XYGlyphView
     vpt1 = scale.v_compute(pt1)
     sside_length = @sdist(scale, pt0, side_length, 'edge', @model.dilate)
     if dim == 0
-      vpt_corner = if vpt0[0] < vpt1[0] then vpt0 else vpt1
+      vpt_corner = if vpt0[0] <= vpt1[0] then vpt0 else vpt1
       return [sside_length, canvas.v_vx_to_sx(vpt_corner)]
     else if dim == 1
-      vpt_corner = if vpt0[0] < vpt1[0] then vpt1 else vpt0
+      vpt_corner = if vpt0[0] <= vpt1[0] then vpt1 else vpt0
       return [sside_length, canvas.v_vy_to_sy(vpt_corner)]

   _ddist: (dim, spts, spans) ->
diff --git a/bokehjs/test/models/glyphs/rect.coffee b/bokehjs/test/models/glyphs/rect.coffee
index 774d2fd2f..00c82747e 100644
--- a/bokehjs/test/models/glyphs/rect.coffee
+++ b/bokehjs/test/models/glyphs/rect.coffee
@@ -138,6 +138,20 @@ describe "Rect", ->
       expect(glyph_view.sx0).to.be.deep.equal({'0': 0})
       expect(glyph_view.sy1).to.be.deep.equal({'0': 0})

+    it "`_map_data` should map values for x0 and y1 when a height is 0", ->
+      glyph = new Rect({
+        x: {field: "x"}
+        y: {field: "y"}
+        width: {value: 10}
+        height: {field: "h"}
+      })
+      data = {x: [1], y: [2], h: [10, 0]}
+      glyph_view = create_glyph_view(glyph, data)
+
+      glyph_view.map_data()
+      expect(glyph_view.sx0).to.be.deep.equal({'0': 0})
+      expect(glyph_view.sy1).to.be.deep.equal({'0': 0})
```

**Comment by bryevdv** [comment]
Unfortuantely the new test above in the diff passes whether the test is strict or non-strict, I will admit I don't understand some of these tests in `rect.coffee`

**Comment by clairetang6** [comment]
I think the correct way to the fix the issue with `_map_dist_corner_for_data_side_length` picking the wrong corner is something like what your first diff has, but could be improved slightly.

When I originally wrote this function, I only considered the side_length (either width or height) as being positive. In that case, given one comparison of the points in vpt0 and vpt1, you would know which was larger and which was smaller for the entire array. But, since the side_length can also be 0, then you get the situation where vpt0 and vpt1 are equal for the index where the side_length is 0. Adding the non-strict comparison fixes the issue with normal scales, but then is incorrect for reverse scales (i.e. y_scale = (10, -10)). Finding the pt_corner for each index is correct, but they all are in the same direction except for the ones where side_length was 0. 

So, a better solution would be to loop through the vpts and as soon as one vpt0 and vpt1 are not equal, return the correct corner. 

```coffeescript
  _map_dist_corner_for_data_side_length: (coord, side_length, scale, canvas, dim) ->
    if scale.source_range.synthetic?
      coord = (scale.source_range.synthetic(x) for x in coord)
    pt0 = (Number(coord[i]) - side_length[i]/2 for i in [0...coord.length])
    pt1 = (Number(coord[i]) + side_length[i]/2 for i in [0...coord.length])
    vpt0 = scale.v_compute(pt0)
    vpt1 = scale.v_compute(pt1)
    sside_length = @sdist(scale, pt0, side_length, 'edge', @model.dilate)
    if dim == 0
      for i in [0...vpt0.length]
        if vpt0[i] != vpt1[i]
          vpt_corner = if vpt0[i] < vpt1[i] then vpt0 else vpt1
          break
      return [sside_length, canvas.v_vx_to_sx(vpt_corner)]
    else if dim == 1
      for i in [0...vpt0.length]
        if vpt0[i] != vpt1[i]
          vpt_corner = if vpt0[i] < vpt1[i] then vpt1 else vpt0
          break
      return [sside_length, canvas.v_vy_to_sy(vpt_corner)]
```

This seems to not break the log hit-testing test, but I did confirm that the other solution did break it, and I don't know why. I wrote those tests by calculating with the scales which points in view space were supposed to hit the rectangles given their data, but they aren't the easiest to understand or change. Hovering and rendering tests would probably be better as screenshot tests. 

The last thing about checking `expect(glyph_view.sy1).to.be.deep.equal({'0': 0})`. This was based off of tests in image, where the map_data should set the `sy1` on the glyph_view, but without a scale, it is set to 0 and the test is that it is 0 and not undefined. But those can be changed to include the line `@set_scales(glyph_view)` before the call to `map_data` to have more meaningful numbers than 0, but they aren't great tests since the math with all of the coordinate systems is not easy to follow.

**Comment by bryevdv** [comment]
> but they aren't great tests since the math with all of the coordinate systems is not easy to follow.

Agreed I just had a hard time adding a test in another PR, I'd like to figure out what changes till make better unit testing of views (and especially hist testing etc) possible and doable in a conventional way that can be documented for others.

**Comment by bryevdv** [comment]
@clairetang6 I'm confused, actually. The previous function `vpt_corner` was an array, so `canvas.v_vy_to_sy(vpt_corner)` was also an array. This was presumably a unique value for every every different rect instance, since they all have whatever corners they happen to have. This new function only computes a single scalar `vpt_corner` for every all rects, that does not seem right?  (and if it were, at a minimum `v_vy_to_sy` would need to be `vy_to_sy` since its no longer a vector arg, but changing to that, nothing gets drawn with the example code.)

**Comment by clairetang6** [comment]
@bryevdv, `vpt_corner` in the new function is also an array. It is just set to either the whole array `vpt0` or `vpt1` based on a single comparison. This works because the side_length can't be negative, so a single comparison will tell you which array has the smaller values and which has the larger values. However, I do see now that my solution in the new function doesn't take into account the case where *all* side_lengths are 0. In that case, `vpt_corner` doesn't get set, which might cause problems, so it should probably be set even though it won't matter in rendering because 0 side_length rectangles are not rendered.
