### ISSUE TITLE
Pre-selection on rows in a Bokeh DataTable fails to display such selection

### ISSUE THREAD

**Issue by thornhale** [bokeh/bokeh#6616]
This is a follow-up on the conversation on the Bokeh mailing list here:

https://groups.google.com/a/continuum.io/forum/#!msg/bokeh/QsmXU9sZstU/vTL2zfJ9BQAJ

The issue has also been covered here:

https://stackoverflow.com/questions/44960975/how-do-i-pre-select-rows-in-a-bokeh-widget-datatable#comment76926949_44960975

Description of issue:

After setting up a ColumnDataSource and attaching the ColumnDataSource to a DataTable, it is not possible to modify what is selected via the following methods:

1.) Modifying the source.selected property from the Python side:

source.selected['1d']['indices'] = [1,2]

2.) Modifying the source.selected property from a JSCustom side:

button.callback = CustomJS(args=dict(source1=source1, source2=source2), code="""
        **source2['selected']['1d'].indices =[1,2,3]**
        var inds_in_source2 = source2['selected']['1d'].indices;

        var d = source2['data'];
        var inds = []

        if (inds_in_source2.length == 0) { return; }

        for (i = 0; i < inds_in_source2.length; i++) {
            ind2 = inds_in_source2[i]
            inds.push(d['index'][ind2])
        }

        source1['selected']['1d'].indices = inds
        source1.trigger('change');
    """)

[test_highlight_from_python.zip](https://github.com/bokeh/bokeh/files/1149965/test_highlight_from_python.zip)

The issue can both be reproduced from a Jupyter Notebook and from the test files attached to this issue.

Pre-liminary analysis of the cause by Bryan Van de ven from [this thread](https://groups.google.com/a/continuum.io/d/msg/bokeh/QsmXU9sZstU/vTL2zfJ9BQAJ):

Further info, the reason permuted_indices is [-1, -1, -1] is because "selected_indices" right above is [7, 8, 9] (not [1,2,3]) I expect this is some unforeseen interaction specific to filtered data sources. Definitely make the issue and I will add this information and ping Claire on it 

I have tried to get this to work in both Bokeh 12.4, and 12.5. The issue occurs in both versions. For version 12.6, Bryan modified the call-back like so:

    button.callback = CustomJS(args=dict(source1=source1, source2=source2), code="""
        source2.selected['1d'].indices = [1,2,3];
        var inds_in_source2 = source2.selected['1d'].indices;

        var d = source2['data'];
        var inds = []

        if (inds_in_source2.length == 0) { return; }

        for (i = 0; i < inds_in_source2.length; i++) {
            ind2 = inds_in_source2[i]
            inds.push(d['index'][ind2])
        }
        source1.selected['1d'].indices = inds
        source1.change.emit()

        source2.properties.selected.change.emit();
        console.log(source2)
    """)

**Comment by bryevdv** [comment]
ping @clairetang6 

it seems that even though the `CustomJS` does this:

    source2.selected['1d'].indices = [1,2,3];

The data table sees the indices of the values in the *full* table, which is `[7, 8, 9]`, then this line:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/widgets/tables/data_table.coffee#L115

ends up returning `[-1, -1, -1]` as a result, for the `permuted_indices` (resulting in no selection). 

What I'm not clear on (I have not had a chance too look) is where the conversion from `[1,2,3]` to `[7, 8, 9]` happens? Because both the` CustomJS` and the data table code both reference the same `source2.selected['1d'].indices`. So I'm guess the CDS itself fixes up selection indices in the presence of a filter? I think that's probably what would be needed for glyphs. So my first inclination is that we will have to handle this situation in `DataTable` specifically (i.e. check for the presence of a filter, to get from "global" CDS indices down to "local" table row indices)

**Comment by clairetang6** [comment]
There definitely is something funny going on. I haven't figured it out yet, but if you cut out everything that has to do with source1 in the callback (code below), then the pre-selected [1, 2, 3] shows up in the DataTable correctly. 

```
button.callback = CustomJS(args=dict(source1=source1, source2=source2), code="""
    source2.selected['1d'].indices = [1,2,3];
    source2.properties.selected.change.emit();
    console.log(source2)
""") 
```
But if you put back in only the one line of `source1.change.emit()` , then the plot circles get selected with [1, 2, 3] too.

```
button.callback = CustomJS(args=dict(source1=source1, source2=source2), code="""
    source2.selected['1d'].indices = [1,2,3];
    source2.properties.selected.change.emit();
    source1.change.emit()
    console.log(source2)
""") 
```

So it seems like the selected properties are being shared between source1 and source2 for some reason. In the original callback code, the [1, 2, 3] is mapped correctly by the CustomJS to the full data set indices to be set on source1. The setting of [7, 8, 9] on source1 seems to be changing the selected on source2 as well, but I'm not sure why yet.

**Comment by clairetang6** [comment]
To answer the original question in the mailing list though @thornhale, without the issue being caused by having two data sources, I think you are just missing `source1.properties.selected.change.emit();`. The signal that causes the re-render of the DataTable is a change in the selected property of a data source. For that to automatically happen, you need to change the selected property all at once with something like: 
```
        var selected_to_set = {}
        selected_to_set['0d'] = {'glyph': null, 'get_view': function () {return null;}, 'indices': []}
        selected_to_set['1d'] = {'indices': [1, 2, 3]}
        selected_to_set['2d'] = {'indices': {}} 
        source1.selected = selected_to_set
```
which is extremely not user-friendly and something that could be improved. But the following should work:
```
    source1.selected['1d'].indices = [1,2,3];
    source1.properties.selected.change.emit();
```

**Comment by mattpap** [comment]
> which is extremely not user-friendly and something that could be improved.

There are helpers for that in `core/hittest`.

**Comment by bryevdv** [comment]
FWIW I tried adding `properties.selected.change.emit()` and it did not seem work (because of the mangled indices) so I think there might be more plumbing updates needed

**Comment by clairetang6** [comment]
@bryevdv, to be clear. It works for me with the following code:
```
from bokeh.plotting import figure, output_file, show
from bokeh.models import CustomJS
from bokeh.models.sources import ColumnDataSource
from bokeh.layouts import column
from bokeh.models.widgets import DataTable, TableColumn, Button

output_file("subset_example.html")

data = dict(
        index = list(range(10)),
        x = list(range(10)),
        y = list(range(10)),
        z = ['some other data'] * 10
    )

source1 = ColumnDataSource(data)

columns = [
        TableColumn(field="y", title="Y"),
        TableColumn(field="z", title="Text"),
    ]
data_table = DataTable(source=source1, columns=columns, width=400, height=280)

button = Button(label="Select")
button.callback = CustomJS(args=dict(source1=source1), code="""
        source1.selected['1d'].indices = [1,2,3];
        source1.properties.selected.change.emit();
    """)
show(column(data_table, button))
```
The issue seems to be caused when there are multiple sources being updated, but I haven't fully figured it out yet.

**Comment by bryevdv** [comment]
@clairetang6 Yes sorry, I should have been specific, I tried `properties.selected.change.emit() ` in the presence of a second filtered data source

**Comment by thornhale** [comment]
Thank you all for looking into this. II also tried to confirm and test out suggestions by Claire.

It seems there are 2 issues then. 

On my end, I did not use the line Claire was recommending to use (since I did not see this in the official documentation, I can add that note if that's ok).

It also appears that this was a recent addition in Bokeh 12.6: I tried the modifications to the script in both 12.5 and 12.6. The datatable only highlighted rows the correct rows in the DataTable in 12.6. 

In 12.5, I got the following error on the FF web console:

TypeError: source2.properties.selected.change is undefined

I also tried in the CustomJS just this for 12.5:

source1.selected.change.emit();

In either case, with 12.5, no rows got highlighted. So at the least it looks like I will have to migrate my application to bokeh 12.6. 

(I hope this doesn't break any of the more normal things I am using bokeh for (since you mentioned in the 12.6 release docs that some interfaces were changed in preparation for version 1.0)).

**Comment by clairetang6** [comment]
Digging in a bit, the issue of the wrong indices being shown in the presence of a second data source doesn't seem to have any to do with the new filterable CDS/CDSView. Instead, it seems that data sources share a selected object on initialization. 

Here is an example script that shows the issue on 0.12.6. 
```
from bokeh.plotting import figure, output_file, show
from bokeh.models import CustomJS
from bokeh.models.sources import ColumnDataSource
from bokeh.layouts import row, column
from bokeh.models.widgets import DataTable, TableColumn, Button

source1 = ColumnDataSource(dict(x=[1,2,3,4,5], y=[1,2,3,4,5]))
source2 = ColumnDataSource(dict(x=[10,21,33,2,4], y=[5,3,2,1,6]))

fig1 = figure(plot_width=300, plot_height=300, tools=['box_select','reset'])
fig1.circle(x='x', y='y', size=10, source=source1)

fig2 = figure(plot_width=300, plot_height=300, tools=['box_select','reset'])
fig2.circle(x="x", y="y", size=10, source=source2)

button = Button(label="Select")
button.callback = CustomJS(args=dict(source1=source1, source2=source2), code="""
        source2['selected']['1d'].indices =[1, 2, 3]

        console.log(source1['selected']['1d'].indices)
        console.log(source2['selected']['1d'].indices)

        console.log(source1['selected'] === source2['selected'])

        source1.trigger('change');
        source2.trigger('change');
    """)
show(row(fig1, fig2, button))
```
If the button is clicked before any selections are made using the box select tool, then both of the sources have their selected indices changed with the first line in the CustomJS. 

<img width="864" alt="screen shot 2017-07-18 at 10 21 45 pm" src="https://user-images.githubusercontent.com/4241244/28351890-b955e158-6c07-11e7-8458-7bbd9531c0e5.png">

However, if you then make a selection using the box select tool on either graph, `console.log(source1['selected'] === source2['selected'])` prints false and clicking the button only affects the second plot.

**Comment by clairetang6** [comment]
This issue and comment thread has gotten a bit confusing because the original issue uncovered other issues. 

The original issue was that it did not seem possible to “pre-select” the rows of a DataTable, i.e. to programmatically specify rows of the data source’s selected property and have them render highlighted on the DataTable. @thornhale tried two ways of doing this and both did not seem to work. One was on the Python-side, to change the `selected` property of the data source and the other was to use CustomJS to update `selected` within a CustomJS callback of a button. 

The issue on the Python side is first and foremost that the DataTable does not render its selection on initialization. Its `updateSelection` method is only called as a slot to `source.properties.selected.change`. But after fixing this to call `updateSelection` on first render, there is another issue as well. Setting the selection Python-side doesn’t work with the lines:

```
source = ColumnDataSource(data)
source.selected[‘1d’][‘indices’] = [1, 2]
```

Instead you need to have either:
```
selected = { '0d': {'glyph': None, 'indices': []},
             '1d': {'indices': [1, 2]},
             '2d': {'indices': {}}}
source = ColumnDataSource(data=data, selected=selected)
```
or 
```
source = ColumnDataSource(data)
selected = { '0d': {'glyph': None, 'indices': []},
             '1d': {'indices': [1, 2]},
             '2d': {'indices': {}}}
source.selected = selected
```

The issue on the CustomJS side was that the wrong signal was being emitted. While `source.change.emit()` doesn’t work, `source.properties.selected.change.emit()` does. This is confusing because `source.change.emit()` *does* update the rendering of the selected rows in glyph renderers. 

And finally, in some of the example code, there were multiple plots, sometimes with different sources, which have the additional unsolved issue of the selected properties on these different sources being shared, which lead to strange behavior. 

To fix the original issue, I’m going to have a PR that has the DataTable render its selection on initialization and change the signal, slot connection for `updateSelection` to be `source.change` instead of `source.properties.selected.change`.

**Comment by bryevdv** [comment]
>  and change the signal, slot connection for updateSelection to be source.change instead of source.properties.selected.change.

Does the former imply the latter? i.e. will executing `source.properties.selected.change.emit()` trigger callbacks on `source.change`? I think that is the case, but if not, I think we need both handlers set up? Asking, since I am not 100% sure offhand.

**Comment by clairetang6** [comment]
@bryevdv, `source.properties.selected.change.emit()` in a CustomJS code snippet does not trigger the callback. This means that the following doesn't work:

```python
button = Button(label="Select")
button.callback = CustomJS(args=dict(source=source), code="""
        source['selected']['1d'].indices = [1, 2]
        source.properties.selected.change.emit(); //doesn't work. 
        //source.change.emit(); // does work
    """)
``` 

However, this does work: 
```python
button = Button(label="Select")
button.callback = CustomJS(args=dict(source=source), code="""
    selected = {};
    selected['0d'] = {'glyph': null, 'indices': []};
    selected['1d'] = {'indices': [1, 2]};
    selected['2d'] = {'indices': {}};
    source.selected = selected;
```
where the `selected` property changes and BokehJS emits both source.properties.selected.change and source.change. 

I think re-adding the `source.properties.selected.change` handler would only catch the case of that signal being emitted by a user, like in the first example where you need to emit a signal because only a piece of the `selected` is being modified so it doesn't get caught by the change machinery. 

Re-adding the `source.properties.selected.change` handler also makes it so that in the second example and all other cases when the selected property is changed (points are box-selected from a separate figure with a shared CDS), the `updateSelection` is called twice, once for the `source.change` and once for the `source.properties.selected.change`. I don't think it should go back and examples that have shown the use of `source.properties.selected.change.emit()` should be changed to `source.change.emit()`.

**Comment by bryevdv** [comment]
> I don't think it should go back and examples that have shown the use of source.properties.selected.change.emit() should be changed to source.change.emit().

That might OK but then the PR needs a migration note. @mattpap @canavandl do you have any thoughts about this?

**Comment by SamDM** [comment]
Hi, has any progress been made on the other issue about the linked selection of data sources (mentioned by ' clairetang6' on Jul 19 above)? I am also facing an issue with this where programmatically selecting rows in a dataframe also updates selections in unrelated plots having different sources.
