### ISSUE TITLE
tap tool on bokeh server does not select data points with a custom callback

### ISSUE THREAD

**Issue by EmperorDali** [bokeh/bokeh#6707]
**Versions**: Firefox 54.0.1 (64-bit) on macOS Sierra, 0.12.6

**Expected behavior**: With the tap tool, the user can select a data point and the specified callback will fire

**Observed behavior**: Callback fires intermittently with incorrect parameters, or does not fire at all

`mwe.py`:

```python
from bokeh import plotting as bplt
from bokeh import layouts as blayouts
from bokeh import models as bmodels
from bokeh import io as bio

fig = bplt.figure(tools="tap")

source = bmodels.ColumnDataSource(dict(x=[0,1], y=[0,1]))

r = fig.circle('x', 'y', source=source, size=4)

def handler(attr, old, new):
    print('attr: {} old: {} new: {}'.format(attr, old, new))

r.data_source.on_change('selected', handler)

bio.curdoc().add_root(blayouts.layout([[fig]]))
```

`bokeh serve --show mwe.py`

**Steps to reproduce**

1. Run `bokeh serve --show mwe.py` as above
2. Click one of the circles
3. Observe that either i) no output is printed, or ii) the following is printed, indicating the callback fired with incorrect empty arguments: 

`attr: selected old: {'0d': {'glyph': None, 'indices': []}, '1d': {'indices': []}, '2d': {'indices': {}}} new: {'0d': {'glyph': None, 'get_view': {}, 'indices': []}, '1d': {'indices': []}, '2d': {'indices': {}}}`

**Comment by bryevdv** [comment]
I can reproduce this on firefox, but not on safari.

**Comment by bryevdv** [comment]
FYI the callback being fired with empty args is equivalent to "unselection". The callbacks fires based on the value of the selection, not based on clicking or even hit-testing positive. If something is already selected, there will be no change, and no callback. Or if you click in outside any glyph or hit esc to unselect, that changes to an empty selection, so there will be a callback with empty data.

**Comment by EmperorDali** [comment]
I'm also encountering the bug in Safari: did you try clicking more than once? Sometimes intermittently one of the circles will select if you're clicking a lot. This happened to me once with Safari, but then I deselected and the other circle wouldn't select.

**Comment by p-himik** [comment]
I can reproduce on Google Chrome.
A couple of things that I notice:

1. You should increase `size` - otherwise, it's way too easy to miss a point
2. The very first tap on an empty space (so, nothing was and nothing is selected) generates the output in the description - the difference is in `get_view`. Probably it's a function that gets added to the selection result dynamically, resulting in this diff
3. If the very first tap is on a dot, the diff includes both `get_view` and the correct dot index
4. In either case, subsequent taps don't cause the callback to be called if the selection doesn't change

**Comment by EmperorDali** [comment]
Update:

With `size = 20` the bug seems to NOT occur. I can reliably select either circle, back and forth.

Something with hit detection?

**Comment by bryevdv** [comment]
> I'm also encountering the bug in Safari: did you try clicking more than once? 

Yes I clicked each circle several dozen times in various orders and it always triggered appropriately

**Comment by bryevdv** [comment]
I updated the code to the current standard usage:
```
r.data_source.selected.on_change('indices', handler)
```
and tested on Chrome, FF, and Safari. The circles were a bit hard to hit (because they are tiny) but in every case the callback printed exactly what is expected. There were lots of issues previously with both the "dict" for selections, and also with Bokeh itself replacing whole `Selection` objects. My guess is this issue was related to those things as well (neither of them exists anymore)
