### ISSUE TITLE
Slider custom CSS template, cannot override bk-noUi-connect

### ISSUE THREAD

**Issue by covelloz** [bokeh/bokeh#6761]
When using custom css style sheet with bokeh serve, trying to override inline style of *bk-noUi-connect* does not work (even with !important)

Version

    $ python -c "import bokeh; print(bokeh.__version__)"
    0.12.7dev16

App Directory

    myapp
       |
       +---main.py
       +---static
       +---templates
            +---index.html
            +---styles.css

styles.css

    .bk-root .bk-bs-btn-default {//works
        color: #000000;
        background-color: #FFFFFF;
        border-color: #DCDCDC;
        margin-top: 5px;
    }
    .bk-root .bk-widget-form-input {//works
        width: 270px;
    }
    .bk-markup {//works
        font-family: "Verdana";
        font-size: 200%;
    }
    .bk-noUi-connect {//fails
        background-color: #6495ED !important;
    }

**Comment by mattpap** [comment]
Inline styles have precedence above all else, so you will have to use javascript to change background color. However, `bk-noUi-connect`'s background color is controlled by `Slider.bar_color` attribute, so you should use that. I presume you want to keep everything in a single style sheet for simplicity, but that's not a reliable approach, because you are touching here on private implementation details of bokehjs, and it's very likely that this will fail in future versions of bokeh. Unfortunately, we are yet to figure out how to reliably allow what you are trying to achieve here.

**Comment by covelloz** [comment]
Beautiful! That did the trick. Thanks @mattpap. I actually figured out what was wrong and it was a dumb error on my end; if you use the !important tag you *can* use custom css template to override the inline style. However, fefinitely want to use bar_color attribute. I should have dove into the abstract slider class first before posting. My bad. Keep up the good work. These sliders look awesome!

**Comment by bryevdv** [comment]
closing inactive discussion
