### ISSUE TITLE
Remove old docs and examples around, please...

### ISSUE THREAD

**Issue by Nemecsek** [bokeh/bokeh#6763]
Hi. 
Searching for info about Bokeh I find a lot of OLD docs and examples around. 
That's utterly confusing: Bokeh syntax changes so much that very often a new revision is not fully compatible with the next one. Examples simply don't work or there are better ways to write new code.

Why keep all doc versions online? I would remove them completely (Google links to them very often) and push people to move to the last version. 

Most programmers don't even write Bokeh version when posting on Stackoverflow. You can have a feeling of it by reading publishing date only. Kind of confusing.

I believe it is clean up time!

**Comment by bryevdv** [comment]
> Why keep all doc versions online? 

We don't keep all the doc versions online, we keep maybe a recent four or five (out of ~40 releases)

And the reason for that is: because there are users that rely on them. Not everyone has the option of upgrading immediately to the latest version. Just because you don't need them does not mean that no-one needs them.

> Most programmers don't even write Bokeh version when posting on Stackoverflow. You can have a feeling of it by reading publishing date only. Kind of confusing.

We have no direct control over what is on StackOverflow. To be perfectly honest, I am not very fond of StackOverflow as  from my perspective it manufactures busy-work for me.

**Comment by Nemecsek** [comment]
Yep, i understand your point of view.
I just see the difficulty, as a newbie, to find out something when all is mixed together... Google search doesn't help.

Thank you for the time you found to answer.

**Comment by bryevdv** [comment]
FYI the docs site itself has a local search bar at the top. That should always search the most recent release of the docs. Hopefully that helps. Again, regarding Stack Overflow and other external sites, we have no control
