### ISSUE TITLE
See status of currenct websocket connection in console / javascript

### ISSUE THREAD

**Issue by sigurdurb** [bokeh/bokeh#6779]
Hi, 

I have a site running Bokeh server and sometimes (little to frequently) it fails to connect to websocket
With an error: "Failed to connect to Bokeh server." and then something like "invalid status line" or "Error: Could not open websocket"
I found one of the catch block that prints out the error:
https://github.com/bokeh/bokeh/blob/b840f95acd932d5cc037bdde5435d633f1d0d5a8/bokehjs/src/coffee/client.coffee#L422

This code does not do anything about trying to reconnect it seems.

I know I can call location.reload and that reloads the site from cache(not a full reload) and that is enough to re-establish the websocket connection. But the issue is time, I need to know straight away if the connection has failed. But how would I do that? How can I get the state of the websocket connection in javascript ?

**Comment by bryevdv** [comment]
There's probably not any good way to currently do that. The most reasonable way forward is probably to expand on the notions in https://github.com/bokeh/bokeh/issues/4272 i.e. instead of just a single callback hook for successful document init, there could be additional "document-level" event hooks for situations like if the web socket fails. That would allow you to configure `CustomJS` callbacks to do whatever you like if a websocket connection fails.

**Comment by bryevdv** [comment]
i'm going to go ahead and close this issue since it is now linked to the other one. If you have additional comments or requirements suggestions, the other issue is the place to put them.
