### ISSUE TITLE
Plot should indicate that it works in LOD mode

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#6785]
In case of plots like color_scatter it's pretty obvious to see LOD in action. However, I have an example where I can only see some flickering on screen, that I initially attributed to a bug. It's only when I realized that I'm plotting a lot more points that initially expected, when attributed this flickering to LOD.  I would expect some sort of icon appear on e.g. toolbar indicating what's happening internally in bokehjs.

**Comment by bryevdv** [comment]
I'm -1 on this. There's not always a toolbar, so that's not a good place to put anything. LOD is usually fine as-is but in cases where its not it can be disabled or its parameters changed. I have not perceived any and large general issue with it as it is and I don't think increased complexity and API surface is merited.

**Comment by bryevdv** [comment]
I'm going to go ahead and close this one.
