### ISSUE TITLE
SaveTool custom filename or use plot title

### ISSUE THREAD

**Issue by portermahoney** [bokeh/bokeh#6798]
https://github.com/bokeh/bokeh/blob/cd5b337fbfffff16dd619e2734e2910fb33c12ec/bokehjs/src/coffee/models/tools/actions/save_tool.coffee#L5

Is there a way to customize the filename for the SaveTool or default it to the plot title?  Having them all named "bokeh_plot" is not ideal when you have multiple plots in a gridplot.  

The export functions give this option.  Should I consider using those with a custom widget download button?

Thanks!

**Comment by bryevdv** [comment]
Unfortunately different browser platforms behave very differently. Some will prompt to save an actual file. Others will only open the new image in a new tab (which can then be saved). The filename is basically irrelevant, or at least, there would be little value in making it configurable with the current save implementation, since how the name gets used or not used on different browsers is outside our control. If you have more experience or know something we have missed, a PR to improve this functionality would certainly be appreciated. 

Otherwise, if you are using a Bokeh server app then a save button or widget that triggers the export functions would work fine, however that would only work in a Bokeh server application (since the export functions are real python code). 

Also, as a gentle reminder, please use the mailing list for general support questions such as this:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
