### ISSUE TITLE
Apps URL's are not directing to correct location

### ISSUE THREAD

**Issue by samroon2** [bokeh/bokeh#6816]
Href's  from website: https://demo.bokehplots.com/apps/ are redirecting to incorrect locations. 

Also a mixed content warning on this page.

```
<a href="/gapminder">gapminder</a>

Needs to be (for all not just this eg.):

<a href="/apps/gapminder">gapminder</a>

```

![image](https://user-images.githubusercontent.com/23491699/29724095-0b363efa-897c-11e7-97ef-693877e34b63.png)

**Comment by bryevdv** [comment]
While I agree that the links are broken, that page is not intended to be used by the anyone. I'm going to be realistic and acknowledge that there is virtually no chance anyone will have to opportunity to do anything about it, and since its not the proper URL for users to use, also no worth fixing in any case. 

The proper URL you should be using is this one:

https://demo.bokehplots.com/

**Comment by samroon2** [comment]
No problem, I know it's a minor thing, just thought I'd bring it to your attention. Love the work you guys do, Bokeh is awesome!

**Comment by bryevdv** [comment]
Thanks for the kind words!
