### ISSUE TITLE
Trouble with encoding on Windows

### ISSUE THREAD

**Issue by damianavila** [bokeh/bokeh#682]
From SO: http://stackoverflow.com/questions/24075840/python-trouble-with-encoding-on-windows-bokeh-plotting-library

Proposed solution, add "encoding" parameter defaulting to UTF-8.

**Comment by gepcel** [comment]
From SO: https://stackoverflow.com/questions/46187520/python-trouble-with-encoding-on-windows-when-run-bokeh-serve-bokeh-plotting-li

I think there is another missing of using 'utf-8' [here](https://github.com/bokeh/bokeh/blob/f3d13963a36130ec126f0a1e87d3abcf8e5870f7/bokeh/application/handlers/script.py#L53). If everyone feels ok, I can pull a request. The current status is if you are under a Windows system, your script file contains some special charactor, `bokeh serve` won't work no matter your script file is saved in utf-8 format or some codec like 'gbk'.

**Comment by guenteru** [comment]
I have to chime in on this because I encountered the same bug as pointed out previously by @gepcel 
Extending that particular [line](https://github.com/bokeh/bokeh/blob/c8982366e3676757c749c2c2b66ea46a737ba7e9/bokeh/application/handlers/script.py#L84) with ```encoding='utf8'``` helps to make my app run. Without that, python switches to cp1252 which leads to a crash.

Tested on Windows 7, German locale, Python 3.6.5 & bokeh 0.13.0

**Comment by bryevdv** [comment]
Happy to consider a PR if someone wants to submit one. I don't really have the means to test that this works in the situations people are reporting, only to test that it does not break in current situations.

**Comment by gepcel** [comment]
Looks like the solution suggested will fix the issue with python3, but break things with python2. There was an unsuccessful trying, see discussion #7305.

As for now, my solution for myself is manually changing this line of code everytime I installed or updated bokeh.

**Comment by lgasnier** [comment]
I made some tests with this script:
```python
# -*- coding: utf-8 -*-
from bokeh.plotting import figure
from bokeh.io import curdoc
fig = figure(title="Entête", plot_width=400, plot_height=200)
curdoc().add_root(fig)
```
on 4 platforms:

- Windows 7 / python 2.7 / bokeh 0.13
  No issue (accented text properly rendered). Just this warning:
  ```
  M:\Anaconda3\envs\py27\lib\site-packages\bokeh\core\property\bases.py:197: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return new == old
  ```

- Linux / python 2.7 / bokeh 0.13
  No issue (accented text properly rendered). Same warning.

- Windows 7 / python 3.6 / bokeh 0.13
  Accented characters are not properly rendered. First line `# -*- coding: utf-8 -*-`
  is not taken into account unlike python 2.7. With python 3.6 the script file is
  read according to `sys.getdefaultencoding()` (= cp1252 on my laptop configuration)

- Linux / python 3.6 / bokeh 0.13
  No issue (accented text properly rendered)

Instead of using `io.open` that breaks things python 2 version - cf. [#7305](https://github.com/bokeh/bokeh/pull/7305) -, maybe we could fix this issue by testing python version in script.py like this:

```python
if sys.version_info[0] > 2:
    with open(filename, 'r', encoding='utf-8') as f:
        kwargs['source'] = f.read()
else:
    with open(filename, 'r') as f:
        kwargs['source'] = f.read()
```

What's your opinion?

**Comment by bryevdv** [comment]
@lgasnier that might be reasonable. Can you push a PR so we can first see that all existing tests pass and also experiment with the change easily?

**Comment by bryevdv** [comment]
Tho, please use `if six.PY2` etc
