### ISSUE TITLE
There should be a way to control order that renderers are drawn.

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#696]
I want to control the order in which renderers are drawn.  I'm building a plot with bar plots and line plots, I want the bars on the bottom and lines drawn over them.

Something similar to z-index in css would do the trick.  I think that would work better than an absolute ordering (which if specified would likely be wrong).  
https://developer.mozilla.org/en-US/docs/Web/CSS/z-index

**Comment by dg-pb** [comment]
Any chance someone could provide a working example, how I can change the order of glyphs interactively? Or `stream` new glyph to be added to the background?

Couldn't figure it out from
https://github.com/bokeh/bokeh/pull/1484

and can't find anything anywhere else.

I have many glyphs and I want to re-arange them interactively on js side, performance is fairly critical.

Appreciate any help.

**Comment by bryevdv** [comment]
@dgrigonis This issue and PR are nearly a decade old. BokehJS has since been re-written from the ground up in an entirely different language and there have been three major releases in that time. There is nothing here relevant to current Bokeh. Since then we have also created a community discourse that is the appropriate place to go to seek help with usage questions:

https://discourse.bokeh.org/

Please ask your question there instead, and provide substantially more detail about what you are trying to achieve.
