### ISSUE TITLE
Slow figure generation if multiple lines and multiple markers

### ISSUE THREAD

**Issue by jxrossel** [bokeh/bokeh#7066]
When a figure contains many lines and markers, the figure generation becomes notably slow (7.5x slower than Matplotlib in the example below). Plotting the same data with a single line and a single marker is extremely fast (32x faster!), so the issue is not due to the amount of data. 

`multi_line`  solves the issue, but only partially:
* there is no equivalent for markers (e.g. a `multi_marker` method is not implemented)
* the legends are only internal (external legends require the use of `Legend`, which requires a list of renderers but `multi_line()` returns a single object)
* only a single type of line dash is allowed for all the lines

In my real-life situation, I need several lines per plots, with different markers and dashes, and an external legend. Altogether, it takes 3 to 5 seconds to generate the figures, which is not a show stopper but still annoying for a live website.

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh: 0.12.9
python: 3.6
OS: Windows 7
browser: irrelevant

#### Complete, minimal, self-contained example code that reproduces the issue

The code below generates figures containing multiple straight lines with various slopes for different implementations with Bokeh and a matplotlib equivalent.

```
import numpy as np
import itertools
from bokeh.palettes import plasma
from bokeh.plotting import figure, show, ColumnDataSource
from bokeh.models import Legend
import time
from matplotlib.figure import Figure as mplFigure
from matplotlib.backends.backend_agg import FigureCanvasAgg as mplFigureCanvas


###############################################################################
# Inits

x = np.linspace( 0, 10, 50 )
a = list( range( 20 ) )

markers = itertools.cycle( 'asterisk circle diamond cross square triangle inverted_triangle'.split() )
markers = [ next( markers ) for ii in range( len( a ) ) ]

line_dashes = itertools.cycle( 'solid dotted'.split() )
line_dashes = [ next( line_dashes ) for ii in range( len( a ) ) ]

colors = plasma( len( a ) )


###############################################################################
# Bokeh: full case
# loop over lines, line dashes and markers with external legend

start_time = time.time()

legs = []
p = figure(tools='')
for this_a,color,marker,line_dash in zip( a, colors, markers, line_dashes ):
    l = p.line( x, this_a*x, color=color, line_dash=line_dash )                    
    m = getattr( p, marker )( x, this_a*x, color=color, line_dash=line_dash )
    legs.append( ( str( this_a ), [l,m] ) )

legend = Legend( items=legs, location=(10, 0) )
p.add_layout( legend, 'right' ) 

print( '\nTime to generate figure (bokeh - full case): ', time.time() - start_time, '\n' )
# -> 0.51 s
    
show(p)        

###############################################################################
# Bokeh: multi_line, but 
#   * no markers, because multi_marker doesn't exist
#   * no external legend because multi_line only allow an internal one
#     (one must have a list of renderers to feed Legend() and .multi_line() returns
#     a single object)
#   * unique type of line dash for all the lines

start_time = time.time()

x_list, y_list, legs = [], [], []
p = figure(tools='')
for this_a in a:
    x_list.append( x )
    y_list.append( this_a*x )
    legs.append( str( this_a ) )

source = ColumnDataSource( dict(x=x_list,y=y_list,legs=legs,colors=colors) )    
l = p.multi_line( xs='x', ys='y', legend='legs', color='colors', source=source )                    
        
print( '\nTime to generate figure (bokeh - multiline): ', time.time() - start_time, '\n' )
# -> 0.011 s, extremely fast but incomplete

show(p)    

###############################################################################
# Bokeh: single line and marker but with all the data

start_time = time.time()

x_list, y_list = [], []
p = figure(tools='')
for this_a in a:
    x_list.append( x )
    y_list.append( this_a*x )
    
x_cat = np.hstack( x_list )
y_cat = np.hstack( y_list )
    
l = p.line( x_cat, y_cat )                    
m = p.circle( x_cat, y_cat )
            
print( '\nTime to generate figure (bokeh - single line/marker): ', time.time() - start_time, '\n' )
# -> 0.016 s, extremely fast so it's not a matter of quantity of data, but
# an issue with the number of lines / markers

show(p)    

###############################################################################
# Equivalent to Bokeh with Matplotlib, using a loop on lines and markers

markers = itertools.cycle( '* o d x s ^ v'.split() )
markers = [ next( markers ) for ii in range( len( a ) ) ]

start_time = time.time()

f = mplFigure()
mplFigureCanvas(f)
ax = f.subplots()

for this_a,color,marker,line_dash in zip( a, colors, markers, line_dashes ):
    l = ax.plot( x, this_a*x )[0]
    l.set_linestyle( line_dash )
    l.set_marker( marker )
    l.set_color( color )
    l.set_label( str( this_a ) )

leg = ax.legend( bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0. )

print( '\nTime to generate figure (mpl): ', time.time() - start_time, '\n' )
# -> 0.068 s, ~7.5x faster than bokeh full case, but slower than what bokeh
# could achieve (see results for simplified cases)

f.savefig( 'test_mpl.png', format='png', bbox_extra_artists=(leg,), bbox_inches='tight' )
```

**Comment by bryevdv** [comment]
Hi @jxrossel thanks for the detailed issue. Bokeh definitely makes specific tradeoffs that tilt towards certain use cases. Finding ways to utilize "vectorized" approaches is almost always going to be preferable and more performant. So rather thatn trying to find way to speed up the much slower case, I think it would be much more profitable to work on extending capability to the fast cases where it is currently lacking. 

In order to keep the tracker manageable, I'd like to propose deciding on a  set of smaller, more focused individual issues to make, then closing this one (after making the other issues and linking back). As an initial stab I'd propose:

* Make a `Scatter` glyph that can vectorize over marker type. There was an old issue for this, if it is currently closed, lets make a new one.

* Make `line_dash` on `MulitLine` a "spec" (i.e. vectorizable)  There was an old issue for this, if it is currently closed, let's make a new one

* Make legends work well with `MultiLine` and `Scatter` (including outside the plot area) Not sure if there is an issue for this already. 

Does that cover all the bases? If so, can you search for/make new issues to link to this one?

Finally, I am going to start inquiring of all feature requests: do you have any capability to assist with the implementation? We are approaching an ebb in direct funding, so the only way to have things happen faster is for more folks to contribute. I am always happy to help new folks get involved. The three tasks above should be fairly approachable individually.

**Comment by jxrossel** [comment]
Yep, your strategy looks good to me. As for contributing to the project, well, I guess it depends on how much my boss wants his figures to be displayed fast or not... For sure, the kind of python-fu involved in bokeh is above my current level of competencies, but I can always learn something new.

**Comment by bryevdv** [comment]
Ok, well I have moved all three issues to the `0.12.x` milestone (so closing this one). If you find you have bandwidth and want to take a look please let us know, other wise they will be prioritized as resources permit.
