### ISSUE TITLE
Seeking advice for speeding up rendering

### ISSUE THREAD

**Issue by billmcknight1953** [bokeh/bokeh#7071]
I am embedding html  + javascript fragments containing bokeh plots in my Angular 4 app. The backend generates the javascript and html  using the Bokeh components method:
```
script, div = components(plot)
```
The script and div values are combined into a  fragment and stored in file on AWS S3. To display the plots,  the backend returns the html fragment with its script tag and it is appended as a child to the DOM

```
 const fragment = document.createRange().createContextualFragment(graph_html);
 graphElement.appendChild(fragment);
```

This process works and the graphs do render (eventually).  But the bokeh javascript is quite large and comes in at over 2 million characters.   It takes something like 25 seconds to pull in and render the plots. (Really it is quite impressive that the browser can do it in less than 30 seconds with so much javascript.)  But is there some other approach to getting interactive graphs to render faster when the script is so large?

**Comment by bryevdv** [comment]
It's possible there are things that can be done, but possibly not -- Bokeh makes tradeoffs that tilt it towards some use cases at the expense of others. But it's not possible to say anything without much more detail about what exactly you are doing. However, as noted in the issue template, GitHub issues are not the appropriate place for general support or usage questions. GH issues are reserved for bug reports and feature requests only, in order to keep it anywhere near manageable. Please consider posting more details on the public mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
