### ISSUE TITLE
False Error when rendering network graph?

### ISSUE THREAD

**Issue by gryBox** [bokeh/bokeh#7112]
Hi - Is this a false error when rendering network graphs? (`Bokeh 12.10`)
![image](https://user-images.githubusercontent.com/16763201/32090980-b9c71176-bab7-11e7-9c82-20530a575008.png)

The person answering a bokeh question on stack also ran into this issue. [link](https://stackoverflow.com/questions/46397671/using-bokeh-how-does-one-plot-variable-size-nodes-and-node-colors)

Toy Example:
```
import numpy as np
import networkx as nx

from bokeh.io import show, output_notebook  #output_file,
from bokeh.plotting import figure
from bokeh.models.graphs import from_networkx

from bokeh.models import GraphRenderer, StaticLayoutProvider, LinearColorMapper, ColumnDataSource
import bokeh.palettes

G = nx.karate_club_graph()
pal_hex_lst = bokeh.palettes.viridis(21)

# Some Random index
node_color = {k:v for k, v  in enumerate(np.random.uniform(low=0, high=21, size=(G.number_of_nodes(),)).round(1))}

### set node attributes
nx.set_node_attributes(G, 'node_color', node_color)


source=ColumnDataSource(pd.DataFrame.from_dict({k:v for k,v in G.nodes(data=True)},orient='index'))
mapper = LinearColorMapper(palette=pal_hex_lst, low=0, high=21)

### Initiate bokeh plot
plot = figure(title="Resized Node Demo", x_range=(-1.1,1.1), y_range=(-1.1,1.1),
          tools="", toolbar_location=None)

# Graph renderer using nx
graph = from_networkx(G, nx.spring_layout, scale=2, center=(0,0))

# Style node
graph.node_renderer.data_source = source
graph.node_renderer.glyph = Circle(size=10, fill_color={'field': 'node_color', 'transform': mapper})


plot.renderers.append(graph)
output_notebook()
show(plot)

```
Resulting in:
![image](https://user-images.githubusercontent.com/16763201/32091469-e8fbf428-bab9-11e7-8ffc-027229aff13b.png)

**Comment by bryevdv** [comment]
ping @canavandl @clairetang6

**Comment by clairetang6** [comment]
When the GraphRenderer is first created through the `from_networkx` function, its node_renderer is created with a default data source and cdsview that is associated with that data source. Then on the next line when the node_renderer's data source is replaced, the view is no longer associated with the correct source. I'm not exactly sure how to fix this. The error goes away if you add the line `graph.node_renderer.view.source = source`, but it seems like it should happen automatically in this case. The error is supposed to warn you when you've supplied a view to a glyph renderer that doesn't have the correct source.

**Comment by gryBox** [comment]
If I understand correctly there are two different data sources for the plot.  Creating an ugly interaction.

```
# Another Data source
source=ColumnDataSource(pd.DataFrame.from_dict({k:v for k,v in G.nodes(data=True)},orient='index'))

# Graph renderer using nx
graph = from_networkx(G, nx.spring_layout, scale=2, center=(0,0))

# Style node
graph.node_renderer.data_source = source
```
**It is not false**.  And from some playing around.  I agree.

The "fault" lies in how `from_networkx` ingests the `graph`. 

Ideally something like this to happen in `from_networkx`:
```
node_source = ColumnDataSource(graph.nodes(data=True))
edge_source = ColumnDataSource(graph.edges(data=True))
```

IMO: This would save a lot of coding acrobatics. .  I did take a stab at it, using various approaches, and had no luck.   Yes @bryevdv , even `node_source=ColumnDataSource(node_df)`:}

**Comment by bryevdv** [comment]
FYI I can only get this code to run with networkx 1.0 not sure if that's something on our end or not. Anyway, this also works around:
```
graph.node_renderer.data_source.data.update(source.data)
```
That's because it avoids replacing the data source. In general I would advise against *replacing* data sources, and always prefer to try and *update existing* data sources. That's because there are lots of things hooked up, watching, connected to data sources. Replacing them wholesale is a somewhat traumatic event from that perspective, and will probably always be more risky. I'm possibly at the point where I would even consider it unsupported and look into technical means to disallow trying it. 

In any event since there are two possible workarounds, and the original code is not recommended practice, I am going to go ahead and close this. @clairetang6 if you do ever have time and inclination to try and make views update automatically here, please feel free to re-open.
