### ISSUE TITLE
Legend text with click_policy="hide"

### ISSUE THREAD

**Issue by rocheseb** [bokeh/bokeh#7190]
Currently when click_policy is set to "hide" for the legend, clicking a legend item changes the alpha of the text and glyph (in the legend).

It can be really difficult to read the text of hidden renderers when you want to make them visible again.

 Would it be possible to keep the text font color/alpha unchanged and just have the glyph alpha reduced ? OR change the current alpha of hidden legend items to make the text easier to read.

**Comment by bryevdv** [comment]
So, after some investigation, I am not sure any code changes are needed for this, at least right now. The dimming is actually accomplished by overlaying a transparent rect over the glyph and label, not by setting he alpha of the label itself. Right now the rect default alpha is 0.95 which is why things appear so dim. But it is configurable. This code:
```
import pandas as pd

from bokeh.palettes import Spectral4
from bokeh.plotting import figure, output_file, show
from bokeh.sampledata.stocks import AAPL, IBM, MSFT, GOOG

p = figure(plot_width=800, plot_height=250, x_axis_type='datetime')
p.title.text = 'Click on legend entries to hide lines'

for data, name, color in zip([AAPL, IBM, MSFT, GOOG], ["AAPL", "IBM", "MSFT", "GOOG"], Spectral4):
    df = pd.DataFrame(data)
    df['date'] = pd.to_datetime(df['date'])
    p.line(df['date'], df['close'], line_width=2, color=color, alpha=0.8, legend=name)

p.legend.location = 'top_left'
p.legend.click_policy = 'hide'
p.legend.inactive_fill_alpha = 0.6  # NOTE SETTING HERE

output_file('interactive_legend.html', title='interactive_legend.py example')

show(p)
```
Yields this when the bottom two items are hidden:

<img width="741" alt="screen shot 2017-11-09 at 13 36 23" src="https://user-images.githubusercontent.com/1078448/32625855-1336b87e-c553-11e7-8a3f-67f8796e683d.png">

It's probably the case that this could be better documented, so I am updating the issue labels to reflect a docs task. If you (or someone else) wanted to make a PR to update the docs it would be a nice help. The relevant Sphinx file for the user's guide is here:

https://raw.githubusercontent.com/bokeh/bokeh/master/sphinx/source/docs/user_guide/interaction/legends.rst

**Comment by rocheseb** [comment]
Oh thanks, I had seen this parameters but on the docs
https://bokeh.pydata.org/en/latest/docs/reference/models/annotations.html

 it says:

"The fill alpha for the legend background style when inactive."

Which sounds like it would change the alpha of the legend background and not affect the legend items

**Comment by bryevdv** [comment]
@rocheseb I agree that help string is not very good, it could be updated as well:

https://github.com/bokeh/bokeh/blob/master/bokeh/models/annotations.py#L110-L112
