### ISSUE TITLE
CustomJS doesn't work on line() ?

### ISSUE THREAD

**Issue by KC22C2** [bokeh/bokeh#7206]
Hello again,

#### Environment
- fully up-to-date Miniconda3 - bokeh 0.12.10
- HTML tested with Chrome

### Code
```
# inspired from https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/callbacks.html#customjs-for-hover
from bokeh.plotting import figure, output_file, show
from bokeh.models import ColumnDataSource, HoverTool, CustomJS
import random

output_file("hover_callback.html")

count = 500
x = [random.random()*10 for _ in range(count)]
y = [3] * count
x2 = [""] * count

p = figure(plot_width=400, plot_height=400, tools="", toolbar_location=None, title='Hover over points')
cr = p.line(x='x', y='y', source=ColumnDataSource({ 'x': x, 'y': y, 'x2': x2 }) )

code = """
	var cdata = circle.data;
	var indices = cb_data.index['1d'].indices;
	console.log("called");
	for (i=0; i < indices.length; i++) {
		console.log("in");
		ind0 = indices[i];
		cdata.x2[ind0] = cdata.x[ind0]*cdata.x[ind0];
	}
"""

p.add_tools(HoverTool(
	tooltips =	([
				("x", "@x"),
				("y", "@y"),
				("x2", "@x2"),
			]),
	callback = CustomJS(args={'circle': cr.data_source}, code=code), 
	renderers = [cr]))

show(p)
```

#### Description of expected behavior and the observed behavior
Although the tooltips appear, the for loop is never entered, as demonstrated by the console.
This is specific to line(), scatter() works fine.
I'd expect that the loop would contain the same indices than those displayed in the tooltip.

Thanks

**Comment by bryevdv** [comment]
`Line` and `Patch` are a bit different than other glyphs, in that they have an implicit connectivity. Wheres with circles, the mouse might hit any number of N circles, with `Line` there only "one" line. Because of this topological distinction, you need to look at the "0d" index instead:
```
code = """
    var cdata = circle.data;
    var indices = cb_data.index['0d'];
    console.log("called", indices);
"""
```

Please note that that we are in the process of completely re-working how selections are handled in Bokeh, so you may want to pay close attention to upcoming migration notes. Apologies in advance for breaking changes, but this corner of Bokeh is too complicated and unwieldy, and addressing must happen before 1.0 in order to have a good and stable API going forward for the long term.
