### ISSUE TITLE
Including both log and linear axis types not working

### ISSUE THREAD

**Issue by doiko** [bokeh/bokeh#7217]
When trying to add an extra axis of different type there are problems with the tickers and the axis using bokeh==0.12.10.

Ticks are wrong, and the axis is linear although defined as LogAxis.
Trying to pan destroys the ticks.
Any idea?

code to replicate
```
import numpy as np
import  bokeh
from bokeh.plotting import figure, show
from bokeh.models import LinearAxis,LogAxis,Range1d
N = 100
x = np.linspace(1, 100, N)
plot=figure(tools="pan,wheel_zoom,box_zoom,reset,previewsave",
        y_axis_type="linear" , x_axis_type="linear", y_range=[0.1, 110], title="log axis scatter example")
plot.scatter(x, x+1, line_width=2, line_color="yellow", legend="y=(x+1)")
plot.extra_x_ranges ['Second Axis'] =  Range1d(start=1, end=110)
axis=LogAxis(x_range_name='Second Axis', axis_label = 'Second Axis')
plot.add_layout(axis, 'above')
plot.scatter(x, x, line_width=2, line_color="green", legend="y=x",x_range_name='Second Axis')
show(plot)
```
![untitled](https://user-images.githubusercontent.com/33360731/32841767-84cfe4f2-ca1b-11e7-882b-714c6c58524a.png)

**Comment by bryevdv** [comment]
Seems like a bug, I am afraid I don't have any immediate workaround to suggest.

**Comment by josepmv** [comment]
The very same also happens when adding LogAxis as an extra_y_range.

And if the range starts at 0, it doesn't plot the ticks neither the numbers, just a line:
plot.extra_x_ranges ['Second Axis'] =  Range1d(start=0, end=110)

**Comment by p-himik** [comment]
With the current API, it's not entirely clear how to approach it. The ranges don't know anything about scale, and yet we specify extra ranges for glyph renderers - not scales. It's also possible to attach multiple axes to the same range, and it could even be a desirable thing to do in some cases.

I think that it would make more sense to pass glyph renderers the whole axis or axis model name instead of just range. @bryevdv Do you have any thoughts on this?

**Comment by bryevdv** [comment]
@p-himik The "extra ranges" code is very old, back from a time when it seemed easier to sometimes just not use models for everything. Now that the model system has improved and well-understood. The right answer is just to always use models directly. If I were to do this today (or think about improving it) I would say such coordination should happen via `Instance` properties and sharing the relevant models directly. Perhaps theres a way to move towards this (while still maintaining named extra ranges for back-combat) I'm happy to discuss/iterate on proposals

**Comment by doiko** [comment]
@bryevdv can you give an example (link) of your suggestion on how to implement multiple axes on a single plot?

**Comment by bryevdv** [comment]
@p-himik I'd have to seriously sit down to really flesh something out. Offhand it seems like:
```
p.circle(..., a_xaxs = some_extra_axis)
```
might move in the right direction, at least for `bokeh.plotting` (i.e. any additional bookkeeping is handled internally). However it does couple glyph position data mapping too closely to the presence of an actual visual axis annotation.   I suspect that what really might help this is make a new model to represent "a range plus a scale" and then have both glyphs and axes be configurable with this new model. But I'm not sure how easily that can be done without breaking things. Like I said it will take some devoted thought.

**Comment by tarikaltuncu** [comment]
Is there any update to this issue?

**Comment by tarikaltuncu** [comment]
Was there an update on 0.13.0 for this? Thanks

**Comment by bryevdv** [comment]
Although things are certainly occasionally fixed "by accident" during unrelated work, any intentional stesp will always be reported in the issue or a linked PR, so there is never any reason to ask about updates. 

This particular issue is the unfortunate basically the worst combination:

* A use case that is not very common
* A fix that is difficult and/or needs breaking changes

Given that Bokeh, like many OSS projects, has much more work than people to do it, I will be frank and say that I would not expect this to be prioritized in the near future. If workarounds like custom formatters are not sufficient and you need an immediate solution, I'd suggest looking to other tools.

**Comment by haroldfarmerNextGen** [comment]
I was just wondering if there is a solution to using both the log and linear axes types. I see that sistemicorp seems to be able to do it but I still see that this issue is open. Is this a temporary solution?

**Comment by sistemicorp** [comment]
@haroldfarmerNextGen : I am **not** able to do it.  What I did do (as a workaround in my app) was manually set the (secondary) linear axis range to values that kinda stretched out the axis so it kinda is usable - but it really isn't.  That "stretching" is not shown in the above snippet as the goal of the above is to aid the developers.

**Comment by haroldfarmerNextGen** [comment]
Ah, I see now. Thanks

**Comment by bryevdv** [comment]
There is an open WIP PR for this but it is not merged yet https://github.com/bokeh/bokeh/pull/11020

**Comment by haroldfarmerNextGen** [comment]
Is there an estimated time to when this will be merged?
