### ISSUE TITLE
Refining the templating capability for Bokeh server

### ISSUE THREAD

**Issue by memetb** [bokeh/bokeh#7226]
I've been reading through some of the previous conversations on the matter, in particular #4176.

On issue #4176, there was a debate as to what owns a template etc. @havocp  pointed out that it's possible to alter a document template during the call to modify_doc but that doesn't make sense semantically.

Why not allow for code to do the following:

```
endpoint1 = Application(FunctionHandler(modify1), template="foo/bar.html" )
endpoint2 = Application(FunctionHandler(modify2), template="foo/baz.html" ) 

server = Server({'/foo/bar': my_endpoint1,
				'/foo/baz': endpoint2},
				num_procs=1,
				extra_patterns=[('/', IndexHandler),
						('/rest-of-tornado-app, blah blah) ])

server.start()

# do a bunch of other stuff

reactor.run()

```

This can be achieved by:

- allowing a `kwargs` for the `Application` class to accept a `template` keyword and forward it [here](https://github.com/bokeh/bokeh/blob/584638b3e88c6ca5bd1d3461d72db159c86701e7/bokeh/application/application.py#L104) 
- propagating that variable to the `Document` class constructor [here](https://github.com/bokeh/bokeh/blob/584638b3e88c6ca5bd1d3461d72db159c86701e7/bokeh/document.py#L288)
- Then replacing [this line](https://github.com/bokeh/bokeh/blob/584638b3e88c6ca5bd1d3461d72db159c86701e7/bokeh/document.py#L293) with `self._template = kwargs.pop('template', FILE)`.

With regards to @havocp 's comment from above, I think that the template should *not* be settable during the `modify_doc` function call. The warning condition mentioned in that discussion seems like a poor code structure.

My opinion is that the `modify_doc` semantics should become closer to a template renderer where successive callees could overwrite the *values* in template variables, and there would be nothing wrong with that from a programmer's perspective. Whisking the entire template away from underneath you doesn't make sense unless we allow for that but maintain the template variable values...

Btw, I've tested the above code by subclassing `Application` and it *looks* nice.

Comments?

**Comment by bryevdv** [comment]
@memetb Bokeh apps already support templates, and user specified template variables. See:

https://bokeh.pydata.org/en/dev/docs/user_guide/server.html#directory-format

It's possible there are further enhancements to make, and perhaps those docs are a bit out of the way. But we should start with what exists already as a basis. There is also already issue https://github.com/bokeh/bokeh/issues/4986 to allow for individual app models to be placed in a template separately (currently everything has to go in one Bokeh layout which is restrictive)

**Comment by memetb** [comment]
@bryevdv thanks for the feedback. 

I had gone through those samples and I'm aware that bokeh supports templating and I'm not suggesting yet another templater.

In both of these examples, `bokeh serve` is being used to serve a "fixed" directory structure and it's not easy to create multiple handlers, each with their own structure (template, and document structure).

I was not able to find any documentation (or mechanism in the code) to allow for creating an `Application` object that has its own bespoke template. Did I miss this?

**Comment by bryevdv** [comment]
> I was not able to find any documentation (or mechanism in the code) to allow for creating an Application object that has its own bespoke template. Did I miss this?

Not exactly, but the template is a property of the `Document`. The `DirectoryHandler` happens to look for a template file and attach one in its `modify_document` but again that's just a convenience it provides, anything can add a template to a document at any time. In terms of making things easier in general I might suggest this:

* make a new `TemplateHandler` that just accepts a template (and maybe template args?) and simply attaches the template to `doc` in its `modify_document` method. 

* refactor the director handler to delegate to this template hander instead of attaching to the doc itself

Everything above maintains the status quo, then:

* Have `Application` accept a template (and args?) arguments optionally. If they are passed, the application automatically creates and adds a template handler as the last handler o `self.handlers`

In this way, a template passed in as an argument would override any template in a directly, which is probably reasonable semantics, and extends ease of adding a template to any application.

regarding:

> My opinion is that the modify_doc semantics should become closer to a template renderer where successive callees could overwrite the values in template variables, and there would be nothing wrong with that from a programmer's perspective.

I think this is already the case. Any handler can modify `template_variables` and I don't think there is any issue or problem or reason not to do that. Thoughts?

**Comment by memetb** [comment]
I think I understand the approach you're taking. You want a document to be created and then the template be modified on the fly by the handler chain. Is this correct?

If so, is there a specific reason you think this is better than the document being created with the appropriate template from the get-go?

With regards to my comment about semantics of `modify_doc`, it's in reference to your comment from #4176
> Well so that's my question, is a template a property of the `Document`? or of an `Application`? Could make template private, only updatable by handlers using private APIs


I don't see a good reason to not have a document always exist with its destined template from the start. In that sense, the template would be a property of the `Application` which is indirectly a `Document` factory. The `template` value in `Document` would be set at creation time and would be immutable (semantically). 

Like I said, a good example where a `modify_doc` changing the template on the fly might be useful. But my understanding of the webstack is that we want individual endpoints to behave identically (from a caching and just general HTTP behaviour point of view)

 Perhaps I'm not seeing a use case or perhaps I'm not making my case clear enough?

**Comment by bryevdv** [comment]
> I think I understand the approach you're taking. You want a document to be created and then the template be modified on the fly by the handler chain. Is this correct?

Yes exactly

> If so, is there a specific reason you think this is better than the document being created with the appropriate template from the get-go?

It's a simple isolated component amenable to easy testing, also this usage is pretty much a model  case of the intent of the handler chain. 

> I don't see a good reason to not have a document always exist with its destined template from the start. In that sense, the template would be a property of the Application which is indirectly a Document factory. The template value in Document would be set at creation time and would be immutable (semantically).

I'm not sure I think I think dynamic template would be common, but if it falls out naturally I would also not want to go out of my way to preclude it. In any case it's associated with the document because it's the document that actually has all the info about a session. The application is really a factory for documents. 

> Agreed. I think the change should be limited entirely to this. It will indeed make testing easier.

> Perhaps I'm not seeing a use case or perhaps I'm not making my case clear enough?

I'm not sure I follow the last bit, it think adding the option args to Application and having it add a `TemplateHandler` would be a trivial change once the other part is done, and would satisfy your desire for a more convenient way to supply a template?

**Comment by memetb** [comment]
> I'm not sure I follow the last bit, it think adding the option args to Application and having it add a TemplateHandler would be a trivial change once the other part is done, and would satisfy your desire for a more convenient way to supply a template?

The comment was simply that I thought it'd be more appropriate to *only* have the Application object modified (without the handler mechanism).

The reason is that while the Document has the variable, it's really the URL/endpoint that determines what the content being served is. In other words, the Application object is the declarative part, whereas the Document object is the run-time implementation (hence my reticence at a runtime swapping of the template).


In any case, it can be implemented it either way and it's your call in the end. 

How would you like to proceed? As it is right now, I'm simply using a subclass of `Application` in my own solution so this is not a critical task for me. I think I could get it done in about 2 weeks.

It would involve:
- modifying `Application` to propagate `kwargs`
- adding a `TemplateHandler` to the handler chain during `Document` creation
- as a minor point, I'd recommend adding two `kwargs` to `Application`:
    - `template` of type `Template`, and...
    - `template_path` of type `string` which gets loaded as a `Template` object.

**Comment by bryevdv** [comment]
Do you mean propagate the args as described in the top post (i.e. in `create_doc`)? I don't agree with that because I'd like for `TemplateHandler` to be the one place responsible for modifying docs with by adding templates. having `create_doc` also do it would be code duplication. My suggestion is for the arguments to be propagated by passing creating a `TemplateHandler` for them, and adding that to the end of the handler chain. That has the same effect but avoids having multiple places responsible for executing basically the same code. 

I'd also prefer a single `template` arg that can be either be a `Template` or ` string, which would be interpreted as a path to a template to load. Having both means having to have logic and testing to handle the case where a user erroneously provides both, and I'd rather avoid that.

**Comment by bryevdv** [comment]
As for timeline, there's no rush, he next release is imminent so this will go in after that in any case.

**Comment by memetb** [comment]
Sorry, I was not clear enough.

A `template` keyword will be set [here](https://github.com/bokeh/bokeh/blob/584638b3e88c6ca5bd1d3461d72db159c86701e7/bokeh/application/application.py#L96) and a `TemplateHandler` will be created in the `__init__` method directly and added to chain. No other changes will be done.

Roger on the `string` or `Template` type for the `template` keyword.

Is the above right?

**Comment by bryevdv** [comment]
Sounds good, look forward to your PR!

**Comment by bryevdv** [comment]
@memetb did you still intend to work on this? If not I think I will close this discussion

**Comment by memetb** [comment]
@bryevdv sorry for late response. Yes, I've been just too swamped at work. 

We should close it and revisit in the future if need be. Sorry I wasn't able to help out more.
