### ISSUE TITLE
Multiprocessing in Windows is not available (ERROR:module 'os' has no attribute 'fork')

### ISSUE THREAD

**Issue by AzraelDD** [bokeh/bokeh#7229]
_Hi everyone,_

_thanks for your awesome work. I guess this might be a known issue, but I could not find it via search._

Multiprocessing in Windows is not available, since `os.fork()` command is not supported under Windows.
Please consider using other multiprocessing modules. Or make Bokeh show a warning and revert to default of 1 worker, instead of crashing with an error.

`bokeh serve myapp.py --num-procs 0`
```
2017-11-17 14:03:57,761 Starting Bokeh server version 0.12.10 (running on Tornado 4.5.2)
2017-11-17 14:03:57,761 Starting 8 processes
ERROR:module 'os' has no attribute 'fork'
```

OS: Windows 10
Bokeh: 0.12.10
Python: 3.6.2

**Comment by bryevdv** [comment]
Bokeh doesn't implement any multiprocessing of its own at all. The `num_procs` value is simple passed on to Tornado, which evidently does not support this feature on windows: https://github.com/tornadoweb/tornado/issues/1669 

I am reticent to add a warning and fallback behavior. In my experience log and warning messages are routinely ignored or overlooked by users. As such, falling back to 1 process may lead people to think that things are working as expected (i.e has multiple processed), when in reality they are not. This kind of effectively silent failure is often a source of bugs and problems. 

I think it would be preferable to add explicit documentation to the command line tool and reference guide. If there were any platform testing at all I would suggest only coverting to a more informative runtime error exception, e.g. "Windows only supports --num-procs=1" rather than no exception.

**Comment by AzraelDD** [comment]
I guess your concerns are valid. Thanks for the explanation!
