### ISSUE TITLE
Bokeh show() produces blue screen and incomplete toolbar on Cloud9 Linux server.

### ISSUE THREAD

**Issue by mgmoulton** [bokeh/bokeh#7246]
Hi,

The simplest possible graph ,,, no widgets or anything else ... produces a blue screen and incomplete toolbar on Cloud9 Linux server.  This is a public subscription based cloud hosting service.
```
#test.py
from bokeh.plotting import figure, output_file, show
# create a Figure object
p = figure(plot_width=300, plot_height=300, tools="pan,reset,save")

# add a Circle renderer to this figure
p.circle([1, 2.5, 3, 2], [2, 3, 1, 1.5], radius=0.3, alpha=0.5)

# specify how to output the plot(s)
#output_file("test1.html")

# display the figure
show(p)
```

**Comment by bryevdv** [comment]
Hi, I am afraid I don't know anything about Cloud9, nor do I have access to it to test anything out. Hover, your code above works as perfectly expected when I run it locally:

<img width="304" alt="screen shot 2017-11-25 at 12 53 28" src="https://user-images.githubusercontent.com/1078448/33233702-d146b9ac-d1df-11e7-855c-277d7ac349f2.png">

I've included the HTML output from my local execution here: 

    https://gist.github.com/bryevdv/c7c1592a821622dcf775aa1b952d83ba 

In case you would like to either compare this output to your output more closely, or to see if this file behaves differently for you that it does for me. 

In any case, until something can be reproduces, I would classify this as a support issue, and would suggest taking this to the mailing list or SO in order to pose the question to a wider audience that might include people that have experience with or access to Cloud9.
