### ISSUE TITLE
Feature Request: Docking widget

### ISSUE THREAD

**Issue by davidpasquale** [bokeh/bokeh#7254]
HI, I love this project!
One thing that I feature that is currently missing is the possibility do dock the widgets.
In the JS world I found a counmp[le of open source project that are very interesting:
PhosphorJS [](http://phosphorjs.github.io/index.html) and  
Golden-layout []([http://golden-layout.com/)
Do you have any plan to build in such a widget?
Do you have any tutorial or guiline to implement such JS libraries?

Thank you very much for your time!

**Comment by bryevdv** [comment]
Hi, it is very unlikely that something like that would be built directly into Bokeh. First because Bokeh is already a very large library as JS libraries go, and we are actually looking for ways to trim, not expand it. But more importantly, it's better for everyone I think if Bokeh remains neutral about this, and simply makes it easy to integrate with whatever external libraries that different users might want to use. It's already very easy to embed standalone (i.e. non-server) Bokeh objects in arbitrary HTML context, so in particular they could be easily places in Phosphor containers. Once https://github.com/bokeh/bokeh/issues/4986 is completed (it is a very high priority for the next release) then the same will be true of distinct objects in Bokeh server applications as well. 

I think  this will provide the flexibility for users to embed Bokeh components in more sophisticated layout systems. If a more "direct" Bokeh integration is desired, users could even write custom Bokeh extensions to wrap those layout facilities (and hopefully share them with the community). But a custom  extension seems like a much better place for this code, than in core Bokeh.
