### ISSUE TITLE
Unclear Filters API

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#7274]
Bokeh 0.12.11

There are multiple classes of the filters that may be used with `CDSView`. One of them is `Filter`, others inherit from it.
There's a couple of places that I think can be improved:

1. Almost all of the code in `Filter` is used only by `CustomJSFilter` - probably that code should be directly in `CustomJSFilter`, since `Filter` is the parent class of all filters
2. `GroupFilter` sets `@indices` inside `compute_indices`, but the field was not declared previously - looks like a leftover from some refactoring

**Comment by bryevdv** [comment]
cc @clairetang6

**Comment by clairetang6** [comment]
Hi @p-himik, 

1) The idea with having the code to deal with arrays of integers or arrays of booleans in `Filter` was that it could be used to create a filter that behaves as either an `IndexFilter` or `BooleanFilter`. This would be useful if you don't know beforehand whether you will have an indices or boolean array to filter on. 

2) Yeah, I don't think the `GroupFilter` needs to set `indices` on itself. The `compute_indices` function just needs to return it. But you could imagine a situation where `indices` is an internal variable on the `GroupFilter` that `compute_indices` could return in situations where the "computation" doesn't need to occur again because the data and filter parameters haven't changed.

**Comment by bryevdv** [comment]
`GroupFilter` no longer sets `@indices`
