### ISSUE TITLE
Feature Request: Sankey Diagrams Plotting Capabilities

### ISSUE THREAD

**Issue by jaradc** [bokeh/bokeh#7280]
Feature Request
Sankey Plots for Python like the ones shown below pretty much don't exist. Matplotlib does provide sankey plotting capabilities but to my knowledge can't output sankey diagrams like the ones below. [Plot.ly has such capabilities ](https://plot.ly/python/sankey-diagram/) but I don't want to pay to use plot.ly just to create sankey diagrams. Most sankey plots [rely on d3.js to make sankey diagrams](https://bost.ocks.org/mike/sankey/) but those options require a lot of heavy lifting. These types of plots would fit in with the unique types of plots bokeh currently offers. That's why I'm suggesting it.

![sankey1](https://user-images.githubusercontent.com/12854767/33592335-550fd2a8-d93f-11e7-97cc-867d45a64997.png)
![sankey2](https://user-images.githubusercontent.com/12854767/33592336-57b951dc-d93f-11e7-92af-6fac75bd0946.png)
![sankey3](https://user-images.githubusercontent.com/12854767/33592337-59363c5a-d93f-11e7-8b2f-8bec9702082b.png)

**Comment by bryevdv** [comment]
Thanks for the discussion @jaradc I think at this point it probably makes more sense to think about something like Sankey diagrams for [Holoviews](https://github.com/ioam/holoviews) rather than core Bokeh. We are trying to pare core Bokeh down to be a rock solid foundation for other higher level tools such as Holoviews to build on reliably. Alternatively it might make sense to develop a custom extension to Bokeh to implement Sankey diagrams. I'm definitely interested in making it easier for extensions to be created and published and shared among users. That's a non-trivial effort that I will need help with. But something like this might serve as a good focus point to motivate that effort.

cc @philippjfr @jlstevens

**Comment by philippjfr** [comment]
There is an open issue about it in HoloViews here: https://github.com/ioam/holoviews/issues/1123

Sankey diagrams are somewhat similar to Chord charts, which I'm developing [here](https://github.com/ioam/holoviews/pull/2138), so I think it's definitely something we would consider including. I can't promise how soon I'll have time to work on it though.

**Comment by jaradc** [comment]
Thanks for your consideration. I wasn't aware of Bokeh's core mission so thank you for that awareness. Extensions are something I was not familiar with until now. I also wasn't aware of holoviews until now so I'll definitely check that out! I've seen chord charts (didn't know that's what their name was) before and the image at holoviews looks very impressive.

My use-case for sankey charts is to visualize web page path data in a way that a typical person can instantly make sense of. Even sankey charts aren't the best I don't think but I don't have a good alternative. Web path data for a million users for example is a lot of pageviews, paths and overall journeys to try and make sense of.

Charts I've considered are: networkx (DiGraphs), [networkx circular tree](https://networkx.github.io/documentation/networkx-1.9/examples/drawing/circular_tree.html), sunburst plots, decision tree-like plots (hierarchical), or even interactive network plots where the node isn't a circle but a screenshot of each web page.

In any event, feel free to close this if you feel it's not relevant. Sorry, I don't suggest features very often so don't know if I'm supposed to close it or not. Thanks for your time!

**Comment by bryevdv** [comment]
No need to apologize. I will go ahead an close this here in favor of the discussion on the Holoview tracker.
