### ISSUE TITLE
Correctly showing Wedge Hover Tooltips with "clock" orient

### ISSUE THREAD

**Issue by fburanelli** [bokeh/bokeh#7428]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Python 3.6.3
Bokeh 0.12.10

#### Description of expected behavior and the observed behavior

The hover shows information of all the slices except the one you are pointing to, it should work the other way around.

#### Complete, minimal, self-contained example code that reproduces the issue

Example code taken from [https://stackoverflow.com/questions/48305017/correctly-showing-hover-tooltips-on-bokeh-wedge-chart](url)

```
import numpy as np
from bokeh.plotting import figure
from bokeh.io import show, output_file
from bokeh.models import HoverTool, ColumnDataSource
from math import pi



percents = [0, 5/143, 51/143, 88/143, 108/143, 141/143, 1.0]
category = ['A ', 'B ', 'C ', 'D ', 'E ', 'F']
counts = [5, 46, 37, 20, 33, 2]
starts = [1/2*pi-(p*2*pi) for p in percents[:-1]]
ends = [1/2*pi-(p*2*pi) for p in percents[1:]]
colors = ['#889dba', '#1f356f', '#1e92b8', '#33748a', '#a5d3e3', '#bbc2d4']
# create source
source = ColumnDataSource(
    data=dict(
        x=[0 for x in percents],
        y=[0 for x in percents],
        radius = [0.5 for x in percents],
        percents=percents,
        category= category,
        starts=starts,
        colors=colors,
        ends=ends,
        counts = counts
    )
)

TOOLS = "hover"

p = figure(plot_width = 500, plot_height = 500, x_axis_label = None, y_axis_label = None,
title = 'Type', tools = TOOLS)

p.title.align = 'center'
p.title.text_font = 'arial narrow'

p.wedge(x='x', y='y',  radius = 'radius', direction="clock",
                start_angle='starts', end_angle='ends', color='colors', source=source)

hover = p.select(dict(type=HoverTool))
hover.tooltips = [
    ('category', '@category'),
    ('percents','@counts')
]


p.axis.visible = False
p.ygrid.visible = False
p.xgrid.visible = False

output_file(pie.html')
show(p)

```

The hover works correctly if the user inverts the data and removes the clockwise statement as shown in this answer of the Stackoverflow question.
[https://stackoverflow.com/questions/48305017/correctly-showing-hover-tooltips-on-bokeh-wedge-chart/48306227#48306227](url)

**Comment by j-yu** [comment]
hi, can i work on this?

**Comment by bryevdv** [comment]
@j-yu we are always happy to have new contributions. The `_hit_point` function for wedges, which is probably what needs to be fixed up, is here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/glyphs/wedge.ts#L46

It seems as tho the current function only correctly hit-tests when the orientation is `anticlock`

Additionally, it would be good to add `scx` and `scy` methods so that hover tooltips get positioned better than just in the center, you can find an example for the annular wedge here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/glyphs/annular_wedge.ts#L119-L126

I'd expect the corresponding versions for `wedge` to be nearly identical 

In terms of getting setup and BokehJS built, there is a developer guide here:

https://bokeh.pydata.org/en/latest/docs/dev_guide.html
