### ISSUE TITLE
Bokeh layout elements overlap in new version

### ISSUE THREAD

**Issue by wochner** [bokeh/bokeh#7443]
I have a layout overlap since upgrading to the newest version of Python/Bokeh (switched to Conda/Envs..)

Bokeh 0.12.13 / Python 3.6.4 (64-bit) / Windows 7 / Firefox 52.5.0 (32-Bit)

Expect the Multiselect widgets to be below the figure.

Excerpt from the code (the layout section). Functionally it works.

```
tab1 = Panel(child=draw_spread_scatter(df),title="Spread Scatter")
tab2 = Panel(child=draw_spread_history(df),title="Spread History")
tabs = Tabs(tabs=[tab1, tab2])

l = layout([
    [tabs,timeframe_select, curve_section],
    [country_select, rating_select, currency_select, x_axis_select],
    [industry_select, industry_group_select, barclays_select],
    ])

curdoc().add_root(l)

```
![grafik](https://user-images.githubusercontent.com/25208141/35231203-76c7a310-ff98-11e7-95bb-e1d5a0733934.png)

**Comment by wochner** [comment]
Figured out my previous version and confirm this issue did not exist in version 0.12.07

**Comment by mattpap** [comment]
The problem here is that tabs widget reports incorrect height that only includes the header, so select box is placed "correctly" below it and overlaps plot panels. This kind of worked before by coincidence, but somewhere around 0.12.7 bokeh's layout was being improved and those fixes reveled cases like the one in this issue.
