### ISSUE TITLE
Remove rows from ColumnDataSource

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#7491]
We can use `update` to replace all rows in a ColumnDataSource, `stream` to append rows, and `patch` to modify values of rows.  Is there an operation that allows users to remove select rows from a ColumnDataSource?  This would be important, for example, if rows of data stopped being valid.  If such an operation exists, what are its performance characteristics?

**Comment by bryevdv** [comment]
There is not any such operation currently. Bokeh's built underlying data sources are columnar, so removing a row is likely to be somewhat expensive, i.e. N array deletions for N columns. Possible avenues:

* If points just need to be *hidden* but it would otherwise be OK to not actually remove them, then a CDS filter is probably worth looking at as an alternative

* Consider implementing the operation, even if it is not especially performant, if it just needs to be possible at all

* If you really need to optimize for deleting rows, it's possible to imagine a custom extension for a new data source that stores internally as rows but that can adapt to the existing CDS interface/usage. It's possible this would require supporting work in BokehJS to abstract away any direct access to `.data['foo']` with some `.get_column('foo')` first.

**Comment by mrocklin** [comment]
My original plan was to hide rows until I had enough to warrant a full
update rather than a stream or patch command.  Looking at a CDS filter is
an interesting choice.  I hadn't considered that before.

**Comment by mrocklin** [comment]
In the case of `IndexFilter`s is it cheap to add new indices one-by-one similar to `ColumnDataSource.stream`? My guess is that the answer is "no", but I thought I'd check.

**Comment by rsska** [comment]
I have large sections of rows that I would like to remove and update with and another sections of rows (could be more or could be less). Both Sections meet the same filter CDS filter. I can give the "slice" of rows to remove by removing their values - and then stream to add the new values, but the CD is growing.

**Comment by bryevdv** [comment]
This discussion seems to have gone stale, so I am closing this. Happy to re-open if there is a concrete proposal and especially if someone is willing to help work on it.
