### ISSUE TITLE
Enforce usage of npm >= 5.6

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#7571]
Because of #7514 , I had to run ``npm run prepare`` in order to generate a .package.json file (containing a hash of package.json) in order for gulp build to run.

I would suggest two things:
* Better message for when .package.json doesn't exist - currently it says ``package.json has changed. Run `npm install`.`` but suggesting running ``npm run prepare`` in this case would be clearer.
* Document in the dev guide the need to run the ``npm run prepare`` command

bokeh=0.12.14dev4

**Comment by mattpap** [comment]
`prepare` is a special npm task, and will run whenever `npm install` (literally, no arguments) or `npm publish` is run. You shouldn't have to run in manually. Now, did `npm install` fail to run `prepare` for you? If so, then this is bug. Otherwise you should always run `npm install` whenever dependencies change or you clone a repository or check out a different branch. Thus I think the message is accurate. You should also not mix `npm install` with `npm install pkg_name` when `package.json` is present (unless you really know what you are doing).

**Comment by canavandl** [comment]
I see that the ``prepare`` task is a npm@4.0.0 feature I was was running npm@3.x.x that shipped with node v6.11.0. Bokeh's meta.yaml appears to say that nodejs >=8.8,<9.0 is required, so my development environment is out of date.

That said, is it worth adding a node version check to the build task?

**Comment by mattpap** [comment]
Actually, due to bugs in npm, we will have to enforce npm >= 5.6.0.

**Comment by mattpap** [comment]
Also, looks like npm 5.6.0 is way faster than the previous versions (7 seconds vs ~30 on my computer for `npm install`).
