### ISSUE TITLE
Allow setting of xaxis in kw of figure()

### ISSUE THREAD

**Issue by MelvinYin** [bokeh/bokeh#7650]
```
from bokeh.plotting import figure
from bokeh.models.tickers import AdaptiveTicker

p1 = figure(plot_width=400)
p1.xaxis.ticker = AdaptiveTicker()

# AttributeError: '_list_attr_splat' object has no attribute 'ticker'
a = p1.xaxis.ticker

# But this works, giving LinearAxis.
b = p1.xaxis
```
This makes it troublesome when one wants to create a generic `figure`, that can be used as a template. 

Also, `figure.xaxis` cannot be set currently. It should be possible for a check to be done on `__setattr__` to `xaxis`, that requires the input to be an instance of `Axis` or its subclasses. Otherwise, it doesn't seem to make sense that `xaxis.ticker` can be set but not `xaxis`.

```
p2.xaxis = b    # AttributeError: unexpected attribute 'xaxis' to Figure
```

Finally, if `xaxis` can indeed be set, it should be possible to set it as a `kwarg` when instantiating `figure`, something like 
```
p1 = figure(plot_width=400)
p1.xaxis.ticker = AdaptiveTicker()

p2 = figure(plot_width=p1.plot_width, xaxis=p1.xaxis)
```
Bokeh 0.12.14, Python 3.6.4.

**Comment by bryevdv** [comment]
@MelvinYin This is really a usage type question, so I am going to close and refer to the mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

As per the project GH usage guidelines. 

I will say a couple of quick things here tho:

* `.p.xaxis` is a convenience property that allows easily setting *all* the x axes, because there can be several

* It is not really intended to be settable at all

* I can't think of any reason to share actual `Axes` between plots, ever. I would not expect that to work. If you want linked panning, etc. you want to share *Range* objects, not Axes. see: https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/linking.html#userguide-interaction-linking
