### ISSUE TITLE
More updates to Selection docs

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#7656]
* Selection class and module doc strings can be expeanded
* Selection properties need help strings
* User guide chapter on data can be expanded

Additionally @clairetang6 there is a question with @jlstevens about why the key for `multiline_indices` is a string and not an int?

**Comment by clairetang6** [comment]
@jlstevens, the reason the key for multiline_indices is a string is just because keys must be strings on the JS side, but I think it would be possible to allow ints as keys on the python side if that would be useful. Before selections were made into a model, they only existed on the JS side and so the "2d indices" had strings for keys, and I didn't think to change them when I brought it over to the python side.

**Comment by bryevdv** [comment]
Going to call this a dupe of #9073
