### ISSUE TITLE
All release notes on one webpage

### ISSUE THREAD

**Issue by rocheseb** [bokeh/bokeh#7715]
Would it be possible to have a version of the release notes in the same style as e.g. the pandas package ? http://pandas.pydata.org/pandas-docs/version/0.21/release.html

Everything in one page with one long scrollbar. This makes the navigation easier with ctrl+f, especially to find breaking changes and deprecated features.

The Releases page on the bokeh website is well structured, but hard to use when you don't know which version to look up.

**Comment by bryevdv** [comment]
I'll work on this after the current release in progess.

**Comment by bryevdv** [comment]
Just circling back here, I think it is likely that we will soon remove migration notes from the "releases" page on the published docs, and move them to a wiki page so that they can be more easily edited and updated (especially if something comes to light after a release). But we will keep them all on a single wiki page. The releases page will then just contain the high level bullet points for features/fixes.
