### ISSUE TITLE
Feature request: Offline PDF documentation of Bokeh

### ISSUE THREAD

**Issue by duytrung** [bokeh/bokeh#7731]
Hi, 

I usually travel so I would like to download the whole docs for offline browsing. Is it possible for bokeh to provide a pdf documentation like of the other packages such as numpy?

I think that it would be convenient for users need to browse the docs by ipad or laptop without an internet connection.

Thanks

**Comment by tfblum** [comment]
@bryevdv I believe it could be useful to be able to spin up a local doc server so that the docs are served as html but only at localhost. I have a similar issue in that I work on the bus to work with a bad internet connection.

**Comment by bryevdv** [comment]
@tfblum that's certainly already possible, though you have to build the docs locally yourself. See: 

https://bokeh.pydata.org/en/latest/docs/dev_guide/documentation.html

I don't see any way around building yourself (if the issue is limited bandwidth, building them yourself is the way around for that)
