### ISSUE TITLE
Changelog missing information on row_header

### ISSUE THREAD

**Issue by hyamanieu** [bokeh/bokeh#7733]
The latest changelog is missing at least one information (link: https://github.com/bokeh/bokeh/blob/0.12.15/CHANGELOG)

An attribute of the DataTable widget became singular (row_header/s) and a new attribute appeared (index_header). This makes some bokeh applications not back compatible between 0.12.14 and 0.12.15

thank you.

**Comment by bryevdv** [comment]
@hyamanieu it's not there because removing it was an [unintentional mistake](https://github.com/bokeh/bokeh/issues/7719). There was supposed to be a clean compatible deprecation deprecation of `row_headerS` but the python property was accidentally misspelled without an S, and  the accident was not noticed in time.  

That said, the changelog is purely for capturing what issues were closed between releases, so no changes would go there. Migration notes are captured on the releases page, e.g. 

https://bokeh.pydata.org/en/latest/docs/releases/0.12.15.html 

Ad you can see there that it describes how `row_headers` was supposed to be deprecated.  *(NOTE: this URL is dropping the version at the end in the next release, all release notes are being combined into a single page going forward)*

Anyway, it's a small mess, but from my perspective the damage is done. I would not want to encourage anyone to use `row_header` ever at all since it was always a mistake, and in fact, it has [***already been removed***](https://github.com/bokeh/bokeh/pull/7721). You should **definitely not use it**. Use `index_header` as described in the release notes. If you want to make an edit to this file to note that it was accidentally removed (but makes no mention of `row_header`), I'd accept a PR:

https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/releases/0.12.15.rst

Otherwise, it will never be an issue for new users, and I don't think the property was used by many existing users, so the issue is documented enough in the tracker as far as I am concerned. 

---

As an aside we make semi-regular [dev builds](https://bokeh.pydata.org/en/latest/docs/installation.html#developer-builds) available. The best way to forestall problems like this is for more people to actively help out and try the dev builds prior to release.

**Comment by x9y9** [comment]
**@bryevdv** Since  row_header/s have been removed in 0.12.16 release, can you tell us how to disable the index column now?

**Comment by bryevdv** [comment]
Information like that is always in the release notes/migration guide: http://bokeh.pydata.org/en/latest/docs/releases.html#datatable

**Comment by x9y9** [comment]
**@bryevdv** thanks!
