### ISSUE TITLE
Adjust Glyphs To Match Area

### ISSUE THREAD

**Issue by cbusenbu** [bokeh/bokeh#7796]
One thing I have been dealing with recently is the perception of the sizing of glyphs.

Currently, I have been using circles, triangles, and squares. When these are stacked on top of one another, there is clear differences in 'size', even though their size parameter could be the exact same. This is currently an expected behavior, due to how the glyphs are shown. 

![image](https://user-images.githubusercontent.com/10522477/38815236-7a9c41fc-4161-11e8-90a7-584891299285.png)

In the figure above the glyphs look much smaller. This is why I would suggest either a defaulted parameter where someone can make their areas equal to the equivalent width square, or just make it the default.

As an example, I calculated the coefficient needed to make a circle equivalent to the square.
```python
size_of_square = 20
area_equivalent_size_of_circle = 1.12838 * size_of_square
area_equivalent_size_of_triangle = 1.51967 * size_of_square
```
With these calculations, I think you will find that the glyphs look much closer in size when using them in reference to each other.

![image](https://user-images.githubusercontent.com/10522477/38815628-5f3323b2-4162-11e8-9cee-baa3e00ae58b.png)

Just wanted to get some thoughts.

**Comment by bryevdv** [comment]
@cbusenbu I agree that some of the markers look a but smaller than might be ideally preferred. However the value in `size` is that is has a consistent an unambiguous meaning for markers, the overall diameter in pixels. The issue with having `size` (or something else) mean "sort of area" is that what does the mean for markers like cross that don't really have an area at all, etc? It would be more nebulous and harder to explain and document. Given that users have ultimate control and can adjust things to suit their needs my inclination is simply to leave things generally as they are. 

What *might* be reasonable, if someone wants to undertake the work, is to figure out a set of "nice" scalings for all glyphs, and just to make them available in some straightforward fashion so that if people want to apply this kind of scaling, they have an easy path to do so. Are you interested in pursuing this? If not that's fine, but then we will probably close this issue for now (if someone wants to do it at a later date we can always re-open)

**Comment by cbusenbu** [comment]
@bryevdv I will take a look at it, I am not super familiar with the underlying development, but I will look at contributor documentation, and the like to see if I can help.

**Comment by bryevdv** [comment]
In this case I think the main task is just to mage the list of scsle factors. Once that is done we can just put them anywhere convenient with a little documentation about what they are useful for

**Comment by bryevdv** [comment]
@cbusenbu just checking, will you be able to compile the list of of factors? If not I'd like to close this out.

**Comment by cbusenbu** [comment]
Yeah, I have had a rough week, planning on it this weekend.

**Comment by bryevdv** [comment]
OK, will leave this open!

**Comment by cbusenbu** [comment]
After looking at this, over the weekend. Other than the glyphs I have posted about, it doesn't seem like this really works well with the others glyphs, it's just a bunch of trying and testing. there isn't a good concrete way to say a cross, matches a square.. things like that. It all comes down to what the user desires. So I am going to close this one down, and if anyone wants to know what I ended up using for the more primary shapes, they are here to see.
