### ISSUE TITLE
Improve documentation for creating interactive plots in Notebook 

### ISSUE THREAD

**Issue by orodbhen** [bokeh/bokeh#7831]
I'm trying to figure out how to create a fully interactive plots in Jupyter Notebook, with widgets, etc. I've spent several days going through the Bokeh documentation, trying to wrap my head around the paradigm. There seems to be three  ways of doing this:

- JS callbacks
- Bokeh server
- Embed Bokeh application in Notebook

I'm wondering why there's not a more straight-forward way of doing this, though. The plots created with `output_notebook` are interactive, so that means there's already an event loop there. Why can't that be used for widget callbacks written in Python?

No so much a feature request as trying to fill in what appear to be gaps in the documentation. Maybe the gaps are for historical reasons, e.g. Bokeh evolved with Notebook support as an afterthought. I'm willing to help improve the Bokeh documentation for Notebook, if I can get clearer idea of how this all works, and why you can't simply add widgets and callbacks in Notebook. 

There doesn't seem to be a fully featured Python plotting library that integrates well with Notebook, but Bokeh is the best candidate I've found. But, at present, it takes quite a bit of time in the documentation just to get started.

**Comment by bryevdv** [comment]
[Just a heads up that this will be closed very soon unless specific actions are determined]

First, it would be helpful to know, did you come across the (live) tutorial notebooks? They are at:

https://mybinder.org/v2/gh/bokeh/bokeh-notebooks/master?filepath=tutorial%2F00%20-%20Introduction%20and%20Setup.ipynb

I personally think 15 notebooks full of examples is a pretty good start, so it would be good to know if you disagree about their value, or whether they simply were not easy enough to find.

Regarding:

> There seems to be three ways of doing this:
> 
> JS callbacks
> Bokeh server
> Embed Bokeh application in Notebook

This not quite right. The last two are really the same. The Bokeh server is what runs Bokeh applications, which are things that automatically connect JS events in the browser to live python code. Embedding in the notebook just means that it runs on the notebook IOLoop instead of a separate process. 

> The plots created with output_notebook are interactive, so that means there's already an event loop there. Why can't that be used for widget callbacks written in Python?

Bokeh is a large Python library with a huge separate JS runtime component. The classic notebook is a large python program with a huge separate JS runtime component. The new JupyterLab is yet another of the same, with a new plugin architecture that wholly incompatibly with classic notebook. Getting all these to work together is frankly, a technical nightmare. It has taken many person-months of frustration, false-starts, and refactors just to get what is available now. But there is another reason that python callbacks have to be defined in the context of an embedded server app -- the possibility of out-of-order-execution of notebook cells means that is just becomes completely unreasonable quickly, in the literal sense that it is not possible to effectively reason about program state. That is true both for users, and perhaps even more so for trying to make it work as developers. I would personally go so far as to say that the possibility of out-of-order-execution of notebook cells is the notebooks very worst mis-feature. If you really need this then people have resorted to `CustomJS` callbacks that invoke `kernel.execute`. Personally I think down that path lies madness, but for specific and narrow usage where you can apply assumptions about your special case, maybe it's useful.

> I'm willing to help improve the Bokeh documentation for Notebook,

This would definitely be welcome and appreciated. One of the challenges is that neither of the main core devs are heavy or regular notebook users. So having actual users of the notebook improve notebook documentation would be very valuable.

**Comment by bryevdv** [comment]
@orodbhen just checking in, are you able to continue this discussion?

**Comment by orodbhen** [comment]
Thanks for the explanation. I can see that the architecture of Notebook makes it more complicated. I realize I probably should have been more specific about what documentation improvements I'm asking for. 

I had not seen the Notebook examples you referenced. I only went through [Working in the Notebook](https://bokeh.pydata.org/en/latest/docs/user_guide/notebook.html), and some other blog examples I found through web searches. So, I think what would be very helpful is if the former reference was more complete, i.e. have more detail and/or links about the different ways you can use Bokeh in a Notebook. 

The Bokeh paradigm is not very intuitive when you're, like probably most people, coming from a background of Matlab and/or Pyplot. That's not to say it's not very powerful and useful. Now that I'm a little more familiar with it, I think it's less nebulous than MPL for creating complex visualizations. But initially, I was pretty lost. 

The first documentation I read talked about the server and everything. having mostly worked in an interactive Python shell environment, it didn't occur to me that Bokeh was designed for something else, so I followed the instructions for creating a server, but in a Notebook, and it didn't work. In short, it's taken me quite a bit of reading and experimentation to really get a handle on Bokeh (no pun intended). 

I've done a lot of experimenting with other Python plotting tools, in a search for a better "go to" toolkit than MPL, e.g. VisPy, Chaco, Mayavi, Plotly, etc. Unless your a Python Viz insider, it's all pretty confusing. I think that's why most people still fall back to MPL, even though it may not be the best tool for the task. 

My search began out of frustration from trying to plot signals captured at very high sample rates. MPL was painfully slow. More recently I've begun doing research in data science. So the fact that Bokeh integrates well with Datashader is a big plus. VisPy is awesome, but hard to use still pretty coarse. 

So yes, I'd like to help improve the docs, particularly the "Working in the Notebook" page. Unless you think there's a better main reference. For my own work, I don't have be strictly bound to the Notebook, but I'd prefer to stay in it as much as possible without running external programs. In particular, I'd like to create interactive plots with widgets, callbacks, etc., and think more information about that should be added to the Notebook documentation.

**Comment by jbednar** [comment]
On Tue, Apr 24, 2018 at 8:36 PM, orodbhen <notifications@github.com> wrote:

> I'm trying to figure out how to create a fully interactive plots in
> Jupyter Notebook, with widgets, etc.
>
There doesn't seem to be a fully featured Python plotting library that
> integrates well with Notebook, but Bokeh is the best candidate I've found.
> But, at present, it takes quite a bit of time in the documentation just to
> get started.
>
So the fact that Bokeh integrates well with Datashader is a big plus.


As an author of HoloViews, I'm surely biased, but I think the combination
of Bokeh+HoloViews is very much a fully featured Python plotting library
that integrates well with the notebook.  HoloViews was designed from the
start with the notebook in mind, and when we later added Bokeh integration,
working with Bokeh in the notebook became much more straightforward.

HoloViews also makes working with Datashader much simpler, as Datashader
itself does not actually integrate well with Bokeh.  Only when HoloViews
coordinates dynamically regenerating Datashader plots as needed does it
become easy to use Datashader in a Bokeh plot.

As for documentation, check out pyviz.org, which has a series of tutorials
showing how to use HoloViews, Bokeh, and Datashader together in or out of
notebooks (mostly in), including using custom Bokeh widget. (Without the
packages described at pyviz.org, Bokeh widgets only work in Bokeh Server,
not in notebooks.) The whole workflow (datashaded plots with custom widgets
in or out of notebooks) is encapsulated in one notebook here
<https://github.com/pyviz/pyviz/blob/master/notebooks/A2_Dashboard_Workflow.ipynb>,
and the rest of pyviz.org goes through it all step by step.

Jim

**Comment by bryevdv** [comment]
@orodbhen It would definitely be good to expand the "Working  in the Notebook" section, I've actually had it in mind for a while. Some things like

* https://github.com/bokeh/bokeh/issues/7835
* direct links to the tutorial notbeooks
* more screenshots and example code

In general it's just been hard to find the time, and of course, I do think a more avid notebook user would also do a better job than I. The sphinx source for that page is locate here:

https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/user_guide/notebook.rst

Building the docs can be very slightly tricky, so let me know if you run into any issues getting started. 

---

I should also say that checking out HoloViews is also a fine suggestion, tho I do want to correct this statement:

> Without the packages described at pyviz.org, Bokeh widgets only work in Bokeh Server, not in notebooks.

Bokeh widgets work fine in the notebook with:

* CustomJS callbacks
* python callbacks with embedded Bokeh server apps

**Comment by orodbhen** [comment]
Ok, thanks for all the references. There's definitely a lot of good information if you know where to find it. It's going to take me little while to get through all the docs and examples. Should I reference this issue when committing changes?

**Comment by bryevdv** [comment]
Yes that wish be great, I'd suggest making a minimal PR as soon as you are up and running then we can collaborate on specific questions there!

**Comment by okomarov** [comment]
@bryevdv I just recently created a time-series plot with a range slider in a notebook and probably faced many of the issues that @orodbhen found. 

I posted on https://github.com/bokeh/bokeh/issues/7822 full snippets of code, which can be re-used to showcase what I believe belongs to @bryevdv's second bullet point (python callbacks with embedded Bokeh server apps). I could not find such examples in the docs and had to work from this full GUI http://rubydatasystems.com/user_guide.html#editor-tool. Before seeing this GUI, I had no idea Bokeh could create such a complete interface in a notebook.

**Comment by aavanian** [comment]
There are a few answers on SO that give examples of bokeh server within notebook. Here's [one I made sometime ago](https://stackoverflow.com/questions/46644197/histogram-with-slider-filter/46647774#46647774). Unfortunately I guess they tend to pop-up on specific use cases search rather than looking for notebook/server answers.

**Comment by orodbhen** [comment]
@okomarov I only became aware of it after reading this blog [post](http://biobits.org/bokeh-jupyter-embed.html). The author points out that this feature is only available as of release `0.12.5`. I think this information should be added to the docs, after confirming that it's correct. 

Posts on SO and blogs are great, but I wish more people would contribute to the actual docs.

**Comment by bryevdv** [comment]
@orodbhen  That info is correct, although there are even simpler ways to accomplish what's in that post, now. Offhand I would suggest these as potential new sections for the Notebooks User's guide  chapter:

```
Interactivity in the Notebook
-----------------------------

Working with JavaScript Callbacks
~~~~~~~~~~~~~~~~~~~~~~~~~

How JS callbacks can add interactive features that work even in staticly rendered notebooks

Using ``push_notebook`` with Jupyter Interactors
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Show how one-way updates (Python -> JS) can be used together with native Jupyter widgets (requires running jupyter kernel)

Embedding Bokeh Server Applications
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Show how Bokeh server apps can be embedded by passing a "modify doc" function to `show` (requires a running jupyter kernel)

```

For all of these we could add support notebooks in the `bokeh-notebooks` repo, then we could  link to liver versions running on beaker that users could immediately play with.

**Comment by bryevdv** [comment]
Quite a bit of new content was added in #7859 I'm going to go ahead and close this issue and ask that further work get new issues. (It confuses tracker history when multiple PRs cover the same issue)
