### ISSUE TITLE
Upgrade from 0.12.13 to 0.12.15 has broken my plot

### ISSUE THREAD

**Issue by hsmfedor** [bokeh/bokeh#7834]
Code below was working for version 0.12.13, but not working now when I upgraded to version 0.12.15.
Now, on tap event Bokeh shows empty plot.

```
tapCallback = CustomJS(args=dict(source_cn=source_cn,
                                 source_ap=source_ap,
                                 x_range = p.x_range,
                                 y_range = p.y_range,
                                 x_range_cn = p_cn.x_range,
                                 y_range_cn = p_cn.y_range), 
code="""
...
source_cn.data.xname  = nxname;
source_cn.data.yname  = nyname;
source_cn.data.colors = ncolors;
source_cn.data.alphas = nalphas;
source_cn.data.means  = nmeans;
source_cn.data.stds   = nstds;

x_range.factors = xrange_factors;
y_range.factors = yrange_factors;
source_cn.change.emit();
""")

p.select_one(HoverTool).tooltips = [('OD:', '@yname-@xname'),('mean', '@means'),('std', '@stds'),]
p.select_one(TapTool).behavior = 'inspect'
p.select_one(TapTool).callback = tapCallback
```

**Comment by hsmfedor** [comment]
It doesn't work in 0.12.14 either.

**Comment by mattpap** [comment]
Please submit runnable code. Also, are there any errors in JS console?

**Comment by bryevdv** [comment]
I think this discussion is more appropriate to start on mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

If it's determined there is a bug or regression, this issue can be re-opened with full details. However it's possible there was an intentional change, or that you were relying on undocumented behaviour. As mentioned, a ***complete*** runnable example is necessary to try and help.
