### ISSUE TITLE
Better handling of timedelta

### ISSUE THREAD

**Issue by hyamanieu** [bokeh/bokeh#7867]
A minor issue: Timedelta aren't correctly handled and formatted. 

Using `DatetimeTickFormatter` with e.g.` '%jd %H:%M:%S'` to count the number of days/hours/minutes  gives out `1d 00:00:00` (_1 day_) for `t=0` when it should really be `0d 00:00:00`. It considers a datetime, hence January 1st of epoch, instead of a time range.

Using `NumeralTickFormatter(format='00:00:00')` doesn't work either as they're automaticaly turned in float of ms in a data source, while this formatter uses seconds.

Using `FuncTickFormatter` imposes installing flexx which breaks my conda environment (and is also not friendly).

**Potential solution:**
https://bokeh.pydata.org/en/latest/_modules/bokeh/util/serialization.html could be modified to set timedelta as seconds and document for the use of `NumeralTickFormatter` in this specific case.

**Workaround**: turn timedelta dataframe columns to float with `total_seconds()` before adding to the source then use `NumeralTickFormatter`.

It seems that this issue is related to https://github.com/bokeh/bokeh/issues/5426

**Comment by bryevdv** [comment]
> Using DatetimeTickFormatter

is not appropiate, because time delta values are not date time values

> Using FuncTickFormatter imposes installing flexx

This is not accurate. `FuncTickFormatter` is ultimately a means of specifying JavaScript code to perform tick formatting. The `from_py_func` merely a convenience for those that do want to use it, and is entirely optional in any case.  If you don't want to install flexx that's perfectly fine, one line of JS should do the trick:
```
p.yaxis.formatter = FuncTickFormatter(code="""return (tick/1000).toFixed(2)""")
```

It seems to me the units of serialization for time deltas are entirely arbitrary, and no choice of default will satisfy everyone. Since there are ways to accomplish any particular desired outcome, I'm inclined to not take any action here. 

@mattpap do you have any other thoughts?

**Comment by bryevdv** [comment]
Actually this answer on SO demonstrates a compelling reason why serializing as ms is definitely useful (so that timedelta values are immediately compatible as widths, etc for use with datetime axes):

https://stackoverflow.com/a/50238241/3406693

Given that, I will close this.

**Comment by miccoli** [comment]
In my opinion timedelta support should be improved in bokeh.

Let me express this with an example. Given

```
dt = np.arange('2018-03-14', '2020-06-28', dtype='datetime64[h]')
td = dt - dt[len(dt)//2]
y = np.sin(td/np.timedelta64(24*40, 'h'))
```

Here `dt` (date time) is
```
array(['2018-03-14T00', '2018-03-14T01', '2018-03-14T02', ...,
       '2020-06-27T21', '2020-06-27T22', '2020-06-27T23'],
      dtype='datetime64[h]')
```
while `td` (time delta)
```
array([-10044, -10043, -10042, ...,  10041,  10042,  10043],
      dtype='timedelta64[h]')
```

The plot `p.line(x=dt, y=y)` is 
![image](https://user-images.githubusercontent.com/6403904/41821574-453212fe-77e3-11e8-93fb-b707a19ebab5.png)
while `p.line(x=td, y=y)` is
![image](https://user-images.githubusercontent.com/6403904/41821597-8db353ee-77e3-11e8-8af9-4beef7294143.png)
which makes no sense at all.  In this latter case tick labels should something like `['-360d', '-180d', '0d', '180d', '360d']`

These labels would be consistent with numpy timedelta64 semantics:
```
>>> td / np.timedelta64(1, 'D')
array([-418.5       , -418.45833333, -418.41666667, ...,  418.375     ,
        418.41666667,  418.45833333])
>>> td / np.timedelta64(1, 'M')
TypeError: Cannot get a common metadata divisor for NumPy datetime metadata [h] and [M] because they have incompatible nonlinear base time units
```
clearly showing that timedelta64 should not be converted to month/year representation.

I would suggest to reopen this issue, which is related to #5426 and ioam/holoviews#2807

**Comment by bryevdv** [comment]
> clearly showing that timedelta64 should not be converted to month/year representation.

They are *not* converted to month/year representation. They are converted to absolute milliseconds (which is fine, the unit choice is arbitrary and ms has some advantages, see above). They are are being *displayed* as dates because *you* have configured a datetime axis, which interprets values a "ms since epoch". As stated above, it's not sensical to use a datetime axis with timedeltas, because timedeltas are not datetimes. The answer, however, is just: don't use a datetime axis with timedeltas.

Given that any formatting anyone wants can now be achieved with `FuncTickFormatter`, it's not a high priority to build in (and therefore have to maintain) more code about this.

**Comment by miccoli** [comment]
Sorry, I now see my misunderstanding of the `x_axis_type='datetime'` machinery.  Thank you for the time you spent replying to my ill posed comments.

What was confusing for me (I report it here in the hope that this could help others avoiding this pitfall) is that for small time intervals the plots you get are completely reasonable. E.g.:

```
dt = np.arange('2018-03-14T14:30:27.878', '2018-03-14T14:30:27.898', dtype='datetime64[us]')
td = dt - dt[len(dt)//2]
y = np.sin(4*np.pi*td / td.ptp())
p = figure(x_axis_type='datetime', plot_width=400, plot_height=100, tools = "save")
p.line(x=dt, y=y)
show(p)

p = figure(x_axis_type='datetime', plot_width=400, plot_height=100, tools = "save")
p.line(x=td, y=y)
show(p)
```

**Comment by bryevdv** [comment]
Yes, that's a pure coincidence, I am not sure offhand what we can do but I'm certainly open to suggestions if there is something we can document or demonstrate better

**Comment by miccoli** [comment]
As what regards documentation, <https://bokeh.pydata.org/en/0.13.0/docs/user_guide/plotting.html#datetime-axes> contains the following statement (emphasis added by me)

> When dealing with timeseries data, or *any data that involves dates or times*, it is desirable to have an axis that can display labels that are appropriate to different date and time scales.

Even if the numpy semantics of 'datetime64' and 'timedelta64' were clear to me, it was not obvious that 'any data that involves dates or times' excludes 'timedelta64'. (And yes, I did not read the reference guide.)

However I agree that support of timedelta axes is not high priority, and may be it is better for the user to do scaling and formatting explicitly.
