### ISSUE TITLE
re-jitter on tap is unexpected

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#7915]
This may be intended behavior. But if so, it would be good to provide documentation of a workaround because it surprised me, and I would think others too

This only a slightly tweaked version of the categorical jitter example in gallery, that adds a tap tool.

You can also see it here: http://nbviewer.jupyter.org/github/birdsarah/bokeh-miscellany/blob/master/jitter%20on%20tap.ipynb

```python
from bokeh.io import show, output_notebook
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure
from bokeh.sampledata.commits import data
from bokeh.transform import jitter

output_notebook()

DAYS = ['Sun', 'Sat', 'Fri', 'Thu', 'Wed', 'Tue', 'Mon']

source = ColumnDataSource(data)

p = figure(plot_width=800, plot_height=300, y_range=DAYS, x_axis_type='datetime', tools='tap, save',
           title="Commits by Time of Day (US/Central) 2012-2016")

p.circle(x='time', y=jitter('day', width=0.6, range=p.y_range),  source=source, alpha=0.3, 
         selection_color='magenta', selection_alpha=1, size=8)

p.xaxis[0].formatter.days = ['%Hh']
p.x_range.range_padding = 0
p.ygrid.grid_line_color = None

show(p)
```

On tap, I expect the point under my mouse to highlight.

What happens is that a repaint occurs causing a fresh jitter so the higlighted point has moved. This is particularly clear if you tap on two points that were on top of each other but have now moved

![bokeh_plot_two](https://user-images.githubusercontent.com/1796208/40153907-83266066-5951-11e8-83d4-2690a18554eb.png)

**Comment by bryevdv** [comment]
It's definitely expected, given the way things are written. Whether it's desirable is another question. Right now any cal to `set_data` will result in a column transform being re-executed. There's a few possible different things that could be tried:

* generally see if `set_data` could be triggered less often
* specifically for `Jitter`, cache computed jitter offsets and re-apply them as long a the size of the column does not change 

I'm open to either (or to doing nothing) but I won't have too much time to look at it myself anytime soon.

**Comment by birdsarah** [comment]
> It's definitely expected, given the way things are written. Whether it's desirable is another question.

yes. that's what i should have said, apologies.

Random thoughts:

> specifically for Jitter, cache computed jitter offsets and re-apply them as long a the size of the column does not change

- i think it should be user configurable, a flag of some kind. 
- we'd need to think through whether this was for all transforms or just jitter. 
- it's not just the length of the column, if data was patched what should happen?


> in general, see if `set_data` could be triggered less often

- Perhaps some abstraction / indirection and nuance on different kinds of data setting - a selection is more of a view on the data than defining new data....

**Comment by bryevdv** [comment]
> *  i think it should be user configurable, a flag of some kind.

Seems reasonable, also occurred to me

> * we'd need to think through whether this was for all transforms or just jitter.
> * it's not just the length of the column, if data was patched what should happen?

Well, I am proposing "just jitter" and "only column length" together specifically because computing a random offset does not actually depend on the inputs. As soon as you admit transforms that do actually depend on the inputs, I agree that column length alone is not sufficient. I am trying to keep things simple, though. 

*  a selection is more of a view on the data than defining new data....

Offhand I definitely think that a mere selection should not trigger `set_data`. I'm not sure if what would be needed is a new finer-grained signal to trigger, or if there is an existing different one that would work. I've been meaning to map out and document all of our signals because they are kind of a rats nest at the moment. 

I guess I'd propose both: doing "just jitter / only column length" caching as an immediate and reasonable improvement for jitter specifically, and then trying to make selections trigger less work as a slightly more involved task.

**Comment by birdsarah** [comment]
> all of our signals because they are kind of a rats nest at the moment.

there's no need to talk smack about rats' nests :smile:

**Comment by bryevdv** [comment]
Since I think it's the most common and cost effective, for now just got to get the cache on length for jitter done.
