### ISSUE TITLE
Templates Not Included When Compiling With Py2exe

### ISSUE THREAD

**Issue by bhicks92** [bokeh/bokeh#799]
I am attempting to use py2exe to build an executable from a python script that uses bokeh. The entire templates folder is not included in the compiled bokeh library, and the executable therefore cannot create plots.

Traceback (most recent call last):
  File "myscript.py", line 624, in myfunction
  File "bokeh\plotting.pyc", line 358, in show
  File "bokeh\session\html_file_session.pyc", line 194, in save
  File "bokeh\session\html_file_session.pyc", line 150, in dumps
  File "bokeh\session\base_html_session.pyc", line 67, in _load_template
IOError: [Errno 2] No such file or directory: 'C:\dist\library.zip\bokeh\session\..\templates\plots.js'

**Comment by bryevdv** [comment]
No response, `py2exe` seems like a fairly marginal use case, closing. OP please re-open if you have more information to provide regarding the new information above.

**Comment by FabeG** [comment]
I succeeded in building an executable with ``py2exe`` from a script using ``bokeh``.

My first try wasn't very promising (using the last ``bokeh`` version 0.12.3). It failed with:

Traceback (most recent call last):
  File "test_bokeh_simple.py", line 8, in <module>
  File "bokeh\io.pyc", line 29, in <module>
  File "bokeh\core\state.pyc", line 44, in <module>
  File "bokeh\document.pyc", line 34, in <module>
  File "bokeh\core\templates.pyc", line 22, in <module>
  File "jinja2\environment.pyc", line 812, in get_template
  File "jinja2\environment.pyc", line 774, in _load_template
  File "jinja2\loaders.pyc", line 235, in get_source
jinja2.exceptions.TemplateNotFound: js_resources.html

It seems that all the template files contained in the `bokeh/core/_templates` should be included in the package created by ``py2exe``.
Using the ``data_files`` option of ``py2exe``  doesn't solve the problem, because these template files have to be in the `bokeh/core/_templates` directory.
Since the ``bokeh`` module is included in the ``library.zip`` file created by ``py2exe``, the idea was to add the ``_templates`` directory into this zip file. 

Here is the minimal ``setup.py`` file that worked for me (`test_simple_bokeh.py` being the file to convert into an executable):

```python
import zipfile
import os
import sys
from setuptools import setup

import bokeh.core
import py2exe
from matplotlib import get_py2exe_datafiles

current_dir = os.path.dirname(os.path.realpath(__file__))
dist_dir = os.path.join(current_dir, "dist")
setup(
    data_files=get_py2exe_datafiles(),
    windows=[{"script": "test_bokeh_simple.py", "dest_base": "test_bokeh" }],
    options={
        'py2exe':
        {
            'includes': [ 'tornado', 'bokeh.core', 'email', 'email.parser', 'markupsafe', 'jinja2', ],
            'packages': [ 'pkg_resources' ],
            'compressed': True,
            'dist_dir': dist_dir,
        }
    },
)

# Add boke/core/_templates files to the library.zip file
bokeh_path = sys.modules['bokeh.core'].__path__[0]
zipfile_path = os.path.join(dist_dir, "library.zip")
z = zipfile.ZipFile(zipfile_path, 'a')
for dirpath,dirs,files in os.walk(os.path.join(bokeh_path, '_templates')):
  for f in files:
      fn = os.path.join(dirpath, f)
      z.write(fn, os.path.join(dirpath[dirpath.index('bokeh'):], f))
z.close()
```

**Comment by crashMOGWAI** [comment]
More evidence that Jinja2 is the culprit. [Here is the pyinstaller thread.](https://github.com/pyinstaller/pyinstaller/issues/1898)

**Comment by DominicAntonacci** [comment]
It seems like py2exe hasn't been maintained recently, but PyInstaller is another common exe compilation library.

There are a couple of things that need to be done for Bokeh to play nicely with those. First, in `core/templates.py` needs to be modified to avoid the Jinja2 error. Second, a lot of the non-Python Bokeh files are missed when the exe is created. A basic workaround is to copy them manually, but there is almost certainly a better way to do it.

I'm planning on working on this unless anyone else wants to take it on. However, I can't spend too much time on it until mid-May or so.

**Comment by bryevdv** [comment]
Sounds good (and thanks!), I have re-triaged.

**Comment by bryevdv** [comment]
@DominicAntonacci checking in do you still expect to be able to work on this soon?

**Comment by DominicAntonacci** [comment]
Yes, I do plan on working on it soon. Hopefully get started sometime next weekend. Not sure how long it will take, so I don't want to put an ETA down yet.

**Comment by bryevdv** [comment]
@DominicAntonacci checking in again, there will be a release next week but we would need a PR by EOD Saturday to consider it for this cycle.

**Comment by DominicAntonacci** [comment]
It hasn't slipped my mind, but I haven't done much with it yet. When's the next release cycle? I'll try to get it done before then.

**Comment by bryevdv** [comment]
> When's the next release cycle? 

The next release is tomorrow (or possibly Thursday) so it will most likely have to be the following cycle.

**Comment by bryevdv** [comment]
@DominicAntonacci Another user submitted a #8008 in the mean time. It should solve the prpblems but please report back if there are any issues.
