### ISSUE TITLE
Bokeh without opening ports on firewall

### ISSUE THREAD

**Issue by chiragshah1312** [bokeh/bokeh#8039]
I'm starting a bokeh server on a machine using python.
`sockets, port = bind_sockets("localhost", 0)
`
This is embeded in flask app so I'm using
`bokeh_tornado = BokehTornado({'/bkapp': bkapp}, extra_websocket_origins=["localhost:8000", "*"])`
i use 
gunicorn -w 4 main:app
to start the flask app.

When i hit the ip:port of the gunicorn from broswer, 
the gunicorn gets the request and it loads the title on browser.
But, the autoload.js request fails
since the code is requesting it from 
http://ip:port/bkapp/autoload.js

Since I'm using **0 in bind_sockets**, the OS will automatically pickup a port.
But this port is not open on my firewall and i **DONT** want to OPEN a new port on firewall.
I need a solution so that the autoload.js request get successful without opening a new port. i dont mind using Nginx

**Comment by bryevdv** [comment]
There was a previous discussion around making it possible to use unix sockets instead: https://github.com/bokeh/bokeh/issues/5383 but that did not go anywhere at the time. We could certainly revisit things, especially if someone new is interested in leading the effort. Otherwise, support questions e.g. about nginx or other configuration, shoudl go on the mailing list, not the issue tracker:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
