### ISSUE TITLE
Not providing x and y data makes some glyphs not render in legend

### ISSUE THREAD

**Issue by tobiasfriden** [bokeh/bokeh#8077]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh version: 0.12.6
Python version: 2.7.13
Browser: firefox
#### Description of expected behavior and the observed behavior
When creating a custom legend and not providing x and y data some glyphs (x, cross) do not render in the legend while some (circle, line) do.
#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.models import Legend
from bokeh.plotting import figure, curdoc

plot = figure(width=300, height=300)

legend_items = []

# Renders in legend
legend_items.append(('circle', [plot.circle(x=[], y=[])]))
legend_items.append(('line', [plot.line(x=[], y=[])]))
legend_items.append(('x', [plot.x(x=[1], y=[1])]))

# Doesn't render in legend
legend_items.append(('x', [plot.x(x=[], y=[])]))
legend_items.append(('cross', [plot.cross(x=[], y=[])]))

legend = Legend(items=legend_items, location='top_left')
plot.add_layout(legend, 'center')

curdoc().add_root(plot)

```

#### Screenshots or screencasts of the bug in action
![bild](https://user-images.githubusercontent.com/24483099/42630216-4533415a-85d6-11e8-80a9-98cd0bd21052.png)

**Comment by bryevdv** [comment]
This happens because the legend rendering method tries to extract the corresponding angle for the representative point, but when there is no data this value is undefined. There are two options:

* don't match the angle ever, just always set it to zero
* try to match (when there is data), otherwise set to zero

I don't have a strong opinion. It's also possible this same sort of issue affects other glyphs, but given the unusual-ness of the situation, I am inclined to only fix the marker case, and not try and perform any exhaustive survey to find out.

**Comment by bryevdv** [comment]
@tobiasfriden @mattpap anyone have a preference on which solution?

**Comment by bryevdv** [comment]
This is what option 2 looks like:

<img width="328" alt="screen shot 2018-07-12 at 16 20 00" src="https://user-images.githubusercontent.com/1078448/42659984-788938ca-85ef-11e8-915f-1dd98c1983bd.png">


Option 1 would just display unrotated X for both.

**Comment by mattpap** [comment]
I would choose the simplest approach. After all, angle can vary between indices, so this may not depict the a glyph accurately.
