### ISSUE TITLE
major_label_overrides dict does not work with numpy scalar keys

### ISSUE THREAD

**Issue by djbarker** [bokeh/bokeh#8166]
This issue is very strange but using a programmatically generated dictionary with `xaxis.major_label_overrides` fails, whereas using it with a hard-coded dictionary works fine. Even stranger, setting first the hard-coded, and then the programmatically generated also works. Here is an example

**Example:**

```python
print(sys.version)
print(bokeh.__version__)
x = np.array([1, 2, 3])
y = np.array([5, 3, 8])
a = list("ABC")
d = dict(zip(x, a))
plot = figure(width=300, height=300)
plot.vbar(x=x, top=y, width=1, bottom=0, color=["red", "green", "blue"])
plot.xaxis.ticker = x
assert d == {1: "A", 2: "B", 3: "C"}  # this assert passes
# plot.xaxis.major_label_overrides = {1: "A", 2: "B", 3: "C"} # this works
plot.xaxis.major_label_overrides = d # this doesn't 
show(plot)
```
**Stdout:**

3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0]
0.13.0

**Stacktrace:**

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-52-6f355b807b3e> in <module>()
     13 # this doesn't
     14 plot.xaxis.major_label_overrides = d
---> 15 show(plot)

~/anaconda3/lib/python3.6/site-packages/bokeh/io/showing.py in show(obj, browser, new, notebook_handle, notebook_url)
    135     if obj not in state.document.roots:
    136         state.document.add_root(obj)
--> 137     return _show_with_state(obj, state, browser, new, notebook_handle=notebook_handle)
    138 
    139 #-----------------------------------------------------------------------------

~/anaconda3/lib/python3.6/site-packages/bokeh/io/showing.py in _show_with_state(obj, state, browser, new, notebook_handle)
    169 
    170     if state.notebook:
--> 171         comms_handle = run_notebook_hook(state.notebook_type, 'doc', obj, state, notebook_handle)
    172         shown = True
    173 

~/anaconda3/lib/python3.6/site-packages/bokeh/io/notebook.py in run_notebook_hook(notebook_type, action, *args, **kw)
    286     if _HOOKS[notebook_type][action] is None:
    287         raise RuntimeError("notebook hook for %r did not install %r action" % notebook_type, action)
--> 288     return _HOOKS[notebook_type][action](*args, **kw)
    289 
    290 #-----------------------------------------------------------------------------

~/anaconda3/lib/python3.6/site-packages/bokeh/io/notebook.py in show_doc(obj, state, notebook_handle)
    491     from ..embed.notebook import notebook_content
    492     comms_target = make_id() if notebook_handle else None
--> 493     (script, div, cell_doc) = notebook_content(obj, comms_target)
    494 
    495     publish_display_data({HTML_MIME_TYPE: div})

~/anaconda3/lib/python3.6/site-packages/bokeh/embed/notebook.py in notebook_content(model, notebook_comms_target, theme)
     80     # has models with the same IDs as they were started with
     81     with _ModelInEmptyDocument(model, apply_theme=theme) as new_doc:
---> 82         (docs_json, [render_item]) = standalone_docs_json_and_render_items([model])
     83 
     84     div = div_for_render_item(render_item)

~/anaconda3/lib/python3.6/site-packages/bokeh/embed/util.py in standalone_docs_json_and_render_items(models)
    338     docs_json = {}
    339     for doc, (docid, _) in docs.items():
--> 340         docs_json[docid] = doc.to_json()
    341 
    342     render_items = []

~/anaconda3/lib/python3.6/site-packages/bokeh/document/document.py in to_json(self)
    779         # this is a total hack to go via a string, needed because
    780         # our BokehJSONEncoder goes straight to a string.
--> 781         doc_json = self.to_json_string()
    782         return loads(doc_json)
    783 

~/anaconda3/lib/python3.6/site-packages/bokeh/document/document.py in to_json_string(self, indent)
    808         }
    809 
--> 810         return serialize_json(json, indent=indent)
    811 
    812     def validate(self):

~/anaconda3/lib/python3.6/site-packages/bokeh/core/json_encoder.py in serialize_json(obj, pretty, indent, **kwargs)
    211         indent = 2
    212 
--> 213     return json.dumps(obj, cls=BokehJSONEncoder, allow_nan=False, indent=indent, separators=separators, sort_keys=True, **kwargs)

~/anaconda3/lib/python3.6/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    236         check_circular=check_circular, allow_nan=allow_nan, indent=indent,
    237         separators=separators, default=default, sort_keys=sort_keys,
--> 238         **kw).encode(obj)
    239 
    240 

~/anaconda3/lib/python3.6/json/encoder.py in encode(self, o)
    197         # exceptions aren't as detailed.  The list call should be roughly
    198         # equivalent to the PySequence_Fast that ''.join() would do.
--> 199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
    201             chunks = list(chunks)

~/anaconda3/lib/python3.6/json/encoder.py in iterencode(self, o, _one_shot)
    255                 self.key_separator, self.item_separator, self.sort_keys,
    256                 self.skipkeys, _one_shot)
--> 257         return _iterencode(o, 0)
    258 
    259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

TypeError: keys must be a string
```

**Comment by djbarker** [comment]
Ah right, this makes sense now thanks. Replacing the offending line with `dict(zip(map(int, x), a))` does the trick.

**Comment by djbarker** [comment]
I'm not sure it is such an obscure corner case. It's quite common to have data in numpy arrays and pandas dataframes, and from these it's natural to build the tick labels. I obviously have no view on how best to handle it internally to Bokeh.

**Comment by bryevdv** [comment]
I looked into this a bit further. The python standard library does this:
```
        if (_one_shot and c_make_encoder is not None
                and self.indent is None):
            _iterencode = c_make_encoder(
                markers, self.default, _encoder, self.indent,
                self.key_separator, self.item_separator, self.sort_keys,
                self.skipkeys, self.allow_nan)
        else:
            _iterencode = _make_iterencode(
                markers, self.default, _encoder, self.indent, floatstr,
                self.key_separator, self.item_separator, self.sort_keys,
                self.skipkeys, _one_shot)
        return _iterencode(o, 0)
```

The exception comes out of the C-optimized `_iterencode`. Putting a debug break here is not helpful since it's not possible to step into the C function. Putting a debug in our JSON encoder `default` function shows that it is never hit before the type error. This means the only *possible* thing we could do would be to not use the built in C JSON encoder, but rely on a Python one (which I guess is what was mentioned above).  However, that would destroy serialization performance, and adversely affect almost every current user, some of whom are already running into issues with performance. There's not any way to justify making a bad change for 99% of cases  just for to make this one case, which has a workaround documented here, better. I agree it's annoying, but sometimes there is simply no good path.

**Comment by bryevdv** [comment]
For grins I tried swapping out `json` for `simplejson` but that has essentially the same outcome:

> TypeError: keys must be str, int, float, bool or None, not numpy.int64

Regarding:

>  It's quite common to have data in numpy arrays and pandas dataframes, and from these it's natural to build the tick labels.

I agree a large percentage of users use these, however, overriding tick labels at all is a corner case to begin with. A large percentage of a corner case is still a corner case.

**Comment by mattpap** [comment]
I tripped over this issue my self when working on the layout. I got `DeserializationError('Int expected Integral, got 0')` (without any additional context, only failing with `pull_session()`). One obvious issue here is that `0` is an `Integral`, but the value is actually `"0"` string, just badly formatted due to usage of `%s` instead of `%r` in the error string. The origin of this error is a new layout property of type `Dict(Int, RowSizing)`. Given that bokeh's `Dict(K, V)` maps to JSON's `{[key: string]: V}`, there is no way to modify a non `Dict(String, V)` (so e.g. `Dict(Int, V)`) in bokehjs and get a result of correct type in bokeh.

I think that `Dict(K, V)` was always intended to work only with `K = String`, just it wasn't enforced, leading to errors and/or confusion like in here or in the original report. So, I think, this issue needs to be addressed in some way. My initial idea was to override serialization of dicts in `json` module, but given its implementation, that's not a feasible option. The simplest option would be to disallow non-string keys and make nonconforming cases (1 in master + 2 in layout PR) changed (`major_label_overrides` can use `.accepts()` for floats and in layout I can use different types). Alternatively we can implement proper dicts in bokehjs and map py dicts <-> js dicts. That's quite a lot of work and this idea was abandoned at least once before, and still would require custom serialization (usually done by using arrays). We could also hook into `Property.from_json()` (and possibly `to_json()`)  to do necessary conversions, though I'm not sure how much work or how viable this is.

**Comment by jfx319** [comment]
I'm copying over from gitter a related discussion with @bryevdv in case it helps with contributing towards getting to the bottom of this issue.

I also started with numpy when getting tripped up. But later, I removed numpy and observed the following: 

```python
major_ticks = [1.5, 2.0, 3.0]
p.xaxis.ticker = FixedTicker(ticks=major_ticks)
```

```python
major_label_overrides = {1.5: 'foo1', 2.0: 'foo2', 3.0: 'foo3'}
```
including the ".0" in the the latter two dict_keys prevents the override from happening, while removing the ".0" does activate the override
```python
{1.5: 'foo1', 2: 'foo2', 3: 'foo3'}
```
This is unexpected, since one might generate the dictionary keys using the original list of ticks values. 

The fact that the key=1.5 works, suggests a possible reason: the float values ending in .0's are likely being stripped of their decimals when [converted to string, here?](https://github.com/bokeh/bokeh/blob/13baccbb2835f7d5831c22b5cf68214e89c02618/bokehjs/src/lib/models/axes/axis.ts#L386) (My .ts knowledge is only from a cursory googling but that seems to be a difference compared to the [python side, here](https://github.com/bokeh/bokeh/blob/13baccbb2835f7d5831c22b5cf68214e89c02618/bokeh/models/axes.py#L102), where the key can be either float or str)

### workaround:
Convert any whole-number floats to integers when creating the dictionary keys (the tick values themselves need not be converted). I think my typical use case would be: I already know the major_ticks to specify and their corresponding labels --> the dictionary of overrides would be procedurally generated, so that would be the time to do this protection, rather than fixing the tick values themselves. 

```python
major_ticks = [1.5, 2.0, 3.0]
major_data_labels = ["foo1", "foo2", "foo3"]

#convert in place
for index, item in enumerate(major_ticks):
    if float(item).is_integer():
        major_ticks[index] = int(item)

major_label_overrides = dict(zip(major_ticks, major_data_labels))
```

**Comment by bryevdv** [comment]
> The simplest option would be to disallow non-string keys and make nonconforming cases (2 in master + 2 in layout PR) changed (major_label_overrides can use .accepts() for floats and in layout I can use different types). 

I think this is the only route I would support at this point. Here is a diff that gets the original code working:
```
diff --git a/bokeh/core/property/bases.py b/bokeh/core/property/bases.py
index 947e4a476..269531398 100644
--- a/bokeh/core/property/bases.py
+++ b/bokeh/core/property/bases.py
@@ -321,7 +321,11 @@ class Property(PropertyDescriptorFactory):
                 self.validate(value)
         except ValueError as e:
             for tp, converter in self.alternatives:
-                if tp.is_valid(value):
+                if callable(tp):
+                    valid = tp(value)
+                else:
+                    valid = tp.is_valid(value)
+                if valid:
                     value = converter(value)
                     break
             else:
@@ -369,7 +373,8 @@ class Property(PropertyDescriptorFactory):

         '''

-        tp = ParameterizedProperty._validate_type_param(tp)
+        if not callable(tp):
+            tp = ParameterizedProperty._validate_type_param(tp)
         self.alternatives.append((tp, converter))
         return self

@@ -414,7 +419,7 @@ class ParameterizedProperty(Property):
         elif isinstance(type_param, Property):
             return type_param

-        raise ValueError("expected a Propertyas type parameter, got %s" % type_param)
+        raise ValueError("expected a Property as type parameter, got %s" % type_param)

     @property
     def type_params(self):
diff --git a/bokeh/core/property/container.py b/bokeh/core/property/container.py
index 2b5e60980..db7b83630 100644
--- a/bokeh/core/property/container.py
+++ b/bokeh/core/property/container.py
@@ -189,6 +189,9 @@ class Dict(ContainerProperty):
                     all(self.keys_type.is_valid(key) and self.values_type.is_valid(val) for key, val in iteritems(value))):
                 msg = "" if not detail else "expected an element of %s, got %r" % (self, value)
                 raise ValueError(msg)
+            import numpy as np
+            if any(isinstance(key, np.number) for key, val in iteritems(value)):
+                raise ValueError("")

     @classmethod
     def wrap(cls, value):
diff --git a/bokeh/models/axes.py b/bokeh/models/axes.py
index 600344d9b..378335c99 100644
--- a/bokeh/models/axes.py
+++ b/bokeh/models/axes.py
@@ -13,6 +13,12 @@ from .formatters import BasicTickFormatter, CategoricalTickFormatter, DatetimeTi
 from .renderers import GuideRenderer
 from .tickers import Ticker, BasicTicker, LogTicker, CategoricalTicker, DatetimeTicker, FixedTicker, MercatorTicker

+def _array_has_np_scalar_keys(d):
+    import numpy as np
+    if any(isinstance(x, np.number) for x in d.keys()):
+        return True
+    return False
+
 @abstract
 class Axis(GuideRenderer):
     ''' A base class that defines common properties for all axis types.
@@ -102,7 +108,8 @@ class Axis(GuideRenderer):
     major_label_overrides = Dict(Either(Float, String), String, default={}, help="""
     Provide explicit tick label values for specific tick locations that
     override normal formatting.
-    """)
+    """).accepts(_array_has_np_scalar_keys,
+                 lambda d: {float(k): v for (k,v) in d.items()})

     major_label_props = Include(TextProps, help="""
     The %s of the major tick labels.
```

**Comment by bryevdv** [comment]
Ok, I am inclined to close this again. While the above diff did suppress the error, evidently it did not actually work to display the overrides. The reason is because the `accepts` always converts numpy scalar to floats (it has to convert them to *something*), but if the fixed ticks are provided as ints, then they do not get applied. I.e. completely independent of Numpy usage, this works:
```
plot.xaxis.major_label_overrides = {1: "A", 2: "B", 3: "C"} 
```
but this does not work:
```
plot.xaxis.major_label_overrides = {1.0: "A", 2.0: "B", 3.0: "C"} 
```
Which is presumably because the BokehJS axis code does:
```
if (ticks[i] in this.model.major_label_overrides)
        labels[i] = this.model.major_label_overrides[ticks[i]]
```

There's no way to know ahead of time whether the ticks chosen are or will be floats. So there is no way to know whether numpy scalars would need to be converted to ints or to floats. It's just a pick-one-and-hope situation. In fact, there is no reason the fixed ticks could not be *both*, in which case there is *no way* to pick a single converted type that will work for all the fixed ticks.  That makes this "solution: 
* fragile
* hard to explain
* involves nontrivial changes to low level code

The only way to make it work fully would be to change the axis JS code above to be some *N^2* loop with a further double loop inside that tries out different  pairwise type combinations against each other. There is no way this one use case justifies a mess like that.  Closing with `wontfix`
