### ISSUE TITLE
[Feature Request] Figure Numbers for bokeh plots

### ISSUE THREAD

**Issue by jreed1701** [bokeh/bokeh#8178]
Generally when using the sphinx extension directive:

.. bokeh-plot:: script.py
  **:source-position: none**

The only option is bolded. When inserting the plot along with other figures there is no way to number them in line with others or even hard code a figure number, unless you insert one into the title of the figure. Hard coding the figure number can be problematic if the number changes. 

Request feature to number the figure along with a figure number label similar to other sphinx extensions.

Example:
```
.. bokeh-plot:: script.py
   :source-position: none
   :name: my figure
   Text to go with figure number goes here
 ```

**Comment by bryevdv** [comment]
@jreed1701 are you interested in working on this? It's a pure python task so it should be more accessible to more people than, e.g. something involving BokehJS changes. It's unlikely I will be able to personally prioritize this any time soon.

**Comment by jreed1701** [comment]
I read through the python. In your opinion, would the modifications be limited to this file: 
https://github.com/bokeh/bokeh/blob/master/bokeh/sphinxext/bokeh_plot.py? Or, would I have to touch other sources? If you could show me the front door I may be able to do the rest.

**Comment by bryevdv** [comment]
@jreed1701 Yes that's absolutely the file, I would expect all the changes to be in that file, and in the corresponding HTML template file:

https://github.com/bokeh/bokeh/blob/master/bokeh/sphinxext/_templates/plot_page.rst

One thing I will note up front: we can't use the "content" area under the directive, since that is already used in case users want to inline plot code directly in the directive instead of loading and outside file. So any new things can only be "options". The options are defined here:

https://github.com/bokeh/bokeh/blob/master/bokeh/sphinxext/bokeh_plot.py#L220-L225

So you'd want to add to that and then handle the new options in the `run` method. Handling should basically only mean: set up or any additional arguments to the template based on the options. 

One thing I am not clear on: are you proposing auto-numbering? Or just a general facility for adding arbitrary annotation text to the figure? The latter would be somewhat easer. In fact it's not even clear to me how auto-numbering could work, in principle. What is the "order" in a hyperlinked document?  Other tools may be for more narrow use cases that provide assumptions about global order, but that's not really the case with the bokeh plot directive. I think explicitly specifying the numbers may be the only viable route. 

In any case the first thing to do (before diving into code) is define exactly the new options and their behaviors. Tentatively, I might proprose
```
.. bokeh-plot:: script.py
   :source-position: none
   :name: my figure
   :fignum: 2
   :figtext: text to come after "Figure 2"
```

You didn't mention the `:name:` option, but that's new, can you clarify what you intend it to do, exactly?

**Comment by bryevdv** [comment]
I guess  would say: it's not impossible to conceive of auto-numbering, but I'd rate that a much bigger task. It would involve being able to specify some option information about your intended global page "order", and then being able to reference that in one of the final render steps to replace the figure number based on that. I'd say it would be much better to start with something like the above, that would still leave room for something like this later if someone wants to try and tack auto-numbering:
```
.. bokeh-plot:: script.py
   :source-position: none
   :name: my figure
   :fignum: auto
   :figtext: text to come after "Figure N"
```

**Comment by jreed1701** [comment]
@bryevdv Thank you for pointing out the HTML template. 

To offer a response to your questions.  About auto-numbering, that would be nice however I came to the same conclusion you did about difficulty of implementation.  The issue would be simplified if you were dealing with a single page. One could simply count the number of directive calls made by incrementing a persistent variable somewhere. Outside of a single page I thought you might have to search each page in a toctree, perform a count, and store in a separate variables. I would have to study the software to find a solution.  To summarize, I agree. An incremental solution would be a good idea.  Static first. Dynamic second. 

To speak to the new options. My original post had :name: in it because I copied and pasted a ".. figure" directive as an example.  Your post refined my original thought with :fignum: and :figtext:.  So here's how I think the new options might look. :name: is removed. 

.. bokeh-plot:: script.py
   :source-position: none
   :fignum: (N or auto) 
   :figtext: text to come after "Figure N"

**Comment by bryevdv** [comment]
@jreed1701 OK great! I think we are on the same page, to summarize the work:

* update the template to accept the new (optional) `fignum` and `figtext` template variables
* update the options spec linked above to list the two `fignum` and `figtext` new options
* update the `run` function to use the new options (by passing to the template) if they are present.

The only minor question is what to do if a user provides a `figtext` without providing a `fignum`? I think perhaps that should be an error.

**Comment by jreed1701** [comment]
The user may not want text to be inserted. In which case the software might simply have "Figure N" shown underneath the plot.  The converse should definitely produce an error. That is, providing :figtext: without a :fignum:.

**Comment by bryevdv** [comment]
Yes I agree `fignum` by itself OK, just `figtext` by itself that does not make sense. There should be some examples of raising errors in various places in the `sphinxext` code you can refer to, but let me know if you need a reference to something specific.

**Comment by bryevdv** [comment]
@jreed1701 just checking in, are you still interested in working this up?

**Comment by bryevdv** [comment]
I don't personally consider this a priority and given the lack of response regarding making a contribution, I will close this now. We can always re-open if someone wants to work on it
