### ISSUE TITLE
Relativize module paths in generated js/d.ts files

### ISSUE THREAD

**Issue by tavinashb** [bokeh/bokeh#8197]
Hi, 

I am trying to use standalone BokehJS library with typescript and AngularJS.

I have installed JS library using `npm i bokehjs`.

and imported in component using `import * as Bokeh from "bokehjs"`

But after starting application getting multiple errors related to `Module not found: Error: Cannot resolve module`.

Here are first few lines of log - 

```
ERROR in ./~/bokehjs/build/js/tree/document.js
Module not found: Error: Cannot resolve module 'core/bokeh_events' in
@ ./~/bokehjs/build/js/tree/document.js 7:21-49

ERROR in ./~/bokehjs/build/js/tree/protocol/message.js
Module not found: Error: Cannot resolve module 'core/util/string' in
@ ./~/bokehjs/build/js/tree/protocol/message.js 3:15-42

ERROR in ./~/bokehjs/build/js/tree/models/layouts/layout_dom.js
Module not found: Error: Cannot resolve module 'core/dom' in 
@ ./~/bokehjs/build/js/tree/models/layouts/layout_dom.js 5:12-31 
```

**Comment by mattpap** [comment]
bokehjs uses a combination of relative and absolute imports within the library (for better or worse), so you need an additional step in the compilation and bundling processes. Here is an example how to configure TypeScript to work with bokehjs (based on the configuration of our unit tests):
```json
    "paths": {
      "*": ["../build/js/tree/*", "../build/js/types/*", "../src/lib/external/*"]
    },
```
(https://github.com/bokeh/bokeh/blob/master/bokehjs/test/tsconfig.json#L16-L19). You will need to consult documentation of other tools you use to set things up there. Usually it's as simple as adding the above paths to an appropriate configuration option.

bokehjs was originally meant to be used as a JavaScript bundle, so using it as a set of node modules is currently suboptimal. This may or in fact should improve in future.

**Comment by tavinashb** [comment]
@mattpap thanks for reply, i am using webpack and bower in my project instead of typescript. 

In this case,  how to remove dependencies error as mentioned above?

**Comment by Shekharrajak** [comment]
Even I tried to use BokehJs in Angular application and got these kinds of error. Actually ervery path should have been relative path.

**Comment by paddymul** [comment]
@mattpap  Do you have objections to me making a PR for those changes?  I want to use bokehJS as a standalone module too.   

Are there any problems with adding things to the bokehjs npm artifact?

**Comment by mattpap** [comment]
> Do you have objections to me making a PR for those changes?

What changes exactly you are referring to?

**Comment by paddymul** [comment]
Changing the paths as you described on Aug, 31st.  

To put it another way, what thoughts or concerns does the core bokeh team have about node module that gets published to NPM?

Would they be open to a pull request that makes bokehJS usable as standalone library for an NPM based js project.

**Comment by mattpap** [comment]
> Changing the paths as you described on Aug, 31st.

This refers to external configurations, nothing that can be done within bokehjs. What can be done in bokehjs, is changing the build system, by adding a stage that would rewrite absolute internal module paths with relative paths (I have some preliminary work done towards this). I don't consider this an issue by itself, because it's not uncommon for large projects to have mapped module paths. However, this is something that definitively needs attention, because even recently we run into some conflicts between our modules and transcendental dependencies (though changing the build wouldn't actually solve this particular issue).

>  makes bokehJS usable as standalone library for an NPM based js project.

bokehjs is already usable under configuration. Module paths aside, the only other issue is that `require("bokehjs")` doesn't give the same API as `Bokeh` global from `bokeh.js` bundle. I'm not sure about the overall solution to this issue, because we make actually change the API of `Bokeh` and not load all models ahead of time or make the API lazy, etc., to improve bokeh.js' load times. This will require some thought. I'm speaking about `master`, because whatever is currently published to npmjs.com is outdated and irrelevant.

**Comment by paddymul** [comment]
Is there a downside to rewriting all absolute internal module paths to relative paths statically in git?  I'd be happy to do this.

**Comment by mattpap** [comment]
The downside is that we will end up with module paths like:
```ts
import {sum} from "../../../../core/util/array"
```
which is a pain to work with and maintain the code. We used to use such paths and I'm definitively not going back to that. An alternative would be to split up bokehjs into more fine grained modules, but given the complexity of the project that's easier said than done and may be actually more work than it's worth. That's why I think the most effective solution is to transform source files automatically (using TypeScript compiler's AST transforms). Given that we already interact with the compiler heavily, that should be pretty easy for me to implement, though not the biggest priority right now. However, I will be making big changes to our build next month, e.g. to allow building custom bokeh.js bundles on demand, so this could be done at the same time.

**Comment by paddymul** [comment]
I would really like to help on this.  I’m looking to play with bokehJS in standalone JS apps, particularly ReactJS.  If you could point me to docs on either the compiler transform side or more information (similarly packaged projects, relevant docs) about how to use bokehJS in a standalone project I would appreciate it.

Thanks,
Paddy

**Comment by appleparan** [comment]
Is it really completed? I got error when just importing `bokehjs` in React and start with `npm start`.

```
./node_modules/@bokeh/bokehjs/build/js/lib/models/annotations/annotation.js
Module not found: Can't resolve 'styles/annotations.css' in 'mydirectories../node_modules/@bokeh/bokehjs/build/js/lib/models/annotations'
```
I made an [example](https://github.com/appleparan/bokeh-8197) to reproduce error.
I just followed these steps.

```
$ npm -v
6.14.5
$ node -v
v14.4.0
$ npx create-react-app myapp
$ cd myapp
$ npm i @bokeh/bokehjs
```
then add `import * as Bokeh from "@bokeh/bokehjs";` in `App.js`. 
I tested with Ubuntu 18.04 on WSL2.


Here is where the error is caused.

https://github.com/bokeh/bokeh/blob/00cdec4979bc27a4f1cb35dc3d8f4e62ae93deac/bokehjs/src/lib/models/annotations/annotation.ts#L9

**Comment by mattpap** [comment]
It was completed, but recent changes may have caused a regression. Please start a new issue based on your comment. This should be trivial to fix.
