### ISSUE TITLE
Split BokehJS in multiple plugins

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#820]
Suggest that models that are believed to be used less often be removed from BokehJS proper, and loaded from python modules via an `__implementation__`. Suggestions might be `Gear`, `Gauge`

**Comment by mattpap** [comment]
I will close this issue, because we already have bokehjs split into `bokeh`, `bokeh-api` and `bokeh-widgets`, and soon there will be `bokeh-webgl`. Additionally `Gear` was removed from bokeh/bokehjs and an example was created instead. We should now focus on issues targeting specific areas where the size of the main bokehjs bundle can be reduced.
