### ISSUE TITLE
Incorrect figure(scatter) rendering for 2 points with different axis scale.

### ISSUE THREAD

**Issue by shir994** [bokeh/bokeh#8266]
For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

- python3 -c "import bokeh; print(bokeh.__version__)"
0.13.0
- Python 3.5.2
- Browser independent(opened in Chrome, Safari, Opera)

#### Description of expected behavior and the observed behavior
The expected behaviour is a scatter plot with 2 circles of different radius, like in provided screenshot.

In reality, I get two circles with incorrect radius, and incorrectly rendered(see another screenshot).

That depends on x,y I specify for points_descr. If x << y, than axis on the plot has different scale and the radius on on of the axis does not coincide with the one, specified in the code. Thus, I just get huge circle(in y), which covers the whole plot.
```
import bokeh
from bokeh.plotting import figure, output_file, show, ColumnDataSource, save
from bokeh.models import ColumnDataSource, HoverTool

p = figure()

points_descr = ColumnDataSource({'x': [-0.12758381], 'y': [5.87131042]})
p.scatter(x='x', y='y', radius=0.05, source=points_descr)

pivot_center = ColumnDataSource({'x':[0], 'y':[0]})
p.scatter(x='x', y='y', radius=0.2, source=pivot_center)

output_file("./templates/color_scatter.html", title="color_scatter.py example")
save(p)
```
good render
![good](https://user-images.githubusercontent.com/8977719/45828570-20ebc100-bcf9-11e8-8045-59e9453520ae.png)
bad render
![bad](https://user-images.githubusercontent.com/8977719/45828571-21845780-bcf9-11e8-8bfa-07201f3d7db5.png)
bad render, zoomed out
![bad_2](https://user-images.githubusercontent.com/8977719/45828572-21845780-bcf9-11e8-9e05-e0e87658d48b.png)

```

**Comment by bryevdv** [comment]
@shir994 circles have to pick some direction to measure, there is no getting around that. If you have very differnet scales on x and y axes, your choices are:
 
* use `match_aspect=True` to force the scales to be the same on both axes

* use `size` instead of `radius` to draw the circle as a size in *pixels*

This is discussed already in several other issues. #474 #517 #6500 #6603 #6760 In the future please make an effort to search the tracker first before making new issues.
