### ISSUE TITLE
ESC has no effect on selections

### ISSUE THREAD

**Issue by ibestvina** [bokeh/bokeh#8292]
Minimal example:  
```
from bokeh.plotting import figure, output_file, show
from bokeh.models import BoxSelectTool

output_file("clear_select.html")

plot = figure(plot_height= 300, plot_width=300, tools=[BoxSelectTool()])
plot.circle(x=[1,2,3,4], y=[1,2,3,4])

show(plot)
```
After selection, `ESC` does not clear it. `SHIFT` works for multiple selections. Tried on Firefox (61), Chrome (69) and Edge (42). Windows 10 64bit. Bokeh 0.13.

I'm quite sure it all worked fine ~10 days ago. AFAIK nothing updated since then. It's not a problem of keys not getting through to the browser, on pages like http://www.keyboardtester.com/ `ESC` works fine.

**Comment by bryevdv** [comment]
cc @mattpap 

Looking at old gallery plots for older versions, this seems to have been broken since 0.12.15 I don't really understand it, though. I can verify the code to call `sm.clear` is getting called when ESC is pressed, but the selection does not update. However, the reset tool does work and AFAICT it ends up just doing the same thing, calling `sm.clear`

**Comment by mattpap** [comment]
It clears just fine, just doesn't rerender. I presume glyph renderer doesn't listen on the right signals. Reset tool works, I presume, because there is other code there that may request render. Also, I noticed that keyboard event is handled twice in (at least) select tool.
