### ISSUE TITLE
Legend click_policy with labels

### ISSUE THREAD

**Issue by juglaz** [bokeh/bokeh#8342]
Hi All,

I'm interested in using the click_policy feature on the legend, but there doesn't seem to be any way to tie this behavior to the relevant labels. It would be great to be able to associate a Label with a series so that the label hides with the series on click.

Alex

**Comment by bryevdv** [comment]
@juglaz I'm not really sure what you are asking about based on this. However, as it stands it seems like more of a help/support request than a bug report or feature request.  As stated in the issue template, the GitHub issue tracker is reserved for bug reports and feature requests only. It is not the appropriate place to seek general support or help with usage questions. For that, please consider [Stack Overflow](https://stackoverflow.com/) or the [public mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh). To increase the chance that someone will decide to volunteer their time to help, always include as much information and detail as possible. *Most especially: a minimal, **complete** code sample*.

If it turns out otherwise, we can always re-open this (with more detailed information)
