### ISSUE TITLE
Confusing multi_line error message

### ISSUE THREAD

**Issue by syhooper** [bokeh/bokeh#8348]
I got this error message (“RuntimeError: 
Supplying a user-defined data source AND iterable values to glyph methods is
not possibe. Either: Pass all data directly as literals: p.circe(x=a_list, y=an_array, ...)
Or, put all data in a ColumnDataSource and pass column names: source = ColumnDataSource(data=dict(x=a_list, y=an_array)) p.circe(x='x', y='y', source=source, ...)”) when I tried to run the code below. 

However, the error message doesn't seem to be helpful. The problem is from line_color. I should have defined the line color in the ColumnDataSource and then referenced the line color in the multi_line function. So it would be helpful if the error message points out the line_color issue. Also, there is a typo 'circe' in the error message.  

Thanks! 

**Code with the error message:**
```
ys = [row[1].as_matrix() for row in DF.iloc[:,1:].iterrows()]
num_lines = len(DF)
xs = [DF.columns[1:].values]*num_lines

source = ColumnDataSource(data=dict(
    x = xs,
    y=  ys
))

p = figure(
           x_range = DF.columns[1:].values.tolist(),
           plot_width=600, plot_height=300)
p.multi_line(
    xs='x', 
    ys='y',
    source=source,
    line_color=Viridis256[0:num_lines],
    line_width=2
)
show(p)

```

**Correct code:**
```
ys = [row[1].as_matrix() for row in DF.iloc[:,1:].iterrows()]
num_lines = len(DF)
xs = [DF.columns[1:].values]*num_lines

source = ColumnDataSource(data=dict(
    x = xs,
    y=  ys,
    color = Viridis256[0:num_lines]
))

p = figure(
           x_range = DF.columns[1:].values.tolist(),
           plot_width=600, plot_height=300)
p.multi_line(
    xs='x', 
    ys='y',
    source=source,
    line_color='color',
    line_width=2
)
show(p)
```

**Comment by bryevdv** [comment]
@syhooper The error message is just meant to be illustrative of the *kind* of usage that is correct, which is also why the "..." are there. I'm not sure what else or more we can do here though if you have a specific suggestion for different wording, please share it so we can consider it.

**Comment by jbednar** [comment]
I can't quite see how to interpret the "...".  Why does line_color have to be a column name here, while line_width doesn't?  Is the problem that Viridis256 is a list, and it would have been fine as "red"?  If so maybe the error message could say that all properties provided either need to be scalars (like "red") or else strings specifying a column in the CDS?

**Comment by bryevdv** [comment]
> I can't quite see how to interpret the "..."

I'm genuinely surprised by this. What other meaning could there be besides "extra irrelevant stuff has been omitted"?

> all properties provided either need to be scalars (like "red") or else strings specifying a column in the CDS?

That's not a true statement. This situation only applies to DataSpecs, which can either be single scalar values, or columns of data. When providing any columns of data for a DataSpec property, the situation is:

* either all the columns have to be literal sequences passed to the glyph function, OR
* all the columns have to be string names that reference a column in a CDS

You can't mix and match the two possibilities. The current message is an attempt to balance giving enough information to act vs going off into the weeds with a 15 line message. 

I guess, not to put to fine a point on it, I disagree that the message is not helpful, since it led the suer to the correct code, which is exactly its purpose.

**Comment by jbednar** [comment]
Actually, it didn't!  Sophia and I both stared at that message, and we agreed that we had done everything it said, yet it was still complaining.  I certainly had no idea that "Viridis256[0:num_lines]" was the culprit. I think Philipp helped her figure that out, and I suggested she file this issue because we both found the current message was *not* pointing us in the right direction.  So I'm giving feedback that the current message did not make it clear what to do, at least not to me. I think if there were an example of some optional value that also needs to be updated, then it would be clear to look for those.

**Comment by bryevdv** [comment]
>  I think if there were an example of some optional value that also needs to be updated, then it would be clear to look for those.

I'm not really sure what you are suggesting. What I would appreciate is a concrete sentence or paragraph, actual specific text, to replace what is there. I think the current message is good, so I am definitely not qualified to author a replacement.

**Comment by philippjfr** [comment]
Personally I also find the message informative, but that's probably because I was aware of this restrictions and was therefore immediately able to point out the issue to @syhooper. Would it not be possible to specifically point out the dataspecs that were constructed incorrectly, i.e. leave the current error as an illustrative example and then add something like:

```
Expected xs and line_color to reference fields in the data source.
```

**Comment by bryevdv** [comment]
```
In [1]: from bokeh.plotting import figure, ColumnDataSource
   ...: p = figure()
   ...: source = ColumnDataSource(data=dict(x=[1,2,3]))
   ...: p.circle('x', [4,5,5], line_color=["red", "green", "blue"], source=source)
y True
line_color True
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-5197055b149c> in <module>
      2 p = figure()
      3 source = ColumnDataSource(data=dict(x=[1,2,3]))
----> 4 p.circle('x', [4,5,5], line_color=["red", "green", "blue"], source=source)

fakesource in circle(self, x, y, **kwargs)

~/work/bokeh/bokeh/plotting/helpers.py in func(self, **kwargs)
    756         incompatible_literal_spec_values += _process_sequence_literals(glyphclass, glyph_ca, source, is_user_source)
    757         if incompatible_literal_spec_values:
--> 758             raise RuntimeError(_GLYPH_SOURCE_MSG % nice_join(incompatible_literal_spec_values, conjuction="and"))
    759
    760         # handle the nonselection glyph, we always set one

RuntimeError:

Expected y and line_color to reference fields in the supplied data source.

When a 'source' argument is passed to a glyph method, values that are sequences
(like lists or arrays) must come from references to data columns in the source.

For instance, as an example:

    source = ColumnDataSource(data=dict(x=a_list, y=an_array))

    p.circle(x='x', y='y', source=source, ...) # pass column names and a source

Alternatively, *all* data sequences amy be provided as literals as long as a
source is *not* provided:

    p.circle(x=a_list, y=an_array, ...)  # pass actual sequences and no source

```

@syhooper @jbednar @philippjfr ?

**Comment by jbednar** [comment]
Perfect, after amy->may.  Thanks for seeing this through.

**Comment by philippjfr** [comment]
Looks perfect to me.

**Comment by syhooper** [comment]
Awesome! Thanks so much!

**Comment by bryevdv** [comment]
It truly doesn't matter what we do, it seems:

https://stackoverflow.com/questions/53084449/bokeh-runtimeerror-how-to-add-tooltips-to-plot
