### ISSUE TITLE
Add a Figure.contour method

### ISSUE THREAD

**Issue by jsignell** [bokeh/bokeh#8360]
Since `MultiPolygons` have landed, we should be able to support filled contours. Filled contours should be composed of multiple polygons each of which can have holes. Levels of contours should never overlap with each other - every new level that is contained within the bounds of a level should be a hole. This will make hover and tap tools great *and* makes sense conceptually if we think about elevation because no x, y has multiple elevations. 

My original attempts at determining which polygons contain which others is contained in this notebook - but holoviews now has the concept of holes,  so it should be more straightforward:
https://anaconda.org/jsignell/contouring_with_holoviews/notebook

We can probably borrow most of the logic from holoviews if we want to depend on matplotlib. Otherwise there is a scikit-image method as well.

**Comment by bryevdv** [comment]
Definitely don't want to depend on MPL. The two options I would see would be:

* Write code on top of the skimage code to generate polygons, and optionally depend on skimage 

* make a new separate package of the current C++ contour implementation in MPL (or of the old "legacy" c version which is fine AFAIK) and put those up for distribution via conda and pip wheels, then optionally depend on that package (or even make it a hard requirement -- the point is only to not have compiled code in the Bokeh build proper)

I guess all things being equal, I'd prefer option 2 since generating polygons "after the fact" from single isolines is not trivial, and the C library already handles this.

**Comment by spott** [comment]
So, I really wanted this and wrote up a bunch of code to make it work using just skimage.

The code is here:
https://gist.github.com/spott/0d140df0d3b3e30aa821fc97b8e35f3a

It isn't really *done*, (there is a few cleanups to do:  rescaling the axes, maybe transposing it so it matches with figure.image), but it is getting there.

I'll try and work this into a pull request over the next *n* days, but I'll probably need some help... I built a bunch of utility classes, in order to make this work, and I'm not sure where to put them, or if they should be ported to better internal representations.

For example, do you guys have an internal binary tree that you use for anything?

let me know what you think!

**Comment by bryevdv** [comment]
@spott First off: this is an exciting possibility. My druthers would still be with making and publishing a new package for the old MPL contour function, simply to avoid all the dependencies that skimage brings in (even if it is optional). However, realistically I don't know when I would have time to dedicate to that project, so I would definitely support a workable solution based on skimage at this point. 

I did try to run your notebook, but ran into some problems:

<img width="1095" alt="Screen Shot 2019-06-06 at 5 28 12 PM" src="https://user-images.githubusercontent.com/1078448/59074615-0fdfe180-8881-11e9-876c-81bbb034550b.png">

To answer your other questions: 
* we don't have or use a binary tree structure anywhere on the python side (most work is in BokehJS with a few exceptions like hex-binning and this)
* `bokeh.contour` is probably a good place to stick most everything to start, we can split things off at the end if need be
* I'd suggest an API that takes an image and configures or generates a CDS compatible with `multi_polygons` then a `Figure.contour` is just a simple wrapper around that.

**Comment by bryevdv** [comment]
FYI when I run it's the first `t.children` that fails:
```
>>> print(len(t.children))
2
```
Also  may I suggest we move this to the Development category of the Discourse? Given the amount of up-front discussion and iteration that I think this might take, that would be a more comfortable venue: https://discourse.bokeh.org/c/development

**Comment by spott** [comment]
It appears I left some debug code in that notebook, sorry about that.  I’ll update it with a cleaner version when I get into work.

I’ll also jump on the development discord server, and we can talk a bit more about how to organize this.

**Comment by spott** [comment]
The notebook should work now.

**Comment by spott** [comment]
I've started a thread in discourse: https://discourse.bokeh.org/t/contourplot-discussion/3567

**Comment by p-himik** [comment]
Answering to [the comment](https://github.com/bokeh/bokeh/issues/11105#issuecomment-809638197):
> Regarding contours, we are already looking at optional C or C++ packages to support it. The best I could imagine doing in JS is implementing a Marching Squares implementation. But it would probably be too slow, and worse, Marching Squares is a purely local algo that generates a pile of disconnected segments rather then actual iso-lines that could drive MultiPolygons.


Perhaps, instead of creating a full implementation, it would instead be possible to create an API that:
- Binds together Bokeh and BokehJS
- Has a working implementation in Bokeh with whatever libraries you choose
- Makes it easy for the end user to provide the right implementation for BokehJS

Then you won't have to think if something is fast enough or not and works the right way or not. Marching Squares might be just the thing for someone but an ugly mess for someone else (and then they might end up using wasm with those C/C++ packages). No need to decide for them.

**Comment by bryevdv** [comment]
> Perhaps, instead of creating a full implementation

I should be clear that I don't really want to implement anything here, per se. There are existing options to do the heavy lifting:

* maybe sk-image `find_countours` can be leveraged (by ensuing their contours become closed)
* the old MPL tracing implementation in C could be packaged
* the new MPL marching + post-processing implementation in C++ could be packaged

*All* I want in bokeh is (what I consider) a very small amount of convenience glue code to connect the dots between any of the existing tools for countouring, and `MulitPolygons`.

**Comment by mattpap** [comment]
> Porting the algorithm to JavaScript might be an interesting project for someone, but I don't expect it to run fast enough to be workable.

This may be a good opportunity to experiment with WebAssembly and assess validity of using it in bokehjs.

**Comment by ianthomas23** [comment]
> > Porting the algorithm to JavaScript might be an interesting project for someone, but I don't expect it to run fast enough to be workable.
> 
> This may be a good opportunity to experiment with WebAssembly and assess validity of using it in bokehjs.

I don't have any experience of WebAssembly so I am not qualified to comment on the pros and cons of this approach or how much effort it would take, but I agree that it sounds like something we should look at.

Alternative functionality that we might consider as our first foray into WebAssembly is the triangulation of MultiPolygons which will be needed for WebGL rendering.  I would expect this to be easier than porting the contouring code as we might find an existing implementation that has already done much of the heavy lifting for us.

**Comment by bryevdv** [comment]
closed by #12020
