### ISSUE TITLE
no source (columndatasource) for hexbin glyph?

### ISSUE THREAD

**Issue by bjarthur** [bokeh/bokeh#8361]
most other glyphs can input a columndatasource for the x and y parameters.  but not hexbin.  a feature yet to be added?

**Comment by bryevdv** [comment]
(FYI this kind of question should go on the mailing list)

Hexbin is not a glyph, it is a high level function that creates a `HexTile` (which is a glyph) as well as a column data source for the `HexTile` glyph. The reason it is not useful for `hexbin` to accept a CDS is because, unlike glyphs which just draw the data exactly as given to them, `hexbin` actually performs a computation and transformation of the data. Furthermore, this computation relies on Pandas, so it has to happen in Python. It would not be possible, e.g. to have `hexbin` accept a CDS, and then have the plot update correctly if that CDS was changes by a `CustomJS` callback.

If you want to access hex tile coordinates directly, use the actual `hex_tile` glyphs rather than `hexbin` (or if you just want to refer to them, the renderer returned by `hexbin` has a data source that was created after as a result of the binning that can be inspected.
