### ISSUE TITLE
Autohide toolbar should work with gridplot 

### ISSUE THREAD

**Issue by jsignell** [bokeh/bokeh#8364]
At the moment, the autohide callbacks are implemented in `toolbar_panel` where we have access to `plot_view` - where we can keep track of mouse events. For `gridplots`, the toolbar is instantiated in `toobar_box` and we don't have access to `plot_view` there. It doesn't even really make sense to have a `plot_view` since there are multiple plots. We do have access to the `root_element`, so we could use that to monitor `mouseenter` and `mouseleave` events. But I am pretty sure that is bad form.

**Comment by jsuarez5341** [comment]
This is still an issue and makes gridplots pretty ugly. Autohide only functions correctly in the top left plot. When working with a grid of plots, your options are 1) use autohide and lose interactive tools on all but the first plot or 2) don't use autohide and have your gridplot cluttered with multiple toolbars.

I think that this issue should be promoted to type:bug given that the current situation breaks expected behavior. It took me a bit of head scratching and googling to find this issue.

**Comment by bryevdv** [comment]
Respectfully @jsuarez5341 the clarification is not a matter of promotion or priority. Bugs are problems in code that exists. Features are things that the (volunteer) contributors have yet to implement.

**Comment by jsuarez5341** [comment]
Fair enough -- I'll find a workaround for my application and post back if I come up with anything that might help others in the meanwhile. I would suggest adding a couple lines to the autohide docs. I didn't see any indication that current functionality is limited to certain layouts, hence it seemed like a bug.
