### ISSUE TITLE
Glyph max_size, min_size type: feature

### ISSUE THREAD

**Issue by iconberg** [bokeh/bokeh#8382]
I would like to see a way to set a max/min value for glyph size in screen space units.
For example, if i use a lot of scatter points (~6000, using radius) on a geo map, i see small glyphs until zooming in. But zooming in the glyphs grow to big, so they cover up the map.
To slove that a max_size, min_size would be useful.
![bokeh_map1](https://user-images.githubusercontent.com/8441455/47722013-b57b0480-dc51-11e8-9923-f998b4990efd.png)
![bokeh_map2](https://user-images.githubusercontent.com/8441455/47722020-b9a72200-dc51-11e8-80f5-1e2c82016a2c.png)

**Comment by bryevdv** [comment]
@iconberg it's something we might be able to consider, but the proposal needs to be fleshed out more carefully and fully first. For example, off the top of my head, max size makes no sense at all with some glyphs like `line`, `patch`, `arc`, bezier`... It also makes no sense with all markers except Circle, since they are already (and only) draw at a fixed screen space size. At a minimum you would need to do a survey of all the existing glyphs and draft a complete list of exactly which glyphs would get this new attribute.

However, I would say it's also worth exploring first whether this could already be accomplished with a `CustomJS` transform, without needing to add anything new at all. It seems to me that might be feasible.  If that is the case, I'd much more favor adding a new example/documentation about how to use a general capability like `CustomJSTransform` to moderate attributes, rather than adding a new very specialized feature.

**Comment by iconberg** [comment]
@bryevdv Yes, i see now, most of the glyph have a fixed size that wont be changed while zooming. For display data on a geo map i tried some with radius, circle, wedge and annulus so far. I use radius and they changed size while zooming, what i want to see. But i think if more people see how nice geo maps are usable in bokeh they want different glyphs that change while zooming within boundaries.

So i think a general solution maybe are a change_with_zoom flag, which enables changing glyph size from zooming and min_bounding_box / max_bounding_box for all glyphs. So it could be possible to draw buildings with polygons and place them on a geo map for example. Or pie charts, bar charts etc. And use different glyphs for series of data. But for me this seems like a big, complicated and work intensive task to archive.

Maybe there is a more simple way like [Mappers](https://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#using-mappers) for colors. Instead of colors we can map sizes to a zoom factor. I would like such a solution.

I take a look at the callback you mentioned above, i guess i can figure this out if an example is provided.

**Comment by bryevdv** [comment]
a `CustomJSTransform` is not a callback, it is actually a more general kind of mapper. Here is an example:

https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/customjs_transform.py

To make this work I believe you'd want to use the scale to convert the max/min size into a max/min data space length, then use that to clip the computed radius value, etc.

**Comment by iconberg** [comment]
I would like to try avoid using javascript, so i can use [CustomJS with a Python function](http://bokeh.pydata.org/en/latest/docs/user_guide/interaction/callbacks.html#customjs-with-a-python-function) or Bokeh Server Application. I think i will go with "CustomJS with a Python function" for offline usage too. 

Yes, i want to use the scale or perhaps the shown range and modify the glyphs. I think i should/could use x_range / y_range form here: [bokeh.plotting.figure](http://bokeh.pydata.org/en/latest/_modules/bokeh/plotting/figure.html#figure)
Right? Thank you for your help.

**Comment by bryevdv** [comment]
@iconberg Yes you could use the range start/end directly to compute data space lengths instead of using the scale. Since this is now more of a support question, it really belongs on the mailing list. I am going to close this issue and we can continue discussions there if need be.
