### ISSUE TITLE
Bokeh charts load very slow with Uncaught TypeError: in browser console

### ISSUE THREAD

**Issue by false9striker** [bokeh/bokeh#8403]
Bokeh charts render data points very slow with below error in the browser console. 

```
Uncaught TypeError: Cannot read property 'handle' of null
    at t._steady_state_handler (connection.js:262)
    at t.ACK.t.msgtype._current_handler (connection.js:242)
    at t._on_message (connection.js:204)
    at WebSocket.i.socket.onmessage (connection.js:61)
```

#### Screenshots or screencasts of the bug in action

<img width="472" alt="screen shot 2018-11-06 at 8 58 44 am" src="https://user-images.githubusercontent.com/628338/48080688-231fb700-e1a3-11e8-85a6-53d72598bc8f.png">

**Comment by mattpap** [comment]
This seems to be a legitimate bug, but without a lot more information regarding the setup, preferably a minimal, reproducible code sample, we won't be able to do much about this.

**Comment by false9striker** [comment]
I think this was happening because of a slower response from API. Closing this as it's working as expected now.

**Comment by p-himik** [comment]
I finally updated from Bokeh 0.12.16 to 1.2.0 and now I see these errors as well.
It seems there's some race condition: this line https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/client/connection.ts#L283 gets executed before this one https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/client/connection.ts#L167
I'll try to debug this a bit more but it'd be great to have some pointers since it's been quite a while since the last time I touched any Bokeh code.

**Comment by p-himik** [comment]
Huh: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/client/connection.ts#L264-L266
```
      // Reload any sessions
      // TODO (havocp) there's a race where we might get a PATCH before
      // we send and get a reply to our pulls.
```

**Comment by bryevdv** [comment]
@p-himik Offhand it seems like we could queue messages in `_steady_state_handler` if there is no session yet, then apply any queued messages immediately after the session is opened. 

We could in fact consider using a queue for messages in general, to decouple the web socket message receiving from session actions

**Comment by p-himik** [comment]
@bryevdv Thanks. :)

But the WS messages handling is synchronous, including the method that generates `PULL-DOC-REPLY` response. That means that all the queued messages will be already incorporated into the document when it arrives. So instead of putting messages in a queue and then applying them (hoping that they're idempotent) we could just discard them.
Does it make sense?

**Comment by bryevdv** [comment]
@p-himik I only made a cursory glance so definitely happy to defer to your more careful analysis
