### ISSUE TITLE
HoverTool does not display fields within JupyterLab's Dark Theme

### ISSUE THREAD

**Issue by pisymbol** [bokeh/bokeh#8459]
#### Software

jupyter 4.4.0
jupyterlab 0.35.4
bokeh 1.0.1
python 3.6.6
Ubuntu 18.04 bionic docker container (not that this makes a difference)

#### Description of expected behavior and the observed behavior

HooverTool  fields (`@field` etc.) are not displayed when you highlight a region on a chart when you are under a Jupyter Dark Theme. If I change my notebook's theme to the default Light theme, everything just works.

#### Complete, minimal, self-contained example code that reproduces the issue

https://bokeh.pydata.org/en/latest/docs/gallery/pie_chart.html

#### Screenshots or screencasts of the bug in action

<img width="698" alt="hooverdarktheme" src="https://user-images.githubusercontent.com/17936726/49049661-f82af080-f1ad-11e8-92d7-76497e8e6fba.png">

**Comment by mattpap** [comment]
I will consider this to be a bug on our side, because setting background color should be accompanied by setting text color as well, and not depend on any inherited values in such scenario. However, I think that part of the problem is also in jlab, because they shouldn't style output area the way they do and only limit theme application to e.g. their widgets. Alternatively, if they set text color, they should set background color as well. I think this should be followed up upstream.
