### ISSUE TITLE
Feature Request: CSV Download Tool

### ISSUE THREAD

**Issue by platise** [bokeh/bokeh#8483]
We are using bokeh with jupyter to generate measurements reports, like [hw usage tutorial](https://www.isotel.eu/idm/device/monodaq/monodaq-u-x.html#real-power-comes-with-python-and-jupyter) besides harware test reports, calibration reports, etc., so this charts appear whenever there is some analog circuitry involved. So if there is a transfer characteristics which user would like to further evaluate it would be nice to have aka **Download in CSV format** tool option on the right.

**Comment by bryevdv** [comment]
I would instead point you at this example that demonstrates how to use a CustomJS callback to save a data source:

https://github.com/bokeh/bokeh/tree/master/examples/app/export_csv

If you'd rather have that in a toolbar button, you could also use the recent `CustomAction` instead of a `Button`. 

There are unfortunately alot of use case possibilities:

* There can be multiple data sources, save which one? All of them? A UI to choose?
* Save to file? To s3? To dropbox? Just open a new tab with the CSV? Also, ticks to prompt a "file save" don't work on all browsers  (the example above no longer works on Safari for instance -- it used to)

I think it is likely that any tool we might add:

* would be complicated and fragile
* would fail to satisfy many people's needs. 

Given that, and our extremely limited resourcing, I deem that it's better for everyone, and a better use of those limited resources, to provide and document raw capability (i.e. `CustomJS` callbacks) so that users can customize a solution to their individual needs,.
