### ISSUE TITLE
Tap event latency

### ISSUE THREAD

**Issue by atrabattoni** [bokeh/bokeh#8508]
The Tap event does not kick in directly. It takes place after a short timeout which can be unwanted for some applications (see below). Apparently, as discussed [here](https://groups.google.com/a/continuum.io/d/msgid/bokeh/62C55C5B-4D99-4897-BFB9-EFB7FC7DA6B3%40gmail.com?utm_medium=email&utm_source=footer) the underlying gesture event library used probably has to delay recognition of single tap events long enough to determine that the tap is not actually just the start of a double tap. It would be nice if the user could choose to remove this timeout for more reactive click interactions.  

Here an example where things do not work as expected:
I want to fit curves on a background image. For that purpose I plan to:
1) use the MouseMove event to update on real time some (quite complex) curve which pass where the mouse is. 
2) use the Tap event to freeze/unfreeze the curve to stop updating the curve shape when at the right location. 

Due to this timeout, when I click at the wanted curve position and then move the mouse some where else some MouseMove events occur before the Tap event kicks in, which is very frustrating.

A minimal code with screencast below. I click on the purple square and move the mouse to the right. Instead of staying at the tap location, the curve follow the mouse during the Tap timeout. 

```
import numpy as np
from bokeh.plotting import figure, curdoc
from bokeh.models import Span
from bokeh.models.widgets import Div
from bokeh.events import Tap, MouseMove

# controls if mouse positions update shape property
active = False 

p = figure(x_range=(0, 1), y_range=(0, 1))

# any background image 
img = np.random.randint(0, 255, (3, 3, 4), 'uint8') 
p.image_rgba(image=[img], x=[0], y=[0], dw=[1], dh=[1]) 

# any (complicated) shape
shape = Span(location=0, dimension='height') 
p.renderers.extend([shape])

# freeze/unfreeze shape
def tap_callback(event):
    global active
    active = not active
    
def shape_callback(event):
    if active:
        # any (complicated) shape update 
        shape.location = event.x
    
p.on_event(Tap, tap_callback, shape_callback)
p.on_event(MouseMove, shape_callback)

curdoc().add_root(p)
curdoc().add_root(div)

```

![2018-12-17 11 12 36](https://user-images.githubusercontent.com/32540975/50080974-9a5a5900-01ed-11e9-8712-b11cb015bd0b.gif)

**Comment by bryevdv** [comment]
FYI I believe this hypothesis is the correct explanation. Here is the documentation for the tap event in HammerJS:

http://hammerjs.github.io/recognizer-tap/

Which states:

> ... it waits the interval time before emitting the event. This is because if you want to only trigger a doubletap, hammer needs to see if any other taps are coming in.

And it looks like the default setting for "Maximum time in ms between multiple taps." is 300ms, which seems consistent with your observations of "about half a second". 

We could add an `interval` property to the `TapTool` that just sets the `interval` property in HammerJS. It would retain the existing default, but would provide an "escape hatch" for users that need or want a different setting. We should be clear that setting this value may adversely effect other event detects (i.e. double taps may not register anymore... just speculating)

Another possibility might instead be to add a property to turn of "requiring failure of double tap". This is configured in the BokehJS code here:

https://github.com/bokeh/bokeh/blob/f4b4b113008d0eb5c06cd966dede0e379616a7bf/bokehjs/src/lib/core/ui_events.ts#L118-L120

I'm open to either possibility. Some experiments need to be carried out to confirm that

* dropping the required failure solves the problem, or
* lowering the interval solves the problem

Then we can decide which route to pursue. 

@atrabattoni would you be interested in working on this with some help/guidance? I think it is likely that you would be able to get to it sooner than anyone on the core team.

**Comment by atrabattoni** [comment]
I'll see if I can do something but it will probably wait the begging of January.

**Comment by bryevdv** [comment]
@atrabattoni do you still expect to be able to look at this?

**Comment by meson800** [comment]
Sorry to necro this issue; it seems to be the most recent relevant issue. Is there a workaround for this issue that can be done on the bokehjs side?

I'm writing a custom bokehjs edit tool, and the tap latency is making it feel sluggish. For my extension, I'd be fine with generating two tap events for every double-tap event, as I can handle that. 

I've been trying to see if there is a hacky way I can get the `UIEvents` object and customize Hammer from there, or perhaps doing something even messier and registering/deregistering my own mouse-down event to feed into my custom extension to get around the 300ms delay.

**Comment by meson800** [comment]
Ok, I've confirmed that dropping the doubletap failure does eliminate the latency. In my custom tool, doing something like:
```
 override activate(): void {
    this.plot_view.canvas.ui_event_bus['hammer'].get("tap").dropRequireFailure("doubletap")
    // other activation
}
override deactivate(): void {
    this.plot_view.canvas.ui_event_bus['hammer'].get("tap").requireFailure("doubletap")
}
```
eliminates the 300ms latency, but only for my tool.

For the moment, I'm going to use this approach, but it is still definitely a hack because 1) it's using the string array trick to access the private member `hammer` and 2) I'm just restoring the current Bokeh default, which means if for whatever reason someone else is doing the same trick, it could interfere.

**Comment by atrabattoni** [comment]
Hi @meson800 . I encountered this issue again for a new stuff I'm working on. Your hack is interesting me! Where should I put this JS code ? Are you doing something similar than https://docs.bokeh.org/en/latest/docs/user_guide/advanced/extensions/tool.html#a-new-custom-tool ? Thanks !

**Comment by meson800** [comment]
Hi @atrabattoni! Yes, I'm making a custom tool and put in the tool class definition. It looks like I haven't pushed that specific code so can't access it right now, so can give you a fuller code snippet tonight. For my purposes, I was already making a Bokeh extension so needed custom tools anyway.

**Comment by atrabattoni** [comment]
I'm looking for a quick hack. Do you think it could be possible to run `this.plot_view.canvas.ui_event_bus['hammer'].get("tap").dropRequireFailure("doubletap")`
using a CustomJS callback? The thing is that I don't know how to acces to this ui_event_bus field. In which object should i look ?

**Comment by meson800** [comment]
From a brief glance, I don't know if it is possible to access it through CustomJS.
[CustomJS](https://github.com/bokeh/bokeh/blob/branch-3.1/bokehjs/src/lib/models/callbacks/customjs.ts) inherits from [Callback](https://github.com/bokeh/bokeh/blob/branch-3.1/bokehjs/src/lib/models/callbacks/callback.ts) which inherits from [model](https://github.com/bokeh/bokeh/blob/branch-3.1/bokehjs/src/lib/model.ts), which I don't see any reference or way to easily get back to the event bus. 

In contrast, with the custom tool, the code looks like:
```
export class CustomPolyToolView extends PolyToolView {
  override model: CustomPolyToolView

  override activate(): void {
    console.log("Dropping doubletap failure")
    this.plot_view.canvas.ui_event_bus['hammer'].get("tap").dropRequireFailure("doubletap")
   // Normal PolyToolView code below
    if (!this.model.vertex_renderer || !this.model.active)
      return
    this._show_vertices()
    if (!this._initialized) {
      const cds = this.model.source
      cds.connect(cds.properties.data.change, () => this._show_vertices())
    }
    this._initialized = true
  }

  override deactivate(): void {
    if (this._drawing) {
      this._remove()
      this._drawing = false
    }
    if (this.model.vertex_renderer)
      this._hide_vertices()
   // Normal PolyToolView code above
    console.log("Adding doubletap failure again")
    this.plot_view.canvas.ui_event_bus['hammer'].get("tap").requireFailure("doubletap")
  }
}
```
but that works because [PolyToolView](https://github.com/bokeh/bokeh/blob/branch-3.1/bokehjs/src/lib/models/tools/edit/poly_tool.ts) inherits [EditToolView](https://github.com/bokeh/bokeh/blob/branch-3.1/bokehjs/src/lib/models/tools/edit/edit_tool.ts) inherits [GestureToolView](https://github.com/bokeh/bokeh/blob/branch-3.1/bokehjs/src/lib/models/tools/gestures/gesture_tool.ts) which explicitly sets up the `plot_view` that I am using:
```
  override readonly parent: PlotView

  get plot_view(): PlotView {
    return this.parent
  }
```

That being said, it as helpful for me to drop a `console.log(this)` into my TypeScript to figure out what was happening. If you open the DevTools console, you can poke around the rendered version of the object and see if you can backtrack your way back to a [Canvas](https://github.com/bokeh/bokeh/blob/branch-3.1/bokehjs/src/lib/models/canvas/canvas.ts) object, since the canvas is what the `ui_event_bus` is connected to. I used this method to find the `plot_view.canvas` object.

**Comment by atrabattoni** [comment]
Sorry for the late response @meson800, I was quite unsuccesfull at finding the canvas through CustomJS and the `console.log(this)` exploration method. Then I used your trick with a custom tool quite similart to what you propose and it worked like a charm! Thank you very much it helped me a lot.
