### ISSUE TITLE
Feature Request: Non-straight edges in networkx graphs

### ISSUE THREAD

**Issue by gmlevin** [bokeh/bokeh#8536]
Support non-straight edges between nodes in the networkx graphs. 
* Quadratic bezier curves would be nice, with a parameter to control the degree of arc. 
* Put a midpoint some fraction of the distance between the two points.
* The direction of the curve should be a function of the direction of the edge, so that if there are two edges (A,B) and (B,A), they don't overlap.

Should be able to add a label to the edge as well, but that should be a separate issue.

And there should be a way to add an arrow at the end. Might need to be offset by some steps, because determining where the edge of the node is could be hard.

Rough code for adding the edge now would be as below. If the interactive graph allows moving the nodes, this would require code in the browser, which is more complex.
```
### Draw quadratic bezier paths
def quad(t, a,b,c) :
    return (1-t)**2*a + 2*(1-t)*t*b + t*t*c

def bezier(p1,p2,width, N):
    steps = [i/N for i in range(N+1)]

    x1,y1 = p1
    x2,y2 = p2
    dx = x2-x1
    dy = y2-y1
    xm = (x1+dx/2+dy*width)
    ym = (y1+dy/2-dx*width)
    return [quad(t,x1,xm,x2) for t in steps], [quad(t,y1,ym,y2) for t in steps]

# assuming that the graph layout has determined the positions
pos = graph_renderer.layout_provider.graph_layout
xs, ys = [], []
for sn, en in G.edges():
    sx,sy = pos[sn]
    ex,ey = pos[en]
    xpath, ypath = bezier(pos[sn], pos[en], 0.2, 50)
    xs.append(xpath)
    ys.append(ypath)
graph_renderer.edge_renderer.data_source.data['xs'] = xs
graph_renderer.edge_renderer.data_source.data['ys'] = ys

```

**Comment by bryevdv** [comment]
I'm going to close this discussion as there has been no response. @gmlevin if you can elaborate a more concrete proposal, we can re-open. FWIW the code above seems to suggest generating paths as polylines with a large number of points. This is already possible with the current implementation. If the proposal is only to use existing API in a specific way, I'd suggest that adding a new example is a better route to go. Otherwise, and more impactful idea might be to somehow integrate the exiting Bezier glyphs better, so that only the paramters need to be shipped, not all the many poly line points
