### ISSUE TITLE
Blank page when using Ubuntu 16.04 default tornado version

### ISSUE THREAD

**Issue by VinceDT** [bokeh/bokeh#8540]
Just as as reference for others who have the same problem.
I needed to use bokeh in an environment with system-site packages. When trying out bokeh server examples I just got a blank page. Ultimately the reason was the apt package python-tornado with version 4.2.
In my case I could fix it by uninstalling the python-tornado package, as I did no need it and install a newer one (5.1.1) via pip.

The debug output was helpful to find the error:
```
bokeh serve app_script.py --log-level debug
```

**Comment by bryevdv** [comment]
FYI minimum required dependencies are also documented here: 

https://bokeh.pydata.org/en/latest/docs/installation.html#required-dependencies

Closing this, since there is no particular action to take. However @VinceDT if if you wanted to make a PR to check versions at runtime, we would be happy to consider it. Just note that although Tornado is required to use the Bokeh server, we want the rests of Bokeh to work if Tornado is not installed at all. So just a little care is required to limit tornado imports to specific places.
