### ISSUE TITLE
Bokeh cannot serve notebooks on Python 2

### ISSUE THREAD

**Issue by jlstevens** [bokeh/bokeh#8554]
Using a notebook containing a single code cell (simply  `1+1`) in a Python 2 environment: 

`bokeh serve --show Test.ipynb`

Results in the following error:

```
SyntaxError: encoding declaration in Unicode string
```

Note that this is why the unit tests added in #8546 skip for Python 2.

**Comment by bryevdv** [comment]
This issue is primarily to serve as documentation. I am not averse to considering a PR from anyone interested in contributing a fix for Python 2. However, given the BEP-5 plans for dropping Python 2 support later this year, it is not a priority for @bokeh/core, so I'm closing as `wontfix`. (Can re-open if/when a PR appears)
