### ISSUE TITLE
Fixed tick locations do not affect grid line locations

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#8561]
Using current master it is possible to specify fixed tick locations using the FixedTicker, however I would have expected that these fixed tick locations also determine the locations of the gridlines. Instead the tick locations and the grid lines are completely independent in this configuration. I do not think this behavior is desirable so it would be nice that at least by default the grid lines respect the fixed tick locations.

To illustrate the issue, in the plot below I would have expected the x-axis gridlines to align with the four ticks at 0.25, 0.75, 1.25 and 1.75:

![bokeh_plot](https://user-images.githubusercontent.com/1550771/51051602-32204c80-15cc-11e9-989f-7085c8e36294.png)

This problem was noted in the original issue that led to the introduction of the FixedTicker: https://github.com/bokeh/bokeh/issues/2548

**Comment by bryevdv** [comment]
Well this is because `Grid` has its own individually configured `ticker`. Arguably it might be preferable for `Grid` to be configured with an `Axis` so that it could delegate to the Axis's ticker. But then how do you allow for the case where someone *doesn't* want them synchronized? And how could this be changed in a compatible way? It seems like it might need to be a 2.0 kind of thing.

I think the only option in the short term might some convenience method like `set_ticker_for_grid_and_axis(...)` to explicitly coordinate things, or else a `grid.sync_ticker_to_axis`

**Comment by philippjfr** [comment]
Personally I'd be fine deferring this to 2.0 and then defaulting to mirroring the Axis ticker, but allowing a separate ticker. For our usage I'm happy to syncing the tickers manually for the time being (I didn't actually know about the separate Grid ticker).

**Comment by carlosrobelli** [comment]
I'm running into this same issue - how can I align the Gridlines with the Tickers manually?

**Comment by philippjfr** [comment]
@carlosrobelli This worked for me:

```python
plot.xgrid[0].ticker = plot.xaxis[0].ticker
plot.ygrid[0].ticker = plot.yaxis[0].ticker
```

**Comment by bryevdv** [comment]
As of Bokeh 1.4 this slightly simpler version should also work:

```
plot.xgrid.ticker = plot.xaxis.ticker
plot.ygrid.ticker = plot.yaxis.ticker
```
@philippjfr do you have a proposal for how this could be improved for 2.0? 

I supposed `Grid` could be configured with a `.axis` property, in which case it delegates to the axis' ticker or with an explicit `.ticker` that would override the axis.
