### ISSUE TITLE
subprocess.call('bokeh serve --show Project') [WinError 2]

### ISSUE THREAD

**Issue by tompwd** [bokeh/bokeh#8576]
Calling subprocess.call('bokeh serve --show Kodiak') within project main.py script throws FileNotFoundError: [WinError 2] The system cannot find the file specified error

Printing current directory using os.getcwd() shows directory that Kodiak (project name) is in. So directory is correct, but file cannot be found.

When 'bokeh serve --show Kodiak' is run directly in python it will run, and previously also ran in the script, but now will only run when directly called in python not through subprocess in script

Version List
bokeh version - 1.04
python version - v3.6.5:f59c0932b4 (64bit)
windows 10 version 10.0.17134

Example Code:
```
from bokeh.models.widgets import Tabs, Panel
from bokeh.io import curdoc
import os
import subprocess

tab1 = Panel(title='Pressure') # blank panel just for example
tab2 = Panel(title='Temp') # blank panel just for example

tabs = Tabs(tabs = [tab1, tab2])
curdoc().add_root(tabs)

user = os.getlogin()
thisRepo = r'C:\Users\' + user + '\1 - Projects' 
        ''' (location of 'Kodiak' Project folder which contains main.py '''

os.chdir(thisRepo)
print(os.getcwd()) ''' shows im in correct directory'''
subprocess.call('bokeh serve --show Kodiak')

```
Traceback (most recent call last):
  File 'C:\Users\USERNAME\1 - Projects\Kodiak\main.py", line 23, in <module>
    subprocess.call('bokeh serve --show Kodiak')
  File "C:\Users\USERNAME\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\USERNAME\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\USERNAME\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by bryevdv** [comment]
I think this basically the same underlying issue as #8529, so I am going to close as a duplicate. 

For reference, it's likely `bokeh.exe` is the actual executable file on Windows platforms, and AFAIK this is just how entry points have to work on Windows. I'd love for any Windows experts to contribute guidance or best practices, though. 

In any case, I think you can either:

* use `bokeh.exe` instead of `bokeh` when executing programmatically on Windows, or
* execute `python -m bokeh serve ...` instead
