### ISSUE TITLE
OpenURL in current tab

### ISSUE THREAD

**Issue by aparamon** [bokeh/bokeh#8671]
* Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
* Google Chrome Version 72.0.3626.109 (Official Build) (64-bit)
* Bokeh 1.0.2

Currently, [bokeh.models.OpenURL](https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/callbacks.html#openurl) always opens page in a new browser window/tab. It is proposed that `bokeh.models.OpenURL()` gains additional option to open in current tab, with implementation using [window.open(url,"_self")](https://stackoverflow.com/questions/40316017/openurl-in-bokeh-open-in-same-tab) or (better) [window.location.href](https://stackoverflow.com/questions/4813879/window-open-target-self-v-window-location-href).

**Comment by bryevdv** [comment]
@aparamon Offhand I'd actually be more inclined to get rid of `OpenURL` some day, since anything it does could also be done with a `CustomJSCallback`. So, adding features to it is not at all a priority in my mind. Howervet, if you would like to submit a PR to add this, we would consider it and mosts likely merge it. (If you are *not* interested in working on it, please let us know so we can close the issue)
