### ISSUE TITLE
Custom CSS not working in bokeh-1.1.0dev6 

### ISSUE THREAD

**Issue by samirak93** [bokeh/bokeh#8674]
I've created a custom CSS for modifying styles of dropdown buttons. I'm using bokeh-1.1.0dev6 version and in the output, I can see that the CSS styles are not reflecting. This was working fine till version 1.0.4. Is this something related to the recent update in layouts?

The CSS code is below:

```
.bk-root {
    font-family: georgia;
    font-size: 10pt;
    position: relative;
    width: auto;
    height: auto;
}
.bk-root .bk-widget-box {
    overflow: visible;
    padding: 10.1px 15px;
}

.bk-root .bk-widget label {
    margin-bottom: 2px;
}

.bk-root .bk-widget select {
    min-width: 50%;
}
.bk-root .bk-widget-form-input {
    -moz-appearance: none;
	font-family: georgia;
    font-size: 9pt;
    display: block;
    padding: 0;
    height: 30px;
    color: whitesmoke;
    background-color: #05b7ff;
    border: 1px solid #ccc;
    border-radius: 40px;
    border-color: whitesmoke;
}

.bk-root .bk-bs-btn-default.bk-bs-active{
    color: whitesmoke;
    background-color: #05b7ff;
    border-color: whitesmoke;
      -webkit-appearance: none;
}

.bk-root .bk-bs-btn-default {
    color: #333;
    background-color: whitesmoke;
    border-color: #ccc;
    margin-top: 17px;
}

```

#### Screenshots:

**Expected output**: ![img](https://files.gitter.im/samirak93/N74U/image.png)

**Current output**: ![img](https://files.gitter.im/samirak93/hJYe/image.png)

Thanks.

**Comment by bryevdv** [comment]
@mattpap I expect some css selectors changed recently? We should try to provide guidance

**Comment by mattpap** [comment]
CSS selectors changed, in particular due to removal of bootstrap, but in general widgets (controls) are almost a complete rewrite for 1.1. Some of the classes were preserved, but without `bs-` secondary prefix. What's more important, DOM structure has changed, which implies that semantics of most of the classes changed as well. They main reason I kept any CSS classes is due to limitations on the CSS-JavaScript boundary (some things can only be specified in a stylesheet and need to be referenced by a class).

At this point I don't have any good advice, except that this stylesheet has to be updated to match new widgets. What we should do, is to either provide an API for styling widgets, or allow to do this via CSS, but in a structured and controlled manner, explicitly defining what, how and to what extend can be modified (e.g. it's never a good idea to touch `display` property).

**Comment by cuxcrider** [comment]
@mattpap I am trying to add some customization to buttons and am following this example exactly (https://stackoverflow.com/questions/43057328/change-colour-of-bokeh-buttons) but it does not seem to work.  Should there be some modifications to the code?  I am using the latest bokeh 1.1.0.  Thanks!

**Comment by cuxcrider** [comment]
I also tried a slightly different example found here:  https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/VG94SmNMWj0

but the best I can do is get a button with a clear background.  It seems to actually be searching the template file because I had a typo that triggered an error, but it just is not actually using the style.  Maybe it is related to the bs- prefix you mention?

**Comment by samirak93** [comment]
**Update.** 
The css for buttons and select seem to be working now in 1.1.0. I'd try other widgets and provide an update soon. 


<img width="500" alt="image" src="https://user-images.githubusercontent.com/22864480/58147650-6528bb80-7c10-11e9-993a-f76fd8b77f50.png">

**Code:** 

```

.bk-root .bk-btn-default {
    color: black;
    font-size:12pt;
    background-color: #05b7ff;
    border-color: #05b7ff;
}

.bk-root .bk-input {
    display: inline-block;
    width: 100%;
    flex-grow: 1;
    -webkit-flex-grow: 1;
    min-height: 31px;
    padding: 0 12px;
    background-color: #05b7ff;
    border: 1px solid #ccc;
    border-radius: 4px;
}
```

**Comment by cuxcrider** [comment]
@samirak93 thank you very much.  I'm very new to css and html, would you mind providing your index html code and bokeh .py so I can see how you are supposed to reference all of them.  For example in the .py code for the button, how should I reference the css class.  I've been trying: button = Button(label = "Test Button", css_classes = ['bk-btn-default'])

I can inspect my code on Chrome and see my style sheet but seems like it is just replaced by the default Bokeh style.  Clearly I'm doing something wrong...

**Comment by cuxcrider** [comment]
@samirak93 I seem to have got it, maybe a little differently than you did.  I'm not sure of the pros/cons. 
My file structure is buttonBokeh/templates

 Here is my buttonBokeh/main.py code:


```
from bokeh.layouts import layout
from bokeh.plotting import curdoc
from bokeh.models import Button

button = Button(label = "Test Button", css_classes =['custom_button_bokeh'])
layout = layout([[button]])
curdoc().add_root(layout)
```

And here is buttonBokeh/templates/index.html
```
<!DOCTYPE html>
<html lang="en">
    <head>
      <meta charset="utf-8">
      {{ bokeh_css }}
      {{ bokeh_js }}
      <style type="text/css">{% include 'styles.css' %}</style>
    </head>
    <body>
      {{ plot_div|indent(8) }}
      {{ plot_script|indent(8) }}
    </body>
</html>

```
And here is the buttonBokeh/templates/styles.css
```
.custom_button_bokeh button.bk.bk-btn.bk-btn-default {
    color: black;
    font-size:12pt;
    background-color: #05b7ff;
    border-color: #05b7ff;
}
```
I run it with:  
bokeh serve --allow-websocket-origin=ip_address:xxxx buttonBokeh --port xxxx

**Comment by bryevdv** [comment]
I'm not sure there is any action to take here, CSS targets are stabilizing over time but still subject to development.
