### ISSUE TITLE
Don't warn on empty layouts

### ISSUE THREAD

**Issue by jsignell** [bokeh/bokeh#8725]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
```
Python version      :  3.6.7 | packaged by conda-forge | (default, Nov 20 2018, 18:37:09)
IPython version     :  7.2.0
Tornado version     :  5.1.1
Bokeh version       :  1.1.0dev9+2.g1138433
BokehJS static path :  /Users/jsignell/conda/envs/bokeh-dev/lib/python3.6/site-packages/bokeh-1.1.0.dev9+2.g1138433-py3.6.egg/bokeh/server/static
node.js version     :  v11.6.0
npm version         :  6.5.0
```

#### Description of expected behavior and the observed behavior
I think that layouts should be allowed to be empty without raising a warning. There is a legitimate use of an empty layout object to create an empty area which can later be appended to or extended. This is especially useful in panel (see issue: https://github.com/pyviz/panel/issues/285) where the layout object will re-render if the children change. 

I understand that it could potentially be confusing if someone were to create an empty layout object and then think that it is just not rendering - but it doesn't seem like that would be terribly common (if it has been in the past, then maybe this warning shouldn't be removed).

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.io import output_notebook, show
from bokeh.layouts import column
from bokeh.models.widgets import Button

output_notebook()

col = column([])
show(col)
```
warning will be displayed

```python
# add a button
button = Button(label='Click me!')
col.children.append(button)
show(col)
```
column will render properly

#### Stack traceback and/or browser JavaScript console output

This is the relevant warning:

https://github.com/bokeh/bokeh/blob/113843391ae24a685c12f04bc57cb2404df56155/bokeh/core/validation/warnings.py#L13-L14

#### Screenshots or screencasts of the bug in action

This is the warning:

<img width="820" alt="screen shot 2019-03-07 at 8 57 03 am" src="https://user-images.githubusercontent.com/4806877/53962228-86214c00-40b8-11e9-94bd-c9e1cff00eb9.png">

And this is the column rendering properly after adding an item to it:
<img width="817" alt="screen shot 2019-03-07 at 8 58 31 am" src="https://user-images.githubusercontent.com/4806877/53962235-891c3c80-40b8-11e9-8459-0c958a96784f.png">

**Comment by jbednar** [comment]
Personally, I think that empty containers should almost never be considered an error condition.  They come up in many legitimate situations, such as dynamically constructing plots based on a query or external file, as temporaries that will later have things put in them, as placeholders for items that may or may not turn out to be available, as the limiting case to various algorithms, and so on.  I can imagine some cases where this warning would be helpful to a user, but there are so many cases where it is inappropriate and forces users into awkward approaches to avoid the warning.  So I vote for disabling the warning by default.

**Comment by mattpap** [comment]
This is something that was carried over from the old layout. I will remove this warning.

**Comment by bryevdv** [comment]
Well, my original intent was to make various warnings individually on/off configurable so then things like HV could turn them off if that made sense. But that has not happened as of yet. FWIW this warning was specifically added in response to a bunch of "why is my page empty?" support questions, to try and give users immediate actionable feedback that would save them from making an issue or ML/SO question. So removing it entirely is asking us to assume the burden of explicitly handling those reports again. I'd prefer if we are to spend effort, to add the configurability that would let HV disable the ones that don't make sense for it.

**Comment by jbednar** [comment]
I can't quite see what a user would have expected to happen for an empty layout other than having an empty page; what were they hoping for?  And I don't get much out of "Layout has no children".  So I'll have to defer to your judgment and painful experience with that. :-)

**Comment by bryevdv** [comment]
> I can't quite see what a user would have expected to happen for an empty layout other than having an empty page

They were not *intending* to show empty layouts, they just had happened to, by some mistake.

**Comment by jsignell** [comment]
If you guys have experienced pain from this before then I think it makes perfect sense to just make the disabling of warnings easily configurable. That is a more general solution anyways since there will likely be other situations in which what is right for bokeh users isn't necessarily right for downstream projects.

**Comment by bryevdv** [comment]
@jsignell do you want to make a PR? I think it should be fairly straightforward, e.g. just an internal set of warning numbers to silence (added/remove via some API) that gets checked before a warning is emitted.

**Comment by jsignell** [comment]
Sure I will take a stab at it.

**Comment by mattpap** [comment]
I will have to disagree, because warning about something that's perfectly valid or even encouraged in the new layout (grids with track specs and no children), is wrong in my opinion. It's even worse to make it configurable, but on by default. This will encourage users to just disable warnings altogether and risk not being informed about something important (actually wrong, but not critical). I would reverse the logic and let users know by default only about actual problems, and provide them with a mode in which any potential issues would be pointed out and explained. This way users who know what they are doing wouldn't be annoyed and others would still get the help needed to figure out any issues. This could actually solve some of bokeh's performance issues, because we could do less validation by default, but allow very robust validation upon request. Anyway, that's a significant chunk of work, so I suppose it's outside the scope of this issue.

**Comment by jbednar** [comment]
That's an interesting idea -- you could have the Bokeh issue template suggest that users turn on this special verbose mode before they report an issue, because the messages may help them discover the problem themselves.

**Comment by bryevdv** [comment]
The crux of the matter is that I strongly suspect that the number of people legitimately intending to show an empty layout is minuscule [1] compared to a much greater occurrence of people unintentionally showing an empty layout left wondering why they are staring at an empty screen with no guidance or feedback. In which case we are optimizing for the wrong (uncommon) case.

[1] Case in point, it is basically never useful to show an empty layout for any standalone, non-server case, because there is no way to update and add anything after the fact. Most usage is non-server.
