### ISSUE TITLE
Embed bokeh figure in wxPython

### ISSUE THREAD

**Issue by baderAmmoun** [bokeh/bokeh#8735]
# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

```

**Comment by bryevdv** [comment]
This issue is lacking every piece of information requested, which is reason enough to close it. However,  based off the title, I will add that Bokeh explicitly does not test on/support wxWindows (it may work, it may not, I don't know). Official support for wxWindows would require a new contributor to agree to make on the time and work commitment to take on the role of maintainer for that.
