### ISSUE TITLE
How can i update Bokeh canvas in front end

### ISSUE THREAD

**Issue by FengHuangDong** [bokeh/bokeh#8768]
```
item = JSON.parse(item_text);
Bokeh.embed.embed_item(item, "myplot");
```
Is there an API to update canvas when I dynamically change **item** in the front end after bokeh generation?

My current solution
```
document.getElementById("myplot").innerHTML = ''
Bokeh.embed.embed_item(newItem, "myplot");
```

Is there a better solution?

**Comment by bryevdv** [comment]
As stated in the issue template, the GitHub issue tracker is reserved for bug reports and feature requests only. It is not the appropriate place to seek general support or help with usage questions. For that, please consider [Stack Overflow](https://stackoverflow.com/) or the [public mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh). To increase the chance that someone will decide to volunteer their time to help, always include as much information and detail as possible. *Most especially: a minimal, **complete** code sample*.

**Comment by bryevdv** [comment]
Further mailing list discussion yields that this is really a feature request.

**Comment by FengHuangDong** [comment]
@bryevdv 
To add a scene:
```
Bokeh.embed.embed_item(item, "myplot");
console.log(window.Bokeh.index("myplot")) //undefined
```
When should I get the bokeh model through index? maybe need a callback?

**Comment by bryevdv** [comment]
cc @mattpap is better informed about this side of BokehJS than I am. The problem statement is: how can we help better BokehJS users obtain a reference to a plot e.g. that they have embedded, so that they can update by setting properties. It's possible there is already a good path to do this but it just needs documentation, or maybe BokehJS could use some dev work. This issue is to discsuss that.

**Comment by bryevdv** [comment]
This was addressed in https://github.com/bokeh/bokeh/pull/9604
