### ISSUE TITLE
Support scale factor for PNG output

### ISSUE THREAD

**Issue by geekonloose** [bokeh/bokeh#8807]
# This is feature request:
I know that Bokeh has acquired png saving capability. However, As far I know, it does not have way to specify to save at exact resolution (in dpi) like matplotlib. This is crucial for scientific community where, most of publication houses asks for higher dpi resolution graphs.
I hope I have not offended 'issue' guidelines.

**Comment by rysport** [comment]
I'm all for your suggestion, but if you're going to publish your plots you are probably better off [exporting them vectorized (svg)](https://bokeh.pydata.org/en/latest/docs/user_guide/export.html), and adding any labels etc. in Inkscape or similar.

**Comment by bryevdv** [comment]
@geekonloose DPI is a function of the physical size the image is printed/displayed at. Bokeh has n0 ability to control or dictate that. You can already set the image resolution of exported imaged via the `width` and `height` parameters to `export_png`. It i s up to you to set the width and height appropriately, to obtain the DPI you want, given the physical size the image will ultimately have (which only you know).

**Comment by stas-sl** [comment]
Here is a workaround to get high DPI png screenshots. You have to create manually webdriver instance with `--force-device-scale-factor=2` and remove image resizing here:
https://github.com/bokeh/bokeh/blob/de08fb161b4b9e3dcf52de61d76ef8e4a294d529/bokeh/io/export.py#L246

```python
import io
import tempfile

from typing import Optional
from PIL import Image
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from bokeh.plotting import figure, show, output_notebook
from bokeh.sampledata.penguins import data
from bokeh.transform import factor_cmap, factor_mark
from bokeh.io import export_png, export_svg
from bokeh.io.export import get_screenshot_as_png
from bokeh.resources import INLINE, Resources
from bokeh.io.export import wait_until_render_complete, _maximize_viewport, get_layout_html

output_notebook()

def get_screenshot_as_png_highdpi(obj, *, driver=None, timeout: int = 5,
        resources: Resources = INLINE, width: Optional[int] = None, height: Optional[int] = None) -> Image.Image:

    with tempfile.NamedTemporaryFile(suffix='.html', mode='w', encoding="utf-8") as f:
        html = get_layout_html(obj, resources=resources, width=width, height=height)
        f.write(html)

        driver.maximize_window()
        driver.get(f"file://{f.name}")
        wait_until_render_complete(driver, timeout)
        [width, height, dpr] = _maximize_viewport(driver)
        png = driver.get_screenshot_as_png()

    return (Image.open(io.BytesIO(png))
                 .convert("RGBA")
                 .crop((0, 0, width * dpr, height * dpr)))

options = Options()
options.add_argument('--no-sandbox')
options.add_argument('--headless')
options.add_argument('--no-first-run')
options.add_argument('--disable-gpu')
options.add_argument('--force-device-scale-factor=2')

driver = webdriver.Chrome(options=options)

SPECIES = sorted(data.species.unique())
MARKERS = ['hex', 'circle_x', 'triangle']

p = figure(title = "Penguin size", background_fill_color="#fafafa", width=300, height=300)
p.xaxis.axis_label = 'Flipper Length (mm)'
p.yaxis.axis_label = 'Body Mass (g)'

p.scatter("flipper_length_mm", "body_mass_g", source=data,
          legend_group="species", fill_alpha=0.4, size=8,
          marker=factor_mark('species', MARKERS, SPECIES),
          color=factor_cmap('species', 'Category10_3', SPECIES))

p.legend.location = "top_left"
p.legend.title = "Species"

get_screenshot_as_png_highdpi(p, driver=driver).save('plot.png')
```

Here is the difference:

300x300 low DPI:
![plot_300x300_lowdpi](https://user-images.githubusercontent.com/4602302/151698736-32d87aaf-e913-48de-adbe-4b0cddddc940.png)

600x600 high DPI: (it is impossible to get this quality with current `get_screenshot_as_png` implementation)
![plot_600x600_highdpi](https://user-images.githubusercontent.com/4602302/151698738-2aa49fa0-cecc-4e7b-a1a6-312db4f929ef.png)

600x600 low DPI: (yes, it is twice as large but isn't sharp on retina displays)
![plot_600x600_lowdpi](https://user-images.githubusercontent.com/4602302/151698739-cd519534-e29d-498c-ad08-75d779b10b95.png)

Related issue: https://github.com/bokeh/bokeh/issues/11769
Related PR: https://github.com/bokeh/bokeh/pull/9675 (@mattpap)

Although there is a workaround, of course I vote for an additional parameter in the `export_png/get_screenshot_as_png` function (whether it would be `scale_factor ` or `dpi` or `pixel_ratio`).

**Comment by bryevdv** [comment]
@stas-sl Are you interested to make a PR to add a `scale_factor` argument to the export API functions? We would need to make sure it works with both chrome and FF as the browser backend (or else add appropriate docs and explicit warnings in case of non-workable configurations)

**Comment by golmschenk** [comment]
In case others need a solution, a workaround I have been using is to export to SVG and use a third party library (`cairosvg`) to convert the SVG to a higher resolution PNG.

Example:
```python
from bokeh.io import export_svg, export_png
from bokeh.plotting import figure as Figure
from cairosvg import svg2png

figure = Figure()
figure.scatter(x=[1, 2, 3], y=[1, 2, 3])

export_png(figure, filename='low_resolution_output.png')

figure.output_backend = 'svg'
export_svg(figure, filename='temporary.svg')
svg2png(url='temporary.svg', write_to='high_resolution_output.png', scale=2.5)
```

**Comment by stas-sl** [comment]
One of the reasons why I wanted to export some plots as png was that they had lots of data (~100K points) and svgs probably will be huge in that case as well, while pngs are more or less have fixed size.

**Comment by London38** [comment]
![imagen](https://user-images.githubusercontent.com/98439553/161897238-27e802d7-70dc-43e2-a63b-177faa6aefd9.png)
@bryevdv  @stas-sl  Also extra y axis has more resolution than normal x and y axis as is shown in the image.
I thought I was getting blind ;/

Hope ya guys take a look at this in the future ;)
Thanks for your efforts

**Comment by bryevdv** [comment]
@London38 For PNG output, Bokeh ultimately just calls the HTML canvas [`ctx.fillText`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillText) method with the text to render. Everything beyond that is out of our control. SVG output might be a better option if the PNG results are not suitable for your use-case.

**Comment by bryevdv** [comment]
I've reopened this with a new title. In case anyone wants to take a stab at implementing @stas-sl  earlier idea, a reminder of what is needed:

> add a scale_factor argument to the export API functions? We would need to make sure it works with both chrome and FF as the browser backend (or else add appropriate docs and explicit warnings in case of non-workable configurations)

This is a (somewhat rare) purely Python task, so it is really an excellent opportunity for someone new to decide to become involved without having to dive into BokehJS.

**Comment by London38** [comment]
`import random
from bokeh.io import output_notebook
# Call once to configure Bokeh to display plots inline in the notebook.
output_notebook()
from bokeh.plotting import figure, show
from bokeh.models import ( 
                      Range1d,
                      LinearAxis,
                      )
def random_timeseries(initial_value: float, volatility: float, count: int) -> list:
    time_series = [initial_value, ]
    for _ in range(count):
        time_series.append(time_series[-1] + initial_value * random.gauss(0, 1) * volatility)
    return time_series

a=20000 #20
b=50000 #50
ts_ybot = random_timeseries(a, 0.15, b)
ts_x = list(range(0, len(ts_ybot)))
ts_ytop = [i*5 for i in ts_ybot]

p = figure(#width=1200, height=500,
           sizing_mode= 'stretch_both',
           toolbar_location='left',
           y_axis_location= 'right',
           background_fill_color = 'black',
           background_fill_alpha = 1,
           border_fill_color = 'black',
           min_border_left = 80)
   # X Axis color
p.xaxis.axis_line_color = 'white'
p.xaxis.major_label_text_color = 'white'
p.xaxis.major_tick_line_color= 'white'
p.xaxis.minor_tick_line_color= 'white'
    # Y Axis color
p.yaxis.axis_line_color = 'white'
p.yaxis.major_label_text_color = 'white'
p.yaxis.major_tick_line_color= 'white'
p.yaxis.minor_tick_line_color= 'white'
    #X Axis label color
p.xaxis.axis_label_text_color='white'
    # Y Axis label color
p.yaxis.axis_label_text_color='white'
    # X date rientation
p.xaxis.major_label_orientation= 1.5708
p.xaxis.axis_label= 'ABCDEFGHYJKL'
p.xaxis.axis_label_text_color='white'
    # Y Title and color
p.yaxis.axis_label= 'ABCDEFGHYJKL'
p.yaxis.axis_label_text_color='white'


p.extra_y_ranges = ({'a': Range1d(start= min(ts_ybot), end= 3*max(ts_ybot))})
p.add_layout(LinearAxis(y_range_name='a',
                        axis_line_color = 'white',
                        major_label_text_color = 'white',
                        major_tick_line_color= 'white',
                        minor_tick_line_color= 'white',
                        bounds = (min(ts_ybot), max(ts_ybot)),
                        axis_label='ABCDEFGHYJKL',
                        axis_label_text_color='white'), 
             'left'
             )
#p.line(x= ts_x, y= ts_ytop,  line_color= 'pink', line_width= 50)
p.vbar(x=ts_x, top=ts_ytop, bottom=0, color= 'red')    
p.line(x= ts_x, y= ts_ybot, line_color= 'yellow', line_width= 1, y_range_name='a')
show(p)
`
width=1200, height=500
![imagen](https://user-images.githubusercontent.com/98439553/162056742-d3af8d66-9a0d-4089-9390-5fcc1b52f960.png)

sizing_mode= 'stretch_both'
![imagen](https://user-images.githubusercontent.com/98439553/162058492-4d015982-2a32-484b-8b37-6a94dd2e842a.png)

 width=1200, height=500 with big numbers
![imagen](https://user-images.githubusercontent.com/98439553/162073142-6ae41342-9efa-441e-8c53-35ada5d35cb9.png)

sizing_mode= 'stretch_both' with big numbers
![imagen](https://user-images.githubusercontent.com/98439553/162074064-7b650fd0-34d4-4ad8-9976-f4b247cbc5c0.png)

@bryevdv It seems the problem is when sizing_mode= 'stretch_both' is used when there are big numbers, also the color of Extra Y Axis dissapear like its shown in the image

**Comment by bryevdv** [comment]
@London38 You did not provide any of the details I mentioned:

> [1] Is this with Chome? Or FF? On Windows or Linux or Mac? What Bokeh version? What browser version? What Selenium version? What OS version? What font was specified? Literally any and all of these things could be responsible for differences in low-level of canvas rendering.

I'm not sure how I can make it clearer: this is very likely a ***highly platform specific issue***. Those details *matter* and we can't how to do or say anything without the. 

*All that said*, I don't actually think this has anything to do with the issue at hand, since you aren't actually exporting anything, and this issue is about exports. To help keep our tracker organized, I'd kindly ask that you:

* Make a brand new issue
* With code and ***All relevant platform details***
* Link to this issue, then delete the comments here
