### ISSUE TITLE
RadioButtonGroup orientation vertical

### ISSUE THREAD

**Issue by bjarthur** [bokeh/bokeh#8847]
with v1.0 i was able to create vertically oriented RadioButtonGroups by constraining them to a certain width with `widgetbox(RadioButtonGroup(...), width=50)`.  no longer in v1.1.

the `orientation` field in RadioButtonGroup does not help, nor do it's `width` or `max_width` fields.

here is a screenshot with the default orientation of "horizontal":

<img width="823" alt="Screen Shot 2019-04-16 at 11 38 16 AM" src="https://user-images.githubusercontent.com/1538268/56223807-77756f80-603c-11e9-9b86-c5bae4aec6b0.png">

and here with it set to "vertical":

<img width="816" alt="Screen Shot 2019-04-16 at 11 39 27 AM" src="https://user-images.githubusercontent.com/1538268/56223814-79d7c980-603c-11e9-98d8-ae998b7435a3.png">

is there a workaround?  thanks.

**Comment by mattpap** [comment]
> `widgetbox(RadioButtonGroup(...), width=50)`

This may have visually worked to some extent, but it wasn't intended to. Button groups were horizontal by design. `orientation` was added in 1.1 to all widgets, but more due to technical limitations than a feature (only sliders take advantage of it). However, vertical orientation can be implemented in button groups.
