### ISSUE TITLE
[BUG] Legend click_policy "mute" not working

### ISSUE THREAD

**Issue by tony-bony** [bokeh/bokeh#8852]
**ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)**

```
Python version      :  2.7.15 (default, Oct  4 2018, 22:42:40) 
IPython version     :  5.8.0
Tornado version     :  4.5.3
Bokeh version       :  1.1.0
BokehJS static path :  /usr/local/lib/python2.7/site-packages/bokeh/server/static
node.js version     :  v10.15.1
npm version         :  6.7.0
```

```
OS: Mac OS X Yosemite 10.10.5
Browser: Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)
```

**Description of expected behavior and the observed behavior**
The glyphs should mute when legend is clicked

**Complete, minimal, self-contained example code that reproduces the issue**
```
from bokeh.plotting import figure, show

p = figure()
l1 = p.line([1, 2, 3, 4, 5], [14, 16, 11, 12, 17], legend = 'Mute')
p.legend.click_policy = "mute"

show(p)
```

**Comment by bryevdv** [comment]
@tony-bony users want different things to happen when muting, so bokeh does not impose any decisions of its own. It is up to you to specify e.g. a muted alpha value:
```
l1 = p.line([1, 2, 3, 4, 5], [14, 16, 11, 12, 17], line_width=3, legend = 'Mute', muted_alpha=0.3)
```

<img width="604" alt="Screen Shot 2019-04-19 at 8 15 24 AM" src="https://user-images.githubusercontent.com/1078448/56430532-7716e780-627b-11e9-9e8f-8f15c4991bb9.png">

This is demonstrated in the documentation:

https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/legends.html#muting-glyphs

**Comment by Dr-Nuke** [comment]
legend click_polcy 'mute' has no effect on stacked bar plot

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh                     2.0.0
python                    3.7.7
jupyterlab                1.2.6
WSL Ubuntu 18.04
Firefox 74.0 (64-bit)
Chrome Version 79.0.3945.117 (Official Build) (64-bit)
Microsoft Edge 44.18362.449.0

#### Description of expected behavior and the observed behavior
the bar patches should fade partially

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.io import output_file, show
from bokeh.plotting import figure

output_file("stacked.html")

fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']
years = ["2015", "2016", "2017"]
colors = ["#c9d9d3", "#718dbf", "#e84d60"]

data = {'fruits' : fruits,
        '2015'   : [2, 1, 4, 3, 2, 4],
        '2016'   : [5, 3, 4, 2, 4, 6],
        '2017'   : [3, 2, 4, 4, 5, 3]}

p = figure(x_range=fruits, plot_height=250, title="Fruit Counts by Year",
           toolbar_location=None, tools="")

p.vbar_stack(years, x='fruits', width=0.9, color=colors, source=data,
             legend_label=years)

p.y_range.start = 0
p.x_range.range_padding = 0.1
p.xgrid.grid_line_color = None
p.axis.minor_tick_line_color = None
p.outline_line_color = None
p.legend.location = "top_left"
p.legend.orientation = "horizontal"
p.legend.click_policy="mute"

```

#### Stack traceback and/or browser JavaScript console output

no error output

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/56429408/77860503-0b215b00-7210-11ea-9984-16d1ffa7267e.png)

**Comment by bryevdv** [comment]
@Dr-Nuke this is not the issue I linked as a duplicate?

**Comment by tony-bony** [comment]
I think more people will come with the same issue.  
This is because they set `legend.click_policy="mute"` and nothing happens.

Bokeh sets dozens of default values when creating a plot (e.g. `plot_width`, `line_color`etc...) or when adding certain functionalities (e.g. `callback_policy` is set default to `continuous` when adding a callback to slider widget, etc...)

So I think it would be really beter to set the `muted_alpha` by default to e.g. 0.5 so people see it works.
