### ISSUE TITLE
Thoughts on DataFrame input data for chart.Scatter

### ISSUE THREAD

**Issue by chdoig** [bokeh/bokeh#886]
Right now to perform a Scatterplot using the charts.Scatter, there are three ways to pass the data:
-OrderedDict
-DataFrame
-GroupBy object

In the case of the DataFrame, you have to pass a concat DataFrame that looks something like this:
![screen shot 2014-07-24 at 3 29 15 pm](https://cloud.githubusercontent.com/assets/4940549/3694402/df1611ca-1371-11e4-8331-3f0d6593cbfe.png)

Which is not your usual DataFrame. Usually, you'll have a DataFrame that looks something like this:
![screen shot 2014-07-24 at 3 37 31 pm](https://cloud.githubusercontent.com/assets/4940549/3694449/5f60364e-1372-11e4-89b0-99d5fecc6c26.png)

In the case of using the GroupBy object, you'll have to create a new DataFrame by selecting the x and y you want to plot and the categorical variable you want to groupby and then do a groupby and then pass that groupby object to Scatter.

The DataFrame way right now doesn't convince me because its not your usual DataFrame and the GroupBy way seems to have too many steps to get the GroupBy object.
When I think of passing a DataFrame, I think more of doing something like:

`Scatter('x', 'y', 'color=gb')`

That's how you do it with ggplot and matplotlib:
`ggplot(dat, aes(x=xvar, y=yvar, color=cond))`
`scatter(x, y, c=colour)`

I think it would be nice to have a DataFrame way that could work like this:

``` python
Scatter(df['sepal_width'], df['sepal_length'], color=df['species'])
```

**Comment by iyneedham** [comment]
Anders and I have been speaking with Damian, and he suggested that we post on this thread. We thought that what Bryan suggested above was really intuitive: 

```python
Scatter(df, x='sepal_width', y='sepal_length', color='species')
```

Right now, here’s what you need to do to produce a graph where you give bokeh a dataframe and what columns you want to use for x and y: 

```python
import pandas as pd
from bokeh.charts import Bar
import bokeh
bokeh.load_notebook(force=True)
campaign = pd.DataFrame({
'Delivery date': ['9/11/2013', '9/11/2013', '9/18/2013', '10/2/2013', '10/8/2013', '10/15/2013', '10/17/2013', '10/22/2013', '11/8/2013'],
'Google Tracking Code':  ['msag1413e ', 'mss1113e ', 'mss1813e ', 'mso213e ', 'mso813e2 ', 'mso1413e ', 'mssigns13 ', 'sepp102213 ', 'msn813e1 '],
'Visits':  [2777, 3361, 3140, 3111, 2306, 2097, 3135, 1925, 1839],
'Revenue':  [3776, 9606.5, 19269.28, 47121.6, 13271.43, 28417.8, 1285.47, 694.36, 4572],
'Transactions':  [43, 40, 68, 157, 47, 89, 12, 8, 16]
})

campaign2 = campaign.set_index('Google Tracking Code')
values = campaign2.Visits.values
cat = campaign2.index.values.tolist()
Bar(values, cat=cat).title("Email Campaign Results").stacked(True).notebook().show()
```

Imagine that you’re a beginner, and you’re trying to use bokeh to create 4 charts that use different columns for x and y.  You’d have to use 4 lines of pretty intimidating code for every chart. 

We think bokeh produces beautiful graphs, and we want it to become the standard library everyone uses for data visualization in pandas. But based on our work teaching pandas to beginners, we’re concerned that the difficulty of this code will scare off folks.

Is there any chance that Bryan’s approach might be implemented in the next version?

**Comment by damianavila** [comment]
pinging @fpliger who was lately involved in Charts to provide his thoughts :wink:

**Comment by fpliger** [comment]
@iyneedham can you provide some more context? Or an example of how would you like to code the former example?

In the example you've pasted earlier you can change the last 4 lines to:

```Python
cat=list(campaign['Google Tracking Code'])
Bar([campaign["Visits"]], cat=cat, title="Email Campaign Results", stacked=True, notebook=True).show()
``` 
 
with the same results.

**Comment by damianavila** [comment]
I guess the problem comes from the fact that for beginners, or casual user, one expect the following to work:
```python
Bar(campaign["Visits"], cat=campaign['Google Tracking Code'], title="Email Campaign Results", stacked=True, notebook=True).show()
```
and it is not the case because you have to wrap it in a list... and probably, for beginners, this is not something easier to figured out...

**Comment by fpliger** [comment]
Sure, I do agree. In fact it should work (at least it works with some charts like bar or lines that I've just tried). :wink: 

What I'm not sure is about @iyneedham proposal. Mostly because I miss real examples. Also because @bryevdv suggestion was based on the Scatter chart which is probably the chart we have with the most "custom" input structure (that's why it also accepts GroupBy objects). For scatter I understand the need but not for Bar, Line or other charts...

**Comment by iyneedham** [comment]
Thanks, @fpliger.

What @damianavila suggested would definitely be an improvement.  What would be even better, though, is something like this:

```python
Bar(campaign, x='Visits', y='Google Tracking Code', title="Email Campaign Results", stacked=True, notebook=True).show()
```

Again, this mirrors @bryevdv ‘s scatterplot suggestion.  Even though scatter plots are different from bar charts, what we find so appealing about this is that it uses x and y, which is how most people learn how to graph.

**Comment by aschneiderman** [comment]
To give you a little more context, I sent the code from @fpliger to a friend who's done a lot of grassroots economic training for adults:
```python
cat=list(campaign['Google Tracking Code'])
Bar([campaign["Visits"]], cat=cat, title="Email Campaign Results", stacked=True, notebook=True).show()
```
She wrote back:
> ???

Then I sent her code that looked like @iyneedham's:
```python
Bar(campaign, x='Visits', y='Google Tracking Code', title="Email Campaign Results", notebook=True).show()
```
She wrote back:
> that I could teach

For folks like yourself who are skilled coders, I could definitely see how the difference between the code might seem small, but for a different audience it's pretty significant.  And since I want to empower people to make the very pretty graphs that bokeh does so well -- and banish icky-looking matplotlib graphs from my life :)  -- it would be fabulous to have

**Comment by bryevdv** [comment]
I'm definitely in favor of having this kind of interface for data frames.

**Comment by fpliger** [comment]
Thanks @iyneedham and @aschneiderman for providing more details. I totally agree with you about empowering people and lowering technical requirements to use Bokeh. That's actually something very important for us and why we are always asking users for feedback (and ourselves) about how to make things easier. 

I DO see a lot value in the proposal. My request for more context was mainly because we have had discussions about *similar* interfaces when trying to define a common interface for charts (#1373 and friends). IIRC we didn't include similar interfaces at that time because it actually needs good thinking to get everything "right". So hearing real use cases would have been a good input for us to thing about the problem. 

Let me explain a bit. Here are a few questions to consider (or at least that I remember we have discussed):

* what input objects should support the x/y attributes? Probably just mapping...
* what types we support for x/y? This is actually very important because if you only support one key (string) means that you limit it to one data series... If you do support iterable(keys) you also [may] need to support multiple indexes, etc...

With that in mind I think it's important to add this kind of interface somehow based on user experience trying to make life easier to users (and not over engineering things which may end up with over complicating things).

**Comment by damianavila** [comment]
> I'm definitely in favor of having this kind of interface for data frames.

> With that in mind I think it's important to add this kind of interface somehow based on user experience trying to make life easier to users (and not over engineering things which may end up with over complicating things).

:+1: even if we have to modify the data-adpater to support this request, I think the benefit are gross compared with the cost associated (obviously, always without over-engineer things).

**Comment by iyneedham** [comment]
@fpliger,

I'm a novice myself and am still learning the requisite terms & concepts. Would you mind giving some concrete examples of the issues you lay out in the questions?  I want to make sure you get the answers you need to think through this and make decisions.

**Comment by fpliger** [comment]
@iyneedham sure. If we introduce x and y we need consider the types of inputs supported by charts now: [1d/2d] lists, arrays, dicts and DataFrames. Those have different indexing behaviours and thus you'd need to handle it. It's not impossible and DataAdapter is already kind of doing this. 
Next consider what we'd like to support with the x/y idiom. 
If we support just scalar values for x and y it means that you will only be able to plot 1 series. This is very limiting.
If we support also iterables for x this solves the problem as user can just pass the keys/index of the series [of your input] that you want to place on your chart. 
But what happens for y? What will accept there? An iterable with decoupled values that defines the y values? A scalar that takes the y values from the related key/index on the charts input? Or even accept an iterable to define more then on series from the input so you can create multiple indexes?

These are just the first obvious things to think about but there may be other some complications. 

Here is the list of concrete examples from the previous code:

```Python
#this should be obvious
Bar(campaign, x='Visits', y='Google Tracking Code', title="Email Campaign Results", stacked=True, notebook=True).show()
# should we accept this?
Bar(campaign, x='Visits', y=['a', 'b', ....'z'], title="Email Campaign Results", stacked=True, notebook=True).show()
# this would create a 2 ranges/axis?
Bar(campaign, x=['Visits', 'Revenue'], y=['Delivery date', 'Google Tracking Code'], title="Email Campaign Results", stacked=True, notebook=True).show()
```
 
Again, I'm in favor of adding interfaces that help user and are more obvious but I just think it's not as trivial as it may seem to "add the best implementation". In that sense I encourage you to open an issue for discussion about the topic (this one have already been closed and is specific to Scatter) and provide as much details as you can about your user POV and use cases.

Thank you very much for your feedback and help.

**Comment by iyneedham** [comment]
@fpliger

We really appreciate all the thought you’ve given this.

In in the interest of 1. user friendliness and 2. avoiding over-engineering, we think  that simpler is better, at least for this round.   Based on our experience, most beginners are either using Excel or using tools that were designed with Excel users in mind. So they would only really need--or understand--DataFrames.  

If you could enable the first example:  

```python
Bar(campaign, x='Visits', y='Google Tracking Code', title="Email Campaign Results", stacked=True, notebook=True).show()
```
and perhaps even the second:

```python
Bar(campaign, x='Visits', y=['a', 'b', ....'z'], title="Email Campaign Results", stacked=True, notebook=True).show()
```

and make these two examples work just for DataFrames for a variety of basic graphs—e.g. scatter, line, bar—in the next version, bokeh would become considerably easier to use and teach others how to use.

Re: opening another issue discussion -- How about we hold off until these examples have been implemented? I know that there are a lot of potentially complex issues. But if you want to avoid over-engineering while making bokeh more accessible, we are positive that just these two changes would make a huge difference.

**Comment by fpliger** [comment]
Thanks for the feedback @iyneedham . Added a related issue #1841
