### ISSUE TITLE
Glyph angle not respected in legend

### ISSUE THREAD

**Issue by poplarShift** [bokeh/bokeh#8891]
Glyphs' `angle` is not respected in legend. This is on bokeh 1.1.0.

Same as #4694, which was supposedly fixed by #5689, so I assume there's been a regression since then?

![image](https://user-images.githubusercontent.com/38992106/57142368-545ff500-6d8a-11e9-8099-ee6065a4c48a.png)

```
import bokeh.plotting                                                              
from bokeh.plotting import ColumnDataSource                                        
import math                                                                        

bokeh.plotting.output_file('out.html')                                             

source = ColumnDataSource(data={'x': [1, 2, 3, 4, 5], 'y': [1, 2, 3, 2, 1]})       

figure = bokeh.plotting.figure()                                                   

figure.cross('x', 'y', source=source,                                              
             angle=math.pi/4.0, size=12,                                           
             legend='text')                                                        

bokeh.plotting.show(figure)
```

**Comment by bryevdv** [comment]
This was explicitly removed before 1.0 in #8080, to fix a more serious bug #8077

**Comment by bryevdv** [comment]
@poplarShift To ay a bit more, I don't have any objection to restoring this functionality, it just needs to make sure to avoid the bug above

**Comment by poplarShift** [comment]
I see, thanks. Reminds me that size isn't respected either.

**Comment by bryevdv** [comment]
> I see, thanks. Reminds me that size isn't respected either. 

Size is covered by https://github.com/bokeh/bokeh/issues/2603 (I've updated the title here to restrict the issue to angle) Happy to discuss size more on that issue, but it's a much more involved problem because it runs into, e.g. "what do you do when the glyph size is larger than the legend drawing area"

**Comment by poplarShift** [comment]
Fair enough, I see that would need more discussion on the specifics.

I'm happy to have a look at restoring the functionality but there is something I don't understand in the original issue. In #8077 @mattpap said that 
> I would choose the simplest approach. After all, angle can vary between indices, so this may not depict the a glyph accurately.

What is this "index"? I initially thought one could simply check if angle is supplied, and if it isn't, one would default to 0. I'm not sure how that would relate to this index.

**Comment by bryevdv** [comment]
> What is this "index"? I initially thought one could simply check if angle is supplied, and if it isn't, one would default to 0. I'm not sure how that would relate to this index.

indicies here refers to the index into the arrays of visual properties for each individual glyph that is drawn on the screen. I.e., if you call `p.triangle` to draw 100 triangle markers, it's perfectly possible to give every single one a different and unique angle. So, in that case, which angle do you use for the legend? We now have the notion of a "representative point", which is just the index to into the arrays of various glyph properties. We default it is zero, but it is configurable. But mostly that configurability is to support "groupby" legends. If you have 100 different angles (or colors, or whatever) then picking any one is arbitrary and probably not meaningful. That's part of the reason we dropped this in the first place. But, the case where every triangle has the same angle is not uncommon or unimportant, which is why we would consider restoring this.

**Comment by poplarShift** [comment]
So I had a look at this a while ago. While it's clear what should be done (check whether the attribute exists and if yes, if there's a unique angle given and if yes, use that value) I'm not familiar enough with typescript across different browsers (e.g. one of my implementations used Set, so didn't work everywhere) nor with what utils bokeh already has (I would think that tasks like these are routinely done in bokeh anyway). So I may revisit when I know bokeh better but for the moment I can't be very helpful.

**Comment by bryevdv** [comment]
> if there's a unique angle given 

Currently can plot up to 100s of thousands of scatter markers. I think uniquing arrays that big on renders would have a prohibitively adverse affect on performance. I'd need to see some benchmark evidence to the contrary before merging this approach.

**Comment by bryevdv** [comment]
I'm going to go ahead and close this. In the very specific case at the top, the answer is simply to use the X marker, not ` cross`. (not sure why I did not notice that immediately) In the general case I just don't think it is common enough to justify.
