### ISSUE TITLE
[BUG]error in making doc

### ISSUE THREAD

**Issue by xBlackSwan** [bokeh/bokeh#8918]
[sphinx-err-1y08v5qm.log](https://github.com/bokeh/bokeh/files/3187524/sphinx-err-1y08v5qm.log)

**Comment by bryevdv** [comment]
We build the docs continuously on TravisCI on every push and I build them regularly. So I can only conclude this is some specific issue with your configuration. You probably have an incompatibly Pandas version. However, since you have ignored the issue template and not provided any information whatsoever, it is impossible to speculate further. Since this is also really a support question, I will close this issue. Please feel free to reach out on the [mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) for help.
