### ISSUE TITLE
[FEATURE] Make palettes return Color

### ISSUE THREAD

**Issue by fdw** [bokeh/bokeh#8970]
I was a bit surprised to find that the colors returned by `viridis()` (and other palettes) are simple Hex `str`s, not instances of `Color`. I had expected that I can call `darken` and `lighten` on the generated values, but unfortunately that seems not to be the case.

Additionally, I cannot seem to find a way to generate a `Color` instance out of the hex strings, as there is no `from_css`, `from_hex` or similar method. The only way seems to be to split the `str` manually, convert the numbers from hex to decimal, and then create a `RGB` object from that.

What I would like to have is that the palettes return `Color` instances, so that I can use the full range of methods on them.

**Comment by bryevdv** [comment]
@fdw thank you for your comments. We store the colors as hex strings because that is what BokehJS expects, and in fact if we were to make any compatibility-breaking changes in the future, it would be to go the opposite direction from what you suggest, i.e. we might store the colors as numpy arrays of raw RGBA integers in order to make them suitable for the efficient binary transport that is available for such arrays. 

Storing all the colors as individuals colors would add a lot of overhead, both at import time (which is already longer than we would like) as well as during usage. Using the lightening/darkening functions is not the common case, so we could not justify adding this expense to everyone all the tine. 

However, I do note that it is not currently as easy to do something like this as it could be:

```
from bokeh.palettes import viridis
pal = viridis(16)
objs = [Color(c).lighten(...) for c in pal]
```
And that's because converting *to* hex is supported by `Color` but seemingly there's not a good way to convert *from* hex. If you are interested in working up a Pull Request to add something to make this easy for you to do, I'd be more than happy to consider it. This task is purely on the python side and should be approachable to anyone with modest python experience. I can't say it's a priority for me, so realistically speaking, you would almost certainly be able to get to it much, much sooner than I could.

**Comment by mattpap** [comment]
> (...) we might store the colors as numpy arrays of raw RGBA integers in order to make them suitable for the efficient binary transport that is available for such arrays.

We should consider this for 2.0.

**Comment by fdw** [comment]
So a PR that reads the hex string wouldn't make sense now, right?

**Comment by bryevdv** [comment]
I think a PR to add a hex string is still useful in its own right, but yes if you want to cover all the bases for the possible future you could add both `from_hex` and `from_int` methods.

**Comment by fdw** [comment]
Unfortunately, I haven't found the time, and have since then also migrated away from Bokeh. So if someone still wants to do this, feel free.
If not, you can also close this ticket.

Thanks for your help and Bokeh!

**Comment by bryevdv** [comment]
Absent other input I will close for now
