### ISSUE TITLE
[DOCS] Add mention of Themes to "Styling Visual Attributes" docs page

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#9007]
I was looking for documentation about Themes in the "Styling Visual Attributes" page of the docs and was surprised we didn't have it there. We should...

Add mention of Themes to "Styling Visual Attributes" docs page

**Comment by santos22** [comment]
Any chance the theme examples found at the top of the [bokeh.themes](https://docs.bokeh.org/en/latest/docs/reference/themes.html) reference can be moved over to ["Styling Visual Attributes"](https://docs.bokeh.org/en/latest/docs/user_guide/styling.html#userguide-styling)?

**Comment by bryevdv** [comment]
I don't think anything should move *off* the reference page because the reference is intended to be complete. And I worry about duplicating *all* the themes example on *Styling Visual Attributes* because that page is already huge and long, and the number of themes might grow arbitrarily over time. Putting all of them there may set a precedent we just can't reasonably keep up with forever. I would suggest this as an alternative: Add a "Themes" subjection to *Styling Visual Attributes* that: 
* describes how themes are specified and how to use them
* has one example of a built in theme
* has one example of a custom theme
* has links to the `bokeh.themes` reference 

Thoughts? In my mind the alternative would be a separate new entire chapter, if we want to show everything in the users guide.

**Comment by santos22** [comment]
Yea I think that makes sense. If users want to build their own custom theme, we can show them how in the user guide and also point them to the reference guide where they can see the built-in themes.

What about linking to the following blog post? https://blog.bokeh.org/posts/styling-bokeh

I don't see any other blog posts linked in the source code but I think it might be useful here if we're concerned about the length of the page. Could even link at the top of the page so it doesn't get lost down below.
