### ISSUE TITLE
[BUG] vbar_stack with positive and negative values does not plot correctly

### ISSUE THREAD

**Issue by JING1201** [bokeh/bokeh#9011]
**Expected Behavior:** 
When the source data contain a mixture of positive and negative values, the bars with negative values will stack downward below 0 without interfering the positive bars.

**Observed Behavior:**
When the source data contain a mixture of positive and negative values, the bars with negative values stack downward from the top of the previous positive bar, making that bar not visible.

Note: This is similar to [the issue raised in plotly ](https://community.plot.ly/t/stacked-bar-with-positive-and-negative-values/920), and this is resolved by having a 'relative' barmode.

**Software versions:**
bokeh 1.2.0
Python 3.6.8

**OS:** 
Windows 10

**Example:**

```
from bokeh.plotting import figure, show, save
from bokeh.io import output_notebook
from bokeh.core.properties import value
from bokeh.layouts import *

y_s = ['y1', 'y2']
data = {'x_values': [1, 2, 3, 4, 5],
       'y1': [-2, 5, 1, -2, 3], 
       'y2': [1, -9, -5, 1, -2]}
p = figure(title="Demonstration")
p.vbar_stack(['y1', 'y2'], x='x_values', width = 0.5, color = ['blue','red'], source = data, legend=[value(y) for y in y_s])
p.legend.click_policy="hide"
show(p)

```

![image](https://user-images.githubusercontent.com/19191124/59576012-7cb07280-90f0-11e9-8206-4b3afa4442be.png)

**Expected Output:**

![image](https://user-images.githubusercontent.com/19191124/59576029-9356c980-90f0-11e9-92a4-a7f18938b336.png)

Although using separate vbar glyphs can solve the issue in this example, it will not be much help when there are more stacked bars and the data gets more complicated.

**Comment by bryevdv** [comment]
@JING1201 ING1201 The current output is correct
```
 'y1': [-2, 5, 1, -2, 3], 
       'y2': [1, -9, -5, 1, -2]}

-2 +  1 = -1
 5 + -9 - -4
 1 + -5 = -4 
-2 +  1 = -1
 3 + -2 =  1 
```
Which is exactly what is seen in your plot. Columns are always summed together consecutively. Ther is no other sensible thing to do, since in general, stacks can contain any number of columns to stack, not just two as you have. In general, stacks should all be positive, or all be negative, and if you need to split at zero you will need to split up your data accordingly.

**Comment by bryevdv** [comment]
Speaking of setting alpha < 1 that is also another way to see why the output is the way it is, bars are always stacked "end to end" so mixing pos/neg values will always result in overlap. Again, there is no other sensible procedure given that any number of bars can be stacked at a time.

<img width="649" alt="Screen Shot 2019-06-17 at 1 50 55 PM" src="https://user-images.githubusercontent.com/1078448/59635909-24d13600-9107-11e9-8d51-1386f5a65bf9.png">

**Comment by JING1201** [comment]
@bryevdv Thanks for the explanation! However, could we reopen the issue as a feature perhaps? I think having a feature that automatically splits the data for the user for vbar_stack and other methods that uses _double_stack would be beneficial since having data with mixed signs is not uncommon, and overlapping is not the desired output in most cases. I have seen a lot of others asking about this online, and such feature has been added in plotly and holoviews.

**Comment by bryevdv** [comment]
@JING1201 My time is currently very constrained and mostly accounted for. Realistically it's not something I am going to work on. But such a task is pure python side, so should be accessible to a wide range of Python expertise. I'd be happy to consider a PR for this from anyone who wants to contribute. There are some issues to be aware of:

* would need to check if any given series has mixed signs *within* the array. There is no way to handle this without overlap, so we should at least warn, or possibly raise an error by default (configurable to allow, if desired)

* need to recognize inherent limitations:   The detection/splitting would happen *once*, at the time `hbar_stack` is called, so if a user updates the data in a CDS *after* calling `hbar_stack`, that can't really be detected and its entirely possible to generate nonsense output. i.e. if an all-positive seq is changed to an all-negative sequence, there is no way to automatically update things after the fact. This needs to documented. We could consider adding a serialization time variation check but it might be very expensive.

**Comment by bryevdv** [comment]
Re: re-opening, I'd rather wait until there is a commitment or at least an indication of interest from someone that they want to work on. I have a strong bias against letting issues linger and become stale.

**Comment by JING1201** [comment]
@bryevdv Thank you for pointing the issues out. I'm willing to take on the issue, but I will be relatively slow on updates since I'm new to contributing to a library. 
Since you brought up the issue with CDS, I am thinking of not allowing CDS to be used with the "auto-splitting" feature, which would be a parameter in hbar_stack, as a temporary fix. This means that only static python data structures like dict and lists can be passed in as a source when the splitting feature is used. Do you have any thoughts on this? I am not sure if setting the restriction here or purely documenting the issue would be beneficial for development in the long term.

**Comment by bryevdv** [comment]
> Since you brought up the issue with CDS, I am thinking of not allowing CDS to be used with the "auto-splitting" feature, which would be a parameter in hbar_stack, as a temporary fix

There is always a CDS. If you don't pass one explicitly, then Bokeh creates one internally to use. However, I would not support a PR that makes the change you describe. Every glyph method accepts a `source` argument, without any exceptions whatsoever. This is a foundational aspect of the API and I would be -1 on adding any exceptions to it. I'm OK with with `hbar` trying to split when it can, but it must also always accept a `source`, just as it does now, and handle that case uniformly.

**Comment by bryevdv** [comment]
Just to be clear about expectations: A PR I would accept would have zero change to current API. It would simply internally inspect the relevant columns in the CDS (that must be present) and partition the renderer stacking based on whether the array contents were all positive, or all negative.

**Comment by JING1201** [comment]
@bryevdv I just read through our conversation and realized that I might not have conveyed my ideas very clearly. Here are some clarifications to resolve any misunderstandings:

- By saying not allowing CDS, I'm referring to the situation where the source passed in is of the type ```ColumnDataSource```. When the splitting feature is on, the hbar_stack will still accept a ```source``` parameter, but the value cannot be of the type ```ColumnDataSource``` since it would allow data updates that can potentially lead to nonsense output. Therefore, I am thinking of allowing only sources of the types ```list``` or ```dict``` when the splitting feature is on, since the data set cannot be updated easily. (Please correct me if I'm assumed anything wrong.) 

- I assumed splitting to include splitting an array with internal mixed signs. For example, converting [1, 2, -5, -9] to [1, 2, 0, 0] and [0, 0, -5, -9]. This means that each column in the source data will be inspected and splitted into two arrays (one positive and one negative) and fed into the positive and negative partition respectively. 

Let me know what you think.

**Comment by bryevdv** [comment]
> but the value cannot be of the type ColumnDataSource since it would allow data updates that can potentially lead to nonsense output in the future

It *must* be of type ColumnDataSource. The CDS is the central foundational data structure of Bokeh. It is what:

* automatically synchronizes data between JS and Python
* performs fast binary transport of arrays
* recorded selections, all hit testing, hover tool, etc is due to CDS
* is what is consistently used everywhere, and documented everywhere, not using it means making and explaining a very strange exception, and means (inevitably) more support questions due to that

* I assumed splitting to include splitting an array with internal mixed signs. For example, converting [1, 2, -5, -9] to [1, 2, 0, 0] and [0, 0, -5, -9]. T

I am very -1 on this. We cannot manipulate the data that is passed to us, at all. This is confusing to users, and we also risk our assumptions not matching users intentions. This sort of thing may be appropriate for a higher level tool, e.g. Holoviews. 

At this point I think my inclination is to leave this issue closed and point to Holoviews as a potentially better alternative if you don't want to split things  yourself with Bokeh.

**Comment by JING1201** [comment]
@bryevdv I see what you mean now. Thanks for the explanation :) Since there are so many complications, I agree with you on leaving the issue closed.

**Comment by bryevdv** [comment]
@nabilahmed739 Nothing about my previous analysis above has changed, I am -1 on processing the data at this level. From my perspective, this is a relatively marginal use-use, that can still be otherwise accomplished, that would be non-trivial to implement and maintain, and possibly lead to increased support burden due to confused/overly complicated semantics. As I mentioned it probably makes more sense to ask about something like this on a higher level tool like Holoviews, that is built on top of Bokeh.

**Comment by bsteubing** [comment]
Hi @bryevdv, I have not followed the full discussion here, but I am quite surprised that bokeh does NOT support stacked bar charts with mixed negative/positive numbers out of the box. This was such a "given" for us that we did not consider this in our evaluation to use bokeh for the [Activity Browser](https://github.com/LCA-ActivityBrowser/activity-browser) project. Our implementation is still Matplotlib based, which is a fantastic plotting library, but not as good on the interactive side as bokeh. So while we are not decided yet whether we can actually use bokeh, this here seems to be the [workaround for now](https://docs.bokeh.org/en/latest/docs/gallery/bar_stacked_split.html), i.e. to split any data into a negative and a positive side and then add both separately to the figure. 
This is not only unnecessarily complicated and error prone, but also comes with the downside for us that for making this interactive it gets more complicated as we have to work with two underlying dataframes (tables) instead of just one (like in all other plotting libraries that I am aware of). So we'd appreciate very much if bokeh could offer a solution for supporting stacked bar charts _in general_ instead of the current implementation...

**Comment by bryevdv** [comment]
> I have not followed the full discussion here

@bsteubing if you want to try and convince me to change my mind you will need to understand my objections, and address them.

**Comment by bsteubing** [comment]
@bryevdv I have read through this discussion in the meantime and I cannot fully follow the objections. From a library that can plot stacked bar charts one would expect that it can handle negative numbers correctly... So to be honest, I do not see / understand the use case for the current behavior. There may be certain implementation reasons at the current state of development, but from a user perspective - I am sorry - it does not make sense (at least to me and to others in this thread at least)

**Comment by bryevdv** [comment]
@bsteubing You have hinted at the issue:

> Matplotlib based, which is a fantastic plotting library, but not as good on the interactive side as bokeh. 

Those things are in tension. MPL can take in data, do whatever it wants to do internally, and spit out a static image, all work done in one Python process. Super simple model to work with and extend. Bokeh operates *nothing like that*.  Almost all of the work is actually done in the browser, in JavaScript, by BokehJS.  Furthermore all the state, including all data, from the Python and JS sides has to be mirror-able back and forth  between the runtimes, so transforms need to be sensible and communicable across the Python/JS boundary a well. 

Different features and focuses mean trade-offs, and this is one of them. In any case: is this impossible? No, but it would add non-trivial complexity, and maintenance burden to an already very large and complicated project, maintained by a small team. So then the question is: is all that burden justified to satisfy the request of the three (3) users who have asked about this in the last ~10 years? Let be me perfectly clear that for me, personally, the answer is *no*, it is not. I am happy to review detailed proposals or offer technical guidance to anyone else who might like to work on it. 

Otherwise, not every tool can be perfectly suite for every job, and that is fine. I promise none of us will be upset if MPL is a better tool for you for this case.

**Comment by bsteubing** [comment]
@bryevdv thanks for your explanations. I have no deeper insights into the technical challenges you describe and the priorities at bokeh, but I do fully understand that you have to prioritize, so of course have to accept your "no" here. 

However, as a scientist with 10+ years plotting experience, I fail to understand the logic behind this behavior. Why would stacked bar charts _not_ plot as described here on top under "expected behavior"? I am not aware of any other plotting platform that does not offer this... it is a standard plot. Look at how pandas plots stacked bar charts. And even mainstream software like Excel does it like this. But OK, now we are turning in circles. 

I would not be surprised if there were not quite a few others who'd like to use bokeh for stacked bar charts, but then either go elsewhere or do these additional transformations. **So anyone, please up-vote this if you feel like you are missing this as well in bokeh.**

Should you decide to re-open this issue at some point, it seems that plotly has implemented the behavior we'd be expecting, see here for future inspiration:
https://github.com/plotly/plotly.js/issues/475
https://codepen.io/etpinard/pen/mPGLrY

**Comment by bryevdv** [comment]
BTW just to ground the discussion in concrete details, this example [from the docs] shows just exactly how much extra work a diverging bar stacked back chart actually takes with pure Bokeh:

<img width="802" alt="Screen Shot 2021-09-28 at 12 59 03" src="https://user-images.githubusercontent.com/1078448/135157215-dea55b2b-496b-4edf-9f9f-b1cd710e14f5.png">

Reiterating another point I made earlier: This kind of thing would fit much more naturally in a higher level tool like `pandas_bokeh` or `holoviews` because those tools are in a position to make assumption that pure Bokeh cannot (e.g. "this function only generates standalone output and will never be used in a Bokeh server context, so does not have to worry about munging the data only on the python side")

**Comment by nabilahmed739** [comment]
> @bryevdv thanks for your explanations. I have no deeper insights into the technical challenges you describe and the priorities at bokeh, but I do fully understand that you have to prioritize, so of course have to accept your "no" here.
> 
> However, as a scientist with 10+ years plotting experience, I fail to understand the logic behind this behavior. Why would stacked bar charts _not_ plot as described here on top under "expected behavior"? I am not aware of any other plotting platform that does not offer this... it is a standard plot. Look at how pandas plots stacked bar charts. And even mainstream software like Excel does it like this. But OK, now we are turning in circles.
> 
> I would not be surprised if there were not quite a few others who'd like to use bokeh for stacked bar charts, but then either go elsewhere or do these additional transformations. **So anyone, please up-vote this if you feel like you are missing this as well in bokeh.**
> 
> Should you decide to re-open this issue at some point, it seems that plotly has implemented the behavior we'd be expecting, see here for future inspiration: [plotly/plotly.js#475](https://github.com/plotly/plotly.js/issues/475) https://codepen.io/etpinard/pen/mPGLrY

+1

**Comment by bryevdv** [comment]
@bsteubing FYI the plotly code you linked:

* requries working in JavaScript, no Python
* does not do any stacking of bars!
* is 50% more LOC than what I posted just above

I fail to see how that is an improvement, but again, users should 100% use tools that fit their needs according their own criteria.

**Comment by nabilahmed739** [comment]
@bryevdv 
Just FYI, examples of the relative stacked mode of Plotly in Python:
 
![image](https://user-images.githubusercontent.com/6296604/135279422-ba024a71-0e9e-4241-9217-01bd7864a494.png)
src: https://plotly.com/python/bar-charts/

![image](https://user-images.githubusercontent.com/6296604/135279650-5da36c9a-21e3-42a1-b898-11a16895516b.png)
src: https://www.kaggle.com/jrmistry/plotly-how-to-create-diverging-stacked-bar-chart
