### ISSUE TITLE
Inspection indices' filtering is very slow

### ISSUE THREAD

**Issue by masip85** [bokeh/bokeh#9016]
I was working on my plots (100k timeseries points) with very slow performance when zooming,panning or whatever.Them, I started to thought webGL isn't working. After many test of my script, browser, OS hardware driver ... I re-started by the easiest case. I went to website no-webgl/webgl case:

https://bokeh.pydata.org/en/latest/docs/user_guide/webgl.html

I see no difference in speed performance between no webGL plot related to webGL plot. (tested in differentet browser Edge/Firefox/Chrome, different computers with different OS).

But the speed performance improvement I remembered can be seen here!
https://bokeh.pydata.org/en/0.13.0/docs/user_guide/webgl.html

Have we lost webGL from 0.13 to 1.0?

**Comment by bryevdv** [comment]
@masip85 The WebGL component no longer has an active maintainer so it's entirely possible there are regressions. That said, I always run the standard webgl examples in the repo manually before releases, and they seems to be functioning as expected. So if you are seeing something different, what we need from you is:

* detailed version, platform, browser info
* a complete example that reproduces the issue

I can't say when it might get looked at, offhand. We will be proposing revamping WebGL support as part of an upcoming grant proposal, but of course there's no guarantees that the proposal will be accepted, and even if it is the work would not start until next year. But if we can reproduce the problem, there might be a simple, obvious fix that suggests itself, so the first, absolute necessity for any investigation is to get us everything necessary to reproduce what you are seeing.

**Comment by masip85** [comment]
Ok. 

I have executed maually https://github.com/bokeh/bokeh/blob/master/examples/webgl/scatter10k.py#L6

This works. But the plot of this code that exist in the web https://bokeh.pydata.org/en/latest/docs/user_guide/webgl.html is not working. You can test in with windows and ubuntu, with firefox ,chrome or edge. You can't see webgl speedup.

And as I have already told, in https://bokeh.pydata.org/en/0.13.0/docs/user_guide/webgl.html you can see the speed up.

So it works, but **website webgl example is wrong**.

Then, I have came back to my problem, a line of 100k points moving really slow. So I have teste bokeh line webgl example with 100k points:
```
import numpy as np

from bokeh.plotting import figure, show, output_file

N = 100000

x = np.linspace(0, 10*np.pi, N)
y = np.cos(x) + np.sin(2*x+1.25) + np.random.normal(0, 0.001, (N, ))

p = figure(title="A line consisting of 100k points", output_backend="webgl")
p.line(x, y, color="#22aa22", line_width=3)
show(p)
```
It works quite nice. Then I have wondered ... why my p.line of 100k points moves so slow. The answer is: the hove tools make everything very slow:

Add to the example line code this code:

```
p.add_tools(HoverTool(
    show_arrow=True,
    line_policy='next',
    tooltips=[
        ( 'date',   '@x{%F}'            ),
        ( 'quantity', '@y{0. a}'      ),
    ],
    formatters={
        'x'      : 'datetime', #in my example I need datetime formatter
    },
    mode='vline'

))
```
Maybe this is not a webGL issue then. Otherwise, why does hover tools slow down everything so much? If you test it, you can see is quite a lot.

[line10k.zip](https://github.com/bokeh/bokeh/files/3314233/line10k.zip)

**Comment by bryevdv** [comment]
In order to function, hover tool has to perform hate-testing on every mouse move. (i.e. to display a tooltip for a given point, you have first know which point, if any, out of all the points, was hit). For lines, it's even worse: for every segment, it has to perform a fairly expensive segment-intersection test for every adjacent pair of points in the line. 

We use an RTree-like  spatial index to greatly accelerate hit-testing for some glyphs (e.g. scatter glyphs). Basically the index helps to greatly prune down the potential list of hit candidates first .However, currently the spatial index is not used for line glyphs. The reason is because the line case is not nearly as simple as the scatter case. E.g. for any given hit-test box you pass to the index, it can be the case that:

* both endpoints are in the box (segment entirely inside the box)
* only one of the endpoint is in the box (segment is halfway out the box)
* neither of the endpoints is in the box (segment crosses over the box)

But *all* of these cases might be potential hits for a over, so they still all have to be considered. It's not clear at all that adding alot of complicated spatial indexing to lines would actually improve anything. Someone will have to do some investigation. 

But the takeaway is this: fixing this is going to require somewhat of an investigation. I don't have a solution or workaround for you. I would simply say that hover tool (especially with vline, etc) with lines that have many points is simply not currently supportable.

**Comment by bryevdv** [comment]
@mattpap has been able to make some impovements, we will make sure to get this out in a dev build  very soon. Any follow-on should go in new issues (link here as appropriate)
