### ISSUE TITLE
[FEATURE] Extend applicability of "js_link"

### ISSUE THREAD

**Issue by tony-bony** [bokeh/bokeh#9023]
Currently `js_link` requires the two linked Bokeh model properties must be of the same type.
It could be nice to also support linking model properties of different types like `int` and `str` or vice versa.

In the following example `Div.text` expects `str` while `int` is passed from the `Slider.value` resulting in an error.

```
from bokeh.io import show
from bokeh.models import Slider, Div, Column

slider_values = {0:"Text 0", 1:"Text 1", 2:"Text 2", 3:"Text 3"}
slider = Slider(start=0, end=3, value=0, step=1, show_value = False)
div = Div(text = slider_values[slider.value])

slider.js_link('value', div, 'text')

layout = Column(div, slider)

show(layout)
```

**Preferred solution:**

Apply automatic type casting so the following works:
`slider.js_link('value', div, 'text')`

**Alternative solution:**
Allow to specify the type casting like: 
`slider.js_link(str(value), div, 'text')`
`slider.js_link(str(value), div.text)`

**Additional context**
Besides `Slider` also string (number) values from `TextInput`, `Spinner` or `Select` could be converted to `int` or `float` like:
`select.js_link(int(value), tabs, 'active')` 
`select.js_link(float(value), renderer.glyph, 'size')`

and many more...

**Comment by bryevdv** [comment]
There's unfortunately not any way to make this work, the linkage happens in the browser, on the JS side, not the Python side, so `str`, `int`, etc. don't exist. This is why the first argument is a *string*, because it's actually the name of the property that the JavaScript code will have to look up. 

If you need this kind of conversion, you should use a standard `CustomJS` callbacks

**Comment by tony-bony** [comment]
I see. Thanks
