### ISSUE TITLE
[FEATURE] add favicon support to Bokeh server

### ISSUE THREAD

**Issue by timsnyder** [bokeh/bokeh#9086]
in bokeh/demo.bokeh.org#14 I reported that https://demo.bokeh.org doesn't have a [favicon](https://en.wikipedia.org/wiki/Favicon).  @bryevdv pointed out that nothing coming from a Bokeh server will have it set.

favicon support in bokeh server would help applications appear more "polished" to users because favicon is displayed by most browser clients in the 'tab' along with the <title> (from inside \<head\>).

**Comment by timsnyder** [comment]
@bryevdv , I noticed that http://demo.bokeh.org also has "Bokeh Applications" as it's title.  If Bokeh server doesn't support customizing the page's title, we should probably do that along with the favicon support.

**Comment by bryevdv** [comment]
@timsnyder That page is a template, so the title can be anything the template specifies. It is currently set here:

https://github.com/bokeh/demo.bokeh.org/blob/master/index.html#L4

**Comment by timsnyder** [comment]
@bryevdv  After looking through demo.bokeh.org's setup and looking at the examples/app/movies, I have a much better notion of what's going on here.  I see where we would want to add a favicon attribute on bokeh.document.Document and needs to behave roughly the same as the {{title}} attribute.  Am I on the right track?

Also, looking across bokeh.org, bokeh.pydata.org, it looks like you have copies of the favicon.ico in each webpage.  Do you want to put it on the CDN and have the default favicon link from there?  

How does one see what's available on cdn.bokeh.org?  Trying to browse around in there gives me access denied XML responses.

**Comment by bryevdv** [comment]
>  I see where we would want to add a favicon attribute on bokeh.document.Document and needs to behave roughly the same as the title attribute. Am I on the right track?

There's a couple of potential ways. We could simply look for a `favicon.ico` file in directory style apps. We could have a command line `--favicon=<...>` option. Either way there needs to be an option that works with both a top-level `index.html` as well as with app pages I *think* we would want to make a new Tornado request hander `FaviconHandler` that can be set up to respond to `/favicon.ico` and `/app/favicon.com` Perhaps there can just be one per endpoint and it is configured with an image (either from the document.favicon for apps, or from command line for the top level)

>  Do you want to put it on the CDN and have the default favicon link from there?

It's on my short to-do list. I am about to receive an cleaned up new word markwith a distinctive font from a designer friend. When that happens I was going to move a set of image assets and (maybe) the bootstrap files to the `static.bokeh.org` bucket (and probably put that behind a CDN as well)

> How does one see what's available on cdn.bokeh.org? 

All the CDN sites are backed by s3 buckets. I am a little reticent to start handing out write access to things on AWS just yet (only worried about accidents and not having thought out full recovery scenarios yet) but I can see about making a read-only group for now if you are interested. Realistically, the CDN b bucket should probably be re-created with versioning and delete protections turned on, but I think that will require a new bucket from scratch.

**Comment by timsnyder** [comment]
Good point about making it work for top-level index.html as well as app pages.  I'll probably utilize the suggestions from the [tornado docs](https://www.tornadoweb.org/en/stable/guide/running.html#static-files-and-aggressive-file-caching)

Without looking at how Bokeh Server sets up the tornado app, I'm leaning toward having a static_path defined, putting any locally provided favicon in there and using the appropriate `<link />` tag in the `<head>` of the relavant page.  That pattern works for an icon that is locally provided or something that comes via http, like a bokeh default icon. 

I probably need to go look through the server code before I flap my fingers anymore...

> reticent to start handing out write access to things on AWS

No problem.  I just wanted to make sure that there isn't a favicon.ico somewhere that I should be pointing to as the default when the user doesn't specify one.  No need to spend time looking into a read-only way for me to look.

I'll code up the behavior and we can decide what the default should be later.

**Comment by bryevdv** [comment]
The issue with a static path is that this has to work for the single file `bokeh serve app.py case as well as the notebook embed case and neither of those have a naturally available directory that could be static directory. That's why I was leaning toward a simple but custom `FaviconHandler` that did not assume or rely on any particular filesystem layout

**Comment by timsnyder** [comment]
Good point.  You have all of the usecases loaded in your brain. :)

**Comment by jbednar** [comment]
I'd like to second this request, because I end up with dozens of Chrome windows that look like: 

![image](https://user-images.githubusercontent.com/1695496/61440352-22c1e900-a8f8-11e9-84fb-e6f9c7a0392b.png)

and I have to page through all of them to find anything. Having a page title would help, and I don't think that should require a template -- for me, the page title is about how to manage browser tabs, while a template is about the look and feel of the web page. I don't want to have to define a template just to get the browser tab to say something useful. In fact, can't the browser tab say the actual filename by default, without the user needing to do anything? E.g. for `bokeh serve file.py`, can the page title be `File` or `File - Bokeh Server` by default? That way most of my tabs would automatically be distinguishable.

Similarly, I'd like to be able to define a favicon from within a single file, without having to move to a directory format or pass in a special command-line option; can't it be something we declare from Python?  With Panel a single file (often a notebook) is often sufficient, and I wouldn't want to have to switch to a directory just to get the favicon customized. In any case, always having the Bokeh icon would be better than the current generic icon.

**Comment by philippjfr** [comment]
>Having a page title would help, and I don't think that should require a template

This is already possible, in Panel you can do this by setting the title in the servable call, e.g. ``obj.servable('A Custom title')``

**Comment by jbednar** [comment]
Oh, in that case let's do that for all our  Panel examples, so that people like me can't fail to miss it!  :-) Let this issue return to favicons, which are also important...

**Comment by timsnyder** [comment]
bq. Having a page title would help, and I don't think that should require a template

And I think that @bryevdv was speaking specifically of the template for http://demo.bokeh.org/index.html .  Pages that are Bokeh server app's like https://demo.bokeh.org/movies can and do set the title (and it's also looks possible to dynamically change it).

bq. I'd like to be able to define a favicon from within a single file, without having to move to a directory format or pass in a special command-line option
ACK.  I'll make sure that it is possible to keep the single-file usecase alive and well.

**Comment by timsnyder** [comment]
Do we care about being able to dynamically change the favicon?  Should I just do the first step of having support for a basic static favicon first and save dynamic fanciness for another PR?  Making it dynamic seems interesting but it will be a lot more code additions.

[A blog post that makes me think it's possible to have dynamic favicon support.](https://medium.com/@alperen.talaslioglu/building-dynamic-favicon-with-javascript-223ad7999661)

**Comment by philippjfr** [comment]
I'd vote for going for static favicon support first, while dynamic support seems cool it doesn't seem like a particularly common usecase.

**Comment by bryevdv** [comment]
I am fine with starting with static, and also just a single one for all pages specified on the command line with `--favicon=`. Then a `FaviconHandler` configured at `/favicon` just returns this image data. 

For later, to support both a "top level" favicon (for the index.html page) as well as per-document favicons (potentially dynamic),  it occurs to me that favicons are always at the very top level e.g. `/favicon.ico` so we would probably have to implement this as a single `FaviconHandler` that examples the referrer URL in the request. Then if the referrer is from an app URL and that app has registered a favicon, use that. Otherwise use any top-level one (e.g supplied on the command line).

**Comment by timsnyder** [comment]
I think that if we want to have them be per-page and/or dynamic, we'll need to add support for `<link rel="icon" >` and all of it's variants in the `<head>` of the DOM.  The `favicon.ico` in the root of the page is the old way of doing this.  

Oh, the stackoverflow page you linked says the same thing.

@audreyr has a nice (albeit slightly dated)  [favicon cheatsheet](https://github.com/audreyr/favicon-cheat-sheet) that mentions query strings not being quite enough to force a refresh because they can get stripped by CDN's or proxies.

I'll do the easy support first because I can get it done quickly.

**Comment by bryevdv** [comment]
@timsnyder sorry I did not elaborate, I agree 100% with supporting `<link rel>` but also customarily those often point to a `/favicon.*` I was just suggesting conforming with that common practive.  It's worth considering (for later) that there is definitely a distinction between and *app* specifying a favicon to use (for all sessions) and individual sessions specifying favicons. The latter is what would correspond to e.g. `curoc().favicon = ...` because that is something every session could set differently. Something to sort out for later. But again, for now, just one favicon for everything (index page and all apps/sessions) seems fine,.

**Comment by timsnyder** [comment]
Great.  I think we're on the same page.  I just started out thinking about using `<link>` because I was also thinking about `output_html()` cases being able to point to a CDN-ified http://bokeh.org/favicon.ico as the default and providing programmatic ways to change set the href (possibly to a data URI so that the client-only output remains a single file).

I'll just focus on the bokeh server case first and then output_html.

**Comment by bryevdv** [comment]
The issue I have here is that favicon "best practices" seem quite involved. Specifically, I don't think affording a single file provided via `--favicon=` or `curdoc().favicon = ` is actually anywhere near sufficient. Even a "minimal" favicon package has multiple sizes and many HTML tags:

```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
```

Things can get substantially even more complicated than that. The problem is I am not an expert here by any means. I don't know how to judge which options are the most important (what's the right 20% to focus on to get 80% capability). 

And then beyond that, there's just a question of what is an ergonomic UX to configure something as complicated as this? A very simple ``--favicon=`  with a single file won't do, and any ideas that come to my offhand seem very clunky or convoluted. To the point where I wonder if this is simply something that should be considered "custom template" territory, so that whatever the actual user needs are, they can be put in the template regardless, and according to standard best-practice guidance. 

Definitely need substantially more input/help to refine this, before moving on any implementation.

**Comment by jbednar** [comment]
The single .ico file can (and in our work normally does) have multiple resolutions, covering at least 32x32 and 16x16.  The fancy Apple Touch stuff seems beyond what's needed here. So I'd think that 80% is covered simply by having a single file.

**Comment by bryevdv** [comment]
I can already hear the "that's so 90's, you need to support *modern* web practices" complaints. But it's what I might could  accomplish presently, and as long as it's done in a way that separates concerns enough to avoid clobbering any future ideas, I guess it will have to do. So I'd amend to proposal:

* Add `IconHandler` that can be configured with a single path to a `.ico` file, or None
* By default it is configured to return the Bokeh project favicon 
* Directory style apps will automatically configure a `favicon.ico` in the directory 
* `bokeh serve` gets --icon=` and `--no-icon` options 
   
I specifically want "icon" instead of "favicon" to make it clear that this only pertains to `.ico` file configuration. And more importantly, to leave "favicon" term available for more general favicon support potentially in the future. Browsers just always automatically look for `favicon.ico` if nothing else is present, so those future configurations (for a `.ico` vs a "favicon package") would be orthogonal. 

Questions:

* should the default Bokeh favicon be tweeked specifically for "bokeh apps" if so, how?

**Comment by bryevdv** [comment]
Well, the current Bokeh `favicon.ico` does not have transparency: https://static.bokeh.org/favicon/favicon.ico

**Comment by EfremBraun** [comment]
> I can already hear the "that's so 90's, you need to support _modern_ web practices" complaints. But what you suggest is probably all I might be able to accomplish, presently.

I'd be very happy with a solution that just gets the icon on the browser tab. That's about all that's needed for a baseline "professional website" look in my opinion. I'd much much rather a solution that does that and that doesn't show up on the Apple Touch Bar and in other fringe cases, rather than having no solution.

**Comment by bryevdv** [comment]
Marking `completed` let's have separate new issues for any future refinements.
