### ISSUE TITLE
[FEATURE] Autobuild docker images

### ISSUE THREAD

**Issue by Karel-van-de-Plassche** [bokeh/bokeh#9094]
Maybe we should add tests for the Dockerfiles and/or auto-update and push to our docker repository https://cloud.docker.com/u/bokeh/repository/docker/bokeh/bokeh. It seems travis can run docker-in-docker https://docs.travis-ci.com/user/docker/#building-a-docker-image-from-a-dockerfile. Presumably we'd build a Docker container from source every minor version of bokeh, and maybe test the Dockerfile generation every minor version? It takes quite a while to run, so let's not test every commit. Thoughts?

**Comment by bryevdv** [comment]
I don't use these regularly, the only docker file I interact with much is the one in the demo repo for the Elastic Beanstalk deploy for the demo site. I am generally for automating things, but I don't have strong opinions about how in this case due to my inexperience. This seems like it might be  good task for a nightly build, but I don't know if Travis ever added support for that. I think Azure has that option. Otherwise there's not many good options besides per-commit. We would 100% not want to test on a full release tag, so that only leaves dev/rc tags as candidates, and those get pushed pretty randomly.

**Comment by Karel-van-de-Plassche** [comment]
It looks like travis supports cron jobs: https://docs.travis-ci.com/user/cron-jobs/ So it seems we could run test nightly/weekly. 

Looks we can also trigger a Docker image build for dockerhub every tag: https://stackoverflow.com/questions/28590638/can-i-trigger-travis-ci-to-build-my-app-by-creating-git-tag

**Comment by bryevdv** [comment]
@ianthomas23 is this issue useful to you? If not, we can close

**Comment by ianthomas23** [comment]
@bryevdv Yes, we may as well close it. We have the Docker discussion https://github.com/bokeh/bokeh/discussions/12235 and when we have the full set of CI runs passing I will finish off the PR (https://github.com/bokeh/bokeh/pull/12351) so that we can use it as part of our usual CI.
