### ISSUE TITLE
[BUG]line_color not accepting columndatasource fields for line

### ISSUE THREAD

**Issue by MikeWoodward** [bokeh/bokeh#9164]
The line_color argument for the line glyph does not accept ColumnDataSource field names when similar arguments for other glyphs do.

Here's some code that shows the problem:

```
import pandas as pd

from bokeh.models import ColumnDataSource
from bokeh.plotting import figure, show

df = pd.DataFrame({'x': [0, 1, 2, 3, 4],
                   'y': [0, 2, 4, 6, 8],
                   'color': ['blue', 'blue', 'blue', 'blue', 'blue']})
dfs = ColumnDataSource(df)

f = figure()
f.line(x='x', y='y', source=dfs, line_color='color')
show(f)
```
This gives the error message:

ValueError: expected an element of either Enum('aliceblue', 'antiquewhite', ...
Byte(Int, 0, 255), Byte(Int, 0, 255)), Tuple(Byte(Int, 0, 255), Byte(Int, 0, 255), Byte(Int, 0, 255), Percent) or RGB, got 'color'

Here's an example of the same thing working for the circle glyph:

```
import pandas as pd

from bokeh.models import ColumnDataSource
from bokeh.plotting import figure, show

df = pd.DataFrame({'x': [0, 1, 2, 3, 4],
                   'y': [0, 2, 4, 6, 8],
                   'color': ['blue', 'blue', 'blue', 'blue', 'blue']})
dfs = ColumnDataSource(df)

f = figure()
f.circle(x='x', y='y', source=dfs, line_color='color')
show(f)
```
Bokeh version 1.3.4
Python version 3.7.0
Mac version OSX 10.14.6
Chrome version 76.0.3809.100

**Comment by bryevdv** [comment]
@MikeWoodward The behavior is different because the underlying connected topology of `line` is different. N points for `circle` gets you N circles. N points for `line` gets you only a single line (with N points) So, I am not sure what you are expecting, but the `line` glyph only draws a *single* line, and therefore can only be configured with a *single* color. The error message is exactly what is expected and intended. 

If you want to draw multiple lines with a list different colors to use for each sub-line, you should look at `multi_line`. If you want a single line that changes color along its length, that is not supported by `line` (but could be approximated with `multi_line`)

**Comment by MikeWoodward** [comment]
I want to change the color of a line in an app. To do this, I want to tie the color to ColumnDataSource so when I update ColumnDataSource the line changes color automatically. 

I have multiple glyphs (quad, circle) that can represent the same data that I display under different conditions. They're all tied to my ColumnDataSource. I wanted to change colors just by changing one field in my ColumnDataSource.

**Comment by bryevdv** [comment]
There is no way to do what you are asking. For `line` specifically, you will have to change the color property of the glyph directly:

```
r = p.line(...)

# later

r.glyph.line_color = "blue"
```

Since these are really support/usage questions I would ask that anything else move to the project Discourse:

https://discourse.bokeh.org
