### ISSUE TITLE
[FEATURE] SVG export for gridplot

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#9169]
Currently export of a gridplot works for export png but not for svg. 

With svg you get a series of plots back and have to manually compile.

User jcacbelos on discourse seems to have a start at something that works: https://discourse.bokeh.org/t/generate-svg-images-from-bokeh-plots-and-include-them-in-a-pdf-report-with-using-svglib-and-reportlab/3889

**Comment by chesucr** [comment]
I am "jcacabelos"

Actually I export the plots as SVG files individually, with the `export_svgs` function. Then I create a PDF file including all of them, not a SVG file.

But what you want is to export an unique SVG file with all the plots in a gridplot right? Or you just want to export them one by one (the same you do with the PNG files)? I think having both options would be a nice feature

**Comment by mattpap** [comment]
> Currently export of a gridplot works for export png but not for svg.

The "export" part should be emphasized, because otherwise bokeh can't save a gridplot as a PNG, only as a sequence of PNGs. This is because gridplot's implementation doesn't live up to its name and produces a composite layout. We can export such layout as a single PNG, because export utility captures a screenshot of an entire page where a gridplot was rendered.

When issue https://github.com/bokeh/bokeh/issues/3821 is fixed, which is currently work in progress scheduled for bokeh 1.4, it will be possible to put multiple plots on a single canvas, which in turn will allow to save multiple plots a single file (PNG or SVG). At bokeh 2.0, `gridplot()` will produce an instance of a single canvas `GridPlot` model. The old behavior will still be possible with an existing `GridBox` layout.

**Comment by bryevdv** [comment]
>  At bokeh 2.0, gridplot() will produce an instance of a single canvas GridPlot model.

We will have to conduct some experiments to validate that single-canvas performance is acceptable, first.

**Comment by birdsarah** [comment]
>> At bokeh 2.0, gridplot() will produce an instance of a single canvas GridPlot model.
> We will have to conduct some experiments to validate that single-canvas performance is acceptable, first.

This is very exciting. 

Regarding performance I would be happy to accept poor performance in the case where I was trying to do an svg export.

Happy to help test / chip in on that!

Thanks for the clarification @chesucr. the pdf arrangement is useful to me while other solutions are coming along but it sounds like @mattpap is working up a proper solution.

**Comment by bryevdv** [comment]
I am going to move this to `short-term` since there is zero chance I will be able to do anything for it for 1.4 at least. If someone else has the bandwidth to submit a PR within the next few weeks, it coudl be considered for 1.4

**Comment by bryevdv** [comment]
Looks like there are some issues with this in the 2.2 release packages, re-opening and marking for 2.3
