### ISSUE TITLE
[BUG] sizing_mode='stretch_width' makes plot too wide if scrollbar is showing

### ISSUE THREAD

**Issue by jnettels** [bokeh/bokeh#9208]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Windows 10
Google Chrome: Version 76.0.3809.132 (Offizieller Build) (64-Bit)
Firefox: 68.0.2
Microsoft Edge: 44.1862.267.0
Bokeh: 1.3.4
Python: 3.7.1

#### Description of expected behavior and the observed behavior
I guess this is related to #7645 and #7677. In all browsers, ``sizing_mode='stretch_width'`` stretches a figure to the total width of the browser (as desired).
If, however, the layout is tall enough to require a vertical scrollbar, the stretched width stays the same. A couple of pixels are therefore hidden under the scrollbar and a horizontal scrollbar appears at the bottom of the screen.
One could either implement a hardcoded gap that is always present or try to read the effective width including the scrollbar from the browser. Sadly, I have no clue how hard that might be.

#### Complete, minimal, self-contained example code that reproduces the issue
Small height works fine:
```
from bokeh.io import show
from bokeh.plotting import figure
p = figure(plot_height=100, sizing_mode='stretch_width')
p.line([1, 2, 3], [1, 2, 3])
show(p)
```
Large height causes the scrollbar to appear and the figure is cut off:
```
from bokeh.io import show
from bokeh.plotting import figure
p = figure(plot_height=9000, sizing_mode='stretch_width')
p.line([1, 2, 3], [1, 2, 3])
show(p)
```

#### Screenshots or screencasts of the bug in action
![bokeh_scale_width](https://user-images.githubusercontent.com/8526498/64027902-f974b980-cb41-11e9-8ef5-a1afcd865f61.png)

**Comment by julioasotodv** [comment]
@jnettels thank you for reporting this. I was seeing my "stretch_width" widgets grow beyond its parent divs and was driving me crazy! At least now I know the error was not in my code...

**Comment by benlipson** [comment]
Maybe it's the same thing; I find the same problem with stretch-both.

85.0.4183.83 (Official Build) (64-bit) (cohort: Stable)
--
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Windows 10 OS Version 2004 (Build 19041.450)
JavaScript | V8 8.5.210.20

![image](https://user-images.githubusercontent.com/3837169/93490325-30d51600-f8bd-11ea-9887-84c5025e5079.png)

**Comment by jnettels** [comment]
In case anyone still cares: One workaround is creating a margin of e.g. 9 pixels on the right side, by adding this argument to the figure:
```p = figure(plot_height=9000, sizing_mode='stretch_width', margin=(0, 9, 0, 0))```
See:
https://docs.bokeh.org/en/latest/docs/reference/plotting/figure.html?highlight=bokeh.plotting.Figure.margin#bokeh.plotting.Figure.margin

It allows seeing all the toolbar icons on the right. This does not prevent the horizontal scroll wheel, though :-(

**Comment by jmranger** [comment]
A few more details - although I'm using `scale_width`, not `stretch_width`
- this issue is still present in bokeh 2.4.3
- it is a regression - it was not present in 0.12.7, although this is debatable - 0.12.7 was much less aggressive in using the screen space. Using this as the test code:
```
import bokeh
from bokeh.io import show
from bokeh.plotting import figure
print(bokeh.__version__)
p = figure(sizing_mode='scale_width')
p.line([1, 2, 3], [1, 2, 3])
show(p)
```
The render from 0.12.7:
![0 12 7](https://user-images.githubusercontent.com/12662295/182031667-41e4d616-6961-446a-81b6-f73b827f6780.png)
Compared to 2.4.3:
![2 4 3](https://user-images.githubusercontent.com/12662295/182031710-500708ce-c345-45ff-aa53-1047596442ae.png)
- I tried to use the "new" `width_policy` instead, but it suffers from the same issue:
```
from bokeh.io import show
from bokeh.plotting import figure
p = figure(height=9000, width_policy='max')
p.line([1, 2, 3], [1, 2, 3])
show(p)
```
![widthpolicy](https://user-images.githubusercontent.com/12662295/182031907-ec821ef2-8809-462a-89ad-19c4b5aa7af0.png)

I'm really looking forward to a workaround for this one - I'm stuck at 0.12.7 for the time being.
