### ISSUE TITLE
Add support for globs to `bokeh serve`

### ISSUE THREAD

**Issue by jsignell** [bokeh/bokeh#9209]
I have been working on a way to make it easier to use `panel serve` to launch deployments at a proxied port on `jupyter notebook` calls, so that your deployment shows up at `localhost:8888/panel`. I've got this working for cases where you have a dir with one notebook in it called main.ipynb, but I'd like to have it look at all the notebooks and generate an index. This would be equivalent to calling `panel serve *.ipynb` but using a flag instead. The reason for the flag is that it isn't possible to pass the * in the [proxy code](https://github.com/pyviz/jupyter-panel-proxy/blob/b0d483d2774d159a065eae3432854d1196c8b5e0/panel_server/__init__.py#L3):

```
'command': ["panel", "serve", ".", "--allow-websocket-origin=*", "--port", "{port}", "--prefix", "{base_url}panel"],
```

For context this functionality would make it very easy to deploy apps on binder. The user would just need to include jupyter-panel-proxy in their env and stick `?urlpath=panel` at the end of the binder url.

These are the relevant PRs:
  - https://github.com/pyviz/jupyter-panel-proxy/pull/1
  - https://github.com/pyviz-demos/glaciers/pull/11

If we were able to add the `--all-notebooks` flag, then I'd be happy to write a jupyter-bokeh-proxy as well :)

**Comment by jsignell** [comment]
I see that @bryevdv, you've been touching the serve code recently, so just wanted to check that this would be a reasonable thing to add from your perspective.

**Comment by bryevdv** [comment]
@jsignell I am still missing some context. Why can't you just call `bokeh serve` with all the individual notebooks on the command line on your end? (i.e. you figure out what all those need to be, and the pass them explicitly). Currently the notion of "directory style app" is very clear and delineated with no "except in this case"es or "almost always behaves this way"s. I'd really prefer to try and not muddy the waters.

**Comment by mattpap** [comment]
> The reason for the flag is that it isn't possible to pass the * in the proxy code:

I think that it's not the case that it isn't possible to pass `*`, but that there's a difference between:
```
bokeh serve *.ipynb
```
and
```
bokeh serve '*.ipynb'
```
The former one uses shell expansion, whereas the later pass on a verbatim glob. This gets worse when spawning a subprocess, e.g. with `Popen`, because then you would drop those quotes (assuming not using shell mode).

So, if I read this feature request correctly, all you actually need is support for globs in `bokeh serve`, and (I suppose) a `GlobHandler`, that would accompany `DirectoryHandler`, without altering its current semantics. If that's the case, I think it would be a nice addition.

**Comment by bryevdv** [comment]
Ok now I actually understand the context. I agree it it probably nicer to make 
 ```
 bokeh serve '*.ipynb'
```
work. I'm not sure about a new application handler, though. I think I would instead suggest confining changes to `bokeh.command`, i.e. detect `*` in the command line args as early as possibly and emulate shell expansion there, before passing the expanded list on to downstream `bokeh.sever`. That is, basically right in before this line:

https://github.com/bokeh/bokeh/blob/05be3eb0133bf5fac82484536c71500c30900dad/bokeh/command/subcommands/serve.py#L592

**Comment by bryevdv** [comment]
Thinking more, if we are going to do our own globbing internally, then *that* should probably be configurable, e.g. via `--no-glob` or similar. Otherwise we leave no avenue for users to run files that do actually have literal asterisks in them. But `--no-glob` (or whatever) is easy to explain and document and does not have interactions with anything else.

**Comment by mattpap** [comment]
I think that the default should be no glob (or no magic in general), so the command would be e.g. `bokeh serve --glob notebooks/**/*.ipynb`.

**Comment by jsignell** [comment]
I'm fine with the suggestion to do our own globbing and agree that it is preferable to an `--all-notebooks` flag. I think having the ability to turn off the globbing also seems reasonable.

> the default should be no glob

@mattpap that changes the default behavior on a feature that we are using in long-lived projects. Is that really preferable?

**Comment by bryevdv** [comment]
> that changes the default behavior on a feature that we are using in long-lived projects. Is that really preferable?

I don't think it does? Currently we always get shell globbing for 
```
bokeh serve *.py
```
And we always will&mdash;we have no ability to affect or turn off shell globbing. My understanding of this issue is that it is desirable that this *also* work:
```
bokeh serve '*.py'  
```
But that does not work because the shell does not apply in quotes. So the proposal (as I understand it) it to allow 

```
bokeh serve --glob '*.py'  
```
for cases when this might arise (e.g. calling a subprocess without `shell=True`)

**Comment by jsignell** [comment]
Ah sorry yes that is true. Ok I am good with the suggestion.
