### ISSUE TITLE
Svg backend cannot draw annular_wedge correctly [BUG]

### ISSUE THREAD

**Issue by ruoyu0088** [bokeh/bokeh#9213]
Here is the code:

```
from bokeh.plotting import figure, show

p = figure(plot_width=400, plot_height=400, output_backend="svg")
p.annular_wedge(x=[1, 2, 3], y=[1, 2, 3], inner_radius=0.1, outer_radius=0.25,
                start_angle=0.4, end_angle=4.8, color="green", alpha=0.6)

show(p)
```

and the output:

![chrome_2019-09-05_11-31-37](https://user-images.githubusercontent.com/826871/64307362-d2e6d080-cfd0-11e9-8f51-fd82d71bc65f.png)

**Comment by bryevdv** [comment]
Confirmed this on master. @ruoyu0088 please always provide the requested version information. 

Unfortunately, Bokeh relies on a third party library for Canvas<->SVG conversion, and this bug is almost certainly in that library. It's possible that there is simply a new version we can update to that fixes the problem, but AFAIK it is not under heavy development, so I am not to hopeful of that. Just to set expectations: if we have to fix things ourselves on a fork of the library, it will probably not be done anytime soon.

**Comment by mattpap** [comment]
> (...) but AFAIK it is not under heavy development (...)

`canvas2svg` isn't maintained anymore, so we shouldn't expect any bug fixes like that happen on its own. I think we will have to look into alternatives in the long term.
