### ISSUE TITLE
[BUG] Hovertool datetime formatting doesn't work with pandas datetime column

### ISSUE THREAD

**Issue by AntonSavchenko** [bokeh/bokeh#9217]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 1.3.4
python 3.7.4
jupyterlab 1.1.1
pandas 0.25.1
ubuntu 18.04.3 LTS
chromium browser

#### Description of expected behavior and the observed behavior
Tried adding a hovertool to a plot with datetime axis, it doesn't seem to work - instead the value is converted to an int.

By the way, the user guide page
https://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#hovertool
is inconsistent - you never show an example where the HoverTool is defined and added to the plot - there are separate code snippets for manipulating the HoverTool object, but whenever you show the plotting part, you only use TOOLTIPS list

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.models import HoverTool
import bokeh.plotting as bkp
import pandas as pd

source = bkp.ColumnDataSource(data=dict(
    index=pd.to_datetime(['2015-08-17','2015-08-18','2015-08-19']),
    x=[1,2,3],
    y=[3,2,1]))

# There are two variants listed in the guide, neither seem to work
# hover = HoverTool(tooltips=[('Date','@index'),('x','@x'),('y','@y')],mode='vline')
# hover.formatters = {'index':'datetime'}

hover = HoverTool(tooltips=[('Date','@index'),('x','@x'),('y','@y')],
                  formatters = {'index':'datetime'},
                  mode='vline')

p = bkp.figure(x_axis_type='datetime',tools=[hover])
p.circle(x='index',y='y',source=source)
bkp.show(p)
```

#### Screenshots or screencasts of the bug in action
![Bokeh_hovertool_formatter](https://user-images.githubusercontent.com/22128555/64537129-87a72780-d31a-11e9-9d88-083e015b1734.png)

**Comment by bryevdv** [comment]
@antonSavchenko `index` specifically seems to require the more explicit syntax with `@`:
```
hover = HoverTool(tooltips=[('Date','@index'),('x','@x'),('y','@y')],
                  formatters = {'@index':'datetime'},
                  mode='vline')
```

<img width="416" alt="Screen Shot 2019-09-09 at 9 24 00 AM" src="https://user-images.githubusercontent.com/1078448/64548725-12b8fb00-d2e4-11e9-9f34-a64ae281dae7.png">


Note that in upcoming BoKeh 2.0 the `@` prefix will be mandator for *all* CDS fields in a formatters dict. Both because that allows formatters to also work on special `$` values, and also because it makes it more clear what needs to line up with what (have had many support questions where people tried to line up the  *tooltip label* rather than then CDS column name, and mandating this syntax makes it evident that the formatter key must be a column)

> By the way, the user guide page https://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#hovertool is inconsistent 

Core devs are pretty underwater right now, we would welcome your contribution to improve that section. The relevant file is here:

https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/user_guide/tools.rst

**Comment by AntonSavchenko** [comment]
To be honest, my first version had the '@index', but firstly, it did not help (the hover is still an integer, not the datetime), and secondly, any mention of the formatter for hovertool that I found in the docs didn't have the @.

I tested it once more, this time on a freshly installed Anaconda on windows 10 - same bokeh 1.3.4, same error, even with the "@index"

**Comment by bryevdv** [comment]
Sorry, I shouldn't try to answer issues on a train. I was looking at the axis, not the tooltip. So ignore what I said before, the issue is that you are not providing any format for the formatter to use:
```
hover = HoverTool(tooltips=[('Date','@index{%F}'),('x','@x'),('y','@y')],
                  formatters = {'index':'datetime'},
                  mode='vline')
```

<img width="426" alt="Screen Shot 2019-09-09 at 2 16 37 PM" src="https://user-images.githubusercontent.com/1078448/64567252-aa324400-d30c-11e9-883e-b4a9bb153f06.png">

And giving a format is demonstrated in the docs for every example. As a gentle suggestion,  if something is not very clearly a but, please start with a topic on the Discourse. If it is determined there is a bug, we will certainly ask for a GH issue.

**Comment by AntonSavchenko** [comment]
Oh, sorry, that's my bad, I definitely started with the {%F}, but probably at the beginning had other issues and since I didn't understand what the '%F' is for, I erased it to try and reduce ambiguity...
Sorry again, will keep the Discourse in mind.

**Comment by bryevdv** [comment]
The formats are listed here:

https://docs.bokeh.org/en/latest/docs/reference/models/formatters.html#bokeh.models.formatters.DatetimeTickFormatter
