### ISSUE TITLE
[FEATURE] Make INLINE resources configurable for Sphinx

### ISSUE THREAD

**Issue by maxbsp3** [bokeh/bokeh#9223]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh Project Discourse](https://discourse.bokeh.org).

**Is your feature request related to a problem? Please describe.**
Sphinx extension bokeh_plot directive resources defaulted to cdn which is an issue when working on computers that are not connected to the internet

**Describe the solution you'd like**
A workaround for cdn resources

**Describe alternatives you've considered**
Monkey patch on conf.py file as below:

```python
def get_sphinx_resources(include Bokehjs api-false):
    from bokeh.resources import INLINE
    return INLINE

import bokeh.sphinxext.util as util
util.get_sphinx_resources = get_sphinx_resources
```

**Additional context**

**Comment by bryevdv** [comment]
I'll go ahead and mark it `feature` but @maxbsp3 chances are much higher that it would go in sooner if you decide to work up a PR yourself (happy to offer guidance)

**Comment by bryevdv** [comment]
Since there has been no further interest expressed in this, I am going to close. The use-case of developing Bokeh docs behind an airgap does not seem common, and a trivial workaround is documented above in case it is really necessary. 

I'd additionally mention `BOKEH_DOCS_CDN="local"` is also an option for using a locally built BokehJS as well.
