### ISSUE TITLE
CustomJS change.emit() Filtered DataFrame

### ISSUE THREAD

**Issue by koti-Maddala** [bokeh/bokeh#9246]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh Project Discourse](https://discourse.bokeh.org).

**Is your feature request related to a problem? Please describe.**
I have a Bokeh Layout with 20 plots generated from one data source (panda DataFrame with 30 columns).

And there are 2 Select Widgets added to filter the pandas DataFrame.

I want to update all the plots with these 2 Select widgets (basically I would like to filter the data frame) base on these 

**Describe the solution you'd like**
Filter the whole dataFrame at once based on Select widget input from customJS callback.

**Describe alternatives you've considered**
Already able to filter the data by filtering based on Select input and using "push" function iterating through rows and checking the condition

Issue with above method: i have to  push all the 30 columns and additional calculation in customJS to update my whole bokeh layout

**Additional context**

**Comment by bryevdv** [comment]
@koti-Maddala I am not really sure what you are asking for based on the information above. Offhand, this seems more like a support question, in which case the appropriate venue is the [Project Discourse](https://discourse.bokeh.org). Otherwise, if you do want to propose some new feature then it needs to be much more fleshed out, e.g proposed syntax or new API

**Comment by koti-Maddala** [comment]
My Bad, I would post it in the Project Discourse
