### ISSUE TITLE
It is not possible to set a Range1d / DataRange1d with datetime.time value

### ISSUE THREAD

**Issue by SteveAlexander** [bokeh/bokeh#9251]
Exactly as https://github.com/bokeh/bokeh/issues/5426 but for datetime.time values

e.g. the following doesn't work, and gives a ValueError

```python
yrange1 = Range1d(start=datetime.time(8, 0, 0) ,end=datetime.time(10, 0, 0))
```

This is because Range1d / DataRange1d don't allow time values, even though they will be transformed correctly from (say) a dataframe into a CDS.

As a workaround, using `from bokeh.util.serialization import convert_datetime_type` seems to work fine for adapting times into numbers. 

bokeh 1.3.5.dev3
python 3.7.3

**Comment by bryevdv** [comment]
@SteveAlexander Range start/end accept ***date***times, or time ***deltas***:

```
    start = Either(Float, Datetime, TimeDelta, default=0, help="""
    The start of the range.
    """)

    end = Either(Float, Datetime, TimeDelta, default=1, help="""
    The end of the range.
    """)
```

It's not exactly clear to me what the expectation should be for passing only a pure time value, since that could only really be interpreted as a time on the very first day of EPOCH, which seems arbitrary and not especially useful in general. 

Not saying nothing should be done, just that this requires a little more discussion/thought.

**Comment by SteveAlexander** [comment]
Thanks! I'll offer some detail about what I'm doing, as maybe that will help thinking about what's useful vs confusing.

My specific use is that I'm displaying a sparkline-style chart of a day's activity. It was very straightforward to take my DataFrame with an index made up of times, and make a CDS from this. The chart plotted fine.

But when I tried to use a Range1d to constrain the x axis, I found I couldn't use the same units as had worked fine for the data's index.

So, from a principle of intuitiveness, I'd propose that Range1d should accept the same date / time types as work in a CDS. So, that's any converted by `convert_datetime_type`.

**Comment by bryevdv** [comment]
That would convert time values to milliseconds since epoch, i.e. to datetime values for times on the "first day". That seems technically wrong (pure time values do not have a date component and this would force them to have a fake one) as well as something that could lead to confusion. I think a better approach might be to represent times as number of floating point hours since midnight, and then use an appropriate tick formatter to show values on the axis as times.

**Comment by SteveAlexander** [comment]
@bryevdv That makes sense to me

**Comment by bryevdv** [comment]
I don't think there is any action here
