### ISSUE TITLE
[Suggestion] Adopt github actions

### ISSUE THREAD

**Issue by ammarnajjar** [bokeh/bokeh#9284]
## Description:
[Github actions beta](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/) are now available for all open source repositories and integrated into github. The first release is planned on November 13th 2019.

This issue is a suggestion to replace the current CI/CD pipeline with github actions.

### Pros:

- Better [Usage Limits](https://help.github.com/en/articles/about-github-actions#usage-limits) (concurrent jobs/workflows, API requests, timeouts.. )
- One central place to manage CI/CD pipelines. Currently there are two pipelines, one for windows using appveyor, and another for linux using travis-ci.
- Support for latest Windows/MacOS/Ubuntu out of the box.
- Support caching inside the same job.
- There is an [open issue](https://github.com/actions/toolkit/issues/47) to support caching on the workflow level, and @joshmgross is currently [working](https://github.com/actions/toolkit/issues/47#issuecomment-540331125) on it.
- Integrated, actively developed and backed up.

### Cons:
- New tool, new syntax, ...
- In beta for now, so you have to sign up for the beta program in order to use it.

## More Info:
- Sign up for beta -> https://github.com/features/actions
- Github help -> https://help.github.com/en/articles/about-github-actions
- Toolkit repository -> https://github.com/actions/toolkit
- Node setup -> https://github.com/actions/setup-node
- Python setup -> https://github.com/actions/setup-python

### Alternatives to consider:
 
- Azure pipelines: 
    - https://github.com/apps/azure-pipelines
    - https://azure.microsoft.com/en-us/services/devops/pipelines/

**Comment by bryevdv** [comment]
There are definitely things I would like to use GH actions for but at least for now I see it as a  complement, rather than a replacement. First worth mentioning: GH Actions are built directly on Azure Devops, they are for all intents and purposes indistinguishable. Not sure that are worth consider separately except perhaps as a matter of increased capacity. 

In any case, there are other cons:

*Since  GH Actions is based on Azure Devops, they have a separate process for each stage. This plays poorly with a conda-envoronment based scenario because there is no way to set an env up front once at the start of a build, it has to keep being set on every stage

* GH actions does not support regex for branch selection. The simple glob syntax is not sufficient to distinguish our different /dev/rc/release version tags. We cannot change our tag/versioning scheme as that is a *huge* risk (version tie directly in to BokehJS CDN deployment and loading, etc.) That means TravisCI will have to run at least the release build for the foreseeable future. 

My own suggestion would be:

* Get test builds running on windows and osx on GH actions as a start, and phase out Appveyor. That keeps the number of tools we have to deal with neutral but does signifiantly increase testing bandwidth. From there we can figure out if Linux should move too, and we could leave just release builds on Travis CI.

Also AFAIK we re already out of the beta and an use GH Actions any time.

**Comment by ammarnajjar** [comment]
> Get test builds running on windows and osx on GH actions as a start, and phase out Appveyor. That keeps the number of tools we have to deal with neutral but does signifiantly increase testing bandwidth. From there we can figure out if Linux should move too, and we could leave just release builds on Travis CI.

👍

**Comment by ammarnajjar** [comment]
I have opened #9336, please review 😄

**Comment by bryevdv** [comment]
This was done
