### ISSUE TITLE
[Question] Why does the Boilerplate contain unnecessary code?

### ISSUE THREAD

**Issue by ammarnajjar** [bokeh/bokeh#9288]
## Background:
While I was browsing the source code, I noticed that the following piece of code is included in so many python modules, even when it is not used there:

```python
import logging
log = logging.getLogger(__name__)
```
grep with:

```bash
grep -rn "log = logging.getLogger(__name__)" bokeh
```

It looks like a part of the Boilarplate.

## The question is:
**Why is this piece of code there when it is not used in the module?**

**Comment by bryevdv** [comment]
It's so that if someone is developing or debugging bokeh there is always a logger ready to use in any situation. It's also aspirational in the sense that it encourages and looks forward to a time when there is more and more consistent logging throughout the library. And lastly it allows the top matter above the imports to be identical across files. Unless a significant performance or other concrete disadvantage can be demonstrated, I would not been favor of removing them.

**Comment by ammarnajjar** [comment]
ok, thanks @bryevdv for the quick response!

**Comment by mattpap** [comment]
To me this is dead code and as such should be removed. This would be more prominent if we disallowed (I suppose in flake8) unused variables across bokeh's Python codebase, the same as we do in bokehjs. Note that this is different from `__future__` imports, which establish semantics of Python language and runtime for all our source code.
