### ISSUE TITLE
[Print Option additional tool in bokeh plot.]

### ISSUE THREAD

**Issue by sameerCoder** [bokeh/bokeh#9301]
Hi,
As like toolbar options - save, zooom in , zoom out , pan Etc .
Same way i am thinking to put Print tool options in toolbar of bokeh plot.
How i can add Print option in  plot so that it can capture the current view of plot as well, As every Web Browser allow Print option

**Comment by bryevdv** [comment]
The only thing available in browsers, AFAIK, is `window.print()`:

https://www.w3schools.com/jsref/met_win_print.asp

I'm not personally inclined to add anything directly in to Bokeh itself:

* No functional difference with print screen options that already exist in the browser menus
* Could be trivially added by any user with a one-line `CustomAction` if they really wanted
* A print of the entire screen is not actually what most people want in most cases

cc @bokeh/dev

**Comment by sameerCoder** [comment]
yes, I have tried window.print() but i was thinking if as print tool come in bokeh then it will be good.

**Comment by bryevdv** [comment]
I'm not sure what you re asking for. You want something built in to Bokeh that uses `window.print`? that does not seem valuable. If you want that, you can make a `CustomAction` as suggested above. If you want something different, then you need to state and actual detailed proposal because I don't know what that would be.

**Comment by bryevdv** [comment]
OK I am going to go ahead and close this. If there is a concrete (detailed) proposal, we can re-open.
