### ISSUE TITLE
test_ext.py hanging on OSX

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9433]
@mattpap as of today this test just hangs indefinitely for me. I can no longer run unit tests without skipping it. Do you have any suggestions to diagnose? I have nodejs 10 installed

**Comment by mattpap** [comment]
This test is indeed slow (takes some 40 s to finish), but should work. Past two days npm site was having issues, so maybe that added to the problem, because the test runs `npm install`, which installs all bokehjs' dependencies. As soon as bokehjs is split, this install time will be significantly reduced. However, we could also mark somehow (e.g. `pytest.mark.slow`) or split off tests that are slow, require external services or heavy dependencies (e.g. `io.export`).

**Comment by bryevdv** [comment]
Well, I let it sit for 5 minutes but I will try again.

**Comment by bryevdv** [comment]
Has randomly started working
