### ISSUE TITLE
Git Required to Install BokehJS?

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9447]
@mattpap Question from a BokehJS user today: 

> Why does installing BokehJS require git on a system?

Looking at our dependencies:

```
  "dependencies": {
    "tslib": "^1.10.0",
    "canvas2svg": "https://github.com/bokeh/canvas2svg#v1.0.21",
    "es5-ext": "^0.10.50",
    "es6-promise": "4.2.6",
    "es6-weak-map": "^2.0.2",
    "es6-map": "^0.1.5",
    "es6-set": "^0.1.5",
    "flatbush": "^3.1.1",
    "gloo2": "https://github.com/bokeh/gloo2.git#b41bd5d",
    "hammerjs": "^2.0.4",
    "nouislider": "^10.0.0",
    "numbro": "https://github.com/bokeh/numbro.git#e1b6c52",
    "pikaday": "https://github.com/bokeh/pikaday.git#6b7258e",
    "proj4": "<2.4",
    "slickgrid": "https://github.com/bokeh/SlickGrid.git#8e993bf",
    "sprintf-js": "^1.1.2",
    "timezone": "^1.0.22",
    "underscore.template": "^0.1.7"
  }
```
Why are things like gloo2 and pikaday, etc *dependencies* and not *devDependencies*? These packages are built in to BokehJS?

cc @mattpap @shughes-uk

**Comment by mattpap** [comment]
bokehjs has to be importable in node, thus all those are production dependencies. Bundles are not the only way bokehjs can be consumed. Though if models and views weren't defined together (each pair in a single module), then most of those dependencies wouldn't be necessary at run time, especially all dependencies that rely on git. This will be fixed in #9296 or after, but definitively in 2.0.
