### ISSUE TITLE
isort error message unhelpful

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#9454]
For example:
```
 AssertionError: isort issues:
E         ERROR: /home/travis/build/bokeh/bokeh/bokehjs/make/tasks/generate_defaults.py Imports are incorrectly sorted.
```
Can I get a diff of what isort would like to see?

**Comment by bryevdv** [comment]
No, but it's not necessary. The appropriate action is to run isort on the
file to fix it.

**Comment by bryevdv** [comment]
I did try to see if e.g. `isort -c --verbose` but it does not. In any case, isort itself is the standard. There is no point to ever trying to fix things "by hand" that is the entire point: that it be automated and without discretion. 

What we can consider doing (there is already an issue) is just running this in `pre-commit` hooks so that it is just guaranteed to be right on ingest, every time.

**Comment by mattpap** [comment]
To my surprise, it has: `isort -df -rc -c . | colordiff`.

**Comment by mattpap** [comment]
Also this is peculiar:
```diff
$ isort -df -rc -c . | colordiff
--- /home/mateusz/repo/bokeh2/examples/app/image_blur.py:before	2019-11-26 15:45:23.700313
+++ /home/mateusz/repo/bokeh2/examples/app/image_blur.py:after	2019-11-26 16:03:54.096396
@@ -1,12 +1,12 @@
 import numpy as np
 import scipy.misc
-from numba import njit
 
 from bokeh.io import curdoc
 from bokeh.layouts import column
 from bokeh.models import ColumnDataSource, Slider
 from bokeh.palettes import gray
 from bokeh.plotting import figure
+from numba import njit
 
 image = scipy.misc.ascent().astype(np.int32)[::-1, :]
 w, h = image.shape
```

**Comment by bryevdv** [comment]
You can tell it known third party libraries in the config, when necessary.

**Comment by mattpap** [comment]
Sure, the problem is that I didn't modify this file and `test_itest` passes in CI. Now after upgrading my environment, it stopped complaining about that file, but complains about `server/django/*`, treating `channels` as bokeh's module. This seems like like a bug in isort.

**Comment by mattpap** [comment]
The problem is that isort determines whether a library is thirdparty or not by inspecting installed packages, at least by default. I didn't have `channels` installed, due to lack of a conda package, so tests failed. Installing it (via pip) "resolved" the issue.

**Comment by mattpap** [comment]
Apparently a tool designed around sorting isn't able to provide output in an ordered manner:
```
AssertionError: isort issues:
E         ERROR: bokeh/command/util.py Imports are incorrectly sorted.
E         ERROR: bokeh/command/subcommands/secret.py Imports are incorrectly sorted.
E         ERROR: bokeh/command/subcommands/static.py Imports are incorrectly sorted.
E         ERROR: bokeh/command/subcommands/info.py Imports are incorrectly sorted.
E         ERROR: bokeh/command/subcommands/__init__.py Imports are incorrectly sorted.
E         ERROR: bokeh/command/subcommands/file_output.py Imports are incorrectly sorted.
E         ERROR: bokeh/command/subcommands/svg.py Imports are incorrectly sorted.
E         ERROR: bokeh/command/subcommands/html.py Imports are incorrectly sorted.
E         ERROR: bokeh/command/subcommands/init.py Imports are incorrectly sorted.
E         ERROR: bokeh/command/subcommands/json.py Imports are incorrectly sorted.
E         ERROR: bokeh/command/subcommands/build.py Imports are incorrectly sorted.
E         ERROR: bokeh/command/subcommands/png.py Imports are incorrectly sorted.
```

**Comment by bryevdv** [comment]
Well, I would guess the number of people who actually look at this output is vanishingly small, so it does not surprise me that it has not gotten any attention. 

FWIW I actually want to make some docker images for all of these tasks:

* isort
* black
* image diff and baseline updating
* BokehJS release build

so that they can be guaranteed to be done consistently across all platforms. (E.g. so I can actually run baselines and get consistency results or so BokehJS can be built locally on release tag)
