### ISSUE TITLE
[BUG] HoverTool in 'vline' mode doesn't work with vertical segments

### ISSUE THREAD

**Issue by graeme-hattan** [bokeh/bokeh#9458]
Bokeh version: 1.4
Python version: 3.7.5
Browser: Firefox / Chromium
OS: Linux

When adding a `HoverTool` with `mode='vline'` to a plot with vertical segments, the tooltip is not displayed.

Example code:

```
from bokeh.io import output_file, save
from bokeh.models import HoverTool
from bokeh.plotting import figure

x = [1, 2, 3, 4]
y0 = [1] * 4
y1 = [2] * 4
fig = figure(tools=[HoverTool(mode='vline')])
fig.segment(x, y0, x, y1)
output_file('vline.html')
save(fig)
```

Screenshot:
![image](https://user-images.githubusercontent.com/1633586/69484939-c2f0c700-0e30-11ea-90e1-ea505bdacbf0.png)

**Comment by graeme-hattan** [comment]
This also affects `hline` mode with horizontal segments:

```
from bokeh.io import output_file, save
from bokeh.models import HoverTool
from bokeh.plotting import figure

x0 = [1] * 4
x1 = [2] * 4
y = [1, 2, 3, 4]
fig = figure(tools=[HoverTool(mode='hline')])
fig.segment(x0, y, x1, y)
save(fig)
```
In the default mode it looks like the segments are treated like they are 4 pixels wide, presumably the effective width in the other modes is zero.

**Comment by sahajsk21** [comment]
I wish to work on this issue but can someone clearly explain what is meant by "the tooltip is not displayed".

**Comment by bryevdv** [comment]
@sahajsk21 The issue is referring to the hovering display for the Hover Tool:

https://docs.bokeh.org/en/1.4.0/docs/user_guide/tools.html#hovertool

**Comment by kumaran-14** [comment]
@bryevdv Can I take this up?
I've looked at the demo and reproduced the behaviour.
The link which you provided shows the correct usage which shows data on `vline` type hover.
I can try dig in to find out why this happens. What do you think about this?

**Comment by bryevdv** [comment]
@kumaran-14 Any one can take up any issue they please :) I think it would be great if you are able to look in to this. Specifically, the hit testing for `Segment` glyphs agains "spans" (e.g. a vline or hline) is here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/glyphs/segment.ts#L95-L124

That's probably what would need to be modified.

**Comment by kumaran-14** [comment]
@bryevdv I tried to find the cause of this issue. Take a look at this case where it works.

```
x = [2, 4]
x0 = [2.5, 4.5]
y0 = [1.5, 1.5]
y1 = [1.75, 1.75]
fig = figure(tools=[HoverTool(mode='vline')])
fig.segment(x, y0, x0, y1)
```

![bokehvline](https://user-images.githubusercontent.com/32682103/74978627-06b89400-5453-11ea-9390-a885d5a71af1.gif)


The problem is only when it is a straight line.
At `_hit_span` function in file `bokehjs/src/lib/models/glyphs/segment.ts`, 
```
    for (const i of candidates) {
      if ((v0[i] <= val && val <= v1[i]) || (v1[i] <= val && val <= v0[i]))
        hits.push(i)
    }
```
where `v0` and `v1` are segment's `x` coordinates.
Now the `val` is the cursor `x` coordinate and is a high precision floating point value and is never accurately equal to `v0` and `v1` when the segment is a straight line ( when `v0` and `v1` are equal )

**Comment by bryevdv** [comment]
@kumaran-14 That seems about right, how do you propose to resolve the problem?

**Comment by kumaran-14** [comment]
@bryevdv A straight forward way would be to have a small horizontal range over which we say this is a hit with vertical segment.

**Comment by bryevdv** [comment]
@kumaran-14 For sure, and I presume a corresponding change for the `hline` with horizontal segment as well? (I think any PR for this should fix both cases at once). Do you have a concrete proposal for the amount of "epsilon" to add around the comparison?

**Comment by kumaran-14** [comment]
@bryevdv Yes for hline too. I don't have a definite value but the important issue is that epsilon value should scale with the geometry.

**Comment by bryevdv** [comment]
@kumaran-14 perhaps the comparisons can be changed to be in "pixel-space" instead of "data-space"? In which case I fixed epsilon of e.g. 0.5 (of a pixel) on either side might be sufficient.

**Comment by kumaran-14** [comment]
@bryevdv That sounds great. How would I convert the values into pixel-space?

**Comment by kumaran-14** [comment]
@bryevdv how would I do that?

**Comment by bryevdv** [comment]
@kumaran-14 the span coordinate geometry comes in as pixel coordinates. You can see that scale `invert` function is use to convert to back to "data space" (so that the spatial index an be used to get a first batch of potential hits). Scales also have a `compute` method, you can use that to convert segment data coordinates to pixel coordinates in a similar way, for the final comparison.

**Comment by kumaran-14** [comment]
@bryevdv In [Segment.ts](https://github.com/bokeh/bokeh/blob/b7649074fdf127a5c30471f9e3dd50a4477aa1ef/bokehjs/src/lib/models/glyphs/segment.ts#L102-L124), I'm doing this.

```
    const val_px = this.renderer.yscale.compute(val)
    console.log("################", val_px)
 
    for (const i of candidates) {
      const v0_px = this.renderer.yscale.compute(v0[i])
```
I get negative values in both cases. Am I doing it correctly?

**Comment by bryevdv** [comment]
@kumaran-14 actually you should be able to access the screen coords for the glyph without any work. They are in `this.sx1`, `this.sy1` etc

**Comment by kumaran-14** [comment]
@bryevdv 0.5 was too small. So I increased that to 2.5. This works for me. Could you try out this and let me know. If it is, I can proceed to make a pr.
```
    for (const i of candidates) {
      if ((v0[i] <= val && val <= v1[i]) || (v1[i] <= val && val <= v0[i]))
        hits.push(i)
      
      if (v0[i] == v1[i]) {
        if (geometry.direction == 'h') {
          if (Math.abs(this.sx0[i] - sx) <= 2.5) {
            hits.push(i)
          }
        } else {
          if (Math.abs(this.sy0[i] - sy) <= 2.5) {
            hits.push(i)
          }
        }
      }
    }
```

**Comment by bryevdv** [comment]
@kumaran-14 It's usually advised to just make a PR. At this stage that is an easier place to collaborate (the reason I did not see this before is that there are many many issues and it's easy for issue comments to get lost, that's much less likely with PRs since there are usually not that many open)

Offhand, I might believe 0.5 is too small, but 2.5 seems too big. Did you try intermediate values, e.g. 1?

**Comment by kumaran-14** [comment]
@bryevdv yes. I did try 1. It was kind of hard to detect a hit. Even with 2.5 it's still hard to detect. But I think it is reasonable now.

**Comment by bryevdv** [comment]
OK well  let's make a PR and go from there (there other reason to make a PR earlier is that it is *much easier* for other people to try out a PR)
