### ISSUE TITLE
Add to the User Guide a complete list of graphs that can be created using Bokeh [FEATURE]

### ISSUE THREAD

**Issue by samcoh** [bokeh/bokeh#9495]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

**Is your feature request related to a problem? Please describe.**
This feature request is related to increasing understandability and usability of the bokeh library for new users. There should be a table created that shows every graph that can be created using bokeh. I am still exploring new functionality and capability of the software and I have been using this library for awhile. In order to decrease learning curve, a table should be created of all the graphs that can be created using this module. 

**Describe the solution you'd like**
A table located in the User Guide section of the website that outlines every visualization that can be created (in the simplest form) and a description of when you would use this visualization. More specifically, the table should include columns like Graph Type, Bokeh Name, and Description. Graph Type would state the type of graph, for example regular bar graph. In the Bokeh Name column the field should state the name of the graph in bokeh. If the graph is a regular bar graph, under this column this field would state hbar. Lastly, the description column would state a description of the graph and when it could be used (especially useful for more complex graphs). 

**Describe alternatives you've considered**
There needs to be one central place to find all the different graphs you can create for new users. This will increase the user experience of library. Having example graphs throughout the website is confusing for new users who want to learn about ways to use the library. 

**Additional context**
https://docs.bokeh.org/en/latest/docs/user_guide.html
A link should be added that states "All Graphs" . This link should take users to a page that shows a large table of the type of graph (i.e., hbar)

**Comment by bryevdv** [comment]
@samcoh While I agree in principle, I think it's worth clarifying terminology. Bokeh is *very much* centered around the concept vectorizable visual glyphs. I.e. Bokeh has a lot of *shape types* that you can throw arrays of data at to produce lots of those shapes. These can be used to draw *any* sort of chart you want (some very easily, some less so). But Bokeh does not have a notion of Schematized Chart Types, e.g. Bar Plot, Histogram, Pie Chart, TimeSeries, Candlestick Plot, etc. Bokeh can *render* all of these kinds of plots (and there are many examples of each in the docs/examples), but there are not "named" classes or functions for them, so the notion of "Bokeh Name" is not a useful one. Instead, it would be meaningful to talk about *"what glyphs are needed to make this kind of chart"* (plural because some charts need mulitple glyph types). 

*(As an aside: If you want that kind of very-high-level schematized plotting API, you might consider tools built on top of Bokeh, such as [Holoviews](http://holoviews.org/), [Chartify](https://github.com/spotify/chartify), or [Pandas-Bokeh](https://github.com/PatrikHlobil/Pandas-Bokeh))*

I don't think it's possible to enumerate "all graphs" that can be drawn with Bokeh, and I also don't think that would be valuable, strictly speaking. E.g. Bokeh can draw [this historical plot by Burtin](https://docs.bokeh.org/en/latest/docs/gallery/burtin.html) but that's mostly just an interesting display of capability, not something anyone else would ever really want to duplicate, or that is worth cluttering such a list with. 

So, I'd propose a "Howto" sort of section. It would have subsections for several *common* Chart types, that contain a general description of how this chart type can be made with Bokeh, list all the glyphs that are used for this kind plot, provide a basic example, and link to other relevant sections in the docs. Then, your table idea (which I really like) could become a visual Table of Contents that links to all these subsections.

What do you think about this? Also, is this something you are interested to collaborate on?

**Comment by samcoh** [comment]
@bryevdv I really like your modified idea! I think that is a great solution. I would be interested in helping create this table; although, I would feel most comfortable assisting in this project if other collaborators also helped me create this table.

**Comment by bryevdv** [comment]
@samcoh For sure, I am happy to help with this issue to start, and we can see if we can interest other people in pitching in over time, as well. I would say a good "first task" is simply to enumerate all the "high level chart types" that we would like to include. A wiki page might be the best place to start that, so that after the top level outline is done, details can be filled in. May I add you to @bokeh/dev so that you can edit pages on the Wiki?

**Comment by samcoh** [comment]
@bryevdv Yes that would be great! I can get started on that. The collaborator @chenwil wants to help too!

**Comment by bryevdv** [comment]
Great! It actually looks like the Wiki is publicly editable so in fact you should already be able to make edits to this page:

https://github.com/bokeh/bokeh/wiki/Charts-Hotwo-Collaboration

Please let me know if you run in to any issue. I'd suggest starting with a simple list and then we can make sections for each entry to flesh things out.

**Comment by jbednar** [comment]
The [HoloViews Bokeh Reference Gallery](http://holoviews.org/reference/index.html) might be a good start as a list of things that Bokeh can clearly do (since HoloViews does them using Bokeh) and that represent commonly used plotting concepts.

**Comment by bryevdv** [comment]
Looks like you are able to edit the Wiki, great! Here are some potential other ideas to consider for the list:

* Histogram (uses bars)
* Pie Chart (uses wedge or annular wedge)
* Timeseries (line glyph with a datetime axis)
* Heatmap (rect or possibly quads)
* Images (various image glyphs)
* Area Charts (varea and harea)

**Comment by adamerose** [comment]
> @samcoh While I agree in principle, I think it's worth clarifying terminology. Bokeh is _very much_ centered around the concept vectorizable visual glyphs. I.e. Bokeh has a lot of _shape types_ that you can throw arrays of data at to produce lots of those shapes. These can be used to draw _any_ sort of chart you want (some very easily, some less so). But Bokeh does not have a notion of Schematized Chart Types, e.g. Bar Plot, Histogram, Pie Chart, TimeSeries, Candlestick Plot, etc. Bokeh can _render_ all of these kinds of plots (and there are many examples of each in the docs/examples), but there are not "named" classes or functions for them, so the notion of "Bokeh Name" is not a useful one. Instead, it would be meaningful to talk about _"what glyphs are needed to make this kind of chart"_ (plural because some charts need mulitple glyph types).
> 
> _(As an aside: If you want that kind of very-high-level schematized plotting API, you might consider tools built on top of Bokeh, such as [Holoviews](http://holoviews.org/), [Chartify](https://github.com/spotify/chartify), or [Pandas-Bokeh](https://github.com/PatrikHlobil/Pandas-Bokeh))_
> 
> I don't think it's possible to enumerate "all graphs" that can be drawn with Bokeh, and I also don't think that would be valuable, strictly speaking. E.g. Bokeh can draw [this historical plot by Burtin](https://docs.bokeh.org/en/latest/docs/gallery/burtin.html) but that's mostly just an interesting display of capability, not something anyone else would ever really want to duplicate, or that is worth cluttering such a list with.
> 
> So, I'd propose a "Howto" sort of section. It would have subsections for a curated list of several _common_ Chart types. Each subsection could contain a general description of how this chart type can be made with Bokeh, list all the glyphs that are used for this kind plot, provide a basic example, and link to other relevant sections in the docs. Then, your table idea (which I really like) could become a visual Table of Contents that links to all these subsections at the very top of the page.
> 
> What do you think about this? Also, is this something you are interested to collaborate on?

I think what you said here should be made clear in the docs. As a newcomer to Bokeh I was just trying to make plots, and seeing that it took over 10 lines of code to make a histogram was discouraging. I think most people doing plotting in Python want to make high level plots and not build things from scratch using glyphs, so Bokeh should mention the wrappers for making high level plots.

It looks like Bokeh used to include high level wrappers like this - https://docs.bokeh.org/en/0.10.0/docs/gallery/histograms_chart.html

This looks very useful... why was bokeh.charts removed? Is there any plan to bring that back? It seems like a step backwards to remove that and now all examples I see for Bokeh histograms is calculating bins manually using numpy. As someone who just wants to make good plots as fast as possible I found Plot.ly was much easier to get started with for reasons like this

**Comment by bryevdv** [comment]
> As a newcomer to Bokeh I was just trying to make plots, and seeing that it took over 10 lines of code to make a histogram was discouraging.

Discounting imports, which any library will have, It takes three lines to make a histogram:
```
hist, edges = np.histogram(data, density=True, bins=50)
p = figure()
p.quad(top=hist, bottom=0, left=edges[:-1], right=edges[1:], line_color="white")
```

>  think most people doing plotting in Python want to make high level plots and not build things from scratch using glyphs, so Bokeh should mention the wrappers for making high level plots.

It does, there is an entire chapter in the User's Guide dedicated to [Exploring Other Tools](https://docs.bokeh.org/en/latest/docs/user_guide/compat.html) built on Bokeh. If you'd like to make a PR contribution to expand or improve that section your effort would be appreciated. 

Also, respectfully, I have now responded to  thousands of user questions of the years, and can easily state that people use bokeh for a wide variety or reasons: some want the streaming capabilities, some want the efficient binary array transport for large images, many actually *prefer* verbosity and control, even the point of preferring the *extremely* low level `bokeh.models` API. Extrapolating from one person's personal preferences to "what most users" want is pure speculation. 

> This looks very useful... why was bokeh.charts removed? 

There was no ability to maintain it. Developer time in volunteer OSS (or even funded OSS) is not an infinite resource, and sometimes decisions have to be made about what gets left on the cutting room floor. This was one of those times. 

Additionally, `bokeh.charts` was a bit of a muddle, which comes down to me. A high level API like that really requires a strong vision and opinions in order to make the right trade-offs between ease of use and sacrificing flexibility. I don't really have those opinions (I'm not a data science practitioner, personally) and at the time my attention was widely split and I could not give the attention needed to direct the `bokeh.charts` work successfully. 

>  Is there any plan to bring that back?

The current core team has no plans, for the primary reason that these days, other project like the ones you linked exist and fill that niche. 

That said, if someone with a strong vision wanted to contribute an opinionated higher level API component to Bokeh, we could consider it, as long as the person was joining the core team and not dropping a PR and disappearing. A real commitment to the Bokeh community for continued support of the new API is a primary requirement to consider something. Specifically it would need to be someone who could either bring in dedicated funding for the work over some period of time, or bring in additional collaborators with them to spread out the burden, or both. 

> As someone who just wants to make good plots as fast as possible I found Plot.ly was much easier to get started with for reasons like this

No one tool can be all things to all users. If another tool fits your preferences and use-case better, then there's no reason not to use it.

**Comment by adamerose** [comment]
@bryevdv Thanks for the response. I guess I was misunderstanding the priorities of Bokeh because I've seen it compared to Plot.ly more often than to low level things like D3, and because I saw the old bokeh.charts API. Looking at the docs again I don't think they are unclear, I just came in with some wrong assumptions.

I guess I should really be comparing EDA solutions like Plotly/Altair/Seaborn/etc. to HoloViews or Chartify instead of Bokeh.

**Comment by bryevdv** [comment]
> Seems like I should really be comparing EDA solutions like Plotly/Altair/Seaborn/etc. to HoloViews or Chartify instead of Bokeh.

I think this is a very reasonable assessment.  People can and do use Bokeh for EDA in notebooks but whether any individual does that is really up to a matter of personal taste. There are definitely higher level, more opinionated tools that are custom-created with an eye towards EDA  (Chartify, Holoviews), that are therefore potentially more compelling for the EDA use case. 

FWIW I don't consider Bokeh "low level" (explicit drawing on a canvas with a vector API and manual scale transformations is low level) but of course these labels boil down to POV.

**Comment by bryevdv** [comment]
This was a nice discussion but I will close the issue due to lack of activity.
