### ISSUE TITLE
[FEATURE] BokehJS embed_item should return a reference to the plot. 

### ISSUE THREAD

**Issue by shughes-uk** [bokeh/bokeh#9524]
Bokeh.embed.embed_item currently returns nothing. I propose it should return a reference to the plot object so I don't have to go fishing (Bokeh.index[plotData.root_id]) in Bokeh.index to do things like call resize_layout() manually.

Honestly any sort of 'official' method for doing this would be super useful.

**Comment by bryevdv** [comment]
This seems reasonable to me, as well as simple to implement.

**Comment by mattpap** [comment]
In fact I did this in PR #9499, by turning `embed_item()` and `embed_items()` in to async functions, but had to backtrack. Using async functions alone was insufficient to keep the semantics intact. Those functions were designed to create a pause between loading bokehjs and initializing an object graph, specifically to allow a full GC. There are two options. Either move the logic elsewhere or make `defer()` function return a `Promise`. I put defer logic in those two functions on purpose, so that we don't have to remember about this on each use site, complicating already complex templates, so the former isn't a good option. I will see if the later maintains the required semantics.
