### ISSUE TITLE
Building Sphinx documentation fails when GOOGLE_API_KEY not set

### ISSUE THREAD

**Issue by UsabilityEtc** [bokeh/bokeh#9528]
When I try to build the Sphinx documentation with, e.g.

`make html`

if the `GOOGLE_API_KEY` environment variable is not set the build fails with the following error:

`
The GOOGLE_API_KEY environment variable is not set. Set GOOGLE_API_KEY to a valid API key, or set bokeh_missing_google_api_key_ok=True in conf.py to build anyway (with broken GMaps)
`

The notes for [Release 0.12.16](https://github.com/bokeh/bokeh/blob/master/sphinx/source/docs/releases/0.12.16.rst#bokeh_docs_missing_api_key_ok-environment-variable) about `GOOGLE_API_KEY` say:

> Now, builds will succeed by default, even witout a Google API key defined (but Google Maps plots will not fully render).

However, when `GOOGLE_API_KEY` is not set, building the documentation fails with the above error.

> To require an API be defined (i.e. to restore the previous behavior) you can now set bokeh_missing_google_api_key_ok = False in the Sphinx config file.

This seems to imply that `bokeh_missing_google_api_key_ok` should be `True` by default if builds should succeed by default when `GOOGLE_API_KEY` is not set. In [conf.py](https://github.com/bokeh/bokeh/blob/85e34b5dc425808a9aadc69425c2680e6e850821/sphinx/source/conf.py#L67), the value of `bokeh_missing_google_api_key_ok` is `False`.

Any help to understand this would be great.

**Comment by bryevdv** [comment]
@UsabilityEtc I suppose I can see how that statement is confusing. People use `:bokeh-plot:` in their own docs (i.e. outside the Bokeh documentation), and that statement pertains to that *general case*. i.e. if you use `:bokeh-plot:` in your own docs, and don't configure anything, then things will succeed, even without at Google API key provided.

However the Bokeh docs themselves, are a *specific case*, and we explicitly and purposefully configure them so they *do fail* if no key is provided. That is because, *for the project itself*, publishing without an API key means publishing broken docs. We don't want to publish broken docs, so we test docs-building with the strict setting turned on specifically to avoid that risk. 

That's not we would want to change, so the the simplest "workaround" for building the Bokeh docs locally would be just to set `GOOGLE_API_KEY="junk"`.

**Comment by UsabilityEtc** [comment]
@bryevdv Thank you for taking the time to explain this 👍
