### ISSUE TITLE
[TASK] Coverage tool breaking change affects Bokeh tests

### ISSUE THREAD

**Issue by jdlesage** [bokeh/bokeh#9533]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### Description of expected behavior and the observed behavior

One utility function of bokeh creates a fake python file called fakesource. This one is not associated to a file on disk and makes the tool coverage to break in report.
The fix is quite easy... `fakesource` should be in angle brackets to be ignored by converage. It has been discussed in a coverage issue: https://github.com/nedbat/coveragepy/issues/898

#### Complete, minimal, self-contained example code that reproduces the issue
Run coverage report on some code that uses bokeh

**Comment by bryevdv** [comment]
@jdlesage Thanks for the catch and the fix! While you are here I would like to see if you have suggestions for another coverage issue. We recently split the tests out from the code into a single completely separate `tests` directory (i.e. instead of lots of `tests` subdirs in with the source). Since doing this, the coverage report is erroneously sill including coverage from files in the source tree as well as from the conda test env install. Do you have any ideas what might cause that?
