### ISSUE TITLE
Trouble getting selection to work on quads

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#964]
I am using quads to represent a histogram.  I build up a datasource where each point has
`x, y, top, bottom, left, right`.  `top, bottom, left, right` are used to plot a histogram. `x,y` are used to plot a scatter in a separate plot.  When I use the select tool in the scatter plot window, the correct histogram bars show up as selected/non_selected.  However, I cannot seem to cause any quad in the histogram window to be selected.

**Comment by birdsarah** [comment]
(want to see if this is still an issue)

**Comment by bryevdv** [comment]
See https://github.com/bokeh/bokeh/pull/2689/files#r36428414 for more info. Selection does not work if the data is inconsisten, i.e., if `left` is not actually less than `right`.

**Comment by bryevdv** [comment]
So question is: what to do in that case? error at serialization? warning? try to "fix up" the data at render time (can certainly do that)

**Comment by birdsarah** [comment]
Confirmed that when hover works, selection works as part of #2689.

I think error (or warning) at serialization would be good.

**Comment by birdsarah** [comment]
I should add that I prefer warning than trying to "fix up" data because:
- I think users may want to do wild things and we should let them do so at their own risk
- it sounds like the kind of feature that would be hard to debug and would surprise people

**Comment by nathanielatom** [comment]
I'm having trouble selecting quads using box select, lasso select, and poly select. 
With `left=[0, 2], top=[1, 2], bottom=[0, 0], right=[1, 3]`, these selection tools don't seem to do anything, even when an entire quad is highlighted. However, tap select still works.

Part of the reason I wanted to use quads instead of rects is because I noticed that rect selection is based on the centre of the rect glyph. Is this the same for quads? If possible, I would like to change the selection behaviour / policy such that any glyph that is even partially highlighted (say only a couple pixels on the edge of the glyph) gets selected.

**Comment by bryevdv** [comment]
`Quad` only currently supports point selection currently (i.e. tap or click events). It's always been unclear to me what the semantics of area selection with quads should be. If you are suggesting that "partial intersection" is a good criteria for when a quad should be considered "hit" for hit-testing purposes, that's a useful data point. Do you have any other information about how other systems handle area selection with things like quads? 

Would you be interested in helping work up a PR? It's a matter of adding one or two function `_hit_poly` and `_hit_rect` to the BokehJS implementation of `Quad` that would perform the geometry intersection test.
