### ISSUE TITLE
ResetTool don't reset to initial extra_y_ranges[i].start  and extra_y_ranges[i].end

### ISSUE THREAD

**Issue by aegr82** [bokeh/bokeh#9677]
I don't know how to reset to initial values of, for example, extra_y_ranges[i].start  and extra_y_ranges[i].end. Both ResetTool and UndoTool reset only x_range and y_range, but they don't reset to initial extra_x_ranges or extra_y_ranges.

**Comment by bryevdv** [comment]
@aegr82 Please supply a *minimal reproducing example*

**Comment by aegr82** [comment]
from bokeh.plotting import figure
from bokeh.models import BoxZoomTool, ResetTool, PanTool, LinearAxis, Range1d

plot = figure(title = "Time Serie", x_axis_type = 'datetime')
plot.line('x', 'y1', source=data, alpha=0.8, line_width = 2, color = 'green')
plot.extra_y_ranges = {'1': Range1d(start = 0, end = 1)}
plot.add_layout(LinearAxis(y_range_name='1'), 'right')
plot.line('x', 'y2', source=data, alpha=0.8, line_width = 2, color = 'orange', y_range_name='1')

plot.x_range.start = min(values[x])
plot.x_range.end = max(values[x])
plot.y_range.start = min(values[y1])*0.95 if min(values[y1]) > 0 else min(values[y1])*1.05
plot.y_range.end = max(values[y1])*1.05 if max(values[y1]) > 0 else max(values[y1])*0.95
plot.extra_y_ranges['1'].start = min(values[y2])*0.95 if min(values[y2]) > 0 else min(values[y2])*1.05
plot.extra_y_ranges['1'].end = max(values[y2])*1.05 if max(values[y2]) > 0 else max(values[y2])*0.95

plot.tools = [BoxZoomTool(), ResetTool(), PanTool()]
...

**Comment by xavArtley** [comment]
I don't see the problem (bokeh master)
![Peek 16-02-2020 18-36](https://user-images.githubusercontent.com/18531147/74609540-41d16500-50eb-11ea-91a0-31f13036713b.gif)

**Comment by bryevdv** [comment]
@aegr82 please also provide the requested version info in the issue template, and also describe the steps to reproduce in more detail.

**Comment by aegr82** [comment]
Ok, but sometimes in my data the y_axis values range from 500 to 800 and in those cases the ResetTool fails.

**Comment by aegr82** [comment]
PLease, prove with

'y2': np.random.rand(500, 800)}

**Comment by xavArtley** [comment]
![Peek 16-02-2020 18-46](https://user-images.githubusercontent.com/18531147/74609679-af31c580-50ec-11ea-899c-f479d301a8d1.gif)

**Comment by bryevdv** [comment]
@aegr82 I don't mean to seem short. But you are not making it easy for us to help you. The issue template listed *all the information* we need to be able to investigate something. Yet you deleted the template, an d just wrote a single sentence? I am asking sincerely, canyon explain why you did that? It's very frustrating when users do that, because we *do* very much want help and fix any problems, but ignoring the issue template only makes that difficult/impossible. I'd like to understand what we can do to help users understand that OSS is a collaboration, and they have a part to play (e.g. filling out the template completely). 

EDIT: 

```
PLease, prove with

'y2': np.random.rand(500, 800)}
```
I mean this in the kindest way possible: This task (providing a **complete, minimal, resproducer**, i.e. that can be run with *no modification whatsoever* to reproduce the issues, is *you job*.

**Comment by bryevdv** [comment]
OK, so I guess you must have chose the "Custom" issue template? In which case that does not list the things we need, but is also not for support questions, and does clearly state that. Still, I think I am going to delete the "Custom" template so that all users only see a complete feature or bug template. There is really no reason for normal users to use "Custom" and it seems to only cause problems. 


As for this issue, given @xavArtley demonstrations, I am going to close as `invalid`. If you can provide a ***complete*** MRE and details instructions to reproduce a problem as well as all relevant version info, we could consider re-opening. Otherwise, for further support/usage questions, the appropriate venue is the Project Discourse:

https://discourse.bokeh.org/

**Comment by aegr82** [comment]
Oh, thank you very much. The issue is that my program is big, with several layouts and interactions, I don't know how to properly present a minimal example. In my program, the 'y2' edge doesn't reset to [500-800] interval, but in this example it does. I will try to do a better understandable example. Sorry if I caused any discomfort, I appreciate a lot your work.

**Comment by bryevdv** [comment]
@aegr82 Thank you for the kind words, we are happy to re-open any time the issue can be reliably reproduced (we can only investigate things that can be reproduced, this its where your help is critical)

**Comment by bryevdv** [comment]
@aegr82 also, my apologies for assuming you had deleted the template. I have opened a PR that removes the "Custom" template which should help reduce this confusion in the future.

**Comment by aegr82** [comment]
Sincerely, I don't understand anything, hehe.
