### ISSUE TITLE
[FEATURE] improve bokehjs dependency and project management 

### ISSUE THREAD

**Issue by sethkaufee** [bokeh/bokeh#9750]
**Is your feature request related to a problem? Please describe.**
Our team currently is using Bokehjs within a webpack/React project (the es module update is much appreciated!). The issue we had initially was that some of the internal dependencies get pulled via git, i.e. canvas2svg, which breaks due to the fact that alpine images don't have git pre installed. We install git now on our build now and everything works fine, but it seemed to be a unique issue that I haven't seen in other projects. 
The packages I am referring to are:
    - canvas2svg
    - gloo2
    - numbro
    - slickgrid
    - timezone

**Describe the solution you'd like**
I think there would be a lot of benefit managing the npm packages within a [Lerna](https://lerna.js.org/) project (or similar) and publishing them under @bokehjs/ on npm. This could be in a separate repo or in the bokehjs subdirectory itself which would be ideal for linking packages although does add additional project bloat. 

It's pretty easy to import/migrate packages with their git history into one project, so at the very least, this would consolidate some not so frequently update packages and makes it easier to develop, version and publish with little effort to setup.

**Describe alternatives you've considered**
Install git on images and everyone keeps doing what they love. 

**Additional context**
There would be a lot of ways to set this up or approach this, but just wanted to gauge the interest level. 

Thanks!

**Comment by bryevdv** [comment]
@sethkaufee I agree 100% that we need to continue to work to make BokehJS easily usable but everyday JS devs using standard JS dev tools and workflows. (That's not me yet BTW I still have lots to learn on the JS side).  A few notes about the packages:

- canvas2svg - we could/should split this into a separate bokeh-svg.js bundle perhaps. It's only used when rendering SVG

- gloo2 - This should not be need if you are not loading bokehl-gl.js (and will some day longer term probably go away)

- numbro - this is used fairly widely, though it would be better if we didn't need a fork of it. Not sure what the current status is, perhaps we can work towards using the standard package instead of our fork 

- slickgrid - This is only needed if you are using bokeh-tables.js for `DataTable` support (quite possible just and FYI in case not)

- timezone - not sure why we have forked this

@mattpap any comments you have would be appreciated. Can we make it a short-term priority to publish our versions of these under `@bokehjs`? They done change much AFAIK so it seems like a low expenditure of effort that will be helpful to lower the bar for BokehJS adoption.

**Comment by mattpap** [comment]
The simplest solution is to publish those dependencies under `@bokeh` namespace, as proposed in #7512. Similar request was made in #9447.

**Comment by mattpap** [comment]
> timezone - not sure why we have forked this

Issues with ESM support (don't remember exactly why; may have been obsoleted by later work) and typing.

**Comment by bryevdv** [comment]
@sethkaufee If I get you access to the forked repos can you get them updated to publish to NPM, then I can quickly publish as soon as they are ready.
