### ISSUE TITLE
[FEATURE] Compose Bokeh server with other Tornado HTTP Servers

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#9813]
So I have an application that has a tornado.web.HTTPServer .  I would love to run my Bokeh application on this web server, rather than have two different servers running on two different ports.

Currently Bokeh creates a Tornado HTTPServer within the `bokeh.server.server.Server` class, which takes in a set of `http_server_kwargs`, and then makes it's own server.  It would be swell if it could optionally take in a running tornado HTTPServer.

But wait!  There is this BaseServer class which seems to do exactly this:

```python
class BaseServer:
    def __init__(self, io_loop, tornado_app, http_server):
```

So now I'm wondering if using that class instead is a reasonable approach.  It looks like there is some other non-trivial setup in `Server.__init__` (binding sockets and whatnot) as well as some other properties like index, prefix, address, and port.  Some of these properties seem to be used upstream within BaseServer (such as `BaseServer.show`).  Should they be moved up to that class?

To be even more opinionated, I could imagine a future where there was just one class, call it `BaseServer` for now, and a function `Server` which included the logic within `Server.__init__`.  That's probably no longer possible today (presumably many people have `isinstance(foo, bokeh.server.server.Server)` calls in code, but maybe it provides motivation to move some functionality around, like the properties currently on Server.

**Comment by bryevdv** [comment]
@mrocklin If there are things that would be helpful to push down in to `BaseServer` I think that would be fine (since presumably the `Server` API would not need to change, just the internals, to forward any such arguments further down to `BaseServer`) IIRC there are probably some things that can't get pushed down, but probably mostly things relate to coordinating the `HTTPServer` that gets created, which you are not interested in. 

Would you like to contribute a PR for this? Being closest to your own requirements, I think a PR from you is the most efficient way to ensure that those requirements get met.

**Comment by mrocklin** [comment]
Yeah, I'm not averse to doing the work myself here.  Thanks for giving
general clearance.
