### ISSUE TITLE
Bar chart is not documented

### ISSUE THREAD

**Issue by aterrel** [bokeh/bokeh#983]
Bar chart isn't documented in either the bokeh charts page: http://bokeh.pydata.org/docs/user_guide.html#bokeh-charts  

or in code:

```
In [3]: Bar?
Type:            type
String form:     <class 'bokeh.charts.bar.Bar'>
File:            /Users/aterrel/workspace/apps/anaconda/miniconda-3.5.5/lib/python2.7/site-packages/bokeh/charts/bar.py
Init definition: Bar(self, value, cat=None, stacked=False, title=None, xlabel=None, ylabel=None, legend=False, xscale='categorical', yscale='linear', width=800, height=600, tools=True, filename=False, server=False, notebook=False)
Docstring:       <no docstring>
```

**Comment by Devataa** [comment]
There is no way I can overlay a line graph over the stacked bar graph using .extra_y_range as found in Figure is there?

**Comment by damianavila** [comment]
Currently, bokeh.charts is being refactored (#1735) to make it inherit from the Plot object which, in turn, will give us the feature you are requesting easy to do...

**Comment by fpliger** [comment]
There is a hacky way to do this now but I'd recommend you to way for 0.8 if you can as this is going to change completely. That said, the following example that combines `Line`, `Step`, `Scatter` and `Bar` charts should work (with a small change due to recent changes on master branch.. see my comment on bottom):

```Python
from __future__ import print_function
from collections import OrderedDict

from bokeh.charts import Step, Line, Scatter, Bar
from bokeh.charts.utils import Figure

xyvalues = OrderedDict(
    python=[2, 3, 7, 5, 26, 81, 44, 93, 94, 105, 66, 67, 90, 83],
    pypy=[12, 20, 47, 15, 126, 121, 144, 333, 354, 225, 276, 287, 270, 230],
    jython=[22, 43, 70, 75, 76, 101, 114, 123, 194, 215, 201, 227, 139, 160],
)
sxyvalues = OrderedDict()
for k, v in xyvalues.items():
    sxyvalues[k] = [(float(x), float(y)) for x, y in enumerate(v)]

tools = "pan,wheel_zoom,box_zoom,reset,save,box_select,lasso_select"
step = Step(xyvalues, width=600, height=600, title="Steps", ylabel='measures', tools=tools)
step.xlabel('time').legend("top_left")
sca = Scatter(sxyvalues, width=600, height=600, title="Steps", ylabel='measures',tools=tools)
sca.xlabel('time').legend("top_left")
line = Line(xyvalues, width=600, height=600, title="Steps", ylabel='measures',tools=tools)
line.xlabel('time').legend("top_left")
hist = Bar(xyvalues, width=600, height=600, title="Steps", ylabel='measures',tools=tools)

ovf = Figure(sca, line, step, hist, title="MIXED!", filename="steps.html")
ovf.show()
```

You may have an error because of Document missing hold method. because of recent changes. If so, you need to comment that single line of code.

I'm passing this solution mostly to say that it is *possible* but I highly discourage doing this. Unless it's really impossible to wait I'd invite you to wait for the next 0.8 release.

**Comment by Devataa** [comment]
@fpliger Thank you so much! This is exactly what I needed. Needed to do a mock up quickly to show a proof of concept so to incorporate Bokeh tool into our analytics team, this did it. Can't wait for the update.

**Comment by Devataa** [comment]
@fpliger For a stacked bar graph plotted with a line graph as you've demonstrated above, is it possible to incorporate dual axis on the right hand side corresponding to the line graph range? Somewhat similar to this demo here; https://github.com/bokeh/bokeh/blob/master/examples/glyphs/twin_axis.py ?

**Comment by fpliger** [comment]
@Devataa Sure. In that case you need to used the Plot object shared between all the charts. In order to make if work with the previous example please add `from bokeh.models import Range1d, LinearAxis` to the top of your file and change:

```Python
ovf = Figure(sca, line, step, hist, title="MIXED!", filename="steps.html")
ovf.show()
```

with

```Python
ovf = Figure(sca, line, step, hist, title="MIXED!", filename="steps.html")
p = ovf.doc._current_plot
p.extra_y_ranges = {"foo": Range1d(start=0, end=100)}
p.add_layout(LinearAxis(y_range_name="foo"), 'left')
ovf.show()
```

Once again I'd like to remember that all this will be changing really soon! :wink:
