### ISSUE TITLE
Hover tool question.

### ISSUE THREAD

**Issue by cheremovsky** [bokeh/bokeh#984]
Hi.
It is not clear why the hover tool does not work in the following example.
Could you say, what's wrong with it?

```
output_notebook()
TOOLS="pan,wheel_zoom,box_zoom,reset,previewsave,hover"
source = ColumnDataSource(
    data=dict(
        x=np.array(AAPL['date'], 'M64'),
        y=AAPL['adj_close']
    )
)
line(np.array(AAPL['date'], 'M64'), AAPL['adj_close'], color='#A6CEE3', legend='AAPL', source=source,tools=TOOLS)
hover = [t for t in curplot().tools if isinstance(t, HoverTool)][0]
hover.tooltips = OrderedDict([
    ("(x,y)", "($x, $y)")
])
show()
```

Is it a good place for such questions, or I may ask somewhere else?
Thank you.

**Comment by HackerMD** [comment]
I ended up here because I would like to use the hover tool for images. Is there any progress in this direction? Or could you provide any tips on how I could implement this functionality myself? I've adapted the [unemployment example](http://bokeh.pydata.org/en/latest/docs/gallery/unemployment.html), but it doesn't work for large images and is therefore not an option.

Another problem I ran into is the use of color palettes for display of images. I would like to display a 8-bit image in form of a numpy array of type *uint8*. Any suggestions?

**Comment by HackerMD** [comment]
Found a temporary solution for the color palettes in another [issue](https://github.com/bokeh/bokeh/issues/2426)

**Comment by birdsarah** [comment]
This doesn't solve your problem, but a hack would be to add
invisible glyphs (square markers, circles, whatever) on the same plot
and attach a hovertool to them.

One thing that's worth noting is that bokeh's hovertool may give you
some problems if you have lots of points that you're trying to hover
over. It destroys and creates a DOM element every time you are hovering
over a new point so can get sluggish. This may not affect you, but just
something to know.

**Comment by HackerMD** [comment]
Thank you for your feedback! My images are pretty big so that I anticipate problems with the number of points. Since the image data is simply stored as an array I thought it should be straight forward to read out the values from the plot object!? For now I will try to do this on the client side via the generated canvas element.
