### ISSUE TITLE
Loosen extension compiler checks?

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9842]
I was answering a user question and reworked a (now-nonfunctional) old answer to work:
```javascipt
import {CategoricalTicker, FactorTickSpec} from "models/tickers/categorical_ticker"
import {FactorRange} from "models/ranges/factor_range"

export class MyTicker extends CategoricalTicker {

  get_ticks(start: number, end: number, range: FactorRange, cross_loc: any, _: any): FactorTickSpec {
    const ticks = super.get_ticks(start, end, range, cross_loc, _)

    function filt(_: any, index: number, __: any) {
      return (index % 2 == 0)
    }
    ticks.major = ticks.major.filter(filt)

    return ticks
  }
}
```

@mattpap I want to call your attention to this in particular:
```
function filt(_: any, index: number, __: any) 
```
If you look up any exampel of writing a filter on google, it would just be:
```
function filt(_, index, __) 
```
But if we try that with Bokeh the compiler puke about implicit anys. I propose for compiling extensions that we turn off the flag that bails on implicit anys for extension compilation, and perhaps a few others. The bar for creating Bokeh extensions has risen ***astronomically*** high for average users, to the point that I basically don't even mention the possibility in many instances where I otherwise might think it provides a solution.  For us, as library developers, the settings should be as stringent and strict as possible. *For users* to make things as simple, easy, quick, painless as feasible, the settings should be as *lax* as possible,. 

As an aside, I'd really prefer to have this sort of conversation off GitHub, so I'd encourage you join the Zulip chat.

**Comment by mattpap** [comment]
Extensions can be written in JavaScript as well, which is what I would suggest to use, if someone doesn't want type safety. Turning off no implicit any turns TypeScript into JavaScript, and is a really harmful thing to do if you actually intend to write TypeScript. Note that JavaScript is still compiled in both extensions' compilers, so one gets syntax checking, module resolution, transpilation to older ES versions, etc., just no type checking at all.

TypeScript requires standalone functions to have all arguments typed. This can be worked around by defining a function at the call site and taking advantage of type inference, like this:
```ts
ticks.major = ticks.major.filter((_value, index) => index % 2 == 0)
```
(one can do the same with `function (...) { ... }` syntax, it's just more verbose).

The new extensions' compiler allows users to provide their own `tsconfig.json`, so one can relax the type safety settings and change other things as well. However, providing such configuration isn't that easy, especially for someone who would be complaining about extension's code in the first place. What I can do is to allow users to override tsc settings in both compilers.

Ultimately I think that the underlying problem isn't type safety or not, but the fact that users are forced to write JavaScript/TypeScript, or extensions in particular, but `CustomJS` is another offender, to achieve trivial functionality like the filter function. Extensions weren't meant for the average user, but for people who need to provide unique, reusable functionality for other users, that is otherwise not provided by bokeh, and those will know better how to write this kind of code. Similarly `CustomJS` was supposed to be a relief mechanism, but was turned into the default way of interacting with data, writing callbacks, etc.

Then you have users that copied some code from our examples, code which almost certainly they don't understand, then they modified it a bit, or maybe copied some more code from stackoverflow or so, and then there's a problem because the compiler will inevitably complain and the user will have little to no idea what to do about this. Typically dynamic typing is the answer, because one can easily ignore soundness of the implementation. That being said, let's make it clear that I'm not dissing on users here, but I'm appalled by the state of this project and what it offers to its users. It's one of many great failing of this project, that any deviation from the default path forces users to use low-level tools, that normally they shouldn't be touching, but they have no other choice in bokeh. It's a binary system in which either everything works great or one has to write an extension to filter out factors. There's no middle ground.

**Comment by mattpap** [comment]
> As an aside, I'd really prefer to have this sort of conversation off GitHub, so I'd encourage you join the Zulip chat.

GitHub is exactly the right place for this kind of discussion, because it's an important and open one, and actually a discussion and not a chat. It also needs to be preserved, so that in some time, possibly years, people will be able to figure out why we ended up with bokeh that we ended up. The only historically reliable place to preserve such discussions is the repository, either in the issue tracker, PRs or the version controlled wiki. Anything else is a liability and good path towards either eventually or immediately (e.g. private E-mails) erasing valuable information. You can use a chat for issues that intrinsically require immediate back and forth, but any conclusions of value must be preserved in the repository. Additionally I'm not going to search multiple places to get answers I need. The only exception are private discussions, which unfortunately can't happen on GitHub. Though in that case discourse would be a preferred choice over a chat.

**Comment by bryevdv** [comment]
> GitHub is exactly the right place for this kind of discussion, because it's an important and open one, and actually a discussion and not a chat

This ignores human concerns. Namely that I would sometimes just like to have a casual, exploratory conversation to hopefully learn from each other and inform our opinions, before getting to the point of long drawn out GH discussions, which I do not always have the stamina or desire for. Case in point. 

> I'm appalled by the state of this project and what it offers to its users.

I don't really have a response to this. There will always be many improvements to make but OSS is about what is possible *given available resources*, and the evidence of the utility this project affords is in the CDN logs. You ever make perfect the enemy of good. I'll just say that if you are appalled by this project I would not object if you wanted to step away from it.

**Comment by peekxc** [comment]
> The new extensions' compiler allows users to provide their own tsconfig.json, so one can relax the type safety settings and change other things as well. 

This seems false, Bokeh ignore any changes I make to the local tsconfig.json

> However, providing such configuration isn't that easy, especially for someone who would be complaining about extension's code in the first place. What I can do is to allow users to override tsc settings in both compilers.

Great.... how do you do this, if not though tsconfig?
