### ISSUE TITLE
categorical slider

### ISSUE THREAD

**Issue by Dr-Nuke** [bokeh/bokeh#9843]
Similarly to the Dash slider (https://dash.plotly.com/dash-core-components/slider)
add a categorical (or ordinal) slider that allows to specify
1) values (e.g. values=[0,1,2,3]) and
2) labels (e.g. labels=['yearly','quarterly','monthly','weekly'])
that are both accessible from within the callback function.

The functionality is similar to a radio button group, but can be optically more pleasing.
![image](https://user-images.githubusercontent.com/56429408/77849066-24eb7f80-71c9-11ea-990b-9a680af3793c.png)

**Comment by mattpap** [comment]
This is doable, the internal implementation already allows this, it just need to be exposed to the user.

**Comment by Tekaichi** [comment]
Hey, can I work on this or is someone working on it already?
Just to make sure, this categorical slider would be a new class on sliders.py right?

**Comment by bryevdv** [comment]
> Just to make sure, this categorical slider would be a new class on sliders.py right?

That is part of it, but to be clear about what is involved, most of the work would actually be in TypeScript on the BokehJS side.

**Comment by Tekaichi** [comment]
A Categorical slider would simply by a slider with step 1, if we map the `values = [...]`  to indexes, each step in the slider would just increase/decrease the index of it. Other than that, each value should be displayed under the slider, so the styling of it would need to be extended/customized as well.

Is this correct or should I approach this differently? Right now I am still studying the code so I might be missing something.

**Comment by Tekaichi** [comment]
I have been reading more of the code and realized that I may not need to adapt a normal range slider and just create a new type of slider instead. 
I am working on this atm.

**Comment by Tekaichi** [comment]
Any feedback on this?

**Comment by bryevdv** [comment]
@Tekaichi Just to set your expectations: OSS is mostly  a volunteer effort, and issue cycles often move slowly. Bokeh is actually on the better end of responsiveness but you should still be prepared for cycle times of days/weeks, not hours.  

A released version of BokehJS does what it does. The only way to make it do new or different things are:

* add a custom extension (this can be done independently by users), or
* commit new changes to the core repo and include them in a new release

It's not clear what you have actually tried to do (in terms of code) so it's not possible to say anything more.

**Comment by Tekaichi** [comment]
I have built bokehjs locally and have been testing on this locally built version. 
Until now, I have added the CategorySlider model in python inside sliders.py and proceeded to create category_slider.ts on bokehjs. Right now category_slider.ts just inherits from abstractslider and I only changed its properties, so I was expecting the category_slider to render as a slider but it does not renders at all due to that "Model not registered" issue.

**Comment by bryevdv** [comment]
Are you actually using the local built BokehJS? By default Bokeh loads BokehJS from CDN, which means you will get the last released version. If you are doing dev you need to set `BOKEH_RESOURCES` accordingly to actually use what you have built locally.

**Comment by bryevdv** [comment]
Perhaps this will be a useful reference:

https://github.com/bokeh/bokeh/pull/9546

That is a single self-contained PR that adds one new widget. It should be representative of the scope of work involved (the BokehJS implementation may be simpler here since there is existing slider base class that might be re-used)

**Comment by Tekaichi** [comment]
> Perhaps this will be a useful reference: #9546
> 
> That is a single self-contained PR that adds one new widget. It should be representative of the scope of work involved (the BokehJS implementation may be simpler here since there is existing slider base class that might be re-used)

Thank you! Will look into that! 

I was doing bokeh serve, and I think it was fetching the last version from CDN as you mentioned and not the locally built one.

**Comment by bryevdv** [comment]
Well, actually Bokeh server does serve resources itself so that should work, assuming you have installed the local BokehJS into the source tree with `python setup.py develop --install-js` (or `--build-js` will build and install). you can look at your browsers network tab to see exactly what BokehJS is getting loaded.

**Comment by andrzejnovak** [comment]
Seems I missed this before opening #10325. Hopefully, this would generalize for RangeSlider as well.

I think that labels should be optional. It would also be cool if the spacing was reflected in the slider e.g. `values = [1,2,3,10,50]` would not appear equidistant in the slider, but "bunched" towards the beginning
