### ISSUE TITLE
Deprecated versions of `@bokeh/bokehjs`

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#9858]
Reviewing existing versions of `@bokeh/bokehjs` I noticed the following:
```
$ npm view @bokeh/bokehjs versions
[ '2.0.0-dev.5', '2.0.0', '2.0.1-rc.2', '2.0.1' ]
$ npm view @bokeh/bokehjs@2.0.0-dev.5 deprecated
this package has been deprecated
$ npm view @bokeh/bokehjs@2.0.0 deprecated
$ npm view @bokeh/bokehjs@2.0.1-rc.2 deprecated
this package has been deprecated
$ npm view @bokeh/bokehjs@2.0.1 deprecated
```
Were those deprecations done intentionally? Either way, this isn't the correct publishing strategy. Those should be undeprecated and retagged using `npm dist-tag`. All future published versions should be tagged at publishing time, using `npm publish --tag TAG_NAME`, where `TAG_NAME` is either `latest`, `rc`, `beta`, `alpha` or `nightly`, or something along this, because only `latest` is really meaningful to npm, because it's the default (and can be skipped in the CLI).

**Comment by bryevdv** [comment]
I deprecated the dev/rc releases in the UI because I was surprised to see them. We have never before published dev or rc versions to NPM, and there has not been any discussion around starting to.

**Comment by mattpap** [comment]
There was a PR https://github.com/bokeh/bokeh/pull/9578 not that long ago enabling dev release publishing. Having published dev releases is critical for any hope of having a decent standalone bokehjs library, especially in the context of other work that depends on it (e.g. `jupyter_bokeh` and `ipywidgets_bokeh`). In fact I will be setting up nightly builds in near future (at last in `future` branch,  but it won't hurt to have this enabled in `master` as well).

**Comment by bryevdv** [comment]
I guess I missed the context, which is why I'd really like to have, and keep asking for, more conversational interpersonal interactions, because that's how my brain is efficient at obtaining context.  My recollection was there was a one-off need to publish a "dev" build to support some downstream testing or something, not that we were starting a whole new process.

In any case, then, there's things that need to be figured out. First and foremost: should npm "beta" version publishing be synced to the build automation for the overall project? Does publishing `bokeh-2.0.2dev3` on Anaconda.org (and CDN) imply an NPM release? I feel like this risks littering NPM with many packages, which may even be identical despite different versions, and also deprives NPM publishing of its own intentionality. But maybe that's not an issue? Alternatively what about having the automation:
* continue to exclude dev builds from NPM 
* start including rc builds to NPM
* intentional. independent BokehJS NPM releases can use "beta"

**Comment by bryevdv** [comment]
Noting decision from call:  Automation will start publishing all versions (dev, rc) to NPM.

**Comment by mattpap** [comment]
This was done in PR #10730. Prerelease packages will be published under `dev` tag.
