### ISSUE TITLE
[FEATURE] Add "dot" marker variants

### ISSUE THREAD

**Issue by BenPortner** [bokeh/bokeh#9863]
Dear bokeh developers,

there are `_cross` versions of `circle`, `square`, and `diamond`. But not for `triangle`. I tried to add a `triangle_cross` marker to my plot and got an error. Is there a particular reason for this and if no, could you add it?

Keep up the good work!
Ben

**Comment by bryevdv** [comment]
@BenPortner Do you have examples of this in other libraries? cross was added to circle, square, and diamond because the obvious symmetry correspondences. (Tho, thinking right now: `diamond_cross` probably should more acurately have been `diamond_plus`)

**Comment by BenPortner** [comment]
@bryevdv I don't know if other libraries implement a `triangle_cross`. It would be nice to have though. I am using transformations to adapt the marker style depending on categorical values in my `ColumnDataSource`. With `marker` and `color`, one can easily create __bivariate__ scatter plots. I was intending to use the `_cross` as workaround to create __trivariate__ scatter plots: marker, color, cross/no cross. A bit like a `factor_hatch` transform for scatter plots. However, right now my workaround only works if one uses less than four markers: `circle`, `square`, and `diamond`. 

Of course, one can always plot multiple markers on top of each other. But this is not supported in the `scatter` convenience function. Instead, one would have to go and manually map column values to (multiple) markers and colors.

**Comment by bryevdv** [comment]
@BenPortner I can't find any evidence of a triangle cross marker in other libraries:

* https://matplotlib.org/api/markers_api.html
* https://plotly.com/python/marker-style/
* https://plotly.com/python/marker-style/

And I am fairly certain the reason for that is that it would be both visually unappealing due to lack of symmetry, but also not efficacious from a vis standpoint. So I am not inclined to forge new ground here. 

Personally, I think trying to encode this much into visual marker appearance makes a plot difficult to read and interpret. Setting aside my own opinions, however, we could consider adopting the "dot" variants that plotly shows. Those have an unambiguous application to circle, square, diamond, triangle, and hexagon. Would that be acceptable? (and would you be interested to work on the issue with some guidance/direction?)

**Comment by BenPortner** [comment]
Sure, the `-dot` variants would work just as well. How much work would you expect this to be? If it's not too much I can give it a try.

**Comment by bryevdv** [comment]
@BenPortner Here is a recent PR that added support for a hexagon marker (including docs and examples):

https://github.com/bokeh/bokeh/pull/7658/files

**Comment by bryevdv** [comment]
@BenPortner I am taking care of this in https://github.com/bokeh/bokeh/pull/9905

**Comment by BenPortner** [comment]
Very nice @bryevdv!!! Love the new markers. Sorry that I didn't get around to doing it myself. I hope I can contribute something to bokeh in the future because I really love it. Keep up the good work, guys!
