### ISSUE TITLE
[BUG] Zoom tools not functioning with Bokeh GmapPlot 

### ISSUE THREAD

**Issue by yannispetro** [bokeh/bokeh#9874]
The only zoom tool that functions with Bokeh GMapPlot is the WheelZoomTool and even that is very slow and non-responsive. BoxZoomTool, ZoomInTool and ZoomOutTool are not working at all. I am using Bokeh 2.0.1, Python 3.7.3, Pandas 0.24.2, Jupyter 4.4.0 on macOS Darwin 18.7.0

Is there any plan to fix this ?

See my code below:

```
from bokeh.resources import INLINE
from bokeh.io import output_notebook
from bokeh.models import ColumnDataSource, GMapOptions
from bokeh.plotting import gmap, show
import os

output_notebook(INLINE)

map_options = GMapOptions(lat=30.2861, lng=-97.7394, map_type="roadmap", zoom=11)

api_key = os.environ['GOOGLE_API_KEY']
p = gmap(api_key, map_options, title="Austin", tools="pan,wheel_zoom,zoom_in,zoom_out,box_zoom,reset")

source = ColumnDataSource( 
data=dict(lat=[ 30.29,  30.20,  30.29], lon=[-97.70, -97.74,-97.78]))

p.circle(x="lon", y="lat", size=15, fill_color="blue", fill_alpha=0.8, source=source)

show(p)
```

Thanks!

**Comment by bryevdv** [comment]
@yannispetro please provide the data needed to run the example.

**Comment by bryevdv** [comment]
Actually a quick look at the code reminds me that these are not supported on gmap plots, because they cannot be supported on gmap plots. Google maps exert strict control over aspect ratio and other things, that we cannot override. The only tools we can support here are pan and zoom. If you want other tools, you should look at using the Bokeh `TileProvider` with a tile source of your choosing, instead of gmap. 

https://docs.bokeh.org/en/latest/docs/user_guide/geo.html#tile-provider-maps

**Comment by yannispetro** [comment]
I see. Thanks!
