### ISSUE TITLE
Remove Explicit Marker Models

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#9910]
This issue is to discuss a potential idea for the Bokeh 3.0 timeframe. Namely, should we remove individual scatter models, e.g. `CircleCross`, `InvertedTriangle`, etc. in favor of only having the single `Scatter` model that is configured via a `MarkerType` enum? This would afford removing all the code for dynamically creating marker classes in BokehJS (time and space improvement) as well as a ton of boilerplate. 

In particular I would like to make it more regular and compact to compose and represent variants:

* `circle`, `circle-dot`, `circle-x`, `circle-cross`, `circle-y`
* `triangle-up`, `triangle-down`, `triangle-left`, `triangle-right`

Some questions:

* keep `Circle` (almost certainly necessary due to `radius`)?
* keep `Figure` marker methods?

I would be in favor of keeping figure methods (but reimplementing in terms of `Scatter`)

cc @bokeh/dev

**Comment by RyanRio** [comment]
Your suggestion makes sense to me - to be clear, you are in favor of keeping `annular_wedge(), annulus(), arc(), etc` on Figure but move things like `circle_cross()` on figure into a marker-type passed into `scatter()`? _Or_ since `circle_cross(), etc` is being rewritten in terms of `Scatter` anyway are you proposing even those stay?

Would `Circle` also be reimplemented in terms of `Scatter` then?

Currently I'm not familiar with how BokehJS dynamically creates marker classes, but I see no downside to simplifying it to a single model.

**Comment by p-himik** [comment]
> configured via a MarkerType enum

It would make it impossible to use `Scatter` for user glyphs. Maybe it can be avoided by using a regular string and just making a check in runtime.

> keep `Circle` (almost certainly necessary due to `radius`)?

Too early to tell, but I feel there should be a reasonable way to implement glyphs that require additional parameters using `Scatter`. It would also be useful to user glyphs that may have parameters.

> keep Figure marker methods?

Absolutely. But only for the built-in scatter glyphs. It's possible to support user glyphs here as well, but I don't think that it would be a good idea.

**Comment by bryevdv** [comment]
> It would make it impossible to use Scatter for user glyphs. Maybe it can be avoided by using a regular string and just making a check in runtime.

I would resolve this by accepting an enum or `CustomJSMarker` marker instance.

> Too early to tell, but I feel there should be a reasonable way to implement glyphs that require additional parameters using Scatter

It's really important that all the markers conform to the same interface. That is what makes them usable completely interchangeably in a marker mapper, e.g

**Comment by p-himik** [comment]
> I would resolve this by accepting an enum or CustomJSMarker marker instance.

Hmm, maybe. Initially, I was thinking about something like `register_user_marker` that a user could call just so that a regular string could be used later. After all, that string could be in a column of a data source, right?

> It's really important that all the markers conform to the same interface

Absolutely. And a solution with custom parameters does not require deviations in the interface. Just a single `extra_args` attribute solves this problem. It makes `Scatter` _much_ more flexible, and all the errors can still be caught in runtime - we don't have to guard against every single possible mistake during the compile time, it's just not feasible.

**Comment by birdsarah** [comment]
I haven’t given this deep thought. Glad others are engaging, but as a first impression I like it. I’ve been playing with other plotting libraries recently and getting a feel for other APIs. This idea seems very normal in that context, and you’ve well articulated the benefits.

**Comment by bryevdv** [comment]
going to go ahead and mark as `task` for `future`. The experience adding less than ten new markers in #9905 has convinced me we have *way* too much overhead around markers.

**Comment by mattpap** [comment]
This was completed in PR #10698. `Circle` and `Scatter` glyph models were kept, as well as all existing marker functions (they now return `Scatter` glyph instances). Marker models were converted to functions (returning `Scatter` glyph instances) and deprecated (to be removed in 3.0). I think we don't need issues for deprecations, so I'm going to close this one.
