### ISSUE TITLE
[BUG] Django server resources are not working

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#9924]
As first reported in https://github.com/holoviz/panel/issues/1205 the Django server integration experienced a regression in Bokeh 2.0.1 when the server resources handling was refactored. We will have to update it to serve the JS and CSS resources correctly when the Resources mode='server'. As a quick fix we can instead make the default mode='cdn' for Django server.

**Comment by philippjfr** [comment]
This is not fixed for me, still seeing this with bokeh 2.0.2rc1:

```
87b1a473-a59a-433e-9084-5a14cf9eec15:89 GET http://localhost:8000/static/extensions/panel/panel.min.js net::ERR_ABORTED 404 (Not Found)
load_libs @ 87b1a473-a59a-433e-9084-5a14cf9eec15:89
(anonymous) @ 87b1a473-a59a-433e-9084-5a14cf9eec15:175
(anonymous) @ 87b1a473-a59a-433e-9084-5a14cf9eec15:180
87b1a473-a59a-433e-9084-5a14cf9eec15:60 failed to load http://localhost:8000/static/extensions/panel/panel.min.js
```

**Comment by philippjfr** [comment]
I see it's meant to get the extension from `bokeh.embed.bundle.extension_dirs` but as far as I can tell that is still empty when `static_extensions` is called.

**Comment by philippjfr** [comment]
Even when I force it to populate `extension_dirs` like this it still doesn't serve panel.min.js correctly:

```
from bokeh.embed.bundle import _bundle_extensions
from bokeh.resources import Resources

_bundle_extensions(None, Resources(mode="server"))
```

**Comment by philippjfr** [comment]
Maybe we should restore my change to switch to CDN by default again?

**Comment by mattpap** [comment]
@philippjfr, can you post code you are testing on?

**Comment by philippjfr** [comment]
I'm testing on https://github.com/holoviz/panel/tree/master/examples/apps/django_multi_apps with a small patch, adding this to urls.py:

```
from bokeh.server.django import static_extensions
urlpatterns += static_extensions()
```

**Comment by mattpap** [comment]
Let's start from removing this line:
```
https://github.com/holoviz/panel/blob/master/examples/apps/django_multi_apps/django_multi_apps/settings.py#L39
```
and use 
```py
from bokeh.server.django import static_extensions
urlpatterns += static_extensions()

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()
```
in urls.py (in that order so that `static/extensions` takes precedence).

**Comment by philippjfr** [comment]
Ah, yes, sorry did that too.

**Comment by mattpap** [comment]
In that case I will need to debug this.

**Comment by philippjfr** [comment]
Okay, sorry changing the order of urlpatterns fixes it, so I needed to do this:

```
from bokeh.server.django import static_extensions
from bokeh.embed.bundle import _bundle_extensions
from bokeh.resources import Resources

_bundle_extensions(None, Resources(mode="server"))
urlpatterns += static_extensions()
urlpatterns += staticfiles_urlpatterns()
```

**Comment by mattpap** [comment]
Though the most important part is removing the middleware from settings. Alternatively you could leave the middleware and prepend `static_extensions()` to `urlpatterns` and remove `staticfiles_urlpatters()` (which is redundant when the middleware is present).

**Comment by mattpap** [comment]
I suppose this can be closed?

**Comment by philippjfr** [comment]
Importing and calling a private function with an obscure signature like `_bundle_extensions` is definitely not ideal.

**Comment by mattpap** [comment]
> `_bundle_extensions(None, Resources(mode="server"))`

I see, I thought this was just for testing.

**Comment by philippjfr** [comment]
Wait I think it might actually be working, very confused why it didn't before but I'll close.

**Comment by mattpap** [comment]
This is still clearly broken:
```
> /home/mateusz/repo/bokeh/bokeh/embed/bundle.py(184)bundle_for_objs_and_resources()
    183         extensions = _bundle_extensions(objs, js_resources)
--> 184         mode = js_resources.mode if resources is not None else "inline"
    185         if mode == "inline":

ipdb> p extensions                                                                                                                               
[ExtensionEmbed(artifact_path='/home/mateusz/repo/panel/panel/dist/panel.min.js', server_url='http://localhost:5006/static/extensions/panel/panel.min.js', cdn_url='https://unpkg.com/@holoviz/panel@^0.9.5/dist/panel.min.js')]
```
when django is running on port 8000. I'm not sure how this I tested it and it "worked".

**Comment by mattpap** [comment]
Actually in in dev mode. Normally it's working OK:
```
ipdb> p extensions                                                                                                                               
[ExtensionEmbed(artifact_path='/home/mateusz/repo/panel/panel/dist/panel.min.js', server_url='http://localhost:8000/static/extensions/panel/panel.min.js', cdn_url='https://unpkg.com/@holoviz/panel@^0.9.5/dist/panel.min.js')]
```

**Comment by philippjfr** [comment]
Yeah, things are working fine for me. @mattpap Should this block the release? I think we're good from my perspective.

**Comment by mattpap** [comment]
> Should this block the release? I think we're good from my perspective.

This doesn't have to block the release, but has to be fixed regardless.

**Comment by bryevdv** [comment]
@mattpap @philippjfr AFAIK this should be `completed` if that is not the case, please re-open with any new information or context.

**Comment by wearpants** [comment]
Can this get reopened?  The current solution (`urlpatterns += static_extensions()`) confuses the heck out of Django static file handling -  it breaks channels' `LiveServerTestCase` very badly, and would not work at all with `collectstatic` + using an external 
 web server like nginx.

Django expects static files to be present on disk at startup time, and the set of static files to be actually static; at present, new directories are functionally added when [autoload.js  is handled](https://github.com/bokeh/bokeh/blob/57da24a50e53c8b97e6efa155272e1a9379a9689/bokeh/server/django/consumers.py#L144) via [_bundle_extensions](https://github.com/bokeh/bokeh/blob/57da24a50e53c8b97e6efa155272e1a9379a9689/bokeh/embed/bundle.py#L233). In nginx case, requests for extension files will never hit Django since they share a URL prefix with the actual `STATIC_URL` (which is served directly by nginx)

I see two options:
1) change the URL prefix for these extension files so that they can be served directly by Django
2) provide a function pointing to the extension files like [bokehjsdir](https://github.com/bokeh/bokeh/blob/57da24a50e53c8b97e6efa155272e1a9379a9689/bokeh/util/paths.py#L47) so that they can be handled through the normal static files mechanisms: `STATICFILES_DIRS = [bokehjsdir()]` 

(2)  is highly  preferably in my opinion, but I admit to not fully understanding  the context here
