### ISSUE TITLE
[BUG] Using the same layout element (here: plot) multiple times

### ISSUE THREAD

**Issue by Dr-Nuke** [bokeh/bokeh#9971]
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh                     2.0.0                    py37_0  
python                    3.7.7           hcf32534_0_cpython 
WSL Ubuntu 18.04 (hosted on win10
Firefox 75.0 (64-bit)
running the app with command `bokeh serve testapp.py --dev`
#### Description of expected behavior and the observed behavior
Using an array of the same plot twice, i.e.
`rows=row( children=[plot1,plot1], width=800)`
does not show the plot twice. Using a deepcopy of plot1 will show the same behavior.
## Expected behavior
![image](https://user-images.githubusercontent.com/56429408/80697318-17335d80-8ad9-11ea-8fe9-032c4ad45299.png)

## Actual behavior
![image](https://user-images.githubusercontent.com/56429408/80697456-41851b00-8ad9-11ea-80a8-44bdcbcc745b.png)

#### Complete, minimal, self-contained example code that reproduces the issue

```
# minimal example for a bokeh dashboard featurigng the same element twice 
# (here: a plot)
from bokeh.io import curdoc
from bokeh.layouts import column, row
from bokeh.plotting import figure

from copy import deepcopy
import numpy as np

# Set up data
x = np.linspace(0, 15, 200)
y = np.sin(x)

# Set up plots
plot1 = figure(plot_height=400, plot_width=400)
plot1.line(x, y,  line_width=3, line_alpha=0.6)
# plot2 = figure(plot_height=400, plot_width=400)
# plot2.line(x, y,  line_width=3, line_alpha=0.6)
# plot2=deepcopy(plot1) # can we just copy the first plot?

# set up the layout
rows=row( children=[plot1,plot1], width=800) # <= use plot 1 & 2 to get the "expected" behavior
curdoc().add_root(rows)
```

#### Stack traceback and/or browser JavaScript console output
no errors

#### Screenshots or screencasts of the bug in action
see above

**Comment by bryevdv** [comment]
@Dr-Nuke This has been explicitly not-supported for a long time. May I ask why you would ever want to put the same plot in a layout twice?

**Comment by Dr-Nuke** [comment]
aha ok explicitly not-supported.
Then I guess it's purely my intuition and idea of object-oriented  programming that wants me to use the same object twice. Maybe the example of a graph is too specific, it could be any (cosmetic) object on a dashboard

**Comment by mattpap** [comment]
The technical reason for this not being supported is that the mapping between a model's view and its children, is a simple `model.id` -> model view mapping. So e.g. `Row.children` can't have duplicated entries, though it should at least warn you about it. However, you can work around this by nesting a layout like this:
```py
from bokeh.io import save
from bokeh.plotting import figure
from bokeh.layouts import column, row

import numpy as np

x = np.linspace(0, 15, 200)
y = np.sin(x)

plot1 = figure(plot_height=400, plot_width=400)
plot1.line(x, y,  line_width=3, line_alpha=0.6)
r = row([plot1, row([plot1])])
save(r)
```
This will actually show two plots. However, by reusing the same model and all its referenced models, you are effectively linking those two plots. This results in e.g. panning one plot would pan the other one as well. I doubt this is the expected behavior.

If you have two very similar plots and you would like to save yourself some typing, then the best option would be do deep clone a model, but that's not supported currently. The most reliable alternative, that we use all across our documentation and examples, is to wrap code that produces a plot in a function, and the modify the results to the specific needs.

**Comment by mattpap** [comment]
> `# plot2=deepcopy(plot1) # can we just copy the first plot?`

Unfortunately `deepcopy()` would copy the identity of all involved models, so you would be back to square one, if it can copy bokeh's models reliably at all.

**Comment by mattpap** [comment]
I will consider this as a bug, because you should be at least warned (preferably an exception should be throwed) that duplicated entries are prohibited.

**Comment by Dr-Nuke** [comment]
I think a warning/ exception makes sense. Would have prevented me from going this far :)
I also understand why the `deepcopy` would not help.
nice workaround though!

**Comment by bryevdv** [comment]
I do think adding a `.clone` API to create copies (with new model ids) would be reasonable and useful
